SELECT 
MTRF.CODCOLIGADA,
MTRF.IDTRF, 
MTRF.IDPRJ,
ISNULL (MTRF.IDCMP,0) AS IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MCMP.CODCMP,
/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER O CODIGO DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.CODTRF 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODISM FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODCMP FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODIGO,
	 
MTRF.NOME,

/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER A UNIDADE DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN ' '  
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODUND FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODUND FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODUND,
	 
	 
convert(decimal(18,4),ISNULL (MTRF.QUANTIDADE  ,1)) AS QUANTIDADE,
	 
	 
/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER O VALOR DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.VALORTOTAL 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT VALOR FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT VALORTOTAL FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS PRECO
	 

FROM MTRF (NOLOCK)
INNER JOIN MCMP (NOLOCK) ON (MTRF.CODCOLIGADA = MCMP.CODCOLIGADA AND MTRF.IDCMP = MCMP.IDCMP AND MTRF.IDPRJ = MCMP.IDPRJ)

WHERE MTRF.IDPRJ = 
(SELECT IDPRJ FROM MPRJ (NOLOCK) WHERE CODCOLIGADA =@CODCOLIGADA AND CODPRJ = @CODPRJ AND REVISAO = @REVISAO)
AND   MTRF.CODTRF >= @TAREFAINI 
AND   MTRF.CODTRF <= @TAREFAFIM
AND MTRF.CODCOLIGADA =@CODCOLIGADA 



GROUP BY
MTRF.IDTRF, 
MTRF.IDPRJ,
MTRF.IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MTRF.CODCOLIGADA,
MTRF.NOME,
MTRF.QUANTIDADE,
MTRF.VALORTOTAL,
MCMP.CODCMP

ORDER BY MTRF.CODTRF 