USE CORPORE_RESIDENCIAL
SET NOCOUNT ON /*TIRAR O LINHAS AFETADAS*/
DECLARE @CODUSUARIO VARCHAR (20)= 'ana.carvalho'
DECLARE @ANALISTA VARCHAR (20)= 'yan.alves'
BEGIN TRAN
--DELETE FROM MPRJUSR WHERE CODUSUARIO = 'bruno.felix' AND CODCOLIGADA = 1
		INSERT INTO MPRJUSR ([CODCOLIGADA],[IDPRJ],[CODUSUARIO],[RECCREATEDBY],[RECCREATEDON],[RECMODIFIEDBY],[RECMODIFIEDON])
			SELECT [CODCOLIGADA], [IDPRJ], @CODUSUARIO, @ANALISTA, GETDATE(), @ANALISTA, GETDATE()
			 FROM MPRJUSR WHERE CODUSUARIO = 'fernanda.canuto' AND IDPRJ NOT IN (SELECT IDPRJ FROM MPRJUSR WHERE CODUSUARIO =@CODUSUARIO)

 
--COMMIT
--ROLLBACK