SELECT 

MCMP.IDCMP,
MCMP.CODCMP,
MCMP.DESCCMP,
MCMP.CODUND,
ISM.QUANTIDADE,
MCMP.VALORTOTAL

FROM DBO.DCMP_ISM_2
(@CODCOLIGADA,@IDPRJ,@IDCMP) AS ISM

LEFT JOIN MCMP (NOLOCK) ON (MCMP.IDPRJ = ISM.IDPRJ AND MCMP.IDCMP = ISM.CODIGO AND MCMP.CODCOLIGADA = ISM.CODCOLIGADA AND ISM.TIPO = 'C')

ORDER BY ISM.IDCMPFILHA, MCMP.CODCMP