SELECT 
MTRF.CODCOLIGADA,
MTRF.IDTRF, 
MTRF.IDPRJ,
ISNULL (MTRF.IDCMP,0) AS IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MCMP.CODCMP,
/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER O CODIGO DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.CODTRF 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODISM FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODCMP FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODIGO,
	 
MTRF.NOME,

/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER A UNIDADE DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN ' '  
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODUND FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODUND FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODUND,
	 
	 
convert(decimal(18,4),ISNULL (MTRF.QUANTIDADE  ,1)) AS QUANTIDADE,
	 
	 
/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER O VALOR DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.VALORTOTAL 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT VALOR FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT VALORTOTAL FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS PRECO,
/* CONSULTA 2 */
MRECCMP .CODCOLIGADA,
MRECCMP .IDPRJ,
MRECCMP .IDCMP,
MISM.IDISM,
MISM.CODISM,
MISM.DESCISM,
MISM.CODUND,
MRECCMP.QUANTIDADE / MRECCMP.COEFICIENTEPRODUTIVO AS QUANTIDADE,
MRECCMP.VALORUNIT,

/* CONSULTA 3 */
MCMP.IDCMP,
MCMP.CODCMP,
MCMP.DESCCMP,
MCMP.CODUND,
ISM.QUANTIDADE,
MCMP.VALORTOTAL


FROM MTRF (NOLOCK)
INNER JOIN MCMP				(NOLOCK) ON (MTRF.CODCOLIGADA = MCMP.CODCOLIGADA AND MTRF.IDCMP = MCMP.IDCMP AND MTRF.IDPRJ = MCMP.IDPRJ)
INNER JOIN MRECCMP			(NOLOCK) ON (MRECCMP.CODCOLIGADA = MCMP.CODCOLIGADA AND MRECCMP.IDPRJ = MCMP.IDPRJ AND MRECCMP.IDCMP = MCMP.IDCMP)
INNER JOIN MISM				(NOLOCK) ON (MISM.IDISM = MRECCMP.IDISM AND MISM.IDPRJ = MRECCMP.IDPRJ AND MISM.CODCOLIGADA = MRECCMP.CODCOLIGADA)
INNER JOIN DBO.DCMP_ISM_2   (NOLOCK) ON (DBO.DCMP_ISM_2.@CODCOLIGADA = )

/*
WHERE MTRF.IDPRJ = 
(SELECT IDPRJ FROM MPRJ (NOLOCK) WHERE CODCOLIGADA =@CODCOLIGADA AND CODPRJ = @CODPRJ AND REVISAO = @REVISAO)
AND   MTRF.CODTRF >= @TAREFAINI 
AND   MTRF.CODTRF <= @TAREFAFIM
AND MTRF.CODCOLIGADA =@CODCOLIGADA 

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'MCMP' 

*/
WHERE MTRF.IDPRJ = 
(SELECT IDPRJ FROM MPRJ (NOLOCK) WHERE CODCOLIGADA =39 AND CODPRJ = 'SP.2024.001' AND REVISAO = 2)
AND   MTRF.CODTRF >= '009'
AND   MTRF.CODTRF <= '010'
AND MTRF.CODCOLIGADA =39 

GROUP BY
MTRF.IDTRF, 
MTRF.IDPRJ,
MTRF.IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MTRF.CODCOLIGADA,
MTRF.NOME,
MTRF.QUANTIDADE,
MTRF.VALORTOTAL,
MCMP.CODCMP,
MRECCMP .CODCOLIGADA,
MRECCMP .IDPRJ,
MRECCMP .IDCMP,
MISM.IDISM,
MISM.CODISM,
MISM.DESCISM,
MISM.CODUND,
MRECCMP.QUANTIDADE,
MRECCMP.COEFICIENTEPRODUTIVO,
MRECCMP.VALORUNIT

ORDER BY MTRF.CODTRF 