SELECT 

MRECCMP .CODCOLIGADA,
MRECCMP .IDPRJ,
MRECCMP .IDCMP,
MISM.IDISM,
MISM.CODISM,
MISM.DESCISM,
MISM.CODUND,
MRECCMP.QUANTIDADE / MRECCMP.COEFICIENTEPRODUTIVO AS QUANTIDADE,
MRECCMP.VALORUNIT


 FROM MRECCMP 
 
INNER JOIN MISM (NOLOCK) ON (MISM.IDISM = MRECCMP.IDISM AND MISM.IDPRJ = MRECCMP.IDPRJ AND MISM.CODCOLIGADA = MRECCMP.CODCOLIGADA)

WHERE	MRECCMP.IDPRJ = @IDPRJ
AND		MRECCMP.IDCMP = @IDCMP 
AND		MRECCMP.IDISM IS NOT NULL
AND		MRECCMP.CODCOLIGADA =@CODCOLIGADA

ORDER BY MISM.CODISM 

/*
SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'MCMP'

SELECT * 
FROM MCMP 
WHERE CODCMP = 'MRO.066'

*/

SELECT 

MISM.IDISM,
MISM.CODISM,
MISM.DESCISM,
MISM.CODUND,
MRECCMP.QUANTIDADE / MRECCMP.COEFICIENTEPRODUTIVO AS QUANTIDADE,
MRECCMP.VALORUNIT


 FROM MRECCMP 
 
INNER JOIN MISM (NOLOCK) ON (MISM.IDISM = MRECCMP.IDISM AND MISM.IDPRJ = MRECCMP.IDPRJ AND MISM.CODCOLIGADA = MRECCMP.CODCOLIGADA)

WHERE	MRECCMP.IDPRJ = @IDPRJ
AND		MRECCMP.IDCMP = @IDCMP 
AND		MRECCMP.IDISM IS NOT NULL
AND		MRECCMP.CODCOLIGADA =@CODCOLIGADA

ORDER BY MISM.CODISM 