/*Consulta 01*/
SELECT 

SUM(GRUPO.VALORODC) AS FRETEODC,
SUM(GRUPO.FRETE_NF) AS FRETENF,
SUM(GRUPO.VALORLIQUIDO) AS FRETECTRC
,GRUPO.FRETECIFOUFOB,
CASE WHEN SUM(GRUPO.VALORNOTAS) > 0 THEN CONVERT(DECIMAL(10,2),(SUM(GRUPO.VALORLIQUIDONF)  / SUM(GRUPO.VALORNOTAS) * SUM(GRUPO.VALORLIQUIDO))) ELSE 0 END AS VALORFRETEPROPORCIONAL

 FROM (

SELECT 

0 AS VALORODC,
NF.VALORFRETE FRETE_NF,
IIF(CTRC.VALORLIQUIDO = 0,CTRC.VALORLIQUIDOORIG,CTRC.VALORLIQUIDO) AS VALORLIQUIDO,
ODC.FRETECIFOUFOB,
NF.VALORLIQUIDO AS VALORLIQUIDONF,
TCTRCMOV.VALORNOTAS


FROM
 TMOV ODC (NOLOCK)
 INNER JOIN TMOVRELAC      (NOLOCK) ON ODC.IDMOV = TMOVRELAC.IDMOVORIGEM AND ODC.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM
 INNER JOIN TMOV NF		   (NOLOCK) ON NF.IDMOV = TMOVRELAC.IDMOVDESTINO AND NF.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO
 LEFT JOIN TCTRCENTRADA    (NOLOCK) ON TCTRCENTRADA.IDMOVNF = NF.IDMOV  AND TCTRCENTRADA.CODCOLIGADA = NF.CODCOLIGADA
 LEFT JOIN TMOV CTRC	   (NOLOCK) ON CTRC.IDMOV = TCTRCENTRADA.IDMOVCTRC AND CTRC.CODCOLIGADA = TCTRCENTRADA.CODCOLIGADA
 LEFT JOIN TCTRCMOV		   (NOLOCK) ON TCTRCMOV.IDMOV = CTRC.IDMOV AND TCTRCMOV.CODCOLIGADA = CTRC.CODCOLIGADA

WHERE 
    ODC.IDMOV IN(25015, 25125) AND ODC.CODCOLIGADA =51

GROUP BY  
ODC.CODCOLIGADA,
ODC.FRETECIFOUFOB,
NF.VALORFRETE,
CTRC.VALORLIQUIDO,
CTRC.VALORLIQUIDOORIG,
NF.IDMOV,
NF.VALORLIQUIDO,
TCTRCMOV.VALORNOTAS

UNION ALL


SELECT 
ODC.VALORFRETE,
0,
0,
ODC.FRETECIFOUFOB,
0,
0


FROM
 TMOV ODC (NOLOCK)
WHERE 
    ODC.IDMOV IN(25015, 25125) AND ODC.CODCOLIGADA =51
) AS GRUPO

GROUP BY GRUPO.FRETECIFOUFOB

/* FIM DA CONSULTA 01 */
/*CONSULTA 2 */

WITH SOMA AS (  
    SELECT   
        SUM(GRUPO.VALORODC) AS FRETEODC,  
        SUM(GRUPO.FRETE_NF) AS FRETENF  
              
    FROM (  
        SELECT   
            0 AS VALORODC,  
            NF.VALORFRETE AS FRETE_NF,  
            IIF(CTRC.VALORLIQUIDO = 0, CTRC.VALORLIQUIDOORIG, CTRC.VALORLIQUIDO) AS VALORLIQUIDO,  
            NF.CODCOLIGADA,  
            NF.CODFILIAL  
        FROM  
            TMOV ODC (NOLOCK)  
            INNER JOIN TMOVRELAC (NOLOCK) ON ODC.IDMOV = TMOVRELAC.IDMOVORIGEM AND ODC.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM  
            INNER JOIN TMOV NF (NOLOCK) ON NF.IDMOV = TMOVRELAC.IDMOVDESTINO AND NF.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO  
            LEFT JOIN TCTRCENTRADA (NOLOCK) ON TCTRCENTRADA.IDMOVNF = NF.IDMOV AND TCTRCENTRADA.CODCOLIGADA = NF.CODCOLIGADA  
            LEFT JOIN TMOV CTRC (NOLOCK) ON CTRC.IDMOV = TCTRCENTRADA.IDMOVCTRC AND CTRC.CODCOLIGADA = TCTRCENTRADA.CODCOLIGADA  
            LEFT JOIN TCTRCMOV (NOLOCK) ON TCTRCMOV.IDMOV = CTRC.IDMOV AND TCTRCMOV.CODCOLIGADA = CTRC.CODCOLIGADA  
        WHERE   
            ODC.IDMOV IN (25015, 25125) AND ODC.CODCOLIGADA = 51
        GROUP BY  
            NF.VALORFRETE,    
            CTRC.VALORLIQUIDO,  
            CTRC.VALORLIQUIDOORIG,  
            NF.IDMOV,  
            NF.CODCOLIGADA,  
            NF.CODFILIAL,  
            TCTRCMOV.VALORNOTAS  

        UNION ALL  

        SELECT   
            ODC.VALORFRETE,  
            0,   
            0,  
            ODC.CODCOLIGADA,  
            ODC.CODFILIAL  
        FROM  
            TMOV ODC (NOLOCK)  
        WHERE   
            ODC.IDMOV IN (25015, 25125) AND ODC.CODCOLIGADA = 51
    ) AS GRUPO  
    
)  

SELECT   
    R.FRETEODC,  
    R.FRETENF,  
    NF.VALORFRETE AS FRETE_NF,  
    NF.IDMOV AS NF_IDMOV,  
    NF.CODTMV AS NF_CODTMV,  
    ODC.IDMOV AS ODC_IDMOV,  
    ODC.CODTMV AS ODC_CODTMV,  
    NF.CODCOLIGADA AS CODCOLIGADA_NF,   
    NF.CODFILIAL AS CODFILIAL_NF        
FROM   
    SOMA R  
    JOIN TMOV ODC (NOLOCK) ON ODC.IDMOV IN (9967) AND ODC.CODCOLIGADA = 37  
    INNER JOIN TMOVRELAC (NOLOCK) ON ODC.IDMOV = TMOVRELAC.IDMOVORIGEM AND ODC.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM  
    INNER JOIN TMOV NF (NOLOCK) ON NF.IDMOV = TMOVRELAC.IDMOVDESTINO AND NF.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO  
WHERE   
    ODC.IDMOV IN (25015, 25125) AND ODC.CODCOLIGADA = 51;

	/* FIM DA CONSULTA 02 */
	SELECT fretecifoufob, *
	FROM TMOV 
	WHERE CODCOLIGADA = 51
	AND IDMOV IN (25015, 25125)
	and fretecifoufob = 3

