
SELECT 
MTRF.CODCOLIGADA,
MTRF.IDTRF, 
MTRF.IDPRJ,
ISNULL (MTRF.IDCMP,0) AS IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MCMP.CODCMP,
/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER O CODIGO DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.CODTRF 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODISM FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODCMP FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODIGO,
	 
MTRF.NOME,

/*REGRA PARA VER SE É SERVIÇO OU NÃO PARA TRAZER A UNIDADE DO INSUMO OU COMPOSIÇÃO*/

CASE WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN ' '  
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT CODUND FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT CODUND FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS CODUND,
	 convert(decimal(18,4),ISNULL (MTRF.QUANTIDADE  ,1)) AS QUANTIDADE,
	CASE 
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NULL) THEN MTRF.VALORTOTAL 
	 WHEN (MTRF.IDISM IS NOT NULL AND MTRF.IDCMP IS NULL) THEN (SELECT VALOR FROM MISM (NOLOCK) WHERE IDISM = MTRF.IDISM AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 WHEN (MTRF.IDISM IS NULL AND MTRF.IDCMP IS NOT NULL) THEN (SELECT VALORTOTAL FROM MCMP (NOLOCK) WHERE IDCMP = MTRF.IDCMP AND IDPRJ = MTRF.IDPRJ AND CODCOLIGADA = MTRF.CODCOLIGADA)
	 END AS PRECO,

/* CONSULTA 2 */
MRECCMP.CODCOLIGADA,
MRECCMP.IDPRJ,
MRECCMP.IDCMP,
(CASE WHEN MISM.IDISM IS NULL THEN MCMPFIL.IDCMP ELSE MISM.IDISM END) AS 'ID_INSUMO - COMP',
(CASE WHEN MISM.CODISM IS NULL THEN MCMPFIL.CODCMP ELSE MISM.CODISM END) AS 'COD_INSUMO - COMP',
(CASE WHEN MISM.DESCISM IS NULL THEN MCMPFIL.DESCCMP ELSE MISM.DESCISM END) AS 'DESC_INSUMO_COMP',
(CASE WHEN MISM.CODUND IS NULL THEN MCMPFIL.CODUND ELSE MISM.CODUND END) AS 'CODUND_INS - COMP',
MRECCMP.QUANTIDADE / MRECCMP.COEFICIENTEPRODUTIVO AS QUANTIDADE,
MRECCMP.VALORUNIT,

/* CONSULTA 3 */
MRECCMPFIL.CODCOLIGADA,
MRECCMPFIL.IDPRJ,
MRECCMPFIL.IDCMP,
(CASE WHEN MISMFIL.IDISM IS NULL THEN MCMPFIL2.IDCMP ELSE MISMFIL.IDISM END) AS 'ID_INSUMO - COMP 2',
(CASE WHEN MISMFIL.CODISM IS NULL THEN MCMPFIL2.CODCMP ELSE MISMFIL.CODISM END) AS 'COD_INSUMO - COMP 2 ',
(CASE WHEN MISMFIL.DESCISM IS NULL THEN MCMPFIL2.DESCCMP ELSE MISMFIL.DESCISM END) AS 'DESC_INSUMO_COMP 2',
(CASE WHEN MISMFIL.CODUND IS NULL THEN MCMPFIL2.CODUND ELSE MISMFIL.CODUND END) AS 'CODUND_INS - COMP 2',
MRECCMPFIL.QUANTIDADE / MRECCMP.COEFICIENTEPRODUTIVO AS QUANTIDADE,
MRECCMPFIL.VALORUNIT


FROM MTRF (NOLOCK)
INNER JOIN MCMP											(NOLOCK) ON (MTRF.CODCOLIGADA = MCMP.CODCOLIGADA AND MTRF.IDCMP = MCMP.IDCMP AND MTRF.IDPRJ = MCMP.IDPRJ)
INNER JOIN MRECCMP										(NOLOCK) ON (MRECCMP.CODCOLIGADA = MCMP.CODCOLIGADA AND MRECCMP.IDPRJ = MCMP.IDPRJ AND MRECCMP.IDCMP = MCMP.IDCMP AND MRECCMP.GRUPODNER = 'C')
LEFT JOIN MISM											(NOLOCK) ON (MISM.IDISM = MRECCMP.IDISM AND MISM.IDPRJ = MRECCMP.IDPRJ AND MISM.CODCOLIGADA = MRECCMP.CODCOLIGADA)
LEFT JOIN MCMP AS MCMPFIL								(NOLOCK) ON (MRECCMP.CODCOLIGADA = MCMPFIL.CODCOLIGADA AND MRECCMP.IDPRJ = MCMPFIL.IDPRJ AND MRECCMP.IDCMPFILHA = MCMPFIL.IDCMP)
INNER JOIN MRECCMP AS MRECCMPFIL 						(NOLOCK) ON (MRECCMPFIL.CODCOLIGADA = MCMPFIL.CODCOLIGADA AND MRECCMPFIL.IDPRJ = MCMPFIL.IDPRJ AND MRECCMPFIL.IDCMP = MCMPFIL.IDCMP AND MRECCMP.GRUPODNER = 'C')
LEFT JOIN MISM AS MISMFIL								(NOLOCK) ON (MISMFIL.IDISM = MRECCMPFIL.IDISM AND MISMFIL.IDPRJ = MRECCMPFIL.IDPRJ AND MISMFIL.CODCOLIGADA = MRECCMPFIL.CODCOLIGADA)
LEFT JOIN MCMP AS MCMPFIL2								(NOLOCK) ON (MRECCMPFIL.CODCOLIGADA = MCMPFIL2.CODCOLIGADA AND MRECCMPFIL.IDPRJ = MCMPFIL2.IDPRJ AND MRECCMPFIL.IDCMPFILHA = MCMPFIL2.IDCMP)

WHERE MRECCMP.CODCOLIGADA  = 39
AND MRECCMP.IDPRJ = 12
AND MRECCMP.IDCMP = 757053


GROUP BY
MTRF.IDTRF, 
MTRF.IDPRJ,
MTRF.IDCMP,
MTRF.CODTRF,
MTRF.IDISM,
MTRF.CODCOLIGADA,
MTRF.NOME,
MTRF.QUANTIDADE,
MTRF.VALORTOTAL,
MCMP.CODCMP,
MCMP.IDCMP,
MCMP.DESCCMP,
MRECCMP.CODCOLIGADA,
MRECCMP.IDPRJ,
MRECCMP.IDCMP,
MISM.IDISM,
MISM.CODISM,
MISM.DESCISM,
MISM.CODUND,
MRECCMP.QUANTIDADE,
MRECCMP.COEFICIENTEPRODUTIVO,
MRECCMP.VALORUNIT,
MCMPFIL.IDCMP,
MCMPFIL.CODCMP,
MCMPFIL.DESCCMP,
MCMPFIL.CODUND,
MRECCMPFIL.CODCOLIGADA,
MRECCMPFIL.IDPRJ,
MRECCMPFIL.IDCMP,
MRECCMPFIL.QUANTIDADE,
MRECCMP.COEFICIENTEPRODUTIVO,
MRECCMPFIL.VALORUNIT,
MISMFIL.IDISM,
MISMFIL.CODISM,
MISMFIL.DESCISM,
MISMFIL.CODUND,
MCMPFIL2.IDCMP,
MCMPFIL2.CODCMP,
MCMPFIL2.DESCCMP,
MCMPFIL2.CODUND

ORDER BY DESC_INSUMO_COMP