SELECT  
TMOV.CODCOLIGADA AS 'COLIGADA',
TMOV.CODFILIAL AS 'CODFILIAL',
GFILIAL.NOMEFANTASIA AS 'NOME FILIAL',
GFILIAL.RUA ,
GFILIAL.BAIRRO,
GFILIAL.CIDADE,
GFILIAL.ESTADO,
GFILIAL.CEP,
GFILIAL.CGC AS 'CNPJ',
GFILIAL.INSCRICAOESTADUAL,
'(31) 3526-7455 / (31) 3526-7455' AS 'TELEFONE',
'(31) 3261-4246' AS 'FAX',
TMOV.IDMOV AS 'REFERENCIA',
TMOV.NUMEROMOV AS 'NUMERO NOTA',
TMOV.CODTMV AS 'MOVIMENTO',
TMOV.CODCCUSTO,
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO',
TMOV.CODLOC AS 'LOCAL DE ESTOQUE',
TLOC.NOME AS 'NOME LOCAL DE ESTOQUE',
TMOV.DATAEMISSAO,
TITMMOV.QUANTIDADE,
TITMMOV.CODUND,
TPRD.DESCRICAO,
TITMMOV.PRECOUNITARIO,
TMOVHISTORICO.HISTORICOLONGO,
/* UNIFICANDO CONSULTA SQL.T02002.3 */
TRPR.NOME,
TRPR.RUA + ' - Nº :' + CONVERT(VARCHAR, TRPR.NUMERO) AS RUA,
TRPR.BAIRRO,
TRPR.CIDADE + ' / ' + TRPR.CODETD AS CIDADE,
TRPR.CEP + ' - REF: ' + TRPR.COMPLEMENTO AS CEP,
TRPR.CGC,
TRPR.INSCRESTADUAL,
TRPR.CONTATO,
TRPR.TELEFONE,
TRPR.FAX,
TRPR.CELULAR,
/* FIM DA UNIFICAÇÃO CONSULTA SQL.T02002.3 */
/* UNIFICANDO CONSULTA SQL.T02002.1 */
CASE WHEN TMOV.DATAENTREGA = '2001-01-01' THEN 'PROGRAMADO' 
            WHEN TMOV.DATAENTREGA = '2001-01-02' THEN 'VIDE OBS'
            WHEN TMOV.DATAENTREGA = '2001-01-03' THEN 'IMEDIATO'
            ELSE convert(varchar,TMOV.DATAENTREGA,103) END AS 'DATAENTREGA'
/* FIM DA UNIFICAÇÃO CONSULTA SQL.T02002.1 */
FROM TMOV
INNER JOIN GFILIAL			(NOLOCK) ON TMOV.CODCOLIGADA = GFILIAL.CODCOLIGADA AND TMOV.CODFILIAL = GFILIAL.CODFILIAL
INNER JOIN GCCUSTO			(NOLOCK) ON TMOV.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND TMOV.CODCCUSTO = GCCUSTO.CODCCUSTO
INNER JOIN TITMMOV			(NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
INNER JOIN TMOVHISTORICO	(NOLOCK) ON TMOV.CODCOLIGADA = TMOVHISTORICO.CODCOLIGADA AND TMOV.IDMOV = TMOVHISTORICO.IDMOV
INNER JOIN TLOC				(NOLOCK) ON TITMMOV.CODCOLIGADA = TLOC.CODCOLIGADA AND TITMMOV.CODFILIAL = TLOC.CODFILIAL AND  TITMMOV.CODLOC = TLOC.CODLOC
INNER JOIN TPRD				(NOLOCK) ON TITMMOV.CODCOLIGADA = TPRD.CODCOLIGADA AND TITMMOV.IDPRD = TPRD.IDPRD
/* UNIFICANDO CONSULTA SQL.T02002.3 */
LEFT  JOIN TRPR				(NOLOCK) ON TRPR.CODCOLIGADA = TMOV.CODCOLIGADA AND TRPR.CODRPR = TMOV.CODRPR 
/* FIM DA UNIFICAÇÃO CONSULTA SQL.T02002.3 */
/*
WHERE
TMOV.CODCOLIGADA = :$CODCOLIGADA 
AND TMOV.IDMOV = :IDMOV
*/

WHERE
TMOV.CODCOLIGADA = 1
AND TMOV.IDMOV = '2222992'


/*
SELECT * 
FROM GLINKSREL
WHERE CHILDTABLE = 'TLOC'

SELECT * 
FROM TPRD

*/