--SELECT TMOV.RECCREATEDON, RECCREATEDby,* 
--FROM TMOV 
--WHERE CODCOLIGADA = 44 
--AND CODTMV = '1.1.18'
--AND STATUS <> 'F'
--ORDER BY TMOV.RECCREATEDON DESC

--SELECT * 
--FROM GFILIAL
--WHERE CODCOLIGADA = 55

--select nome,* 
--from pfunc 
--where codcoligada = 37
--and CODSITUACAO = 'a'
--order by RECCREATEDON desc


--SELECT * 
--FROM GWORKFLOW
--WHERE XOMLDATA LIKE '%ESTORNAR%'

select nome,* 
from pfunc 
where codsecao = '0001.0001.03.01.0004'
and codsituacao = 'a'


--select * 
--from tmov 
--where codtmv = '1.2.82'
--order by RECCREATEDON desc

--SELECT * 
--FROM FCFO 
--WHERE NOME LIKE '%tles%'

SELECT * 
FROM TNFEENTRADA 
WHERE CHAVEACESSO = '35250708980044000137550010000015571331385410'

--select ultimonivel, * 
--from tprd 
--where codigoprd = '001.02194'
--and codcoligada = 37


--select * 
--from tmov 
--where idmov = 22734
--and codcoligada = 59

USE DBCONTROLEMP

SELECT  REC.ID_REQUISICAO, REC_MAT.RM_IDPRJ, CLASSE.* 
FROM [RMO].[REQUISICAO] AS REC
INNER JOIN [RMO].[REQUISICAO_MATERIAL] AS REC_MAT ON REC_MAT.ID_REQUISICAO = REC.ID_REQUISICAO
INNER JOIN [dbo].[CLASSE_OBRA] AS CLASSE ON CLASSE.ID_CLASSE = REC_MAT.ID_CLASSE AND REC.ID_OBRA = CLASSE.ID_OBRA

WHERE REC.ID_OBRA = 201
AND REC.ID_REQUISICAO = 873980

USE CORPORE_RESIDENCIAL
SELECT CODCOLIGADA, IDPRJ, IDTRF, CODTRF
FROM MTRF 
WHERE CODCOLIGADA = 51
AND IDTRF = 8

USE CORPORE_RESIDENCIAL
SELECT IDTRF,TITMMOV.RECCREATEDON, * 
FROM TITMMOV
WHERE CODCOLIGADA = 51 
AND RECCREATEDON > '20250101'
ORDER BY TITMMOV.RECCREATEDON DESC


--SELECT * 
--FROM [dbo].[CLASSE_OBRA]

SELECT * 
FROM TMOV 
WHERE IDMOV = 15456 
AND CODCOLIGADA = 32

SELECT PFVALETR.*
FROM PFUNC 
INNER JOIN PFVALETR ON PFVALETR.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFVALETR.CHAPA = PFUNC.CHAPA
WHERE PFVALETR.CODCOLIGADA = 59 
AND CODSITUACAO = 'A' 
AND PFVALETR.RECMODIFIEDBY = 'rosangela.ferreira'
ORDER BY PFVALETR.RECCREATEDON DESC

SELECT * 
FROM PFVALETR
WHERE CODCOLIGADA = 59

select reccreatedby, * 
from tmov 
where idmov = 11043
and codcoligada = 31 

SELECT * 
FROM CLASSE_OBRA
WHERE ID_OBRA = 212 
AND ID_CLASSE = 43

SELECT * 
FROM [RMO].[REQUISICAO]
WHERE ID_REQUISICAO = 836855

SELECT * 
FROM OBRA
WHERE ID_OBRA = 203