WITH RM AS 
(	SELECT 
	PPESSOA.CODUSUARIO,
	PPESSOA.CODIGO,
	PFUNC.CODSITUACAO,
	PFUNC.NOME AS 'FUNCIONARIO',
	PFUNCAO.NOME AS 'NOME_FUNC'
	FROM CORPORE_RESIDENCIAL..PPESSOA		AS PPESSOA	
	INNER JOIN CORPORE_RESIDENCIAL..PFUNC	AS PFUNC	ON PFUNC.CODPESSOA = PPESSOA.CODIGO
	INNER JOIN CORPORE_RESIDENCIAL..PFUNCAO AS PFUNCAO  ON PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA
)


SELECT DISTINCT
    C.Path AS 'PASTA',
    (SUBSTRING(U.UserName, CHARINDEX('\', U.UserName) + 1, LEN(U.UserName))) AS USUARIO,
   (CASE 
	WHEN R.ROLENAME = 'BROWSER' THEN 'ACESSO A VER RELATORIOS' ELSE 'ACESSO ADM' END)AS PAPEL
FROM 
    CATALOG AS C
    INNER JOIN [DBO].[POLICIES] AS P ON C.POLICYID = P.POLICYID
    INNER JOIN POLICYUSERROLE AS PUR ON P.POLICYID = PUR.POLICYID
    INNER JOIN USERS AS U ON PUR.USERID = U.USERID
    INNER JOIN ROLES AS R ON PUR.ROLEID = R.ROLEID
	--inner join RM		  on rm.CODUSUARIO COLLATE Latin1_General_CI_AS_KS_WS = (SUBSTRING(U.UserName, CHARINDEX('\', U.UserName) + 1, LEN(U.UserName)))
WHERE /*C.PATH = '/RELATÓRIOS EMCCAMP/P.014 - OBRA'
AND*/ U.USERNAME NOT IN ( 'EMCCAMP\_RES_TI_SISTEMAS_GLOBAL', 'EMCCAMP\_RES_CONTABILIDADE_LOCAL', 'EMCCAMP\_RES_IMOBILIARIO_GLOBAL', 'EMCCAMP\_RES_IMOBILIARIO_LOCAL', 'EMCCAMP\_RES_MARKETING_LOCAL', 'EMCCAMP\_RES_TI_GLOBAL', 'BUILTIN\ADMINISTRATORS'
,'EMCCAMP\ADMIN.BI', 'EMCCAMP\_RES_FISCAL', 'EMCCAMP\_RES_CEDOC_LOCAL', 'EMCCAMP\_RES_CENTRAL-DE-NOTAS', 'EMCCAMP\_RES_CONTABILIDADE_GESTAO', 'EMCCAMP\_RES_CONTROLE_GLOBAL', 'EMCCAMP\_RES_LEGALIZACAO', 'EMCCAMP\_RES_SSM_GLOBAL')
--AND RM.CODSITUACAO <> 'D'
--AND RM.NOME_FUNC LIKE '%ENG%'
and C.Path not in ( '', '/68f0607b-9378-4bbb-9e70-4da3d7d66838')
and C.Path not like '%CRM%'
and C.Path not like '%shared%'
and C.Path not like '%parts%'

ORDER BY 
    1,2;
	