--select 
--CONVERT(MONEY,(CASE 
--	WHEN GRUPO.CODSINDICATO = '0002' THEN (
--								CASE WHEN GRUPO.SALARIO < GRUPO.salario_base_bh THEN ((GRUPO.salario / GRUPO.JORNADA) * 80)
--								ELSE ((GRUPO.salario_base_bh / JORNADA) * 80) END)
--	WHEN GRUPO.CODSINDICATO = '0011' THEN (
--								CASE WHEN GRUPO.SALARIO < GRUPO.salario_base_cont THEN ((GRUPO.salario / JORNADA) * 80)
--								ELSE ((GRUPO.salario_base_cont / JORNADA) * 80) END) 
--								ELSE 'ERRO' END)) AS 'VALOR DE ABONO'
--from 
--(
--SELECT CODSINDICATO,
--220 AS JORNADA, 
--CONVERT(MONEY,(CASE WHEN PVALFIX.CODIGO = '0002' THEN PVALFIX.VALOR ELSE '0' END))as 'salario_base_bh',
--CONVERT(MONEY,(CASE WHEN PVALFIX.CODIGO = '0011' THEN PVALFIX.VALOR ELSE '0' END))as 'salario_base_cont',
--CONVERT(MONEY,PFUNC.SALARIO) AS SALARIO,
--PFUNC.NOME,
--PFUNC.CHAPA

--FROM PFUNC
--INNER JOIN PVALFIX ON PVALFIX.CODCOLIGADA = PFUNC.CODCOLIGADA AND PVALFIX.CODIGO = PFUNC.CODSINDICATO
--where
--PFUNC.codcoligada = 1 
--and PFUNC.chapa = :CHAPA)AS GRUPO



SELECT (CASE WHEN (GP2.NRODIASABONO + GP2.NRODIASFERIAS) = 30 AND gp2.faltas >= 3 THEN 'NÃO PAGA' ELSE 'PAGA' END) AS 'CONSULTA_PAGA_ABONO', *
FROM(
SELECT 
PFUNC.CODCOLIGADA AS COLIG,
PFUNC.CHAPA,
PFUNC.NOME,
PFUFERIAS.INICIOPERAQUIS,
PFUFERIAS.FIMPERAQUIS AS FIM_PERIO_AQ,
PFUFERIAS.SALDO, 
PFUFERIAS.FALTAS,
PFUFERIASPER.DATAINICIO,
PFUFERIASPER.DATAFIM,
PFUFERIASPER.NRODIASABONO,
PFUFERIASPER.NRODIASFERIAS
FROM PFUFERIAS
LEFT JOIN PFUFERIASPER ON PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA AND PFUFERIASPER.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS
INNER JOIN PFUNC ON PFUFERIAS.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUFERIAS.CHAPA = PFUNC.CHAPA
where
PFUNC.codcoligada = 1 
and PFUNC.chapa IN ('00009460','00015519','00023655','00024221')
AND PFUFERIASPER.FALTAS > 1
AND PFUNC.CODSITUACAO <> 'D'
) AS GP2



