


DECLARE @PEDIDOBRS AS VARCHAR(10) = '8702324';

DECLARE @IDMOV AS INT = (SELECT IDMOV FROM TMOVCOMPL WHERE PEDIDOBRS = @PEDIDOBRS),	
		@CODCOLIGADA AS INT = (SELECT CODCOLIGADA FROM TMOVCOMPL WHERE PEDIDOBRS = @PEDIDOBRS);

SELECT         
TMOV.CODCOLIGADA,
TMOV.IDMOV,
FORMAT(ISNULL(HHISTORICOEXT.RECCREATEDON,TMOVAPROVA.RECMODIFIEDON),'dd/MM/yyyy HH:mm:ss') AS DATA,    
TMOVAPROVA.DATADESAPROVA AS DATA_DESAPROVACAO,    
TMOVAPROVA.USUARIODESAPROVA,    
DBO.TRAZ_ETAPA_ALCADA(HHISTORICOEXT.CODTAREFAATUAL) AS 'ETAPA',    
ISNULL(TMOVAPROVA.CODUSUARIO,PPESSOA.CODUSUARIO)  AS USUARIO,    
TMOV.CODCCUSTO,    GCCUSTO.NOME AS CENTRO_CUSTO      

FROM TMOV (NOLOCK)      
LEFT JOIN TMOVATEND    (NOLOCK) ON TMOV.IDMOV = TMOVATEND.IDMOV AND TMOV.CODCOLIGADA = TMOVATEND.CODCOLIGADA    
LEFT JOIN HATENDIMENTOBASE  (NOLOCK) ON TMOVATEND.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO AND TMOVATEND.CODCOLIGADAATEND = HATENDIMENTOBASE.CODCOLIGADA    
LEFT JOIN HHISTORICOEXT   (NOLOCK) ON HHISTORICOEXT.CODATENDIMENTO = HATENDIMENTOBASE.CODATENDIMENTO AND TMOVATEND.CODCOLIGADAATEND = HHISTORICOEXT.CODCOLIGADA    
LEFT JOIN HATENDENTE    (NOLOCK) ON HATENDENTE.CODATENDENTE = HHISTORICOEXT.CODATENDPARA AND HATENDENTE.CODCOLIGADA = HHISTORICOEXT.CODCOLIGADAPARA    
LEFT JOIN PPESSOA    (NOLOCK) ON PPESSOA.CODIGO = HATENDENTE.CODPESSOA    
LEFT JOIN GCCUSTO    (NOLOCK) ON TMOV.CODCCUSTO = GCCUSTO.CODCCUSTO AND TMOV.CODCOLIGADA = GCCUSTO.CODCOLIGADA    
LEFT JOIN TMOVAPROVA    (NOLOCK) ON TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA        

WHERE TMOV.IDMOV = @IDMOV AND TMOV.CODCOLIGADA =@CODCOLIGADA    

ORDER BY ISNULL(HATENDIMENTOBASE.RECMODIFIEDON,TMOVAPROVA.RECMODIFIEDON)    