DECLARE @CODCOLIGADA AS INT = 51,
		@DATA_SOLICITACAO_INI_D AS DATE = '20240901',
		@DATA_SOLICITACAO_FIN_D AS DATE = '20240930';


SELECT 
/* 
TITMMOV.PRECOUNITARIO + CONVERT(DECIMAL(10,2),ISNULL(TTRBMOV.VALOR,0) / TITMMOV.QUANTIDADETOTAL) + (((((TITMMOV.QUANTIDADETOTAL * TITMMOV.PRECOUNITARIO) / IIF(TMOV.VALORBRUTO = 0 OR TMOV.VALORBRUTO < TMOV.VALORBRUTOORIG,TMOV.VALORBRUTOORIG,TMOV.VALORBRUTO)) * TMOV.VALORFRETE) / TITMMOV.QUANTIDADETOTAL))
*/ 

ISNULL(CONVERT(MONEY,GRUPO.PRECOUNITARIO + CONVERT(DECIMAL(10,2),ISNULL(GRUPO.VALOR_IPI,0) / GRUPO.QUANTIDADETOTAL) + (((((GRUPO.QUANTIDADETOTAL * GRUPO.PRECOUNITARIO) / IIF(GRUPO.VALORBRUTO = 0 OR GRUPO.VALORBRUTO < GRUPO.VALORBRUTOORIG,GRUPO.VALORBRUTOORIG,GRUPO.VALORBRUTO)) * GRUPO.VALORFRETE) / GRUPO.QUANTIDADETOTAL))* GRUPO.QUANTIDADETOTAL),0) AS 'Valor Odc + IPI + Frete/Item',

GRUPO.* 
FROM(
SELECT 
ISNULL(TITMMOV.PRECOUNITARIO,0) as 'PRECOUNITARIO',
ISNULL(TTRBMOV.VALOR,0) as 'VALOR_IPI',
NULLIF(TITMMOV.QUANTIDADETOTAL,0) as 'QUANTIDADETOTAL',
ISNULL(TMOV.VALORBRUTO,0) as 'VALORBRUTO',
ISNULL(TMOV.VALORBRUTOORIG,0) as 'VALOR BRUTO ORIG',
ISNULL(TMOV.VALORFRETE,0) as 'VALORFRETE',

(SELECT COUNT(*) FROM TCITMORCAMENTO (NOLOCK) WHERE TCITMORCAMENTO.IDMOV = TMOV.IDMOV AND TCITMORCAMENTO.CODCOLIGADA = TMOV.CODCOLIGADA AND TCITMORCAMENTO.IDPRD =  TITMMOV.IDPRD AND TCITMORCAMENTO.VALCOTACAO > 0 ) AS QTD_COTACOES,

/*DADOS DA SOLICITACAO*/
TMOV.CODCOLIGADA AS COLIGADA,
TMOV.CODFILIAL AS FILIAL,
GCCUSTO.NOME AS OBRA,
TMOV.IDMOV,
TMOV.NUMEROMOV AS NUMERO_SOLICITACAO,
TMOV.CODTMV AS TIPO_MOV_SOLICITACAO,
TMOV.DATACRIACAO AS CRIACAO_SOLICITACAO,
TMOV.CODCCUSTO,

dbo.TRAZ_STATUS (TMOV.STATUS) AS STATUS_SOLICITACAO,

SUM (TITMMOV.QUANTIDADETOTAL) AS QUANTIDADE_SOLICITADA,
TPRD.CODIGOPRD,
TPRD.NOMEFANTASIA,
TITMMOV.CODUND,

/* DADOS DA ODC */

TMOV_ODC.IDMOV AS IDMOV_ODC,
TMOV_ODC.NUMEROMOV AS NUMERO_ODC,
TMOV_ODC.CODTMV AS CODTMV_ODC,
TMOV_ODC.DATACRIACAO AS CRIACAO_ODC,
FORMAT(TMOV_ODC.DATAENTREGA, 'dd/MM/yyyy') AS ENTREGA_ODC,
dbo.TRAZ_STATUS (TMOV_ODC.STATUS) AS STATUS_ODC,
FCFO.NOMEFANTASIA AS FORNECEDOR,
TITMMOV_ODC.PRECOUNITARIO AS PRECO_UNITARIO_ODC,
TITMMOV_ODC.QUANTIDADETOTAL AS QUANTIDADE_ODC,
TITMMOV_ODC.QUANTIDADETOTAL - TITMMOV_ODC.QUANTIDADE AS QUANTIDADE_RECEBIDA_ODC,
TITMMOV_ODC.QUANTIDADE AS  QUANTIDADE_A_RECEBER_ODC,
GFILIAL.ESTADO AS 'ESTADO_FILIAL',
TMOV_ODC.RECCREATEDBY AS 'US_CRIACAO_OC',
TMOV_ODC.VALORLIQUIDO AS 'VALOR_TOTAL_ODC',


/* DADOS DA NOTA */

TMOV_NOTA.IDMOV AS IDMOV_NOTA,
TMOV_NOTA.NUMEROMOV AS NUMERO_NOTA,
TMOV_NOTA.CODTMV AS CODTMV_NOTA,
TMOV_NOTA.DATACRIACAO AS CRIACAO_NOTA,
dbo.TRAZ_STATUS (TMOV_NOTA.STATUS) AS STATUS_NOTA,
TMOV_NOTA.VALORBRUTOORIG,
TMOV_NOTA.VALORDESC AS DESCONTO_NOTA,
TITMMOV_NOTA.PRECOUNITARIO AS PRECOUNITARIO_NOTA,
TITMMOV_NOTA.QUANTIDADETOTAL AS QUANTIDADE_NOTA,
TITMMOV_NOTA.VALORDESC AS DESCONTO_ITEM,
TMOV_NOTA.DATAEMISSAO AS EMISSAO_NOTA,
TMOVCOMPL.URGENCIA,

CASE WHEN TMOVCOMPL_ODC.REGULARIZACAO = 'T' THEN 'MARCADO'
		ELSE 'NÃO MARCADO'
			END AS REGULARIZACAO

 
FROM TMOV

/* DADOS SOLICITACAO */

INNER JOIN TITMMOV							(NOLOCK) ON (TITMMOV.IDMOV = TMOV.IDMOV AND TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA)
INNER JOIN TPRD								(NOLOCK) ON (TPRD.IDPRD = TITMMOV.IDPRD AND TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT JOIN TITMMOVRELAC						(NOLOCK) ON (TITMMOVRELAC.IDMOVORIGEM = TITMMOV.IDMOV AND TITMMOVRELAC.NSEQITMMOVORIGEM = TITMMOV.NSEQITMMOV AND TITMMOVRELAC.CODCOLORIGEM = TITMMOV.CODCOLIGADA)
LEFT JOIN GCCUSTO							(NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN TMOVCOMPL							(NOLOCK) ON (TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA)

/* DADOS DA ODC */

LEFT JOIN TITMMOV		AS TITMMOV_ODC		(NOLOCK) ON (TITMMOV_ODC.IDMOV = TITMMOVRELAC.IDMOVDESTINO AND TITMMOV_ODC.NSEQITMMOV = TITMMOVRELAC.NSEQITMMOVDESTINO AND TITMMOV_ODC.CODCOLIGADA = TITMMOVRELAC.CODCOLDESTINO)
LEFT JOIN TMOV			AS TMOV_ODC			(NOLOCK) ON (TMOV_ODC.IDMOV = TITMMOV_ODC.IDMOV AND TMOV_ODC.CODCOLIGADA = TITMMOV_ODC.CODCOLIGADA)
LEFT JOIN FCFO								(NOLOCK) ON (FCFO.CODCFO = TMOV_ODC.CODCFO AND FCFO.CODCOLIGADA = TMOV_ODC.CODCOLCFO)
LEFT JOIN TITMMOVRELAC  AS TITMMOVRELAC_ODC	(NOLOCK) ON (TITMMOVRELAC_ODC.IDMOVORIGEM = TITMMOV_ODC.IDMOV AND TITMMOVRELAC_ODC.NSEQITMMOVORIGEM = TITMMOV_ODC.NSEQITMMOV AND TITMMOVRELAC_ODC.CODCOLORIGEM = TITMMOV_ODC.CODCOLIGADA)
LEFT JOIN TMOVCOMPL		AS TMOVCOMPL_ODC	(NOLOCK) ON (TMOV_ODC.IDMOV = TMOVCOMPL_ODC.IDMOV AND TMOVCOMPL_ODC.CODCOLIGADA = TMOV_ODC.CODCOLIGADA)
LEFT JOIN GFILIAL                           (NOLOCK) ON (TMOV_ODC.CODCOLIGADA = GFILIAL.CODCOLIGADA AND TMOV_ODC.CODFILIAL = GFILIAL.CODFILIAL)

/*DADOS DA NOTA */

LEFT JOIN TITMMOV		AS TITMMOV_NOTA		(NOLOCK) ON (TITMMOV_NOTA.IDMOV = TITMMOVRELAC_ODC.IDMOVDESTINO AND TITMMOV_NOTA.NSEQITMMOV = TITMMOVRELAC_ODC.NSEQITMMOVDESTINO AND TITMMOV_NOTA.CODCOLIGADA = TITMMOVRELAC_ODC.CODCOLDESTINO)
LEFT JOIN TMOV			AS TMOV_NOTA		(NOLOCK) ON (TMOV_NOTA.IDMOV = TITMMOV_NOTA.IDMOV AND TMOV_NOTA.CODCOLIGADA = TITMMOV_NOTA.CODCOLIGADA)

/* VALOR TOTAL */
LEFT JOIN TTRBMOV							(NOLOCK) ON (TITMMOV.IDMOV = TTRBMOV.IDMOV AND TITMMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TTRBMOV.NSEQITMMOV = TITMMOV.NSEQITMMOV AND TTRBMOV.CODTRB = 'IPI')

WHERE	TMOV.CODTMV IN ('1.1.18','1.1.20','1.1.25','1.1.34')
AND		TMOV.STATUS <> 'C'
AND		TMOV.CODCOLIGADA IN (@CODCOLIGADA)
--AND 	TMOV.CODCCUSTO IN (@CCUSTO_INI_S)
AND		TMOV_ODC.DATAENTREGA BETWEEN @DATA_SOLICITACAO_INI_D AND @DATA_SOLICITACAO_FIN_D
--AND 	TPRD.CODIGOPRD BETWEEN @COD_PRODUTO_INI_S AND @COD_PRODUTO_FIN_S

GROUP BY

/* DADOS DA SOLICITAÇÃO*/
tmov.CODCOLIGADA,
tmov.CODFILIAL,
GCCUSTO.NOME,
TMOV.IDMOV,
TMOV.NUMEROMOV,
TMOV.CODTMV,
TMOV.DATACRIACAO,
TMOV.CODCCUSTO,

TMOV.STATUS,
TPRD.CODIGOPRD,
TPRD.NOMEFANTASIA,
TITMMOV.CODUND,
TMOVCOMPL.URGENCIA,
TITMMOV.IDPRD,

/* DADOS DA ODC */

TMOV_ODC.IDMOV,
TMOV_ODC.DATAENTREGA,
TMOV_ODC.NUMEROMOV,
TMOV_ODC.CODTMV,
TMOV_ODC.DATACRIACAO,
TMOV_ODC.STATUS,
FCFO.NOMEFANTASIA,
TITMMOV_ODC.NSEQITMMOV,
TITMMOV_ODC.PRECOUNITARIO,
TITMMOV_ODC.QUANTIDADETOTAL,
TITMMOV_ODC.QUANTIDADETOTAL,
TITMMOV_ODC.QUANTIDADE,
TITMMOV_ODC.QUANTIDADE,
TMOVCOMPL_ODC.REGULARIZACAO,
TMOV_ODC.VALORLIQUIDO,
GFILIAL.ESTADO,
TMOV_ODC.RECCREATEDBY,

/*DADOS DA NOTA*/

TMOV_NOTA.IDMOV,
TMOV_NOTA.NUMEROMOV,
TMOV_NOTA.CODTMV ,
TMOV_NOTA.DATACRIACAO,
TMOV_NOTA.DATAEMISSAO,
TMOV_NOTA.STATUS,
TITMMOV_NOTA.PRECOUNITARIO,
TITMMOV_NOTA.QUANTIDADETOTAL,
TMOV_NOTA.VALORBRUTOORIG,
TMOV_NOTA.VALORDESC,
TITMMOV_NOTA.VALORDESC,

/* CALCULO VALOR TOTAL */
TITMMOV.PRECOUNITARIO,
TMOV.VALORBRUTOORIG,
TTRBMOV.VALOR,
TITMMOV.QUANTIDADETOTAL,
TMOV.VALORBRUTO,
TMOV.VALORFRETE


 ) AS GRUPO

ORDER BY  GRUPO.NOMEFANTASIA



