/* DE OBRA */
SELECT CODTRF,
MTAREFA.DESCRICAO,
CODTRF + ' - ' + MTAREFA.nome AS NOMETAREFA,
MTAREFA.IDPRJ

FROM MTAREFA (NOLOCK)
INNER JOIN MPRJ ON MPRJ.CODCOLIGADA = MTAREFA.CODCOLIGADA AND MPRJ.IDPRJ = MTAREFA.IDPRJ

WHERE MTAREFA.CODCOLIGADA= @codcoligada
AND CODPRJ=@codprj
AND CODTRF >=LEFT(@codtrfini ,3)
AND REVISAO = @revisao

/*
WHERE MTAREFA.CODCOLIGADA=39
AND CODPRJ= 'SP.2024.001' 
AND CODTRF = '011'
and revisao = 2
--AND CODTRF <=LEFT(@CODTRFINI ,3)
*/

ORDER BY 1  ASC
/* ATÉ OBRA */
SELECT top 1 CODTRF, 
CODTRF + ' - ' + MTAREFA.nome AS NOMETAREFA

FROM MTAREFA (NOLOCK)
INNER JOIN MPRJ ON MPRJ.CODCOLIGADA = MTAREFA.CODCOLIGADA AND MPRJ.IDPRJ = MTAREFA.IDPRJ

/*
WHERE MTAREFA.CODCOLIGADA=39
AND CODPRJ= 'SP.2024.001' 
--AND CODTRF <=LEFT(@CODTRFINI ,3)
*/

WHERE MTAREFA.CODCOLIGADA=@codcoligada
AND CODPRJ= @codprj 
AND CODTRF >=LEFT(@codtrfFIM ,3)
AND REVISAO = @revisao


ORDER BY 1 

/* DADOS DO PROJETO */ 
SELECT  
CONCAT(MPRJ.CODPRJ,' - R: ', MPRJ.REVISAO,' - ', MPRJ.DESCRICAO) AS PROJETO, 
MPRJCOMPL.DTBASE,
MPRJCOMPL.CLIFOR, 
MPRJ.CODPRJ,
MPRJ.REVISAO

FROM MPRJ 
INNER JOIN MPRJCOMPL ON MPRJCOMPL.CODCOLIGADA = MPRJ.CODCOLIGADA AND MPRJCOMPL.IDPRJ = MPRJ.IDPRJ

WHERE 
MPRJ.CODCOLIGADA = @codcoligada 
AND  MPRJ.CODPRJ = @codprj 
AND MPRJ.REVISAO = @revisao
ORDER BY MPRJ.REVISAO

/* CODIGO DO PROJETO */ 
SELECT 
CONCAT(MPRJ.CODPRJ,' - R', MPRJ.REVISAO,' - ', MPRJ.DESCRICAO) AS PROJETO,
MPRJ.CODPRJ AS CODPROJETO,
MPRJ.REVISAO AS REVISAO

FROM MPRJ 

WHERE 
MPRJ.CODCOLIGADA = @codcoligada

ORDER BY 3


/* PROJETO */
/* CODIGO DO PROJETO */ 
SELECT 
CONCAT(MPRJ.CODPRJ,' - R', MPRJ.REVISAO,' - ', MPRJ.DESCRICAO) AS PROJETO,
MPRJ.CODPRJ AS CODPROJETO,
MPRJ.REVISAO AS REVISAO

FROM MPRJ (NOLOCK)

WHERE 
MPRJ.CODCOLIGADA = @codcoligada

ORDER BY 3

/* 
=First(Fields!PROJETO.Value, "PROJETO")
=First(Fields!PROJETO.Value, "PRJ_INICIAL")
=First(Fields!PROJETO.Value, "PRJ_FIM")
*/