
SELECT
/* SERVIÇO E PRODUTO */
(CASE WHEN TPRDGRUPOPRODUTO.CODGRUPO IN 
('DPTX','ESCR','CBAL','EQUI','INFO','EPIC','EIND','COMB','PLAC','MVUT','CERC','SERR','MACO','RESR','CACC','MELE','MPIN','INCE','EQUC','ESQU','ELEV','PREM','VEIC','FRMT','PSGM','FERR') THEN 1 ELSE 0 END) AS VALIDA,
/* SERVIÇO */
(CASE WHEN TPRDGRUPOPRODUTO.CODGRUPO IN
('EQUI','EMBA','ESCR','EIND','DPTX','INFO','EPVT','SERR','MEDC','FERR','MELE','MACO','CERC','AGRE','CACC','COBT','COMB','EQUC','INCE','ESQU','MHID','ELEV','SHAF','FRMT','LOUC','MADE','PLAC','REVP','RESR','GESS','EPIC','PSGM','ASFT')AND TPRD.TIPO = 'S' THEN 1 ELSE 0 END) AS VALIDA2

FROM TPRD (NOLOCK)
LEFT JOIN TPRDGRUPOPRODUTO (NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = TPRD.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = TPRD.CODCOLIGADA)
WHERE TPRD.CODCOLIGADA =:FRM_COLIGITM
AND TPRD.IDPRD =:FRM_IDPRD

