 USE FUSION
 SELECT CANCELAR,
 TMOV.STATUS, 
 TMOV.CODTMV,* 
 FROM D_FRMNOTAFISCAL (NOLOCK)
 INNER JOIN CORPORE_RESIDENCIAL..TMOV AS TMOV (NOLOCK) ON (TMOV.CODCOLIGADA = D_FRMNOTAFISCAL.CODCOLIGADA AND TMOV.IDMOV = D_FRMNOTAFISCAL.IDENTIFICADOR) 
 WHERE D_FRMNOTAFISCAL.IDENTIFICADOR = 2214067 AND D_FRMNOTAFISCAL.CODCOLIGADA = 1



 --ROLLBACK--COMMITBEGIN TRAN UPDATE D_frmNotaFiscal SET CANCELAR = 1 FROM D_frmNotaFiscal (NOLOCK)INNER JOIN CORPORE_RESIDENCIAL..TMOV AS TMOV (NOLOCK) ON (TMOV.CODCOLIGADA = D_frmNotaFiscal.CODCOLIGADA AND TMOV.IDMOV = D_frmNotaFiscal.IDENTIFICADOR) WHERETMOV.STATUS = 'A' AND D_frmNotaFiscal.IDENTIFICADOR = 27763 and D_frmNotaFiscal.CODCOLIGADA = 51 