-- SALDOS E CUSTOS QUE NÃO RODARAM

SELECT *
FROM GJOBXEXECUCAO
WHERE 
    --
	GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%saldos%' and codusuario = 'job') 
	AND PERCPROGRESSO < 100
	AND (DATAFIMEXEC IS NULL OR DATAFIMEXEC < DATEADD(DAY, -1, CAST(GETDATE() AS DATE)))

	ORDER BY GJOBXEXECUCAO.DATAFIMEXEC DESC

-- XML QUE NÃO RODARAM

SELECT *
FROM GJOBXEXECUCAO
INNER JOIN GJOBX ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB
WHERE 
    --
	GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%Importação de Arquivos%'  and codusuario = 'job') 
	AND PERCPROGRESSO < 100
	AND (DATAFIMEXEC IS NULL OR DATAFIMEXEC < DATEADD(DAY, -1, CAST(GETDATE() AS DATE)))

	ORDER BY GJOBXEXECUCAO.DATAFIMEXEC DESC

SELECT *
FROM GJOBXEXECUCAO
INNER JOIN GJOBX ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB
WHERE 
    --
	GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%Serviço%Consulta%XML%'   and codusuario = 'job') 
	AND PERCPROGRESSO < 100
	AND (DATAFIMEXEC IS NULL OR DATAFIMEXEC < DATEADD(DAY, -1, CAST(GETDATE() AS DATE)))

	ORDER BY GJOBXEXECUCAO.DATAFIMEXEC DESC


-- PIX QUE NAO RODARAM 

SELECT *
FROM GJOBXEXECUCAO
INNER JOIN GJOBX ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB
WHERE 
    --
	GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%ajust%transa%' and codusuario = 'job') 
	AND PERCPROGRESSO < 100
	AND (DATAFIMEXEC IS NULL OR DATAFIMEXEC < DATEADD(DAY, -1, CAST(GETDATE() AS DATE)))

	ORDER BY GJOBXEXECUCAO.DATAFIMEXEC DESC


SELECT *
FROM GJOBXEXECUCAO
INNER JOIN GJOBX ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB
WHERE 
    --
	GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like 'Importação do Arquivo de Conciliação' and codusuario = 'job') 
	AND PERCPROGRESSO < 100
	AND (DATAFIMEXEC IS NULL OR DATAFIMEXEC < DATEADD(DAY, -1, CAST(GETDATE() AS DATE)))

	ORDER BY GJOBXEXECUCAO.DATAFIMEXEC DESC