WITH PRODUTO AS (
    SELECT 
        TMOV.CODCOLIGADA,
        TMOV.IDMOV,
        TITMMOV.IDPRJ,
        TITMMOV.IDTRF,
        TITMMOV.IDPRD,
        TITMMOVCOMPL.ID_REQUISICAO_RMO,
        TMOV.RECCREATEDON
    FROM CORPORE_RESIDENCIAL..TMOV (NOLOCK)
    INNER JOIN CORPORE_RESIDENCIAL..TITMMOV (NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
    INNER JOIN CORPORE_RESIDENCIAL..TITMMOVCOMPL (NOLOCK) ON TITMMOV.CODCOLIGADA = TITMMOVCOMPL.CODCOLIGADA AND TITMMOV.IDMOV = TITMMOVCOMPL.IDMOV AND TITMMOV.NSEQITMMOV = TITMMOVCOMPL.NSEQITMMOV
    WHERE TMOV.RECCREATEDON > '20250501'
)

SELECT 
    P1.CODCOLIGADA,
    P1.IDMOV AS IDMOV_1,
    P2.IDMOV AS IDMOV_2,
    P1.IDPRJ,
    P1.IDTRF,
    P1.IDPRD,
    P1.ID_REQUISICAO_RMO,
    P1.RECCREATEDON AS CRIACAO1,
    P2.RECCREATEDON AS CRIACAO2
FROM PRODUTO P1
INNER JOIN PRODUTO P2 ON P1.CODCOLIGADA = P2.CODCOLIGADA AND P1.IDPRJ = P2.IDPRJ AND P1.IDTRF = P2.IDTRF AND P1.IDPRD = P2.IDPRD 
      AND P1.ID_REQUISICAO_RMO = P2.ID_REQUISICAO_RMO AND P1.IDMOV = P2.IDMOV - 1 AND DATEDIFF(SECOND, P1.RECCREATEDON, P2.RECCREATEDON) BETWEEN 0 AND 20
WHERE P1.ID_REQUISICAO_RMO IS NOT NULL

ORDER BY 1, 2 