DECLARE @MES_APROV AS VARCHAR(10) = 'OUT',
		@COLIGADA AS INT = 51,
		@CCUSTO_INI AS VARCHAR(10) = '3.0001.05',
		@DATAINI_D AS DATE = '20241001',
		@DATAFIM_D AS DATE = '20241201';
	
SELECT
(CASE GRUPO.CLASE 
		WHEN 'MT' THEN 'MATERIAL' 
		WHEN 'EQ' THEN 'EQUIPAMENTO' 
		WHEN 'ST' THEN 'SERVIÇOS DE TERCEIROS'
		WHEN 'CI' THEN 'CUSTO INDIRETO'
		WHEN 'CIC' THEN 'CUSTO INDIRETO COMERCIAL'
	ELSE''
END) AS DESC_CLASSE,
GRUPO.CENTRO_CUSTO_NOME,
GRUPO.NOME_PROJETO,
GRUPO.DESCRICAO,
GRUPO.COLIGADA,
GRUPO.QUEBRA$,
GRUPO.CODCQ,
GRUPO.MES_APROV,
GRUPO.ANO_APROV,
GRUPO.CODCCUSTO,
GRUPO.CODIGOPRD,
GRUPO.FASE,
GRUPO.CLASE,
GRUPO.SUB_CLASSE,
GRUPO.DESC_SUB_CLASSE,
GRUPO.DESC_GRUPO,
GRUPO.DESC_INS,
GRUPO.NOME_FORNECEDOR,
GRUPO.NUMEROMOV,
GRUPO.DATAEMISSAO,
GRUPO.VALOR,
GRUPO.CODTMV,
GRUPO.STATUS,
GRUPO.USUARIOCRIACAO,
GRUPO.DATACRIACAO,
GRUPO.USUARIO_APROVACAO,
GRUPO.DATAAPROVACAO,
GRUPO.DATAPG,
GRUPO.IDMOV,
GRUPO.REFERENCIA_PGTO,
GRUPO.HISTORICO_PGTO,
GRUPO.CODTRF,
GRUPO.DESCTRF,
GRUPO.CODTRF_PAI,
GRUPO.DESCTRFPAI,
GRUPO.CODGRUPO, 
GRUPO.UND_PROD,
GRUPO.QTD,
GRUPO.PRECO_UNIT,
GRUPO.DESCRICAO_GRUPO,
GRUPO.NOME_PRODUTO,
GRUPO.CODCOLIGADA,
GRUPO.CODTMV_ORIGEM,
grupo.cod_cc
FROM(

SELECT 
T.CODCCUSTO AS CENTRO_CUSTO_NOME,
(SELECT CONVERT(VARCHAR,PRJ.CODPRJ)+' - '+ CONVERT(VARCHAR,PRJ.DESCRICAO) AS NOME_PROJETO  FROM MPRJ AS PRJ WHERE PRJ.IDPRJ = T.IDPRJ AND  PRJ.CODCOLIGADA = T.CODCOLIGADA) AS NOME_PROJETO,
T.DESCRICAO,
(SELECT TOP 1 COLIGA.NOMEFANTASIA FROM GCCUSTO (NOLOCK) AS CUSTO, GCOLIGADA AS COLIGA WHERE  CUSTO.CODCOLIGADA = T.CODCOLIGADA AND CUSTO.CODCCUSTO = T.CODCCUSTO AND T.CODCOLIGADA = COLIGA.CODCOLIGADA) AS COLIGADA,
DBO.ULTIMODIAMES(GETDATE())AS QUEBRA$,
CODCQ,
/*DATEPART(MONTH,DATAAPROVACAO) AS MES_APROV,*/
@MES_APROV AS MES_APROV,
(CASE WHEN DATEPART(YEAR,DBO.TRAZ_DATAAPROVACAO (CODCOLIGADA,IDMOV)) IS NOT NULL THEN 'RDO' ELSE '' END) AS ANO_APROV,
CODCCUSTO,
CODIGOPRD,
FASE,


(CASE 
	WHEN CODCLASSIFICA IN (10, 4, 6) THEN 'CIC'
	WHEN CODCLASSIFICA = 3 THEN 'CI' 
	WHEN CODTMV IN ('1.1.06', '1.1.40', '1.1.41', '1.1.42', '1.1.43') AND CODTMV_ORIGEM = '1.1.06' THEN 'ST'
	/*WHEN CODTMV = '1.1.27' AND ID_REQUISICAO_RMO IS NULL THEN 'MT'*/
		 WHEN SUB_CLASSE IN ('AC','ADM','AL','ALM','ALT','ATAE','ATE','ATEC','ATEL','ATH','ATIN','ATPO','AT-PO','ATRC','ATT','AUAX','AUD','C','CA','CO','CP','DBC','DF','DI','DRE','DVR','EPC',
                         'EX','EXT','EXTEL','FX','HB','I TX','LC','LD','MA','MAP','MC','ME','MMI','MOI','MOL','MOS','MTO','OTR','PJ','RP','S','SO','TFSLQA','TI','TO','TR','TX','V','VT') THEN 'CI'
	WHEN SUB_CLASSE IN  ('IPDV','MKTC','MKTIN','MKTM','MKTOUT','MKTPD','MKTPM','MKTPP','MKTPPI','MKTRE','MKTRV','MKTSI','MPDV','PBL','PBO','SMAQ','SV','SVC','SVF','SVM','SVP','SVS','VD') THEN 'CIC'
	WHEN LEFT(CODIGOPRD,3) = '001' THEN 'MT'
	WHEN LEFT(CODIGOPRD,3) = '002' THEN 'ST'
	WHEN LEFT(CODIGOPRD,3) = '003' THEN 'EQ'
	WHEN LEFT(CODIGOPRD,3) = '999' THEN [dbo].[CLASSEPORFASE](SUB_CLASSE)
	ELSE 'SEM CLASSE' END) AS 'CLASE',

SUB_CLASSE,
DESC_SUB_CLASSE,
DESC_GRUPO,
DESC_INS,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,
SUM(VALOR) AS 'VALOR',
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
/*USUARIO_APROVACAO,
DATAAPROVACAO,*/
DBO.APROVADOR_MOVIMENTO(CODCOLIGADA,IDMOV) AS USUARIO_APROVACAO,
DBO.TRAZ_DATAAPROVACAO (CODCOLIGADA,IDMOV)AS DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
CODGRUPO, 
UND_PROD,
QTD,
PRECO_UNIT,
DESCRICAO_GRUPO,
T.NOME_PRODUTO
,T.CODCOLIGADA
,ISNULL(CODTMV_ORIGEM,'N/A') AS CODTMV_ORIGEM,
NUMEROSEQUENCIAL,
cod_cc

FROM (
		SELECT 
		CODCQ, 
		TMOV.IDMOV, 
		MTRF.CODCOLIGADA,
		MPRJ.DESCRICAO,
		TMOV.IDPRJ,
		
		(CASE WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN (CONVERT(VARCHAR(10),TMOVRATCCU.CODCCUSTO) + ' - ' + (CCCUSTORAT.NOME)) ELSE (CONVERT(VARCHAR(10),TMOV.CODCCUSTO) + ' - ' + CCUSTONOR.NOME) END) AS CODCCUSTO,
		TMOVRATCCU.CODCCUSTO as 'cod_cc',
		MTRF.CODTRF,
		ISNULL (MTRF.NOME,MTRF.DESCRICAO) AS DESCTRF,
		MTRFPAI.CODTRF AS CODTRF_PAI,
		ISNULL (MTRFPAI.NOME,MTRFPAI.DESCRICAO) AS DESCTRFPAI,
		TITMMOV.CODUND AS 'UND_PROD',
		(CASE WHEN (SELECT COUNT (*) FROM TITMMOVRATCCU WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV ) > 1 
			THEN

	  			(CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)
						*
				((CASE WHEN TITMMOVRATCCU.VALOR = '0' OR TITMMOVRATCCU.VALOR IS NULL THEN TITMMOVRATCCULOGFAT.VALOR ELSE TITMMOVRATCCU.VALOR END)  * 100 / (TITMMOV.PRECOUNITARIO * (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END))/100)
			

			ELSE
				(CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)
		END) AS QTD,
		TITMMOV.PRECOUNITARIO AS 'PRECO_UNIT',
		(SELECT NOMEFANTASIA FROM TPRD (NOLOCK) WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =TMOV.CODCOLIGADA) AS DESC_GRUPO,
		(SELECT TTB22.DESCRICAO 
		FROM TTB2 AS TTB22
		WHERE TTB22.CODCOLIGADA = PRODUTO_DEF.CODCOLIGADA AND TTB22.CODTB2FAT = PRODUTO_DEF.CODTB2FAT) AS 'DESC_INS',
		ISNULL(FCFO.NOMEFANTASIA,'') AS NOME_FORNECEDOR,
		TMOV.NUMEROMOV,
		CONVERT(VARCHAR,DATEADD(D,(SELECT TOP 1 PRAZO1 FROM TCPG (NOLOCK) WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND CODCPG = TMOV.CODCPG),TMOV.DATAEMISSAO),103) AS DATAPG,
		PRODUTO.NOMEFANTASIA AS NOME_PRODUTO,
		PRODUTO.CODIGOPRD,

CASE WHEN 

		(SELECT COUNT (*)FROM TMOV CONTA (NOLOCK)
		LEFT JOIN TITMMOV CONTAITEM ON CONTA.CODCOLIGADA = CONTAITEM.CODCOLIGADA AND CONTA.IDMOV = CONTAITEM.IDMOV
		 WHERE TMOV.IDMOV = CONTA.IDMOV AND TMOV.CODCOLIGADA = CONTA.CODCOLIGADA )>1
		 
		THEN
		
		/* PREÇO MÉDIO DO ITEM FOI MULTIPLICADO PELO RATEIO (CASO TENHA RATEIO) PARA TRAZER O VALOR CORRETO BY MARCELO WAGNER 04-12-2018 */
		
			CASE WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN
		
							((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
							(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV (NOLOCK) WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
							CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
							ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
							)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 
		
								*
		
							((CASE WHEN TMOVRATCCU.VALOR = '0' OR TMOVRATCCU.VALOR IS NULL THEN TMOVRATCCULOGFAT.VALOR ELSE TMOVRATCCU.VALOR END)  * 100 / (TMOV.VALORLIQUIDOORIG)/100)
		
			ELSE
		
			
							((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
							(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV (NOLOCK) WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
							CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
							ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
							)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 
			END
		
			/* FIM DA ALTERACAO */
		WHEN 
		
		(SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1
		
		THEN 
		
		(CASE WHEN TMOVRATCCU.VALOR = '0' OR TMOVRATCCU.VALOR IS NULL THEN TMOVRATCCULOGFAT.VALOR ELSE TMOVRATCCU.VALOR END)
		
		ELSE
		
		TMOV.VALORLIQUIDOORIG

END
AS VALOR,
CASE WHEN CCCUSTORAT.CODCLASSIFICA IS NULL THEN CCUSTONOR.CODCLASSIFICA ELSE CCCUSTORAT.CODCLASSIFICA END AS 'CODCLASSIFICA',

CONVERT(VARCHAR, TMOV.DATACRIACAO,103) AS CRIACAO,

(SELECT NOMEFANTASIA FROM TPRD (NOLOCK)WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =1)AS PRODUTO,
ISNULL(LEFT((SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA),4),'') AS SUB_CLASSE,

ISNULL((SELECT DESCRICAO FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA),'') AS DESC_SUB_CLASSE,


case 
	when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
		and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
		and codcoligada = TMOV.CODCOLIGADA) in	('AC','ALT','AUD','C','CO','CP','DBC','EPI','FX','HB','MA','MMI','MOI','MOL',
												'MOS','PJ','RP','S','TO','TR','TX','USI','V')
		
		then 'CI'  when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
		and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
		and codcoligada = TMOV.CODCOLIGADA) in('APE','CG','CMD','ITB','MKT - CP','MKT - CP','MKT - PROD','MKT - PROM','PBL','PBO','SV','VD')
		
		then 'CIC' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
					and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
					and codcoligada = TMOV.CODCOLIGADA) IN( 'T','FER','AL-EQ')
		then 'EQ' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) and codcoligada = TMOV.CODCOLIGADA) = 'AND'
		then 'MT' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) and codcoligada = TMOV.CODCOLIGADA) IN('CT','AL-ST')
		then 'ST' else
		case when left(produto.CODIGOPRD,1) = 'D' then 'CI' else
			case when left(produto.CODIGOPRD,1) = 'M' then 'MT' else
			case when left(produto.CODIGOPRD,1) = 'S' then 'ST' else
			case when left(produto.CODIGOPRD,1) = 'E' then 'EQ' else
			case when left(produto.CODIGOPRD,1) = 'T' then 'MT' else
			case when left(produto.CODIGOPRD,1) = 'A' then 'ST'
			end
		end
			END
			end
			end
			end
		end
		END
		END
END AS 'FASE',

TMOV.CODTMV,
DBO.TRAZ_STATUS(TMOV.STATUS) AS STATUS,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
TMOVCOMPL.ID_REQUISICAO_RMO,
/*TMOVAPROVA.CODUSUARIO AS USUARIO_APROVACAO,
TMOVAPROVA.DATAAPROVACAO,*/
TMOV.DATAEMISSAO,
TPRDGRUPOPRODUTO.CODGRUPO,
(TGRUPOPRODUTO.CODGRUPO + ' - ' + TGRUPOPRODUTO.DESCRICAO) AS 'DESCRICAO_GRUPO',

(SELECT TOP 1 FLAN.IDLAN FROM FLAN (NOLOCK)
	LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
	WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
	AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
	AND		FLAN.CODTB2FLX NOT IN ('129','02.023')
) AS REFERENCIA_PGTO,

(SELECT TOP 1 REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLAN.HISTORICO),CHAR(13) + CHAR(10),' '),';',' ') FROM FLAN (NOLOCK)
	LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
	WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
	AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
	AND		FLAN.CODTB2FLX NOT IN ('129','02.023')
) AS HISTORICO_PGTO,

(SELECT TOP 1 MOVT.CODTMV
	FROM TMOVRELAC (NOLOCK)
	INNER JOIN TMOV AS MOVT (NOLOCK) ON (MOVT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOVT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
	WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV  AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA
) AS CODTMV_ORIGEM ,
TITMMOV.NUMEROSEQUENCIAL

FROM TMOV (NOLOCK)

INNER JOIN TITMMOV 						(NOLOCK) on (TMOV.IDMOV = TITMMOV.IDMOV and TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT  JOIN TMOVRATCCU					(NOLOCK) ON (TMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCU.IDMOV = TMOV.IDMOV)
LEFT JOIN TMOVRATCCULOGFAT				(NOLOCK) ON (TMOVRATCCULOGFAT.IDMOVRATCCU = TMOVRATCCU.IDMOVRATCCU AND TMOVRATCCULOGFAT.IDMOV = TMOV.IDMOV AND TMOVRATCCULOGFAT.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TMOVRATCCULOGFAT FAT WHERE TMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TMOVRATCCULOGFAT.IDMOVRATCCU))
left JOIN MPRJ 							(NOLOCK) ON (ISNULL(TMOVRATCCU.CODCOLIGADA,TITMMOV.CODCOLIGADA) = MPRJ.CODCOLIGADA AND ISNULL(TMOVRATCCU.IDPRJ,TITMMOV.IDPRJ) = MPRJ.IDPRJ )
LEFT JOIN MPRJCOMPL 					(NOLOCK) on (MPRJ.CODCOLIGADA = MPRJCOMPL.CODCOLIGADA and MPRJ.IDPRJ = MPRJCOMPL.IDPRJ)
LEFT JOIN MTRF 							(NOLOCK) on (MTRF.CODCOLIGADA = TITMMOV.CODCOLIGADA AND MTRF.IDPRJ = TITMMOV.IDPRJ  AND TITMMOV.IDTRF = MTRF.IDTRF)
LEFT JOIN MTRF AS MTRFPAI 				(NOLOCK) ON (MTRFPAI.IDTRF = MTRF.IDPAI AND MTRFPAI.IDPRJ = MTRF.IDPRJ AND MTRFPAI.CODCOLIGADA = MTRF.CODCOLIGADA)												
INNER JOIN TPRD  as produto				(NOLOCK) on (produto.CODCOLIGADA = TITMMOV.CODCOLIGADA and produto.IDPRD = TITMMOV.IDPRD)
INNER JOIN TPRODUTODEF as PRODUTO_DEF	(NOLOCK) ON (PRODUTO_DEF.IDPRD = PRODUTO.IDPRD AND PRODUTO_DEF.CODCOLIGADA = PRODUTO.CODCOLIGADA) 
LEFT JOIN TPRDGRUPOPRODUTO				(NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = produto.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = produto.CODCOLIGADA)
LEFT JOIN TGRUPOPRODUTO					(NOLOCK) ON (TGRUPOPRODUTO.CODCOLIGADA = TPRDGRUPOPRODUTO.CODCOLPRD AND TGRUPOPRODUTO.CODGRUPO = TPRDGRUPOPRODUTO.CODGRUPO)
LEFT JOIN FCFO 							(NOLOCK) on (TMOV.CODCOLCFO = FCFO.CODCOLIGADA and TMOV.CODCFO = FCFO.CODCFO)
LEFT JOIN TITMMOVRATCCU					(NOLOCK) ON (TITMMOVRATCCU.IDMOV = TMOV.IDMOV AND TITMMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV)
LEFT JOIN TITMMOVRATCCULOGFAT			(NOLOCK) ON (TITMMOVRATCCULOGFAT.NSEQITMMOV= TITMMOVRATCCU.NSEQITMMOV AND TITMMOVRATCCULOGFAT.IDMOVRATCCU = TITMMOVRATCCU.IDMOVRATCCU AND TITMMOVRATCCULOGFAT.IDMOV = TITMMOVRATCCU.IDMOV AND TITMMOVRATCCULOGFAT.CODCOLIGADA = TITMMOVRATCCU.CODCOLIGADA AND TITMMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TITMMOVRATCCULOGFAT FAT WHERE TITMMOVRATCCULOGFAT.NSEQITMMOV = FAT.NSEQITMMOV AND TITMMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TITMMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TITMMOVRATCCULOGFAT.IDMOVRATCCU))

/*LEFT JOIN TMOVAPROVA 		(NOLOCK) ON (TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)*/
/* JOIN PARA A NOVA FORMULA DE FASE */
INNER JOIN GCCUSTO AS CCUSTONOR			(NOLOCK) ON (TMOV.CODCCUSTO = CCUSTONOR.CODCCUSTO AND TMOV.CODCOLIGADA = CCUSTONOR.CODCOLIGADA)
INNER JOIN GCCUSTO AS CCCUSTORAT		(NOLOCK) ON (TITMMOVRATCCU.CODCCUSTO = CCCUSTORAT.CODCCUSTO AND TITMMOVRATCCU.CODCOLIGADA = CCCUSTORAT.CODCOLIGADA)
INNER JOIN TMOVCOMPL					(NOLOCK) ON (TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA)

WHERE 
TMOV.CODCOLIGADA IN (@COLIGADA)
/*AND MPRJ.CODPRJ IN (@CODPRJ)*/
AND (MPRJ.CODPRJ LIKE '__.____.___' OR MPRJ.CODPRJ LIKE 'VIAB.__.____.___')

AND (

		/*CASE WHEN CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.64','1.1.15') 
				and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) > 0
			THEN (SELECT count(*) FROM TMOVAPROVA (NOLOCK) WHERE 
									TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and
									TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1) 
		
			WHEN CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  
				AND (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) = 0 
				OR CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  
				AND (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) is null
			
			THEN (SELECT count(*) FROM TMOVAPROVA (NOLOCK) WHERE 
					TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and
					TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)
		
		END > 0*/

		case when CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.64','1.1.15') and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) > 0
then (SELECT COUNT (DBO.TRAZ_DATAAPROVACAO (MOV.CODCOLIGADA,MOV.IDMOV)) FROM TMOV AS MOV WHERE TMOV.IDMOV = MOV.IDMOV AND TMOV.CODCOLIGADA = MOV.CODCOLIGADA)

when CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) = 0 or CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) is null
then (SELECT COUNT (DBO.TRAZ_DATAAPROVACAO (MOV.CODCOLIGADA,MOV.IDMOV)) FROM TMOV AS MOV WHERE TMOV.IDMOV = MOV.IDMOV AND TMOV.CODCOLIGADA = MOV.CODCOLIGADA)

END > 0
 
	)

AND (CASE 
		WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 
		THEN TITMMOVRATCCU.CODCCUSTO 
		ELSE TMOV.CODCCUSTO 
	END) IN (@CCUSTO_INI)
	

AND DBO.TRAZ_DATAAPROVACAO (TMOV.CODCOLIGADA,TMOV.IDMOV) BETWEEN @DATAINI_D AND dateadd(day,1,@DATAFIM_D)
and tmov.STATUS <> 'C'
AND (TITMMOV.QUANTIDADE > 0 OR TITMMOV.QUANTIDADETOTAL > 0)
) as t
GROUP BY 
CODCCUSTO,
CODCQ,
FASE,
SUB_CLASSE,
DESC_SUB_CLASSE,
DESC_GRUPO,
DESC_INS,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
/*USUARIO_APROVACAO,
DATAAPROVACAO,*/
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
CODGRUPO, 
DESCRICAO_GRUPO,
DESCTRF,
UND_PROD,
QTD,
CODCLASSIFICA,
ID_REQUISICAO_RMO,
PRECO_UNIT,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO
,CODTMV_ORIGEM
,T.CODCOLIGADA
,T.DESCRICAO
,T.IDPRJ
,t.CODIGOPRD
,DBO.APROVADOR_MOVIMENTO(CODCOLIGADA,IDMOV)
,DBO.TRAZ_DATAAPROVACAO(CODCOLIGADA,IDMOV)
,NUMEROSEQUENCIAL,
cod_cc
) AS GRUPO
ORDER BY DATAPG