--commit
--rollback

BEGIN TRAN 

DECLARE @CODCOLIGADA INT = 1
DECLARE @MIN_IMP INT = 33 /*rodar daqui a 2 min*/
DECLARE @MIN_CON INT = 35 /*rodar daqui a 4 min*/
DECLARE @MIN_PIX INT = 6
DECLARE @MIN_PIX2 INT = 11

--DECLARE @MULTIPLICADOR INT = 1
--DECLARE @DATA_INICIAL DATETIME = FORMAT(GETDATE(), 'yyyy-MM-dd 20:00')
DECLARE @MAX INT = (SELECT MAX(CODCOLIGADA) FROM GCOLIGADA)

WHILE @CODCOLIGADA <= @MAX
BEGIN
 IF @CODCOLIGADA = 1 OR @CODCOLIGADA >= 10
 
 BEGIN

  PRINT CONCAT('COLIGADA: ', @CODCOLIGADA)


 UPDATE GJOBXEXECUCAO 
      SET GJOBXEXECUCAO.DATAPROGRAMADA = DATEADD(DAY,1,GJOBXEXECUCAO.DATAPROGRAMADA)
      ,DATAINIEXEC = NULL, DATAFIMEXEC = NULL, PERCPROGRESSO = NULL, STATUS = NULL, EMCANCELAMENTO = NULL, MENSAGEMSTATUS = NULL, TEXTOSTATUS = NULL, TEXTOPROGRESSO = NULL
      --,RECCREATEDBY = 'job', RECCREATEDON = GETDATE(), RECMODIFIEDBY ='job', RECMODIFIEDON = GETDATE()
      ,EXCECAO = NULL, PROCESSID = NULL, RECTRIGGEDBY = NULL
      ,IDEXECUCAO = (SELECT MAX(GJOBXEXECUCAO.IDEXECUCAO)+1 FROM GJOBXEXECUCAO (NOLOCK)
          INNER JOIN GJOBX (NOLOCK) ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB
           WHERE  GJOBX.CODCOLIGADA = @CODCOLIGADA)
      WHERE 
      GJOBXEXECUCAO.DATAPROGRAMADA = (SELECT 
              MAX(GJOBXEXECUCAO.DATAPROGRAMADA) FROM GJOBXEXECUCAO (NOLOCK)      
              INNER JOIN GJOBX (NOLOCK) ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB         
              WHERE  GJOBX.CODCOLIGADA = @CODCOLIGADA AND GJOBX.NOME = 'Regerar Saldos e Custos' and GJOBX.CODUSUARIO = 'job' )
      AND GJOBXEXECUCAO.IDJOB = (SELECT TOP 1
              GJOBXEXECUCAO.IDJOB FROM GJOBXEXECUCAO (NOLOCK)    
              INNER JOIN GJOBX (NOLOCK) ON GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB         
              WHERE  GJOBX.CODCOLIGADA = @CODCOLIGADA 
              AND GJOBX.NOME = 'Regerar Saldos e Custos' and GJOBX.CODUSUARIO = 'job'
              ORDER BY GJOBXEXECUCAO.IDJOB DESC)

  SET @MULTIPLICADOR +=1
 END
 SET @CODCOLIGADA += 1
 SET @MIN_IMP += 33
 SET @MIN_CON += 35
 SET @MIN_PIX += 2
 SET @MIN_PIX2 += 2
 

END
 