/*DECLARE @SITUACAO_VENDA INT = 40
DECLARE @EMPREENDIMENTO INT = 17675
DECLARE @COLIGADA INT = 1
DECLARE @DATA_VENDA_INI DATE = '20240601'
DECLARE @DATA_VENDA_FIN DATE = '20241023'
*/

SELECT 
GRUPO.CODCOLIGADA,
GRUPO.NOME_COLIGADA,
GRUPO.ESTADO_EMP,
GRUPO.NOME AS 'NOME_EMP', 
GRUPO.COD_PESS_EMPR AS 'COD_EMP',
GRUPO.COMPRADOR1,
GRUPO.PRIMEIRO_FIADOR,
GRUPO.SEGUNDO_FIADOR,
GRUPO.NUM_CONT,
GRUPO.CGCCFO,
GRUPO.NOME_SEGUNDO_COMPRADOR,
GRUPO.CPF_SEGUNDO_COMPRADOR,
GRUPO.NUM_UNID,
GRUPO.NUM_SUB_UNID,
GRUPO.DSC_SIT_VENDA AS 'SITUACAO_VENDA',
GRUPO.RECCREATEDON AS 'RECCREATEDON', /*NÃO FORMATAR ESTE CAMPO*/ 
FORMAT(GRUPO.DAT_CANCELA,'dd/MM/yyyy') AS 'DAT_CANCELA', 
(SELECT COUNT(*) FROM XSUBUNIDADE (NOLOCK) WHERE XSUBUNIDADE.COD_PESS_EMPR = GRUPO.COD_PESS_EMPR) AS 'NUM_UNIDADES',
GRUPO.NUM_VENDA, 
convert(money,GRUPO.VALOR_VENDA) AS 'VALOR_VENDA', 
FORMAT(GRUPO.DAT_VENDA,'dd/MM/yyyy') AS 'DAT_VENDA',

/*A PEDIDOD DA RENATA SILVA - 18/04 - ARTHUR*/
/*SUM (GRUPO.VALOR_CEF_COMPLETO) + dbo.RETORNA_VALORES_CEF_VENDA(GRUPO.CODCOLIGADA,GRUPO.NUM_VENDA) - dbo.RETORNA_VALORES_FGTS_VENDA(GRUPO.CODCOLIGADA,GRUPO.NUM_VENDA) AS 'TOTAL_CEF',*/

CASE 
    WHEN SUM(GRUPO.VALOR_CEF_COMPLETO) + dbo.RETORNA_VALORES_CEF_VENDA(GRUPO.CODCOLIGADA, GRUPO.NUM_VENDA) - dbo.RETORNA_VALORES_FGTS_VENDA(GRUPO.CODCOLIGADA, GRUPO.NUM_VENDA) < 0 THEN 0
    ELSE SUM(GRUPO.VALOR_CEF_COMPLETO) + dbo.RETORNA_VALORES_CEF_VENDA(GRUPO.CODCOLIGADA, GRUPO.NUM_VENDA) - dbo.RETORNA_VALORES_FGTS_VENDA(GRUPO.CODCOLIGADA, GRUPO.NUM_VENDA)
END AS 'TOTAL_CEF',

GRUPO.MODALIDADE_VENDA,
dbo.RETORNA_VALORES_FGTS_VENDA(GRUPO.CODCOLIGADA,GRUPO.NUM_VENDA) AS 'TOTAL_FGTS',
GRUPO.CODCONTRATOCEF,
GRUPO.VALOR_VENDA - 
		(
			SUM (GRUPO.VALOR_CEF_COMPLETO) + 
			dbo.RETORNA_VALORES_CEF_VENDA(GRUPO.CODCOLIGADA,GRUPO.NUM_VENDA)
		)
	AS 'TOTAL_PROPRIO',
		
SUM(VALOR_DESCONTO) AS 'VALOR_DESCONTO',
SUM(VALOR_SINAL) AS 'VALOR_SINAL',
GRUPO.ADITIVO,

GRUPO.DSC_MOD_VENDA

,ISNULL(GRUPO.QTD_PARC_MENSAL,'') AS 'QTD_PARC_MENSAL'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_MENSAL),'') AS 'VALOR_PARC_MENSAL'
,ISNULL(GRUPO.QTD_PARC_MENSAL2,'') AS 'QTD_PARC_MENSAL2'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_MENSAL2),'') AS 'VALOR_PARC_MENSAL2'
,ISNULL(GRUPO.QTD_PARC_MENSAL3,'') AS 'QTD_PARC_MENSAL3'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_MENSAL3),'') AS 'VALOR_PARC_MENSAL3'
,ISNULL(GRUPO.QTD_PARC_SEMESTRAL,'') AS 'QTD_PARC_SEMESTRAL'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_SEMESTRAL),'') AS 'VALOR_PARC_SEMESTRAL'
,ISNULL(GRUPO.QTD_PARC_ANUAL,'') AS 'QTD_PARC_ANUAL'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_ANUAL),'') AS 'VALOR_PARC_ANUAL'
,ISNULL(GRUPO.QTD_PARC_Escritura_ITBI,'') AS 'QTD_PARC_Escritura_ITBI'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_PARC_Escritura_ITBI),'') AS 'VALOR_PARC_Escritura_ITBI'

,ISNULL(GRUPO.QTD_PARC_TX_JUROS_APOS_ENTREGA_ANUAL,'') AS 'QTD_PARC_TX_JUROS_APOS_ENTREGA_ANUAL'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_TX_JUROS_APOS_ENTREGA_ANUAL),'') AS 'VALOR_TX_JUROS_APOS_ENTREGA_ANUAL'

,ISNULL(GRUPO.QTD_PARC_MENSAL_REG,'') AS 'QTD_PARC_MENSAL_REG'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_MENSAL_REG),'') AS 'VALOR_MENSAL_REG'

,ISNULL(GRUPO.QTD_PARC_JUROS_MUTUARIOS_REG,'') AS 'QTD_PARC_JUROS_MUTUARIOS_REG'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_JUROS_MUTUARIOS_REG),'') AS 'VALOR_JUROS_MUTUARIOS_REG'

,ISNULL(GRUPO.QTD_PARC_ADIANT_ESCRITURA_ITBI_REG,'') AS 'QTD_PARC_ADIANT_ESCRITURA_ITBI_REG'
,ISNULL(CONVERT(MONEY,GRUPO.VALOR_ADIANT_ESCRITURA_ITBI_REG),'') AS 'VALOR_ADIANT_ESCRITURA_ITBI_REG'


/*SUBSELECT PARA PEGAR VALOR DE PARCELAS ATRASADAS COM MAIS DE 5 DIAS E SOMA-LAS */
,ISNULL((SELECT
				SUM(VALORFINAL.TOTAL)
				FROM
				(
				SELECT 
				
							'TOTAL'=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
								-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
								INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
								WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
								-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
								INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
								WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			
				
				FROM FLAN (NOLOCK)
				INNER JOIN  XVENDAPARCELA	(NOLOCK) ON (FLAN.IDLAN = XVENDAPARCELA.IDLAN AND FLAN.CODCOLIGADA = XVENDAPARCELA.CODCOLLAN)
				LEFT JOIN	XTIPOPARCELA	(NOLOCK) ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
				
				WHERE FLAN.CODCOLIGADA = GRUPO.CODCOLIGADA 
				AND XVENDAPARCELA.NUMVENDA = GRUPO.NUM_VENDA
				AND XTIPOPARCELA.COD_TIPO_PARC NOT IN (13,26,90,95,101,106)
				AND FLAN.STATUSLAN in (0,4)
				AND FLAN.DATAVENCIMENTO  <   DATEADD(DAY,-5,GETDATE())) AS VALORFINAL),0) AS VALOR_EM_ATRASO,

		GRUPO.COMPONENTE_FINAL, 
		CONVERT(VARCHAR,GRUPO.VENCIMENTO_FINAL,103) AS 'VENCIMENTO FINAL',
		GRUPO.NOME_DA_MODALIDADE,
		dbo.DiferençaDatas(GRUPO.DAT_VENDA,GRUPO.VENCIMENTO_FINAL) AS 'Prazo'
FROM 


(
		SELECT 
		
		GCOLIGADA.CODCOLIGADA,
		XEMPREENDIMENTO.UF AS ESTADO_EMP,
		GCOLIGADA.NOME AS NOME_COLIGADA,
		XEMPREENDIMENTO.NOME,
		XEMPREENDIMENTO.COD_PESS_EMPR,
		FCFO.NOME AS COMPRADOR1,
		(SELECT TOP 1 FCFO.NOME  FROM XCOMPRADOR  (NOLOCK) AS COMPRADOR2
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS NOME_SEGUNDO_COMPRADOR,

		(SELECT TOP 1 FCFO.CGCCFO  FROM XCOMPRADOR (NOLOCK) AS COMPRADOR2 
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS CPF_SEGUNDO_COMPRADOR,

		(SELECT GRUPO.NOM_PESS FROM 
		(
			SELECT 
			ROW_NUMBER() OVER(ORDER BY XVENDAFIADOR.NUMVENDA) AS CONT,
			XPESSOA.NOM_PESS 
			FROM XVENDAFIADOR (NOLOCK)
			INNER JOIN XPESSOA (NOLOCK) ON (XPESSOA.COD_PESS = XVENDAFIADOR.CODFIADOR)
			WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
		) AS GRUPO
		WHERE GRUPO.CONT = 1) AS PRIMEIRO_FIADOR,
		(SELECT GRUPO.NOM_PESS FROM 
		(
			SELECT 
			ROW_NUMBER() OVER(ORDER BY XVENDAFIADOR.NUMVENDA) AS CONT,
			XPESSOA.NOM_PESS 
			FROM XVENDAFIADOR (NOLOCK)
			INNER JOIN XPESSOA (NOLOCK) ON (XPESSOA.COD_PESS = XVENDAFIADOR.CODFIADOR)
			WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
		) AS GRUPO
		WHERE GRUPO.CONT = 2) AS SEGUNDO_FIADOR,

		XITEMVENDA.NUM_UNID,
		XITEMVENDA.NUM_SUB_UNID,
		UPPER (XSITUACAOVENDA.DSC_SIT_VENDA) AS DSC_SIT_VENDA,
		XVENDA.RECCREATEDON,  
		XVENDA.DAT_CANCELA,
		XVENDA.VALOR_VENDA , 
		XVENDA.NUM_VENDA AS NUM_VENDA, 
		XMODALIDADEVENDA.DSC_MOD_VENDA,
		CONVERT(VARCHAR, XMODALIDADEVENDA.COD_MOD_VENDA) + ' - ' +XMODALIDADEVENDA.DSC_MOD_VENDA AS MODALIDADE_VENDA,
		XVENDA.DAT_VENDA,
		
		FCFO.CGCCFO,
		XVENDAPARCELA.CODTIPOPARC,

		isnull((CASE 
				WHEN XVENDAPARCELA.CODTIPOPARC in (26,90) AND FLAN.STATUSLAN <> 2 
				THEN ISNULL(FLAN.VALORORIGINAL,0)
				ELSE 0 END
		),0) AS VALOR_CEF_COMPLETO,

		FLAN.STATUSLAN,
		
		(CASE WHEN XVENDAPARCELA.CODTIPOPARC = 101 AND FLAN.STATUSLAN <> 2 
				THEN ISNULL(FLAN.VALORORIGINAL,0) + /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
													CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
																				WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
																						AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
																						AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money)  
				ELSE 0 
				END)  VALOR_DESCONTO,
		(CASE WHEN XVENDAPARCELA.CODTIPOPARC = 1 AND FLAN.STATUSLAN <> 2 THEN ISNULL(FLAN.VALORORIGINAL,0)  ELSE 0 END)  VALOR_SINAL,

		XVENDA.NUM_CONT,
 (
			SELECT TOP 1 XREGRACOMPONENTEVENDA.CODCONTRATOCEF 
			FROM  XREGRACOMPONENTEVENDA (NOLOCK) 
			WHERE XVENDA.NUM_VENDA = XREGRACOMPONENTEVENDA.NUM_VENDA 
			AND XVENDA.CODCOLIGADA = XREGRACOMPONENTEVENDA.CODCOLIGADA 
			AND XREGRACOMPONENTEVENDA.CODCONTRATOCEF IS NOT NULL
		) AS CODCONTRATOCEF,

(
			SELECT TOP 1 XREGRACOMPONENTEVENDA.CODCONTRATOCEF 
			FROM  XREGRACOMPONENTEVENDA (NOLOCK) 
			WHERE XVENDA.NUM_VENDA = XREGRACOMPONENTEVENDA.NUM_VENDA 
			AND XVENDA.CODCOLIGADA = XREGRACOMPONENTEVENDA.CODCOLIGADA 
			AND XREGRACOMPONENTEVENDA.CODCONTRATOCEF  IS NOT NULL
			AND COD_COMPN = 500
			AND COD_GRUPO = 4
) AS ADITIVO

	
		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 2
		) AS 'QTD_PARC_MENSAL'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA IN (XVENDAPARCELA.CODCOLIGADA) AND XREGRACOMPONENTEVENDA.NUM_VENDA IN (XVENDAPARCELA.NUMVENDA) AND XCOMPONENTE.COD_COMPN = 2
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money) AS 'VALOR_PARC_MENSAL'


		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 38
		) AS 'QTD_PARC_MENSAL2'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 38
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_PARC_MENSAL2'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 33
		) AS 'QTD_PARC_MENSAL3'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 39
		)- /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_PARC_MENSAL3'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 29
		) AS 'QTD_PARC_SEMESTRAL'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 29
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_PARC_SEMESTRAL'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 36
		) AS 'QTD_PARC_ANUAL'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 36
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_PARC_ANUAL'

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 99
		) AS 'QTD_PARC_Escritura_ITBI'

		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN /*VALOR*/		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 99
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_PARC_Escritura_ITBI'

/*COMPONENTES NOVOS ADICIONADOS (60,) VIA CHAMADO 1024-000735 */

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 60
		) AS 'QTD_PARC_TX_JUROS_APOS_ENTREGA_ANUAL'

		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN 	
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 60
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_TX_JUROS_APOS_ENTREGA_ANUAL'


		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 61
		) AS 'QTD_PARC_MENSAL_REG'

		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN 	
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 61
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_MENSAL_REG'
				

		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 62
		) AS 'QTD_PARC_JUROS_MUTUARIOS_REG'

		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN 	
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 62
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_JUROS_MUTUARIOS_REG'


		,(SELECT TOP 1 
			XREGRACOMPONENTEVENDA.QTD_PARC		
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 63
		) AS 'QTD_PARC_ADIANT_ESCRITURA_ITBI_REG'

		,(SELECT TOP 1
			XREGRACOMPONENTEVENDA.VR_PARTE_COMPN 	
		FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA =XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 63
		) - /*INSERIDO DESCONTO REALIZADO VIA ADITIVO */
			CAST(ISNULL((SELECT SUM(VALOR) FROM FLANINTEGRACAO (NOLOCK) 
										WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
												AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
												AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS money
				) AS 'VALOR_ADIANT_ESCRITURA_ITBI_REG',
				
				(
				SELECT TOP 1 
				(CONVERT(VARCHAR(MAX),XCOMPONENTE.COD_COMPN) + ' - ' + CONVERT(VARCHAR(MAX),XCOMPONENTE.DSC_COMPN)) as 'COMPONENTE'
				FROM XREGRACOMPONENTEVENDA (NOLOCK)			
				INNER JOIN XCOMPONENTE						(NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
				INNER JOIN XVENDAPARCELA AS XVENDAPARCELA1	(NOLOCK) ON (XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA1.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA = XVENDAPARCELA1.NUMVENDA AND XCOMPONENTE.COD_COMPN NOT IN (99,47,57,58,105,150))
				INNER JOIN FLAN	AS FLAN2					(NOLOCK) ON (FLAN2.IDLAN = XVENDAPARCELA1.IDLAN AND FLAN2.CODCOLIGADA = XVENDAPARCELA1.CODCOLLAN)
				WHERE XVENDAPARCELA1.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA 
				AND XVENDAPARCELA1.NUMVENDA = XVENDAPARCELA.NUMVENDA
				ORDER BY FLAN2.DATAVENCIMENTO DESC
				) AS 'COMPONENTE_FINAL',

				(SELECT TOP 1 MAX(FLAN1.DATAVENCIMENTO)
				FROM XVENDAPARCELA AS XVENDAPARCELA1
				INNER JOIN FLAN AS FLAN1 (NOLOCK) ON (XVENDAPARCELA1.CODCOLIGADA = FLAN1.CODCOLIGADA AND XVENDAPARCELA1.IDLAN = FLAN1.IDLAN)
				WHERE XVENDAPARCELA1.NUMVENDA = XVENDAPARCELA.NUMVENDA ) AS 'VENCIMENTO_FINAL',

				(CASE 
					WHEN XMODALIDADEVENDA.COD_MOD_VENDA IN (1,105,113,116,171,173,207,288,30,31,37,47,53,55,57,61,68,81,89) THEN 'Associativo'
					WHEN (SELECT TOP 1 XCOMPONENTE.COD_COMPN 
						  FROM XREGRACOMPONENTEVENDA (NOLOCK)	
						  INNER JOIN XCOMPONENTE						(NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
						  INNER JOIN XVENDAPARCELA AS XVENDAPARCELA1	(NOLOCK) ON (XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA1.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA = XVENDAPARCELA1.NUMVENDA AND XCOMPONENTE.COD_COMPN NOT IN (99,47,57,58,105,150))
						  WHERE XCOMPONENTE.COD_COMPN = 91 
						  AND XVENDAPARCELA1.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA 
						  AND XVENDAPARCELA1.NUMVENDA = XVENDAPARCELA.NUMVENDA) = 91 THEN 'Financiamento SFH' 
					WHEN XMODALIDADEVENDA.COD_MOD_VENDA IN (1,115,171,172,2,288,289,292,30,63,76) THEN 'VENDA DIRETA'
					ELSE ''
					END) AS 'NOME_DA_MODALIDADE'


				

		
FROM XVENDAPARCELA (NOLOCK) 

		INNER JOIN FLAN					(NOLOCK) ON (FLAN.IDLAN = XVENDAPARCELA.IDLAN AND FLAN.CODCOLIGADA = XVENDAPARCELA.CODCOLLAN)
		INNER JOIN XVENDA				(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA)
		INNER JOIN XITEMVENDA			(NOLOCK) ON (XITEMVENDA.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR  AND XITEMVENDA.NUM_VENDA = XVENDA.NUM_VENDA)													
		INNER JOIN GCOLIGADA			(NOLOCK) ON (XVENDA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
		INNER JOIN XCOMPRADOR			(NOLOCK) ON (XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA AND XVENDA.CODCOLIGADA = XCOMPRADOR.CODCOLIGADA AND XCOMPRADOR.PRINCIPAL = '1')
		INNER JOIN FCFO					(NOLOCK) ON (XCOMPRADOR.CODCFO = FCFO.CODCFO AND XCOMPRADOR.CODCOLCFO = FCFO.CODCOLIGADA)
		INNER JOIN XSITUACAOVENDA		(NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
		INNER JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR AND XVENDA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA) 
		INNER JOIN XMODALIDADEVENDA		(NOLOCK) ON (XVENDA.COD_MOD_VENDA = XMODALIDADEVENDA.COD_MOD_VENDA)

		
WHERE	
XVENDA.COD_SIT_VENDA IN (@SITUACAO_VENDA)
AND		XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
AND		(
			(XVENDA.DAT_VENDA >= @DATA_VENDA_INI AND XVENDA.DAT_VENDA < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 0 ELSE 1 END) )
			OR 
			(XVENDA.DAT_CANCELA >= @DATA_VENDA_INI AND XVENDA.DAT_CANCELA < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 1 ELSE 0 END) )
		)
AND	XVENDA.CODCOLIGADA IN (@COLIGADA)

GROUP BY 
GCOLIGADA.CODCOLIGADA,
XEMPREENDIMENTO.UF,
GCOLIGADA.NOME,
XEMPREENDIMENTO.NOME,
XEMPREENDIMENTO.COD_PESS_EMPR,
FCFO.NOME,
XVENDA.NUM_VENDA,
XVENDA.CODCOLIGADA,
XITEMVENDA.NUM_UNID,
XITEMVENDA.NUM_SUB_UNID,
XSITUACAOVENDA.DSC_SIT_VENDA,
XVENDA.RECCREATEDON,
XVENDA.DAT_CANCELA,
XVENDA.VALOR_VENDA,
XMODALIDADEVENDA.DSC_MOD_VENDA,
XMODALIDADEVENDA.COD_MOD_VENDA,
XVENDA.DAT_VENDA,
FCFO.CGCCFO,
XVENDAPARCELA.CODTIPOPARC,
FLAN.STATUSLAN,
FLAN.VALORORIGINAL,
FLAN.CODCOLIGADA,
FLAN.IDLAN,
XVENDA.NUM_CONT,
XVENDAPARCELA.CODCOLIGADA,
XVENDAPARCELA.NUMVENDA,
XVENDAPARCELA.IDLAN,
XVENDAPARCELA.CODCOLLAN
		
) AS GRUPO

GROUP BY 
GRUPO.CODCOLIGADA,
GRUPO.NOME_COLIGADA,
GRUPO.ESTADO_EMP,
GRUPO.COD_PESS_EMPR,
GRUPO.NOME, 
GRUPO.COMPRADOR1,
GRUPO.PRIMEIRO_FIADOR,
GRUPO.SEGUNDO_FIADOR,
GRUPO.CGCCFO,
GRUPO.NOME_SEGUNDO_COMPRADOR,
GRUPO.CPF_SEGUNDO_COMPRADOR,
GRUPO.NUM_UNID,
GRUPO.NUM_SUB_UNID,
GRUPO.DSC_SIT_VENDA,
GRUPO.DAT_VENDA,  
GRUPO.RECCREATEDON,  
GRUPO.VALOR_VENDA , 
GRUPO.NUM_VENDA,
GRUPO.DAT_CANCELA,
GRUPO.DSC_MOD_VENDA,
GRUPO.NUM_CONT,
GRUPO.CODCONTRATOCEF,
GRUPO.MODALIDADE_VENDA,
GRUPO.ADITIVO

,GRUPO.QTD_PARC_MENSAL
,GRUPO.VALOR_PARC_MENSAL
,GRUPO.QTD_PARC_MENSAL2
,GRUPO.VALOR_PARC_MENSAL2
,GRUPO.QTD_PARC_MENSAL3
,GRUPO.VALOR_PARC_MENSAL3
,GRUPO.QTD_PARC_SEMESTRAL
,GRUPO.VALOR_PARC_SEMESTRAL
,GRUPO.QTD_PARC_ANUAL
,GRUPO.VALOR_PARC_ANUAL
,GRUPO.QTD_PARC_Escritura_ITBI
,GRUPO.VALOR_PARC_Escritura_ITBI

,GRUPO.QTD_PARC_TX_JUROS_APOS_ENTREGA_ANUAL
,GRUPO.VALOR_TX_JUROS_APOS_ENTREGA_ANUAL
,GRUPO.VALOR_MENSAL_REG
,GRUPO.QTD_PARC_MENSAL_REG
,GRUPO.QTD_PARC_JUROS_MUTUARIOS_REG
,GRUPO.VALOR_JUROS_MUTUARIOS_REG
,GRUPO.QTD_PARC_ADIANT_ESCRITURA_ITBI_REG
,GRUPO.VALOR_ADIANT_ESCRITURA_ITBI_REG

,GRUPO.COMPONENTE_FINAL
,GRUPO.VENCIMENTO_FINAL
,GRUPO.NOME_DA_MODALIDADE

/*
SELECT TOP 1000 * 
FROM XCOMPONENTE

SELECT TOP 1000 * 
FROM XVENDAPARCELA
WHERE 
XVENDA.COD_SIT_VENDA IN (40)
AND		XVENDA.COD_PESS_EMPR IN (17675)
AND

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'XVENDAPARCELA'

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'XCOMPONENTE'

*/