 SELECT
 CLOTE.CODCOLIGADA AS 'COLIGADA - CLOTE', 
 CPARTIDA.INTEGRAAPLICACAO AS 'SISTEMA - ORIGEM', 
 GSISTEMA.DESCRICAO AS 'NOME_SISTEMA',
 CLOTE.CODLOTE AS 'LOTE - CLOTE', 
 CLOTE.DESCRICAO AS 'DESC LOTE - CLOTE',
 CPARTIDA.CODFILIAL AS 'FILIAL - GFILIAL', 
 CLANCAMENTO.IDLANCAMENTO AS 'IDLAN - CLANCAMENTO', 
 CLANCAMENTO.DESCRICAO AS 'DESC - CLANCAMENTO',
 CPARTIDA.DOCUMENTO AS 'DOC - CPARTIDA',
 CONVERT(VARCHAR,CPARTIDA.DATA,103) AS 'DATA - CPARTIDA',
 CPARTIDA.DEBITO AS 'CONTADEBITO',
 CCONTADEB.DESCRICAO AS 'DESC - DEBITO',
 CPARTIDA.CREDITO AS 'CONTACREDITO',
 CCONTACRE.DESCRICAO AS 'DESC - CREDITO',
 CPARTIDA.VALOR AS 'CPARTIDA - VALOR',
 CPARTIDA.COMPLEMENTO AS 'CPARTIDA - COMPLEMENTO',
 CPARTIDA.CODCCUSTO AS 'FLAN - CCCUSTO',
 GCCUSTO.NOME AS 'NOME CCUSTO',
 CONVERT(VARCHAR,CPARTIDA.DATAINCLU,103) AS 'DATA INCLUSAO - CPARTIDA',
 CPARTIDA.USUARIO AS 'USUARIO - CPARTIDA',
 CONVERT(VARCHAR,CPARTIDA.DATAINTEGRACAO,103) AS 'DATA INTEGRA플O - CPARTIDA',
 CPARTIDA.USUARIOINTEGRACAO AS 'USUARIO INTEGRA플O - CPARTIDA',
 CPARTIDA.USUARIOALTER AS 'USUARIO ALTERA플O - CPARTIDA',
 CONVERT(VARCHAR,CPARTIDA.DATAALTER,103) AS 'DATA ALTERA플O - CPARTIDA',
 CONVERT(VARCHAR,CPARTIDA.DATALIBERACAO,103) AS 'DATA LIBERA플O - CPARTIDA',
 CPARTIDA.INTEGRACHAVE AS 'CHAVE INTEGRA플O - CPARTIDA',
 (CASE WHEN ORIGINADONOVOMOD = 1 THEN 'SIM' ELSE 'N홒' END) AS 'Partida originada no novo modelo de BackOffice',
 GFILIAL.NOMEFANTASIA AS 'NOME FILIAL - GFILIAL',
 '??' AS 'HISTORICO PADRAO',
 '??' AS 'DESCRI플O HISTORICO'




 FROM CLOTE							(NOLOCK)
 INNER JOIN CLANCAMENTO				(NOLOCK) ON CLANCAMENTO.CODCOLIGADA = CLOTE.CODCOLIGADA  AND CLANCAMENTO.CODLOTE = CLOTE.CODLOTE
 INNER JOIN CPARTIDA				(NOLOCK) ON CPARTIDA.CODCOLIGADA = CLANCAMENTO.CODCOLIGADA AND CLANCAMENTO.IDLANCAMENTO = CPARTIDA.IDLANCAMENTO
 --INNER JOIN CCONTA AS CCONTADEB		(NOLOCK) ON CPARTIDA.CODCOLDEBITO = CCONTADEB.CODCOLIGADA AND CPARTIDA.DEBITO = CCONTADEB.CODCONTA
 --INNER JOIN CCONTA AS CCONTACRE		(NOLOCK) ON CPARTIDA.CODCOLCREDITO = CCONTACRE.CODCOLIGADA AND CPARTIDA.CREDITO = CCONTACRE.CODCONTA
 INNER JOIN GCCUSTO					(NOLOCK) ON GCCUSTO.CODCOLIGADA = CPARTIDA.CODCOLIGADA AND GCCUSTO.CODCCUSTO = CPARTIDA.CODCCUSTO
 INNER JOIN GFILIAL					(NOLOCK) ON GFILIAL.CODCOLIGADA = CPARTIDA.CODCOLIGADA AND GFILIAL.CODFILIAL = CPARTIDA.CODFILIAL
 INNER JOIN GSISTEMA				(NOLOCK) ON GSISTEMA.CODSISTEMA = CPARTIDA.INTEGRAAPLICACAO

 WHERE CLOTE.CODCOLIGADA IN (1)
 AND CLOTE.CODLOTE IN ('301213')
 --DATA E SISTEMA

 ORDER BY 1, 3
 /*
 SELECT TOP 1000 * 
 FROM CLOTE
 WHERE CLOTE.CODLOTE IN ('301213')
 SELECT TOP 1000  * 
 FROM CLANCAMENTO
 WHERE CLANCAMENTO.CODLOTE IN ('301213')
 SELECT TOP 1000  * 
 FROM   CPARTIDA
 WHERE CPARTIDA.CODLOTE IN ('301213')
 SELECT TOP 1000 * 
 FROM CLANCAMENTO


 SELECT * 
 FROM GCAMPOS 
 WHERE TABELA LIKE '%SISTEMA%'

 select * 
 from GSISTEMA
  */