SELECT 
CODCOLIGADA , 
(CONVERT(VARCHAR(3),CODCOLIGADA) + ' - ' + NOMEFANTASIA) AS 'COLIGADA'
FROM GCOLIGADA
WHERE (CODCOLIGADA = 1 OR CODCOLIGADA > 8) 
AND CODCOLIGADA NOT IN (54, 61)
AND ATIVO <> 'F'

ORDER BY 1 