/*DECLARE @COLIGADA AS INT= 51,
		@FILIAL AS INT= 2,
		@DATA_INI_D AS DATETIME = '20250921',
		@DATA_FIN_D AS DATETIME = '20250928';*/
WITH 
SOLICITACAO AS (
SELECT 
SOLICITACAO.IDMOV,
SOLICITACAO.CODCOLIGADA,
ISNULL(SOLICITACAO.CODCCUSTO, (SELECT TOP 1 T.CODCCUSTO FROM TMOVRATCCU AS T (NOLOCK) WHERE T.IDMOV = SOLICITACAO.IDMOV AND T.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)) AS CODCCUSTO,
SOLICITACAO.NUMEROMOV AS NUMEROMOV_SOLICITACAO,
SOLICITACAO.USUARIOCRIACAO AS USUARIOCRIACAO_SOLICITACAO,
SOLICITACAO.DATAEMISSAO AS DATAEMISSAO_SOLICITACAO,
SOLICITACAO.CODTMV,
CASE	WHEN SOLICITACAO.STATUS = 'A' THEN 'PENDENTE' 
		WHEN SOLICITACAO.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN SOLICITACAO.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN SOLICITACAO.STATUS = 'C' THEN 'CANCELADA' 
		END AS STATUS_SOLICI,
PRD_SOLI.CODIGOPRD,
(SELECT T.DESCRICAO FROM TPRD T WHERE T.CODCOLIGADA = PRD_SOLI.CODCOLIGADA AND T.CODIGOPRD = SUBSTRING(PRD_SOLI.CODIGOPRD, 1,4)) AS DESC_GRUPO_PROD,
PRD_SOLI.NOMEFANTASIA AS NOMEFANTASIA_PRD_SOLI,
ITM_SOLI.QUANTIDADETOTAL AS QTD_TOTAL_ITM_SOLI,
ITM_SOLI.DATAENTREGA AS DATAENTREGA_ITM_SOLI,

/*DATA DA APROVAÇÃO */
DBO.Dt_aprovacao(SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'DATA_DE_PROVACAO',
[DBO].[USUARIOAPROVADOR](SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'USUARIO_APROVADOR' ,
[DBO].[ETAPA_ATUAL_APROV](SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'ETAPA_(APENAS CASO ALÇADA)' ,
TCCOTACAOITMMOV.CODCOTACAO,
ITM_SOLI.NSEQITMMOV,
TMOVCOMPL.URGENCIA AS 'URGENCIA_PEDIDO',
	(SELECT TOP 1TMOTIVOCONCLPED.MOTIVO 
	FROM TMOTIVOCONCLPED (NOLOCK)
	WHERE TMOTIVOCONCLPED.CODCOLIGADA = SOLICITACAO.CODCOLIGADA
	AND TMOTIVOCONCLPED.IDMOV = SOLICITACAO.IDMOV 
	ORDER BY TMOTIVOCONCLPED.RECCREATEDON DESC )AS 'MOTIVO'

FROM TMOV AS SOLICITACAO            (NOLOCK)

LEFT JOIN TITMMOV AS ITM_SOLI		(NOLOCK) ON (ITM_SOLI.IDMOV = SOLICITACAO.IDMOV AND ITM_SOLI.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)
LEFT JOIN TPRD AS PRD_SOLI		    (NOLOCK) ON (PRD_SOLI.IDPRD = ITM_SOLI.IDPRD AND PRD_SOLI.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)
LEFT JOIN TCCOTACAOITMMOV		    (NOLOCK) ON (TCCOTACAOITMMOV.IDMOV = ITM_SOLI.IDMOV AND TCCOTACAOITMMOV.NSEQITMMOV = ITM_SOLI.NSEQITMMOV AND TCCOTACAOITMMOV.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)
INNER JOIN TMOVCOMPL                (NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = SOLICITACAO.CODCOLIGADA AND TMOVCOMPL.IDMOV = SOLICITACAO.IDMOV)
/*ALTERADO JOIN COM A TCCOTACAO DE INNER PARA LEFT PARA TRAZER COTAÇÃO PENDENTE*/
LEFT JOIN TCCOTACAO                 (NOLOCK) ON (TCCOTACAOITMMOV.CODCOLIGADA = TCCOTACAO.CODCOLIGADA AND TCCOTACAOITMMOV.CODCOTACAO = TCCOTACAO.CODCOTACAO AND TCCOTACAO.STSCOTACAO <> 7)
WHERE	SOLICITACAO.CODTMV  IN ('1.1.18', '1.1.20',/*'1.1.21'*/'1.1.25'/*'1.1.26'*/)
AND		SOLICITACAO.STATUS <> 'C'
AND		SOLICITACAO.DATACRIACAO BETWEEN @DATA_INI_D AND @DATA_FIN_D
AND		SOLICITACAO.CODCCUSTO IN (@CODCCUSTO)
AND		SOLICITACAO.CODCOLIGADA = @COLIGADA
AND		SOLICITACAO.CODFILIAL = @FILIAL
), 

ODC AS (
SELECT 
ORDEM_DE_COMPRA.IDMOV,
ORDEM_DE_COMPRA.CODCOLIGADA,
ORDEM_DE_COMPRA.CODTMV,
ITM_ODC.NSEQITMMOV,
ORDEM_DE_COMPRA.NUMEROMOV,
ORDEM_DE_COMPRA.USUARIOCRIACAO,
ORDEM_DE_COMPRA.DATAEMISSAO,
APROV_ODC.DATAAPROVACAO,
APROV_ODC.CODUSUARIO,
CASE	WHEN ORDEM_DE_COMPRA.STATUS = 'A' THEN 'PENDENTE' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'C' THEN 'CANCELADA' 
		END AS STATUS,

ITM_ODC.QUANTIDADETOTAL,
ITM_ODC.QUANTIDADETOTAL - ITM_ODC.QUANTIDADEARECEBER AS QUANTIDADE_RECEBIDA,
ITM_ODC.QUANTIDADEARECEBER,		
ORDEM_DE_COMPRA.DATAENTREGA DATA_ENTREGA_ODC,		
FCFO.NOMEFANTASIA,
FCFO.CONTATO,
FCFO.TELEFONE,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FCFO.EMAIL),CHAR(13) + CHAR(10),' '),';',' ') AS EMAIL,
MTAREFA.NOME,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVCOMPL.REPROGRAMACAO FROM TMOVCOMPL WHERE TMOVCOMPL.IDMOV = ORDEM_DE_COMPRA.IDMOV AND TMOVCOMPL.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)),CHAR(13) + CHAR(10),' '),';',' ')AS REPROGRAMACAO,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVHISTORICO.HISTORICOLONGO FROM TMOVHISTORICO WHERE TMOVHISTORICO.IDMOV = ORDEM_DE_COMPRA.IDMOV AND TMOVHISTORICO.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)),CHAR(13) + CHAR(10),' '),';',' ')AS HISTORICO_ODC

FROM TMOV AS ORDEM_DE_COMPRA
--LEFT JOIN TITMMOV AS ITM_ODC		(NOLOCK) ON (TITMMOVRELAC.IDMOVDESTINO = ITM_ODC.IDMOV AND TITMMOVRELAC.NSEQITMMOVDESTINO = ITM_ODC.NSEQITMMOV AND TITMMOVRELAC.CODCOLDESTINO = ITM_ODC.CODCOLIGADA)
LEFT JOIN TITMMOV AS ITM_ODC		(NOLOCK) ON (ITM_ODC.IDMOV = ORDEM_DE_COMPRA.IDMOV AND ITM_ODC.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)
LEFT JOIN TMOVAPROVA AS APROV_ODC	(NOLOCK) ON (APROV_ODC.IDMOV = ORDEM_DE_COMPRA.IDMOV AND APROV_ODC.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND APROV_ODC.TIPOAPROVACAO = 1)
LEFT JOIN FCFO				        (NOLOCK) ON (FCFO.CODCFO = ORDEM_DE_COMPRA.CODCFO)
LEFT JOIN MTAREFA					(NOLOCK) ON (ITM_ODC.IDPRJ = MTAREFA.IDPRJ AND ITM_ODC.IDTRF = MTAREFA.IDTRF AND ITM_ODC.CODCOLIGADA = MTAREFA.CODCOLIGADA)
LEFT JOIN TMOTIVOCONCLPED           (NOLOCK) ON (TMOTIVOCONCLPED.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND TMOTIVOCONCLPED.IDMOV = ORDEM_DE_COMPRA.IDMOV)
INNER JOIN TMOVCOMPL                (NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND TMOVCOMPL.IDMOV = ORDEM_DE_COMPRA.IDMOV)

WHERE	ORDEM_DE_COMPRA.CODTMV  IN ('1.1.21','1.1.26')
AND		ORDEM_DE_COMPRA.STATUS <> 'C'
AND		ORDEM_DE_COMPRA.DATACRIACAO BETWEEN @DATA_INI_D AND @DATA_FIN_D
AND		ORDEM_DE_COMPRA.CODCCUSTO IN (@CODCCUSTO)
AND		ORDEM_DE_COMPRA.CODCOLIGADA = @COLIGADA
AND		ORDEM_DE_COMPRA.CODFILIAL = @FILIAL
)


SELECT 
SOLICITACAO.CODCOLIGADA AS 'COLIGADA',
SOLICITACAO.CODCCUSTO AS 'CODCCUSTO',
SOLICITACAO.NUMEROMOV_SOLICITACAO AS 'NUMEROMOV_SOLI',
SOLICITACAO.USUARIOCRIACAO_SOLICITACAO AS 'USUARIO_CRIACAO_SOLI',
CONVERT(DATE,SOLICITACAO.DATAEMISSAO_SOLICITACAO) AS 'DATAEMISSAO_SOLI',
SOLICITACAO.CODTMV AS 'CODTMV_SOLI',
SOLICITACAO.STATUS_SOLICI AS 'STATUS_SOLI',
SOLICITACAO.CODIGOPRD AS 'CODPRD_SOLI',
SOLICITACAO.DESC_GRUPO_PROD AS 'DESC_GRUPO_PROD_SOLI',
SOLICITACAO.NOMEFANTASIA_PRD_SOLI AS 'NOME_FANTASIA_PRD_SOLI',
SOLICITACAO.QTD_TOTAL_ITM_SOLI AS 'QTD_TOTAL_ITM_SOLI',
CONVERT(DATE,SOLICITACAO.DATAENTREGA_ITM_SOLI) AS 'DATAENTREGA_SOLI',
DBO.Dt_aprovacao(SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'DT_APROV_SOLI',
DBO.USUARIOAPROVADOR(SOLICITACAO.CODCOLIGADA,SOLICITACAO.IDMOV) AS 'USUARIO_APROVADOR_SOLI',
DBO.Etapa_atual_aprov(SOLICITACAO.CODCOLIGADA,SOLICITACAO.IDMOV) AS 'ETAPA_SOLI',
SOLICITACAO.CODCOTACAO AS 'CODCOTACAO_SOLI',
ODC.CODTMV AS 'CODTMV_ODC',
ODC.NUMEROMOV AS 'NUMEROMOV_ODC',
ODC.USUARIOCRIACAO AS 'USUARIO_CRICAO_ODC',
CONVERT(DATE,ODC.DATAEMISSAO) AS 'DATAEMISSAO_ODC',
DBO.Dt_aprovacao(ODC.CODCOLIGADA, ODC.IDMOV) AS 'DT_APROV_ODC',
DBO.USUARIOAPROVADOR(ODC.CODCOLIGADA,ODC.IDMOV) AS 'USUARIO_APROVADOR_ODC',
DBO.Etapa_atual_aprov(ODC.CODCOLIGADA,ODC.IDMOV) AS 'ETAPA_ODC',
ODC.STATUS AS 'STATUS_ODC',
ODC.QUANTIDADETOTAL AS 'QUANTIDADETOTAL_ODC',
ODC.QUANTIDADE_RECEBIDA  AS 'QUANTIDADE_RECEBIDA_ODC',
ODC.QUANTIDADEARECEBER AS 'QUANTIDADEARECEBER_ODC',
CONVERT(DATE,ODC.DATA_ENTREGA_ODC) AS 'DATA_ENTREGA_ODC',
ODC.NOMEFANTASIA AS 'NOME_FANTASIA_ODC',
ODC.CONTATO AS 'CONTATO',
ODC.TELEFONE AS 'TELEFONE',
ODC.EMAIL AS 'EMAIL',
ODC.NOME AS 'NOME',
ODC.REPROGRAMACAO AS 'REPROGRAMACAO',
ODC.HISTORICO_ODC AS 'HISTORICO_ODC',
SOLICITACAO.MOTIVO AS 'MOTIVO',
SOLICITACAO.URGENCIA_PEDIDO AS 'URGENCIA_PEDIDO'

FROM SOLICITACAO 
INNER JOIN TITMMOVRELAC				(NOLOCK) ON (TITMMOVRELAC.IDMOVORIGEM = SOLICITACAO.IDMOV	AND  TITMMOVRELAC.NSEQITMMOVORIGEM = SOLICITACAO.NSEQITMMOV AND TITMMOVRELAC.CODCOLORIGEM = SOLICITACAO.CODCOLIGADA)
INNER JOIN ODC								 ON (TITMMOVRELAC.IDMOVDESTINO = ODC.IDMOV			AND TITMMOVRELAC.NSEQITMMOVDESTINO = ODC.NSEQITMMOV			AND TITMMOVRELAC.CODCOLDESTINO = ODC.CODCOLIGADA)



