USE [CORPORE_RESIDENCIAL]
GO

/****** Object:  UserDefinedFunction [dbo].[TABELA_PRECO_MEDIO]    Script Date: 09/10/2025 15:41:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER FUNCTION [dbo].[TABELA_PRECO_MEDIO](@CODCOLIGADA INT, @DATA_INI DATE, @DATA_FIN DATE, @CODLOC_INI VARCHAR(10), @CODLOC_FIN VARCHAR(10))
RETURNS @RESULTABLE TABLE (PRECO_MEDIO NUMERIC (12,4), IDPRD INT, CODCOLIGADA INT)




BEGIN
	INSERT INTO @RESULTABLE SELECT 
											CAST ((CASE WHEN SUM(ISNULL(T.VAL,0)) = '0' THEN '0.01' ELSE SUM(ISNULL(T.VAL,0)) END)
						
													/
						
											(CASE WHEN SUM(T.QUANTIDADE) = '0' THEN '0.01' ELSE SUM(T.QUANTIDADE)END) AS NUMERIC(12,4))

											AS CUSTOMEDIODEENTRADA,
											T.IDPRD,
											T.CODCOLIGADA
			 
									FROM (              
       
							SELECT  TPRD.CODIGOPRD , TMOV.IDMOV,
									TPRD.IDPRD,
									TPRD.NOMEFANTASIA ,
									TPRD.CODUNDCOMPRA ,
									TITMMOV.CODCOLIGADA,
									(CASE WHEN TITMMOV.CODUND = TPRD.CODUNDCONTROLE 
											THEN (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) 
											ELSE ((CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) * (SELECT FATORCONVERSAO FROM TUND (NOLOCK) WHERE TUND.CODUND = TITMMOV.CODUND 
											GROUP BY FATORCONVERSAO)) 
											/ (SELECT FATORCONVERSAO FROM TUND (NOLOCK) WHERE TUND.CODUND = TPRD.CODUNDCONTROLE)
									END) AS QUANTIDADE
	 
	 
									,TITMMOV.PRECOUNITARIO,     

							((TITMMOV.PRECOUNITARIO + 
							(ISNULL(TITMMOV.VALORFRETECTRC,0)/ 
							CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) - 
							(ISNULL(TITMMOV.VALORDESC,0)/
							CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) + 
							(isnull((select sum(VALOR) from TTRBMOV (NOLOCK) where CODCOLIGADA = TITMMOV.CODCOLIGADA 
							and IDMOV = TITMMOV.IDMOV and NSEQITMMOV = TITMMOV.NSEQITMMOV and CODTRB = 'IPI'),0)/
							CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)) +   
							CASE WHEN ISNULL((CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END),0) < 1 THEN
								((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * 
							((TITMMOV.PRECOUNITARIO * (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) ) / 
							CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END )) ELSE
								((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO * 
							(CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) ) / 
							CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END ))/ 
							CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END END)
									* (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) AS VAL
							FROM    TMOV (nolock) ,
									TITMMOV (nolock),
									DBO.TPRD(nolock)
							WHERE   
									TMOV.CODCOLIGADA= @CODCOLIGADA
									AND (TITMMOV.QUANTIDADETOTAL<>0 OR TITMMOV.QUANTIDADE<>0)
									AND ( TMOV.VALORBRUTO <> 0 OR TMOV.VALORBRUTOORIG <> 0)
									AND TMOV.IDMOV = TITMMOV.IDMOV
									AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA
									AND TPRD.IDPRD = TITMMOV.IDPRD
									AND TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA
									AND TMOV.CODTMV IN ('2.2.05','4.1.01','1.1.40','1.1.41','4.1.04','3.1.28','4.1.07','4.1.03')  
									AND TMOV.STATUS<>'C'
		

									AND (CASE WHEN TMOV.CODTMV = '3.1.28' THEN TMOV.CODLOCDESTINO  
								ELSE TMOV.CODLOC END) BETWEEN  @CODLOC_INI AND @CODLOC_FIN

												AND 
											(CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) >= @DATA_INI AND
											(CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) <= @DATA_FIN
							)
									AS T
							GROUP BY 
									T.CODIGOPRD ,
									T.NOMEFANTASIA ,
									T.CODUNDCOMPRA,
									T.CODCOLIGADA,
									T.IDPRD

	RETURN
END

GO


