with RECEBIDO AS (
SELECT 
TMOV.CODCOLIGADA,
TMOV.CODFILIAL,
TMOV.IDMOV, 
TMOV.NUMEROMOV,
TMOV.CODLOC,
TMOV.IDPRJ,
(TMOV.CODTMV + ' - ' + TTMV.NOME) AS 'MOVIMENTO',
(CASE 
	WHEN TMOV.STATUS = 'A' THEN 'PENDENTE'
	WHEN TMOV.STATUS = 'F' THEN 'FATURADO'
	WHEN TMOV.STATUS = 'C' THEN 'CANCELADO'
	WHEN TMOV.STATUS = 'G' THEN 'PARCIALMENTE RECEBIDO'
	WHEN TMOV.STATUS = 'N' THEN 'NORMAL'
	END) AS 'STATUS'


FROM TMOV (NOLOCK)
LEFT JOIN TITMMOV		(NOLOCK) ON (TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV)
LEFT JOIN TPRD			(NOLOCK) ON (TITMMOV.CODCOLIGADA = TPRD.CODCOLIGADA AND TITMMOV.IDPRD = TPRD.IDPRD)
LEFT JOIN TTMV			(NOLOCK) ON (TTMV.CODCOLIGADA = TMOV.CODCOLIGADA AND TTMV.CODTMV = TMOV.CODTMV)
LEFT JOIN TMOVCOMPL		(NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVCOMPL.IDMOV = TMOV.IDMOV)
WHERE TMOV.CODTMV IN ('4.1.05')

)

SELECT 
(TMOV.CODTMV + ' - ' + TTMV.NOME) AS 'MOVIMENTO',
TMOV.CODCOLIGADA, 
TMOV.CODFILIAL, 
TMOV.IDMOV, 
TMOV.NUMEROMOV,
(TMOV.CODLOC + ' - ' + LOC1.NOME) AS 'CODLOC',
(PRJ1.CODPRJ + ' - ' + PRJ1.DESCRICAO) AS 'IDPRJ',
(CASE 
	WHEN TMOV.STATUS = 'A' THEN 'PENDENTE'
	WHEN TMOV.STATUS = 'F' THEN 'FATURADO'
	WHEN TMOV.STATUS = 'C' THEN 'CANCELADO'
	WHEN TMOV.STATUS = 'G' THEN 'PARCIALMENTE RECEBIDO'
	WHEN TMOV.STATUS = 'N' THEN 'NORMAL'
	END) AS 'STATUS',
RECEBIDO.MOVIMENTO AS 'MOVIMENTO_ORIGEM',
RECEBIDO.CODCOLIGADA AS 'COLIGADA_ORIGEM',
RECEBIDO.CODFILIAL AS 'FILIAL_ORIGEM',
RECEBIDO.IDMOV AS 'IDMOV_ORIGEM',
RECEBIDO.NUMEROMOV AS 'NUMEROMOV_ORIGEM',
(RECEBIDO.CODLOC + ' - ' + LOC2.NOME) AS 'CODLOC_ORIGEM',
(PRJ2.CODPRJ + ' - ' + PRJ2.DESCRICAO) AS 'PRJ ORIGEM',
RECEBIDO.STATUS AS 'STATUS_ORIGEM',
TMOV.RECCREATEDBY AS 'USUARIO CRIACAO',
TMOV.RECCREATEDON AS 'DATA CRIACAO',

TPRD.NOMEFANTASIA,
CONVERT(DECIMAL(10,4),TITMMOV.QUANTIDADE) AS 'QTD',
CONVERT(MONEY,TITMMOV.PRECOUNITARIO) AS 'PRECO UNITARIO',
CONVERT(MONEY,TMOV.VALORBRUTO) AS 'VALOR'

FROM TMOV (NOLOCK)
INNER JOIN TITMMOV		(NOLOCK) ON (TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV)
INNER JOIN TPRD			(NOLOCK) ON (TITMMOV.CODCOLIGADA = TPRD.CODCOLIGADA AND TITMMOV.IDPRD = TPRD.IDPRD)
INNER JOIN TTMV			(NOLOCK) ON (TTMV.CODCOLIGADA = TMOV.CODCOLIGADA AND TTMV.CODTMV = TMOV.CODTMV)
INNER JOIN TMOVCOMPL	(NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVCOMPL.IDMOV = TMOV.IDMOV)


/* MOVIMENTO DE RECEBIMENTO */ 
LEFT JOIN RECEBIDO				 ON (RECEBIDO.CODCOLIGADA = ISNULL(TMOVCOMPL.TRANSF_COLIGADA,TMOVCOMPL.TRANSF_COLIGADA_ORIG) AND RECEBIDO.IDMOV = TMOVCOMPL.IDMOV_ORIGEM)

/* LOCAIS DE ESTOQUE */
INNER JOIN TLOC AS LOC1 (NOLOCK) ON (LOC1.CODCOLIGADA = TMOV.CODCOLIGADA AND LOC1.CODLOC = TMOV.CODLOC)
INNER JOIN TLOC AS LOC2 (NOLOCK) ON (LOC2.CODCOLIGADA = RECEBIDO.CODCOLIGADA AND LOC2.CODLOC = RECEBIDO.CODLOC)

/* PROJETO */ 
INNER JOIN MPRJ AS PRJ1 (NOLOCK) ON (PRJ1.CODCOLIGADA = TMOV.CODCOLIGADA AND PRJ1.IDPRJ = TMOV.IDPRJ)
INNER JOIN MPRJ AS PRJ2 (NOLOCK) ON (PRJ2.CODCOLIGADA = RECEBIDO.CODCOLIGADA AND PRJ2.IDPRJ = RECEBIDO.IDPRJ)

WHERE TMOV.CODTMV IN ('4.1.04')
AND TMOV.RECCREATEDON > '20220101'
AND TMOVCOMPL.IDMOV_ORIGEM IS NOT NULL



GROUP BY 
TMOV.CODCOLIGADA, 
RECEBIDO.CODCOLIGADA,
TMOV.CODFILIAL, 
RECEBIDO.CODFILIAL,
TMOV.IDMOV, 
RECEBIDO.IDMOV,
TMOV.NUMEROMOV,
RECEBIDO.NUMEROMOV,
TMOV.CODLOC ,
RECEBIDO.CODLOC,
TMOV.CODTMV,
TTMV.NOME,
RECEBIDO.MOVIMENTO,
RECEBIDO.IDPRJ,
TMOV.IDPRJ,
TMOV.RECCREATEDBY,
TMOV.RECCREATEDON,
TMOV.STATUS,
TPRD.NOMEFANTASIA,
TITMMOV.QUANTIDADE,
TITMMOV.PRECOUNITARIO,
TMOV.VALORBRUTO,
LOC1.NOME,
LOC2.NOME,
RECEBIDO.STATUS,
PRJ1.CODPRJ,
PRJ1.DESCRICAO,
PRJ2.CODPRJ,
PRJ2.DESCRICAO

ORDER BY TMOV.CODCOLIGADA, TMOV.CODFILIAL, TMOV.IDMOV
