DECLARE @COLIGADA AS INT= 51,
		@FILIAL AS INT= 2,
		@DATA_INI_D AS DATETIME = '20251101',
		@DATA_FIN_D AS DATETIME = '20251104';
WITH 

/*INICIO SOLICITAÇÃO DE COMPRA */ 

SOLICITACAO AS (
SELECT 
SOLICITACAO.IDMOV,
SOLICITACAO.CODCOLIGADA,
ISNULL(SOLICITACAO.CODCCUSTO, (SELECT TOP 1 T.CODCCUSTO FROM TMOVRATCCU AS T (NOLOCK) WHERE T.IDMOV = SOLICITACAO.IDMOV AND T.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)) AS CODCCUSTO,
SOLICITACAO.NUMEROMOV AS NUMEROMOV_SOLICITACAO,
SOLICITACAO.USUARIOCRIACAO AS USUARIOCRIACAO_SOLICITACAO,
SOLICITACAO.DATAEMISSAO AS DATAEMISSAO_SOLICITACAO,
SOLICITACAO.CODTMV,
CASE	WHEN SOLICITACAO.STATUS = 'A' THEN 'PENDENTE' 
		WHEN SOLICITACAO.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN SOLICITACAO.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN SOLICITACAO.STATUS = 'C' THEN 'CANCELADA' 
		END AS STATUS_SOLICI,
PRD_SOLI.CODIGOPRD,
(SELECT T.DESCRICAO FROM TPRD T WHERE T.CODCOLIGADA = PRD_SOLI.CODCOLIGADA AND T.CODIGOPRD = SUBSTRING(PRD_SOLI.CODIGOPRD, 1,4)) AS DESC_GRUPO_PROD,
PRD_SOLI.NOMEFANTASIA AS NOMEFANTASIA_PRD_SOLI,
ITM_SOLI.QUANTIDADETOTAL AS QTD_TOTAL_ITM_SOLI,
ITM_SOLI.DATAENTREGA AS DATAENTREGA_ITM_SOLI,

REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVHISTORICO.HISTORICOLONGO FROM TMOVHISTORICO WHERE TMOVHISTORICO.IDMOV = SOLICITACAO.IDMOV AND TMOVHISTORICO.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)),CHAR(13) + CHAR(10),' '),';',' ')AS HISTORICO_SOLI,
DBO.Dt_aprovacao(SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'DATA_DE_PROVACAO',
[DBO].[USUARIOAPROVADOR](SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'USUARIO_APROVADOR' ,
[DBO].[ETAPA_ATUAL_APROV](SOLICITACAO.CODCOLIGADA, SOLICITACAO.IDMOV) AS 'ETAPA_(APENAS CASO ALÇADA)' ,
TCCOTACAOITMMOV.CODCOTACAO,
ITM_SOLI.NSEQITMMOV,
TMOVCOMPL.URGENCIA AS 'URGENCIA_PEDIDO',
	(SELECT TOP 1TMOTIVOCONCLPED.MOTIVO 
	FROM TMOTIVOCONCLPED (NOLOCK)
	WHERE TMOTIVOCONCLPED.CODCOLIGADA = SOLICITACAO.CODCOLIGADA
	AND TMOTIVOCONCLPED.IDMOV = SOLICITACAO.IDMOV 
	ORDER BY TMOTIVOCONCLPED.RECCREATEDON DESC )AS 'MOTIVO'

FROM TMOV AS SOLICITACAO            (NOLOCK)

LEFT JOIN TITMMOV AS ITM_SOLI		(NOLOCK) ON (ITM_SOLI.IDMOV = SOLICITACAO.IDMOV AND ITM_SOLI.CODCOLIGADA = SOLICITACAO.CODCOLIGADA)
LEFT JOIN TPRD AS PRD_SOLI		    (NOLOCK) ON (PRD_SOLI.IDPRD = ITM_SOLI.IDPRD AND PRD_SOLI.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)
LEFT JOIN TCCOTACAOITMMOV		    (NOLOCK) ON (TCCOTACAOITMMOV.IDMOV = ITM_SOLI.IDMOV AND TCCOTACAOITMMOV.NSEQITMMOV = ITM_SOLI.NSEQITMMOV AND TCCOTACAOITMMOV.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)
INNER JOIN TMOVCOMPL                (NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = SOLICITACAO.CODCOLIGADA AND TMOVCOMPL.IDMOV = SOLICITACAO.IDMOV)
/*ALTERADO JOIN COM A TCCOTACAO DE INNER PARA LEFT PARA TRAZER COTAÇÃO PENDENTE*/
LEFT JOIN TCCOTACAO                 (NOLOCK) ON (TCCOTACAOITMMOV.CODCOLIGADA = TCCOTACAO.CODCOLIGADA AND TCCOTACAOITMMOV.CODCOTACAO = TCCOTACAO.CODCOTACAO AND TCCOTACAO.STSCOTACAO <> 7)
WHERE	SOLICITACAO.CODTMV  IN ('1.1.18', '1.1.20',/*'1.1.21'*/'1.1.25'/*'1.1.26'*/)
AND		SOLICITACAO.STATUS <> 'C'
AND		SOLICITACAO.DATAEMISSAO BETWEEN @DATA_INI_D AND @DATA_FIN_D
--AND		SOLICITACAO.CODCCUSTO IN (@CODCCUSTO)
AND		SOLICITACAO.CODCOLIGADA = @COLIGADA
AND		SOLICITACAO.CODFILIAL = @FILIAL
), 

/*FIM DA SOLICITAÇÃO DE COMPRA */
/*INICIO ORDEM DE COMPRA */ 

ODC AS (
SELECT 
ORDEM_DE_COMPRA.IDMOV,
ORDEM_DE_COMPRA.CODCOLIGADA,
ORDEM_DE_COMPRA.CODTMV,
ORDEM_DE_COMPRA.CODCCUSTO,
ITM_ODC.NSEQITMMOV,
ORDEM_DE_COMPRA.NUMEROMOV,
ORDEM_DE_COMPRA.USUARIOCRIACAO,
ORDEM_DE_COMPRA.DATAEMISSAO,
APROV_ODC.DATAAPROVACAO,
APROV_ODC.CODUSUARIO,
CASE	WHEN ORDEM_DE_COMPRA.STATUS = 'A' THEN 'PENDENTE' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'F' THEN 'RECEBIDO' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'G' THEN 'PARC. RECEBIDO' 
		WHEN ORDEM_DE_COMPRA.STATUS = 'C' THEN 'CANCELADA' 
		END AS STATUS,

ITM_ODC.QUANTIDADETOTAL,
ITM_ODC.QUANTIDADETOTAL - ITM_ODC.QUANTIDADEARECEBER AS QUANTIDADE_RECEBIDA,
ITM_ODC.QUANTIDADEARECEBER,		
ORDEM_DE_COMPRA.DATAENTREGA DATA_ENTREGA_ODC,		
FCFO.NOMEFANTASIA,
FCFO.CONTATO,
FCFO.TELEFONE,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FCFO.EMAIL),CHAR(13) + CHAR(10),' '),';',' ') AS EMAIL,
MTAREFA.NOME,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVCOMPL.REPROGRAMACAO FROM TMOVCOMPL WHERE TMOVCOMPL.IDMOV = ORDEM_DE_COMPRA.IDMOV AND TMOVCOMPL.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)),CHAR(13) + CHAR(10),' '),';',' ')AS REPROGRAMACAO,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX),(SELECT TOP 1 TMOVHISTORICO.HISTORICOLONGO FROM TMOVHISTORICO WHERE TMOVHISTORICO.IDMOV = ORDEM_DE_COMPRA.IDMOV AND TMOVHISTORICO.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)),CHAR(13) + CHAR(10),' '),';',' ')AS HISTORICO_ODC

FROM TMOV AS ORDEM_DE_COMPRA
LEFT JOIN TITMMOV AS ITM_ODC		(NOLOCK) ON (ITM_ODC.IDMOV = ORDEM_DE_COMPRA.IDMOV AND ITM_ODC.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA)
LEFT JOIN TMOVAPROVA AS APROV_ODC	(NOLOCK) ON (APROV_ODC.IDMOV = ORDEM_DE_COMPRA.IDMOV AND APROV_ODC.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND APROV_ODC.TIPOAPROVACAO = 1)
LEFT JOIN FCFO				        (NOLOCK) ON (FCFO.CODCFO = ORDEM_DE_COMPRA.CODCFO)
LEFT JOIN MTAREFA					(NOLOCK) ON (ITM_ODC.IDPRJ = MTAREFA.IDPRJ AND ITM_ODC.IDTRF = MTAREFA.IDTRF AND ITM_ODC.CODCOLIGADA = MTAREFA.CODCOLIGADA)
LEFT JOIN TMOTIVOCONCLPED           (NOLOCK) ON (TMOTIVOCONCLPED.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND TMOTIVOCONCLPED.IDMOV = ORDEM_DE_COMPRA.IDMOV)
INNER JOIN TMOVCOMPL                (NOLOCK) ON (TMOVCOMPL.CODCOLIGADA = ORDEM_DE_COMPRA.CODCOLIGADA AND TMOVCOMPL.IDMOV = ORDEM_DE_COMPRA.IDMOV)

WHERE	ORDEM_DE_COMPRA.CODTMV  IN ('1.1.21','1.1.26')
AND		ORDEM_DE_COMPRA.STATUS <> 'C'
--AND		ORDEM_DE_COMPRA.CODCCUSTO IN (@CODCCUSTO)
AND		ORDEM_DE_COMPRA.CODCOLIGADA = @COLIGADA
AND		ORDEM_DE_COMPRA.CODFILIAL = @FILIAL
),

/* FIM ORDEM DE COMPRA*/
/*INICIO ETAPA */

ETAPA AS (
    SELECT 
        TM1.IDMOV,
        TM1.CODCOLIGADA,
        ETAPA_RESULT.DATA,
        ETAPA_RESULT.ETAPA,
        ETAPA_RESULT.USUARIO,
		ETAPA_RESULT.NOME
    FROM TMOV TM1 (NOLOCK)

    OUTER APPLY (
        SELECT TOP 1
            ISNULL(HH.RECCREATEDON, AP.RECMODIFIEDON) AS DATA,
            DBO.TRAZ_ETAPA_ALCADA(HH.CODTAREFAATUAL) AS ETAPA,
            ISNULL(AP.CODUSUARIO, PP.CODUSUARIO) AS USUARIO,
			PP.NOME
        FROM TMOV TM2 (NOLOCK)
            LEFT JOIN TMOVATEND TA       (NOLOCK) ON TM2.IDMOV = TA.IDMOV AND TM2.CODCOLIGADA = TA.CODCOLIGADA
            LEFT JOIN HATENDIMENTOBASE HB(NOLOCK) ON TA.CODATENDIMENTO = HB.CODATENDIMENTO AND TA.CODCOLIGADAATEND = HB.CODCOLIGADA
            LEFT JOIN HHISTORICOEXT HH   (NOLOCK) ON HH.CODATENDIMENTO = HB.CODATENDIMENTO AND TA.CODCOLIGADAATEND = HH.CODCOLIGADA
            LEFT JOIN HATENDENTE HE      (NOLOCK) ON HE.CODATENDENTE = HH.CODATENDPARA AND HE.CODCOLIGADA = HH.CODCOLIGADAPARA
            LEFT JOIN PPESSOA PP         (NOLOCK) ON PP.CODIGO = HE.CODPESSOA
            LEFT JOIN TMOVAPROVA AP      (NOLOCK) ON TM2.IDMOV = AP.IDMOV AND TM2.CODCOLIGADA = AP.CODCOLIGADA
        WHERE TM2.IDMOV = TM1.IDMOV
          AND TM2.CODCOLIGADA = TM1.CODCOLIGADA
        ORDER BY ISNULL(HH.RECCREATEDON, AP.RECMODIFIEDON) DESC
    ) AS ETAPA_RESULT

    WHERE TM1.CODCOLIGADA = @COLIGADA
)



/* FIM DA ETAPA */
/* INICIO CONSULTA AGRUPADORA */

SELECT 
/*CHAMADA SOLICITAÇÃO */ 
SOLICITACAO.IDMOV AS 'SOLI_IDMOV',
SOLICITACAO.CODCOLIGADA AS 'COLIGADA',
SOLICITACAO.CODCCUSTO AS 'CODCCUSTO',
SOLICITACAO.NUMEROMOV_SOLICITACAO AS 'NUMEROMOV_SOLI',
SOLICITACAO.USUARIOCRIACAO_SOLICITACAO AS 'USUARIO_CRIACAO_SOLI',
CONVERT(DATE,SOLICITACAO.DATAEMISSAO_SOLICITACAO) AS 'DATAEMISSAO_SOLI',
SOLICITACAO.CODTMV AS 'CODTMV_SOLI',
SOLICITACAO.STATUS_SOLICI AS 'STATUS_SOLI',
SOLICITACAO.CODIGOPRD AS 'CODPRD_SOLI',
SOLICITACAO.DESC_GRUPO_PROD AS 'DESC_GRUPO_PROD_SOLI',
SOLICITACAO.NOMEFANTASIA_PRD_SOLI AS 'NOME_FANTASIA_PRD_SOLI',
SOLICITACAO.QTD_TOTAL_ITM_SOLI AS 'QTD_TOTAL_ITM_SOLI',
CONVERT(DATE,SOLICITACAO.DATAENTREGA_ITM_SOLI) AS 'DATAENTREGA_SOLI',
(CASE 
	WHEN	ETAPA_SOLI.ETAPA IN ( 'Criação' )	THEN '' 
	WHEN	ETAPA_SOLI.ETAPA NOT IN ( 'Aprovado por alçada', 'Aprovação convencional' )THEN '' 
	ELSE	ETAPA_SOLI.DATA END)  AS 'DT_APROV_SOLI',
(CASE 
	WHEN ETAPA_SOLI.ETAPA IN ( 'Criação' ) THEN ''
	WHEN ETAPA_SOLI.ETAPA NOT IN ( 'Aprovado por alçada', 'Aprovação convencional' ) THEN ( 'Pendente aprovação: ' +  ETAPA_SOLI.USUARIO)
	ELSE ETAPA_SOLI.NOME END)  AS 'USUARIO_APROVADOR_SOLI',
ETAPA_SOLI.ETAPA AS 'ETAPA_SOLI',
SOLICITACAO.HISTORICO_SOLI,
SOLICITACAO.CODCOTACAO AS 'CODCOTACAO_SOLI',

/* FIM SOLICITAÇÃO */ 
/* INICIO CHAMADA ODC */ 
ODC.IDMOV as 'ODC_IDMOV',
ODC.CODTMV AS 'CODTMV_ODC',
ODC.NUMEROMOV AS 'NUMEROMOV_ODC',
ODC.USUARIOCRIACAO AS 'USUARIO_CRICAO_ODC',
CONVERT(DATE,ODC.DATAEMISSAO) AS 'DATAEMISSAO_ODC',
(CASE 
	WHEN	ETAPA_ODC.ETAPA IN ( 'Criação' ) THEN ''
	WHEN	ETAPA_ODC.ETAPA NOT IN ( 'Aprovado por alçada', 'Aprovação convencional' )THEN '' ELSE ETAPA_ODC.DATA END) AS 'DT_APROV_ODC',
(CASE 
	WHEN ETAPA_ODC.ETAPA IN ( 'Criação' ) THEN ''
	WHEN ETAPA_ODC.ETAPA NOT IN ( 'Aprovado por alçada', 'Aprovação convencional' ) THEN ('Pendente aprovação : '+ ETAPA_ODC.USUARIO)
	ELSE ETAPA_ODC.NOME END) AS 'USUARIO_APROVADOR_ODC',
ETAPA_ODC.ETAPA AS 'ETAPA_ODC',
ODC.STATUS AS 'STATUS_ODC',
ODC.QUANTIDADETOTAL AS 'QUANTIDADETOTAL_ODC',
ODC.QUANTIDADE_RECEBIDA  AS 'QUANTIDADE_RECEBIDA_ODC',
ODC.QUANTIDADEARECEBER AS 'QUANTIDADEARECEBER_ODC',
CONVERT(DATE,ODC.DATA_ENTREGA_ODC) AS 'DATA_ENTREGA_ODC',
ODC.NOMEFANTASIA AS 'NOME_FANTASIA_ODC',
ODC.CONTATO AS 'CONTATO',
ODC.TELEFONE AS 'TELEFONE',
ODC.EMAIL AS 'EMAIL',
ODC.NOME AS 'NOME',
ODC.REPROGRAMACAO AS 'REPROGRAMACAO',
ODC.HISTORICO_ODC AS 'HISTORICO_ODC',
SOLICITACAO.MOTIVO AS 'MOTIVO',
SOLICITACAO.URGENCIA_PEDIDO AS 'URGENCIA_PEDIDO'
/* FIM CHAMADA ODC */

FROM SOLICITACAO 
LEFT JOIN TITMMOVRELAC				(NOLOCK) ON (TITMMOVRELAC.IDMOVORIGEM = SOLICITACAO.IDMOV		AND TITMMOVRELAC.NSEQITMMOVORIGEM = SOLICITACAO.NSEQITMMOV	AND TITMMOVRELAC.CODCOLORIGEM = SOLICITACAO.CODCOLIGADA)
LEFT JOIN ODC								 ON (TITMMOVRELAC.IDMOVDESTINO = ODC.IDMOV				AND TITMMOVRELAC.NSEQITMMOVDESTINO = ODC.NSEQITMMOV			AND TITMMOVRELAC.CODCOLDESTINO = ODC.CODCOLIGADA)
LEFT JOIN ETAPA AS ETAPA_SOLI				 ON	(ETAPA_SOLI.CODCOLIGADA = SOLICITACAO.CODCOLIGADA	AND ETAPA_SOLI.IDMOV = SOLICITACAO.IDMOV)
LEFT JOIN ETAPA AS ETAPA_ODC				 ON	(ETAPA_ODC.CODCOLIGADA = ODC.CODCOLIGADA			AND ETAPA_ODC.IDMOV = ODC.IDMOV)

/* FIM DA CONSULTA AGRUPADORA */ 

WHERE SOLICITACAO.IDMOV = 68366



