select * from TCCOTACAOITMMOV

LEFT JOIN TMOV ON (TCCOTACAOITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOV.IDMOV = TCCOTACAOITMMOV.IDMOV)

WHERE TMOV.CODTMV = '1.1.21' and TCCOTACAOITMMOV.idmov = 2119825