	SELECT

		ADIANTAMENTO.CODCOLIGADA AS COLIGADA
		,FCFO.NOMEFANTASIA AS FORNECEDOR
		,FCFO.CGCCFO AS CNPJ
		,GCCUSTO.CODCCUSTO
		,GCCUSTO.NOME AS NOME_CCUSTO
		/*********PRIMEIRO MOMENTO*********/
		
		,ADIANTAMENTO.VALORBAIXADO AS VLR_ADIANTADO
		,ADIANTAMENTO.IDLAN AS REF_ADIANTAMENTO_1
                                ,ADIANTAMENTO.USUARIOCRIACAO AS USUARIO_CRIACAO
		,CONVERT(VARCHAR, ADIANTAMENTO.DATABAIXA, 103) AS DATA_BAIXA_1
		,NOTA_CREDITO.VALORORIGINAL AS NOTA_CREDITO_GERADA		
		,NOTA_CREDITO.IDLAN AS REF_ADIANTAMENTO_2
		,CONVERT(VARCHAR, NOTA_CREDITO.DATABAIXA, 103) AS DATA_BAIXA_2

		/*********SEGUNDO MOMENTO*********/

		,LAN_NOTA_FISCAL.NUMERODOCUMENTO AS NOTA_VINCULADA
		,LAN_NOTA_FISCAL.VALORORIGINAL AS VALOR_ORIGINAL_SEM_RETENCAO
		,LAN_NOTA_FISCAL.VALOROP2 + LAN_NOTA_FISCAL.VALOROP3 AS TRIBUTOS
		,RECEBIMENTO.VALORVINCULO AS VALOR_ADIANTADO
		,LAN_NOTA_FISCAL.VALORBAIXADO AS LIQUIDO_PAGO
		,LAN_NOTA_FISCAL.IDLAN AS REF_BAIXA_3
		,CONVERT(VARCHAR,LAN_NOTA_FISCAL.DATABAIXA,103) AS DATA_BAIXA_3

		/*********TERCEIRO MOMENTO*********/

		,NOTA_CREDITO.VALORORIGINAL - (SELECT ISNULL(SUM(SOMA_VINCULO.VALORVINCULO),0)
									   FROM FRELLAN AS SOMA_VINCULO (NOLOCK)
									   WHERE NOTA_CREDITO.IDLAN = SOMA_VINCULO.IDLANREL AND NOTA_CREDITO.CODCOLIGADA = SOMA_VINCULO.CODCOLIGADA
									   AND SOMA_VINCULO.TIPOREL = 28 AND SOMA_VINCULO.RECCREATEDON <= RECEBIMENTO.RECCREATEDON
			) AS SALDO_ADIANTAMENTO
		,NOTA_CREDITO.CODTB2FLX AS CLASS_FIN
		,NOTA_CREDITO.IDLAN AS REF_NOTA_CREDITO
		,CONVERT(VARCHAR,LAN_NOTA_FISCAL.DATABAIXA,103) AS DATA_BAIXA_4
		,DBO.TRAZ_STATUSLAN(LAN_NOTA_FISCAL.STATUSLAN) AS STATUS_NF

		,(SELECT TOP 1 (CASE WHEN FLANBAIXA.STATUSCONTABIL = 1 THEN 'CONTABIL' ELSE 'NÃO CONTÁBIL' END)
		 FROM FLANBAIXA (NOLOCK) WHERE LAN_NOTA_FISCAL.IDLAN = FLANBAIXA.IDLAN AND LAN_NOTA_FISCAL.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
		) AS STATUS_CONTABIL
		
		,(CASE WHEN RECEBIMENTO.reccreateDON IS NULL THEN
		  DATEDIFF(DAY,ADIANTAMENTO.DATABAIXA,GETDATE()) ELSE
		  DATEDIFF(DAY,ADIANTAMENTO.DATABAIXA,LAN_NOTA_FISCAL.DATABAIXA) END) AS TEMPO
	
	FROM FLAN AS ADIANTAMENTO			(NOLOCK)
	LEFT JOIN FRELLAN					(NOLOCK) ON (ADIANTAMENTO.IDLAN = FRELLAN.IDLAN AND ADIANTAMENTO.CODCOLIGADA = FRELLAN.CODCOLIGADA/* AND ADIANTAMENTO.IDPGTO = 2*/)
	LEFT JOIN FLAN AS NOTA_CREDITO		(NOLOCK) ON (NOTA_CREDITO.IDLAN = FRELLAN.IDLANREL AND NOTA_CREDITO.CODCOLIGADA = FRELLAN.CODCOLIGADA)
	LEFT JOIN FRELLAN AS RECEBIMENTO	(NOLOCK) ON (NOTA_CREDITO.IDLAN = RECEBIMENTO.IDLANREL AND NOTA_CREDITO.CODCOLIGADA = RECEBIMENTO.CODCOLIGADA AND RECEBIMENTO.TIPOREL = 28)
	LEFT JOIN FLAN AS LAN_NOTA_FISCAL	(NOLOCK) ON (LAN_NOTA_FISCAL.IDLAN = RECEBIMENTO.IDLAN	AND LAN_NOTA_FISCAL.CODCOLIGADA = RECEBIMENTO.CODCOLIGADA)
	LEFT JOIN FLAN AS RETENCAO			(NOLOCK) ON (RETENCAO.IDLAN = RECEBIMENTO.IDLAN	AND RETENCAO.CODCOLIGADA = RECEBIMENTO.CODCOLIGADA AND RETENCAO.CODTDO = 0042)
	LEFT JOIN GCCUSTO					(NOLOCK) ON (ADIANTAMENTO.CODCCUSTO = GCCUSTO.CODCCUSTO AND ADIANTAMENTO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
	LEFT JOIN FTDO						(NOLOCK) ON (NOTA_CREDITO.CODTDO = FTDO.CODTDO AND NOTA_CREDITO.CODCOLIGADA = FTDO.CODCOLIGADA)
	INNER JOIN FCFO						(NOLOCK) ON (ADIANTAMENTO.CODCFO = FCFO.CODCFO AND ADIANTAMENTO.CODCOLCFO = FCFO.CODCOLIGADA)
	LEFT JOIN TMOV						(NOLOCK) ON (LAN_NOTA_FISCAL.IDMOV = TMOV.IDMOV AND LAN_NOTA_FISCAL.CODCOLIGADA = TMOV.CODCOLIGADA)
	LEFT JOIN FTB2						(NOLOCK) ON (ADIANTAMENTO.CODTB2FLX = FTB2.CODTB2FLX AND FTB2.CODCOLIGADA = ADIANTAMENTO.CODCOLIGADA)
	
	WHERE 
		FCFO.NOMEFANTASIA LIKE @FORNECEDOR
                                AND ADIANTAMENTO.CODTDO = '0036'
		AND NOTA_CREDITO.CODTDO = '0044'
		AND ADIANTAMENTO.DATABAIXA BETWEEN @DATA_INICIAL_BAIXA AND @DATA_FINAL_BAIXA 
		AND ADIANTAMENTO.CODCOLIGADA IN (@COLIGADA)
	                AND ADIANTAMENTO.CODTB2FLX IN (@CLASS_FIN)