SELECT 
CODCOLIGADA AS 'CODCOLIGADA', 
GRUPO.DATAFECHAMENTOESTOQUE61, 
GRUPO.DataMenosDoisMeses

FROM(
SELECT 
CODCOLIGADA,
DATAFECHAMENTOESTOQUE,
(SELECT TPAR1.DATAFECHAMENTOESTOQUE
 FROM TPAR AS TPAR1 
 WHERE TPAR1.codcoligada = 61) AS 'DATAFECHAMENTOESTOQUE61',
FORMAT(DATEADD(MONTH, -2, GETDATE()),'yyyy-MM-dd') AS DataMenosDoisMeses
FROM TPAR (NOLOCK)
/*where codcoligada = 61 */) AS GRUPO

WHERE CODCOLIGADA NOT IN (0, 54, 61)


COMMIT
BEGIN TRAN
update TPAR
SET DATAFECHAMENTOESTOQUE = '2024-01-01 00:00:00.000'
WHERE CODCOLIGADA = 10

SELECT CODCOLIGADA,DATAFECHAMENTOESTOQUE
FROM TPAR 

SELECT DATA_FINAL_EXEC
FROM [dbo].[CONSULTA_JOB]()
WHERE PROCESSO = 'EstRegerarSaldosECustosProcData' 

SELECT 
STRING_AGG( CODCOLIGADA, ', ') AS 'CODCOLIGADA',
CONVERT(DATE,(DATEADD(DAY, -1, GETDATE()))) AS 'DataOntem',
CONVERT(DATE,(GETDATE())) AS DataHoje,
CONVERT(DATE,(DATEADD(DAY, +1, GETDATE()))) AS DataAmanha

FROM(
SELECT 
CODCOLIGADA,  
STSJOB,
CONVERT(DATE,DATAPROGRAMADA) AS 'DATAPROGRAMADA',
CONVERT(DATE,DATA_FINAL_EXEC) AS 'DATA_FINAL_EXEC',
CONVERT(DATE,(DATEADD(DAY, -1, GETDATE()))) AS 'DataOntem',
CONVERT(DATE,(GETDATE())) AS DataHoje,
CONVERT(DATE,(DATEADD(DAY, +1, GETDATE()))) AS DataAmanha

FROM [dbo].[CONSULTA_JOB]()
WHERE PROCESSO = 'EstRegerarSaldosECustosProcData' 
AND codcoligada <> 61 
AND STSJOB <> 'PARADO'
AND STATUS NOT IN ('JOB ESTÁ EM EXECUÇÃO')

AND DATA_FINAL_EXEC IS NOT NULL) AS GRUPO
/*
WHERE GRUPO.DATA_FINAL_EXEC IS NOT NULL
AND (GRUPO.DATA_FINAL_EXEC = GRUPO.DataOntem OR GRUPO.DATA_FINAL_EXEC = GRUPO.DataHoje)*/

select * 
from [dbo].[CONSULTA_JOB]()

BEGIN TRAN
UPDATE [dbo].[CONSULTA_JOB]()
SET DATA_FINAL_EXEC = '2025-02-28 05:19:12.000'
WHERE CODCOLIGADA IN (10, 11, 12, 13, 14 ,15, 16, 18)

SELECT * 
FROM gjobx
where nome = 'Regerar Saldos e Custos'

/* 
2025-02-28 05:19:12.000
*/ 
