SELECT ZMDALCADASAPROVACAO.CODCOLIGADA,
PPESSOA.NOME, 
ZMDALCADASAPROVACAO.CODCCUSTO, 
GCCUSTO.NOME,
CODTMV, 
NIVEL, 
CONVERT(MONEY,VALOR_LIMITE) AS VALOR_LIMITE
FROM ZMDALCADASAPROVACAO 
JOIN HATENDENTE ON HATENDENTE.CODATENDENTE = ZMDALCADASAPROVACAO.CODATENDENTE
JOIN PPESSOA ON PPESSOA.CODIGO = HATENDENTE.CODPESSOA
JOIN GCCUSTO ON GCCUSTO.CODCCUSTO = ZMDALCADASAPROVACAO.CODCCUSTO

WHERE CODTMV = '1.1.60'

ORDER BY 1
