/*DECLARE @COLIGADA AS INT = 51,
		@DATAINI_D AS DATE = '20250701',
		@DATAFIM_D AS DATE = '20250731';*/

/* SOLICITADO PELO LUCAS - CONTROLE EMPREITEIRO E DESCONTO NA MEDIÇÃO / CHAMADO : 0324-000450*/

WITH 
CONTREMP AS (
SELECT 
REQUISICAO_MATERIAL.ID_REQUISICAO_MATERIAL,
REQUISICAO_MATERIAL.RM_CODCOLIGADA,
REQUISICAO_MATERIAL.RM_IDMOV,
REQUISICAO_MATERIAL.RM_IDPRD,
REQUISICAO_MATERIAL.ID_REQUISICAO,
REQUISICAO_MATERIAL.DESCONTAR_MEDICAO as 'Desconto',
SUBSTRING(DBCONTROLEMP.DBO.ASPNET_USERS.USERNAME, 9, 20) AS REQUISITANTE_NOME,
CONVERT(VARCHAR,DBCONTROLEMP.RMO.REQUISICAO.DATA_REQUISICAO,103) AS DATA_REQUISICAO,
CAST(REQUISICAO.DATA_EXPORTACAO AS DATE) AS DATA_EXPORTACAO,
CASE 
    WHEN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL.DESCONTAR_MEDICAO = 1 AND DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO IS NOT NULL	THEN ('MATERIAL PARA DESCONTO' + ' - '  + DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO) 
    WHEN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL.DESCONTAR_MEDICAO = 1 AND DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO IS NULL		THEN 'MATERIAL PARA DESCONTO - EMCCAMP'
	WHEN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL.DESCONTAR_MEDICAO = 0 AND DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO IS NOT NULL	THEN DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO 
    WHEN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL.DESCONTAR_MEDICAO = 0 AND DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO IS NULL		THEN 'EMCCAMP'
END AS EMPREITEIRO_1
FROM DBCONTROLEMP.RMO.REQUISICAO (NOLOCK)
INNER JOIN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL	(NOLOCK) ON (DBCONTROLEMP.RMO.REQUISICAO.ID_REQUISICAO = DBCONTROLEMP.RMO.REQUISICAO_MATERIAL.ID_REQUISICAO)
LEFT JOIN DBCONTROLEMP..EMPREITEIRO				(NOLOCK) ON (DBCONTROLEMP.RMO.REQUISICAO.ID_EMPREITEIRO = DBCONTROLEMP..EMPREITEIRO.ID_EMPREITEIRO)
LEFT JOIN DBCONTROLEMP.DBO.ASPNET_USERS			(NOLOCK) ON (DBCONTROLEMP.DBO.ASPNET_USERS.USERID = DBCONTROLEMP.RMO.REQUISICAO.ID_USUARIO_REQUISITANTE)
WHERE CAST(REQUISICAO.DATA_EXPORTACAO AS DATE) BETWEEN @DATAINI_D AND @DATAFIM_D
AND REQUISICAO_MATERIAL.RM_CODCOLIGADA IN (@COLIGADA)	
GROUP BY 
REQUISICAO_MATERIAL.ID_REQUISICAO_MATERIAL,
REQUISICAO_MATERIAL.RM_CODCOLIGADA,
REQUISICAO_MATERIAL.RM_IDMOV,
REQUISICAO_MATERIAL.RM_IDPRD,
REQUISICAO_MATERIAL.ID_REQUISICAO,
REQUISICAO_MATERIAL.DESCONTAR_MEDICAO,
DBCONTROLEMP.DBO.ASPNET_USERS.USERNAME,
DBCONTROLEMP.RMO.REQUISICAO.DATA_REQUISICAO,
DBCONTROLEMP..EMPREITEIRO.NOM_EMPREITEIRO,
REQUISICAO.DATA_EXPORTACAO)

SELECT 
A.NOME_PROJETO,
A.CENTRO_CUSTO_NOME,
A.MES_APROV,
A.ANO_APROV,
A.CODCCUSTO,
A.CLASE,
(CASE A.CLASE  
		WHEN 'MT' THEN 'MATERIAL' 
		WHEN 'EQ' THEN 'EQUIPAMENTO' 
		WHEN 'ST' THEN 'SERVIÇOS DE TERCEIROS'
		WHEN 'CI' THEN 'CUSTO INDIRETO'
		WHEN 'CIC' THEN 'CUSTO INDIRETO COMERCIAL'
	ELSE''
END) AS DESC_CLASSE,
A.SUB_CLASSE, 
A.DESC_SUB_CLASSE, 
A.DESCRICAO_GRUPO,
A.DESC_INS,
A.CODIGOPRD,
A.NOME_PRODUTO,
A.EMPREITEIRO_1,
A.NUMEROMOV,
A.DATAEMISSAO,
A.UND_DE_COMPRA,
A.QUANTIDADE,
A.PREÇO_UNITARIO,
A.VALOR,
A.CODTMV,
A.STATUS,
A.USUARIOCRIACAO,
A.DATACRIACAO,
A.USUARIO_APROVACAO,
A.DATAAPROVACAO,
A.DATAPG,
A.IDMOV,
A.REQUISICAO_ID,
A.REC_BASE,
A.ID_REQUISICAO_RMO,
A.REQUISITADO_POR_EM,
A.CODTRF,
A.DESCTRF,
A.CODTRF_PAI,
A.DESCTRFPAI


FROM (
SELECT 
(CASE 
	WHEN CODCLASSIFICACAO IN (10, 4, 6) THEN 'CIC'
	WHEN CODCLASSIFICACAO = 3 THEN 'CI' 
	WHEN CODTMV IN ('1.1.06', '1.1.40', '1.1.41', '1.1.42', '1.1.43') AND CODTMV_ORIGEM = '1.1.06' THEN 'ST'
	WHEN CODTMV = '1.1.27' AND MARC_PRA_DESCONTAR = 1 AND EMPREITEIRO_1 <> 'MATERIAL PARA DESCONTO - EMCCAMP' THEN 'ST'
	 WHEN SUB_CLASSE IN ('AC','ADM','AL','ALM','ALT','ATAE','ATE','ATEC','ATEL','ATH','ATIN','ATPO','AT-PO','ATRC','ATT','AUAX','AUD','C','CA','CO','CP','DBC','DF','DI','DRE','DVR','EPC',
                         'EX','EXT','EXTEL','FX','HB','I TX','LC','LD','MA','MAP','MC','ME','MMI','MOI','MOL','MOS','MTO','OTR','PJ','RP','S','SO','TFSLQA','TI','TO','TR','TX','V','VT') THEN 'CI'
	WHEN SUB_CLASSE IN  ('IPDV','MKTC','MKTIN','MKTM','MKTOUT','MKTPD','MKTPM','MKTPP','MKTPPI','MKTRE','MKTRV','MKTSI','MPDV','PBL','PBO','SMAQ','SV','SVC','SVF','SVM','SVP','SVS','VD') THEN 'CIC'
	WHEN LEFT(CODIGOPRD,3) = '001' THEN 'MT'
	WHEN LEFT(CODIGOPRD,3) = '002' THEN 'ST'
	WHEN LEFT(CODIGOPRD,3) = '003' THEN 'EQ'
	WHEN LEFT(CODIGOPRD,3) = '999' THEN [dbo].[CLASSEPORFASE](SUB_CLASSE)
	ELSE 'SEM CLASSE' END) AS 'CLASE',





* 


FROM (
SELECT 
(SELECT CONVERT(VARCHAR,GCCUSTO.CODCCUSTO)+' - '+ NOME FROM GCCUSTO (NOLOCK) WHERE GCCUSTO.CODCCUSTO = T.CODCCUSTO AND GCCUSTO.CODCOLIGADA = T.CODCOLIGADA) AS CENTRO_CUSTO_NOME,
(SELECT CONVERT(VARCHAR,PRJ.CODPRJ)+' - '+ CONVERT(VARCHAR,PRJ.DESCRICAO) AS NOME_PROJETO  FROM MPRJ AS PRJ WHERE PRJ.IDPRJ = T.IDPRJ AND  PRJ.CODCOLIGADA = T.CODCOLIGADA) AS NOME_PROJETO,
(SELECT CONVERT(VARCHAR, CODCOLIGADA) + ' - ' + NOMEFANTASIA FROM GCOLIGADA (NOLOCK) WHERE T.CODCOLIGADA = GCOLIGADA.CODCOLIGADA) AS NOME_COLIGADA,
DBO.ULTIMODIAMES(GETDATE())AS QUEBRA$,
CODCQ,
@MES_APROV AS MES_APROV,

		 ISNULL(LEFT((SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = T.PAI_FASE AND CODCOLIGADA = T.CODCOLIGADA),4),'') AS SUB_CLASSE,

				ISNULL((SELECT DESCRICAO FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = T.PAI_FASE AND CODCOLIGADA = T.CODCOLIGADA),'') AS DESC_SUB_CLASSE,

				CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
				AND CODCLIENTE = T.PAI_FASE 
				AND CODCOLIGADA = T.CODCOLIGADA) IN		('AC','ALT','AUD','C','CO','CP','DBC','EPI','FX','HB','MA','MMI','MOI','MOL',
														'MOS','PJ','RP','S','TO','TR','TX','USI','V')
				THEN 'CI'  WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
				AND CODCLIENTE = T.PAI_FASE 
				AND CODCOLIGADA = T.CODCOLIGADA) IN('APE','CG','CMD','ITB','MKT - CP','MKT - CP','MKT - PROD','MKT - PROM','PBL','PBO','SV','VD')

				THEN 'CIC' ELSE

				CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = T.PAI_FASE AND CODCOLIGADA = T.CODCOLIGADA) IN( 'T','FER','AL-EQ')
				THEN 'EQ' ELSE

				CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = T.PAI_FASE AND CODCOLIGADA = T.CODCOLIGADA) = 'AND'
				THEN 'MT' ELSE

				CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = T.PAI_FASE AND CODCOLIGADA = T.CODCOLIGADA) IN('CT','AL-ST')
				THEN 'ST' ELSE
				CASE WHEN LEFT(T.CODIGOPRD,1) = 'D' THEN 'CI' ELSE
					CASE WHEN LEFT(T.CODIGOPRD,1) = 'M' THEN 'MT' ELSE
					CASE WHEN LEFT(T.CODIGOPRD,1) = 'S' THEN 'ST' ELSE
					CASE WHEN LEFT(T.CODIGOPRD,1) = 'E' THEN 'EQ' ELSE
					CASE WHEN LEFT(T.CODIGOPRD,1) = 'T' THEN 'MT' ELSE
					CASE WHEN LEFT(T.CODIGOPRD,1) = 'A' THEN 'ST'
					END
				END
					END
					END
					END
					END
				END
				END
				END
				END AS 'FASE',
				
				
--ALTERADO O CAMPO ANO_APROV PARA MOSTAR A PALVRA BAIXA PARA MOSTRAR QUE É UM MOVIMENTO DE BAIXA~, NÃO QUE FOI BAIXADO. A PEDIDO DO LUCAS.PAULA CHAMADO =#0623-000242	*/
'BAIXA' AS ANO_APROV,
CODCCUSTO,
DESC_GRUPO,
DESC_INS,
EMPREITEIRO_1,
NUMEROMOV,
DATAEMISSAO,
CASE WHEN CODTMV = '2.2.05' THEN SUM(VALOR) * -1 ELSE SUM(VALOR) END AS VALOR,
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
USUARIO_APROVACAO,
DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO,
t.QUANTIDADE,
T.UND_DE_COMPRA,
T.PREÇO_UNITARIO,
ISNULL(CODTMV_ORIGEM,'N/A') AS CODTMV_ORIGEM
,T.CODCOLIGADA
,CODGRUPO
,DESCRICAO_GRUPO
,REQUISITADO_POR_EM
,REQUISICAO_ID
,REC_BASE
,IDPRD
,T.CODIGOPRD
,T.CODCLASSIFICACAO,
T.MARC_PRA_DESCONTAR
,T.ID_REQUISICAO_RMO
,t.NUMEROSEQUENCIAL

FROM (
SELECT CODCQ, TMOV.IDMOV, TMOV.CODCCUSTO,TMOV.CODCOLIGADA, TMOV.IDPRJ,  FCFO.NOME,

PRODUTO.NOMEFANTASIA AS NOME_PRODUTO,
PRODUTO_DEF.CODUNDCOMPRA AS UND_DE_COMPRA,
PRODUTO_DEF.CUSTOUNITARIO AS PREÇO_UNITARIO,
(CASE WHEN TMOV.CODTMV = '2.2.05' THEN  -1 * TITMMOV.QUANTIDADE ELSE TITMMOV.QUANTIDADE END) AS 'QUANTIDADE',
DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AS PAI_FASE,

MTRF.CODTRF,
ISNULL (MTRF.NOME,MTRF.DESCRICAO) AS DESCTRF,
MTRFPAI.CODTRF AS CODTRF_PAI,
ISNULL (MTRFPAI.NOME,MTRFPAI.DESCRICAO) AS DESCTRFPAI,
(SELECT NOMEFANTASIA FROM TPRD (NOLOCK) WHERE IDPRD = PRODUTO.IDPRD AND CODCOLIGADA =TMOV.CODCOLIGADA) AS 'DESC_GRUPO',
(SELECT TTB22.DESCRICAO 
FROM TTB2 AS TTB22
WHERE TTB22.CODCOLIGADA = PRODUTO_DEF.CODCOLIGADA AND TTB22.CODTB2FAT = PRODUTO_DEF.CODTB2FAT) AS 'DESC_INS',
ISNULL(FCFO.NOMEFANTASIA,'') AS NOME_FORNECEDOR,
TMOV.NUMEROMOV,
CONVERT(VARCHAR,DATEADD(D,(SELECT TOP 1 PRAZO1 FROM TCPG (NOLOCK) WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND CODCPG = TMOV.CODCPG),TMOV.DATAEMISSAO),103) DATAPG,

((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV (NOLOCK) WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
CASE WHEN ISNULL(TITMMOV.QUANTIDADETOTAL,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO * TITMMOV.QUANTIDADETOTAL ) / CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END )) 
ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO * TITMMOV.QUANTIDADETOTAL ) / CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END ))/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
)* TITMMOV.QUANTIDADETOTAL)) AS VALOR,

CONVERT(VARCHAR, TMOV.DATACRIACAO,103) AS CRIACAO,
(SELECT NOMEFANTASIA FROM TPRD (NOLOCK) WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =1)AS PRODUTO,

TMOV.CODTMV,
DBO.TRAZ_STATUS(TMOV.STATUS) AS STATUS,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
TMOVAPROVA.CODUSUARIO AS USUARIO_APROVACAO,
TMOVAPROVA.DATAAPROVACAO,
TMOV.DATAEMISSAO,

(SELECT TOP 1 FLAN.IDLAN FROM FLAN (NOLOCK) 
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
AND		FLAN.CODTB2FLX NOT IN ('129','02.023')) AS REFERENCIA_PGTO,

(SELECT TOP 1 REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLAN.HISTORICO),CHAR(13) + CHAR(10),' '),';',' ') FROM FLAN (NOLOCK)
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
AND		FLAN.CODTB2FLX NOT IN ('129','02.023')) AS HISTORICO_PGTO,


(SELECT TOP 1 MOVT.CODTMV
FROM TMOVRELAC (NOLOCK)
INNER JOIN TMOV AS MOVT (NOLOCK) ON (MOVT.IDMOV = TMOVRELAC.IDMOVDESTINO AND MOVT.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
WHERE TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV  AND TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
) AS CODTMV_ORIGEM  /*OBS: O RELACIONAMENTO DO JOIN ESTÁ INVERTIDO POIS É COPIA DE MOVIMENTO POR REFERÊNCIA */

		,/*(
			SELECT TOP 1 TITMMOVCOMPL.ID_REQUISICAO_RMO
			FROM TITMMOVCOMPL (NOLOCK)
			
			WHERE TITMMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA
			AND TITMMOVCOMPL.IDMOV = TMOV.IDMOV
			AND TITMMOVCOMPL.NSEQITMMOV = TITMMOV.NSEQITMMOV
		) ID_REQUISICAO,*/

		CASE 
			WHEN REQUISITANTE_NOME IS NULL THEN ''
			ELSE CONCAT('REQUISITADO POR ', REQUISITANTE_NOME, ' EM ', DATA_REQUISICAO)
			END AS REQUISITADO_POR_EM,

			/* SOLICITADO PELO LUCAS - CONTROLE EMPREITEIRO E DESCONTO NA MEDIÇÃO / CHAMADO : 0324-000450*/
			
			EMPREITEIRO_1,
			TPRDGRUPOPRODUTO.CODGRUPO,
			(TGRUPOPRODUTO.CODGRUPO + ' - ' + TGRUPOPRODUTO.DESCRICAO) AS 'DESCRICAO_GRUPO',
			GCRATEADO.CODCLASSIFICA AS 'CODCLASSIFICACAO',
			PRODUTO.CODIGOPRD,
			TITMMOV.NUMEROSEQUENCIAL,
			CONTREMP.Desconto AS 'MARC_PRA_DESCONTAR',
			TITMMOV.IDPRD,
			CONTREMP.ID_REQUISICAO AS 'REC_BASE',
			TITMMOVCOMPL.ID_REQUISICAO_RMO,
			(SELECT TOP 1 REC_MAT.ID_REQUISICAO
			 FROM DBCONTROLEMP.RMO.REQUISICAO_MATERIAL AS REC_MAT
			 WHERE ID_REQUISICAO_MATERIAL = TITMMOVCOMPL.ID_REQUISICAO_RMO
			 and RM_CODCOLIGADA IN (@COLIGADA)) AS REQUISICAO_ID


			


FROM TMOV (NOLOCK)

LEFT JOIN GCCUSTO						(NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN TITMMOV						(NOLOCK) ON (TMOV.IDMOV = TITMMOV.IDMOV AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT JOIN TITMMOVCOMPL					(NOLOCK) ON TITMMOV.IDMOV = TITMMOVCOMPL.IDMOV AND TITMMOV.CODCOLIGADA = TITMMOVCOMPL.CODCOLIGADA AND TITMMOV.NSEQITMMOV = TITMMOVCOMPL.NSEQITMMOV
LEFT JOIN MPRJ							(NOLOCK) ON (TMOV.CODCOLIGADA = MPRJ.CODCOLIGADA AND TMOV.IDPRJ = MPRJ.IDPRJ)
LEFT JOIN MPRJCOMPL						(NOLOCK) ON (MPRJ.CODCOLIGADA = MPRJCOMPL.CODCOLIGADA AND MPRJ.IDPRJ = MPRJCOMPL.IDPRJ)
LEFT JOIN MTRF							(NOLOCK) ON (MPRJ.CODCOLIGADA = MTRF.CODCOLIGADA AND MPRJ.IDPRJ = MTRF.IDPRJ  AND TITMMOV.IDTRF = MTRF.IDTRF)
LEFT JOIN MTRF AS MTRFPAI				(NOLOCK) ON (MTRFPAI.IDTRF = MTRF.IDPAI AND MTRFPAI.IDPRJ = MTRF.IDPRJ AND MTRFPAI.CODCOLIGADA = MTRF.CODCOLIGADA)
LEFT JOIN TPRD  AS PRODUTO				(NOLOCK) ON (produto.CODCOLIGADA = TITMMOV.CODCOLIGADA and produto.IDPRD = TITMMOV.IDPRD)
LEFT JOIN TPRDGRUPOPRODUTO				(NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = PRODUTO.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = PRODUTO.CODCOLIGADA)
LEFT JOIN TGRUPOPRODUTO					(NOLOCK) ON (TGRUPOPRODUTO.CODCOLIGADA = TPRDGRUPOPRODUTO.CODCOLPRD AND TGRUPOPRODUTO.CODGRUPO = TPRDGRUPOPRODUTO.CODGRUPO)
LEFT JOIN TPRODUTODEF as PRODUTO_DEF	(NOLOCK) ON (PRODUTO_DEF.IDPRD = PRODUTO.IDPRD AND PRODUTO_DEF.CODCOLIGADA = PRODUTO.CODCOLIGADA) 
LEFT JOIN FCFO							(NOLOCK) ON (TMOV.CODCOLCFO = FCFO.CODCOLIGADA AND TMOV.CODCFO = FCFO.CODCFO)
LEFT JOIN TMOVAPROVA					(NOLOCK) ON (TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA AND TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)
LEFT JOIN CONTREMP								 ON	(CONTREMP.RM_IDMOV = TITMMOV.IDMOV AND CONTREMP.RM_CODCOLIGADA = TITMMOV.CODCOLIGADA AND TITMMOVCOMPL.ID_REQUISICAO_RMO = CONTREMP.ID_REQUISICAO_MATERIAL AND TITMMOV.IDPRD = CONTREMP.RM_IDPRD)
LEFT JOIN TMOVRATCCU					(NOLOCK) ON (TMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCU.IDMOV = TMOV.IDMOV)
LEFT JOIN GCCUSTO AS GCRATEADO 			(NOLOCK) ON (TMOVRATCCU.CODCCUSTO = GCRATEADO.CODCCUSTO AND TMOVRATCCU.CODCOLIGADA = GCRATEADO.CODCOLIGADA)
LEFT JOIN TMOVCOMPL					(NOLOCK) ON (TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA)

WHERE 
TMOV.CODCOLIGADA IN (@COLIGADA)
AND (MPRJ.CODPRJ LIKE '__.____.___' OR MPRJ.CODPRJ LIKE 'VIAB.__.____.___')
/*and produto.NOMEFANTASIA like '%bloco%'*/
/*AND MPRJ.CODPRJ IN (@CODPRJ)*/
AND TMOV.CODTMV IN ('1.1.27','2.2.05')
--AND TMOV.CODCCUSTO IN (@CCUSTO_INI)
/*AND TMOV.IDMOV = 34725*/
AND TMOV.DATAEMISSAO BETWEEN @DATAINI_D AND @DATAFIM_D
AND TMOV.STATUS <> 'C'
AND (TITMMOV.QUANTIDADE > 0 OR TITMMOV.QUANTIDADETOTAL <> 0)
AND (TMOV.VALORBRUTO > 0 OR TMOV.VALORBRUTOORIG <> 0)
/*and TMOV.IDMOV = '35645'
AND PRODUTO.CODIGOPRD = '001.13652'*/


) AS T
GROUP BY 
T.MARC_PRA_DESCONTAR,
CODCQ,
CODCCUSTO,
PAI_FASE,
T.CODIGOPRD,
DESC_GRUPO,
DESC_INS,
NOME_FORNECEDOR,
EMPREITEIRO_1,
NUMEROMOV,
DATAEMISSAO,
CODTMV,
STATUS,
CODGRUPO,
DESCRICAO_GRUPO,
USUARIOCRIACAO,
DATACRIACAO,
USUARIO_APROVACAO,
DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO,
t.QUANTIDADE,
T.UND_DE_COMPRA,
T.PREÇO_UNITARIO,
T.CODTMV_ORIGEM,
T.CODCOLIGADA
,T.IDPRJ
,IDPRD
,T.NOME
,REC_BASE
,REQUISITADO_POR_EM
,T.CODCLASSIFICACAO,
t.NUMEROSEQUENCIAL,
T.ID_REQUISICAO_RMO,
T.REQUISICAO_ID

/*
ORDER BY DATAPG,VALOR
*/
) AS GRUPO
) AS A

order by A.NOME_PRODUTO
