
DECLARE @CODCCUSTO AS VARCHAR(15) = '3.0001.06',
		@CGC_FILIAL AS VARCHAR(50) = '44763499000326';


SELECT 
    GFILIAL.CODCOLIGADA,
    -1 AS IDMOV,
    GFILIAL.CODFILIAL,
    ZMDCCUSTOXLOCAL.CODLOCAL AS CODLOC,
    'F51196' AS CODCFO,
    0 AS CODCOLCFO,
    'C' AS SERIE,
    '1.1.07' AS CODTMV,
    'A' AS STATUS,
    '054' AS CODCPG,
    '0005' AS CODTB1FLX,
    '1' AS FRETECIFOUFOB,
    @CODCCUSTO AS CODCCUSTO,
    'T' AS INTEGRAAPLICACAO,
    isnull((SELECT TOP 1  MPRJ.IDPRJ FROM MPRJ (NOLOCK)
			INNER JOIN MTRFCCUSTO (NOLOCK) ON MTRFCCUSTO.IDPRJ = MPRJ.IDPRJ AND MPRJ.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MPRJ.REVISAO = ( SELECT MAX(PRJ.REVISAO) FROM MPRJ AS PRJ WHERE PRJ.CODPRJ= MPRJ.CODPRJ AND PRJ.CODCOLIGADA = MPRJ.CODCOLIGADA)
	WHERE  MTRFCCUSTO.CODCOLIGADA = GFILIAL.CODCOLIGADA AND ZMDCCUSTOXLOCAL.CODLOCAL = MTRFCCUSTO.CODCCUSTO AND  EXISTS(SELECT 1 FROM MTRFCCUSTO AS RATEIO WHERE RATEIO.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MTRFCCUSTO.IDPRJ = RATEIO.IDPRJ AND RATEIO.CODCCUSTO =@CODCCUSTO)
	and MPRJ.CODPRJ LIKE '__.____.___'),(SELECT PRJ.IDPRJ FROM MPRJ AS PRJ WHERE PRJ.CODFILIAL = GFILIAL.CODFILIAL AND PRJ.CODCOLIGADA = GFILIAL.CODCOLIGADA AND PRJ.CODCCUSTO =@CODCCUSTO AND PRJ.CODPRJ LIKE '__.____.___' AND PRJ.REVISAO = (
						  SELECT MAX(PROJ.REVISAO) FROM MPRJ AS PROJ WHERE PROJ.CODPRJ= PRJ.CODPRJ AND PROJ.CODCOLIGADA = PRJ.CODCOLIGADA))) AS IDPRJ,
    /*
    isnull((SELECT TOP 1  MPRJ.IDPRJ FROM MPRJ (NOLOCK)
			INNER JOIN MTRFCCUSTO (NOLOCK) ON MTRFCCUSTO.IDPRJ = MPRJ.IDPRJ AND MPRJ.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MPRJ.REVISAO = (
						  SELECT MAX(PRJ.REVISAO) FROM MPRJ AS PRJ WHERE PRJ.CODPRJ= MPRJ.CODPRJ AND PRJ.CODCOLIGADA = MPRJ.CODCOLIGADA)
	WHERE MTRFCCUSTO.CODCCUSTO = :CODCCUSTO AND MTRFCCUSTO.CODCOLIGADA = GFILIAL.CODCOLIGADA
	and MPRJ.CODPRJ LIKE '__.____.___'),(SELECT PRJ.IDPRJ FROM MPRJ AS PRJ WHERE PRJ.CODFILIAL = GFILIAL.CODFILIAL AND PRJ.CODCOLIGADA = GFILIAL.CODCOLIGADA AND PRJ.CODCCUSTO = :CODCCUSTO AND PRJ.CODPRJ LIKE '__.____.___' AND PRJ.REVISAO = (
						  SELECT MAX(PROJ.REVISAO) FROM MPRJ AS PROJ WHERE PROJ.CODPRJ= PRJ.CODPRJ AND PROJ.CODCOLIGADA = PRJ.CODCOLIGADA))) AS IDPRJ,
*/
    '' AS HISTORICOLONGO,
	'' AS PEDIDOBRS 

FROM GFILIAL (NOLOCK)
INNER JOIN ZMDCCUSTOXLOCAL (NOLOCK) ON ZMDCCUSTOXLOCAL.CODFILIAL = GFILIAL.CODFILIAL AND ZMDCCUSTOXLOCAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND ZMDCCUSTOXLOCAL.CODCCUSTO = @CODCCUSTO
WHERE REPLACE(REPLACE(REPLACE(GFILIAL.CGC,'.',''),'/',''),'-','') = @CGC_FILIAL
AND GFILIAL.ATIVO = 1

--select * 
--from gfilial 
--where cgc = '44.763.499/0003-26'

--SELECT * 
--FROM MPRJ
--WHERE CODCOLIGADA = 60 