/*declare @DATA_INI_D date = '20240301'
declare @DATA_FIM_D	date = '20240331'
declare @CONTA_CAIXA varchar(15) = '56161-4'
declare @COLIGADA int = 1*/

SELECT 

FXCX.IDXCX AS IDXCX2
,(CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO OR FXCX.IDFORMAPAGTO IN ('2','4') OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATACOMPENSACAO ELSE FXCX.DATA END) AS DATA
,FXCX.NUMERODOCUMENTO

,(SELECT TOP 1 CASE WHEN FLAN.CNABSTATUS <> 0 THEN
	CASE WHEN FLAN.PAGREC = 2 THEN
	'CEF REMESSA' ELSE FXCX.NOMINAL END 
	ELSE FXCX.NOMINAL END) AS 'NOMINAL'
,FXCX.VALOR

	,(

	SELECT DISTINCT  TOP 1 SUM(FXCX.VALOR)

	FROM FXCX (NOLOCK)

	WHERE FXCX.COMPENSADO<>2 
	AND FXCX.CODCXA = @CONTA_CAIXA
	AND (CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO AND FXCX.IDFORMAPAGTO = '2' OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATA ELSE FXCX.DATACOMPENSACAO END ) < @DATA_INI_D
	AND FXCX.CODCOLIGADA = @COLIGADA
	AND FXCX.TIPO NOT IN (8,9,10)
	AND FXCX.DATAESTORNO IS NULL
	) +	(SUM(FXCX.VALOR) OVER(ORDER BY FXCX.DATACOMPENSACAO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW))AS SALDO,
	FXCX.CODCOLIGADA,
/* INICIO 009.002 */ 
FLAN.IDLAN,
FLANBAIXA.DATACONTABILIZBX AS 'DATA CONTABILIZAÇÃO',
GCCUSTO.CODCCUSTO AS 'CENTRO DE CUSTO',
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO', 
FCFO.NOME AS 'NOME FANTASIA', 
FLAN.HISTORICO,
FLANBAIXA.VALORBAIXA AS 'VALOR BAIXADO', 
FLAN.DATABAIXA AS 'DATA DA BAIXA',
FLAN.CODTB2FLX, 
FTB5.DESCRICAO AS 'DESCRICAO ITEM',
/* FIM 009.002 */ 

/* INICIO 009.051 */ 
CAST(
    ROUND(
        (
            FLAN.VALORORIGINAL - 
            (
                FLAN.VALORDESCONTO +
                FLAN.VALORADIANTAMENTO +
                FLAN.VALORDEVOLUCAO +
                FLAN.VALOROP1 +
                FLAN.VALOROP2 +
                FLAN.VALOROP3 +
                FLAN.VALOROP5 +
                FLAN.VALORINSS +
                FLAN.VALORIRRF +
                FLAN.VALORSESTSENAT +
                (SELECT ISNULL(SUM(FTRBLAN.VALOR), 0) FROM FTRBLAN (NOLOCK) WHERE FTRBLAN.IDLAN = FLAN.IDLAN AND FTRBLAN.CODCOLIGADA = FLAN.CODCOLIGADA)
            ) +
            FLAN.VALOROP4 +
            FLAN.VALORJUROS +
            FLAN.VALORMULTA
        ) * ISNULL(FLANRATCCU.PERCENTUAL, 100) / 100, 
        2
    ) 
AS money) AS 'VALOR_LIQUIDO_RATEADO',


dbo.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA, FLAN.IDLAN, GCCUSTO.CODCCUSTO) AS 'VALOR_LIQUIDO_RATEADO2',
FLAN.DATABAIXA,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
FLAN.NUMERODOCUMENTO as 'NUNDOC',
DBO.REMOVE_QUEBRA_LINHA(FLAN.HISTORICO) AS 'FLAN_HISTORICO'

/* FIM 009.051 */

FROM FXCX (NOLOCK)
LEFT JOIN FLANBAIXA			(NOLOCK) ON (FXCX.CODCOLIGADA = FLANBAIXA.CODCOLXCX AND FXCX.IDXCX = FLANBAIXA.IDXCX)
LEFT JOIN FLAN				(NOLOCK) ON (FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN)
LEFT JOIN TMOV				(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB5				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN FCFO				(NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN FCFODEF			(NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB2 AS FTB2_DEF	(NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)
LEFT JOIN FTB2				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB2.CODCOLIGADA AND FLAN.CODTB2FLX=FTB2.CODTB2FLX)
LEFT JOIN FLANRATCCU		(NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN)
LEFT JOIN GCCUSTO			(NOLOCK) ON (GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO AND GCCUSTO.CODCOLIGADA = FLAN.CODCOLIGADA)

WHERE		
		FXCX.DATACOMPENSACAO BETWEEN @DATA_INI_D AND @DATA_FIM_D
		AND FXCX.CODCOLIGADA = @COLIGADA
		AND FXCX.CODCXA = @CONTA_CAIXA
		AND FXCX.DATAESTORNO IS NULL
ORDER BY
(CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO OR FXCX.IDFORMAPAGTO IN ('2','4') OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATACOMPENSACAO ELSE FXCX.DATA END)