--SQL - EMC.T.019.07-02.2 - CONSULTA EMPREITEIRO - PORTAL
/*DECLARE @EMPREITEIRO VARCHAR (6)	='F51911'
DECLARE @CODCOLIGADA INT =26*/


SELECT 
GRUPO.CODCFO,
GRUPO.NOMEFANTASIA + ' - (' + DBO.INITCAP(GRUPO.NOME) + ')' + '   /  CNPJ: ' + GRUPO.CGCCFO + '   /   INCLUSÃO: ' + CONVERT (VARCHAR, GRUPO.DATACRIACAO,103) AS EMPREITEIRO,
(GRUPO.CODCCUSTO + ' - ' + (SELECT NOME FROM GCCUSTO (NOLOCK) WHERE CODCCUSTO = GRUPO.CODCCUSTO AND CODCOLIGADA = @CODCOLIGADA)) AS NOME_CCUSTO,

(SELECT TOP 1 NOM_EMPREENDIMENTO 
FROM DBCONTROLEMP.DBO.EMPREENDIMENTO (NOLOCK)
INNER JOIN DBCONTROLEMP.DBO.OBRA (NOLOCK) ON (DBCONTROLEMP.DBO.OBRA.ID_EMPREENDIMENTO = DBCONTROLEMP.DBO.EMPREENDIMENTO.ID_EMPREENDIMENTO)
WHERE DBCONTROLEMP.DBO.OBRA.RM_CODCCUSTO =GRUPO.CODCCUSTO AND DBCONTROLEMP.DBO.OBRA.RM_CODCOLIGADA = @CODCOLIGADA) AS EMPREENDIMENTO,


(SELECT MAX (DATABAIXA) FROM FLAN (NOLOCK)

WHERE FLAN.CODTB2FLX IN ('062','02.124')
AND	  STATUSLAN <> '2'
AND	  CODCFO = GRUPO.CODCFO
AND   CODCOLIGADA = GRUPO.COLIGADA
AND   CODCCUSTO = GRUPO.CODCCUSTO) AS ULTIMA_MOVIMENTACAO,

SUM(GRUPO.VLR_RETENCOES) AS 'VLR_RETENCOES',
SUM(GRUPO.VLR_NAOVINCULADOS) AS 'VLR_NAOVINCULADOS',
SUM(GRUPO.VLR_SALDOCONTROLEMP) AS 'VLR_SALDOCONTROLEMP' ,
SUM(GRUPO.VLR_ADIANT_PLAN_CONT) AS 'VLR_ADIANT_PLAN_CONT',
SUM(GRUPO.VLR_ADIANT_DIVER_OBRA) AS 'VLR_ADIANT_DIVER_OBRA',
SUM(GRUPO.VLR_DESCONTO *-1) AS 'DESCONTO',
SUM(GRUPO.VLR_ADIANTAMENTO_CX4) AS 'VLR_ADIANTAMENTO_CX4'

 FROM 

(SELECT 
EMPREITEIROS.NOME,
EMPREITEIROS.DATACRIACAO,
EMPREITEIROS.CGCCFO,
EMPREITEIROS.COLIGADA,
EMPREITEIROS.CODCFO,
EMPREITEIROS.NOMEFANTASIA,
EMPREITEIROS.CODCCUSTO,
ISNULL (RETENCOES.VLR_RETENCOES,0) AS VLR_RETENCOES,
ISNULL (RETENCOES_CONTACAIXA4.DESCONTO,0) AS VLR_DESCONTO,
ISNULL (NAOVINCULADOS.VLR_NAOVINCULADOS,0) AS VLR_NAOVINCULADOS,
ISNULL (SALDOCONTROLEMP.VLR_SALDOCONTROLEMP,0) AS VLR_SALDOCONTROLEMP,
ISNULL (ADIANT_PLAN_CONT.VALORORIGINAL,0) AS VLR_ADIANT_PLAN_CONT,
ISNULL (ADIANT_DIVER_OBRA.VALORORIGINAL,0) AS VLR_ADIANT_DIVER_OBRA,
ISNULL (ADIANTAMENTO_CX4.VLR_ADIANTAMENTO_CX4,0) AS VLR_ADIANTAMENTO_CX4



FROM 
  (		
  
		/* AGRUPAMENTO INTERNO FEITO PARA CONTEMPLAR EMPREITEIROS DO CONTROLEMP E RM */
		SELECT 
		* 
		FROM 

		(

				SELECT 
				FCFO.CODCFO,
				FCFO.CGCCFO,
				FCFO.NOME,
				FCFO.DATACRIACAO,
				FLAN.CODCOLIGADA,
				FCFO.NOMEFANTASIA,
				ISNULL (FLAN.CODCCUSTO,'1.0012') AS CODCCUSTO,
				ISNULL (FLAN.CODCOLIGADA,@CODCOLIGADA) AS COLIGADA

				FROM FCFO (NOLOCK)

				LEFT JOIN FLAN (NOLOCK) ON (FCFO.CODCFO = FLAN.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
				WHERE /*FCFO.CODCFO = @EM_PREITEIRO*/
				(FCFO.CODCFO = @EMPREITEIRO)
				AND FLAN.CODCOLIGADA = @CODCOLIGADA

				UNION ALL

				SELECT 
				EMPREITEIRO.RM_CODCFO, 
				(SELECT F.CGCCFO		FROM FCFO AS F	(NOLOCK) WHERE F.CODCFO = EMPREITEIRO.RM_CODCFO AND F.CODCOLIGADA = EMPREITEIRO.RM_CODCOLIGADA) AS CODCFO,
				(SELECT F.NOME			FROM FCFO AS F	(NOLOCK) WHERE F.CODCFO = EMPREITEIRO.RM_CODCFO AND F.CODCOLIGADA = EMPREITEIRO.RM_CODCOLIGADA) AS NOME,
				(SELECT F.DATACRIACAO	FROM FCFO AS F	(NOLOCK) WHERE F.CODCFO = EMPREITEIRO.RM_CODCFO AND F.CODCOLIGADA = EMPREITEIRO.RM_CODCOLIGADA) AS DATACRIACAO,
				(SELECT F.CODCOLIGADA	FROM FCFO AS F	(NOLOCK) WHERE F.CODCFO = EMPREITEIRO.RM_CODCFO AND F.CODCOLIGADA = EMPREITEIRO.RM_CODCOLIGADA) AS CODCOLIGADA,
				(SELECT F.NOMEFANTASIA	FROM FCFO AS F	(NOLOCK) WHERE F.CODCFO = EMPREITEIRO.RM_CODCFO AND F.CODCOLIGADA = EMPREITEIRO.RM_CODCOLIGADA) AS NOMEFANTASIA,
				ISNULL (OBRA.RM_CODCCUSTO,'1.0012') AS CODCCUSTO,
				@CODCOLIGADA AS COLIGADA

				FROM DBCONTROLEMP.DBO.EMPREITEIRO AS EMPREITEIRO (NOLOCK)
				 
				LEFT JOIN DBCONTROLEMP.DBO.CONTRATO AS CONTRATO		(NOLOCK) ON (CONTRATO.ID_EMPREITEIRO = EMPREITEIRO.ID_EMPREITEIRO)
				LEFT JOIN DBCONTROLEMP.DBO.OBRA	 AS OBRA			(NOLOCK) ON (CONTRATO.ID_OBRA = OBRA.ID_OBRA AND OBRA.RM_CODCOLIGADA = @CODCOLIGADA)

				WHERE /*EMPREITEIRO.RM_CODCFO = @EM_PREITEIRO*/
				(EMPREITEIRO.RM_CODCFO LIKE @EMPREITEIRO)	
				AND OBRA.RM_CODCOLIGADA = @CODCOLIGADA /*ADICIONADO POIS ESTAVA TRAZENDO DADOS DE OUTRAS COLIGADAS COMO COLIGADA ZERO*/
				AND OBRA.RM_CODCOLIGADA <> 0
		)AS EMPREITEIROS_CONTROLEMP_RM 

		GROUP BY

		EMPREITEIROS_CONTROLEMP_RM.CODCFO,
		EMPREITEIROS_CONTROLEMP_RM.CGCCFO,
		EMPREITEIROS_CONTROLEMP_RM.NOME,
		EMPREITEIROS_CONTROLEMP_RM.DATACRIACAO,
		EMPREITEIROS_CONTROLEMP_RM.CODCOLIGADA,
		EMPREITEIROS_CONTROLEMP_RM.NOMEFANTASIA,
		EMPREITEIROS_CONTROLEMP_RM.CODCCUSTO,
		EMPREITEIROS_CONTROLEMP_RM.COLIGADA


  ) AS EMPREITEIROS /* TRAZ TODOS EMPREITEIROS DO RM FLUXUS E QUE POSSUAM CONTRATO NO CONTROLEMP--- MUDANÇA FEITA PELA MICHELLE A PARTIR DO DIA 20/01/2017*/ 


/* JOIN USANDO SELECT PARA TRAZER RETENCOES EM ABERTO */
LEFT JOIN (

			SELECT 
			
			GRUPO.CODCFO,
			GRUPO.NOMEFANTASIA,
			GRUPO.CODCOLIGADA,
			GRUPO.CODCCUSTO,
			GRUPO.DESCRICAO,
			SUM (VALOR) AS VLR_RETENCOES
			
			 FROM 
			
			(
				SELECT
				
				FCFO.CODCFO,
				FCFO.NOMEFANTASIA,
				FCFO.CODCOLIGADA,
				FLAN.CODCCUSTO,	
				GCCUSTO.CODCCUSTO +' - '+ GCCUSTO.NOME AS OBRA, 
				FTB2.DESCRICAO,
				SUM((FLAN.VALOROP1 + FLAN.VALORJUROS + FLAN.VALORMULTA) - 
				                (FLAN.VALORDESCONTO + FLAN.VALOROP2 + FLAN.VALOROP3 + FLAN.VALOROP4 + FLAN.VALOROP5 + FLAN.VALOROP6 + FLAN.VALOROP7 + FLAN.VALORADIANTAMENTO + FLAN.VALORDEVOLUCAO) + 
				                 FLAN.VALORORIGINAL - FLAN.VALORINSS - FLAN.VALORIRRF)AS VALOR
				
				
				FROM TMOV (NOLOCK)
				
				INNER JOIN GCCUSTO (NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA =TMOV.CODCOLIGADA)
				INNER JOIN FLAN	   (NOLOCK) ON (TMOV.CODCOLIGADA = FLAN.CODCOLIGADA AND TMOV.IDMOV = FLAN.IDMOV)
				INNER JOIN FCFO    (NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
				INNER JOIN FTB2    (NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
				
				WHERE TMOV.CODCOLIGADA = @CODCOLIGADA
				AND TMOV.CODCOLIGADA <> 0
				/*ALTERADO CODTMV PARA BUSCAR TODOS MOVIMENTOS 1.2 - CHAMADO 0824-001252 - FLAVIA GIBRAM */
				/*AND TMOV.CODTMV IN ('1.2.07', '1.2.08','1.2.14','1.2.13')*/
				AND TMOV.CODTMV LIKE ('1.2.__')
				AND FLAN.CODTB2FLX IN ('129','02.023')
				AND FLAN.PAGREC = 2
				AND FLAN.STATUSLAN NOT IN ('1','2')
				/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (FCFO.CODCFO = @EMPREITEIRO)
				
				GROUP BY 
				
				FCFO.CODCFO,
				FCFO.NOMEFANTASIA,
				FLAN.CODCCUSTO,
				FCFO.CODCOLIGADA,
				GCCUSTO.CODCCUSTO,
				FTB2.DESCRICAO,
				GCCUSTO.NOME
			) AS GRUPO
			
			GROUP BY 
			GRUPO.CODCFO,
			GRUPO.NOMEFANTASIA,
			GRUPO.DESCRICAO,
			GRUPO.CODCOLIGADA,
			GRUPO.CODCCUSTO
) AS RETENCOES ON (RETENCOES.CODCFO = EMPREITEIROS.CODCFO AND RETENCOES.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND RETENCOES.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)

/* FIM DO JOIN COM SELECT 'RETENCOES' */


/* JOIN USANDO SELECT PARA TRAZER DESCONTOS FEITOS NA PROPRIA MEDICÃO OU RETENÇÃO NO CAMPO FLAN.VALORDESCONTO */
LEFT JOIN (
			SELECT 
			SUM(RETENCOES.DESCONTO) AS DESCONTO,
			RETENCOES.CODCOLIGADA,
			RETENCOES.CODCCUSTO,
			RETENCOES.CODCFO
			FROM (
					SELECT
					FCFO.CODCFO,
					SUM (FLAN.VALORDESCONTO) AS DESCONTO, 
					FLAN.CODCCUSTO,
					FCFO.CODCOLIGADA
					
					FROM FLAN (NOLOCK)
					
					INNER JOIN FCFO (NOLOCK) ON (FCFO.CODCFO = FLAN.CODCFO AND FCFO.CODCOLIGADA = FLAN.CODCOLCFO)
					
					WHERE	FLAN.CODTDO <> '0025'
					AND		FLAN.STATUSLAN <> 2
					AND		FLAN.CODCOLIGADA = @CODCOLIGADA
					AND		FLAN.CODCOLIGADA <> 0
					/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (FCFO.CODCFO = @EMPREITEIRO)
					
					/* AND 	FLAN.CODTB2FLX IN ('129','062') RETIRADO A PEDIDO DE CADU E MICHELLE */
					
					GROUP BY
					FLAN.CODCCUSTO,
					FCFO.CODCOLIGADA,
					FCFO.CODCFO
					
					UNION ALL
					
					SELECT 
					
					GRUPO.CODCFO,
					SUM (VALOR_CONTACAIXA4) AS VLR_RETENCOES_CONTACAIXA4,
					GRUPO.CODCCUSTO,
					GRUPO.CODCOLIGADA
					
					 FROM 
					
					(
						SELECT
						
						FCFO.CODCFO,
						SUM(FLAN.VALORBAIXADO)AS VALOR_CONTACAIXA4,
						FLAN.CODCCUSTO,
						FCFO.CODCOLIGADA
						
						FROM TMOV (NOLOCK)
						
						INNER JOIN GCCUSTO		(NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA =TMOV.CODCOLIGADA)
						INNER JOIN FLAN			(NOLOCK) ON (TMOV.CODCOLIGADA = FLAN.CODCOLIGADA AND TMOV.IDMOV = FLAN.IDMOV)
						INNER JOIN FLANBAIXA	(NOLOCK) ON (FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.IDLAN = FLAN.IDLAN)
						INNER JOIN FCFO			(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
						INNER JOIN FTB2			(NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
						
						WHERE 
						/*AND TMOV.CODTMV IN ('1.2.07', '1.2.08','1.2.14','1.2.13')*/
						FLAN.CODTB2FLX IN ('129','02.023')
						AND FLANBAIXA.CODCXA IN ('4','8')
						AND FLAN.PAGREC = 2
						AND	FLAN.CODCOLIGADA = @CODCOLIGADA
						AND FLAN.CODCOLIGADA <> 0
						/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (FCFO.CODCFO = @EMPREITEIRO)
						
						GROUP BY 
						
						FCFO.CODCFO,
						FLAN.CODCCUSTO,
						FCFO.CODCOLIGADA
					) AS GRUPO
					
					GROUP BY 
					GRUPO.CODCFO,
					GRUPO.CODCOLIGADA,
					GRUPO.CODCCUSTO
			) AS RETENCOES
			GROUP BY RETENCOES.CODCFO,RETENCOES.CODCCUSTO,RETENCOES.CODCOLIGADA
) AS RETENCOES_CONTACAIXA4 ON (RETENCOES_CONTACAIXA4.CODCFO = EMPREITEIROS.CODCFO AND RETENCOES_CONTACAIXA4.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND RETENCOES_CONTACAIXA4.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)
/* FIM DO JOIN COM DESCONTO */


/* JOIN USANDO SELECT PARA TRAZER ADIANTAMENTOS NAO VINCULADOS */
LEFT JOIN (
			SELECT
			GRUPO1.CODCFO,
			GRUPO1.FORNECEDOR,
			GRUPO1.CODCCUSTO,
			GRUPO1.CODCOLIGADA,
			SUM (GRUPO1.NAOVINCULADOS) AS VLR_NAOVINCULADOS
			
			FROM 
			
			/* ADIANTAMENTOS MODELO NOVO VERSAO 11.82 */
			
			(
				SELECT
				FLAN.CODCFO,
				FCFO.CODCOLIGADA,
				FCFO.NOMEFANTASIA AS FORNECEDOR,
				FLAN.CODCCUSTO,
				FLAN.VALORORIGINAL - ISNULL(SUM (FRELLAN.VALORVINCULO),0) AS NAOVINCULADOS,
				0 AS NAOVINCULADOSCONTACAIXA4
				
				FROM FLAN (NOLOCK)
				
				LEFT JOIN FRELLAN	(NOLOCK) ON (FLAN.IDLAN = FRELLAN.IDLANREL AND FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA AND FRELLAN.TIPOREL = 28)
				LEFT JOIN FCFO		(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
				
				WHERE FLAN.CODTDO = '0044' 
				AND FLAN.CODTB2FLX IN ('124','171','172','02.125','02.158','02.157')
				AND FLAN.STATUSLAN IN (0,3,4)
				AND FLAN.CODCOLIGADA = @CODCOLIGADA
				AND FLAN.CODCOLIGADA <> 0
				/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (FCFO.CODCFO = @EMPREITEIRO)
				
				GROUP BY
				
				FLAN.IDLAN,
				FLAN.CODTDO,
				FLAN.CODCFO,
				FCFO.NOMEFANTASIA,
				FCFO.NOME,
				FCFO.CGCCFO,
				FCFO.CODCOLIGADA,
				FLAN.CODCOLIGADA,
				FLAN.CODCCUSTO,
				FLAN.NUMERODOCUMENTO,
				FLAN.DATAEMISSAO,
				FLAN.VALORORIGINAL
				HAVING FLAN.VALORORIGINAL - ISNULL(SUM (FRELLAN.VALORVINCULO),0) > 0
				
			) AS GRUPO1
			
			GROUP BY
			
			GRUPO1.CODCFO,
			GRUPO1.FORNECEDOR,
			GRUPO1.CODCOLIGADA,
			GRUPO1.CODCCUSTO
) AS NAOVINCULADOS ON (NAOVINCULADOS.CODCFO = EMPREITEIROS.CODCFO AND NAOVINCULADOS.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND NAOVINCULADOS.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)
/* FIM DO JOIN COM SELECT 'NAOVINCULADOS */


LEFT JOIN (
			SELECT 
			GRUPO2.CODCFO,
			GRUPO2.FORNECEDOR,
			GRUPO2.CODCCUSTO,
			GRUPO2.CODCOLIGADA,
			SUM (GRUPO2.ADIANTAMENTO_CX4) AS VLR_ADIANTAMENTO_CX4
			FROM (
					SELECT
					
					FLAN.CODCFO,
					FLAN.CODCOLIGADA,
					FCFO.NOMEFANTASIA AS FORNECEDOR,
					FLAN.CODCCUSTO,
					ISNULL(FLAN.VALORBAIXADO,0) AS ADIANTAMENTO_CX4
					
					FROM FLAN (NOLOCK)
					
					/*LEFT JOIN FRELLAN					(NOLOCK) ON (FLAN.IDLAN = FRELLAN.IDLANREL AND FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA)*/
					LEFT JOIN FTB4						(NOLOCK) ON (FLAN.CODTB4FLX = FTB4.CODTB4FLX AND FLAN.CODCOLIGADA = FTB4.CODCOLIGADA)
					LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
					/*LEFT JOIN FLAN DESCONTO (NOLOCK) ON (DESCONTO.IDLAN = FRELLAN.IDLAN AND DESCONTO.CODCOLIGADA = FRELLAN.CODCOLIGADA)
					LEFT JOIN FTB2						(NOLOCK) ON (FTB2.CODTB2FLX = DESCONTO.CODTB2FLX AND FTB2.CODCOLIGADA = DESCONTO.CODCOLIGADA)*/
					
					WHERE
					FLAN.CODTDO IN ('0044')
					AND FLAN.PAGREC = 1
					AND FLAN.CODCOLIGADA = @CODCOLIGADA
					AND FLAN.CODCOLIGADA <> 0
					AND  (SELECT TOP 1 FLANBAIXA.CODCXA FROM FLANBAIXA (NOLOCK) WHERE FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.CODCXA IN ('4','8') ) IN ('4','8')
					AND FLAN.CODTB2FLX IN ('02.009','02.125')
					/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (FCFO.CODCFO = @EMPREITEIRO )
			) AS GRUPO2
			
			GROUP BY
			
			GRUPO2.CODCFO,
			GRUPO2.FORNECEDOR,
			GRUPO2.CODCOLIGADA,
			GRUPO2.CODCCUSTO
) AS ADIANTAMENTO_CX4 ON (ADIANTAMENTO_CX4.CODCFO = EMPREITEIROS.CODCFO AND ADIANTAMENTO_CX4.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND ADIANTAMENTO_CX4.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)

/***************************************************************************************************//****************************************************************************/

/*JOIN PARA TRAZER RETENÇÕES BAIXADAS COM CONTA CAIXA 4*/
/*LEFT JOIN 


(SELECT 

GRUPO.CODCFO,
GRUPO.NOMEFANTASIA,
GRUPO.CODCOLIGADA,
GRUPO.CODCCUSTO,
GRUPO.DESCRICAO,
SUM (VALOR_CONTACAIXA4) AS VLR_RETENCOES_CONTACAIXA4


 FROM 

(
SELECT

FCFO.CODCFO,
FCFO.NOMEFANTASIA,
FCFO.CODCOLIGADA,
FLAN.CODCCUSTO,	
GCCUSTO.CODCCUSTO +' - '+ GCCUSTO.NOME AS OBRA, 
FTB2.DESCRICAO,
SUM(FLAN.VALORBAIXADO)AS VALOR_CONTACAIXA4


FROM TMOV (NOLOCK)

INNER JOIN GCCUSTO (NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA =TMOV.CODCOLIGADA)
INNER JOIN FLAN	   (NOLOCK) ON (TMOV.CODCOLIGADA = FLAN.CODCOLIGADA AND TMOV.IDMOV = FLAN.IDMOV)
INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.IDLAN = FLAN.IDLAN)
INNER JOIN FCFO    (NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
INNER JOIN FTB2    (NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)

WHERE TMOV.CODCOLIGADA = @CODCOLIGADA
--AND TMOV.CODTMV IN ('1.2.07', '1.2.08','1.2.14','1.2.13')
AND FLAN.CODTB2FLX IN ('129','02.023')
AND FLANBAIXA.CODCXA = '4'
AND FLAN.PAGREC = 2


GROUP BY 

FCFO.CODCFO,
FCFO.NOMEFANTASIA,
FLAN.CODCCUSTO,
FCFO.CODCOLIGADA,
GCCUSTO.CODCCUSTO,
FTB2.DESCRICAO,
GCCUSTO.NOME
) AS GRUPO

GROUP BY 
GRUPO.CODCFO,
GRUPO.NOMEFANTASIA,
GRUPO.DESCRICAO,
GRUPO.CODCOLIGADA,
GRUPO.CODCCUSTO
) AS RETENCOES_CONTACAIXA4 ON (RETENCOES_CONTACAIXA4.CODCFO = EMPREITEIROS.CODCFO AND RETENCOES_CONTACAIXA4.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND RETENCOES_CONTACAIXA4.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)
*/


/***************************************************************************************************//****************************************************************************/


/* JOIN USANDO SELECT PARA TRAZER SALDO DE ADIANTAMENTOS DO CONTROLEMP */
LEFT JOIN(
			SELECT 
			DBCONTROLEMP.DBO.EMPREITEIRO.RM_CODCFO AS RM_CODCFO,
			DBCONTROLEMP.DBO.EMPREITEIRO.RM_CODCOLIGADA,
			DBCONTROLEMP.DBO.OBRA.RM_CODCOLIGADA AS COLIGADA_OBRA,
			DBCONTROLEMP.DBO.EMPREITEIRO.NOM_FANTASIA,
			DBCONTROLEMP.DBO.OBRA.RM_CODCCUSTO AS RM_CODCCUSTO,
			
			SUM(DBCONTROLEMP.DBO.MEDICAO_ITEM_EMPREENDIMENTO.VLR_MEDIDO) AS VLR_SALDOCONTROLEMP
			
			FROM DBCONTROLEMP.DBO.MEDICAO (NOLOCK)
			
			INNER JOIN DBCONTROLEMP.DBO.MEDICAO_ITEM_EMPREENDIMENTO	(NOLOCK) ON (DBCONTROLEMP.DBO.MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO = DBCONTROLEMP.DBO.MEDICAO.ID_MEDICAO)
			INNER JOIN DBCONTROLEMP.DBO.ITEM_EMPREENDIMENTO			(NOLOCK) ON (DBCONTROLEMP.DBO.MEDICAO_ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = DBCONTROLEMP.DBO.ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)
			INNER JOIN DBCONTROLEMP.DBO.CONTRATO					(NOLOCK) ON (DBCONTROLEMP.DBO.CONTRATO.ID_CONTRATO = DBCONTROLEMP.DBO.MEDICAO.ID_CONTRATO)
			INNER JOIN DBCONTROLEMP.DBO.OBRA						(NOLOCK) ON (DBCONTROLEMP.DBO.OBRA.ID_OBRA = DBCONTROLEMP.DBO.CONTRATO.ID_OBRA)
			INNER JOIN DBCONTROLEMP.DBO.EMPREITEIRO					(NOLOCK) ON (DBCONTROLEMP.DBO.EMPREITEIRO.ID_EMPREITEIRO = DBCONTROLEMP.DBO.CONTRATO.ID_EMPREITEIRO)
			
			WHERE	DBCONTROLEMP.DBO.ITEM_EMPREENDIMENTO.ID_GRUPO_ITEM = 67
			AND		DBCONTROLEMP.DBO.MEDICAO.EXCLUIDO <> 1
			AND		DBCONTROLEMP.DBO.MEDICAO.ID_ETAPA = 4
			/*ADICIONADO CODCFO PARA MELHORAR PERFORMACE DA CONSULTA*/AND (EMPREITEIRO.RM_CODCFO LIKE @EMPREITEIRO)
			GROUP BY
			
			DBCONTROLEMP.DBO.EMPREITEIRO.RM_CODCFO,
			DBCONTROLEMP.DBO.EMPREITEIRO.NOM_FANTASIA,
			DBCONTROLEMP.DBO.EMPREITEIRO.RM_CODCOLIGADA,
			DBCONTROLEMP.DBO.OBRA.RM_CODCCUSTO,
			DBCONTROLEMP.DBO.OBRA.RM_CODCOLIGADA
) AS SALDOCONTROLEMP ON (SALDOCONTROLEMP.COLIGADA_OBRA = @CODCOLIGADA AND SALDOCONTROLEMP.RM_CODCFO = EMPREITEIROS.CODCFO AND SALDOCONTROLEMP.RM_CODCCUSTO = EMPREITEIROS.CODCCUSTO AND SALDOCONTROLEMP.RM_CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)
/* FIM DO JOIN COM SELECT 'SLADOCONTROLEMP' */

/* JOIN USANDO SELECT PARA TRAZER ADIANTAMENTOS PLANEJ. E CONTROLE MOV. 1.1.68 */
LEFT JOIN (
			SELECT 
			FCFO.CODCFO,
			FCFO.CODCOLIGADA,
			FCFO.NOMEFANTASIA,
			TMOV.CODCCUSTO, 
			SUM (TMOV.VALORLIQUIDO) AS VALORORIGINAL
			
			FROM TMOV (NOLOCK)
			
			INNER JOIN FCFO (NOLOCK) ON (TMOV.CODCFO = FCFO.CODCFO AND TMOV.CODCOLCFO = FCFO.CODCOLIGADA)
			
			WHERE CODTMV = '1.1.68'
			AND TMOV.CODCOLIGADA = @CODCOLIGADA 
			AND TMOV.CODCOLIGADA <> 0/*ADICIONADO PARA CORRIGIR ERRO DE DUPLICIDADE NOS VALORES - MICHELLE PIRES E ANNA CLARA*/
			/*AND TMOV.CODCFO = @EM_PREITEIRO*/
			AND FCFO.CODCFO = @EMPREITEIRO

			GROUP BY 
			FCFO.CODCFO,
			FCFO.CODCOLIGADA,
			FCFO.NOMEFANTASIA,
			TMOV.CODCCUSTO
) AS ADIANT_PLAN_CONT ON (ADIANT_PLAN_CONT.CODCFO = EMPREITEIROS.CODCFO AND ADIANT_PLAN_CONT.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND ADIANT_PLAN_CONT.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)
/* FIM DO JOIN COM SELECT 'ADIANT_PLAN_CONT' */

/* JOIN USANDO SELECT PARA TRAZER ADIANTAMENTOS DIVERSOS OBRA MOV. 1.1.63 */
LEFT JOIN (
			SELECT 
			FCFO.CODCFO,
			FCFO.CODCOLIGADA,
			FCFO.NOMEFANTASIA,
			TMOV.CODCCUSTO, 
			SUM (TMOV.VALORBRUTOORIG) AS VALORORIGINAL
			
			FROM TMOV (NOLOCK)
			
			INNER JOIN FCFO (NOLOCK) ON (TMOV.CODCFO = FCFO.CODCFO AND TMOV.CODCOLCFO = FCFO.CODCOLIGADA)
			
			WHERE CODTMV = '1.1.63'
			AND TMOV.CODCOLIGADA = @CODCOLIGADA 
			AND TMOV.CODCOLIGADA <> 0 /*ADICIONADO PARA CORRIGIR ERRO DE DUPLICIDADE NOS VALORES - MICHELLE PIRES E ANNA CLARA*/
			/*AND TMOV.CODCFO = @EM_PREITEIRO*/
			AND (FCFO.CODCFO = @EMPREITEIRO)
			GROUP BY 
			FCFO.CODCFO,
			FCFO.CODCOLIGADA,
			FCFO.NOMEFANTASIA,
			TMOV.CODCCUSTO
) AS ADIANT_DIVER_OBRA ON (ADIANT_DIVER_OBRA.CODCFO = EMPREITEIROS.CODCFO AND ADIANT_DIVER_OBRA.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND ADIANT_DIVER_OBRA.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)

/* FIM DO JOIN COM SELECT 'ADIANT_DIVER_OBRA' */
) AS GRUPO

GROUP BY 
GRUPO.CODCFO, 
GRUPO.NOMEFANTASIA, 
GRUPO.NOME,
GRUPO.CGCCFO,
GRUPO.DATACRIACAO,
GRUPO.CODCCUSTO,
GRUPO.COLIGADA