SELECT 
TMOV.CODCOLIGADA, 
TMOV.CODFILIAL,
GFILIAL.NOME,
TMOV.CODTMV AS 'MOVIMENTO', 
TMOV.IDMOV AS 'REFERENCIA', 
TMOV.CODLOC AS 'LOCAL DE ESTOQUE',
TMOV.NUMEROMOV AS 'NUMERO NOTA',
TMOV.SERIE,
TMOV.DATAEMISSAO,
FCFO.CODCFO,
FCFO.NOME,
TMOV.STATUS,
TMOV.VALORBRUTO,
TMOV.VALORLIQUIDO,
flan.idlan as 'REF LAN',
FLAN.DATABAIXA
/*,FLANBAIXA.DATABAIXA*/

FROM TMOV (NOLOCK)
INNER JOIN GFILIAL		(NOLOCK) ON TMOV.CODCOLIGADA = GFILIAL.CODCOLIGADA AND TMOV.CODFILIAL = GFILIAL.CODFILIAL
INNER JOIN FCFO			(NOLOCK) ON TMOV.CODCFO = FCFO.CODCFO
LEFT JOIN FLAN			(NOLOCK) ON TMOV.CODCOLIGADA = FLAN.CODCOLIGADA AND TMOV.IDMOV = FLAN.IDMOV
LEFT JOIN FLANBAIXA	(NOLOCK) ON FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN

WHERE TMOV.CODTMV = '1.1.66'
and TMOV.CODCOLIGADA IN (1)
ORDER BY 1, 2

