
SELECT  COLIGADA, CODCCUSTO, ZMDUSUARIO.CODUSUARIO, NOME, ATIVO 
FROM ZMDCENTRODECUSTO
JOIN ZMDUSUARIO ON ZMDUSUARIO.CODUSUARIO = ZMDCENTRODECUSTO.CODUSUARIO
WHERE COLIGADA = 32 
AND CODCCUSTO = '3.0001.06'

SELECT NOME, STATUS, CODCOLIGADA, CODCCUSTO
FROM GUSUARIO
JOIN TUSUARIOCCUSTO ON TUSUARIOCCUSTO.CODUSUARIO =  GUSUARIO.CODUSUARIO
WHERE CODCOLIGADA = 32 AND CODCCUSTO = '3.0001.06'