 SELECT
 CLOTE.CODCOLIGADA AS 'COLIGADA - CLOTE', 
 CLOTE.INTEGRAAPLICACAO AS 'SISTEMA - ORIGEM', 
 CLOTE.CODLOTE AS 'LOTE - CLOTE', 
 CLOTE.DESCRICAO AS 'DESC LOTE - CLOTE',
 CPARTIDA.CODFILIAL AS 'FILIAL - GFILIAL', 
 CLANCAMENTO.IDLANCAMENTO AS 'IDLAN - CLANCAMENTO', 
 CLANCAMENTO.DESCRICAO AS 'DESC - CLAN / TMOV 2 - CLANCAMENTO',
 CPARTIDA.DOCUMENTO AS 'DOC - CPARTIDA',
 CPARTIDA.DATA AS 'DATA - CPARTIDA',
 CPARTIDA.DEBITO AS 'CONTADEBITO',
	 (SELECT CCONTA.DESCRICAO
	  FROM CCONTA
	  WHERE CPARTIDA.CODCOLDEBITO = CCONTA.CODCOLIGADA 
	  AND CPARTIDA.DEBITO = CCONTA.CODCONTA) AS 'DESC - DEBITO',
 CPARTIDA.CREDITO AS 'CONTACREDITO',
	 (SELECT CCONTA.DESCRICAO
	 FROM CCONTA
	 WHERE CPARTIDA.CODCOLCREDITO = CCONTA.CODCOLIGADA 
	 AND CPARTIDA.CREDITO = CCONTA.CODCONTA) AS 'DESC - CREDITO',
 CPARTIDA.VALOR AS 'CPARTIDA - VALOR',
 CPARTIDA.COMPLEMENTO AS 'CPARTIDA - COMPLEMENTO',
 CPARTIDA.CODCCUSTO AS 'FLAN - CCCUSTO',
 GCCUSTO.NOME AS 'NOME CCUSTO',
 CPARTIDA.DATAINCLU AS 'DATA INCLUSAO - CPARTIDA',
 CPARTIDA.USUARIO AS 'USUARIO - CPARTIDA',
 CPARTIDA.DATAINTEGRACAO AS 'DATA INTEGRAÇÃO - CPARTIDA',
 CPARTIDA.USUARIOINTEGRACAO AS 'USUARIO INTEGRAÇÃO - CPARTIDA',
 CPARTIDA.USUARIOALTER AS 'USUARIO ALTERAÇÃO - CPARTIDA',
 CPARTIDA.DATAALTER AS 'DATA ALTERAÇÃO - CPARTIDA',
 CPARTIDA.DATALIBERACAO AS 'DATA LIBERAÇÃO - CPARTIDA',
 CPARTIDA.INTEGRACHAVE AS 'CHAVE INTEGRAÇÃO - CPARTIDA',
 (CASE WHEN ORIGINADONOVOMOD = 1 THEN 'SIM' ELSE 'NÃO' END) AS 'Partida originada no novo modelo de BackOffice',
 GFILIAL.NOMEFANTASIA AS 'NOME FILIAL - GFILIAL',
 '??' AS 'DESCRIÇÃO HISTORICO',
 '??' AS 'HISTORICO PADRAO'



 FROM CLOTE							(NOLOCK)
 INNER JOIN CLANCAMENTO				(NOLOCK) ON CLANCAMENTO.CODCOLIGADA = CLOTE.CODCOLIGADA  AND CLANCAMENTO.CODLOTE = CLOTE.CODLOTE
 INNER JOIN CPARTIDA				(NOLOCK) ON CPARTIDA.CODCOLIGADA = CLANCAMENTO.CODCOLIGADA AND CLANCAMENTO.IDLANCAMENTO = CPARTIDA.IDLANCAMENTO
 INNER JOIN GCCUSTO					(NOLOCK) ON GCCUSTO.CODCOLIGADA = CPARTIDA.CODCOLIGADA AND GCCUSTO.CODCCUSTO = CPARTIDA.CODCCUSTO
 INNER JOIN GFILIAL					(NOLOCK) ON GFILIAL.CODCOLIGADA = CPARTIDA.CODCOLIGADA AND GFILIAL.CODFILIAL = CPARTIDA.CODFILIAL


 WHERE CLOTE.CODCOLIGADA IN (@CODCOLIGADA)
 AND CLOTE.CODLOTE IN (@LOTE)
 AND CPARTIDA.DATA BETWEEN @DATA_INI AND @DATA_FIM

 ORDER BY 1, 3


 /* ATÉ OBRA */
SELECT TOP 1 CODTRF, 
CODTRF + ' - ' + MTAREFA.NOME AS NOMETAREFA

FROM MTAREFA (NOLOCK)
INNER JOIN MPRJ ON MPRJ.CODCOLIGADA = MTAREFA.CODCOLIGADA AND MPRJ.IDPRJ = MTAREFA.IDPRJ

/*
WHERE MTAREFA.CODCOLIGADA=39
AND CODPRJ = 'SP.2024.001'
AND CODTRF <=LEFT('011' ,3)
AND REVISAO = '2'
*/

WHERE MTAREFA.CODCOLIGADA=@codcoligada
AND CODPRJ= @codprj 
AND CODTRF <=LEFT(@codtrfFIM ,3)
AND REVISAO = @revisao

ORDER BY 1  DESC

SELECT * 
FROM MTAREFA 
WHERE CODCOLIGADA = 39 
AND CODTRF <=LEFT('011' ,3)