DECLARE @CODCOLIGADA AS INT = 1,
		@IDMOV AS INT = '2224554';
		/*idmov = 2224185 */
SELECT 
NF.CODCOLIGADA,
NF.IDMOV,
NF.DATAEMISSAO AS 'NF_DATAEMISSAO',
ODC.DATAEMISSAO AS 'OD_DATAEMISSAO',
TMOVCOMPL.REGULARIZACAO

FROM TMOV NF (NOLOCK)
INNER JOIN TMOVRELAC      (NOLOCK) ON NF.IDMOV = TMOVRELAC.IDMOVDESTINO AND NF.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO
INNER JOIN TMOV ODC		  (NOLOCK) ON ODC.IDMOV = TMOVRELAC.IDMOVORIGEM AND ODC.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM
INNER JOIN TMOVCOMPL      (NOLOCK) ON NF.IDMOV = TMOVCOMPL.IDMOV AND NF.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA

WHERE NF.IDMOV IN(@IDMOV) 
AND NF.CODCOLIGADA = @CODCOLIGADA
AND NF.CODTMV IN ('1.1.40', '1.1.41')

GROUP BY  
NF.CODCOLIGADA,
NF.IDMOV,
NF.DATAEMISSAO,
ODC.DATAEMISSAO,
TMOVCOMPL.REGULARIZACAO

/*
SELECT TOP 100 * 
FROM TMOV 
WHERE CODTMV = '1.1.41'
ORDER BY RECCREATEDON DESC
*/