SELECT DISTINCT TPRDGRUPOPRODUTO.CODGRUPO, (TGRUPOPRODUTO.CODGRUPO + ' - ' + TGRUPOPRODUTO.DESCRICAO) AS NOME_GRUPOS
FROM TPRD (NOLOCK)
INNER JOIN TPRDGRUPOPRODUTO (NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = TPRD.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = TPRD.CODCOLIGADA)
INNER JOIN TGRUPOPRODUTO	(NOLOCK) ON (TGRUPOPRODUTO.CODCOLIGADA = TPRDGRUPOPRODUTO.CODCOLPRD AND TGRUPOPRODUTO.CODGRUPO = TPRDGRUPOPRODUTO.CODGRUPO)

WHERE TPRD.INATIVO = 0
ORDER BY 1

select * from TGRUPOPRODUTO

/*
COMPRA1160
COMRRA1.1.60
TABELA CRIADA PARA SUBSTITUIR A FORMULA DO 1.1.60
*/

SELECT
/* SERVIÇO E PRODUTO */
(CASE WHEN TPRDGRUPOPRODUTO.CODGRUPO IN 
('DPTX','ESCR','CBAL','EQUI','INFO','EPIC','EIND','COMB','PLAC','MVUT','CERC','SERR','MACO','RESR','CACC','MELE','MPIN','INCE','EQUC','ESQU','ELEV','PREM','VEIC','FRMT','PSGM','FERR') THEN 1 ELSE 0 END) AS VALIDA,
/* SERVIÇO */
(CASE WHEN TPRDGRUPOPRODUTO.CODGRUPO IN
('EQUI','EMBA','ESCR','EIND','DPTX','INFO','EPVT','SERR','MEDC','FERR','MELE','MACO','CERC','AGRE','CACC','COBT','COMB','EQUC','INCE','ESQU','MHID','ELEV','SHAF','FRMT','LOUC',/*'MADE' grupo não encontrado,*/'PLAC','REVP','RESR','GESS','EPIC','PSGM','ASFT') AND TPRD.TIPO = 'S' THEN 1 ELSE 0 END) AS VALIDA2

FROM TPRD (NOLOCK)
LEFT JOIN TPRDGRUPOPRODUTO (NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = TPRD.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = TPRD.CODCOLIGADA)
WHERE TPRD.CODCOLIGADA =:FRM_COLIGITM
AND TPRD.IDPRD =:FRM_IDPRD

SELECT 
(CASE	
		WHEN ZMDCOMPRA1160.COMPRA1160 = 0 THEN 0
		WHEN ZMDCOMPRA1160.COMPRA1160 = 1 AND TPRD.TIPO = 'P' AND ZMDCOMPRA1160.PRODUTOESERVICO = 0 THEN 0 
		WHEN ZMDCOMPRA1160.COMPRA1160 = 1 AND TPRD.TIPO = 'P' AND ZMDCOMPRA1160.PRODUTOESERVICO = 1 THEN 1
		WHEN ZMDCOMPRA1160.COMPRA1160 = 1 AND TPRD.TIPO = 'S' AND ZMDCOMPRA1160.PRODUTOESERVICO = 1 THEN 1
	 ELSE 0 END) AS VALIDA

FROM TPRD (NOLOCK)
LEFT JOIN TPRDGRUPOPRODUTO	(NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = TPRD.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = TPRD.CODCOLIGADA)
LEFT JOIN ZMDCOMPRA1160		(NOLOCK) ON (TPRDGRUPOPRODUTO.CODGRUPO = ZMDCOMPRA1160.CODGRUPO AND TPRDGRUPOPRODUTO.CODCOLPRD = ZMDCOMPRA1160.CODCOLGRUPO)


WHERE TPRD.CODCOLIGADA =:FRM_COLIGITM
AND TPRD.IDPRD =:FRM_IDPRD
