 /* 
SELECT DISTINCT TGRUPOPRODUTO.CODGRUPO, (TGRUPOPRODUTO.CODGRUPO + ' - ' + TGRUPOPRODUTO.DESCRICAO) AS 'GRUPO_PROD',

FROM TPRD

INNER JOIN TPRDGRUPOPRODUTO						(NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = TPRD.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = TPRD.CODCOLIGADA)
INNER JOIN TGRUPOPRODUTO						(NOLOCK) ON (TGRUPOPRODUTO.CODCOLIGADA = TPRDGRUPOPRODUTO.CODCOLPRD AND TGRUPOPRODUTO.CODGRUPO = TPRDGRUPOPRODUTO.CODGRUPO)

WHERE CODCOLIGADA IN (@CODCOLIGADA)

ORDER BY 1

*/