SELECT 

TPRD.CODIGOPRD AS QUEBRA$,
TITMMOV.CODUND,
TMOV.CODCCUSTO,
TMOV.NUMEROMOV, 
TMOV.DATACRIACAO,
TITMMOV.QUANTIDADETOTAL,
TITMMOV.PRECOUNITARIO,
TITMMOV.VALORTOTALITEM,
FCFO.CODCFO +'-'+FCFO.NOME AS NOME,
TMOV.USUARIOCRIACAO,
(CASE WHEN TMOVAPROVA.IDMOV IS NULL THEN 'N' ELSE 'S' END ) AS APROVADO,


/* PRECO MEDIO */

CAST (((TITMMOV.PRECOUNITARIO + 
	(
		ISNULL(TITMMOV.VALORFRETECTRC,0)/ 
		NULLIF((CASE WHEN TITMMOV.QUANTIDADE = '0' 
		THEN TITMMOV.QUANTIDADETOTAL 
		ELSE TITMMOV.QUANTIDADE END),0) 
	) -
	(
		ISNULL(TITMMOV.VALORDESC,0)/
		NULLIF(
			(
				CASE WHEN TITMMOV.QUANTIDADE = '0' 
				THEN TITMMOV.QUANTIDADETOTAL 
				ELSE TITMMOV.QUANTIDADE END),0) 
	) +
		(
			isnull(
				(
					select sum(VALOR) 
					from TTRBMOV 
					where CODCOLIGADA = TITMMOV.CODCOLIGADA 
					and IDMOV = TITMMOV.IDMOV 
					and NSEQITMMOV = TITMMOV.NSEQITMMOV 
					and CODTRB = 'IPI')
				,0)/
				NULLIF(
					(
						CASE WHEN TITMMOV.QUANTIDADE = '0' 
						THEN TITMMOV.QUANTIDADETOTAL 
						ELSE TITMMOV.QUANTIDADE END)
					,0) 
				)
			) +
			CASE WHEN 
				ISNULL
					(
						(
							CASE WHEN TITMMOV.QUANTIDADE = '0' 
							THEN TITMMOV.QUANTIDADETOTAL 
							ELSE TITMMOV.QUANTIDADE END)
					,0) < 1
						THEN 
						(
							(
								ISNULL(TMOV.VALORFRETE,0)-
								ISNULL(TMOV.VALORDESC,0)+
								ISNULL(TMOV.VALOREXTRA1,0)
							) * 
								(
									(TITMMOV.PRECOUNITARIO * 
										NULLIF
											(
												(
													CASE WHEN TITMMOV.QUANTIDADE = '0' 
													THEN TITMMOV.QUANTIDADETOTAL 
													ELSE TITMMOV.QUANTIDADE END)
											,0) 
									) / 
										NULLIF
											(
												(
													CASE WHEN TMOV.VALORBRUTO = '0' 
													THEN TMOV.VALORBRUTOORIG 
													ELSE TMOV.VALORBRUTO END)
												,0) 
									)
						) 
							ELSE
								(
									(
										ISNULL(TMOV.VALORFRETE,0)-
										ISNULL(TMOV.VALORDESC,0)+
										ISNULL(TMOV.VALOREXTRA1,0)
									) * (
										(
											TITMMOV.PRECOUNITARIO * 
												NULLIF
													(
														(
															CASE WHEN TITMMOV.QUANTIDADE = '0' 
															THEN TITMMOV.QUANTIDADETOTAL 
															ELSE TITMMOV.QUANTIDADE END)
														,0)
										) / 
											NULLIF
												(
													(
														CASE WHEN TMOV.VALORBRUTO = '0' 
														THEN TMOV.VALORBRUTOORIG 
														ELSE TMOV.VALORBRUTO END)
												,0) 
													)
														)/ 
															NULLIF
																(
																	(
																		CASE WHEN TITMMOV.QUANTIDADE = '0' 
																		THEN TITMMOV.QUANTIDADETOTAL 
																		ELSE TITMMOV.QUANTIDADE END)
																,0)  
			END) * NULLIF
				(
					(
						CASE WHEN TITMMOV.QUANTIDADE = '0' 
						THEN TITMMOV.QUANTIDADETOTAL 
						ELSE TITMMOV.QUANTIDADE END)
					,0)  /
						(
							CASE WHEN TITMMOV.CODUND = TPRD.CODUNDCONTROLE
							THEN 
								NULLIF
									(
										(
											CASE WHEN TITMMOV.QUANTIDADE = '0' 
											THEN TITMMOV.QUANTIDADETOTAL 
												ELSE TITMMOV.QUANTIDADE END)
										,0)
											ELSE 
												(NULLIF
													(
														(
															CASE WHEN TITMMOV.QUANTIDADE = '0' 
															THEN TITMMOV.QUANTIDADETOTAL 
															ELSE TITMMOV.QUANTIDADE END)
													,0)  * (
														SELECT FATORCONVERSAO 
														FROM TUND 
														WHERE TUND.CODUND = TITMMOV.CODUND
														GROUP BY FATORCONVERSAO
														)
												) / (
													SELECT FATORCONVERSAO 
													FROM TUND 
													WHERE TUND.CODUND = TITMMOV.CODUND
													) END) AS DECIMAL (10,2)
		) AS PRC_MEDIO,
TMOV.DATAEMISSAO,
TITMMOV.CODUND,
	(
		CASE WHEN TMOV.STATUS = 'A' 
		THEN 'Pendente' 
		ELSE 'Recebido' END) AS STATUS,
			(
				SELECT TOP 1 ODC.CODTMV 
				FROM TMOVRELAC
				
LEFT JOIN TMOV AS ODC	(NOLOCK) ON (TMOVRELAC.IDMOVORIGEM = ODC.IDMOV AND TMOVRELAC.CODCOLORIGEM = ODC.CODCOLIGADA)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA) AS ODC_CODTMV

FROM TITMMOV (NOLOCK)

INNER JOIN	TMOV		(NOLOCK) ON (TITMMOV.IDMOV = TMOV.IDMOV AND TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA)
INNER JOIN	FCFO		(NOLOCK) ON (TMOV.CODCFO = FCFO.CODCFO AND TMOV.CODCOLCFO = FCFO.CODCOLIGADA)
INNER JOIN	TPRD		(NOLOCK) ON (TPRD.IDPRD = TITMMOV.IDPRD AND TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA)  
INNER JOIN	GCCUSTO		(NOLOCK) ON (TMOV.CODCCUSTO = GCCUSTO.CODCCUSTO AND TMOV.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT  JOIN	TMOVAPROVA	(NOLOCK) ON (TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA AND TMOVAPROVA.TIPOAPROVACAO = 1)


WHERE TMOV.CODTMV IN ('1.1.41','1.1.40')
AND     TMOV.CODCOLIGADA = :ESPELHO#4
AND     TMOV.STATUS <> 'C'
AND     TMOV.DATACRIACAO BETWEEN :DATACRIACAO_INI_D AND :DATACRIACAO_FIN_D
AND     TMOV.IDMOV NOT IN (SELECT IDMOV FROM TMOTIVOCONCLPED)
AND     TMOV.CODLOC BETWEEN :LESTOQUE_INI_S AND :LESTOQUE_FIN_S
AND     TPRD.CODIGOPRD = :ESPELHO#2_S

order by QUEBRA$, TMOV.DATACRIACAO, TMOV.CODCCUSTO, TMOV.NUMEROMOV