SELECT DISTINCT
GRUPO.CODIGOPRD,
GRUPO.NOMEFANTASIA,
GRUPO.CODUNDCONTROLE,
/*Entradas*/
SUM (CASE WHEN CODTMV IN ('1.1.40','1.1.41') THEN ENTRADA ELSE 0 END) AS NF,
SUM (CASE WHEN CODTMV IN ('3.1.28','4.1.04') THEN ENTRADA ELSE 0 END) AS TRANSF_ENTRADA,
SUM (CASE WHEN CODTMV IN ('1.1.27','1.1.33') THEN SAIDA ELSE 0 END) AS BAIXA,
SUM (CASE WHEN CODTMV = '4.1.01' THEN ENTRADA ELSE 0 END) AS IMPLANT_SALDO,
SUM (CASE WHEN CODTMV IN ('4.1.03') THEN ENTRADA2 ELSE 0 END) AS REDUZ_BAIXA,

/*Saídas*/

SUM (CASE WHEN CODTMV IN ('2.2.05') THEN ENTRADA ELSE 0 END)*-1 AS ESTORNO,
SUM (CASE WHEN CODTMV IN ('3.1.28','3.1.36','3.1.39','4.1.05') THEN SAIDA ELSE 0 END) AS TRANSF_SAIDA,
SUM (CASE WHEN CODTMV IN ('4.1.06') THEN SAIDA ELSE 0 END) AS AJUSTE,
SUM (CASE WHEN CODTMV IN ('2.1.01') THEN SAIDA ELSE 0 END) AS DEVOLUCAO,
GRUPO.PREÇO_MEDIO,
GRUPO.CODLOC

FROM (

		SELECT 
		T.IDPRD, 
		T.CODIGOPRD, 
		T.NOMEFANTASIA, 
		T.CODTMV,
		T.CODLOC,
		SUM(ISNULL(T.ENTRADA,0)) AS ENTRADA, 
		(SUM(ISNULL(T.SAIDA,0)) - SUM(ISNULL(T.ENTRADA2,0)))AS SAIDA, 
		 T.CODUNDCONTROLE,
		(SUM(ISNULL(T.ENTRADA,0)) -SUM(ISNULL(T.SAIDA,0)) )AS DIFERENCA,
		SUM(ISNULL(T.ENTRADA2,0)) AS ENTRADA2,
		TAB_PRECO_MEDIO.PRECO_MEDIO

		 FROM 
				(select 
				TPRD.IDPRD, 
				TPRD.CODIGOPRD, 
				TPRD.NOMEFANTASIA, 
				TMOV.CODTMV, 
					(CASE WHEN TITMMOV.CODUND = TPRD.CODUNDCONTROLE 
					 THEN  (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)  
					 ELSE ( (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)  
					 * 
						(SELECT ISNULL(FATORCONVERSAO,0) 
						FROM TUND (NOLOCK) 
						WHERE TUND.CODUND = TITMMOV.CODUND)
					) / 
						(SELECT ISNULL(FATORCONVERSAO,0) 
						FROM TUND (NOLOCK)  
						WHERE TUND.CODUND = TPRD.CODUNDCONTROLE)
					END) AS ENTRADA, 
				 0 AS SAIDA,
				TPRD.CODUNDCONTROLE,
					TMOV.CODLOC,
					0 AS ENTRADA2,
					TMOV.CODFILIAL

				FROM TITMMOV (NOLOCK)

				INNER JOIN TMOV (NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
				INNER JOIN TPRD (NOLOCK) ON TPRD.CODCOLIGADA = TMOV.CODCOLIGADA AND TPRD.IDPRD = TITMMOV.IDPRD

				WHERE TMOV.CODCOLIGADA= '1'
 				AND (TITMMOV.QUANTIDADETOTAL<>0 OR TITMMOV.QUANTIDADE<>0) 
				AND TMOV.STATUS <> 'C' 
				AND TMOV.CODTMV IN ('2.2.05','1.1.40','1.1.41','4.1.01','4.1.04' ,'3.1.28')
				AND (
					CASE WHEN TMOV.CODTMV = '3.1.28' THEN TMOV.CODLOCDESTINO  
				   ELSE TMOV.CODLOC END) BETWEEN '1' AND '9.9999' 
				AND (CASE WHEN TMOV.CODTMV = '3.1.28' THEN TMOV.CODFILIALDESTINO
					   ELSE TMOV.CODFILIAL END) ='1'
				AND TPRD.CODIGOPRD >='a' AND TPRD.CODIGOPRD <='z' 
				AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) >= '2023-01-01' 
				AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) <= '2023-05-01'

				UNION ALL

				SELECT 
				TPRD.IDPRD, 
				TPRD.CODIGOPRD, 
				TPRD.NOMEFANTASIA, 
				TMOV.CODTMV,
				0 AS ENTRADA, 
				(CASE WHEN TITMMOV.CODUND = TPRD.CODUNDCONTROLE 
				 THEN  (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)  
				 ELSE ( (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)  
				 * 
					(SELECT ISNULL(FATORCONVERSAO,0) 
					FROM TUND (NOLOCK) 
					WHERE TUND.CODUND = TITMMOV.CODUND)
				) / 
					(SELECT ISNULL(FATORCONVERSAO,0) 
					FROM TUND (NOLOCK) 
					WHERE TUND.CODUND = TPRD.CODUNDCONTROLE)
				 END) AS SAIDA,
				TPRD.CODUNDCONTROLE,
				TMOV.CODLOC,
				0 AS ENTRADA2,
				TMOV.CODFILIAL

				FROM TITMMOV (NOLOCK)

				INNER JOIN TMOV (NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
				INNER JOIN TPRD (NOLOCK) ON TPRD.CODCOLIGADA = TMOV.CODCOLIGADA AND TPRD.IDPRD = TITMMOV.IDPRD

				WHERE TMOV.CODCOLIGADA= '1'
				AND TMOV.CODFILIAL ='1'
 				AND (TITMMOV.QUANTIDADETOTAL<>0 OR TITMMOV.QUANTIDADE<>0) 
				AND TMOV.STATUS <> 'C' 
				AND TMOV.CODTMV IN  ('1.1.03','1.1.27','1.1.33','3.1.28','3.1.36','3.1.39','2.1.01','4.1.06','4.1.05')
				AND TMOV.CODLOC BETWEEN '1' AND '9.9999'
				AND TPRD.CODIGOPRD >='a' 
				AND TPRD.CODIGOPRD <='z' 
				AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) >= '2023-01-01' 
				AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) <= '2023-05-01'

				UNION ALL

				SELECT 
				TPRD.IDPRD, 
				TPRD.CODIGOPRD, 
				TPRD.NOMEFANTASIA, 
				TMOV.CODTMV,
				0 AS ENTRADA, 
				0 AS SAIDA,
				TPRD.CODUNDCONTROLE,
				TMOV.CODLOC,
					(CASE WHEN TITMMOV.CODUND = TPRD.CODUNDCONTROLE 
					 THEN  (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)  
					 ELSE ( (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END) 
					 *
						(SELECT FATORCONVERSAO 
						FROM TUND (NOLOCK) 
						WHERE TUND.CODUND = TITMMOV.CODUND)
					 ) / 
						(SELECT FATORCONVERSAO 
						FROM TUND (NOLOCK) 
						WHERE TUND.CODUND = TPRD.CODUNDCONTROLE)
					 END) AS ENTRADA2,
				TMOV.CODFILIAL

				FROM TITMMOV (NOLOCK)

				INNER JOIN TMOV (NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
				INNER JOIN TPRD (NOLOCK) ON TPRD.CODCOLIGADA = TMOV.CODCOLIGADA AND TPRD.IDPRD = TITMMOV.IDPRD

				 WHERE TMOV.CODCOLIGADA= '1'
				 AND TMOV.CODFILIAL ='1'
				 AND (TITMMOV.QUANTIDADETOTAL<>0 OR TITMMOV.QUANTIDADE<>0) 
				 AND TMOV.STATUS <> 'C' 
				 AND TMOV.CODTMV IN 
					(select TTMV.CODTMV 
					from TTMV (NOLOCK)
					inner join TITMTMV (NOLOCK) on TTMV.CODTMV = TITMTMV.CODTMV AND TTMV.CODCOLIGADA = TITMTMV.CODCOLIGADA
					and TITMTMV.codtmv ='4.1.03')  
				 AND TMOV.CODLOC BETWEEN '1' AND '9.9999'
				 AND TPRD.CODIGOPRD >='a' 
				 AND TPRD.CODIGOPRD <='z' 
				 AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) >= '2023-01-01' 
				 AND (CASE WHEN CAST(TMOV.DATACRIACAO AS DATE) IS NULL THEN CAST(TMOV.DATACRIACAO AS DATE) ELSE CAST(TMOV.DATACRIACAO AS DATE) END) <= '2023-05-01'
				) AS T 

		LEFT JOIN (SELECT * FROM DBO.TABELA_PRECO_MEDIO('1', '2023-01-01', '2023-05-01', '1', '9.9999')) AS TAB_PRECO_MEDIO ON (TAB_PRECO_MEDIO.IDPRD = T.IDPRD AND TAB_PRECO_MEDIO.CODCOLIGADA = '1')

		GROUP BY
		T.IDPRD, T.CODIGOPRD, T.NOMEFANTASIA,
		T.CODUNDCONTROLE, T.CODTMV, T.CODLOC,T.CODFILIAL,
		TAB_PRECO_MEDIO.PRECO_MEDIO

		) AS GRUPO

GROUP BY 
GRUPO.IDPRD,
GRUPO.CODIGOPRD,
GRUPO.NOMEFANTASIA,
GRUPO.PREÇO_MEDIO,
GRUPO.CODUNDCONTROLE,
GRUPO.CODLOC


ORDER BY GRUPO.NOMEFANTASIA