BEGIN TRAN
UPDATE TUSRTMV SET INCLUIR = 0 , 
ALTERAR= 0, 
EXCLUIR= 0, 
CANCELAR= 0, 
LANCAR= 0, 
FATURAR= 0, 
ATIVAR= 0, 
IMPRIMIR= 0, 
ALTERARDEPOISIMP= 0, 
REABRIR= 0, 
CONSULTAR= 0, 
COPIAR= 0, 
CONTABILIZAR= 0, 
REIMPRIMIR= 0, 
ESTORNARCONTAB= 0, 
INCLUIRPORFAT= 0, 
ALTERARDEPOISEMAIL= 0, 
EMAIL= 0, COTAR= 0, 
ALTERARITEMINTEGRADO= 0, 
GERACONTRATO= 0, 
GERARCOTACAOAUTOMATICA = 0, 
RECMODIFIEDBY = 'gabriel.ferreira', 
RECMODIFIEDON = getdate()
WHERE TUSRTMV.CODUSUARIO IN (
								SELECT TUSRTMV.CODUSUARIO
								FROM GUSRPERFIL 
								LEFT JOIN TUSRTMV	(NOLOCK) ON (TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
								LEFT JOIN GUSUARIO	(NOLOCK) ON (GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
								LEFT JOIN PFUNC		(NOLOCK) ON (PFUNC.NOME = GUSUARIO.NOME)
								
								WHERE CODSISTEMA = 'T'    
								AND CODTMV = '1.1.80'
								AND PFUNC.CODSITUACAO <>  'D'
								AND PFUNC.CODSECAO NOT IN ('01.500.20', '01.500.11', '01.500.74') GROUP BY TUSRTMV.CODUSUARIO )
AND TUSRTMV.CODTMV = '1.1.80'

--commit