DECLARE @COLIGADA INT = 37

SELECT CODCOLIGADA, CODFILIAL, NOMEFANTASIA, CGC 
FROM GFILIAL
WHERE CODCOLIGADA IN (@COLIGADA)


SELECT PFUNC.NOME, GUSUARIO.EMAIL, PPESSOA.CODUSUARIO, PFUNC.CODCOLIGADA
FROM PFUNC (NOLOCK)
JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA
JOIN GUSUARIO (NOLOCK) ON PPESSOA.CODUSUARIO = GUSUARIO.CODUSUARIO
JOIN GPERMIS (NOLOCK) ON GPERMIS.CODCOLIGADA = PFUNC.CODCOLIGADA AND GPERMIS.CODUSUARIO = GUSUARIO.CODUSUARIO
WHERE PFUNC.CODCOLIGADA IN (@COLIGADA) 
AND CODSISTEMA = 'T'
AND CODSITUACAO <> 'D'
AND GUSUARIO.EMAIL IN ('abia.vicente@emccamp.com.br'
,'alecson.santos@emccamp.com.br'
,'alesson.silva@emccamp.com.br'
,'alex.jesus@emccamp.com.br'
,'alex.santos@emccamp.com.br'
,'alexandre.cantarino@emccamp.com.br'
,'alexandremoreira@emccamp.com.br'
,'aline.cruz@emccamp.com.br'
,'alysson.silverio@emccamp.com.br'
,'ana.almeida@emccamp.com.br'
,'anderson.santos@emccamp.com.br'
,'andre.barbosa@emccamp.com.br'
,'arthur.cordeiro@emccamp.com.br'
,'barbara.costa@emccamp.com.br'
,'barbara.pimenta@emccamp.com.br'
,'brenda.freitas@emccamp.com.br'
,'breno.souza@emccamp.com.br'
,'bruno.felix@emccamp.com.br'
,'carlos.pereira@emccamp.com.br'
,'carloseduardo.melo@emccamp.com.bR'
,'carloseduardo.melo@emccamp.com.br'
,'carlos.oliveira@emccamp.com.br'
,'carolina.lins@emccamp.com.br'
,'caroline.pereira@emccamp.com.br'
,'celio.santos@emccamp.com.br'
,'charles.goncalves@emccamp.com.br'
,'cinthya.freitas@emccamp.com.br'
,'cristiano.ribeiro@emccamp.com.br'
,'daniele.glater@emccamp.com.br'
,'debora.brito@emccamp.com.br'
,'deise.porto@emccamp.com.br'
,'eduardo.argolo@emccamp.com.br'
,'elizeu.oliveira@emccamp.com.br'
,'erick.telles@emccamp.com.br'
,'fabiano.souza@emccamp.com.br'
,'fabio.pimenta@emccamp.com.br'
,'fabio.rodrigues@emccamp.com.br'
,'felipe.almeida@emccamp.com.br'
,'fiscal@emccamp.com.br'
,'flavia.martins@emccamp.com.br'
,'flaviano.silva@emccamp.com.br'
,'frederico.cerqueira@emccamp.com.br'
,'gabriela.ferreira@emccamp.com.br'
,'geraldo.carvalho@emccamp.com.br'
,'gilberto.vieira@emccamp.com.br'
,'gilliard.forte@emccamp.com.br'
,'gilmar.santana@emccamp.com.br'
,'giovanny.santos@emccamp.com.br'
,'guilherme.italia@emccamp.com.br'
,'igor.rodrigues@emccamp.com.br'
,'inacio.rodrigues@emccamp.com.br'
,'jeferson.nascimento@emccamp.com.br'
,'jessica.franca@emccamp.com.br'
,'jessica.rodrigues@emccamp.com.br'
,'joao.barbosa@emccamp.com.br'
,'joao.vicente@emccamp.com.br'
,'joao.teodoro@emccamp.com.br'
,'joel.lima@emccamp.com.br'
,'jonatas.nascimento@emccamp.com.br'
,'jorge.lima@construtoraemccamp.com.br'
,'jorge.pereira@emccamp.com.br'
,'jose.nilson@emccamp.com.br'
,'karina.moreira@emccamp.com.br'
,'kelly.guerra@emccamp.com.br'
,'larissa.morais@emccamp.com.br'
,'layane.rodrigues@emccamp.com.br'
,'leandro.santana@emccamp.com.br'
,'leiliana.silva@emccamp.com.br'
,'leonardo.correa@emccamp.com.br'
,'leonardo.oliveira@emccamp.com.br'
,'leydiane.viana@emccamp.com.br'
,'lilian.roman@emccamp.com.br'
,'luana.silva@emccamp.com.br'
,'lucas.sales@emccamp.com.br'
,'luciano.jesus@emccamp.com.br'
,'luciara.silva@emccamp.com.br'
,'luis.vebri@emccamp.com.br'
,'luiz.santos@emccamp.com.br'
,'luiz.viana@emccamp.com.br'
,'luiza.silva@emccamp.com.br'
,'marcelo.candido@emccamp.com.br'
,'marcelo.pereira@emccamp.com.br'
,'marcelo.ribeiro@emccamp.com.br'
,'marcelo.silva@emccamp.com.br'
,'marcos.vinicius@emccamp.com.br'
,'mariany.silva@emccamp.com.br'
,'marta.mendes@emccamp.com.br'
,'mateus.almeida@emccamp.com.br'
,'matheus.ferreira@emccamp.com.br'
,'mauro.silva@emccamp.com.br'
,'mayara.martins@emccamp.com.br'
,'michael.silva@emccamp.com.br'
,'natalia.santos@emccamp.com.br'
,'natalia.silveira@emccamp.com.br'
,'patricia.silva@emccamp.com.br'
,'paulo.financeiro@emccamp.com.br'
,'paulo.junior@emccamp.com.br'
,'paulo.neto@emccamp.com.br'
,'paulo.oliveira@emccamp.com.br'
,'rafael.azevedo@emccamp.com.br'
,'rafael.mendonca@emccamp.com.br'
,'ramiro.joaquim@emccamp.com.br'
,'ramon.alvim@emccamp.com.br'
,'raphael.assis@emccamp.com.br'
,'redner.pereira@emccamp.com.br'
,'ricardo.souto@emccamp.com.br'
,'robertinho.moreira@emccamp.com.br'
,'robson.cunha@emccamp.com.br'
,'rodrigo.lopes@emccamp.com.br'
,'rogerio.junior@emccamp.com.br'
,'romana.cabral@emccamp.com.br'
,'ronan.caetano@emccamp.com.br'
,'ronni.vieira@emccamp.com.br'
,'rosivan.santos@emccamp.com.br'
,'sabrina.sales@emccamp.com.br'
,'silvana.goncalves@emccamp.com.br'
,'silvio@emccamp.com.br'
,'simone.melo@emccamp.com.br'
,'stepane.pereira@emccamp.com.br'
,'tayana.ibanez@emccamp.com.br'
,'thaina.silva@emccamp.com.br'
,'thais.aguiar@emccamp.com.br'
,'thamiris.oliveira@emccamp.com.br'
,'thatiana.seminara@emccamp.com.br'
,'recebimento.nfe@emccamp.com.br'
,'rogerio.amorim@emccamp.com.br'
,'vildigar.santos@emccamp.com.br'
,'washington.rodrigues@emccamp.com.br'
,'wellington.silva@emccamp.com.br'
,'weverton.gomes@emccamp.com.br'
,'yan.alves@emccamp.com.br'
)



