SELECT 
FLAN.CODCOLIGADA 'AS COLIGADA',
FLAN.IDLAN,
FLAN.DATABAIXA AS 'DATA DA BAIXA',
GCCUSTO.CODCCUSTO AS 'CENTRO DE CUSTO',
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO', 
FCFO.NOME AS 'NOME FANTASIA', 
FLAN.HISTORICO, 
FLANBAIXA.VALORBAIXA AS 'VALOR BAIXADO', 
FLAN.CODTB2FLX, 
FTB2.DESCRICAO AS 'DESCRICAO PRODUTO', 
FTB5.DESCRICAO AS 'DESCRICAO ITEM',
FLAN.CODCXA AS 'CONTA CAIXA',
FLAN.DATAVENCIMENTO AS 'DATA_VENCIMENTO',
FLANBAIXA.DATABAIXA AS 'DATA_BAIXA',
FLANBAIXA.DATACONTABILIZBX AS 'DATA CONTABILIZAÇÃO'


FROM FLANBAIXA  (NOLOCK)
LEFT JOIN 		FLAN				(NOLOCK) ON (FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA)
LEFT JOIN		TMOV				(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN		FTB5				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN		FCFO				(NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN		FCFODEF				(NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN		FTB2 AS FTB2_DEF	(NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)
LEFT JOIN		FTB2				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB2.CODCOLIGADA AND FLAN.CODTB2FLX=FTB2.CODTB2FLX)
LEFT JOIN		FLANRATCCU			(NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN)
LEFT JOIN		GCCUSTO			(NOLOCK) ON (GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO AND GCCUSTO.CODCOLIGADA = FLAN.CODCOLIGADA)

WHERE
FLAN.CODCOLIGADA IN (@CODCOLIGADA)
AND FLANBAIXA.DATACONTABILIZBX BETWEEN @DATA_BAIXA_INICIAL AND @DATA_BAIXA_FINAL
AND FLAN.PAGREC = 1
AND FLAN.CODTDO NOT IN('0025', '0041')
AND FLAN.NFOUDUP <> 1
AND FLAN.CODCXA NOT IN ('1','4')
AND FLANBAIXA.STATUS <> 1
AND FLANBAIXA.VALORBAIXA > 0
AND FLAN.CODTB2FLX IN (@CLASS_FINANC)

ORDER BY FLAN.CODCOLIGADA 