SELECT 

FXCX.IDXCX AS IDXCX2
,(CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO OR FXCX.IDFORMAPAGTO IN ('2','4') OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATACOMPENSACAO ELSE FXCX.DATA END) AS DATA
,FXCX.NUMERODOCUMENTO

,(SELECT TOP 1 CASE WHEN FLAN.CNABSTATUS <> 0 THEN
	CASE WHEN FLAN.PAGREC = 2 THEN
	'CEF REMESSA' ELSE FXCX.NOMINAL END 
	ELSE FXCX.NOMINAL END) AS 'NOMINAL'
,FXCX.VALOR

	,(

	SELECT DISTINCT  TOP 1 SUM(FXCX.VALOR)

	FROM FXCX (NOLOCK)

	WHERE FXCX.COMPENSADO<>2 
	AND FXCX.CODCXA = @CONTA_CAIXA
	AND (CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO AND FXCX.IDFORMAPAGTO = '2' OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATA ELSE FXCX.DATACOMPENSACAO END ) < @DATA_INI_D
	AND FXCX.CODCOLIGADA = @COLIGADA
	AND FXCX.TIPO NOT IN (8,9,10)
	AND FXCX.DATAESTORNO IS NULL
	) +	(SUM(FXCX.VALOR) OVER(ORDER BY FXCX.DATACOMPENSACAO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW))AS SALDO
--,(
--	(
--	SELECT SALDODATABASE FROM FCXA (NOLOCK) 
--	WHERE 
--	FCXA.CODCXA = @CONTA_CAIXA
--	AND FCXA.CODCOLIGADA = @COLIGADA)
--	+ 
--	(
--	SELECT DISTINCT  ISNULL(SUM(FXCX.VALOR),0) 
--	FROM FXCX (NOLOCK)
--	WHERE FXCX.COMPENSADO<>2 
--	AND FXCX.CODCXA = @CONTA_CAIXA
--	AND FXCX.DATACOMPENSACAO < @DATA_INI_D
--	AND FXCX.CODCOLIGADA = @COLIGADA
--	AND FXCX.TIPO NOT IN (8,9,10)
--	)+	
--	(SUM(FXCX.VALOR) OVER(ORDER BY FXCX.DATACOMPENSACAO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
--	)  
----)
----+
----	(
----	SELECT CASE WHEN SUM(VALOR) <1 THEN SUM(VALOR) ELSE 0 END FROM FXCX 
--	WHERE CODCOLIGADA= @COLIGADA
--	AND IDXCX IN 
--	(
--	SELECT 
--	FXCX.IDXCX
--	FROM FXCX (NOLOCK)

--	WHERE
--	(CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO AND FXCX.IDFORMAPAGTO IN ('2') OR  FXCX.DATACOMPENSACAO IS NULL 
--			THEN FXCX.DATA ELSE FXCX.DATACOMPENSACAO END )
--			BETWEEN @DATA_INI_NAO_COMPENSADOS AND @DATA_FIM_NAO_COMPENSADOS
--	AND FXCX.CODCOLIGADA = @COLIGADA
--	AND FXCX.CODCXA = @CONTA_CAIXA
--	AND FXCX.COMPENSADO <= 0
--	)
--) AS SALDO

FROM FXCX (NOLOCK)
	LEFT JOIN FLAN (NOLOCK) ON (FXCX.CODCOLIGADA = FLAN.CODCOLIGADA AND FXCX.IDXCX = FLAN.IDXCX)
	LEFT JOIN FLANBAIXA (NOLOCK) ON (FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLXCX)
	LEFT JOIN FCFO (NOLOCK) ON (FCFO.CODCFO = FLAN.CODCFO AND FCFO.CODCOLIGADA = FLAN.CODCOLCFO)

WHERE		
		FXCX.DATACOMPENSACAO BETWEEN @DATA_INI_D AND @DATA_FIM_D
		AND FXCX.CODCOLIGADA = @COLIGADA
		AND FXCX.CODCXA = @CONTA_CAIXA
		AND FXCX.DATAESTORNO IS NULL
ORDER BY
(CASE WHEN FXCX.DATA <> FXCX.DATACOMPENSACAO OR FXCX.IDFORMAPAGTO IN ('2','4') OR  FXCX.DATACOMPENSACAO IS NULL  THEN FXCX.DATACOMPENSACAO ELSE FXCX.DATA END)