/*CONSULTA - SALDO
declare @DATA_INI_D date = '20240301'
declare @DATA_FIM_D	date = '20240331'
declare @CONTA_CAIXA varchar(15) = '56161-4'
declare @COLIGADA int = 1
*/

DECLARE @SALDO RMDVALOR4

DECLARE @CODCOLIGADA INT, @CONT INT, @IDXCX INT, @SALDO_ANTERIOR RMDVALOR4, @VALOR RMDVALOR4

DECLARE @TABELA TABLE (CODCOLIGADA INT, IDXCX INT, VALOR RMDVALOR4, SALDO RMDVALOR4, SALDO_ANTERIOR RMDVALOR4)

DECLARE CURSOR01 CURSOR FOR 

SELECT 
FXCX.CODCOLIGADA,
ROW_NUMBER() OVER (ORDER BY FXCX.DATACOMPENSACAO,FXCX.IDXCX) AS CONT,
FXCX.IDXCX,

ISNULL((SELECT 
	SUM(F.VALOR) AS 'SALDO_ANTERIOR_RM'
	FROM FXCX F(NOLOCK)
	WHERE
	F.CODCOLIGADA = @COLIGADA
	AND F.DATACOMPENSACAO < @DATA_INI_D
	AND F.CODCXA = @CONTA_CAIXA),'0')  AS 'SALDO_ANTERIOR_RM',
 
FXCX.VALOR AS 'VALOR'


FROM FXCX (NOLOCK)
 
WHERE
FXCX.CODCOLIGADA = @COLIGADA
AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
AND FXCX.CODCXA = @CONTA_CAIXA

ORDER BY
FXCX.DATACOMPENSACAO,FXCX.IDXCX
 
OPEN CURSOR01
FETCH NEXT FROM CURSOR01 INTO  @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR 
WHILE @@FETCH_STATUS = 0 
BEGIN 

IF (@CONT = 1)
	BEGIN
		INSERT INTO @TABELA VALUES(@CODCOLIGADA, @IDXCX, @VALOR, (@SALDO_ANTERIOR + @VALOR), @SALDO_ANTERIOR )
		SET @SALDO = @SALDO_ANTERIOR + @VALOR
	END
ELSE
	BEGIN
		INSERT INTO @TABELA VALUES(@CODCOLIGADA, @IDXCX, @VALOR, (@SALDO + @VALOR), @SALDO_ANTERIOR )
		SET @SALDO = @SALDO + @VALOR
	END


FETCH NEXT FROM CURSOR01 INTO  @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR 
END 
CLOSE CURSOR01
DEALLOCATE CURSOR01

SELECT 

A.IDXCX,
/*FXCX.DATA,*/
FXCX.DATACOMPENSACAO AS 'DATA',
FXCX.NUMERODOCUMENTO,
'' AS 'NOMINAL',
A.VALOR,
A.SALDO,
A.SALDO_ANTERIOR

FROM @TABELA AS A
INNER JOIN FXCX (NOLOCK) ON (FXCX.IDXCX = A.IDXCX AND FXCX.CODCOLIGADA = A.CODCOLIGADA)


WHERE
FXCX.CODCOLIGADA = @COLIGADA
AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
AND FXCX.CODCXA = @CONTA_CAIXA


ORDER BY
FXCX.DATACOMPENSACAO,FXCX.IDXCX