DECLARE @DATA_INI_D DATE = '20240301'
DECLARE @DATA_FIM_D DATE = '20240331'

-- LISTA DAS COLIGADAS VÁLIDAS (AJUSTE SE QUISER IGNORAR ALGUMAS)
DECLARE @COLIGADAS TABLE (CODCOLIGADA INT)
INSERT INTO @COLIGADAS
SELECT CODCOLIGADA
FROM GCOLIGADA
WHERE CODCOLIGADA NOT IN (54, 61)
AND CODCOLIGADA BETWEEN 2 AND 9

-- TABELA TEMPORÁRIA COM TODAS AS CONTAS COM MOVIMENTAÇÃO NO PERÍODO
DECLARE @CONTAS TABLE (ID INT IDENTITY(1,1), CODCOLIGADA INT, CONTA_CAIXA VARCHAR(20))
INSERT INTO @CONTAS
SELECT DISTINCT CODCOLIGADA, CODCXA
FROM FXCX
WHERE DATACOMPENSACAO BETWEEN @DATA_INI_D AND @DATA_FIM_D
AND FXCX.VALOR <> 0

-- TABELA FINAL DE RESULTADOS
DECLARE @RESULTADO TABLE (
    CODCOLIGADA INT,
    CODCXA VARCHAR(20),
    VALOR RMDVALOR4,
    SALDO RMDVALOR4,
    SALDO_ANTERIOR RMDVALOR4
)

-- VARIÁVEIS AUXILIARES
DECLARE @IDX INT = 1
DECLARE @TOTAL INT = (SELECT COUNT(*) FROM @CONTAS)

-- LOOP PRINCIPAL
WHILE @IDX <= @TOTAL
BEGIN
    DECLARE @COLIGADA INT, @CONTA_CAIXA VARCHAR(20)
    SELECT @COLIGADA = CODCOLIGADA, @CONTA_CAIXA = CONTA_CAIXA FROM @CONTAS WHERE ID = @IDX

    -- TABELA TEMPORÁRIA PARA OS CÁLCULOS
    DECLARE @TABELA TABLE (CODCOLIGADA INT, IDXCX INT, VALOR RMDVALOR4, SALDO RMDVALOR4, SALDO_ANTERIOR RMDVALOR4)

    DECLARE @SALDO RMDVALOR4
    DECLARE @CODCOLIGADA_C INT, @CONT INT, @IDXCX INT, @SALDO_ANTERIOR RMDVALOR4, @VALOR RMDVALOR4

    DECLARE CURSOR01 CURSOR FOR 
    SELECT 
        FXCX.CODCOLIGADA,
        ROW_NUMBER() OVER (ORDER BY FXCX.DATACOMPENSACAO, FXCX.IDXCX) AS CONT,
        FXCX.IDXCX,

        ISNULL((SELECT SUM(F.VALOR) FROM FXCX F(NOLOCK)
                WHERE F.CODCOLIGADA = FXCX.CODCOLIGADA
                AND F.DATACOMPENSACAO < @DATA_INI_D
                AND F.CODCXA = @CONTA_CAIXA), 0) AS SALDO_ANTERIOR_RM,

        FXCX.VALOR
    FROM FXCX (NOLOCK)
    WHERE
        FXCX.CODCOLIGADA = @COLIGADA
        AND FXCX.DATACOMPENSACAO BETWEEN @DATA_INI_D AND @DATA_FIM_D
        AND FXCX.CODCXA = @CONTA_CAIXA
    ORDER BY FXCX.DATACOMPENSACAO, FXCX.IDXCX

    OPEN CURSOR01
    FETCH NEXT FROM CURSOR01 INTO @CODCOLIGADA_C, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR 
    WHILE @@FETCH_STATUS = 0 
    BEGIN 
        IF @CONT = 1
        BEGIN
            INSERT INTO @TABELA VALUES(@CODCOLIGADA_C, @IDXCX, @VALOR, (@SALDO_ANTERIOR + @VALOR), @SALDO_ANTERIOR)
            SET @SALDO = @SALDO_ANTERIOR + @VALOR
        END
        ELSE
        BEGIN
            INSERT INTO @TABELA VALUES(@CODCOLIGADA_C, @IDXCX, @VALOR, (@SALDO + @VALOR), @SALDO_ANTERIOR)
            SET @SALDO = @SALDO + @VALOR
        END

        FETCH NEXT FROM CURSOR01 INTO @CODCOLIGADA_C, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR 
    END 
    CLOSE CURSOR01
    DEALLOCATE CURSOR01

    -- INSERINDO O RESULTADO CONSOLIDADO
    INSERT INTO @RESULTADO
    SELECT 
    FXCX.CODCOLIGADA,
    FXCX.CODCXA,
    SUM(T.VALOR),
    SUM(T.SALDO),
    T.SALDO_ANTERIOR
    FROM @TABELA T
    INNER JOIN FXCX (NOLOCK) ON FXCX.IDXCX = T.IDXCX AND FXCX.CODCOLIGADA = T.CODCOLIGADA
    
	WHERE FXCX.CODCOLIGADA = @COLIGADA
    AND FXCX.DATACOMPENSACAO BETWEEN @DATA_INI_D AND @DATA_FIM_D
    AND FXCX.CODCXA = @CONTA_CAIXA
    GROUP BY 
	FXCX.CODCOLIGADA,
	FXCX.CODCXA,
	T.SALDO_ANTERIOR

    SET @IDX = @IDX + 1
END

-- EXIBIR RESULTADOS
SELECT * FROM @RESULTADO
ORDER BY CODCOLIGADA, CODCXA
