
--sql_cabeçalho - SALDO ANTERIOR RM 
/*declare @DATA_INI_D date = '20240501'
declare @DATA_FIM_D	date = '20240531'
declare @COLIGADA int = 39*/

SELECT 
G.CODCXA,
G.NOME_CONTA,
G.SALDO_ANTERIOR_RM,
G.SALDO_FINAL_RM,
((G.SALDO_ANTERIOR_RM - G.SALDO_FINAL_RM)* (-1)) AS TOTAL

FROM (

SELECT 
FCXA.CODCXA,
UPPER(FCXA.DESCRICAO) AS NOME_CONTA,

CONVERT(MONEY,ISNULL((SELECT 
			SUM(FXCX1.VALOR) 
			FROM FXCX as FXCX1 (NOLOCK)
			WHERE
			FXCX1.CODCOLIGADA = FCXA.CODCOLIGADA
			AND FXCX1.DATACOMPENSACAO < @DATA_INI_D
			AND FXCX1.CODCXA = FCXA.CODCXA
			GROUP BY
			FXCX1.CODCXA),'0')) AS 'SALDO_ANTERIOR_RM',


CONVERT(MONEY,(
	SELECT 
	SUM(fxcx2.VALOR)
	FROM FXCX as fxcx2 (NOLOCK)
	WHERE
	fxcx2.CODCOLIGADA = FCXA.CODCOLIGADA
	AND fxcx2.DATACOMPENSACAO <= @DATA_FIM_D
	AND fxcx2.CODCXA = FCXA.CODCXA
)) AS 'SALDO_FINAL_RM'




FROM FCXA (NOLOCK) /*ALTERADO TABELAS PARA PEGAR AS CONTAS MESMO SEM EXTRATO*/
LEFT JOIN FXCX			(NOLOCK)	ON (FXCX.CODCOLIGADA = FCXA.CODCOLIGADA AND FXCX.CODCXA = FCXA.CODCXA)
WHERE
FCXA.CODCOLIGADA IN (@COLIGADA)


GROUP BY
FCXA.CODCOLIGADA,
FCXA.CODCXA,
FCXA.DESCRICAO


) AS G
WHERE G.SALDO_ANTERIOR_RM > 0

GROUP BY 
G.CODCXA,
G.NOME_CONTA,
G.SALDO_ANTERIOR_RM,
G.SALDO_FINAL_RM