/*DECLARE @COLIGADA INT = 57,
		--@FILIAL INT = 63,
		@DATAINI DATE ='20250101',
		@DATAFIN DATE ='20250131',
		@TRIBUTO VARCHAR(12) = 'inss';
		--@IDMOV INT = 2166686*/
		

SELECT  

GRUPO.SQL,
GRUPO.IDLAF,
GRUPO.IDGUIA
,GRUPO.DATASAIDA
,GRUPO.CODCOLIGADA
,GRUPO.CODFILIAL
,GRUPO.NUMEROMOV
,GRUPO.IDMOV
,GRUPO.NOMEMUNICIPIO
,GRUPO.DATAEMISSAO
,GRUPO.DATACRIACAO
,GRUPO.CODTMV
,GRUPO.CODIGOSERVICO
,GRUPO.VALOR_BRUTO
,GRUPO.TRIBUTO
,GRUPO.USUARIOCRIACAO
,GRUPO.BAIXA_LANÇAMENTO_MOV
,GRUPO.VALOR_TRIBUTO
,GRUPO.STATUS_GUIA
,GRUPO.VALOR_GUIA
,GRUPO.DESCRICAO
,GRUPO.CODRECEITA
,GRUPO.DATAVENC

FROM (

				SELECT  /* SELECT PARA PEGAR O RTOTAL */

				1 AS 'SQL',	
				DGUIAPERIODO.IDLAF,
				DGUIAPERIODO.IDGUIA,
				TMOV.DATASAIDA,
				TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,TTRBMOV.CODTRB AS 'TRIBUTO'
				/*,DPERIODO.CODTRB AS 'TRIBUTO'*/
				,FORMAT(TTRBMOV.VALOR, 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				/*,FORMAT(SUM(DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'*/
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/ 
				,FORMAT(DGUIAPERIODO.VALORAPURADO, 'C', 'pt-BR') AS 'VALOR_GUIA'
				,(CASE	WHEN TRIBUTO.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN TRIBUTO.STATUSLAN = 1
							THEN 'Pago' 
						WHEN TRIBUTO.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN TRIBUTO.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN TRIBUTO.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN TRIBUTO.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
				 END) AS 'STATUS_GUIA'
			
				 /*,TRIBUTO.STATUSLAN as 'STATUS_GUIA'*/
				,DGUIAPERIODO.DESCRICAO
				,DGUIAPERIODO.CODRECEITA
				,DGUIAPERIODO.DATAVENC

				FROM FLAN (NOLOCK)
					INNER JOIN TMOV				(NOLOCK) ON	(TMOV.idmov = FLAN.idmov and TMOV.codcoligada = FLAN.codcoligada)
					INNER JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV)
					LEFT JOIN FRELLAN			(NOLOCK) ON (FLAN.idlan = FRELLAN.idlan and FLAN.codcoligada = FRELLAN.codcoligada and FRELLAN.tiporel = 9)
					LEFT JOIN FLAN AS TRIBUTO	(NOLOCK) ON (TRIBUTO.idlan = FRELLAN.idlanrel and TRIBUTO.codcoligada = FRELLAN.codcoligada)
					LEFT JOIN FFAT				(NOLOCK) ON (TRIBUTO.idfat = FFAT.idfat and TRIBUTO.codcoligada = FFAT.codcoligada and TRIBUTO.nfoudup = 1)
					LEFT JOIN FLAN AS RTOTAL	(NOLOCK) ON (FFAT.idfat = rtotal.idfat and rtotal.codcoligada = FFAT.codcoligada and rtotal.nfoudup = 2)
					LEFT JOIN DGUIAPERIODO		(NOLOCK) ON (rtotal.idguia = dguiaperiodo.idguia and rtotal.codcoligada = dguiaperiodo.CODCOLIGADA)
					LEFT JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
					/*INNER JOIN DPERIODO			(NOLOCK) ON (DPERIODO.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA AND DPERIODO.IDPER = DGUIAPERIODO.IDPER)*/

					WHERE

						TMOV.CODCOLIGADA IN (@COLIGADA)
						--AND TMOV.CODFILIAL IN (@FILIAL)
						AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
						AND TMOV.CODTMV IN ('1.2.07', '1.2.08', '1.2.10', '1.2.33', '1.2.64')
						AND TTRBMOV.VALOR >0
						AND TTRBMOV.CODTRB = 'RTOTAL'
						--AND TMOV.IDMOV = @IDMOV
						/*and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/

					GROUP BY 	

						TMOV.DATASAIDA,
						TMOV.CODCOLIGADA
						,TMOV.CODFILIAL
						,TMOV.NUMEROMOV
						,TMOV.IDMOV
						,GMUNICIPIO.NOMEMUNICIPIO
						,TMOV.DATAEMISSAO
						,TMOV.DATACRIACAO
						,TMOV.CODTMV
						,TMOV.CODIGOSERVICO
						,TMOV.VALORBRUTO
						,TTRBMOV.CODTRB
						/*,DPERIODO.CODTRB*/
						,TMOV.USUARIOCRIACAO
						,TRIBUTO.STATUSLAN
						,DGUIAPERIODO.VALORAPURADO
						,DGUIAPERIODO.DESCRICAO
						,DGUIAPERIODO.CODRECEITA
						,DGUIAPERIODO.DATAVENC,
						DGUIAPERIODO.IDLAF,
						DGUIAPERIODO.IDGUIA,TTRBMOV.VALOR

UNION ALL

			SELECT  /*SELECT PARA PEGAR O CAMPO TRIBUTO NO LANÇAMENTO APENAS NO MOVIMENTO 1.2.64*/
				2 AS 'SQL',	
				DGUIAPERIODO.IDLAF
				,DGUIAPERIODO.IDGUIA
				,TMOV.DATASAIDA
				,TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,'IR' AS 'TRIBUTO'
				,FORMAT(ISNULL(SUM(IRRF.VALORORIGINAL),SUM(TRIBUTO.VALORORIGINAL)), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/ 
				,FORMAT(DGUIAPERIODO.VALORAPURADO, 'C', 'pt-BR') AS 'VALOR_GUIA'
				,(CASE  WHEN TRIBUTO.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN TRIBUTO.STATUSLAN = 1
							THEN 'Pago'
						WHEN TRIBUTO.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN TRIBUTO.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN TRIBUTO.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN TRIBUTO.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
				 END) AS 'STATUS_GUIA'
				 /*,TRIBUTO.STATUSLAN as 'STATUS_GUIA'*/
				,DGUIAPERIODO.DESCRICAO
				,DGUIAPERIODO.CODRECEITA
				,DGUIAPERIODO.DATAVENC
				/*FROM TMOV (NOLOCK)

					LEFT JOIN FLAN				(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
					LEFT JOIN DLAF				(NOLOCK) ON (TMOV.IDMOV = DLAF.IDMOV AND TMOV.CODCOLIGADA = DLAF.CODCOLIGADA)
					LEFT JOIN DTRBLAF			(NOLOCK) ON (DTRBLAF.IDLAF = DLAF.IDLAF AND DTRBLAF.CODCOLIGADA = DLAF.CODCOLIGADA )
					LEFT JOIN DGUIAPERIODO		(NOLOCK) ON (DGUIAPERIODO.IDGUIA = DTRBLAF.IDGUIA AND DGUIAPERIODO.CODCOLIGADA = DTRBLAF.CODCOLIGADA)
					LEFT JOIN DPERIODO			(NOLOCK) ON (DPERIODO.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA AND DPERIODO.IDPER = DGUIAPERIODO.IDPER)
					LEFT JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
					LEFT JOIN FLAN AS LAMGUIA	(NOLOCK) ON (LAMGUIA.IDGUIA = DGUIAPERIODO.IDGUIA AND LAMGUIA.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA)	

				*/

				FROM FLAN (NOLOCK)

					INNER JOIN TMOV				(NOLOCK) ON	(TMOV.idmov = FLAN.idmov and TMOV.codcoligada = FLAN.codcoligada)
					LEFT JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV AND  TTRBMOV.VALOR >0)
					LEFT JOIN FRELLAN			(NOLOCK) ON (FLAN.idlan = FRELLAN.idlan and FLAN.codcoligada = FRELLAN.codcoligada and FRELLAN.tiporel = 1)
					LEFT JOIN FLAN AS TRIBUTO	(NOLOCK) ON (TRIBUTO.idlan = FRELLAN.idlanrel and TRIBUTO.codcoligada = FRELLAN.codcoligada)
					LEFT JOIN FFAT				(NOLOCK) ON (TRIBUTO.idfat = FFAT.idfat and TRIBUTO.codcoligada = FFAT.codcoligada and TRIBUTO.nfoudup = 1)
					LEFT JOIN FLAN AS IRRF		(NOLOCK) ON (FFAT.idfat = IRRF.idfat and IRRF.codcoligada = FFAT.codcoligada and IRRF.nfoudup = 2)
					LEFT JOIN DGUIAPERIODO		(NOLOCK) ON (IRRF.idguia = dguiaperiodo.idguia and IRRF.codcoligada = dguiaperiodo.CODCOLIGADA)
					LEFT JOIN DPERIODO			(NOLOCK) ON (DPERIODO.IDPER = DGUIAPERIODO.IDPER AND DGUIAPERIODO.CODCOLIGADA = DPERIODO.CODCOLIGADA)
					LEFT JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
					/*INNER JOIN DPERIODO			(NOLOCK) ON (DPERIODO.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA AND DPERIODO.IDPER = DGUIAPERIODO.IDPER)*/

					WHERE

						TMOV.CODCOLIGADA IN (@COLIGADA)
						AND TMOV.CODTMV IN ('1.2.64')
						--AND TMOV.CODFILIAL IN (@FILIAL)
						AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
		
						--AND TMOV.IDMOV = @IDMOV
						/*AND TTRBMOV.CODTRB IN (@TRIBUTO)

						and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/

					GROUP BY 	

						TMOV.DATASAIDA,
						TMOV.CODCOLIGADA
						,TMOV.CODFILIAL
						,TMOV.NUMEROMOV
						,TMOV.IDMOV
						,GMUNICIPIO.NOMEMUNICIPIO
						,TMOV.DATAEMISSAO
						,TMOV.DATACRIACAO
						,TMOV.CODTMV
						,TMOV.CODIGOSERVICO
						,TMOV.VALORBRUTO
						,DPERIODO.CODTRB
						/*,DPERIODO.CODTRB*/
						,TMOV.USUARIOCRIACAO
						,TRIBUTO.STATUSLAN
						,DGUIAPERIODO.VALORAPURADO
						,DGUIAPERIODO.DESCRICAO
						,DGUIAPERIODO.CODRECEITA
						,DGUIAPERIODO.DATAVENC
						,DGUIAPERIODO.IDLAF
						,DGUIAPERIODO.IDGUIA

UNION ALL

			(SELECT 

				GRUPO2.SQL,
				GRUPO2.IDLAF,
				GRUPO2.IDGUIA
				,GRUPO2.DATASAIDA
				,GRUPO2.CODCOLIGADA
				,GRUPO2.CODFILIAL
				,GRUPO2.NUMEROMOV
				,GRUPO2.IDMOV
				,GRUPO2.NOMEMUNICIPIO
				,GRUPO2.DATAEMISSAO
				,GRUPO2.DATACRIACAO
				,GRUPO2.CODTMV
				,GRUPO2.CODIGOSERVICO
				,GRUPO2.VALOR_BRUTO
				,GRUPO2.TRIBUTO
				,GRUPO2.VALOR_TRIBUTO
				,GRUPO2.USUARIOCRIACAO
				,GRUPO2.BAIXA_LANÇAMENTO_MOV
				,GRUPO2.VALOR_GUIA
				,GRUPO2.STATUS_GUIA
				,GRUPO2.DESCRICAO
				,GRUPO2.CODRECEITA
				,GRUPO2.DATAVENC

				FROM (
		/*SELECT PARA TRAZER OS LANÇAMENTOS QUE FORAM ESCRITURADOS E QUEM TEM IDGUIA PREENCHIDO NA DTRBITEM */
					SELECT 
					
						3 AS 'SQL',
							DTRBITEM.IDLAF,
				DTRBITEM.IDGUIA,
				TMOV.DATASAIDA,
				TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,DTRBITEM.CODTRB AS 'TRIBUTO'
				/*,DTRBITEM.CODTRB AS 'TRIBUTO'*/
				,FORMAT((DTRBITEM.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				/*,FORMAT(SUM(DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'*/
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/ 
				,FORMAT(DGUIAPERIODO.VALORAPURADO, 'C', 'pt-BR') AS 'VALOR_GUIA'
				,(CASE	WHEN LAMGUIA.STATUSLAN = 1
							THEN 'Pago'
						WHEN LAMGUIA.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN LAMGUIA.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN LAMGUIA.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN LAMGUIA.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN LAMGUIA.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
				 END) AS 'STATUS_GUIA'

				,DGUIAPERIODO.DESCRICAO
				,DGUIAPERIODO.CODRECEITA
				,DGUIAPERIODO.DATAVENC
						
						FROM TMOV (NOLOCK)

							INNER JOIN DLAF				(NOLOCK) ON (TMOV.IDMOV = DLAF.IDMOV AND TMOV.CODCOLIGADA = DLAF.CODCOLIGADA)
							INNER JOIN DITEM				(NOLOCK) ON (DITEM.IDLAF = DLAF.IDLAF AND DITEM.CODCOLIGADA = DLAF.CODCOLIGADA)
							INNER JOIN DTRBITEM			(NOLOCK) ON (DTRBITEM.CODCOLIGADA = DITEM.CODCOLIGADA AND DTRBITEM.IDLAF = DITEM.IDLAF AND DTRBITEM.NUMITEM = DITEM.NUMITEM)
							--INNER JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV AND DTRBITEM.CODTRB = TTRBMOV.CODTRB) 
							INNER JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)

					INNER JOIN DGUIAPERIODO		(NOLOCK) ON (DGUIAPERIODO.IDGUIA = DTRBITEM.IDGUIA AND DGUIAPERIODO.CODCOLIGADA = DTRBITEM.CODCOLIGADA)
					/*INNER JOIN DPERIODO			(NOLOCK) ON (DPERIODO.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA AND DPERIODO.IDPER = DGUIAPERIODO.IDPER)*/
					LEFT JOIN FLAN AS LAMGUIA	(NOLOCK) ON (LAMGUIA.IDGUIA = DGUIAPERIODO.IDGUIA AND LAMGUIA.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA)	

							WHERE

								TMOV.CODCOLIGADA IN (@COLIGADA)
								AND TMOV.CODTMV IN ('1.2.07', '1.2.08', '1.2.10', '1.2.33', '1.2.64')
								--AND TMOV.CODFILIAL IN (@FILIAL)
								AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
								AND DTRBITEM.CODTRB IN (@TRIBUTO)
								AND DTRBITEM.CODTRB NOT IN ('RTOTAL')
								AND DTRBITEM.VALORTRB >0
								AND DTRBITEM.IDGUIA IS NOT NULL
								--AND TMOV.IDMOV = @IDMOV
								--AND NOT EXISTS (SELECT 1 FROM DTRBLAF (NOLOCK) WHERE DTRBLAF.IDLAF = DLAF.IDLAF AND DTRBLAF.CODCOLIGADA = DLAF.CODCOLIGADA AND DTRBITEM.CODTRB = DTRBLAF.CODTRB AND DTRBLAF.IDGUIA IS NOT NULL)
								/*and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/
 
							GROUP BY 	

										TMOV.DATASAIDA,
						TMOV.CODCOLIGADA
						,TMOV.CODFILIAL
						,TMOV.NUMEROMOV
						,TMOV.IDMOV
						,GMUNICIPIO.NOMEMUNICIPIO
						,TMOV.DATAEMISSAO
						,TMOV.DATACRIACAO
						,TMOV.CODTMV
						,TMOV.CODIGOSERVICO
						,TMOV.VALORBRUTO
						,DTRBITEM.VALORTRB
						,DTRBITEM.CODTRB
						,TMOV.USUARIOCRIACAO
						,LAMGUIA.STATUSLAN
						,DGUIAPERIODO.VALORAPURADO
						,DGUIAPERIODO.DESCRICAO
						,DGUIAPERIODO.CODRECEITA
						,DGUIAPERIODO.DATAVENC
						,DTRBITEM.IDLAF
						,DTRBITEM.IDGUIA

				UNION ALL
				/*SELECT PARA TRAZER OS LANÇAMENTOS QUE FORAM ESCRITURADOS E QUEM TEM IDGUIA PREENCHIDO NA DTRBLAF */
					SELECT 

						3 AS 'SQL',
							DTRBLAF.IDLAF,
				DTRBLAF.IDGUIA,
				TMOV.DATASAIDA,
				TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,DTRBLAF.CODTRB AS 'TRIBUTO'
				/*,DTRBITEM.CODTRB AS 'TRIBUTO'*/
				,FORMAT((DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				/*,FORMAT(SUM(DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'*/
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/ 
				,FORMAT(DGUIAPERIODO.VALORAPURADO, 'C', 'pt-BR') AS 'VALOR_GUIA'
				,(CASE	WHEN LAMGUIA.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN LAMGUIA.STATUSLAN = 1
							THEN 'Pago'
						WHEN LAMGUIA.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN LAMGUIA.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN LAMGUIA.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN LAMGUIA.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
				 END) AS 'STATUS_GUIA'

				,DGUIAPERIODO.DESCRICAO
				,DGUIAPERIODO.CODRECEITA
				,DGUIAPERIODO.DATAVENC

						FROM TMOV (NOLOCK)

							INNER JOIN DLAF				(NOLOCK) ON (TMOV.IDMOV = DLAF.IDMOV AND TMOV.CODCOLIGADA = DLAF.CODCOLIGADA)
							INNER JOIN DTRBLAF			(NOLOCK) ON (DTRBLAF.IDLAF = DLAF.IDLAF AND DTRBLAF.CODCOLIGADA = DLAF.CODCOLIGADA )
							--INNER JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV AND DTRBLAF.CODTRB = TTRBMOV.CODTRB) 
							INNER JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
							INNER JOIN DGUIAPERIODO		(NOLOCK) ON (DGUIAPERIODO.IDGUIA = DTRBLAF.IDGUIA AND DGUIAPERIODO.CODCOLIGADA = DTRBLAF.CODCOLIGADA)
					/*INNER JOIN DPERIODO			(NOLOCK) ON (DPERIODO.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA AND DPERIODO.IDPER = DGUIAPERIODO.IDPER)*/
					
							LEFT JOIN FLAN AS LAMGUIA	(NOLOCK) ON (LAMGUIA.IDGUIA = DGUIAPERIODO.IDGUIA AND LAMGUIA.CODCOLIGADA = DGUIAPERIODO.CODCOLIGADA)	

							WHERE

								TMOV.CODCOLIGADA IN (@COLIGADA)
								AND TMOV.CODTMV IN ('1.2.07', '1.2.08', '1.2.10', '1.2.33', '1.2.64')
								--AND TMOV.CODFILIAL IN (@FILIAL)
								AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
								AND DTRBLAF.CODTRB IN (@TRIBUTO)
								AND DTRBLAF.CODTRB NOT IN ('RTOTAL')
								AND DTRBLAF.VALORTRB >0
								AND DTRBLAF.IDGUIA IS NOT NULL
								--AND TMOV.IDMOV = @IDMOV
								--AND NOT EXISTS (SELECT 1 FROM DTRBITEM (NOLOCK) WHERE DTRBITEM.IDLAF = DLAF.IDLAF AND DTRBITEM.CODCOLIGADA = DLAF.CODCOLIGADA AND  DTRBITEM.CODTRB = DTRBLAF.CODTRB AND DTRBITEM.IDGUIA IS NOT NULL)

								/*and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/

							GROUP BY 	

						TMOV.DATASAIDA
						,TMOV.CODCOLIGADA
						,TMOV.CODFILIAL
						,TMOV.NUMEROMOV
						,TMOV.IDMOV
						,GMUNICIPIO.NOMEMUNICIPIO
						,TMOV.DATAEMISSAO
						,TMOV.DATACRIACAO
						,TMOV.CODTMV
						,TMOV.CODIGOSERVICO
						,TMOV.VALORBRUTO
						,DTRBLAF.VALORTRB
						,DTRBLAF.CODTRB
						,TMOV.USUARIOCRIACAO
						,LAMGUIA.STATUSLAN
						,DGUIAPERIODO.VALORAPURADO
						,DGUIAPERIODO.DESCRICAO
						,DGUIAPERIODO.CODRECEITA
						,DGUIAPERIODO.DATAVENC
						,DTRBLAF.IDLAF
						,DTRBLAF.IDGUIA

					) AS GRUPO2)

UNION ALL
/*SELECT PARA TRAZER LANÇAMENTOS ESCRITURADOS MAS QUE O IDGUIA SEJA NULO NA DTRBLAF E NA DTRBITEM*/
			SELECT 
				4 AS 'SQL'
				,NULL AS IDLAF
				,NULL AS IDGUIA
				,TMOV.DATASAIDA
				,TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,TTRBMOV.CODTRB AS 'TRIBUTO'
				/*,DPERIODO.CODTRB AS 'TRIBUTO'*/
				,FORMAT((TTRBMOV.VALOR), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				/*,FORMAT(SUM(DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'*/
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/
				,NULL AS 'VALOR_GUIA'
				,(SELECT TOP 1 (CASE	WHEN FLAN.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN FLAN.STATUSLAN = 1
							THEN 'Pago'
						WHEN FLAN.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN FLAN.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN FLAN.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN FLAN.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
						END) 
						FROM FLAN 
						WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA
						AND FLAN.STATUSLAN IS NOT NULL
						ORDER BY 1 ) AS 'STATUS_GUIA'
				,NULL AS DESCRICAO
				,NULL AS CODRECEITA
				,NULL AS DATAVENC

				FROM TMOV (NOLOCK)		

					LEFT JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV) 
					INNER JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
					LEFT JOIN FLAN				(NOLOCK) ON (FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA)

				WHERE

					TMOV.CODCOLIGADA IN (@COLIGADA)
					AND TMOV.CODTMV IN ('1.2.07', '1.2.08', '1.2.10', '1.2.33', '1.2.64')
					--AND TMOV.CODFILIAL IN (@FILIAL)
					AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
					AND TTRBMOV.CODTRB IN (@TRIBUTO)
					AND TTRBMOV.CODTRB NOT IN ('RTOTAL')
					AND TTRBMOV.VALOR >0
					--AND TMOV.IDMOV = @IDMOV
					--AND (TMOV.CODLAF IS NULL AND TMOV.CODLAFE IS NULL)
					AND EXISTS(
					SELECT 1 FROM 
					 DLAF	
					 LEFT JOIN DTRBLAF	(NOLOCK) ON (DTRBLAF.IDLAF = DLAF.IDLAF AND DTRBLAF.CODCOLIGADA = DLAF.CODCOLIGADA AND DTRBLAF.CODTRB = TTRBMOV.CODTRB)
					 LEFT JOIN DITEM	(NOLOCK) ON (DITEM.IDLAF = DLAF.IDLAF AND DITEM.CODCOLIGADA = DLAF.CODCOLIGADA)
					 LEFT JOIN DTRBITEM	(NOLOCK) ON (DTRBITEM.CODCOLIGADA = DITEM.CODCOLIGADA AND DTRBITEM.IDLAF = DITEM.IDLAF AND DTRBITEM.NUMITEM = DITEM.NUMITEM AND TTRBMOV.CODTRB = DTRBITEM.CODTRB)

					 WHERE TMOV.IDMOV = DLAF.IDMOV AND TMOV.CODCOLIGADA = DLAF.CODCOLIGADA
					 AND DTRBITEM.IDGUIA IS NULL AND DTRBLAF.IDGUIA IS NULL)
					/*and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/

				GROUP BY 	

					TMOV.DATASAIDA
					,TMOV.CODCOLIGADA
					,TMOV.CODFILIAL
					,TMOV.NUMEROMOV
					,TMOV.IDMOV
					,GMUNICIPIO.NOMEMUNICIPIO
					,TMOV.DATAEMISSAO
					,TMOV.DATACRIACAO
					,TMOV.CODTMV
					,TMOV.CODIGOSERVICO
					,TMOV.VALORBRUTO
					,TTRBMOV.VALOR
					,TTRBMOV.CODTRB
					,TMOV.USUARIOCRIACAO

UNION ALL
/*SELECT PARA TRAZER LANÇAMENTOS NÃO ESCRITURADOS*/
SELECT 
				5 AS 'SQL'
				,NULL AS IDLAF
				,NULL AS IDGUIA
				,TMOV.DATASAIDA
				,TMOV.CODCOLIGADA
				,TMOV.CODFILIAL
				,TMOV.NUMEROMOV
				,TMOV.IDMOV
				,GMUNICIPIO.NOMEMUNICIPIO
				,TMOV.DATAEMISSAO
				,TMOV.DATACRIACAO
				,TMOV.CODTMV
				,TMOV.CODIGOSERVICO
				,FORMAT(TMOV.VALORBRUTO, 'C', 'pt-BR') AS 'VALOR_BRUTO'
				,TTRBMOV.CODTRB AS 'TRIBUTO'
				/*,DPERIODO.CODTRB AS 'TRIBUTO'*/
				,FORMAT((TTRBMOV.VALOR), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'
				/*,FORMAT(SUM(DTRBLAF.VALORTRB), 'C', 'pt-BR') AS 'VALOR_TRIBUTO'*/
				,TMOV.USUARIOCRIACAO 
				,(SELECT  MIN(DATABAIXA) FROM FLAN (NOLOCK) WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA) AS 'BAIXA_LANÇAMENTO_MOV'  /*A PEDIDO DA BARBARA PIMENTA, SEMPRE MOSTRAR O PRIMEIRO LANÇAMENTO GERADO*/
				,NULL AS 'VALOR_GUIA'
				,(SELECT TOP 1 (CASE	WHEN FLAN.STATUSLAN = 0
							THEN 'Em aberto'
						WHEN FLAN.STATUSLAN = 1
							THEN 'Pago'
						WHEN FLAN.STATUSLAN = 2
							THEN 'Cancelado'
						WHEN FLAN.STATUSLAN = 3
							THEN 'Baixado por Acordo'
						WHEN FLAN.STATUSLAN = 4
							THEN 'Baixado Parceialmente'
						WHEN FLAN.STATUSLAN = 5
							THEN 'Borderô'
						ELSE CONVERT(VARCHAR,'Parcialmente em aberto')
						END) 
						FROM FLAN 
						WHERE FLAN.IDMOV = TMOV.IDMOV AND FLAN.CODCOLIGADA = TMOV.CODCOLIGADA
						AND FLAN.STATUSLAN IS NOT NULL
						ORDER BY 1 ) AS 'STATUS_GUIA'
				,NULL AS DESCRICAO
				,NULL AS CODRECEITA
				,NULL AS DATAVENC

				FROM TMOV (NOLOCK)		

					LEFT JOIN TTRBMOV			(NOLOCK) ON (TMOV.CODCOLIGADA = TTRBMOV.CODCOLIGADA AND TMOV.IDMOV = TTRBMOV.IDMOV) 
					INNER JOIN GMUNICIPIO		(NOLOCK) ON (TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO)
					/*LEFT JOIN FLAN				(NOLOCK) ON */

				WHERE

					TMOV.CODCOLIGADA IN (@COLIGADA)
					AND TMOV.CODTMV IN ('1.2.07', '1.2.08', '1.2.10', '1.2.33', '1.2.64')
					--AND TMOV.CODFILIAL IN (@FILIAL)
					AND TMOV.DATASAIDA BETWEEN @DATAINI AND @DATAFIN
					AND TTRBMOV.CODTRB IN (@TRIBUTO)
					AND TTRBMOV.CODTRB NOT IN ('RTOTAL')
					AND TTRBMOV.VALOR >0

					--AND TMOV.IDMOV = @IDMOV
					AND TMOV.CODLAFE IS NULL
					
					/*and tmov.idmov in (2149607,2151036,2150271,2151332,2151298,2151334)*/

				GROUP BY 	

					TMOV.DATASAIDA
					,TMOV.CODCOLIGADA
					,TMOV.CODFILIAL
					,TMOV.NUMEROMOV
					,TMOV.IDMOV
					,GMUNICIPIO.NOMEMUNICIPIO
					,TMOV.DATAEMISSAO
					,TMOV.DATACRIACAO
					,TMOV.CODTMV
					,TMOV.CODIGOSERVICO
					,TMOV.VALORBRUTO
					,TTRBMOV.VALOR
					,TTRBMOV.CODTRB
					,TMOV.USUARIOCRIACAO



) AS GRUPO

WHERE GRUPO.TRIBUTO IN(@TRIBUTO)
--AND STATUS_GUIA <> 'Nulo'

GROUP BY 
GRUPO.SQL
,GRUPO.DATASAIDA
,GRUPO.CODCOLIGADA
,GRUPO.CODFILIAL
,GRUPO.NUMEROMOV
,GRUPO.IDMOV
,GRUPO.NOMEMUNICIPIO
,GRUPO.DATAEMISSAO
,GRUPO.DATACRIACAO
,GRUPO.CODTMV
,GRUPO.CODIGOSERVICO
,GRUPO.VALOR_BRUTO
,GRUPO.TRIBUTO
,GRUPO.USUARIOCRIACAO
,GRUPO.BAIXA_LANÇAMENTO_MOV
,GRUPO.VALOR_TRIBUTO
,GRUPO.STATUS_GUIA
,GRUPO.VALOR_GUIA
,GRUPO.DESCRICAO
,GRUPO.CODRECEITA
,GRUPO.DATAVENC
,GRUPO.IDLAF
,GRUPO.IDGUIA
 
ORDER BY

GRUPO.CODCOLIGADA
,GRUPO.CODFILIAL
,GRUPO.IDMOV



