/*DECLARE @DATA_MOVIMENTO_INICIAL DATE = '20240101',
		@DATA_MOVIMENTO_FINAL DATE = '20241011',
		@CODCOLIGADA INT = 51,
		@CODFILIAL INT = 2;*/



SELECT 
(CONVERT(DECIMAL(10,2),GRUPO.CSRF_VALOR) + CONVERT(DECIMAL(10,2),GRUPO.COFRF_VALOR) + CONVERT(DECIMAL(10,4),GRUPO.PISRF_VALOR)) AS 'SOMA RTOTAL',
grupo.*
FROM	
(
SELECT 
TMOV.IDMOV --
,GFILIAL.CODFILIAL --
,TMOV.CODCOLIGADA --
,GFILIAL.NOMEFANTASIA --
,TMOV.CODTMV --
,TMOV.NUMEROMOV --
,GCCUSTO.CODCCUSTO --
,GCCUSTO.NOME AS 'CENTRO_DE_CUSTO' --
,TMOV.VALORBRUTO --
,FLAN.DATABAIXA --
,FLAN.DATAPAG --
,FLAN.VALORBAIXADO AS VR_BAIXA --
,TMOV.CODIGOSERVICO --
,TMOV.DATAEMISSAO --
,TMOV.DATACRIACAO AS 'DT_CRIACAO' --
,CONVERT(VARCHAR,TMOV.DATASAIDA,103) AS 'DATA_DE_CRIACAO' --
,CONVERT(VARCHAR,TMOV.DATAEMISSAO,103) AS 'DATA_DE_EMISSAO' --
,FCFO.CGCCFO AS 'CNPJ' --
,FCFO.NOME --
,ISNULL( CONVERT(VARCHAR(MAX),TMOVHISTORICO.HISTORICOLONGO),CONVERT(VARCHAR(MAX),TMOVHISTORICO.HISTORICOCURTO))AS 'HISTORICO' --
,TMOV.CODTDO --
,TMOV.CODTB5FAT + ' - ' + TTB5.DESCRICAO AS SITUACAO_FORNECEDOR --


,(
	SELECT TOP 1 CONVERT(VARCHAR,DESTINO.RECCREATEDON,103) FROM TMOVRELAC (NOLOCK)
	LEFT JOIN	TMOV DESTINO (NOLOCK) ON (DESTINO.IDMOV = TMOVRELAC.IDMOVDESTINO AND DESTINO.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
	WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA
) AS 'DATA_CRIACAO'
 
,CONVERT(VARCHAR,TMOV.DATAMOVIMENTO,103) AS DATA_RECEBIMENTO

,TMOV.RECCREATEDBY AS 'USUARIO_CRIOU_MOVIMENTO'

,CONCAT(TMOV.CODTDO,'  ',FTDO.DESCRICAO) AS 'TIPO_DE_DOCUMENTO'

,(
	SELECT ISNULL(SUM(INSSRETIDO.VALOR),0) 		
	FROM TTRBMOV AS INSSRETIDO (NOLOCK)
	WHERE TMOV.IDMOV = INSSRETIDO.IDMOV 
	AND TMOV.CODCOLIGADA = INSSRETIDO.CODCOLIGADA 
	AND INSSRETIDO.CODTRB = 'INSS'
) AS 'INSS_RETIDO'
 
,(
	SELECT ISNULL(SUM(IRRFPJRETIDO.VALOR),0) 		
	FROM TTRBMOV AS IRRFPJRETIDO (NOLOCK)
	WHERE TMOV.IDMOV = IRRFPJRETIDO.IDMOV 
	AND TMOV.CODCOLIGADA = IRRFPJRETIDO.CODCOLIGADA 
	AND IRRFPJRETIDO.CODTRB = 'IRRFPJ'
) AS 'IRRFPJ_RETIDO'
  
,(
	SELECT ISNULL(SUM(IRRFPJ.VALOR),0)
	FROM TTRBMOV IRRFPJ (NOLOCK)
	WHERE TMOV.IDMOV = IRRFPJ.IDMOV 
	AND TMOV.CODCOLIGADA = IRRFPJ.CODCOLIGADA 
	AND IRRFPJ.CODTRB = 'CSRF'
) AS 'CSRF_RETIDO'
 
/*COD RETENCAO DO IMPOSTO*/
/*,(SELECT TOP 1 CODRETENCAO 
FROM TTRBMOV AS TRB_IRRFPJ
WHERE NSEQITMMOV > 0 
AND CODTRB = 'IRRFPJ' 
AND TRB_IRRFPJ.CODCOLIGADA = TMOV.CODCOLIGADA
AND TRB_IRRFPJ.IDMOV = TMOV.IDMOV) AS 'CODRETENCAO_IRRFPJ'

,(SELECT TOP 1 CODRETENCAO 
FROM TTRBMOV AS TRB_RTOTAL
WHERE NSEQITMMOV > 0 
AND CODTRB = 'RTOTAL' 
AND TRB_RTOTAL.CODCOLIGADA = TMOV.CODCOLIGADA
AND TRB_RTOTAL.IDMOV = TMOV.IDMOV) AS 'CODRETENCAO_RTOTAL'
 
 ,CASE 
    WHEN CAST(TMOVCOMPL.CNO2 AS VARCHAR) = '1' THEN 'MARCADO'
    ELSE 'NÃO MARCADO'
END AS 'CONFERENCIA_CNO'*/,

(
	SELECT ISNULL (SUM(VALORIRRFPJ.VALOR),0)
	FROM TTRBMOV AS VALORIRRFPJ (NOLOCK)
	WHERE TMOV.IDMOV = VALORIRRFPJ.IDMOV 
	AND TMOV.CODCOLIGADA = VALORIRRFPJ.CODCOLIGADA 
	AND VALORIRRFPJ.CODTRB = 'IRRFPJ'
	AND CODRETENCAO = '1708'
) AS 'IRRFPJ_VALOR_1708',

(
	SELECT ISNULL (SUM(VALORIRRFPJ.VALOR),0)
	FROM TTRBMOV AS VALORIRRFPJ (NOLOCK)
	WHERE TMOV.IDMOV = VALORIRRFPJ.IDMOV 
	AND TMOV.CODCOLIGADA = VALORIRRFPJ.CODCOLIGADA 
	AND VALORIRRFPJ.CODTRB = 'IRRFPJ'
	AND CODRETENCAO = '3208'
) AS 'IRRFPJ_VALOR_3208',

(
	SELECT ISNULL (SUM(VALORIRRFPJ.VALOR),0)
	FROM TTRBMOV AS VALORIRRFPJ (NOLOCK)
	WHERE TMOV.IDMOV = VALORIRRFPJ.IDMOV 
	AND TMOV.CODCOLIGADA = VALORIRRFPJ.CODCOLIGADA 
	AND VALORIRRFPJ.CODTRB = 'IRRFPJ'
	AND CODRETENCAO = '5952'
) AS 'IRRFPJ_VALOR_5952',

(
	SELECT ISNULL (SUM(VALORIRRFPJ.VALOR),0)
	FROM TTRBMOV AS VALORIRRFPJ (NOLOCK)
	WHERE TMOV.IDMOV = VALORIRRFPJ.IDMOV 
	AND TMOV.CODCOLIGADA = VALORIRRFPJ.CODCOLIGADA 
	AND VALORIRRFPJ.CODTRB = 'IRRFPJ'
	AND CODRETENCAO = '8045'
) AS 'IRRFPJ_VALOR_8045',

(
	SELECT ISNULL (SUM(VALORISSQN.VALOR),0)
	FROM TTRBMOV AS VALORISSQN (NOLOCK)
	WHERE TMOV.IDMOV = VALORISSQN.IDMOV 
	AND TMOV.CODCOLIGADA = VALORISSQN.CODCOLIGADA 
	AND VALORISSQN.CODTRB = 'ISS'
) AS 'ISSQN_VALOR',

/* INSS */
(
	SELECT ISNULL(SUM(INSSVALOR.VALOR),0)
	FROM TTRBMOV AS INSSVALOR (NOLOCK)
	WHERE TMOV.IDMOV = INSSVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = INSSVALOR.CODCOLIGADA 
	AND INSSVALOR.CODTRB = 'INSS'
) AS 'INSS_VALOR',

/* ISS */

(
	SELECT ISNULL(SUM(ISSVALOR.VALOR),0)
	FROM TTRBMOV AS ISSVALOR (NOLOCK)
	WHERE TMOV.IDMOV = ISSVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = ISSVALOR.CODCOLIGADA 
	AND ISSVALOR.CODTRB = 'ISS'
) AS 'ISS_VALOR',

/* IMPOSTOS RTOTAL */
 (
	SELECT ISNULL(SUM(CSRFVALOR.VALOR),0)
	FROM TTRBMOV AS CSRFVALOR (NOLOCK)
	WHERE TMOV.IDMOV = CSRFVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = CSRFVALOR.CODCOLIGADA 
	AND CSRFVALOR.CODTRB = 'CSRF'
) AS 'CSRF_VALOR',

 (
	SELECT ISNULL(SUM(COFRFVALOR.VALOR),0)
	FROM TTRBMOV AS COFRFVALOR (NOLOCK)
	WHERE TMOV.IDMOV = COFRFVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = COFRFVALOR.CODCOLIGADA 
	AND COFRFVALOR.CODTRB = 'COFRF'
) AS 'COFRF_VALOR',

(
	SELECT ISNULL(SUM(PISRFVALOR.VALOR),0)
	FROM TTRBMOV PISRFVALOR(NOLOCK)
	WHERE TMOV.IDMOV = PISRFVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = PISRFVALOR.CODCOLIGADA 
	AND PISRFVALOR.CODTRB = 'PISRF'
) AS 'PISRF_VALOR',

	(SELECT ISNULL(SUM(RTOTALVALOR.VALOR),0)
	FROM TTRBMOV RTOTALVALOR(NOLOCK)
	WHERE TMOV.IDMOV = RTOTALVALOR.IDMOV 
	AND TMOV.CODCOLIGADA = RTOTALVALOR.CODCOLIGADA 
	AND RTOTALVALOR.CODTRB = 'RTOTAL'
) AS 'RTOTAL_VALOR'
 
 /* FIM DE IMPOSTOS RTOTAL */

/* JOIN IMPOSTOS FEDERAIS */ 
 
FROM TTRBMOV								(NOLOCK)
LEFT JOIN TMOV								(NOLOCK) ON (TMOV.IDMOV = TTRBMOV.IDMOV AND TMOV.CODCOLIGADA  = TTRBMOV.CODCOLIGADA)
LEFT JOIN TITMMOV							(NOLOCK) ON (TTRBMOV.IDMOV = TITMMOV.IDMOV AND TTRBMOV.CODCOLIGADA  = TITMMOV.CODCOLIGADA AND TITMMOV.NSEQITMMOV = TTRBMOV.NSEQITMMOV )
LEFT JOIN FLAN								(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FCFO								(NOLOCK) ON (TMOV.CODCFO = FCFO.CODCFO AND TMOV.CODCOLCFO = FCFO.CODCOLIGADA)
LEFT JOIN GFILIAL							(NOLOCK) ON (GFILIAL.CODFILIAL = TMOV.CODFILIAL AND GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN TMOVHISTORICO						(NOLOCK) ON (TMOV.IDMOV = TMOVHISTORICO.IDMOV AND TMOV.CODCOLIGADA = TMOVHISTORICO.CODCOLIGADA)
LEFT JOIN TTB5								(NOLOCK) ON (TMOV.CODTB5FAT = TTB5.CODTB5FAT AND TTB5.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN FTDO								(NOLOCK) ON (TMOV.CODTDO = FTDO.CODTDO AND TMOV.CODCOLIGADA = FTDO.CODCOLIGADA)
INNER JOIN TMOVCOMPL						(NOLOCK) ON	(TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA AND TMOV.IDMOV = TMOVCOMPL.IDMOV)

/* JOIN IMPOSTOS MUNICIPAIS */ 

LEFT JOIN GMUNICIPIO						(NOLOCK) ON TMOV.CODMUNSERVICO = GMUNICIPIO.CODMUNICIPIO AND TMOV.CODETDMUNSERV = GMUNICIPIO.CODETDMUNICIPIO
LEFT JOIN GETD								(NOLOCK) ON TMOV.CODETDMUNSERV = GETD.CODETD
LEFT JOIN GCCUSTO							(NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN GMUNICIPIO AS FCFO_MUNICIPIO		(NOLOCK) ON FCFO_MUNICIPIO.CODMUNICIPIO = FCFO.CODMUNICIPIO AND FCFO_MUNICIPIO.CODETDMUNICIPIO = FCFO.CODETD
LEFT JOIN GETD AS FCFO_ESTADO				(NOLOCK) ON (FCFO_ESTADO.CODETD = FCFO.CODETD)

 
 
 
WHERE TMOV.STATUS <> 'C'
AND TMOV.CODCOLIGADA IN (@CODCOLIGADA)
AND TMOV.CODFILIAL IN (@CODFILIAL)
AND TMOV.DATACRIACAO BETWEEN @DATA_MOVIMENTO_INICIAL AND @DATA_MOVIMENTO_FINAL
AND (TMOV.CODTMV IN ('1.2.07','1.2.08','1.2.10','1.2.17','1.2.33','1.2.64') OR (TMOV.CODTMV = '1.2.63' AND TMOV.CODTDO = 9998 ) OR (TMOV.CODTMV = '1.2.04' AND TMOV.CODTDO = 67))
 
) AS GRUPO
 
 
/*WHERE GRUPO.DATAEMISSAO BETWEEN @DATA_MOVIMENTO_INICIAL AND @DATA_MOVIMENTO_FINAL*/


 
 
GROUP BY
GRUPO.IDMOV
,GRUPO.CODCOLIGADA
,GRUPO.CODFILIAL
,GRUPO.NOMEFANTASIA
,GRUPO.CODTMV
,GRUPO.NUMEROMOV
,GRUPO.CODIGOSERVICO

,GRUPO.DATA_CRIACAO
,GRUPO.DATA_RECEBIMENTO
,GRUPO.VALORBRUTO
,GRUPO.DATABAIXA
,GRUPO.VR_BAIXA
,GRUPO.INSS_RETIDO
,GRUPO.IRRFPJ_RETIDO
,GRUPO.CNPJ
,GRUPO.NOME
,GRUPO.HISTORICO

,GRUPO.DATA_DE_CRIACAO
,GRUPO.DATA_DE_EMISSAO
,GRUPO.DT_CRIACAO
,GRUPO.SITUACAO_FORNECEDOR
,GRUPO.USUARIO_CRIOU_MOVIMENTO 

,GRUPO.DATAPAG
,GRUPO.TIPO_DE_DOCUMENTO

,GRUPO.CODCCUSTO
,CENTRO_DE_CUSTO
,GRUPO.DATAEMISSAO
,GRUPO.CODTDO

,GRUPO.CSRF_RETIDO
,ISSQN_VALOR
,GRUPO.CSRF_VALOR
,GRUPO.COFRF_VALOR
,GRUPO.PISRF_VALOR
,GRUPO.INSS_VALOR
,GRUPO.ISS_VALOR
,GRUPO.RTOTAL_VALOR
,GRUPO.IRRFPJ_VALOR_1708
,GRUPO.IRRFPJ_VALOR_3208
,GRUPO.IRRFPJ_VALOR_5952
,GRUPO.IRRFPJ_VALOR_8045

ORDER BY GRUPO.CODCOLIGADA, 
GRUPO.CODFILIAL, 
GRUPO.IDMOV