SELECT DISTINCT
TUSRTMV.CODCOLIGADA, 
TUSRTMV.CODUSUARIO, 
TUSRTMV.CODTMV,
--CODPERFIL
(CASE WHEN CONSULTAR = 1 THEN 'PODE CONSULTAR' ELSE 'NÃO PODE' END) CONSULTAR,
(CASE WHEN ALTERAR = 1 THEN 'PODE ALTERAR' ELSE 'NÃO PODE' END) ALTERAR,
(CASE WHEN INCLUIR = 1 THEN 'PODE INCLUIR' ELSE 'NÃO PODE' END) INCLUIR,
(CASE WHEN EXCLUIR = 1 THEN 'PODE EXCLUIR' ELSE 'NÃO PODE' END) EXCLUIR,
(CASE WHEN ATIVAR = 1 THEN 'PODE ATIVAR' ELSE 'NÃO PODE' END) ATIVAR_INATIVAR,
(CASE WHEN ALTERARDEPOISEMAIL = 1 THEN 'PODE ALTERAR DEPOIS DE EMAIL' ELSE 'NÃO PODE' END) ALTERAR_DEPOIS_DO_EMAIL,
(CASE WHEN CANCELAR = 1 THEN 'PODE CANCELAR' ELSE 'NÃO PODE' END) CANCELAR,
(CASE WHEN REABRIR = 1 THEN 'PODE REABRIR' ELSE 'NÃO PODE' END) REABRIR,
(CASE WHEN ALTERARDEPOISIMP = 1 THEN 'PODE ALTERAR DEPOIS DE IMPRIMIR' ELSE 'NÃO PODE' END) ALTERAR_DEPOIS_DO_IMPRIMIR,
(CASE WHEN ALTERARITEMINTEGRADO = 1 THEN 'PODE ALTERAR ITEM INTEGRADO' ELSE 'NÃO PODE' END) ALTERAR_ITEM_INTEGRADO,
(CASE WHEN IMPRIMIR = 1 THEN 'PODE IMPRIMIR' ELSE 'NÃO PODE' END) IMPRIMIR,
(CASE WHEN COPIAR = 1 THEN 'PODE COPIAR' ELSE 'NÃO PODE' END) COPIAR,
(CASE WHEN TUSRTMV.EMAIL = 1 THEN 'PODE ENVIAR EMAIL' ELSE 'NÃO PODE' END) ENVIAR_EMAIL,
(CASE WHEN GERACONTRATO = 1 THEN 'PODE GERACONTRATO' ELSE 'NÃO PODE' END) GERAR_CONTRATO,
(CASE WHEN LANCAR = 1 THEN 'PODE LANCAR' ELSE 'NÃO PODE' END) LANCAR,
(CASE WHEN FATURAR = 1 THEN 'PODE FATURAR' ELSE 'NÃO PODE' END) FATURAR,
(CASE WHEN COTAR = 1 THEN 'PODE COTAR' ELSE 'NÃO PODE' END) COTAR,
(CASE WHEN CONTABILIZAR = 1 THEN 'PODE CONTABILIZAR' ELSE 'NÃO PODE' END) CONTABILIZAR, 
(CASE WHEN ESTORNARCONTAB = 1 THEN 'PODE ESTORNAR PARA A CONTABILIDADE' ELSE 'NÃO PODE' END) ESTORNAR_CONTABILIDADE, 
(CASE WHEN INCLUIRPORFAT = 1 THEN 'PODE INCLUIR POR FATURAMENTO' ELSE 'NÃO PODE' END) INCLUIR_POR_FATURAMENTO

FROM GUSRPERFIL 
LEFT JOIN TUSRTMV					(NOLOCK)			ON (TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO					(NOLOCK)			ON (GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
LEFT JOIN PFUNC						(NOLOCK)			ON (PFUNC.NOME = GUSUARIO.NOME)

WHERE CODSISTEMA = 'T'    
AND CODTMV = '1.1.80'
AND PFUNC.CODSITUACAO <>  'D'
AND PFUNC.CODSECAO NOT IN ('01.500.20', '01.500.11', '01.500.74')
-- IN (SELECT NOME FROM PFUNC WHERE CODSECAO NOT IN ('01.500.20','01.500.21','01.500.91') AND CODSITUACAO <> 'D')   


--BEGIN TRAN
--UPDATE
