SELECT
(
	SELECT TOP 1 NUMEROCHEQUE 
	FROM FLANBAIXA (NOLOCK) 
	WHERE FLANBAIXA.IDLAN = FLAN.IDLAN
	AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA
) AS NUMEROCHEQUE,



(CASE WHEN DBO.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA,FLAN.IDLAN,FLAN.CODCCUSTO) IS NULL
	OR DBO.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA,FLAN.IDLAN,FLAN.CODCCUSTO) > '0'
	THEN DBO.VALOR_LIQUIDO_FLUXUS_SEM_RATEIO(FLAN.CODCOLIGADA, FLAN.IDLAN) 
	ELSE CAST(DBO.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA,FLAN.IDLAN,FLAN.CODCCUSTO)AS MONEY) 
END)  

/*VINCULOS DE ADIANTAMENTO*/
-

ISNULL((SELECT SUM(FRELLAN.VALORVINCULO) FROM FRELLAN (NOLOCK)
INNER JOIN FLAN AS F (NOLOCK)  ON (F.IDLAN = FRELLAN.IDLAN AND F.CODCOLIGADA = FRELLAN.CODCOLIGADA)
WHERE FRELLAN.IDLANREL = FLAN.IDLAN AND FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA
AND FRELLAN.TIPOREL = 28
AND F.STATUSLAN <> 2),0)

AS 'VALOR LIQUIDO',


DBO.TRAZ_STATUSLAN(FLAN.STATUSLAN) AS 'Imagem - Status',
FLAN.CODCOLIGADA AS 'Coligada da Conta/Caixa',
FLAN.CODCXA AS 'Conta/Caixa',
FTDO.DESCRICAO AS 'Classificação',
FLAN.IDLAN 'Ref. Lançamento',
GCCUSTO.NOME AS 'Descrição Centro de Custo',
FTB2.CODTB2FLX AS 'Classif. Financeira',
FCFO.NOME AS 'Nome',
FCFO.NOMEFANTASIA AS 'Nome Fantasia',
FCFO.CGCCFO AS 'CNPJ/CPF',
FLAN.NUMERODOCUMENTO AS 'Número do Documento',
CONVERT(VARCHAR,FLAN.DATAEMISSAO,103) AS 'Data de Emissão',
FLAN.DATACRIACAO AS 'Dt_Lanc_Criado',
CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS 'Data de Vencimento',
FLAN.VALORORIGINAL AS 'Valor Original',

CONVERT(VARCHAR,FLAN.DATAPAG,103) AS 'Data de Pagamento',
FLAN.RECMODIFIEDBY AS 'Usuário de Alteração',
CONVERT(VARCHAR,FLAN.DATAALTERACAO,103) AS 'Data de Alteração',
FLAN.RECCREATEDBY AS 'Usuário de Criação',
CONVERT(VARCHAR,TMOV.RECCREATEDON,103) AS 'Data de Criação',
FLAN.VALORBAIXADO 'Valor Baixado',
CONVERT(VARCHAR,FLAN.DATABAIXA,103) AS 'Data de baixa',
GCCUSTO.CODCCUSTO 'Centro de Custo',
FCXA.DESCRICAO AS 'Descrição Conta/Caixa',
FTB2.DESCRICAO AS 'Nome Class. Financeira',
FCXA.CODMOEDA as 'Moeda',
FLAN.VALORORIGINAL AS 'Original Baixa',
CONVERT(VARCHAR,FLAN.DATACRIAÇÃO,103) AS 'Data Entrada',
FTDO.CODTDO + ' - ' + FTDO.DESCRICAO AS 'Tipo de Documento',
(CASE WHEN TMOVHISTORICO.HISTORICOCURTO IS NULL THEN TMOVHISTORICO.HISTORICOLONGO ELSE '' END) AS HISTORICO,
'BANCO: ' + FDADOSPGTO.NUMEROBANCO + ' / AGENCIA: ' + FDADOSPGTO.CODIGOAGENCIA + ' CONTA: ' + FDADOSPGTO.CONTACORRENTE AS 'DADOS BANCARIOS',
(
	CASE FLAN.TIPOCONTABILLAN 
	WHEN 0 THEN 'NÃO CONTÁBIL' 
	WHEN 1 THEN 'CONTÁBIL' 
	WHEN 2 THEN 'BAIXA CONTÁBIL' 
	WHEN 1 THEN 'A CONTABILIZAR'
	ELSE '' 
	END
) AS 'STATUS CONTÁBIL DA BAIXA',
FLAN.VALOROP4 AS 'AJUSTE A MAIOR',

/*INSERIDO SEM RDA AUTORIZADO PELO MARCELO A PEDIDO DO JULIO LAMPERT*/
GSISTEMA.DESCRICAO AS 'APLICAÇÃO GERADORA',

/*INSERIDO POR MARCELO WAGNER DIA 19-01-2023 A PEDIDO DE JULIO LAMPERT E JANAINA SOBRINHO*/



ISNULL((SELECT SUM(FRELLAN.VALORVINCULO) FROM FRELLAN (NOLOCK)
INNER JOIN FLAN AS F (NOLOCK)  ON (F.IDLAN = FRELLAN.IDLAN AND F.CODCOLIGADA = FRELLAN.CODCOLIGADA)
WHERE FRELLAN.IDLANREL = FLAN.IDLAN AND FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA
AND FRELLAN.TIPOREL = 28
AND F.STATUSLAN <> 2),0) AS VALOR_VINCULO,


(SELECT 
TOP 1 FCFOCONT.CODCONTA  
FROM FCFOCONT (NOLOCK) 
WHERE FCFO.CODCFO = FCFOCONT.CODCFO 
AND FCFO.CODCOLIGADA = FCFOCONT.CODCOLCFO 
AND FLAN.CODCOLIGADA = FCFOCONT.CODCOLIGADA 
AND FCFOCONT.PAGREC = 2 
AND FCFOCONT.TIPO = 1) AS CONTA_DEBITO_FORNECEDOR,


(SELECT 
TOP 1 CCONTA.DESCRICAO
FROM FCFOCONT (NOLOCK) 
INNER JOIN CCONTA (NOLOCK) ON (CCONTA.CODCONTA = FCFOCONT.CODCONTA AND CCONTA.CODCOLIGADA = FCFOCONT.CODCOLCONTA)
WHERE FCFO.CODCFO = FCFOCONT.CODCFO 
AND FCFO.CODCOLIGADA = FCFOCONT.CODCOLCFO 
AND FLAN.CODCOLIGADA = FCFOCONT.CODCOLIGADA 
AND FCFOCONT.PAGREC = 2 
AND FCFOCONT.TIPO = 1) AS DESCRICAO_CONTA

FROM FLAN (NOLOCK)
LEFT JOIN FDADOSPGTO	(NOLOCK) ON (FLAN.CODCOLPGTO = FDADOSPGTO.CODCOLIGADA AND FLAN.CODCOLCFO = FDADOSPGTO.CODCOLCFO AND FLAN.CODCFO = FDADOSPGTO.CODCFO AND FLAN.IDPGTO = FDADOSPGTO.IDPGTO)
LEFT JOIN FXCX			(NOLOCK) ON (FLAN.CODCOLXCX = FXCX.CODCOLIGADA AND FLAN.IDXCX = FXCX.IDXCX)
LEFT JOIN FCXA			(NOLOCK ) ON (FLAN.CODCOLCXA= FCXA.CODCOLIGADA AND FLAN.CODCXA = FCXA.CODCXA)
LEFT JOIN GCCUSTO		(NOLOCK) ON (FLAN.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND FLAN.CODCCUSTO = GCCUSTO.CODCCUSTO)
LEFT JOIN TFORMAPAGTO	(NOLOCK) ON (FLAN.CODCOLIGADA = TFORMAPAGTO.CODCOLIGADA AND FLAN.IDFORMAPAGTO = TFORMAPAGTO.IDFORMAPAGTO)
LEFT JOIN TMOVLAN		(NOLOCK) ON (FLAN.IDLAN = TMOVLAN.IDLAN AND FLAN.CODCOLIGADA = TMOVLAN.CODCOLIGADA)
LEFT JOIN TMOV			(NOLOCK) ON (FLAN.CODCOLIGADA = TMOV.CODCOLIGADA AND FLAN.IDMOV = TMOV.IDMOV)
LEFT JOIN TMOVHISTORICO (NOLOCK) ON (TMOVHISTORICO.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVHISTORICO.IDMOV = TMOV.IDMOV)
LEFT JOIN FCFO			(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
LEFT JOIN FTDO			(NOLOCK) ON (FLAN.CODCOLIGADA = FTDO.CODCOLIGADA AND FLAN.CODTDO = FTDO.CODTDO)
LEFT JOIN FTB2			(NOLOCK) ON (FLAN.CODCOLIGADA = FTB2.CODCOLIGADA AND FLAN.CODTB2FLX = FTB2.CODTB2FLX)
LEFT JOIN FTB5			(NOLOCK) ON (FLAN.CODCOLIGADA = FTB5.CODCOLIGADA AND FLAN.CODTB5FLX = FTB5.CODTB5FLX)
LEFT JOIN GCOLIGADA		(NOLOCK) ON (FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)

/*INSERIDO SEM RDA AUTORIZADO PELO MARCELO A PEDIDO DO JULIO LAMPERT*/
LEFT JOIN GSISTEMA		(NOLOCK) ON (FLAN.CODAPLICACAO = GSISTEMA.CODSISTEMA)

WHERE
FLAN.DATAVENCIMENTO BETWEEN @DATAINI AND @DATAFIM
AND (FCFO.CGCCFO IS NULL OR FCFO.CGCCFO LIKE @CNPJCPF)
AND FCFO.NOMEFANTASIA LIKE @NOMEFANTASIA
AND FLAN.CODCOLIGADA IN (@COLIGADA)
AND FLAN.PAGREC = 1
AND FTDO.CODTDO IN (@CODTDO)
AND FTB2.CODTB2FLX IN (@CODTB2FLX)
AND FLAN.STATUSLAN IN (@STATUS)
/*AND FLAN.NFOUDUP <> 2*/

ORDER BY FLAN.CODCOLIGADA, FLAN.CODFILIAL