/*DECLARE @CODCOLIGADA AS INT = 1,
		@DATAINICIO AS DATE = '20240101',
		@DATAFINAL AS DATE = '20250318';*/

DECLARE @COLIGADAS TABLE (CODCOLIGADA INT);

INSERT INTO @COLIGADAS (CODCOLIGADA)
SELECT CODCOLIGADA
FROM GCOLIGADA
WHERE (CODCOLIGADA = 1 OR CODCOLIGADA >= 9) AND CODCOLIGADA NOT IN (54, 61);

CREATE TABLE #Resultado_Secao (
    CODCOLIGADA INT,
	CODFILIAL INT,
	CHAPA VARCHAR(20),
    NOME_FUNCIONARIO VARCHAR(200),
	CPF VARCHAR(15),
	CODSITUACAO VARCHAR(1),
	CODSECAO VARCHAR(35),
	SECAO VARCHAR(200),
	CODFUNCAO VARCHAR(30),
	FUNCAO VARCHAR(200),
	CODSINDICATO VARCHAR(20),
	DATAADMISSAO DATETIME,
    SEÇÃO_ALTERADA VARCHAR(35),
	DT_MUDANCA DATETIME,
	MOTIVO VARCHAR(35)
);

INSERT INTO #Resultado_Secao (
    CODCOLIGADA,
	CODFILIAL,
	CHAPA,
	NOME_FUNCIONARIO,
	CPF,
	CODSITUACAO,
	CODSECAO,
    SECAO,
	CODFUNCAO,
    FUNCAO,
	CODSINDICATO,
	DATAADMISSAO,
	SEÇÃO_ALTERADA,
	DT_MUDANCA,
	MOTIVO
)

SELECT 
	PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CHAPA AS 'CHAPA',
	PPESSOA.NOME AS 'NOME_FUNC',
	PPESSOA.CPF,
	PFUNC.CODSITUACAO,
	PSECAO.CODIGO AS 'SECAO',
	PSECAO.DESCRICAO AS 'NOME_SECAO',
	PFUNC.CODFUNCAO 'FUNCAO_ATUAL',
	PFUNCAO.NOME AS 'NOME_FUNÇÃO_ATUAL',
	PFUNC.CODSINDICATO,
	PFUNC.DATAADMISSAO,
	PFHSTSEC.CODSECAO AS 'SEÇÃO_ALTERADA',
	PFHSTSEC.DTMUDANCA AS 'DTMUDANCA',
			(CASE 
			 WHEN PFHSTSEC.MOTIVO = 'AD' THEN 'ADMISSÃO' 
			 WHEN PFHSTSEC.MOTIVO = 'DC' THEN 'MOTIVO DESCONHECIDO' 
			 WHEN PFHSTSEC.MOTIVO = 'MF' THEN 'MUDANÇA FUNÇÃO' 
			 WHEN PFHSTSEC.MOTIVO = 'PM' THEN 'PROMOÇÃO' 
			 WHEN PFHSTSEC.MOTIVO = 'TR' THEN 'TRANSFERENCIA_FILIAIS' 
			 WHEN PFHSTSEC.MOTIVO = 'TS' THEN 'TRANSFERENCIA DE SEÇÃO' 
			 WHEN PFHSTSEC.MOTIVO = 'TO' THEN 'TRANSFERENCIA DE OBRAS' 
			 WHEN PFHSTSEC.MOTIVO = 'TC' THEN 'TRASNFERENCIA ENTRE COLIGADAS' 
			 WHEN PFHSTSEC.MOTIVO = 'RT' THEN 'RETORNO TRABALHO' 
			 WHEN PFHSTSEC.MOTIVO = 'LM' THEN 'LICENÇA MATERNIDADE' 
			 WHEN PFHSTSEC.MOTIVO = 'DM' THEN 'DEMISSÃO' 
			 WHEN PFHSTSEC.MOTIVO = 'EO' THEN 'ENCERRAMENTO DE OBRA' 
			 END) AS 'MUDANÇA_SEÇÃO'
		
		

		 FROM PFUNC (NOLOCK)
		 INNER JOIN PPESSOA			(NOLOCK) ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
		 INNER JOIN PSECAO			(NOLOCK) ON (PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
		 INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA)
		 INNER JOIN PFUNCAO			(NOLOCK) ON (PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO)
		 INNER JOIN PFUNCAO FUNCAO	(NOLOCK) ON (FUNCAO.CODIGO = PFUNC.CODFUNCAO AND FUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
		 INNER JOIN PFHSTSEC		(NOLOCK) ON (PFHSTSEC.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFHSTSEC.CHAPA = PFUNC.CHAPA)
		 WHERE
		 PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
		 AND PFHSTSEC.DTMUDANCA BETWEEN @DATAINICIO AND @DATAFINAL
		 AND PFUNC.CODSITUACAO NOT IN ('L')
		 AND PFUNC.CODTIPO NOT IN ('A','O','C','D','U','E')
		 /*AND PFUNC.NOME LIKE '%BENNY%'*/
		 AND PFHSTSEC.MOTIVO NOT IN ('AD','MF', 'PM', 'RT', 'LM', 'DM')


	GROUP BY 
	PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CHAPA,
	PPESSOA.NOME,
	PPESSOA.CPF,
	PFUNC.CODSITUACAO,
	PSECAO.CODIGO,
	PSECAO.DESCRICAO,
	PFUNC.CODFUNCAO,
	PFUNCAO.NOME,
	PFUNC.CODSINDICATO,
	PFUNC.DATAADMISSAO,
	PFUNC.SALARIO,
	PFUNC.NOME,
	PFHSTSEC.CODSECAO,
	PFHSTSEC.MOTIVO,
	PFHSTSEC.DTMUDANCA
ORDER BY 1, 2

	
SELECT * FROM #Resultado_Secao;

DROP TABLE #Resultado_Secao;