DECLARE @COLIGADAS TABLE (CODCOLIGADA INT);

INSERT INTO @COLIGADAS (CODCOLIGADA)
SELECT CODCOLIGADA
FROM GCOLIGADA
WHERE (CODCOLIGADA = 1 OR CODCOLIGADA >= 9) AND CODCOLIGADA NOT IN (54, 61);

CREATE TABLE #Resultado (
    CODCOLIGADA INT,
	CODFILIAL INT,
	CPF VARCHAR(15),
	CODSITUACAO VARCHAR(1),
	CODSECAO VARCHAR(35),
	DATAADMISSAO DATETIME,
    CHAPA VARCHAR(20),
    NOME VARCHAR(200),
    SECAO VARCHAR(200),
    FUNCAO VARCHAR(200),
    FUNCAO_ANTERIOR VARCHAR(200),
    EMPRESA VARCHAR(200),
    DTMUDANCA DATETIME,
    SALARIO_NOVO NUMERIC(18,2),
    SALARIO_ANTERIOR NUMERIC(18,2),
    DIFERENCA NUMERIC(18,2),
	VALOR_POR_HORA NUMERIC(10,2),
	JORNADA VARCHAR(5),
	MOTIV_ALT_SAL VARCHAR(200)
);

INSERT INTO #Resultado (
    CODCOLIGADA,
	CODFILIAL,
	CODSITUACAO,
	CODSECAO,
	CPF,
    CHAPA,
    NOME,
    SECAO,
    FUNCAO,
    FUNCAO_ANTERIOR,
	DATAADMISSAO,
    EMPRESA,
    DTMUDANCA,
    SALARIO_NOVO,
    SALARIO_ANTERIOR,
    DIFERENCA,
	VALOR_POR_HORA,
	JORNADA,
	MOTIV_ALT_SAL
)
SELECT
    PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CODSITUACAO,
	PFUNC.CODSECAO,
	PPESSOA.CPF,
    PFUNC.CHAPA,
    PPESSOA.NOME,
    PSECAO.DESCRICAO,
    PFUNCAO_ATUAL.NOME,
    FUN_ANT.NOME AS FUNCAO_ANTERIOR,
	PFUNC.DATAADMISSAO,
    GCOLIGADA.NOME,
    HIST.DTMUDANCA,
    HIST.SALARIO AS SALARIO_NOVO,
    SAL_ANT.SALARIO AS SALARIO_ANTERIOR,
    (HIST.SALARIO - SAL_ANT.SALARIO) AS DIFERENCA,
	CONVERT(DECIMAL(10,2),(HIST.SALARIO / HIST.JORNADA)) AS VALOR_POR_HORA,
	(CASE
			WHEN HIST.JORNADA = 12000 THEN '200'
			WHEN HIST.JORNADA = 13200 THEN '220'
			WHEN HIST.JORNADA = 1800 THEN '300'
			WHEN HIST.JORNADA = 2640 THEN '440'
			WHEN HIST.JORNADA = 2700 THEN '450'
			WHEN HIST.JORNADA = 3600 THEN '600'
			WHEN HIST.JORNADA = 4800 THEN '800'
			WHEN HIST.JORNADA = 5400 THEN '900'
			WHEN HIST.JORNADA = 5760 THEN '960'
			WHEN HIST.JORNADA = 6000 THEN '100'
			WHEN HIST.JORNADA = 6600 THEN '1100'
			WHEN HIST.JORNADA = 7200 THEN '1200'
			WHEN HIST.JORNADA = 7500 THEN '1250'
			WHEN HIST.JORNADA = 7800 THEN '1300'
			WHEN HIST.JORNADA = 8400 THEN '1400'
			WHEN HIST.JORNADA = 8640 THEN '1440'
			WHEN HIST.JORNADA = 9000 THEN '150'
			END) AS JORNADA,
			STRING_AGG(CASE 
			 WHEN HIST.MOTIVO = 'AD' THEN 'ADMISSÃO'
			 WHEN HIST.MOTIVO = 'AS' THEN 'ANTECIPAÇÃO SALARIAL CCT'
			 WHEN HIST.MOTIVO = 'AT' THEN 'ANTECIPAÇÃO DE DISSIDIO COLETIVO'
			 WHEN HIST.MOTIVO = 'BE' THEN 'REAJUSTE BOLSA ESTAGIO'
			 WHEN HIST.MOTIVO = 'CC' THEN 'CONVENÇÃO COLETIVA'
			 WHEN HIST.MOTIVO = 'DC' THEN 'MOTIVO DESCONHECIDO'
			 WHEN HIST.MOTIVO = 'EQ' THEN 'ENQUADRAMENTO'
			 WHEN HIST.MOTIVO = 'ES' THEN 'EQUIPARACAO SALARIAL'
			 WHEN HIST.MOTIVO = 'ME' THEN 'MERITO'
			 WHEN HIST.MOTIVO = 'MF' THEN 'MUDANÇA FUNÇÃO'
			 WHEN HIST.MOTIVO = 'PD' THEN 'PRODUÇÃO'
			 WHEN HIST.MOTIVO = 'PG' THEN 'PROGRESSÃO'
			 WHEN HIST.MOTIVO = 'PM' THEN 'PROMOÇÃO'
			 WHEN HIST.MOTIVO = 'RC' THEN 'RECLASSIFICAÇÃO'
			 WHEN HIST.MOTIVO = 'RE' THEN 'REAJUSTE EXPONTANEO'
			 WHEN HIST.MOTIVO = 'SM' THEN 'ALTERAÇÃO SALARIO MINIMO'
			 WHEN HIST.MOTIVO = 'TR' THEN 'TRANSFERENCIA_FILIAIS' 
			 END, ' - ') AS MOTIV_ALT_SAL
FROM
    PFUNC (NOLOCK)
INNER JOIN PFHSTSAL HIST (NOLOCK) ON HIST.CODCOLIGADA = PFUNC.CODCOLIGADA AND HIST.CHAPA = PFUNC.CHAPA
INNER JOIN PPESSOA (NOLOCK) ON PPESSOA.CODIGO = PFUNC.CODPESSOA
INNER JOIN PSECAO (NOLOCK) ON PSECAO.CODIGO = PFUNC.CODSECAO AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA
INNER JOIN GCOLIGADA (NOLOCK) ON GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA
INNER JOIN PFUNCAO PFUNCAO_ATUAL (NOLOCK) ON PFUNCAO_ATUAL.CODIGO = PFUNC.CODFUNCAO AND PFUNCAO_ATUAL.CODCOLIGADA = PFUNC.CODCOLIGADA
CROSS APPLY (
    SELECT TOP 1 FSAL.SALARIO
    FROM PFHSTSAL FSAL (NOLOCK)
    WHERE FSAL.CHAPA = HIST.CHAPA AND FSAL.CODCOLIGADA = HIST.CODCOLIGADA AND FSAL.DTMUDANCA < HIST.DTMUDANCA
    ORDER BY FSAL.DTMUDANCA DESC
) AS SAL_ANT
CROSS APPLY (
    SELECT TOP 1 FUN.NOME
    FROM PFHSTFCO FO (NOLOCK)
    INNER JOIN PFUNCAO FUN (NOLOCK) ON FUN.CODCOLIGADA = FO.CODCOLIGADA AND FUN.CODIGO = FO.CODFUNCAO
    WHERE FO.CHAPA = HIST.CHAPA AND FO.CODCOLIGADA = HIST.CODCOLIGADA AND FO.DTMUDANCA < HIST.DTMUDANCA
    ORDER BY FO.DTMUDANCA DESC
) AS FUN_ANT
WHERE
    PFUNC.CODSITUACAO NOT IN ('L')
    AND PFUNC.CODCOLIGADA IN (SELECT CODCOLIGADA FROM @COLIGADAS)
	AND HIST.DTMUDANCA BETWEEN @DATAINICIO AND @DATAFINAL
	/*AND HIST.DTMUDANCA >= '2023-01-01' 
	AND HIST.DTMUDANCA <= '2025-08-26'*/
	AND HIST.MOTIVO <> 'AD'
	AND PFUNC.CODTIPO NOT IN ('A','O','C','D','U','E')
	/*AND PFUNC.CHAPA = '00024817'*/

GROUP BY
    PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CODSITUACAO,
	PFUNC.DATAADMISSAO,
	PFUNC.CODSECAO,
	PPESSOA.CPF,
    PFUNC.CHAPA,
    PPESSOA.NOME,
    PSECAO.DESCRICAO,
    PFUNCAO_ATUAL.NOME,
    FUN_ANT.NOME,
    GCOLIGADA.NOME,
    HIST.DTMUDANCA,
    HIST.SALARIO,
    SAL_ANT.SALARIO,
	HIST.JORNADA;

SELECT * FROM #Resultado;

DROP TABLE #Resultado;