SELECT * 
FROM PFUFERIASRECIBO
WHERE CHAPA = '00024817'

SELECT *
FROM PFUFERIASVERBAS
WHERE CHAPA = '00024817'

SELECT * 
FROM PFUFERIASPER
WHERE CHAPA = '00024817'

--SELECT * 
--FROM PEVENTO 
--WHERE CHAPA = '00024817'


DECLARE @CHAPA AS VARCHAR = '00024817',
		@INICIO_FERIAS AS DATE = '20250331';

SELECT GCOLIGADA.NOME, 
(GCOLIGADA.RUA + ', ' + GCOLIGADA.NUMERO + ' - ' + GCOLIGADA.BAIRRO + ', ' + GCOLIGADA.CIDADE + ' - ' + GCOLIGADA.ESTADO) AS 'ENDEREÇO',
GCOLIGADA.CGC AS 'CNPJ',
GCOLIGADA.INSCRICAOESTADUAL,
PFUNC.CODSECAO,
PFUNC.NOME,
PFUNC.CHAPA,
PFUNC.CODFUNCAO,
PFUFERIASPER.NRODIASABONO AS 'DIAS DE ABONO',
PFUNCAO.NOME AS 'NOME FUNCAO',
PFUFERIASPER.DATAPAGTO AS 'DATA DE PAGAMENTO',
PFUFERIASRECIBO.SALARIO AS 'SALARIO BASE',
	(SELECT TOP 1 Salario
		FROM pfhstsal
		WHERE DTmudanca <= :INICIO_FERIAS
		and chapa = PFUFERIAS.CHAPA
ORDER BY DTmudanca DESC) AS 'SALLARIO NO MES',
CONVERT(VARCHAR,PFUFERIASRECIBO.DATAPAGTO,103) AS 'DATA PAGAMENTO',
PFUFERIASRECIBO.BASEPENSAO AS 'TOTAL DE PROVENTOS',
(PFUFERIASRECIBO.IRRF + PFUFERIASRECIBO.INSS1) AS 'TOTAL DE DESCONTOS',
(CASE WHEN PFUFERIASVERBAS.VALOR <> 0 AND PEVENTO.PROVDESCBASE = 'P' THEN PFUFERIASVERBAS.VALOR ELSE 0 END) AS 'PROVENTOS',
(CASE WHEN PFUFERIASVERBAS.VALOR <> 0 AND PEVENTO.PROVDESCBASE = 'D' THEN PFUFERIASVERBAS.VALOR ELSE 0 END) AS 'DESCONTOS',
PFUFERIASRECIBO.LIQUIDO AS 'VALOR LIQUIDO'


FROM PFUFERIAS				(NOLOCK)
INNER JOIN PFUFERIASPER		(NOLOCK) ON (PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA AND PFUFERIAS.FIMPERAQUIS = PFUFERIASPER.FIMPERAQUIS)
INNER JOIN PFUFERIASRECIBO	(NOLOCK) ON (PFUFERIASRECIBO.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASRECIBO.CHAPA = PFUFERIAS.CHAPA AND PFUFERIASRECIBO.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS)
INNER JOIN PFUFERIASVERBAS  (NOLOCK) ON (PFUFERIASVERBAS.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASVERBAS.CHAPA = PFUFERIAS.CHAPA AND PFUFERIAS.FIMPERAQUIS = PFUFERIASVERBAS.FIMPERAQUIS)
INNER JOIN PEVENTO			(NOLOCK) ON (PEVENTO.CODCOLIGADA = PFUFERIASVERBAS.CODCOLIGADA AND PFUFERIASVERBAS.CODEVENTO = PEVENTO.CODIGO)
INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = PFUFERIAS.CODCOLIGADA)
INNER JOIN PFUNC			(NOLOCK) ON (PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUNC.CHAPA = PFUFERIAS.CHAPA)
INNER JOIN PFUNCAO			(NOLOCK) ON (PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)


WHERE PFUFERIAS.CODCOLIGADA = :$CODCOLIGADA
AND PFUFERIAS.CHAPA = :CHAPA
AND PFUFERIASPER.DATAPAGTO BETWEEN DATEADD(DAY, -10, :INICIO_FERIAS) AND :INICIO_FERIAS



select * 
from glinksrel
where childtable = 'pfhstsal'

select * 
from pfhstsal
where chapa = '00024817'

SELECT TOP 1 Salario
FROM pfhstsal
WHERE DTmudanca <= '20250429'
and chapa = '00024817'
ORDER BY DTmudanca DESC;
