SELECT DISTINCT 
GFERIADO.* 
FROM PFUNC
JOIN PSECAO ON PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO
JOIN GCALEND ON GCALEND.CODIGO = PSECAO.CODCALENDARIO
JOIN GFERIADO ON GFERIADO.CODCALENDARIO = GCALEND.CODIGO

WHERE GCALEND.CODIGO = '0000005'
AND YEAR(GFERIADO.DIAFERIADO) = 2025
AND PSECAO.CODIGO = '01.500.20'
