/*DECLARE @DT_INI AS DATE = '20250101',
		@DT_FIM AS DATE = '20250115',
		@CODCOLIGADA AS INT = 1; */

WITH DateRange AS (
    SELECT 
        @DT_INI AS DT_INI, 
        @DT_FIM AS DT_FIM
),
BatidasDiarias AS (
    SELECT 
        ABATFUN.CODCOLIGADA, 
        ABATFUN.CHAPA,
        CAST(ABATFUN.DATA AS DATE) AS DATA_BATIDA,  -- Utilizando apenas a parte da data (sem hora)
        COUNT(*) AS QTD_BATIDAS
    FROM ABATFUN
    WHERE ABATFUN.DATA BETWEEN (SELECT DT_INI FROM DateRange) AND (SELECT DT_FIM FROM DateRange)
    GROUP BY ABATFUN.CODCOLIGADA, ABATFUN.CHAPA, CAST(ABATFUN.DATA AS DATE)
)
SELECT 
    PFUNC.CODCOLIGADA, 
    PFUNC.CODFILIAL, 
    PFUNC.CHAPA, 
    PFUNC.NOME, 
    PPESSOA.CPF, 
    PFUNC.CODSECAO, 
    CONVERT(VARCHAR(100), STRING_AGG(CHEFE.NOME, ' / ')) AS 'CHEFE', 
    CONVERT(VARCHAR(100), STRING_AGG(SUPER.NOME, ' / ')) AS 'SUPERVISOR',
	convert(VARCHAR,BatidasDiarias.DATA_BATIDA,103) AS 'DT_BATIDA',
	BatidasDiarias.QTD_BATIDAS

FROM PFUNC
INNER JOIN PPESSOA (NOLOCK)			ON PPESSOA.CODIGO = PFUNC.CODPESSOA 
LEFT JOIN PSUBSTCHEFE (NOLOCK)		ON PSUBSTCHEFE.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTCHEFE.CODSECAO = PFUNC.CODSECAO
LEFT JOIN PSUBSTSUP (NOLOCK)		ON PSUBSTSUP.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTSUP.CODSECAO = PFUNC.CODSECAO
LEFT JOIN PFUNC AS CHEFE (NOLOCK)	ON PSUBSTCHEFE.CODCOLIGADA = CHEFE.CODCOLIGADA AND PSUBSTCHEFE.CHAPASUBST = CHEFE.CHAPA
LEFT JOIN PFUNC AS SUPER (NOLOCK)	ON PSUBSTSUP.CODCOLIGADA = SUPER.CODCOLIGADA AND PSUBSTSUP.CHAPASUBST = SUPER.CHAPA
LEFT JOIN BatidasDiarias			ON BatidasDiarias.CODCOLIGADA = PFUNC.CODCOLIGADA AND BatidasDiarias.CHAPA = PFUNC.CHAPA

WHERE PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
AND PFUNC.CODSITUACAO <> 'D'
and QTD_BATIDAS not in (2,4,6,8)

GROUP BY 
    PFUNC.CODCOLIGADA, 
    PFUNC.CODFILIAL, 
    PFUNC.CHAPA, 
    PFUNC.NOME, 
    PPESSOA.CPF, 
    PFUNC.CODSECAO,
	BatidasDiarias.DATA_BATIDA,
	BatidasDiarias.QTD_BATIDAS

	order by BatidasDiarias.DATA_BATIDA, pfunc.nome