SELECT 
	(CASE WHEN PFUNC.CODSINDICATO IN ('0002', '0039') 
		AND ZMDCARTASINDICAL.TIPO = 1 
		AND GETDATE() BETWEEN ZMDCARTASINDICAL.DATAENTREGA AND ZMDCARTASINDICAL.DATAVALIDADE 
	THEN 'SIM' 
	ELSE 'NAO' 
	END) AS 'PODE',
	PFUNC.CODSINDICATO,
	ZMDCARTASINDICAL.TIPO,
	ZMDCARTASINDICAL.DATAENTREGA ,
	ZMDCARTASINDICAL.DATAVALIDADE,
	PFUNC.CODCATEGORIAESOCIAL

FROM ZMDCARTASINDICAL (NOLOCK)
INNER JOIN PFUNC (NOLOCK) ON PFUNC.CODPESSOA = ZMDCARTASINDICAL.CODPESSOA




/*WHERE PFUNC.CHAPA IN (:FRM_CHAPA)
AND PFUNC.CODCOLIGADA IN (:FRM_CODCOLIGADA)*/


commit
BEGIN TRAN;
WITH ANOTACAO AS (
SELECT PFUNC.CODCOLIGADA,
PPESSOA.CODIGO AS 'CODPESSOA',
PANOTAC.DTANOTACAO AS 'DATAENTREGA',
PANOTAC.DTRESOLUCAO AS 'DATAVENCIMENTO',
PANOTAC.TIPO,
PANOTAC.TEXTO as 'OBSERVACOES',
'JOB' AS 'USUARIOC',
GETDATE() AS 'DATAC',
'JOB' AS 'USUARIOE',
GETDATE() AS 'DATAE'
FROM PPESSOA 
INNER JOIN PANOTAC	(NOLOCK) ON PPESSOA.CODIGO = PANOTAC.CODPESSOA
INNER JOIN PFUNC	(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO

where 
PANOTAC.tipo = 8
)

INSERT INTO ZMDCARTASINDICAL (CODCOLIGADA,CODPESSOA, DATAENTREGA, DATAVALIDADE, TIPO,OBSERVACOES,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)
SELECT ANOTACAO.CODCOLIGADA,
ANOTACAO.CODPESSOA,
ANOTACAO.DATAENTREGA,
ANOTACAO.DATAVENCIMENTO,
(CASE WHEN ANOTACAO.TIPO = 8 THEN 1 ELSE 0 END) AS  TIPO,
ANOTACAO.OBSERVACOES,
ANOTACAO.USUARIOC,
ANOTACAO.DATAC,
ANOTACAO.USUARIOE,
ANOTACAO.DATAE
FROM ANOTACAO

ALTER TABLE ZMDCARTASINDICAL
ALTER ID INT IDENTITY(1,1);

EXEC sp_rename 'ZMDCARTASINDICAL', 'ZMDCARTASINDICAL_OLD';

CREATE TABLE ZMDCARTASINDICAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    CODCOLIGADA INT,
    CODPESSOA INT,
    DATAENTREGA DATETIME,
    DATAVALIDADE DATETIME,
    TIPO INT,
	OBSERVACOES VARCHAR(MAX),
	RECCREATEDBY VARCHAR(50),
	RECCREATEDON DATETIME,
	RECMODIFIEDBY VARCHAR(50),
	RECMODIFIEDON DATETIME
);



INSERT INTO ZMDCARTASINDICAL (CODCOLIGADA, CODPESSOA, DATAENTREGA, DATAVALIDADE, TIPO,OBSERVACOES,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON)
SELECT CODCOLIGADA, CODPESSOA, DATAENTREGA, DATAVALIDADE, TIPO, OBSERVACOES,RECCREATEDBY,RECCREATEDON,RECMODIFIEDBY,RECMODIFIEDON
FROM ZMDCARTASINDICAL_OLD;


select CODPESSOA,* 
from pfunc
where nome like '%yan%alves%'