select 
		
	   dense_rank() over (order by PFFINANC.MESCOMP) AS CONTADOR,	
	   GCOLIGADA.NOME AS NOME_COLIGADA,
	   GCOLIGADA.RUA,
	   GCOLIGADA.NUMERO,
	   GCOLIGADA.BAIRRO,
	   GCOLIGADA.CIDADE,
	   GCOLIGADA.ESTADO,
	   GCOLIGADA.CGC,
	   GCOLIGADA.INSCRICAOESTADUAL,  
	   PFUNC.CHAPA, 
	   PFUNC.NOME, 
	   PFUNCAO.NOME AS FUNCAO, 
	   PFUNCAO.CODIGO AS CODFUNCAO,
	   PFUNC.CODSECAO, 
	   (SELECT MAX(PFPERFF.SALARIOPAGO) 
	   FROM PFPERFF AS PFPERFF1
	   WHERE PFFINANC.CHAPA = PFPERFF1.CHAPA 
	   AND PFFINANC.CODCOLIGADA = PFPERFF1.CODCOLIGADA 
	   AND PFFINANC.ANOCOMP = PFPERFF1.ANOCOMP 
	   AND PFFINANC.MESCOMP = PFPERFF1.MESCOMP 
	   AND PFFINANC.NROPERIODO = PFPERFF1.NROPERIODO 
	   ) AS SALARIO,  
	   PEVENTO.CODIGO,
	   PEVENTO.DESCRICAO,
	   PFFINANC.REF,
	   (PFPERFF.BASEFGTS + PFPERFF.BASEFGTS13) AS BASE_FGTS,
	   (CASE WHEN PEVENTO.PROVDESCBASE = 'P' THEN PFFINANC.VALOR END) AS VALOR_P,
	   (CASE WHEN PEVENTO.PROVDESCBASE = 'D' THEN PFFINANC.VALOR END) AS VALOR_D,
	   	   (CASE WHEN PFFINANC.MESCOMP = 1 THEN 'JANEIRO'  
	   	   		 WHEN PFFINANC.MESCOMP = 2 THEN 'FEVEREIRO'
	         	 WHEN PFFINANC.MESCOMP = 3 THEN 'MARÇO'	   
	         	 WHEN PFFINANC.MESCOMP = 4 THEN 'ABRIL'
	         	 WHEN PFFINANC.MESCOMP = 5 THEN 'MAIO'     
	         	 WHEN PFFINANC.MESCOMP = 6 THEN 'JUNHO'
	         	 WHEN PFFINANC.MESCOMP = 7 THEN 'JULHO'    
	         	 WHEN PFFINANC.MESCOMP = 8 THEN 'AGOSTO'
	         	 WHEN PFFINANC.MESCOMP = 9 THEN 'SETEMBRO' 
	         	 WHEN PFFINANC.MESCOMP = 10 THEN 'OUTUBRO'
	         	 WHEN PFFINANC.MESCOMP = 11 THEN 'NOVEMBRO' 
	         	 WHEN PFFINANC.MESCOMP = 12 THEN 'DEZEMBRO'
	    END )+ '/' +CONVERT (VARCHAR,PFFINANC.ANOCOMP, 103)AS MESREF,
	    PFFINANC.MESCOMP AS 'CONTADOR_MES'
from PFFINANC (NOLOCK)
INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFPERFF   (NOLOCK) ON (PFFINANC.CHAPA = PFPERFF.CHAPA AND PFFINANC.CODCOLIGADA = PFPERFF.CODCOLIGADA AND
								  PFFINANC.ANOCOMP = PFPERFF.ANOCOMP AND PFFINANC.MESCOMP = PFPERFF.MESCOMP AND
								  PFFINANC.NROPERIODO = PFPERFF.NROPERIODO)
INNER JOIN PFUNCAO	 (NOLOCK) ON (PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
INNER JOIN GCOLIGADA (NOLOCK) ON (PFFINANC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
INNER JOIN GIMAGEM   (NOLOCK) ON (GIMAGEM.ID = GCOLIGADA.IDIMAGEM)

where PFFINANC.ANOCOMP = :ANOCOMP
AND   PFUNC.CHAPA LIKE :CHAPA
AND   PFFINANC.CODCOLIGADA = :CODCOLIGADA
/*AND   PFFINANC.MESCOMP = :MESCOMP*/
AND   PFFINANC.NROPERIODO like :NROPERIODO

AND   PEVENTO.PROVDESCBASE <> 'B'
/*AND   PFUNC.CODSITUACAO <> 'D'*/
/*AND   PFUNC.CODSECAO BETWEEN :CODSECAO_INI_S AND :CODSECAO_FIN_S*/

/*
where PFFINANC.ANOCOMP = :ANOCOMP_N
AND   PFFINANC.MESCOMP = :MESCOMP_N
AND   PFFINANC.NROPERIODO like :NROPERIODO_S
AND   PEVENTO.PROVDESCBASE <> 'B'
AND   PFUNC.CODSITUACAO <> 'D'
AND   PFUNC.CODSECAO BETWEEN :CODSECAO_INI_S AND :CODSECAO_FIN_S
AND   PFFINANC.CODCOLIGADA = :CODCOLIGADA_N
AND   PFUNC.CHAPA =:P_CHAPA
*/

GROUP BY 
	   PFFINANC.MESCOMP,	
	   /*GIMAGEM.IMAGEM,*/
	   GCOLIGADA.NOME,
	   GCOLIGADA.RUA,
	   GCOLIGADA.NUMERO,
	   GCOLIGADA.BAIRRO,
	   GCOLIGADA.CIDADE,
	   GCOLIGADA.ESTADO,
	   GCOLIGADA.CGC,
	   GCOLIGADA.INSCRICAOESTADUAL,  
	   PFUNC.CHAPA, 
	   PFUNC.NOME, 
	   PFUNCAO.NOME, 
	   PFUNCAO.CODIGO,
	   PFUNC.CODSECAO, 
	   PEVENTO.CODIGO,
	   PEVENTO.DESCRICAO,
	   PFFINANC.REF,
	   PFFINANC.CHAPA,
	   PFFINANC.CODCOLIGADA,
	   PFFINANC.ANOCOMP,
	   PFFINANC.NROPERIODO,
	   PFPERFF.BASEFGTS,
	   PFPERFF.BASEFGTS13,
	   PEVENTO.PROVDESCBASE,
	   PFFINANC.VALOR

ORDER BY 
PFFINANC.MESCOMP
,PFUNC.NOME
,PEVENTO.PROVDESCBASE DESC
,PEVENTO.CODIGO