/*DECLARE @CODCOLIGADA AS INT = 51,
		@DT_ABO_INI AS DATE = '20250116',
		@DT_ABO_FIM AS DATE = '20250213',
		@FERIAS_INI AS DATE = '20250401',
		@FERIAS_FIM AS DATE = '20250430';*/
		
SELECT (GRUPO.VALOR_LINHA * GRUPO.QTD_PASSES) AS 'VALOR_DIARIO',
(CASE 
	WHEN GRUPO.CART�O_BHBUS IS NOT NULL THEN 'BHBUS'  
	WHEN GRUPO.CART�O_OTIMO IS NOT NULL THEN 'OTIMO'  
	WHEN GRUPO.CART�O_SP1 IS NOT NULL THEN 'SP1'  
	WHEN GRUPO.CART�O_SP2 IS NOT NULL THEN 'SP2'  
	WHEN GRUPO.CART�O_SP3 IS NOT NULL THEN 'SP3'  
	WHEN GRUPO.CART�O_RJ_JAE IS NOT NULL THEN 'CART�O RJ JA'  
	WHEN GRUPO.CART�O_BETIM_CARD IS NOT NULL THEN 'CART�O BETIM CARD'  
	ELSE 'NAO UTILIZA'
	END) AS 'Operadora_VT',
* 
FROM(

SELECT 
PFUNC.CODCOLIGADA, 
PFUNC.CODFILIAL, 
PFUNC.CHAPA, 
PFUNC.NOME, 
PPESSOA.CPF, 
CONVERT(VARCHAR,PFUNC.DATAADMISSAO,103) AS 'DATAADMISSAO',
/*PFUNCAO.CODIGO,*/ 
PFUNCAO.NOME AS 'NOME_FUNCAO', 
/*(PFRATEIOFIXO.CODCCUSTO + ' - PORCENTAGEM:' + CONVERT(VARCHAR,PFRATEIOFIXO.VALOR) + '%') AS 'RATEIO FIXO',*/
PFRATEIOFIXO.CODCCUSTO AS 'CENTRO_DE_CUSTO_RATEIO',
(SELECT TOP 1 NOME
 FROM GCCUSTO 
 WHERE GCCUSTO.CODCOLIGADA = PFRATEIOFIXO.CODCOLIGADA AND GCCUSTO.CODCCUSTO = PFRATEIOFIXO.CODCCUSTO) AS 'DESC_CENTRO_DE_CUSTO_RATEIO_FIXO',
PFUNC.CODSECAO, 
PSECAO.DESCRICAO AS 'NOME_SE��O', 
PFUNC.CODSITUACAO, 
/*CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS 'DTNASCIMENTO',*/
(PFUNC.CODHORARIO + ' - ' + AHORARIO.DESCRICAO) AS 'HORARIO',
PVALETR.GRUPOTRANSP AS 'COD_GRUPO_TRANSPORTE',
(SELECT TOP 1 DESCRICAO 
 FROM PGRPVALE
 WHERE PGRPVALE.CODCOLIGADA = PVALETR.CODCOLIGADA AND PGRPVALE.CODCLIENTE = PVALETR.GRUPOTRANSP) AS 'DESC_GRUPO_TRANSPORTE',
/*(CASE 
	WHEN PFCOMPL.CARTAOBHBUS IS NOT NULL THEN 'BHBUS'  
	WHEN PFCOMPL.OTIMO IS NOT NULL THEN 'OTIMO'  
	WHEN PFCOMPL.SPVALE IS NOT NULL THEN 'SP1'  
	WHEN PFCOMPL.SPTRANS IS NOT NULL THEN 'SP2'  
	WHEN PFCOMPL.SP3 IS NOT NULL THEN 'SP3'  
	WHEN PFCOMPL.CARTAORJ_JAE IS NOT NULL THEN 'CART�O RJ JA'  
	WHEN PFCOMPL.BETIMCARD IS NOT NULL THEN 'CART�O BETIM CARD'  
	ELSE 'NAO UTILIZA'
	END) AS 'Operadora_VT',*/
/*(CASE WHEN PFCOMPL.CARTAOBHBUS IS NULL THEN PFCOMPL.CARTAOOTIMO ELSE PFCOMPL.CARTAOBHBUS END) AS 'NUM_CARTAOVT',*/
PFCOMPL.CARTAOBHBUS AS 'CART�O_BHBUS',
PFCOMPL.OTIMO AS 'CART�O_OTIMO',
PFCOMPL.SPVALE AS 'CART�O_SP1',
PFCOMPL.SPTRANS AS 'CART�O_SP2',
PFCOMPL.SP3 AS 'CART�O_SP3', 
PFCOMPL.MATRICULARIOCARD as 'CART�O_RIO_CARD',
PFCOMPL.CARTAORJ_JAE AS 'CART�O_RJ_JAE',
PFCOMPL.BETIMCARD AS 'CART�O_BETIM_CARD',
CASE 
 WHEN PFCOMPL.OPVT = 1 THEN 'VALE TRANSPORTE'
 WHEN PFCOMPL.OPVT = 2 THEN 'VALE COMBUSTIVEL' 
ELSE 'NAO POSSUI' END as 'OP_VT',
PTARIFA.VALOR AS 'VALOR_LINHA', 
PFVALETR.NROVIAGENS AS 'QTD_PASSES',
PFUNC.DIASUTPROXMES AS 'DIAS_UTEIS_MES', 
(PFVALETR.CODLINHA + ' -' + PVALETR.NOMELINHA) AS 'LINHA',

(SELECT 
SUM(GRUPO.FALTA_DIA + (GRUPO.FALTA_HORA/7.33)) AS TOTAL_FALTAS
FROM(
SELECT  
PFUNC.NOME,
PFUNC.CODCOLIGADA AS COLIG, 
PFFINANC.REF,
PFUFERIAS.INICIOPERAQUIS AS INI_PER_FER,
PFUFERIAS.FIMPERAQUIS AS FIM_PER_FER,
(CASE WHEN PEVENTO.CODIGO IN ('0594', '0338', '0417') THEN PFFINANC.REF ELSE 0 END) AS FALTA_DIA,
(CASE WHEN PEVENTO.CODIGO IN ('0104', '0614', '0143') THEN PFFINANC.REF ELSE 0 END) AS FALTA_HORA

FROM PFFINANC 
INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC as PFUNC1	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUFERIAS (NOLOCK) ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PERIODOABERTO = 1)

WHERE 
    PFFINANC.ANOCOMP BETWEEN YEAR(PFUFERIAS.INICIOPERAQUIS) AND YEAR(PFUFERIAS.FIMPERAQUIS)
	AND PFUNC1.CHAPA IN (PFUNC.CHAPA)
    AND PFFINANC.CODCOLIGADA IN (PFUNC.CODCOLIGADA)
    AND PFFINANC.NROPERIODO = 3
	AND   PEVENTO.PROVDESCBASE <> 'B'
	) AS GRUPO
	GROUP BY 
	GRUPO.COLIG,
	GRUPO.NOME
)  as 'TOTAL_DE_FALTAS'


/*(SELECT COUNT(*)
from PFFINANC (NOLOCK)
INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
 WHERE PEVENTO.CODIGO IN ('0594', '0614', '0104', '0338')),
 /*CONCLUIR O JOIN DAS FALTAS E ENTENDER COM A LANE OS FILTROS*/
'' AS 'FALTAS',
'' AS 'ATESTADOS',
'' AS 'FERIAS'*/,
'' AS 'TOTAL',
'' AS 'SALDO_SITE_EM',
'' AS 'PROJE��O',
'' AS 'SaldoP_Aproveitar',
'' AS 'COMPRA_SITE',
'' AS 'N_RDA',
'' AS 'N_NF',
'' AS 'OBS'


FROM PFUNC
INNER JOIN PFCOMPL			ON (PFCOMPL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFCOMPL.CHAPA = PFUNC.CHAPA)
INNER JOIN PPESSOA			ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
INNER JOIN PFUNCAO			ON (PFUNCAO.CODIGO = PFUNC.CODFUNCAO AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
INNER JOIN PSECAO			ON (PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO)
INNER JOIN PFVALETR			ON (PFVALETR.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFVALETR.CHAPA = PFUNC.CHAPA)
INNER JOIN PVALETR			ON (PVALETR.CODCOLIGADA = PFVALETR.CODCOLIGADA AND PVALETR.CODIGO = PFVALETR.CODLINHA)
INNER JOIN PTARIFA			ON (PTARIFA.CODCOLIGADA = PVALETR.CODCOLIGADA AND PTARIFA.CODIGO = PVALETR.CODTARIFA)
INNER JOIN AHORARIO			ON (AHORARIO.CODCOLIGADA = PFUNC.CODCOLIGADA AND AHORARIO.CODIGO = PFUNC.CODHORARIO)
pfhstaft

WHERE PFUNC.CODCOLIGADA IN (@CODCOLIGADA) 
AND PFUNC.CHAPA IN (@CHAPA)
) AS GRUPO


GROUP BY
GRUPO.CODCOLIGADA,
GRUPO.CODFILIAL,
GRUPO.VALOR_LINHA,
GRUPO.QTD_PASSES,
GRUPO.CHAPA,
GRUPO.NOME,
GRUPO.CPF,
GRUPO.DATAADMISSAO,
GRUPO.NOME_FUNCAO,
GRUPO.CENTRO_DE_CUSTO_RATEIO,
GRUPO.DESC_CENTRO_DE_CUSTO_RATEIO_FIXO,
GRUPO.CODSECAO,
GRUPO.NOME_SE��O,
GRUPO.CODSITUACAO,
GRUPO.HORARIO,
GRUPO.COD_GRUPO_TRANSPORTE,
GRUPO.DESC_GRUPO_TRANSPORTE,
GRUPO.CART�O_BHBUS,
GRUPO.CART�O_OTIMO,
GRUPO.CART�O_SP1,
GRUPO.CART�O_SP2,
GRUPO.CART�O_SP3,
GRUPO.CART�O_RIO_CARD,
GRUPO.CART�O_RJ_JAE,
GRUPO.CART�O_BETIM_CARD,
GRUPO.DIAS_UTEIS_MES,
--GRUPO.OPERADORA_VT,
GRUPO.OP_VT,
GRUPO.LINHA,
GRUPO.DIASABONADOS,
GRUPO.HORAS_DE_ABONO,
GRUPO.TOTAL_DE_FALTAS,
GRUPO.ATESTADOS,
GRUPO.DIAS_UTEIS_FERIAS,
GRUPO.TOTAL,
GRUPO.SALDO_SITE_EM,
GRUPO.PROJE��O,
GRUPO.SaldoP_Aproveitar,
GRUPO.COMPRA_SITE,
GRUPO.N_RDA,
GRUPO.N_NF,
GRUPO.OBS,
GRUPO.DATAINICIO,
GRUPO.DATAFIM,
GRUPO.CODCALENDARIO

/*WHERE GRUPO.TOTAL_DE_FALTAS > 0*/

ORDER BY GRUPO.CODCOLIGADA,GRUPO.NOME

/*
SELECT PFCOMPL.CARTAORJ_JAE 
FROM PFUNC 
LEFT JOIN PFCOMPL			(NOLOCK) ON (PFCOMPL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFCOMPL.CHAPA = PFUNC.CHAPA)
WHERE PFCOMPL.CODCOLIGADA = 51 
AND PFUNC.CHAPA = '00000556'*/