select 
		
	
	   PFUNC.CHAPA, 
	   PFUNC.NOME,
	   CONVERT (VARCHAR(20),:$CODUSUARIO) AS CODUSUARIO_GERACAO
	  
from PFFINANC (NOLOCK)

INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFPERFF   (NOLOCK) ON (PFFINANC.CHAPA = PFPERFF.CHAPA AND PFFINANC.CODCOLIGADA = PFPERFF.CODCOLIGADA AND
								  PFFINANC.ANOCOMP = PFPERFF.ANOCOMP AND PFFINANC.MESCOMP = PFPERFF.MESCOMP AND
								  PFFINANC.NROPERIODO = PFPERFF.NROPERIODO)
INNER JOIN PFUNCAO	 (NOLOCK) ON (PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
INNER JOIN GCOLIGADA (NOLOCK) ON (PFFINANC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
INNER JOIN GIMAGEM   (NOLOCK) ON (GIMAGEM.ID = GCOLIGADA.IDIMAGEM)

where PFFINANC.ANOCOMP = :ANOCOMP
AND   PFUNC.CHAPA LIKE :CHAPA
AND   PFFINANC.CODCOLIGADA = :CODCOLIGADA
/*AND   PFFINANC.MESCOMP = :MESCOMP*/
AND   PFFINANC.NROPERIODO like :NROPERIODO

AND   PEVENTO.PROVDESCBASE <> 'B'
/*AND   PFUNC.CODSITUACAO <> 'D'*/
/*AND   PFUNC.CODSECAO BETWEEN :CODSECAO_INI_S AND :CODSECAO_FIN_S*/


GROUP BY PFUNC.NOME, PFUNC.CHAPA

ORDER BY PFUNC.NOME