DECLARE @CODCOLIGADA AS INT = 1,
		@DATAINICIO AS DATE = '20000801',
		@DATAFINAL AS DATE = '20250210';
		
SELECT CONVERT(DECIMAL(10,2),(GRUPO.SALARIO_PFHSTSAL / GRUPO.JORNADA)) AS 'VALOR_POR_HORA',
GRUPO.CODCOLIGADA,
GRUPO.CODFILIAL,
GRUPO.CHAPA,
GRUPO.NOME_FUNC,
GRUPO.CPF,
GRUPO.CODSITUACAO,
GRUPO.SECAO,
GRUPO.NOME_SECAO,
GRUPO.FUNCAO_ATUAL,
GRUPO.NOME_FUNÇÃO_ATUAL,
GRUPO.CODSINDICATO,
GRUPO.DATAADMISSAO,
GRUPO.FUNCAO_ANTIGA,
GRUPO.SALARIO_NOVO,
GRUPO.SALARIO_ANTERIOR,
GRUPO.DTMUDANCA,
GRUPO.SALARIO_PFHSTSAL,
GRUPO.JORNADA,
GRUPO.MOTIV_ALT_SAL
FROM 
(
	SELECT 
	PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CHAPA AS 'CHAPA',
	PPESSOA.NOME AS 'NOME_FUNC',
	PPESSOA.CPF,
	PFUNC.CODSITUACAO,
	PSECAO.CODIGO AS 'SECAO',
	PSECAO.DESCRICAO AS 'NOME_SECAO',
	PFUNC.CODFUNCAO 'FUNCAO_ATUAL',
	PFUNCAO.NOME AS 'NOME_FUNÇÃO_ATUAL',
	PFUNC.CODSINDICATO,
	PFUNC.DATAADMISSAO,
	(SELECT TOP 1 FUN.NOME 
			FROM PFHSTFCO FO (NOLOCK)
			LEFT JOIN PFUNCAO FUN	(NOLOCK) ON (FUN.CODCOLIGADA = FO.CODCOLIGADA AND FUN.CODIGO = FO.CODFUNCAO)
			LEFT JOIN PFHSTSEC		(NOLOCK) ON (PFHSTSEC.CODCOLIGADA = PFHSTSAL.CODCOLIGADA AND PFHSTSEC.CHAPA = PFHSTSAL.CHAPA AND PFHSTSEC.DTMUDANCA <> PFHSTSAL.DTMUDANCA AND PFHSTSEC.MOTIVO <> 'AD')
		WHERE FO.DTMUDANCA = PFHSTSAL.DTMUDANCA
			AND FO.CHAPA = PFHSTSAL.CHAPA) AS FUNCAO_ANTIGA,
	(SELECT TOP 1 FF.SALARIO 
			FROM PFHSTSAL FF (NOLOCK)
			LEFT JOIN PFHSTFCO F ON F.CODCOLIGADA = FF.CODCOLIGADA AND F.CHAPA = FF.CHAPA
			LEFT JOIN PFHSTSEC		(NOLOCK) ON (PFHSTSEC.CODCOLIGADA = PFHSTSAL.CODCOLIGADA AND PFHSTSEC.CHAPA = PFHSTSAL.CHAPA AND PFHSTSEC.DTMUDANCA <> PFHSTSAL.DTMUDANCA AND PFHSTSEC.MOTIVO <> 'AD')
		WHERE FF.DTMUDANCA = PFHSTSAL.DTMUDANCA
			AND FF.CHAPA = PFHSTSAL.CHAPA) AS SALARIO_NOVO,
	(SELECT TOP 1 FFSAL.SALARIO 
			FROM PFHSTSAL FFSAL (NOLOCK)
			LEFT JOIN PFHSTFCO FHSTO ON FHSTO.CODCOLIGADA = FFSAL.CODCOLIGADA AND FHSTO.CHAPA = FFSAL.CHAPA
			LEFT JOIN PFHSTSEC		(NOLOCK) ON (PFHSTSEC.CODCOLIGADA = PFHSTSAL.CODCOLIGADA AND PFHSTSEC.CHAPA = PFHSTSAL.CHAPA AND PFHSTSEC.DTMUDANCA <> PFHSTSAL.DTMUDANCA AND PFHSTSEC.MOTIVO <> 'AD')
		WHERE FFSAL.DTMUDANCA < @DATAINICIO
			AND FFSAL.CHAPA = PFUNC.CHAPA
			ORDER BY FFSAL.DTMUDANCA DESC) AS SALARIO_ANTERIOR,
		PFHSTSAL.DTMUDANCA,
		PFHSTSAL.SALARIO as 'SALARIO_PFHSTSAL',

		(CASE 
			WHEN PFHSTSAL.JORNADA = 12000 THEN 200
			WHEN PFHSTSAL.JORNADA = 13200 THEN 220
			WHEN PFHSTSAL.JORNADA = 1800 THEN 300
			WHEN PFHSTSAL.JORNADA = 2640 THEN 440
			WHEN PFHSTSAL.JORNADA = 2700 THEN 450
			WHEN PFHSTSAL.JORNADA = 3600 THEN 600
			WHEN PFHSTSAL.JORNADA = 4800 THEN 800
			WHEN PFHSTSAL.JORNADA = 5400 THEN 900
			WHEN PFHSTSAL.JORNADA = 5760 THEN 960
			WHEN PFHSTSAL.JORNADA = 6000 THEN 100
			WHEN PFHSTSAL.JORNADA = 6600 THEN 1100
			WHEN PFHSTSAL.JORNADA = 7200 THEN 1200
			WHEN PFHSTSAL.JORNADA = 7500 THEN 1250
			WHEN PFHSTSAL.JORNADA = 7800 THEN 1300
			WHEN PFHSTSAL.JORNADA = 8400 THEN 1400
			WHEN PFHSTSAL.JORNADA = 8640 THEN 1440
			WHEN PFHSTSAL.JORNADA = 9000 THEN 150
			END) AS 'JORNADA',
			 CONVERT(VARCHAR(100), STRING_AGG(CASE 
			 WHEN PFHSTSAL.MOTIVO = 'AD' THEN 'ADMISSÃO'
			 WHEN PFHSTSAL.MOTIVO = 'AS' THEN 'ANTECIPAÇÃO SALARIAL CCT'
			 WHEN PFHSTSAL.MOTIVO = 'AT' THEN 'ANTECIPAÇÃO DE DISSIDIO COLETIVO'
			 WHEN PFHSTSAL.MOTIVO = 'BE' THEN 'REAJUSTE BOLSA ESTAGIO'
			 WHEN PFHSTSAL.MOTIVO = 'CC' THEN 'CONVENÇÃO COLETIVA'
			 WHEN PFHSTSAL.MOTIVO = 'DC' THEN 'MOTIVO DESCONHECIDO'
			 WHEN PFHSTSAL.MOTIVO = 'EQ' THEN 'ENQUADRAMENTO'
			 WHEN PFHSTSAL.MOTIVO = 'MF' THEN 'MUDANÇA FUNÇÃO'
			 WHEN PFHSTSAL.MOTIVO = 'PD' THEN 'PRODUÇÃO'
			 WHEN PFHSTSAL.MOTIVO = 'PG' THEN 'PROGRESSÃO'
			 WHEN PFHSTSAL.MOTIVO = 'PM' THEN 'PROMOÇÃO'
			 WHEN PFHSTSAL.MOTIVO = 'RC' THEN 'RECLASSIFICAÇÃO'
			 WHEN PFHSTSAL.MOTIVO = 'RE' THEN 'REAJUSTE EXPONTANEO'
			 WHEN PFHSTSAL.MOTIVO = 'SM' THEN 'ALTERAÇÃO SALARIO MINIMO'
			 WHEN PFHSTSAL.MOTIVO = 'TR' THEN 'TRANSFERENCIA_FILIAIS' 
			 WHEN PFHSTSAL.MOTIVO = 'ME' THEN 'MERITO' 
			 END, ' - ')) AS 'MOTIV_ALT_SAL'

		 FROM PFUNC (NOLOCK)
		 INNER JOIN PFHSTSAL		(NOLOCK) ON (PFHSTSAL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFHSTSAL.CHAPA = PFUNC.CHAPA)
		 INNER JOIN PPESSOA			(NOLOCK) ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
		 INNER JOIN PSECAO			(NOLOCK) ON (PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
		 INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA)
		 INNER JOIN PFUNCAO			(NOLOCK) ON (PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUNCAO.CODIGO = PFUNC.CODFUNCAO)
		 INNER JOIN PFUNCAO FUNCAO	(NOLOCK) ON (FUNCAO.CODIGO = PFUNC.CODFUNCAO AND FUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
		 

		 WHERE
		 PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
		 AND PFHSTSAL.DTMUDANCA BETWEEN @DATAINICIO AND @DATAFINAL
		 AND PFUNC.CODSITUACAO NOT IN ('L')
		 AND PFHSTSAL.MOTIVO <> 'AD'
		 AND PFUNC.CODTIPO NOT IN ('A','O','C','D','U','E')
		 /*AND PFHSTSAL.CHAPA = '00021953'*/


	GROUP BY 
	PFUNC.CODCOLIGADA,
	PFUNC.CODFILIAL,
	PFUNC.CHAPA,
	PPESSOA.NOME,
	PPESSOA.CPF,
	PFUNC.CODSITUACAO,
	PSECAO.CODIGO,
	PSECAO.DESCRICAO,
	PFUNC.CODFUNCAO,
	PFUNCAO.NOME,
	PFUNC.CODSINDICATO,
	PFUNC.DATAADMISSAO,
	PFHSTSAL.DTMUDANCA,
	PFHSTSAL.CHAPA,
	PFUNC.SALARIO,
	PFUNC.NOME,
	PFHSTSAL.CODCOLIGADA,
	PFHSTSAL.JORNADA,
	PFHSTSAL.SALARIO

) AS GRUPO
	WHERE
	GRUPO.NOME_FUNC LIKE '%BENNY%'
	
	ORDER BY GRUPO.NOME_FUNC, GRUPO.CHAPA, GRUPO.DTMUDANCA           

  /* 
  SELECT * 
  FROM GLINKSREL
  WHERE CHILDTABLE = 'PFHSTSEC'

  SELECT DISTINCT MOTIVO 
  FROM PFHSTSEC

  SELECT *
  FROM PFHSTSEC
  WHERE MOTIVO = 'EO'
  */