USE CORPORE_RESIDENCIAL
SELECT
 
PFUNC.CHAPA
--,PFUNC.TIPODEMISSAO
--,PFUNC.DATADEMISSAO
,PFUNC.CODPESSOA
,PPESSOA.SEXO
,PFUNC.CODSITUACAO as 'SITUAÇÃO'
,PFUNC.CODSECAO AS 'SEÇÃO'
,PFUNC.CODCOLIGADA AS 'COLIGADA'
,PPESSOA.CPF
,PFUNC.DATAADMISSAO AS 'ADMISSÃO'
,PFUNC.NOME AS 'NOME FUNCIONARIO'
,GUSUARIO.CODUSUARIO AS 'USUÁRIO RM'
,ppessoa.EMAIL
,PFUNCAO.NOME AS 'FUNCAO'
,ISNULL (PPESSOA.TELEFONE1, 'Ñ POSSUI') AS 'TELEFONE'
,NROCENCUSTOCONT AS 'CENTRO DE CUSTO'
,GCCUSTO.NOME AS 'DEPARTAMENTO/LOCAL DE ACESSO'
,PSECAO.DESCRICAO AS 'NOME SEÇÃO'
,PSECAO.CEP
,PPESSOA.RUA
,PPESSOA.NUMERO
,PPESSOA.COMPLEMENTO
,PPESSOA.BAIRRO
,PSECAO.CIDADE
,PSECAO.ESTADO
,ISNULL (GUSUARIO.EMAIL , 'NÃO POSSUI') AS 'E-MAIL'
,PCODINSTRUCAO.DESCRICAO AS 'GRAU INSTRUCAO'
--,GUSRPERFIL.CODPERFIL AS 'PERFIL ACESSO'
 

    FROM PFUNC (NOLOCK)

        LEFT JOIN PSECAO            (NOLOCK)				 ON (PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
        LEFT JOIN PFUNCAO            (NOLOCK)			 ON (PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
        LEFT JOIN GCCUSTO            (NOLOCK)			  ON (PSECAO.NROCENCUSTOCONT = GCCUSTO.CODCCUSTO AND PSECAO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
        LEFT JOIN PPESSOA            (NOLOCK)				  ON (PFUNC.CODPESSOA = PPESSOA.CODIGO)
        LEFT JOIN GUSUARIO            (NOLOCK)			  ON (PFUNC.NOME = GUSUARIO.NOME)
        LEFT JOIN PCODINSTRUCAO        (NOLOCK)    ON (PPESSOA.GRAUINSTRUCAO = PCODINSTRUCAO.CODINTERNO)
        --INNER JOIN AHORARIO            (NOLOCK)    ON (AHORARIO.CODCOLIGADA = PFUNC.CODCOLIGADA AND AHORARIO.CODIGO = PFUNC.CODCOLIGADA)
        --LEFT JOIN GUSRPERFIL        (NOLOCK)    ON (GUSRPERFIL.CODUSUARIO = GUSUARIO.CODUSUARIO)
            WHERE  PFUNC.CODSITUACAO <> 'D' and
                    --GUSUARIO.CODUSUARIO LIKE 'flavio%'  /* usuário RM */
                    PFUNC.NOME like '%joão%andrade%'  /* procurar por nome */
                    --PFUNCAO.NOME like '%contas%receber%' /* FUNÇÃO */
                    --GCCUSTO.NOME LIKE '%compras%' /*DEPARTAMENTO */


ORDER BY PFUNC.NOME
