

SELECT 
CONVERT(DECIMAL(10,2),(A.ADIANTAMENTO_10 + (A.SALARIO_15 - A.ADIANTAMENTO_10) + A.DECIMOTERCEIRO)) AS 'SOMA_PENSAO'
FROM( 
SELECT 
	ISNULL(CONVERT(MONEY,(SELECT LIQUIDO * 0.10
		FROM PFPERFF PFPERFF1(NOLOCK)
		WHERE PFPERFF1.CHAPA = GRUPO.CHAPA  
		AND PFPERFF1.CODCOLIGADA = GRUPO.CODCOLIGADA 
		AND PFPERFF1.ANOCOMP = GRUPO.ANOPARAM 
		AND PFPERFF1.MESCOMP = GRUPO.MESPARAM
		AND PFPERFF1.NROPERIODO = 1)),0) AS 'ADIANTAMENTO_10',
	ISNULL(CONVERT(MONEY,(SELECT LIQUIDO * 0.15
		FROM PFPERFF PFPERFF2 (NOLOCK)
		WHERE PFPERFF2.CHAPA = GRUPO.CHAPA  
		AND PFPERFF2.CODCOLIGADA = GRUPO.CODCOLIGADA 
		AND PFPERFF2.ANOCOMP = GRUPO.ANOPARAM 
		AND PFPERFF2.MESCOMP = GRUPO.MESPARAM
		AND PFPERFF2.NROPERIODO = 3)),0) AS 'SALARIO_15',
	ISNULL(CONVERT(MONEY,(SELECT LIQUIDO * 0.25
		FROM PFPERFF PFPERFF3(NOLOCK)
		WHERE PFPERFF3.CHAPA = GRUPO.CHAPA  
		AND PFPERFF3.CODCOLIGADA = GRUPO.CODCOLIGADA 
		AND PFPERFF3.ANOCOMP = GRUPO.ANOPARAM 
		AND PFPERFF3.MESCOMP = GRUPO.MESPARAM
		AND PFPERFF3.NROPERIODO = 2)),0) AS 'DECIMOTERCEIRO'
FROM(
SELECT 
	PFUNC.CHAPA,
	PFUNC.CODCOLIGADA,
	(SELECT VALORINT 
		FROM PPARAMQUIOSQUE (NOLOCK)
		WHERE PPARAMQUIOSQUE.NOMECOLUNA IN ('MESCOMPCONSULTAQUIOSQUE')
		AND PPARAMQUIOSQUE.CODGRUPO = 'PORTAL_FUNC'
		AND PPARAMQUIOSQUE.CODCOLIGADA = PFUNC.CODCOLIGADA) AS 'MESPARAM',
	(SELECT VALORINT 
		FROM PPARAMQUIOSQUE (NOLOCK)
		WHERE 
		PPARAMQUIOSQUE.NOMECOLUNA IN ('ANOCOMPCONSULTAQUIOSQUE')
		AND PPARAMQUIOSQUE.CODGRUPO = 'PORTAL_FUNC'
		AND PPARAMQUIOSQUE.CODCOLIGADA = PFUNC.CODCOLIGADA) AS 'ANOPARAM'

FROM PFUNC (NOLOCK)
INNER JOIN PFDEPEND (NOLOCK)ON PFUNC.CODCOLIGADA = PFDEPEND.CODCOLIGADA AND PFUNC.CHAPA = PFDEPEND.CHAPA
WHERE PFDEPEND.INCPENSAO = 1  AND PFUNC.CHAPA IN(:FRM_CHAPA) AND PFUNC.CODCOLIGADA IN (:FRM_COLIGADA)

/*

FROM PFUNC 
INNER JOIN PFDEPEND ON PFUNC.CODCOLIGADA = PFDEPEND.CODCOLIGADA AND PFUNC.CHAPA = PFDEPEND.CHAPA
WHERE PFDEPEND.INCPENSAO = 1  AND PFUNC.CHAPA IN('00000227') AND PFUNC.CODCOLIGADA IN (22)

*/

) AS GRUPO

) AS A
