
SELECT 
PFUNC.CODCOLIGADA,
PFUNC.NOME AS 'NOME_FUNCIONARIO',
PFUNC.CHAPA,
PFUNC.CODFILIAL,
PFENCCC.CODPCCUSTO,
PFUNC.CODSITUACAO,
PFUNC.CODSECAO,
PFUNC.CODSINDICATO,
PSECAO.DESCRICAO AS 'NOME_SECAO',
PEVENTO.CODIGO,
PEVENTO.PROVDESCBASE,
PEVENTO.DESCRICAO,
PFVERBASDIS.IDDADOS,
(CONVERT(VARCHAR,PDADOSDIS.TPACORDO) + CONVERT(VARCHAR,PFVERBASDIS.REF)) AS CODIGO_ACORDO,
PFVERBASDIS.REF,
PFVERBASDIS.VALORORIGINAL,
PFVERBASDIS.VALOR,
PFVERBASDIS.DISSIDIO,
CONVERT(VARCHAR,PFVERBASDIS.DTPAGTO,103) AS 'DTPAGTO',
PFPERFF.MESCOMP,
PFPERFF.ANOCOMP,
PFVERBASDIS.NROPERIODO,
PFVERBASDIS.PERIODOREF

FROM PFUNC (NOLOCK)
INNER JOIN PFVERBASDIS	(NOLOCK) ON (PFVERBASDIS.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFVERBASDIS.CHAPA = PFUNC.CHAPA)
INNER JOIN PEVENTO		(NOLOCK) ON (PEVENTO.CODCOLIGADA = PFVERBASDIS.CODCOLIGADA AND PEVENTO.CODIGO = PFVERBASDIS.CODEVENTO)
INNER JOIN PDADOSDIS	(NOLOCK) ON (PDADOSDIS.CODCOLIGADA = PFVERBASDIS.CODCOLIGADA AND PDADOSDIS.ID = PFVERBASDIS.IDDADOS)
INNER JOIN PSECAO		(NOLOCK) ON (PSECAO.CODIGO = PFUNC.CODSECAO AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
INNER JOIN PFENCCC		(NOLOCK) ON (PFUNC.CODCOLIGADA = PFENCCC.CODCOLIGADA AND PFUNC.CHAPA = PFENCCC.CHAPA)
INNER JOIN PFPERFF		(NOLOCK) ON (PFPERFF.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFPERFF.CHAPA = PFUNC.CHAPA)

WHERE PFUNC.CODCOLIGADA = 38 
AND PFUNC.CHAPA = '00000046'
AND PFPERFF.ANOCOMP = 2024
AND PFPERFF.MESCOMP = 3

/*
WHERE PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
and PFUNC.CHAPA IS NOT NULL
AND PFVERBASDIS.ANOCOMP = @ANO
AND PFVERBASDIS.MESCOMP = @MES
*/

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PFPERFF'





SELECT 
PFUNC.CODCOLIGADA,
PFUNC.NOME AS 'NOME_FUNCIONARIO',
PFUNC.CHAPA,
PFUNC.CODFILIAL,
(SELECT TOP 1PFENCCC.CODPCCUSTO
 FROM PFENCCC
 WHERE PFUNC.CODCOLIGADA = PFENCCC.CODCOLIGADA AND PFUNC.CHAPA = PFENCCC.CHAPA) AS 'CENTRO_DE_CUSTO',
PFUNC.CODSITUACAO,
PFUNC.CODSECAO,
PFUNC.CODSINDICATO,
PSECAO.DESCRICAO AS 'NOME_SECAO',
PEVENTO.CODIGO,
PEVENTO.PROVDESCBASE,
PEVENTO.DESCRICAO,
PFVERBASDIS.IDDADOS,
(SELECT TOP 1 (CONVERT(VARCHAR,PDADOSDIS.TPACORDO) + CONVERT(VARCHAR,PFVERBASDIS.REF)) AS CODIGO_ACORDO
 FROM PDADOSDIS
 WHERE PDADOSDIS.CODCOLIGADA = PFVERBASDIS.CODCOLIGADA AND PDADOSDIS.ID = PFVERBASDIS.IDDADOS) AS ODIGO_ACORDO,
PFVERBASDIS.REF,
PFVERBASDIS.VALORORIGINAL,
--PFVERBASDIS.MESREF,
--PFVERBASDIS.ANOREF,
(CASE WHEN PEVENTO.CODIGO IN ('0003', '0724') THEN PFVERBASDIS.VALOR * (-1) ELSE PFVERBASDIS.VALOR END) AS VALOR,
PFVERBASDIS.DISSIDIO,
CONVERT(VARCHAR,PFVERBASDIS.DTPAGTO,103) AS 'DTPAGTO',
PFPERFF.MESCOMP AS 'PFPERFF.MESCOMP',
PFPERFF.ANOCOMP AS 'PFPERFF.ANOCOMP',
PFVERBASDIS.NROPERIODO,
PFVERBASDIS.PERIODOREF,
PFVERBASDIS.MESREF,
PFVERBASDIS.ANOREF


FROM PFUNC (NOLOCK)
INNER JOIN PFPERFF		(NOLOCK) ON (PFPERFF.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFPERFF.CHAPA = PFUNC.CHAPA)
INNER JOIN PFVERBASDIS	(NOLOCK) ON (PFVERBASDIS.CODCOLIGADA = PFPERFF.CODCOLIGADA AND PFVERBASDIS.CHAPA = PFPERFF.CHAPA AND PFVERBASDIS.MESCOMP = PFPERFF.MESCOMP AND PFVERBASDIS.ANOCOMP = PFPERFF.ANOCOMP AND  PFVERBASDIS.NROPERIODO = PFPERFF.NROPERIODO)
INNER JOIN PEVENTO		(NOLOCK) ON (PEVENTO.CODIGO = PFVERBASDIS.CODEVENTO AND PEVENTO.CODCOLIGADA = PFVERBASDIS.CODCOLIGADA)
INNER JOIN PSECAO		(NOLOCK) ON (PSECAO.CODIGO = PFUNC.CODSECAO AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA)

/*
WHERE PFUNC.CODCOLIGADA = 38 
AND PFUNC.CHAPA = '00000046'
AND PFPERFF.ANOCOMP = 2024
AND PFPERFF.MESCOMP = 3
AND PFVERBASDIS.NROPERIODO = 3
*/

WHERE PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
AND PFUNC.CHAPA IS NOT NULL
AND PFPERFF.ANOCOMP = @ANO
AND PFPERFF.MESCOMP = @MES
AND PFVERBASDIS.NROPERIODO = 3


GROUP BY 
PFUNC.CODCOLIGADA,
PFUNC.NOME ,
PFUNC.CHAPA,
PFUNC.CODFILIAL,
PFUNC.CODSITUACAO,
PFUNC.CODSECAO,
PFUNC.CODSINDICATO,
PSECAO.DESCRICAO,
PEVENTO.CODIGO,
PEVENTO.PROVDESCBASE,
PEVENTO.DESCRICAO,
PFVERBASDIS.IDDADOS,
--PDADOSDIS.TPACORDO,
PFVERBASDIS.CODCOLIGADA,
PFVERBASDIS.REF,
PFVERBASDIS.VALORORIGINAL,
PFVERBASDIS.MESREF,
PFVERBASDIS.ANOREF,
PFVERBASDIS.VALOR,
PFVERBASDIS.DISSIDIO,
PFVERBASDIS.DTPAGTO,
PFPERFF.MESCOMP,
PFPERFF.ANOCOMP,
PFVERBASDIS.NROPERIODO,
PFVERBASDIS.PERIODOREF
--PFFINANC.MESCOMP,
--PFFINANC.ANOCOMP

HAVING PFVERBASDIS.VALOR <> 0 AND PFVERBASDIS.VALORORIGINAL <> 0

ORDER BY 11


select * 
from MISM
where codism like '%fmod%'
order by 3

select * 
from mism 
where codism like 'fmod%' 
and idism <= '54819'