SELECT 
ASALDOBANCOHORFUNDETALHE.CODCOLIGADA
,PFUNC.CHAPA
,PFUNC.NOME

,(SELECT  
DBO.TRAHORA_FORMATADA(SUM(SALDO.VALORATUAL))
FROM ASALDOBANCOHORFUNDETALHE AS SALDO  (NOLOCK)  
INNER JOIN AEVECALC AS CALC             (NOLOCK) ON (CALC.CODCOLIGADA = SALDO.CODCOLIGADA AND CALC.CODEVENTO = SALDO.CODEVENTO)   
WHERE   
    SALDO.CHAPA = ASALDOBANCOHORFUNDETALHE.CHAPA 
    AND SALDO.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA  
    AND CALC.DESCRICAO LIKE '%EXTRA%'
)AS 'TOTAL_CREDITO - (HH:MM)'

,(SELECT  
    DBO.TRAHORA_FORMATADA(SUM(SALDO.VALORPERIODO))
    FROM ASALDOBANCOHORFUNDETALHE AS SALDO  (NOLOCK)  
    INNER JOIN AEVECALC AS CALC             (NOLOCK) ON (CALC.CODCOLIGADA = SALDO.CODCOLIGADA AND CALC.CODEVENTO = SALDO.CODEVENTO)   
    WHERE   
        SALDO.CHAPA = ASALDOBANCOHORFUNDETALHE.CHAPA 
        AND SALDO.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA  
        AND (CALC.DESCRICAO LIKE '%ATRASO%' OR CALC.DESCRICAO LIKE '%FALTAS%')
)AS 'TOTAL_DEBITO - (HH:MM)'


,dbo.MinutosParaHoraFormatada(  
        (  
            (SELECT  
                SUM(SALDO.VALORATUAL)  
            FROM ASALDOBANCOHORFUNDETALHE AS SALDO (NOLOCK)  
            INNER JOIN AEVECALC AS CALC (NOLOCK) ON (CALC.CODCOLIGADA = SALDO.CODCOLIGADA AND CALC.CODEVENTO = SALDO.CODEVENTO)   
            WHERE   
                SALDO.CHAPA = ASALDOBANCOHORFUNDETALHE.CHAPA   
                AND SALDO.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA  
                AND CALC.DESCRICAO LIKE '%EXTRA%'  
            )  
            -   
            (SELECT  
                SUM(SALDO.VALORPERIODO)  
            FROM ASALDOBANCOHORFUNDETALHE AS SALDO (NOLOCK)  
            INNER JOIN AEVECALC AS CALC (NOLOCK) ON (CALC.CODCOLIGADA = SALDO.CODCOLIGADA AND CALC.CODEVENTO = SALDO.CODEVENTO)   
            WHERE   
                SALDO.CHAPA = ASALDOBANCOHORFUNDETALHE.CHAPA   
                AND SALDO.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA  
                AND (CALC.DESCRICAO LIKE '%ATRASO%' OR CALC.DESCRICAO LIKE '%FALTAS%'))  
        )  
    ) AS 'SALDO_ATUAL - (HH:MM)'  



FROM ASALDOBANCOHORFUNDETALHE (NOLOCK)

INNER JOIN AEVECALC (NOLOCK) ON (AEVECALC.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA AND AEVECALC.CODEVENTO = ASALDOBANCOHORFUNDETALHE.CODEVENTO) 
INNER JOIN PFUNC    (NOLOCK) ON (PFUNC.CODCOLIGADA = ASALDOBANCOHORFUNDETALHE.CODCOLIGADA AND PFUNC.CHAPA = ASALDOBANCOHORFUNDETALHE.CHAPA)

--WHERE 
--ASALDOBANCOHORFUNDETALHE.CHAPA = '00017685' AND 
--ASALDOBANCOHORFUNDETALHE.CODCOLIGADA = 1

GROUP BY 
ASALDOBANCOHORFUNDETALHE.CODCOLIGADA
,ASALDOBANCOHORFUNDETALHE.CHAPA
,PFUNC.CHAPA
,PFUNC.NOME

ORDER BY
ASALDOBANCOHORFUNDETALHE.CODCOLIGADA
--,ASALDOBANCOHORFUNDETALHE.CHAPA
,PFUNC.NOME
--Expandir (70 linhas)