SELECT (GRUPO.VALOR_LINHA * GRUPO.QTD_PASSES) AS 'VALOR_DIARIO',
* 
FROM(

SELECT 
PFUNC.CODCOLIGADA, 
PFUNC.CODFILIAL, 
PFUNC.CHAPA, 
PFUNC.NOME, 
PPESSOA.CPF, 
PFUNC.DATAADMISSAO,  
PFUNCAO.CODIGO, 
PFUNCAO.NOME AS 'NOME_FUNCAO', 
'' AS 'RATEIO FIXO',
PFUNC.CODSECAO, 
PSECAO.DESCRICAO AS 'NOME_SEÇÃO', 
PFUNC.CODSITUACAO, 
PPESSOA.DTNASCIMENTO,
(PFUNC.CODHORARIO + ' - ' + AHORARIO.DESCRICAO) AS 'HORARIO',
(CASE WHEN PFCOMPL.CARTAOBHBUS IS NULL THEN 'OTIMO' ELSE 'BH BUSS' END) AS 'Operadora_VT',
(CASE WHEN PFCOMPL.CARTAOBHBUS IS NULL THEN PFCOMPL.CARTAOOTIMO ELSE PFCOMPL.CARTAOBHBUS END) AS 'NUM_CARTAOVT',
PTARIFA.VALOR AS 'VALOR_LINHA', 
PFVALETR.NROVIAGENS AS 'QTD_PASSES',
PFUNC.DIASUTPROXMES AS 'DIAS_UTEIS_MES', 
(PFVALETR.CODLINHA + ' -' + PVALETR.NOMELINHA) AS 'LINHA',
(SELECT COUNT(*)
 FROM PEVENTO
 WHERE CODEVENTO IN ('0594', '0614', '0104', '0338')), /*CONCLUIR O JOIN DAS FALTAS E ENTENDER COM A LANE OS FILTROS*/
'' AS 'FALTAS',
'' AS 'ATESTADOS',
'' AS 'FERIAS',
'' AS 'TOTAL',
'' AS 'SALDO_SITE_EM',
'' AS 'PROJEÇÃO',
'' AS 'Saldo P/ Aproveitar',
'' AS 'COMPRA SITE',
'' AS 'N° RDA',
'' AS 'N° NF',
'' AS 'OBS'


FROM PFUNC
INNER JOIN PFCOMPL			ON (PFCOMPL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFCOMPL.CHAPA = PFUNC.CHAPA)
INNER JOIN PPESSOA			ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
INNER JOIN PFUNCAO			ON (PFUNCAO.CODIGO = PFUNC.CODFUNCAO AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
INNER JOIN PSECAO			ON (PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO)
INNER JOIN PFVALETR			ON (PFVALETR.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFVALETR.CHAPA = PFUNC.CHAPA)
INNER JOIN PVALETR			ON (PVALETR.CODCOLIGADA = PFVALETR.CODCOLIGADA AND PVALETR.CODIGO = PFVALETR.CODLINHA)
INNER JOIN PTARIFA			ON (PTARIFA.CODCOLIGADA = PVALETR.CODCOLIGADA AND PTARIFA.CODIGO = PVALETR.CODTARIFA)
INNER JOIN AHORARIO			ON (AHORARIO.CODCOLIGADA = PFUNC.CODCOLIGADA AND AHORARIO.CODIGO = PFUNC.CODHORARIO)

WHERE PFUNC.CODCOLIGADA = 1 
AND PFUNC.CHAPA = '00024817'
) AS GRUPO


/*
SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PFUNC'
SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PVALETR'

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PFUNC'
AND CHILDTABLE LIKE '%COM%'

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PFHSTCOMPRAVT'

SELECT  *
FROM PFUNCCOMPL


SELECT  *
FROM ptarifa

SELECT  *
FROM PfVALETR
WHERE CODCOLIGADA = 'MG4'

*/