SELECT PFFINANC.CHAPA,
PFUNC.NOME AS NOME_FUNCIONARIO,
PFUNCAO.CODIGO AS CODIGO_FUNCAO,
PFUNCAO.NOME AS NOME_FUNCAO,
PSECAO.CODIGO AS QUEBRA$,
PSECAO.DESCRICAO AS DESCRICAO_SECAO,
PEVENTO.CODIGO AS CODIGO_DO_EVENTO,
PEVENTO.DESCRICAO AS DESCRICAO_EVENTO,
RIGHT (CONVERT(VARCHAR,PFFINANC.DTPAGTO,103),7) AS MESANO,
PEVENTO.VALHORDIAREF,
CASE WHEN PEVENTO.VALHORDIAREF <>'H' THEN PFFINANC.REF ELSE 0 END AS REF,
CASE WHEN PEVENTO.VALHORDIAREF='H' THEN PFFINANC.REF ELSE 0 END AS HORAS,
CASE WHEN PEVENTO.VALHORDIAREF='V' THEN PFFINANC.VALOR ELSE 0 END AS VALORES
FROM PFFINANC
       INNER JOIN pevento(nolock)   ON ( pevento.codcoligada = pffinanc.codcoligada     AND pevento.codigo = pffinanc.codevento ) 
       INNER JOIN PFUNC (nolock)   ON ( PFUNC.codcoligada = pffinanc.codcoligada     AND PFUNC.CHAPA = pffinanc.CHAPA ) 
       INNER JOIN PFUNCAO (nolock)   ON ( PFUNC.codcoligada = PFUNCAO.codcoligada     AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO ) 
       INNER JOIN PSECAO (nolock)   ON ( PFUNC.codcoligada = PSECAO.codcoligada     AND PFUNC.CODSECAO = PSECAO.CODIGO ) 
WHERE 
 PFUNCAO.CODCOLIGADA=PFUNC.CODCOLIGADA
AND PFUNCAO.CODIGO=PFUNC.CODFUNCAO
AND PFUNC.CODCOLIGADA=PFFINANC.CODCOLIGADA
AND PFUNC.CHAPA=PFFINANC.CHAPA
AND PFFINANC.CODCOLIGADA = :$CODCOLIGADA
AND PFUNC.CODSECAO >= :SECAO_INICIAL_S
AND PFUNC.CODSECAO <= :SECAO_FINAL_S
AND PFFINANC.MESCOMP = :MES_COMP
AND PFFINANC.ANOCOMP = :ANO_COMP
AND PFUNC.CODSITUACAO<>'D'
AND PFFINANC.CODEVENTO in ('0054','0008','0614','0280','0104','0630','0620','0625','0083','0060','550',
'0593','0056','0055','0224','0540','0336','0337','0343','0344','0311','0367',
'0312','551','0592','0008','0338','0627','0594','0628','0608','0624',
'0065','0083','0060','0417','DICN','DIML','DIMO','DIMS','DISV','EQBL','EQEL','EQFU','EQHS',
'EQPA','MTBL','MTFU','STAL','STBA','STBF','STBL','STCC','STCT','STEL','STFU','STHS',
'STMU','STPA','STPG','STPP')


order by PEVENTO.CODIGO,
PFUNC.NOME,
QUEBRA$
