
SELECT 
PFUNC.CHAPA, 
PFUNC.NOME AS NOME_FUNCIONARIO, 
PFUNCAO.NOME AS NOME_CARGO,
FORMAT(PFUNC.DATAADMISSAO, 'dd/MM/yyyy') AS DATAADMISSAO,
PSECAO.CODIGO,
PSECAO.DESCRICAO,
FORMAT(PFUNC.DTVENCFERIAS, 'dd/MM/yyyy') AS DATAVENCIFERIAS,
	(SELECT TOP 1 NROAVOSVENCFERDEC 
	FROM PFHSTPROV (NOLOCK)
	WHERE PFHSTPROV.CHAPA = PFUNC.CHAPA 
	AND PFHSTPROV.CODCOLIGADA = PFUNC.CODCOLIGADA) AS AVOS_VENCIDOS,
	(SELECT TOP 1 NROAVOSPROPORCDEC 
	FROM PFHSTPROV (NOLOCK)
	WHERE PFHSTPROV.CHAPA = PFUNC.CHAPA 
	AND PFHSTPROV.CODCOLIGADA = PFUNC.CODCOLIGADA) AS MESES,
FORMAT((DATEADD(MONTH, 11, PFUNC.DTVENCFERIAS)), 'dd/MM/yyyy' )AS LIMITE_CONCESSÃO,

			(CASE
				WHEN PFUNC.dtvencferias <=GETDATE()
				then 'POSSUI FERIAS VENCIDAS' 
			else 'NÃO POSSUI FERIAS VENCIDAS' end) AS POSSUI_FERIAS_VENCIDAS

FROM PFUNC (NOLOCK)
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
LEFT JOIN PFHSTFER					(NOLOCK)			ON			(PFUNC.CHAPA = PFHSTFER.CHAPA AND  PFHSTFER.CODCOLIGADA = PFUNC.CODCOLIGADA)


WHERE  PSECAO.CODIGO >= :SECAO_INI AND PSECAO.CODIGO <= :SECAO_FIM
AND PFUNC.CODCOLIGADA = :$CODCOLIGADA
AND CODSITUACAO <> 'D'
/*
WHERE  PSECAO.CODIGO >= '01.500.20' AND PSECAO.CODIGO <= '01.500.33'
AND PFUNC.CODCOLIGADA = '1'
AND CODSITUACAO <> 'D'
*/
GROUP BY 
PFUNC.CODCOLIGADA,
PFUNC.CHAPA, 
PFUNC.NOME, 
PFUNCAO.NOME,
PFUNC.DATAADMISSAO,
PSECAO.CODIGO,
PSECAO.DESCRICAO,
PFUNC.DTVENCFERIAS,
PFUNC.DTVENCFERIAS,
PFUNC.dtvencferias 


--SELECT TOP 1 * FROM PFHSTPROV WHERE CHAPA = '00024817'

--SELECT * FROM PFUNC WHERE NOME LIKE '%HIAGO%FERREIRA%'