
SELECT 
SUM(GRUPO.FALTA_DIA + (GRUPO.FALTA_HORA/7.33)) AS TOTAL_FALTAS 
FROM(
SELECT  
PFUNC.NOME,
PFUNC.CODCOLIGADA AS COLIG, 
PFFINANC.REF,

(SELECT TOP 1 MAX(INICIOPERAQUIS)
 FROM PFUFERIAS
 WHERE PERIODOABERTO <> 1
 AND PFUNC.CHAPA = PFUFERIAS.CHAPA 
 AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA)AS INI_PER_FER,

(SELECT TOP 1 MAX(FIMPERAQUIS)
 FROM PFUFERIAS
 WHERE PERIODOABERTO <> 1
 AND PFUNC.CHAPA = PFUFERIAS.CHAPA 
 AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA)AS FIM_PER_FER,
/*
PFUFERIAS.INICIOPERAQUIS AS INI_PER_FER,
PFUFERIAS.FIMPERAQUIS AS FIM_PER_FER,
*/
PFFINANC.DTPAGTO,
PFFINANC.MESCOMP AS MES_COMP,
PFFINANC.ANOCOMP AS ANO_COMP,
(CASE WHEN PEVENTO.CODIGO IN ('0594', '0338', '0417') THEN PFFINANC.REF ELSE 0 END) AS FALTA_DIA,
(CASE WHEN PEVENTO.CODIGO IN ('0104', '0614', '0143') THEN PFFINANC.REF ELSE 0 END) AS FALTA_HORA

FROM PFFINANC 

INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
--INNER JOIN PFUFERIAS (NOLOCK) ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PERIODOABERTO = 1)

WHERE 
	PFUNC.CHAPA IN ('00000038')
    AND PFFINANC.CODCOLIGADA IN (59)
    AND PFFINANC.NROPERIODO = 3
	AND PEVENTO.PROVDESCBASE <> 'B'

	) AS GRUPO
	WHERE GRUPO.DTPAGTO BETWEEN INI_PER_FER AND FIM_PER_FER
	--AND GRUPO.MES_COMP BETWEEN MONTH(GRUPO.INI_PER_FER) AND MONTH(GRUPO.FIM_PER_FER)
	AND (FALTA_DIA <> 0 OR FALTA_HORA <> 0)

	/*SELECT * 
	FROM PFUNC 
	WHERE NOME = 'AMANDA CAROLINA DUARTE'*/

