SELECT 
CAST(
    CASE 
		/* CASE DOS DEMITIDOS */
		/*SIND 002*/
		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND (GRUPO.CODSINDICATO = '0002' )
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE_BH 
		THEN 
			(GRUPO.SALARIO / GRUPO.JORNADA) * 80
		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND (GRUPO.CODSINDICATO = '0002' )
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE_BH 
		THEN 
			(GRUPO.SALARIO_BASE_BH / GRUPO.JORNADA) * 80

		/*FIM SIND 002*/
		/*SIND 039*/

		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND (GRUPO.CODSINDICATO = '0039')
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE_BH 
		THEN 
			(GRUPO.SALARIO / GRUPO.JORNADA) * 80
		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND (GRUPO.CODSINDICATO = '0039' )
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE_BH 
		THEN 
			(GRUPO.SALARIO_BASE_BH / GRUPO.JORNADA) * 80

		/*FIM SIND 039*/
		/*SIND 011*/

		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND GRUPO.CODSINDICATO = '0011'
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE_CONT 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
		WHEN
			GRUPO.CODSITUACAO = 'D'
			AND GRUPO.CODSINDICATO = '0011' 
			AND GRUPO.DEMITIDO_COM_EVENTO = 'SIM'
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE_CONT 
		THEN 
            (GRUPO.SALARIO_BASE_CONT / GRUPO.JORNADA) * 80

		/*FIM SIND 011*/
		/*FIM DO CASE DOS DEMITIDOS */

		/* FUNCIONARIOS ATIVOS*/
		/*SIND 002*/
        WHEN 
			GRUPO.CODSINDICATO = '0002' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE_BH 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0002' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL) 
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE_BH 
		THEN 
            (GRUPO.SALARIO_BASE_BH / GRUPO.JORNADA) * 80

		/*FIM SIND 002*/
		/*SIND 039*/

		WHEN 
			GRUPO.CODSINDICATO = '0039' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE__0039 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0039' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL) 
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE__0039 
		THEN 
            (GRUPO.SALARIO_BASE__0039 / GRUPO.JORNADA) * 80

		/*FIM SIND 039*/
		/*SIND 011*/

        WHEN GRUPO.CODSINDICATO = '0011' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.SALARIO_BASE_CONT 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0011'
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO >= GRUPO.SALARIO_BASE_CONT 
		THEN 
            (GRUPO.SALARIO_BASE_CONT / GRUPO.JORNADA) * 80
		/*FIM SIND 011*/
        ELSE 
            0
    END AS DECIMAL(10, 2)) AS 'VALOR DE ABONO' 
    /* FIM DO CASE DOS ATIVOS*/
FROM 
(
SELECT  
CODSINDICATO,
220 AS JORNADA, 
CAST((CASE WHEN PVALFIX.CODIGO = '0002' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))AS 'SALARIO_BASE_BH',
CAST((CASE WHEN PVALFIX.CODIGO = '0011' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))AS 'SALARIO_BASE_CONT',
CAST((CASE WHEN PVALFIX.CODIGO = '0039' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))AS 'SALARIO_BASE__0039',
CAST((PFUNC.SALARIO) AS DECIMAL (10, 2))  AS SALARIO,
PPARAM.MESCOMP,
PPARAM.ANOCOMP,
PFUFERIAS.SALDO,
PFUNC.NOME,
PFUNC.CHAPA,
PFUNC.CODSITUACAO,
(SELECT TOP 1 MAX(PFUFERIASPER1.DATAINICIO) 
FROM PFUFERIASPER as PFUFERIASPER1
WHERE PFUFERIASPER1.SITUACAOFERIAS IN ('F', 'P')
AND PFUFERIASPER1.CHAPA = PFUFERIAS.CHAPA 
AND PFUFERIASPER1.CODCOLIGADA = PFUFERIAS.CODCOLIGADA
/*AND PFUFERIASPER1.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS*/) AS DATA_INICIO,
(SELECT TOP 2 MAX(PFUFERIASPER2.DATAFIM)
FROM PFUFERIASPER AS  PFUFERIASPER2
WHERE  PFUFERIASPER2.SITUACAOFERIAS IN ('F', 'P')
AND PFUFERIASPER2.CHAPA = PFUFERIAS.CHAPA 
AND PFUFERIASPER2.CODCOLIGADA = PFUFERIAS.CODCOLIGADA
/*AND PFUFERIASPER2.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS*/) AS DATA_FIM,

(SELECT (CASE 
			WHEN G.ANO = 1
             AND G.MES = 1
             AND EXISTS (
                 SELECT 1 
                 FROM PFFINANC AS PFFINANC1 
                 WHERE PFFINANC1.CODEVENTO = '0024' 
                   AND PFFINANC1.CHAPA = G.CHAPA AND PFFINANC1.CODCOLIGADA = G.CODCOLIGADA)
			THEN 'SIM'
			ELSE 'NÃO' 
    END) AS 'DEMITIDO COM EVENTO'
FROM (
    SELECT TOP 1
		PFFINANC.CHAPA,
		PFFINANC.CODCOLIGADA,
        CASE WHEN PFFINANC.ANOCOMP = PPARAM1.ANOCOMP THEN 1 ELSE 0 END AS ANO,
        CASE WHEN PFFINANC.MESCOMP = PPARAM1.MESCOMP THEN 1 ELSE 0 END AS MES
    FROM PFFINANC						(NOLOCK)
    INNER JOIN PEVENTO					(NOLOCK) ON PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA
    INNER JOIN PFUNC AS PFUNC1			(NOLOCK) ON PFUNC1.CHAPA = PFFINANC.CHAPA AND PFUNC1.CODCOLIGADA = PFFINANC.CODCOLIGADA
    INNER JOIN PPARAM AS PPARAM1 		(NOLOCK) ON PFUNC1.CODCOLIGADA = PPARAM1.CODCOLIGADA
    WHERE PFUNC1.CODCOLIGADA IN (PFUNC.CODCOLIGADA)
    AND PFUNC1.CHAPA IN (PFUNC.CHAPA)
    ORDER BY PFFINANC.ANOCOMP DESC, PFFINANC.MESCOMP DESC
) AS G) AS 'DEMITIDO_COM_EVENTO'

FROM PFUNC 					(NOLOCK)
LEFT JOIN PVALFIX 			(NOLOCK)			ON (PVALFIX.CODCOLIGADA = PFUNC.CODCOLIGADA AND PVALFIX.CODIGO = PFUNC.CODSINDICATO)
LEFT JOIN PFUFERIAS			(NOLOCK)			ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIAS.PERIODOABERTO = 1)
INNER JOIN PPARAM			(NOLOCK)			ON (PFUNC.CODCOLIGADA = PPARAM.CODCOLIGADA)

WHERE
PFUNC.codcoligada IN (:FRM_COLIGADA) 
and PFUNC.chapa IN (:FRM_CHAPA)

) AS GRUPO

order by 1 DESC

/*
WHERE
PFUNC.CODCOLIGADA IN (24) 
AND PFUNC.CHAPA IN ('00000082')

SELECT * 
FROM GLINKSREL 
WHERE MASTERTABLE = 'PFUFERIASPER'

SELECT DISTINCT SITUACAOFERIAS, CHAPA, CODCOLIGADA 
FROM PFUFERIASPER
WHERE SITUACAOFERIAS = 'D'

M = MARCADAS 
G = AGURDANDO GESTOR
F = FINALIZADAS 
P = PAGAS 
D = AGUARDANDO APROVAÇÃO DO DP
*/