SELECT 
CHAPA, 
PFUNC.NOME AS NOME_FUNCIONARIO, 
PFUNCAO.NOME AS NOME_CARGO,
PSECAO.DESCRICAO,
PFUNC.DATAADMISSAO,
PFUNC.SALARIO,
(CASE WHEN PFUNC.TIPOADMISSAO = 'E' THEN 'ENTRADA TRANFERENCIA COM ONUS PARA O CEDENTE'
	  WHEN PFUNC.TIPOADMISSAO = 'I' THEN 'REINTEGRAÇÃO'
	  WHEN PFUNC.TIPOADMISSAO = 'P' THEN 'PRIMEIRO EMPREGO'
	  WHEN PFUNC.TIPOADMISSAO = 'R' THEN 'REEMPREGO'
	  WHEN PFUNC.TIPOADMISSAO = 'T' THEN 'ENTRADA TRANFERENCIA SEM ONUS PARA O CEDENTE'
	  ELSE 'OUTROS CASOS'END) AS TIPO_DE_ADMISSAO

FROM PFUNC
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
/*
WHERE PFUNC.CODCOLIGADA = :$CODCOLIGADA
AND PSECAO.codigo BETWEEN :SECAO_INI AND :SECAO_FIM
AND PFUNC.DATAADMISSAO BETWEEN :ADMI_INI AND :ADMI_FIM
AND PFUNC.CODSITUACAO <> 'D'
*/

WHERE PFUNC.CODCOLIGADA = 1
AND PSECAO.codigo BETWEEN '01.500.20' AND '01.500.21'
AND PFUNC.DATAADMISSAO BETWEEN '20230101' AND '20240401'
AND PFUNC.CODSITUACAO <> 'D'

GROUP BY CHAPA,
PFUNC.NOME,
PFUNCAO.NOME,
PSECAO.DESCRICAO,
PFUNC.DATAADMISSAO,
PFUNC.TIPOADMISSAO,
PFUNC.SALARIO

ORDER BY 2