SELECT 
CHAPA, 
PFUNC.NOME AS NOME_FUNCIONARIO, 
PFUNCAO.NOME AS NOME_CARGO,
PFUNC.CODRECEBIMENTO,
PSECAO.DESCRICAO,
PSECAO.CODIGO,
PFUNC.DATAADMISSAO,
PFUNC.SALARIO

FROM PFUNC
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)

WHERE PFUNC.CODCOLIGADA IN (:$CODCOLIGADA)
AND PSECAO.codigo BETWEEN :SECAO_INI AND :SECAO_FIM  
AND PFUNC.CODSITUACAO <> 'D'


GROUP BY CHAPA,
PFUNC.NOME,
PFUNCAO.NOME,
PSECAO.DESCRICAO,
PFUNC.DATAADMISSAO,
PFUNC.TIPOADMISSAO,
PFUNC.SALARIO,
PFUNC.CODRECEBIMENTO,
PSECAO.CODIGO

ORDER BY 2