SELECT 
CHAPA, 
PFUNC.NOME AS NOME_FUNCIONARIO, 
PFUNCAO.NOME AS NOME_CARGO,
PSECAO.DESCRICAO AS DESCRICAOSECAO,
STUFF(STUFF(STUFF(PPESSOA.CPF, 10, 0, '-'), 7, 0, '.'), 4, 0, '.') AS CPF,
PFUNC.DATAADMISSAO,
pfunc.CODAGENCIAPAGTO AS AGENCIA,
PFUNC.CONTAPAGAMENTO AS CONTA_FUNCIONARIO,
PSECAO.NROCENCUSTOCONT,
PSECAO.CEI,
    LEFT(PSECAO.COMPLEMENTOGRPS2, CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) - 1) AS OBRA,
    SUBSTRING(
        PSECAO.COMPLEMENTOGRPS2, 
        CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) + 1, 
        CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2, CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) + 1) - CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) - 1
    ) AS CENTRODECUSTO,
    SUBSTRING(
        PSECAO.COMPLEMENTOGRPS2, 
        CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2, CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) + 1) + 1, 
        LEN(PSECAO.COMPLEMENTOGRPS2) - CHARINDEX('-', REVERSE(PSECAO.COMPLEMENTOGRPS2)) - CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2, CHARINDEX('-', PSECAO.COMPLEMENTOGRPS2) + 1)
    ) AS CONTA

FROM PFUNC
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
LEFT JOIN PPESSOA					(NOLOCK)			ON			(PPESSOA.CODIGO = PFUNC.CODPESSOA)

WHERE PFUNC.CODCOLIGADA IN (:$CODCOLIGADA)
AND PSECAO.codigo BETWEEN :SECAO_INI AND :SECAO_FIM 
AND PFUNC.DATAADMISSAO BETWEEN :ADMI_INI AND :ADMI_FIM


GROUP BY CHAPA,
PFUNC.NOME,
PFUNCAO.NOME,
PSECAO.DESCRICAO,
PFUNC.DATAADMISSAO,
PFUNC.TIPOADMISSAO,
PPESSOA.CPF,
PFUNC.SALARIO,
pfunc.CODAGENCIAPAGTO,
PFUNC.CONTAPAGAMENTO,
PSECAO.NROCENCUSTOCONT,
PSECAO.CEI,
COMPLEMENTOGRPS2

ORDER BY 2