select 
CAST(
    CASE 
        WHEN 
			GRUPO.CODSINDICATO = '0002' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.salario_base_bh 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0002' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL) 
			AND GRUPO.SALARIO >= GRUPO.salario_base_bh 
		THEN 
            (GRUPO.salario_base_bh / GRUPO.JORNADA) * 80
		WHEN 
			GRUPO.CODSINDICATO = '0039' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.salario_base__0039 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0039' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL) 
			AND GRUPO.SALARIO >= GRUPO.salario_base__0039 
		THEN 
            (GRUPO.salario_base__0039 / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0011' 
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO < GRUPO.salario_base_cont 
		THEN 
            (GRUPO.SALARIO / GRUPO.JORNADA) * 80
        WHEN GRUPO.CODSINDICATO = '0011'
			AND MONTH(GRUPO.DATA_FIM) = GRUPO.MESCOMP
			AND YEAR(GRUPO.DATA_FIM) = GRUPO.ANOCOMP
			AND GRUPO.CODSITUACAO <> 'D' 
			AND (GRUPO.SALDO = 0 OR GRUPO.SALDO IS NULL)
			AND GRUPO.SALARIO >= GRUPO.salario_base_cont 
		THEN 
            (GRUPO.salario_base_cont / GRUPO.JORNADA) * 80
        ELSE 
            0
    END AS DECIMAL(10, 2)
) AS 'VALOR DE ABONO'
from 
(
SELECT  CODSINDICATO,
220 AS JORNADA, 

CAST((CASE WHEN PVALFIX.CODIGO = '0002' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))as 'salario_base_bh',
CAST((CASE WHEN PVALFIX.CODIGO = '0011' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))as 'salario_base_cont',
CAST((CASE WHEN PVALFIX.CODIGO = '0039' THEN PVALFIX.VALOR ELSE '0' END)AS DECIMAL (10, 2))as 'salario_base__0039',
CAST((PFUNC.SALARIO) AS DECIMAL (10, 2))  AS SALARIO,
PPARAM.MESCOMP,
PPARAM.ANOCOMP,
PFUFERIAS.SALDO,
PFUNC.NOME,
PFUNC.CHAPA,
PFUNC.CODSITUACAO,
(SELECT TOP 1 MAX(PFUFERIASPER.DATAINICIO) 
FROM PFUFERIASPER 
WHERE PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA 
AND PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA) AS DATA_INICIO,
(SELECT TOP 1 MAX(PFUFERIASPER.DATAFIM) 
FROM PFUFERIASPER 
WHERE PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA 
AND PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA) AS DATA_FIM

FROM PFUNC 					(NOLOCK)
left JOIN PVALFIX 			(NOLOCK)			ON (PVALFIX.CODCOLIGADA = PFUNC.CODCOLIGADA AND PVALFIX.CODIGO = PFUNC.CODSINDICATO)
LEFT JOIN PFUFERIAS			(NOLOCK)			ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIAS.PERIODOABERTO = 1)
INNER JOIN pparam			(NOLOCK)			ON (PFUNC.CODCOLIGADA = pparam.CODCOLIGADA)
/*INNER JOIN PFUFERIASPER	(NOLOCK)			ON (PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA AND PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA)*/

WHERE
PFUNC.codcoligada IN (:FRM_COLIGADA) 
and PFUNC.chapa IN (:FRM_CHAPA)

/*
WHERE
PFUNC.codcoligada IN (1) 
and PFUNC.chapa IN ('00018316')
*/
)AS GRUPO

