
SELECT 
SUM(GRUPO.FALTA_DIA + (GRUPO.FALTA_HORA/7.33)) AS TOTAL_FALTAS,
GRUPO.COLIG, 
GRUPO.NOME
FROM(
SELECT  
PFUNC.NOME,
PFUNC.CODCOLIGADA AS COLIG, 
PFFINANC.REF,
PFUFERIAS.INICIOPERAQUIS AS INI_PER_FER,
PFUFERIAS.FIMPERAQUIS AS FIM_PER_FER,
(CASE WHEN PEVENTO.CODIGO IN ('0594', '0338', '0417') THEN PFFINANC.REF ELSE 0 END) AS FALTA_DIA,
(CASE WHEN PEVENTO.CODIGO IN ('0104', '0614') THEN PFFINANC.REF ELSE 0 END) AS FALTA_HORA

FROM PFFINANC 

INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUFERIAS (NOLOCK) ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PERIODOABERTO = 1)

WHERE 
    PFFINANC.ANOCOMP BETWEEN YEAR(PFUFERIAS.INICIOPERAQUIS) AND YEAR(PFUFERIAS.FIMPERAQUIS)
	AND PFUNC.CHAPA IN (:FRM_CHAPA)
    AND PFFINANC.CODCOLIGADA IN (:FRM_COLIGADA)
    AND PFFINANC.NROPERIODO = 3
	AND   PEVENTO.PROVDESCBASE <> 'B'
	) AS GRUPO

	GROUP BY 
	GRUPO.COLIG,
	GRUPO.NOME

