select 
				PSECAO.NROCENCUSTOCONT + ' - ' + 
				(select GCCUSTO.NOME 
				from GCCUSTO 
				WHERE GCCUSTO.CODCCUSTO = PSECAO.NROCENCUSTOCONT AND GCCUSTO.CODCOLIGADA = PSECAO.CODCOLIGADA)  
				as ccusto$,
				PFUNC.CHAPA,
				LEFT (pfunc.nome,43) AS NOME, 
				LEFT (PFUNCAO.NOME,30) AS FUNCAO,
				max(case when PEVENTO.PROVDESCBASE = 'B' and left(PEVENTO.CODIGO,1) in ('S','M','E','D') then left (PEVENTO.DESCRICAO,30) END) as SUBCLASE,
				min(case when PEVENTO.PROVDESCBASE = 'B' and left(PEVENTO.CODIGO,1) in ('S','M','E','D') then Left(PEVENTO.CODIGO,2) END) as CLASSE
				
		FROM PFFINANC
		
				INNER JOIN PFUNC   (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
				INNER JOIN PEVENTO (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
				INNER JOIN PSECAO  (NOLOCK) ON (PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
				INNER JOIN PFUNCAO (NOLOCK) ON (PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO)
		where 
		
				PFFINANC.CODCOLIGADA IN (:$CODCOLIGADA)
                                AND PFFINANC.NROPERIODO = 3
                                AND PSECAO.NROCENCUSTOCONT NOT LIKE '1.%'
				AND PSECAO.NROCENCUSTOCONT BETWEEN :CCUSTOINI AND :CCUSTOFIN
				AND PFFINANC.DTPAGTO BETWEEN :DATAPAGINI AND :DATAPAGFIN
                                AND (SELECT MAX(DTMUDANCA) FROM PFHSTSEC WHERE CHAPA = PFFINANC.CHAPA) <= PFFINANC.DTPAGTO 
							
group by PFUNC.NOME, PSECAO.NROCENCUSTOCONT, PFFINANC.CODCOLIGADA, PFUNC.CHAPA, PFUNCAO.NOME, PSECAO.CODCOLIGADA
order by ccusto$, PFUNC.NOME