DECLARE @CODCOLIGADA AS INT = 1;

SELECT  

CONVERT (VARCHAR,PFUNC.CODCOLIGADA) + '-' + CONVERT (VARCHAR,PFUNC.CHAPA) AS 'COLIGADA E CHAPA',
REPLACE(REPLACE(REPLACE(REPLACE(PSECAO.CGC, '.', ''), '-', ''), '/', ''), ' ', '') AS 'CNPJ',
  /*SUBSTRING(PSECAO.CGC, 1, 2) +  
  SUBSTRING(PSECAO.CGC, 3, 4) + 
  SUBSTRING(PSECAO.CGC, 7, 4) + 
  SUBSTRING(PSECAO.CGC, 11, 5) + '-' + 
  SUBSTRING(PSECAO.CGC, 13, 2) AS 'CNPJ',*/
PFUNC.CODSINDICATO AS 'CODIGO SINDICATO',
PFUNC.PISPASEP AS 'PIS PASEP',
/*PFUNC.TPCONTABANCARIA AS 'TP CONTA1',*/
(CASE 
	WHEN PFUNC.TPCONTABANCARIA = 1 THEN 'CORRENTE'
	WHEN PFUNC.TPCONTABANCARIA = 2 THEN 'POUPANÇA'
	WHEN PFUNC.TPCONTABANCARIA = 3 THEN 'SALÁRIO'
	END ) AS 'TP CONTA1',
(CASE 
	WHEN PFUNC.TPCONTABANCARIA2 = 1 THEN 'CORRENTE'
	WHEN PFUNC.TPCONTABANCARIA2 = 2 THEN 'POUPANÇA'
	WHEN PFUNC.TPCONTABANCARIA2 = 3 THEN 'SALÁRIO'
	END ) AS 'TP CONTA2',
CONVERT(VARCHAR,PFUNC.FIMPRAZOCONTR,103) as '1º VENC CONTRATO',

COALESCE((SELECT TOP 1 (CASE WHEN AHSTUTILIZAPONTO.UTILIZA = 1 THEN 'SIM' ELSE 'NAO' END) AS 'UTILIZA_PONTO'
 FROM AHSTUTILIZAPONTO 
 WHERE PFUNC.CODCOLIGADA = AHSTUTILIZAPONTO.CODCOLIGADA AND PFUNC.CHAPA = AHSTUTILIZAPONTO.CHAPA
 ORDER BY AHSTUTILIZAPONTO.DATAINICIO DESC), 'NAO') AS 'UTILIZA_PONTO',

/*(CASE WHEN AHSTUTILIZAPONTO.UTILIZA = 1 THEN 'SIM' ELSE 'NÃO' END) AS 'UTILIZA_PONTO',*/

(SELECT TOP 1 APARCOL.DESCRICAO  
FROM APARFUN
INNER JOIN APARCOL ON APARCOL.CODCOLIGADA = APARFUN.CODCOLIGADA AND APARCOL.CODIGO = APARFUN.CODPARCOL
WHERE APARFUN.CODCOLIGADA IN (PFUNC.CODCOLIGADA) 
AND APARFUN.CHAPA IN (PFUNC.CHAPA)) AS 'SIND_PARAMETRIZADO',
PFCOMPL.TIPOPLANOBRA AS 'PLANO SAUDE',
(CASE WHEN PFCOMPL.SUBSIDIADOUNIMED = 'F' THEN 'NÃO' 
	  WHEN PFCOMPL.SUBSIDIADOUNIMED = 'T' THEN 'SIM' 
	  ELSE 'NÃO' END) AS 'ISENTO DESC SAUDE',
/*PFCOMPL.ASSISTODON AS 'PLANO ODONTO',*/
(SELECT TOP 1 GCONSIST.DESCRICAO
 FROM GCONSIST
 WHERE PFCOMPL.ASSISTODON = GCONSIST.CODINTERNO) AS 'PLANO_ODONTO',
PFCOMPL.OPERADORA_TICKET AS 'OPERADORA VR/VA',
/*(CASE	WHEN PFCOMPL.TPREGRAVR = 0 THEN 'NÃO UTILIZA'
		WHEN PFCOMPL.TPREGRAVR = 1 THEN 'VALOR DIARIO'
		WHEN PFCOMPL.TPREGRAVR = 2 THEN 'CESTA BASICA - CARTAO ALIMENTACAO'
		WHEN PFCOMPL.TPREGRAVR = 3 THEN 'ALOJADO'
		WHEN PFCOMPL.TPREGRAVR = 4 THEN 'VR DIARIO + CAFE M'
		WHEN PFCOMPL.TPREGRAVR = 5 THEN 'VR DIARIO + CAFE M/T'
		WHEN PFCOMPL.TPREGRAVR = 6 THEN 'CESTA IN NATURA'
		END) AS 'REGRA VR-VA',*/ 
		(CASE WHEN PFUNC.INTEGRCONTABIL = 1 THEN 'CUSTO DIRETO'
			  WHEN PFUNC.INTEGRCONTABIL = 2 THEN 'CUSTO INDIRETO'
			  WHEN PFUNC.INTEGRCONTABIL = 3 THEN 'DESPESA'
			  WHEN PFUNC.INTEGRCONTABIL = 4 THEN 'VENDAS'
			  END) AS 'INTEGRAÇÃO CONTABIL',
		(SELECT TOP 1 GCONSIST.DESCRICAO
		FROM GCONSIST
		WHERE CODTABELA = 'TPREGRAVR' 
		AND GCONSIST.CODCLIENTE = PFCOMPL.TPREGRAVR) AS 'REGRA VR-VA',
(CASE	WHEN PFCOMPL.OPVT = 0 THEN 'NAO UTILIZA'
		WHEN PFCOMPL.OPVT = 1 THEN 'VALE TRANSPORTE'
		WHEN PFCOMPL.OPVT = 2 THEN 'VALE COMBUSTIVEL'
		ELSE 'NÃO UTILIZA' END) AS 'VT',
PFCOMPL.CARTAOBHBUS AS 'CARTAO BHBUS',
PFCOMPL.OTIMO AS 'CARTAO OTIMO',
PFCOMPL.SPVALE AS 'CARTAO VTSP1',
PFCOMPL.SPTRANS AS 'CARTAO VTSP2', 
PFCOMPL.SP3 AS 'CARTAO VTSP3',
PFCOMPL.MATRICULARIOCARD AS 'CARTAO RIO CARD',
PFCOMPL.CARTAORJ_JAE AS 'CARTAO RIO JAE',
PFUNC.CODEQUIPE AS 'COD EQUIPE',
PFUNC.CODGRPQUIOSQUE AS 'COD GRP QUIOSQUE',
PPESSOA.CODUSUARIO AS 'COD USUARIO',

	(CASE WHEN 
		(SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(CHEFE.NOME, ' / '))
		FROM PSUBSTCHEFE (NOLOCK)
		INNER JOIN PFUNC AS CHEFE		(NOLOCK) ON (PSUBSTCHEFE.CODCOLIGADA = CHEFE.CODCOLIGADA AND PSUBSTCHEFE.CHAPASUBST = CHEFE.CHAPA)
		WHERE PSUBSTCHEFE.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTCHEFE.CODSECAO = PFUNC.CODSECAO AND PSUBSTCHEFE.DATAFIM IS NULL)    IS NULL THEN 
			 (SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(CHEFE.NOME, ' / '))
			 FROM PCHEFEEXTERNO CHEFEEXT (NOLOCK)
			 INNER JOIN PEXTERNO (NOLOCK) ON (PEXTERNO.CODCOLIGADA = CHEFEEXT.CODCOLIGADA AND PEXTERNO.CODEXTERNO = CHEFEEXT.CODEXTERNO)
			 INNER JOIN PPESSOA AS CHEFE		(NOLOCK) ON (PEXTERNO.CODPESSOA = CHEFE.CODIGO)
			 WHERE CHEFEEXT.CODCOLIGADA = PFUNC.CODCOLIGADA AND CHEFEEXT.CODSECAO = PFUNC.CODSECAO AND CHEFEEXT.DATAFIM IS NULL) ELSE 	
		(SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(CHEFE.NOME, ' / '))
		FROM PSUBSTCHEFE (NOLOCK)
		INNER JOIN PFUNC AS CHEFE		(NOLOCK) ON (PSUBSTCHEFE.CODCOLIGADA = CHEFE.CODCOLIGADA AND PSUBSTCHEFE.CHAPASUBST = CHEFE.CHAPA)
		WHERE PSUBSTCHEFE.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTCHEFE.CODSECAO = PFUNC.CODSECAO AND PSUBSTCHEFE.DATAFIM IS NULL)
		END) AS 'CHEFE', 

	(CASE WHEN (SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(SUPER.NOME, ' / '))
	 FROM  PSUBSTSUP (NOLOCK)
	 INNER JOIN PFUNC AS SUPER		(NOLOCK) ON (PSUBSTSUP.CODCOLIGADA = SUPER.CODCOLIGADA AND PSUBSTSUP.CHAPASUBST = SUPER.CHAPA)
	 WHERE PSUBSTSUP.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTSUP.CODSECAO = PFUNC.CODSECAO AND PSUBSTSUP.DATAFIM IS NULL) IS NULL THEN 
		(SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(SUPER.NOME, ' / '))
		 FROM  PSUBSTSUP (NOLOCK)
		 INNER JOIN PEXTERNO			(NOLOCK) ON (PEXTERNO.CODCOLIGADA = PSUBSTSUP.CODCOLIGADA AND PEXTERNO.CODEXTERNO = PSUBSTSUP.CHAPASUBST)
		 INNER JOIN PPESSOA AS SUPER	(NOLOCK) ON (PEXTERNO.CODPESSOA = SUPER.CODIGO)
		 WHERE PSUBSTSUP.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTSUP.CODSECAO = PFUNC.CODSECAO AND PSUBSTSUP.DATAFIM IS NULL) ELSE 
	(SELECT TOP 1 CONVERT(VARCHAR(MAX), STRING_AGG(SUPER.NOME, ' / '))
	 FROM  PSUBSTSUP (NOLOCK)
	 INNER JOIN PFUNC AS SUPER		(NOLOCK) ON (PSUBSTSUP.CODCOLIGADA = SUPER.CODCOLIGADA AND PSUBSTSUP.CHAPASUBST = SUPER.CHAPA)
	 WHERE PSUBSTSUP.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSUBSTSUP.CODSECAO = PFUNC.CODSECAO AND PSUBSTSUP.DATAFIM IS NULL) END) AS 'SUPERVISOR',
/*CONVERT(VARCHAR(MAX), STRING_AGG(CHEFE.NOME, ' / ')) AS 'CHEFE', 
CONVERT(VARCHAR(MAX), STRING_AGG(SUPER.NOME, ' / ')) AS 'SUPERVISOR',*/
/*PSUBSTCHEFE.CHAPASUBST AS 'CHEFE',
PSUBSTSUP.CHAPASUBST AS 'SUPERVISOR',*/
PFUNC.CODCOLIGADA AS 'PFUNC COLIGADA',
PFUNC.CODFILIAL AS 'PFUNC FILIAL',
PFUNC.CHAPA AS 'PFUNC-CHAPA',
PFUNC.NOME AS 'NOME_FUNCIONARIO',
PPESSOA.CPF AS 'CPF',
PFUNC.CODFUNCAO AS 'CODIGO DA FUNÇÃO',
PFUNCAO.NOME AS 'DESCR. FUNCAO',
CONVERT(VARCHAR,PFUNC.DATAADMISSAO,103) AS 'DATA ADMISSAO',
PFUNC.PISPASEP AS 'PISPASEP',
PFUNC.SALARIO as 'SALARIO',
PFUNC.CODSITUACAO AS 'SITUACAO',
PFUNC.CODSECAO AS 'CODIGO DA SECAO',
PSECAO.DESCRICAO AS 'DESCR SEÇAO',  
PFUNC.JORNADAMENSAL / 60 AS 'HORAS_JORNADAMENSAL',
/*--AHSTUTILIZAPONTO.UTILIZA, -- Utiliza Ponto*/
PFUNC.PERCENTADIANT,
PFUNC.COTAPCD,
PFUNC.USASALCOMPOSTO,
PFUNC.MATRICULAESOCIAL,
PFUNC.NROFICHAREG,
PFUNC.CODSINDICATO AS 'CODSINDICATO',
PPESSOA.SEXO,	
CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS 'DT NASCIMENTO',

/*PPESSOA.ESTADOCIVIL,*/  /* SUBSTITUIDO PELO SELECT ABAIXO */
(SELECT TOP 1 DESCRICAO 
 FROM PCODESTCIVIL
 WHERE PCODESTCIVIL.CODINTERNO = PPESSOA.ESTADOCIVIL) AS 'ESTADOCIVIL',

PFUNCAO.CBO2002,
PPESSOA.CARTIDENTIDADE,
PPESSOA.ORGEMISSORIDENT,
PPESSOA.CARTEIRATRAB AS 'CART TRAB',
PPESSOA.SERIECARTTRAB AS 'SERIE CART TRAB',
PPESSOA.EMAIL,
CONVERT(VARCHAR,PFUNC.FIMPRAZOCONTR,103) as '2º VENC CONTRATO',
(CASE WHEN PFUNC.SITUACAOINSS = '1' THEN 'CALCULA' ELSE 'NÃO CALCULA' END) AS 'SIT INSS',
(CASE WHEN PFUNC.SITUACAOIRRF = '1' THEN 'CALCULA' ELSE 'NAO CALCULA' END) AS 'SIT IRRF',
PFUNC.CODBANCOPAGTO AS 'COD_BANCO1',
BANCO1.NOME AS 'NOME BANCO 1', 
PFUNC.CODAGENCIAPAGTO AS 'AGCONTA1',
PFUNC.CONTAPAGAMENTO AS 'CONTA_CORRENTE1',
PFUNC.CODBANCOPAGTO2 AS 'COD_BANCO2',
BANCO2.NOME AS 'NOME BANCO 2',
PFUNC.CODAGENCIAPAGTO2 AS 'AGCONTA2',
PFUNC.CONTAPAGAMENTO2 AS 'CONTA_CORRENTE2',
PFUNC.CODFORNECEDOR AS 'COD FORNECEDOR',
FCFO.NOME AS 'NOME FORNECEDOR',
PFUNC.NRODEPSALFAM AS 'NRO DE PSALFAM',
PFUNC.NRODEPIRRF AS 'NRO DE PIRRF',
PFDEPEND.NOME AS 'NOME MÃE', --NOME MÃE
PFDEPEND.GRAUPARENTESCO, /*--MÃE = CODIGO 7*/
PFUNC.CODRECEBIMENTO,
/*PFUNC.CODTIPO AS 'CODIGO DO TIPO',*/
(SELECT TOP 1 DESCRICAO 
 FROM PTPFUNC
 WHERE PTPFUNC.CODINTERNO = PFUNC.CODTIPO) AS 'TIPO',
PFUNC.CODCATEGORIAESOCIAL AS 'COD CATEGORIA ESOCIAL',
(CASE 
	WHEN PFUNC.TPREGIMEPREV = 1 THEN 'REGIME GERAL DA PREVIDÊNCIA SOCIAL - RGPS'
	WHEN PFUNC.TPREGIMEPREV = 2 THEN 'REGIME DOS PARLAMENTARES E SISTEMA DE PROTEÇÃO DOS MILITARES DOS ESTADOS/DF - RPPS'
	WHEN PFUNC.TPREGIMEPREV = 3 THEN 'REGIME DE PREVIDÊNCIA SOCIAL NO EXTERIOR'
	ELSE '' END) AS 'TPREGIMEPREV',
	(SELECT TOP 1 DESCRICAO
	 FROM PCODOCORTRAB 
	 WHERE PCODOCORTRAB.CODINTERNO = PFUNC.CODOCORRENCIA) AS 'COD OCORRENCIA',
/*PFUNC.CODOCORRENCIA AS 'COD OCORRENCIA',*/
(SELECT TOP 1 DESCRICAO
 FROM PCODCATTRAB
 WHERE PCODCATTRAB.CODINTERNO = PFUNC.CODCATEGORIA) AS 'COD CATEGORIA',
/*PFUNC.CODCATEGORIA AS 'COD CATEGORIA',*/
(CASE WHEN PFUNC.SITUACAOFGTS = '1' THEN 'OPTANTE' ELSE 'NAO OPTANTE' END) AS 'SITU-FGTS',
(SELECT TOP 1 DESCRICAO
 FROM PCODSITRAIS
 WHERE PCODSITRAIS.CODINTERNO = PFUNC.SITUACAORAIS) AS 'SIT_RAIS',
/*PFUNC.SITUACAORAIS AS 'SIT_RAIS',*/
PPESSOA.RUA AS 'RUA',
PPESSOA.NUMERO AS 'NUMERO',
PPESSOA.COMPLEMENTO AS 'COMPLEMENTO',
PPESSOA.CODTIPOBAIRRO AS 'COD TIP BAIRRO',
PPESSOA.BAIRRO AS 'P BAIRRO',
PPESSOA.CEP AS 'P CEP',
PPESSOA.ESTADO AS 'P ESTADO',
PPESSOA.CIDADE AS 'P CIDADE',
PCODINSTRUCAO.DESCRICAO AS 'GRAU_INSTRUCAO',
PCORRACA.DESCRICAO AS 'COR_RAÇA',
PPESSOA.TELEFONE1 AS 'TELEFONE',
PFUNC.CODHORARIO AS 'CODIGO DE HORARIO',
AHORARIO.DESCRICAO AS 'DESC HORARIO',
PFCOMPL.VA AS 'VALE_ALIMENTACAO',
PFCOMPL.VR AS 'VALE_REFEICAO',
(CASE 
	WHEN PFCOMPL.ASSISTENCIAODONTO = 'T' 
		THEN 'SIM'
	ELSE 'NÃO'
END) AS ASSISTENCIA_ODONTO,

(CASE 
	WHEN PFCOMPL.ASSISTMEDICA = 'T' 
		THEN 'SIM'
	ELSE 'NÃO'
END) AS ASSISTENCIA_MEDICA


FROM PFUNC						(NOLOCK)
 
LEFT JOIN PSECAO				(NOLOCK) ON (PSECAO.CODIGO = PFUNC.CODSECAO AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN PPESSOA				(NOLOCK) ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
LEFT JOIN AHORARIO				(NOLOCK) ON (AHORARIO.CODIGO = PFUNC.CODHORARIO AND AHORARIO.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN PFUNCAO				(NOLOCK) ON (PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO)
LEFT JOIN PFDEPEND				(NOLOCK) ON (PFDEPEND.CHAPA = PFUNC.CHAPA AND PFDEPEND.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFDEPEND.GRAUPARENTESCO = '7')
LEFT JOIN GBANCO AS BANCO1      (NOLOCK) ON (BANCO1.NUMBANCO = PFUNC.CODBANCOPAGTO) 
LEFT JOIN GBANCO AS BANCO2      (NOLOCK) ON (BANCO2.NUMBANCO = PFUNC.CODBANCOPAGTO2)
LEFT JOIN FCFO					(NOLOCK) ON (FCFO.CODCFO = PFUNC.CODFORNECEDOR AND FCFO.CODCOLIGADA = PFUNC.CODCOLFORNEC)
LEFT JOIN PCODINSTRUCAO			(NOLOCK) ON (PCODINSTRUCAO.CODCLIENTE = PPESSOA.GRAUINSTRUCAO)
LEFT JOIN PCORRACA				(NOLOCK) ON (PCORRACA.CODCLIENTE = PPESSOA.CORRACA)
LEFT JOIN PFCOMPL				(NOLOCK) ON (PFCOMPL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFCOMPL.CHAPA = PFUNC.CHAPA)


WHERE

PFUNC.CODSITUACAO <> 'D' 
AND PFUNC.CODTIPO NOT IN ('A','O')
AND PFUNC.CODCOLIGADA IN (@CODCOLIGADA)
AND PFUNC.CODSECAO IN ('0001.0066.99.01.0001')
/*AND PFUNC.NOME LIKE 'Waldivino%'
AND PSECAO.CODIGO = '01.500.42'*/


 GROUP BY 
    PFUNC.CODCOLIGADA,
	PFUNC.CHAPA,
	PSECAO.CGC,
    PFUNC.CODSINDICATO,
    PFUNC.PISPASEP,
    PFUNC.TPCONTABANCARIA,
    PFUNC.TPCONTABANCARIA2,
    PFUNC.FIMPRAZOCONTR,
    PFCOMPL.TIPOPLANOBRA,
    PFCOMPL.SUBSIDIADOUNIMED,
    PFCOMPL.ASSISTODON,
    PFCOMPL.OPERADORA_TICKET,
    PFCOMPL.TPREGRAVR,
    PFCOMPL.OPVT,
    PFCOMPL.CARTAOBHBUS,
    PFCOMPL.OTIMO,
    PFCOMPL.SPVALE,
    PFCOMPL.SPTRANS, 
    PFCOMPL.SP3,
    PFCOMPL.MATRICULARIOCARD,
    PFCOMPL.CARTAORJ_JAE,
    PFUNC.CODEQUIPE,
    PFUNC.CODGRPQUIOSQUE,
    PPESSOA.CODUSUARIO,
    PFUNC.CODCOLIGADA,
    PFUNC.CODFILIAL,
    PFUNC.CHAPA,
    PFUNC.NOME,
    PPESSOA.CPF,
    PFUNC.CODFUNCAO,
    PFUNCAO.NOME,
    PFUNC.DATAADMISSAO,
    PFUNC.SALARIO,
    PFUNC.CODSITUACAO,
    PFUNC.CODSECAO,
    PSECAO.DESCRICAO,  
    PFUNC.JORNADAMENSAL,
    PFUNC.PERCENTADIANT,
    PFUNC.COTAPCD,
    PFUNC.USASALCOMPOSTO,
    PFUNC.MATRICULAESOCIAL,
    PFUNC.NROFICHAREG,
    PPESSOA.SEXO,	
    PPESSOA.DTNASCIMENTO,
    PPESSOA.ESTADOCIVIL,
    PFUNCAO.CBO2002,
    PPESSOA.CARTIDENTIDADE,
    PPESSOA.ORGEMISSORIDENT,
    PPESSOA.CARTEIRATRAB,
    PPESSOA.SERIECARTTRAB,
    PPESSOA.EMAIL,
    PFUNC.FIMPRAZOCONTR,
    PFUNC.SITUACAOINSS,
    PFUNC.SITUACAOIRRF,
    PFUNC.CODBANCOPAGTO,
    BANCO1.NOME, 
    PFUNC.CODAGENCIAPAGTO,
    PFUNC.CONTAPAGAMENTO,
    PFUNC.CODBANCOPAGTO2,
    BANCO2.NOME,
    PFUNC.CODAGENCIAPAGTO2,
    PFUNC.CONTAPAGAMENTO2,
    PFUNC.CODFORNECEDOR,
    FCFO.NOME,
    PFUNC.NRODEPSALFAM,
    PFUNC.NRODEPIRRF,
    PFDEPEND.NOME,
    PFDEPEND.GRAUPARENTESCO,
    PFUNC.CODRECEBIMENTO,
    PFUNC.CODTIPO,
    PFUNC.CODCATEGORIAESOCIAL,
    PFUNC.TPREGIMEPREV,
    PFUNC.CODOCORRENCIA,
    PFUNC.CODCATEGORIA,
    PFUNC.SITUACAOFGTS,
    PFUNC.SITUACAORAIS,
    PPESSOA.RUA,
    PPESSOA.NUMERO,
    PPESSOA.COMPLEMENTO,
    PPESSOA.CODTIPOBAIRRO,
    PPESSOA.BAIRRO,
    PPESSOA.CEP,
    PPESSOA.ESTADO,
    PPESSOA.CIDADE,
    PCODINSTRUCAO.DESCRICAO,
    PCORRACA.DESCRICAO,
    PPESSOA.TELEFONE1,
    PFUNC.CODHORARIO,
    AHORARIO.DESCRICAO,
    PFCOMPL.VA,
    PFCOMPL.VR,
    PFCOMPL.ASSISTENCIAODONTO,
    PFCOMPL.ASSISTMEDICA,
	PFUNC.INTEGRCONTABIL

ORDER BY PFUNC.NOME, PFUNC.CODSECAO