SELECT PFUNC.CHAPA,
PFUNC.NOME,
NROAVOSVENCFERDEC AS 'NUMERO DE AVOS DE FÉRIAS VENCIDOS',
NROAVOSPROPORCDEC AS 'NUMERO DE AVOS DE FÉRIAS PROPORCIONAIS'

FROM PFUNC (NOLOCK)

JOIN PFHSTPROV (NOLOCK) ON (PFHSTPROV.CHAPA = PFUNC.CHAPA AND PFHSTPROV.CODCOLIGADA = PFUNC.CODCOLIGADA)
WHERE PFUNC.CHAPA = :CHAPA
AND PFUNC.CODCOLIGADA = :$CODCOLIGADA
AND PFHSTPROV.ANO IN :ANO
AND PFHSTPROV.MES IN :MES
AND PFHSTPROV.NROAVOSVENCFERDEC > 0
AND PFHSTPROV.NROAVOSPROPORCDEC > 0

GROUP BY
PFUNC.CHAPA,
PFUNC.NOME,
NROAVOSVENCFERDEC,
NROAVOSPROPORCDEC

ORDER BY PFUNC.NOME 