SELECT 
PFUNC.CHAPA,
PFUNC.NOME AS NOME_FUNC,
PFUNC.CODSECAO,
PSECAO.DESCRICAO AS NOME_SECAO,
GCOLIGADA.NOMEFANTASIA AS NOME_COLI,
GCOLIGADA.RUA,
GCOLIGADA.CIDADE,
GCOLIGADA.CGC,
PFUNC.SALARIO AS SALARIO_BASE,
PFHSTPROV.DTVENCFER,
PFHSTPROV.NROAVOSVENCFERDEC,
PFHSTPROV.NROAVOSPROPORCDEC,
PFHSTPROV.VALPROVFER AS BASE_INSS,
(CONVERT(MONEY, PFHSTPROV.VALPROVFERVENC) + CONVERT(MONEY, PFHSTPROV.VALPROVFERPROP)) AS VALOR_COM_MEDIA,
(PFHSTPROV.MEDIASFERPROP + PFHSTPROV.MEDIASFERVENC) AS MEDIAS,
(PFHSTPROV.VALPROVFER * 0.08) AS FGTS,
((((VALPROVFER -
(ISNULL(MEDIASFERPROP,0) +(ISNULL(MEDIASFERPROP,0)/3))) / 1.3333)/(CASE WHEN NROAVOSPROPORCDEC ='0' THEN 12 ELSE NROAVOSPROPORCDEC END))*12)AS SALARIO


,PFHSTPROV.VALPROVFER 
,round(convert(money,(SELECT ( ( CONVERT(NUMERIC(15, 4), VALOR) * 3 ) + 25.8 ) / 100
									FROM   PSECAOFAPALIQUOTA (NOLOCK)
									WHERE  Getdate() BETWEEN INICIOVIGENCIAALIQUOTA AND FINALVIGENCIAALIQUOTA
									       AND CODCOLIGADA = PFUNC.CODCOLIGADA--:$CODCOLIGADA
									       AND CODSECAO = Substring(PFUNC.CODSECAO, 1, 2))),2)
 	as teste1
	
,(PFHSTPROV.VALPROVFER * (SELECT ( ( CONVERT(NUMERIC(15, 4), VALOR) * 3 ) + 25.8 ) / 100
									FROM   PSECAOFAPALIQUOTA (NOLOCK)
									WHERE  Getdate() BETWEEN INICIOVIGENCIAALIQUOTA AND FINALVIGENCIAALIQUOTA
									       AND CODCOLIGADA = PFUNC.CODCOLIGADA--:$CODCOLIGADA
									       AND CODSECAO = Substring(PFUNC.CODSECAO, 1, 2))
 	)as conta									 

FROM PFUNC (NOLOCK)
LEFT JOIN PFHSTPROV (NOLOCK) ON (PFUNC.CODCOLIGADA = PFHSTPROV.CODCOLIGADA AND PFHSTPROV.CHAPA = PFUNC.CHAPA)
LEFT JOIN PSECAO	(NOLOCK) ON (PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO)
LEFT JOIN GCOLIGADA (NOLOCK) ON (GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA)

WHERE PFUNC.CODSECAO >= '01.000.00'--:SECAO_INI 
AND PFUNC.CODSECAO <= '99.999.99'--:SECAO_FIM
AND PFUNC.CODCOLIGADA = 1 --:$CODCOLIGADA
AND PFUNC.CODSITUACAO <> 'D'
AND PFUNC.CODSITUACAO <> 'T' 
AND PFUNC.CODTIPO  <> 'T'
AND PFHSTPROV.MES = 11--:MES
AND PFHSTPROV.ANO = 2023--:ANO

GROUP BY 
PFUNC.CHAPA,
PFUNC.NOME,
PFUNC.SALARIO,
PFUNC.SALARIO,
PFHSTPROV.DTVENCFER,
PFHSTPROV.NROAVOSVENCFERDEC,
PFHSTPROV.NROAVOSPROPORCDEC,
PFHSTPROV.VALPROVFERVENC,
PFHSTPROV.VALPROVFERPROP,
PFHSTPROV.MEDIASFERVENC,
PFHSTPROV.MEDIASFERPROP,
PFHSTPROV.VALPROVFER,
PSECAO.DESCRICAO,
PFUNC.CODSECAO,
GCOLIGADA.NOMEFANTASIA,
GCOLIGADA.RUA,
GCOLIGADA.CIDADE,
GCOLIGADA.CGC
,PFUNC.CODCOLIGADA

