/*DECLARE @CODCOLIGADA AS INT = 1,
		@DT_ABO_INI AS DATE = '20250116',
		@DT_ABO_FIM AS DATE = '20250213',
		@FERIAS_INI AS DATE = '20250401',
		@FERIAS_FIM AS DATE = '20250430';*/
		
SELECT (GRUPO.VALOR_LINHA * GRUPO.QTD_PASSES) AS 'VALOR_DIARIO',
* 
FROM(

SELECT 
PFUNC.CODCOLIGADA, 
PFUNC.CODFILIAL, 
PFUNC.CHAPA, 
PFUNC.NOME, 
PPESSOA.CPF, 
CONVERT(VARCHAR,PFUNC.DATAADMISSAO,103) AS 'DATAADMISSAO',
/*PFUNCAO.CODIGO,*/ 
PFUNCAO.NOME AS 'NOME_FUNCAO', 
/*(PFRATEIOFIXO.CODCCUSTO + ' - PORCENTAGEM:' + CONVERT(VARCHAR,PFRATEIOFIXO.VALOR) + '%') AS 'RATEIO FIXO',*/
PFRATEIOFIXO.CODCCUSTO AS 'CENTRO_DE_CUSTO_RATEIO',
(SELECT TOP 1 NOME
 FROM GCCUSTO 
 WHERE GCCUSTO.CODCOLIGADA = PFRATEIOFIXO.CODCOLIGADA AND GCCUSTO.CODCCUSTO = PFRATEIOFIXO.CODCCUSTO) AS 'DESC_CENTRO_DE_CUSTO_RATEIO_FIXO',
PFUNC.CODSECAO, 
PSECAO.DESCRICAO AS 'NOME_SEÇÃO', 
PFUNC.CODSITUACAO, 
/*CONVERT(VARCHAR,PPESSOA.DTNASCIMENTO,103) AS 'DTNASCIMENTO',*/
(PFUNC.CODHORARIO + ' - ' + AHORARIO.DESCRICAO) AS 'HORARIO',
PVALETR.GRUPOTRANSP AS 'COD_GRUPO_TRANSPORTE',
(SELECT TOP 1 DESCRICAO 
 FROM PGRPVALE
 WHERE PGRPVALE.CODCOLIGADA = PVALETR.CODCOLIGADA AND PGRPVALE.CODCLIENTE = PVALETR.GRUPOTRANSP) AS 'DESC_GRUPO_TRANSPORTE',
(CASE 
	WHEN PFCOMPL.CARTAOBHBUS IS NOT NULL THEN 'BHBUS'  
	WHEN PFCOMPL.CARTAOOTIMO IS NOT NULL THEN 'OTIMO'  
	WHEN PFCOMPL.SPVALE IS NOT NULL THEN 'SP1'  
	WHEN PFCOMPL.SPTRANS IS NOT NULL THEN 'SP2'  
	WHEN PFCOMPL.SP3 IS NOT NULL THEN 'SP3'  
	WHEN PFCOMPL.CARTAORJ_JAE IS NOT NULL THEN 'CARTÃO RJ JA'  
	WHEN PFCOMPL.BETIMCARD IS NOT NULL THEN 'CARTÃO BETIM CARD'  
	ELSE 'NAO UTILIZA'
	END) AS 'Operadora_VT',
/*(CASE WHEN PFCOMPL.CARTAOBHBUS IS NULL THEN PFCOMPL.CARTAOOTIMO ELSE PFCOMPL.CARTAOBHBUS END) AS 'NUM_CARTAOVT',*/
PFCOMPL.CARTAOBHBUS AS 'CARTÃO_BHBUS',
PFCOMPL.CARTAOOTIMO AS 'CARTÃO_OTIMO',
PFCOMPL.SPVALE AS 'CARTÃO_SP1',
PFCOMPL.SPTRANS AS 'CARTÃO_SP2',
PFCOMPL.SP3 AS 'CARTÃO_SP3', 
PFCOMPL.CARTAORJ_JAE AS 'CARTÃO_RJ_JAE',
PFCOMPL.BETIMCARD AS 'CARTÃO_BETIM_CARD',
CASE 
 WHEN PFCOMPL.OPVT = 1 THEN 'VALE TRANSPORTE'
 WHEN PFCOMPL.OPVT = 2 THEN 'VALE COMBUSTIVEL' 
ELSE 'NAO POSSUI' END as 'OP_VT',
PTARIFA.VALOR AS 'VALOR_LINHA', 
PFVALETR.NROVIAGENS AS 'QTD_PASSES',
[dbo].[DIAS_UTEIS_LABORE](@FERIAS_INI,@FERIAS_FIM,PSECAO.CODCALENDARIO) AS 'DIAS_UTEIS_MES', 
PVALETR.NOMELINHA AS 'LINHA',
ISNULL((SELECT SUM(GRUPO.DIAABONADO) AS 'DIASABONADOS'
FROM (
SELECT (CASE WHEN T.TEMPOABONADO >= T.TEMPODETRABALHOBASE THEN 1 ELSE 0 END) AS DIAABONADO
FROM (
SELECT 
/*FORMAT(DATEADD(MINUTE, SUM(ABONO), 0), 'HH:mm') AS 'TEMPOABONADO',
 FORMAT(DATEADD(MINUTE, MAX(BASE), 0), 'HH:mm') as 'TEMPODETRABALHOBASE'*/
 FORMAT(DATEADD(MINUTE, ABONO, 0), 'HH:mm') AS 'TEMPOABONADO',
 FORMAT(DATEADD(MINUTE, BASE, 0), 'HH:mm') as 'TEMPODETRABALHOBASE'
FROM AAFHTFUN
LEFT JOIN AABONOFUNCIONARIO ON (AABONOFUNCIONARIO.CODCOLIGADA = AAFHTFUN.CODCOLIGADA AND AABONOFUNCIONARIO.CHAPA = AAFHTFUN.CHAPA AND AABONOFUNCIONARIO.DATAREFERENCIA = AAFHTFUN.DATA)
WHERE AAFHTFUN.CHAPA IN (PFUNC.CHAPA)
AND AAFHTFUN.CODCOLIGADA IN (PFUNC.CODCOLIGADA)
AND AAFHTFUN.DATA BETWEEN @DT_ABO_INI AND @DT_ABO_FIM
AND AAFHTFUN.ABONO <> 0
AND CODABONO IN ('001', '002', '003', '004', '005', '006', '007', '008', '009', '010', '011', '012')

GROUP BY 
AAFHTFUN.DATA,
AAFHTFUN.ABONO,
AAFHTFUN.BASE

) AS T 
WHERE T.TEMPOABONADO <> '00:00'
) AS GRUPO
),0) AS 'DIASABONADOS',

(
SELECT TOP 1 FORMAT(DATEADD(MINUTE, SUM(ABONO), 0), 'HH:mm') AS HorasMinutos
FROM AAFHTFUN
WHERE AAFHTFUN.CHAPA IN (PFUNC.CHAPA)
AND AAFHTFUN.CODCOLIGADA IN (PFUNC.CODCOLIGADA)
AND AAFHTFUN.DATA BETWEEN @DT_ABO_INI AND @DT_ABO_FIM
) AS 'HORAS_DE_ABONO',

ISNULL((SELECT 
SUM(GRUPO.FALTA_DIA + (GRUPO.FALTA_HORA/7.33)) AS 'TOTAL_FALTAS'
FROM(
SELECT  
PFUNC.NOME,
PFUNC.CODCOLIGADA AS COLIG, 
PFFINANC.REF,
PFUFERIAS.INICIOPERAQUIS AS INI_PER_FER,
PFUFERIAS.FIMPERAQUIS AS FIM_PER_FER,
(CASE WHEN PEVENTO.CODIGO IN ('0594', '0338', '0417') THEN PFFINANC.REF ELSE 0 END) AS FALTA_DIA,
(CASE WHEN PEVENTO.CODIGO IN ('0104', '0614', '0143') THEN PFFINANC.REF ELSE 0 END) AS FALTA_HORA
FROM PFFINANC 
INNER JOIN PEVENTO	 (NOLOCK) ON (PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUNC as PFUNC1	 (NOLOCK) ON (PFUNC.CHAPA = PFFINANC.CHAPA AND PFUNC.CODCOLIGADA = PFFINANC.CODCOLIGADA)
INNER JOIN PFUFERIAS (NOLOCK) ON (PFUNC.CHAPA = PFUFERIAS.CHAPA AND PFUNC.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PERIODOABERTO = 1)
WHERE 
    PFFINANC.ANOCOMP BETWEEN YEAR(PFUFERIAS.INICIOPERAQUIS) AND YEAR(PFUFERIAS.FIMPERAQUIS)
	AND PFUNC1.CHAPA IN (PFUNC.CHAPA)
    AND PFFINANC.CODCOLIGADA IN (PFUNC.CODCOLIGADA)
	AND PFFINANC.ANOCOMP BETWEEN YEAR(@DT_ABO_INI) AND YEAR(@DT_ABO_FIM)
	AND PFFINANC.MESCOMP BETWEEN MONTH(@DT_ABO_INI) AND MONTH(@DT_ABO_FIM)
    AND PFFINANC.NROPERIODO = 3
	AND PEVENTO.PROVDESCBASE <> 'B'
	) AS GRUPO
	GROUP BY 
	GRUPO.COLIG,
	GRUPO.NOME
),0)  as 'TOTAL_DE_FALTAS',
	(SELECT COUNT(*)
	 FROM AOCORRENCIACALCULADA
	 WHERE AOCORRENCIACALCULADA.TIPOOCORRENCIA = 'AFT' 
	 and DATAREFERENCIA BETWEEN @DT_ABO_INI AND @DT_ABO_FIM
	 AND AOCORRENCIACALCULADA.CODCOLIGADA IN (PFUNC.CODCOLIGADA) 
	 AND AOCORRENCIACALCULADA.CHAPA = PFUNC.CHAPA) AS 'ATESTADOS',
	 PFUFERIASPER.DATAINICIO,
	 PFUFERIASPER.DATAFIM,
	 PSECAO.CODCALENDARIO,
[dbo].[DIAS_UTEIS_LABORE]((CASE WHEN @FERIAS_INI < PFUFERIASPER.DATAINICIO THEN PFUFERIASPER.DATAINICIO ELSE @FERIAS_INI END),(CASE WHEN PFUFERIASPER.DATAFIM > @FERIAS_FIM THEN @FERIAS_FIM ELSE PFUFERIASPER.DATAFIM END),PSECAO.CODCALENDARIO) as 'DIAS_UTEIS_FERIAS',
'' AS 'TOTAL',
'' AS 'SALDO_SITE_EM',
'' AS 'PROJEÇÃO',
'' AS 'SaldoP_Aproveitar',
'' AS 'COMPRA_SITE',
'' AS 'N_RDA',
'' AS 'N_NF',
'' AS 'OBS'


FROM PFUNC				
LEFT JOIN PFCOMPL			(NOLOCK) ON (PFCOMPL.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFCOMPL.CHAPA = PFUNC.CHAPA)
LEFT JOIN PPESSOA			(NOLOCK) ON (PPESSOA.CODIGO = PFUNC.CODPESSOA)
LEFT JOIN PFUNCAO			(NOLOCK) ON (PFUNCAO.CODIGO = PFUNC.CODFUNCAO AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN PSECAO			(NOLOCK) ON (PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO)
LEFT JOIN PFVALETR			(NOLOCK) ON (PFVALETR.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFVALETR.CHAPA = PFUNC.CHAPA AND PFVALETR.DTFIM IS NULL)
LEFT JOIN PVALETR			(NOLOCK) ON (PVALETR.CODCOLIGADA = PFVALETR.CODCOLIGADA AND PVALETR.CODIGO = PFVALETR.CODLINHA)
LEFT JOIN PTARIFA			(NOLOCK) ON (PTARIFA.CODCOLIGADA = PVALETR.CODCOLIGADA AND PTARIFA.CODIGO = PVALETR.CODTARIFA)
LEFT JOIN AHORARIO			(NOLOCK) ON (AHORARIO.CODCOLIGADA = PFUNC.CODCOLIGADA AND AHORARIO.CODIGO = PFUNC.CODHORARIO)
/* TABELAS DE FERIAS */ 
LEFT JOIN PFUFERIAS		(NOLOCK) ON (PFUFERIAS.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFUFERIAS.CHAPA = PFUNC.CHAPA AND PFUFERIAS.PERIODOABERTO = 1)
LEFT JOIN PFUFERIASPER		(NOLOCK) ON (PFUFERIASPER.CODCOLIGADA = PFUFERIAS.CODCOLIGADA AND PFUFERIASPER.CHAPA = PFUFERIAS.CHAPA AND PFUFERIASPER.FIMPERAQUIS = PFUFERIAS.FIMPERAQUIS /*AND PFUFERIASPER.DATAFIM BETWEEN @FERIAS_INI AND @FERIAS_FIM*/)

LEFT JOIN PFRATEIOFIXO		(NOLOCK) ON (PFRATEIOFIXO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PFRATEIOFIXO.CHAPA = PFUNC.CHAPA)

WHERE 
PFUNC.CODCOLIGADA IN (@CODCOLIGADA) 
/*AND PFUFERIASPER.DATAFIM BETWEEN @FERIAS_INI AND @FERIAS_FIM*/
AND PFCOMPL.OPVT in (1,2)
AND PFUNC.CODSITUACAO <> 'D'
/*AND PFUNC.CHAPA = '00024525'
and pfunc.CHAPA = '00025290'*/


GROUP BY 
PFUNC.CODCOLIGADA, 
PFUNC.CODFILIAL, 
PFUNC.CHAPA, 
PFUNC.NOME, 
PPESSOA.CPF, 
PFUNC.DATAADMISSAO,
PFUNCAO.CODIGO, 
PFUNCAO.NOME, 
PFRATEIOFIXO.CODCCUSTO,
PFRATEIOFIXO.CODCOLIGADA,
PFRATEIOFIXO.VALOR,
PFUNC.CODSECAO, 
PSECAO.DESCRICAO, 
PSECAO.CODCALENDARIO,
PFUNC.CODSITUACAO, 
PPESSOA.DTNASCIMENTO,
PFUNC.CODHORARIO,
AHORARIO.DESCRICAO,
PFCOMPL.CARTAOBHBUS,
PFCOMPL.CARTAOBHBUS,
PFCOMPL.CARTAOOTIMO,
PFCOMPL.CARTAOBHBUS,
PFCOMPL.SPVALE,
PFCOMPL.SPTRANS,
PFCOMPL.SP3,
PFCOMPL.CARTAORJ_JAE,
PFCOMPL.BETIMCARD,
PFCOMPL.OPVT,
PVALETR.GRUPOTRANSP,
PVALETR.CODCOLIGADA,
PTARIFA.VALOR, 
PFUFERIASPER.DATAINICIO,
PFUFERIASPER.DATAFIM,
PFVALETR.NROVIAGENS,
PFUNC.DIASUTPROXMES, 
PFVALETR.CODLINHA,
PVALETR.NOMELINHA

) AS GRUPO


GROUP BY
GRUPO.CODCOLIGADA,
GRUPO.CODFILIAL,
GRUPO.VALOR_LINHA,
GRUPO.QTD_PASSES,
GRUPO.CHAPA,
GRUPO.NOME,
GRUPO.CPF,
GRUPO.DATAADMISSAO,
GRUPO.NOME_FUNCAO,
GRUPO.CENTRO_DE_CUSTO_RATEIO,
GRUPO.DESC_CENTRO_DE_CUSTO_RATEIO_FIXO,
GRUPO.CODSECAO,
GRUPO.NOME_SEÇÃO,
GRUPO.CODSITUACAO,
GRUPO.HORARIO,
GRUPO.COD_GRUPO_TRANSPORTE,
GRUPO.DESC_GRUPO_TRANSPORTE,
GRUPO.CARTÃO_BHBUS,
GRUPO.CARTÃO_OTIMO,
GRUPO.CARTÃO_SP1,
GRUPO.CARTÃO_SP2,
GRUPO.CARTÃO_SP3,
GRUPO.CARTÃO_RJ_JAE,
GRUPO.CARTÃO_BETIM_CARD,
GRUPO.DIAS_UTEIS_MES,
GRUPO.OPERADORA_VT,
GRUPO.OP_VT,
GRUPO.LINHA,
GRUPO.DIASABONADOS,
GRUPO.HORAS_DE_ABONO,
GRUPO.TOTAL_DE_FALTAS,
GRUPO.ATESTADOS,
GRUPO.DIAS_UTEIS_FERIAS,
GRUPO.TOTAL,
GRUPO.SALDO_SITE_EM,
GRUPO.PROJEÇÃO,
GRUPO.SaldoP_Aproveitar,
GRUPO.COMPRA_SITE,
GRUPO.N_RDA,
GRUPO.N_NF,
GRUPO.OBS,
GRUPO.DATAINICIO,
GRUPO.DATAFIM,
GRUPO.CODCALENDARIO

/*WHERE GRUPO.TOTAL_DE_FALTAS > 0*/

ORDER BY GRUPO.CODCOLIGADA,GRUPO.NOME
