SELECT 
(CASE WHEN GRUPO.ID_PROJETO IS NULL THEN GRUPO.PROJETOS_TCOP ELSE GRUPO.ID_PROJETO END) AS 'IDPRJ',
* 
FROM (
SELECT 
    GFILIAL.CODCOLIGADA,
    -1 AS IDMOV,
    GFILIAL.CODFILIAL,
    ZMDCCUSTOXLOCAL.CODLOCAL AS CODLOC,
    'F51196' AS CODCFO,
    0 AS CODCOLCFO,
    'C' AS SERIE,
    '1.1.07' AS CODTMV,
    'A' AS STATUS,
    '054' AS CODCPG,
    '0005' AS CODTB1FLX,
    '1' AS FRETECIFOUFOB,
    '3.0001.06' AS CODCCUSTO,
    'T' AS INTEGRAAPLICACAO,
	(SELECT TOP 1 IDPRJ
	FROM MPRJ (NOLOCK)AS PROJETO
	WHERE PROJETO.CODCOLIGADA = GFILIAL.CODCOLIGADA AND PROJETO.CODFILIAL = GFILIAL.CODFILIAL AND REPLACE(REPLACE(REPLACE(PROJETO.CGC, '.', ''), '/', ''), '-', '') = '54109242000228'
	ORDER BY PROJETO.REVISAO DESC) AS 'PROJETOS_TCOP',
    isnull((SELECT TOP 1  MPRJ.IDPRJ FROM MPRJ (NOLOCK)
			INNER JOIN MTRFCCUSTO (NOLOCK) ON MTRFCCUSTO.IDPRJ = MPRJ.IDPRJ AND MPRJ.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MPRJ.REVISAO = ( SELECT MAX(PRJ.REVISAO) FROM MPRJ AS PRJ WHERE PRJ.CODPRJ= MPRJ.CODPRJ AND PRJ.CODCOLIGADA = MPRJ.CODCOLIGADA)
	WHERE  MTRFCCUSTO.CODCOLIGADA = GFILIAL.CODCOLIGADA AND ZMDCCUSTOXLOCAL.CODLOCAL = MTRFCCUSTO.CODCCUSTO AND  EXISTS(SELECT 1 FROM MTRFCCUSTO AS RATEIO WHERE RATEIO.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MTRFCCUSTO.IDPRJ = RATEIO.IDPRJ AND RATEIO.CODCCUSTO ='3.0001.06')
	and MPRJ.CODPRJ LIKE '__.____.___'),(SELECT PRJ.IDPRJ FROM MPRJ AS PRJ WHERE PRJ.CODFILIAL = GFILIAL.CODFILIAL AND PRJ.CODCOLIGADA = GFILIAL.CODCOLIGADA AND PRJ.CODCCUSTO = '3.0001.06'  AND PRJ.CODPRJ LIKE '__.____.___' AND PRJ.REVISAO = (
						  SELECT MAX(PROJ.REVISAO) FROM MPRJ AS PROJ WHERE PROJ.CODPRJ= PRJ.CODPRJ AND PROJ.CODCOLIGADA = PRJ.CODCOLIGADA))) AS 'ID_PROJETO',
    /*
    isnull((SELECT TOP 1  MPRJ.IDPRJ FROM MPRJ (NOLOCK)
			INNER JOIN MTRFCCUSTO (NOLOCK) ON MTRFCCUSTO.IDPRJ = MPRJ.IDPRJ AND MPRJ.CODCOLIGADA = MTRFCCUSTO.CODCOLIGADA AND MPRJ.REVISAO = (
						  SELECT MAX(PRJ.REVISAO) FROM MPRJ AS PRJ WHERE PRJ.CODPRJ= MPRJ.CODPRJ AND PRJ.CODCOLIGADA = MPRJ.CODCOLIGADA)
	WHERE MTRFCCUSTO.CODCCUSTO = :CODCCUSTO AND MTRFCCUSTO.CODCOLIGADA = GFILIAL.CODCOLIGADA
	and MPRJ.CODPRJ LIKE '__.____.___'),(SELECT PRJ.IDPRJ FROM MPRJ AS PRJ WHERE PRJ.CODFILIAL = GFILIAL.CODFILIAL AND PRJ.CODCOLIGADA = GFILIAL.CODCOLIGADA AND PRJ.CODCCUSTO = :CODCCUSTO AND PRJ.CODPRJ LIKE '__.____.___' AND PRJ.REVISAO = (
						  SELECT MAX(PROJ.REVISAO) FROM MPRJ AS PROJ WHERE PROJ.CODPRJ= PRJ.CODPRJ AND PROJ.CODCOLIGADA = PRJ.CODCOLIGADA))) AS IDPRJ,
*/
    '' AS HISTORICOLONGO,
	'' AS PEDIDOBRS 

FROM GFILIAL (NOLOCK)
INNER JOIN ZMDCCUSTOXLOCAL (NOLOCK) ON ZMDCCUSTOXLOCAL.CODFILIAL = GFILIAL.CODFILIAL AND ZMDCCUSTOXLOCAL.CODCOLIGADA = GFILIAL.CODCOLIGADA AND ZMDCCUSTOXLOCAL.CODCCUSTO = '3.0001.06'
WHERE REPLACE(REPLACE(REPLACE(GFILIAL.CGC,'.',''),'/',''),'-','') = '54109242000228'
AND GFILIAL.ATIVO = 1

) AS GRUPO
