ROLLBACK
--commit
BEGIN TRAN 
UPDATE T
SET 
    T.NOMEFANTASIA = Z.DESCRICAO,
    T.DESCRICAO = z.DESCRICAOAUX,
	t.DESCRICAOAUX = null
FROM TPRODUTO T
INNER JOIN ZMD_Astrem_Emccamp_L2 Z ON T.CODIGOPRD = Z.Cod
INNER  JOIN DCLASSIFBENSSERVICO D ON D.numero like ('%' + Z.IDCLASSIFBENSSERVICO)



select Z.cod, Z.IDCLASSIFBENSSERVICO AS 'NUMERO_NCM', D.IDCLASSIFBENSSERVICO , T.IDCLASSIFBENSSERVICO AS 'CLASS_SISTEMA', Z.DESCRICAOAUX--, d.IDCLASSIFBENSSERVICO AS 'ID_NOVO' 
from TPRODUTO t
INNER JOIN ZMD_Astrem_Emccamp_L2 Z ON T.CODIGOPRD = Z.Cod
left JOIN DCLASSIFBENSSERVICO D ON D.numero = Z.IDCLASSIFBENSSERVICO
WHERE 
D.IDCLASSIFBENSSERVICO IS NULL

select * 
from DCLASSIFBENSSERVICO
where numero ='73071990'

select *
from ZMD_Astrem_Emccamp_L2
where cod = '001.02220'



ALTER TABLE ZMD_Astrem_Emccamp
ALTER COLUMN IDCLASSIFBENSSERVICO varchar(50);
drop table ZMD_Astrem_Emccamp

SELECT * 
FROM PPESSOA 
WHERE NOME LIKE '%TALIANA%'

