 DECLARE 
		@DATA_INI_CRIACAO_MOV DATE = '20250801',
		@DATA_FIM_CRIACAO_MOV DATE = '20250831';
		

WITH MOV_ODC AS (
SELECT 
'Relatorio_Analitico_Orcamento_GA' AS NOME_RELATORIO,
       ROW_NUMBER() OVER(PARTITION BY TMOV.IDMOV ORDER BY MOV_ODC.DATACRIACAO) AS RN,
        MOV_ODC.IDMOV AS IDMOV_ODC,
        TMV_ODC.CODTMV,
        TMV_ODC.NOME,
        MOV_ODC.DATACRIACAO,
        MOV_ODC.DATAEMISSAO,
        TMOV.CODCOLIGADA,
        MOV_ODC.USUARIOCRIACAO,
		TMOV.IDMOV
		

FROM TMOV (NOLOCK)

INNER JOIN TMOVRELAC				(NOLOCK) ON (TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
INNER JOIN TMOV MOV_ORIGEM_CONT		(NOLOCK) ON (MOV_ORIGEM_CONT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOV_ORIGEM_CONT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM AND MOV_ORIGEM_CONT.CODTMV NOT IN ('1.1.34','1.1.20','1.1.18','1.1.21','1.1.51','1.2.29','1.2.30'))
INNER JOIN TITMTMV TITM_ORIGEM_CONT (NOLOCK) ON (TITM_ORIGEM_CONT.CODTMV = MOV_ORIGEM_CONT.CODTMV AND TITM_ORIGEM_CONT.CODCOLIGADA = MOV_ORIGEM_CONT.CODCOLIGADA AND TITM_ORIGEM_CONT.HABILITAORCAMENTO = 1)
INNER JOIN TTMV TMV_ORIGEM_CONT		(NOLOCK) ON (TMV_ORIGEM_CONT.CODTMV = TITM_ORIGEM_CONT.CODTMV AND TMV_ORIGEM_CONT.CODCOLIGADA = TITM_ORIGEM_CONT.CODCOLIGADA)

---- Ordem de compra gerada no 1.1.35
INNER JOIN TMOVRELAC ODC	(NOLOCK) ON (MOV_ORIGEM_CONT.IDMOV = ODC.IDMOVDESTINO AND MOV_ORIGEM_CONT.CODCOLIGADA = ODC.CODCOLDESTINO)
INNER JOIN TMOV MOV_ODC		(NOLOCK) ON (ODC.IDMOVORIGEM = MOV_ODC.IDMOV AND ODC.CODCOLORIGEM = MOV_ODC.CODCOLIGADA AND MOV_ODC.CODTMV in('1.1.35'))
INNER JOIN TTMV TMV_ODC		(NOLOCK) ON (TMV_ODC.CODTMV = MOV_ODC.CODTMV AND TMV_ODC.CODCOLIGADA = MOV_ODC.CODCOLIGADA)

WHERE

TMOV.STATUS <> 'C'
AND TMOV.CODCOLIGADA IN (1)

),
MOV_ODC_FIRST AS (
    SELECT *
    FROM MOV_ODC
    WHERE RN = 1 -- Seleciona a primeira linha para cada grupo
)

SELECT * 
FROM (
SELECT

TMOVORCAMENTO.CODCOLIGADA,
TMOV.CODTMV,
TMOV.IDMOV,
GCOLIGADA.NOMEFANTASIA AS 'NOME COLIGADA',
GCCUSTO.CODCCUSTO AS 'CENTRO DE CUSTO',
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO',
TMOV.CODCFO AS 'CODIGO FORNECEDOR',
FCFO.NOMEFANTASIA AS 'NOME FORNECEDOR',
(CASE WHEN TMOV.CODTMV IN ('1.2.21','1.2.41','1.2.29','1.2.30') THEN TMOV.DATAEMISSAO
ELSE
(ISNULL(MOV_ODC_FIRST.DATACRIACAO,(ISNULL(MOV_ORIGEM_CONT.DATACRIACAO,TMOV.DATACRIACAO)))) END) AS 'DATACRIACAO',
(ISNULL(MOV_ODC_FIRST.DATAEMISSAO,(ISNULL(MOV_ORIGEM_CONT.DATAEMISSAO,TMOV.DATAEMISSAO)))) AS 'DATA_EMISSÃO',

(SELECT TOP 1 HISTORICOLONGO FROM TMOVHISTORICO WHERE TMOVHISTORICO.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVHISTORICO.IDMOV = TMOV.IDMOV) AS HISTORICO_LONGO,
TTBORCAMENTO.CODTBORCAMENTO AS 'COD NATUREZA ORÇAMENTO',
TTBORCAMENTO.DESCRICAO AS 'NATUREZA ORÇAMENTO'
,TMOV.VALORBRUTO
,TMOVCONT.CODCONTA
,CCONTA.DESCRICAO

FROM TMOVORCAMENTO					(NOLOCK)
LEFT JOIN TORCAMENTO				(NOLOCK) ON (TMOVORCAMENTO.IDPERIODO = TORCAMENTO.IDPERIODO AND TMOVORCAMENTO.IDORCAMENTO = TORCAMENTO.IDORCAMENTO AND TMOVORCAMENTO.CODCOLIGADA = TORCAMENTO.CODCOLIGADA)
LEFT JOIN GCOLIGADA					(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN TMOV						(NOLOCK) ON (TMOVORCAMENTO.IDMOV = TMOV.IDMOV AND TMOV.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN GFILIAL					(NOLOCK) ON (GFILIAL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA AND TMOV.CODFILIAL = GFILIAL.CODFILIAL)
LEFT JOIN TPERIODOORCAMENTO			(NOLOCK) ON (TPERIODOORCAMENTO.IDPERIODO = TMOVORCAMENTO.IDPERIODO AND TPERIODOORCAMENTO.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN TITMPERIODOORCAMENTO		(NOLOCK) ON (TMOVORCAMENTO.CODCOLIGADA = TITMPERIODOORCAMENTO.CODCOLIGADA AND TMOVORCAMENTO.IDPERIODO = TITMPERIODOORCAMENTO.IDPERIODO AND TITMPERIODOORCAMENTO.IDITMPERIODO = TMOVORCAMENTO.IDITMPERIODO)
LEFT JOIN TTBORCAMENTO				(NOLOCK) ON (TORCAMENTO.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO AND TORCAMENTO.CODCOLTBORCAMENTO = TTBORCAMENTO.CODCOLIGADA)
LEFT JOIN GCCUSTO					(NOLOCK) ON (TORCAMENTO.CODCCUSTO = GCCUSTO.CODCCUSTO AND TORCAMENTO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN TTMV						(NOLOCK) ON (TMOV.CODTMV = TTMV.CODTMV AND TMOV.CODCOLIGADA = TTMV.CODCOLIGADA)
LEFT JOIN TITMTMV					(NOLOCK) ON (TITMTMV.CODCOLIGADA = TTMV.CODCOLIGADA AND TITMTMV.CODTMV = TTMV.CODTMV)
LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCFO = TMOV.CODCFO AND FCFO.CODCOLIGADA = TMOV.CODCOLCFO)
-- Movimento anterior a TMOV
LEFT JOIN TMOVRELAC					(NOLOCK) ON (TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
LEFT JOIN TMOV MOV_ORIGEM_CONT		(NOLOCK) ON (MOV_ORIGEM_CONT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOV_ORIGEM_CONT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM AND MOV_ORIGEM_CONT.CODTMV NOT IN ('1.1.34','1.1.20','1.1.18','1.1.21','1.1.51','1.2.29','1.2.30'))
LEFT JOIN TITMTMV TITM_ORIGEM_CONT	(NOLOCK) ON (TITM_ORIGEM_CONT.CODTMV = MOV_ORIGEM_CONT.CODTMV AND TITM_ORIGEM_CONT.CODCOLIGADA = MOV_ORIGEM_CONT.CODCOLIGADA AND TITM_ORIGEM_CONT.HABILITAORCAMENTO = 1)
LEFT JOIN TTMV TMV_ORIGEM_CONT		(NOLOCK) ON (TMV_ORIGEM_CONT.CODTMV = TITM_ORIGEM_CONT.CODTMV AND TMV_ORIGEM_CONT.CODCOLIGADA = TITM_ORIGEM_CONT.CODCOLIGADA)

LEFT JOIN MOV_ODC_FIRST						 ON MOV_ODC_FIRST.IDMOV = TMOV.IDMOV AND TMOV.CODCOLIGADA = MOV_ODC_FIRST.CODCOLIGADA
LEFT JOIN TMOVCONT					(NOLOCK) ON TMOVCONT.IDMOV = TMOV.IDMOV AND TMOVCONT.CODCOLIGADA = TMOV.CODCOLIGADA
LEFT JOIN CCONTA					(NOLOCK) ON CCONTA.CODCONTA = TMOVCONT.CODCONTA 

WHERE

TMOV.STATUS <> 'C'
/*AND DBO.DTORCAMENTO(TMOV.IDMOV,TMOVORCAMENTO.CODCOLIGADA,GCCUSTO.CODCCUSTO) BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV */
AND TMOVORCAMENTO.CODCOLIGADA IN (1)
/*AND TMOV.DATACRIACAO BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV
AND MOV_ODC_FIRST.DATACRIACAO BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV
AND MOV_ORIGEM_CONT.DATACRIACAO BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV*/

GROUP BY 
 TMOVORCAMENTO.CODCOLIGADA
,GCOLIGADA.NOMEFANTASIA
,GFILIAL.CODFILIAL
,GFILIAL.NOMEFANTASIA
,TMOVORCAMENTO.USUARIOCRIACAO
,MOV_ODC_FIRST.USUARIOCRIACAO
,MOV_ORIGEM_CONT.USUARIOCRIACAO
,TMOV.USUARIOCRIACAO
,TMOV.DATAEXTRA2
,TPERIODOORCAMENTO.DESCRICAO
,TITMPERIODOORCAMENTO.DATAINICIO,TITMPERIODOORCAMENTO.DATAINICIO
,GCCUSTO.CODCCUSTO
,GCCUSTO.NOME 
,MOV_ODC_FIRST.CODTMV
,TMV_ORIGEM_CONT.CODTMV
,TTMV.CODTMV
,MOV_ODC_FIRST.NOME
,TMV_ORIGEM_CONT.NOME
,TTMV.NOME
,MOV_ODC_FIRST.IDMOV
,MOV_ORIGEM_CONT.IDMOV
,TMOV.IDMOV
,TMOV.CODCOLIGADA
,TMOV.CODCFO
,FCFO.NOMEFANTASIA
,TMOV.CODTMV
,TMOV.DATAEMISSAO
,TMOV.DATACRIACAO
,MOV_ODC_FIRST.DATACRIACAO
,MOV_ORIGEM_CONT.DATACRIACAO
,MOV_ODC_FIRST.DATAEMISSAO
,MOV_ORIGEM_CONT.DATAEMISSAO
,TMOV.DATAEMISSAo
,TTBORCAMENTO.CODTBORCAMENTO
,TTBORCAMENTO.DESCRICAO
,TMOVORCAMENTO.VALOROPCIONAL1
,TMOVORCAMENTO.VALOROPCIONAL2
,TMOVORCAMENTO.VALORREAL
,TMOVCONT.CODCONTA
,CCONTA.DESCRICAO
,TMOV.VALORBRUTO) AS GRUPO

WHERE GRUPO.DATACRIACAO BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV

ORDER BY GRUPO.DATACRIACAO 

