SELECT 
(CASE WHEN GRUPO.USUARIO_CRIACAO <> GRUPO.USUARIO_MODIFICACAO THEN (GRUPO.EMAIL_CRIACAO + '; ' + GRUPO.EMAIL_MOD) ELSE GRUPO.EMAIL_CRIACAO END) as 'EMAIL'
,* 
FROM (



SELECT TOP 1
GUSUARIO.EMAIL AS 'EMAIL_CRIACAO',
USERMOD.EMAIL AS 'EMAIL_MOD',
TMOV2.RECCREATEDBY AS 'USUARIO_CRIACAO',
TMOV.RECMODIFIEDBY AS 'USUARIO_MODIFICACAO'
,TCCOTACAO.CODCOLIGADA
,TCCOTACAO.CODFILIAL
,TCCOTACAO.CODCOTACAO
,TMOV.IDMOV
,TMOV.NUMEROMOV
,TMOTIVO.DSCMOTIVO

FROM TMOV 						(NOLOCK)
LEFT JOIN TITMMOV AS ITM_SOLI	(NOLOCK) ON (ITM_SOLI.IDMOV = TMOV.IDMOV AND ITM_SOLI.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN TCCOTACAOITMMOV		(NOLOCK) ON (TCCOTACAOITMMOV.IDMOV = ITM_SOLI.IDMOV AND TCCOTACAOITMMOV.NSEQITMMOV = ITM_SOLI.NSEQITMMOV AND TCCOTACAOITMMOV.CODCOLIGADA = ITM_SOLI.CODCOLIGADA)

INNER JOIN TMOVRELAC		(NOLOCK) ON TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO
INNER JOIN TMOV AS TMOV2	(NOLOCK) ON TMOV2.IDMOV = TMOVRELAC.IDMOVORIGEM AND TMOV2.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM

INNER JOIN GUSUARIO				(NOLOCK) ON GUSUARIO.CODUSUARIO = TMOV2.RECCREATEDBY
INNER JOIN GUSUARIO USERMOD		(NOLOCK) ON USERMOD.CODUSUARIO = TMOV.RECMODIFIEDBY
INNER JOIN TCCOTACAO			(NOLOCK) ON TCCOTACAO.CODCOTACAO = TCCOTACAOITMMOV.CODCOTACAO AND TCCOTACAO.CODCOLIGADA = TCCOTACAOITMMOV.CODCOLIGADA
LEFT JOIN TMOTIVOCONCLPED		(NOLOCK) ON TMOTIVOCONCLPED.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOTIVOCONCLPED.IDMOV = TMOV.IDMOV
LEFT JOIN TMOTIVO 				(NOLOCK) ON TMOTIVO.CODMOTIVO = TMOTIVOCONCLPED.MOTIVO


WHERE TCCOTACAO.CODCOTACAO = :CODCOTACAO
AND TCCOTACAO.CODCOLIGADA = :CODCOLIGADA
AND TMOV.CODTMV  IN ('1.1.18', '1.1.20','1.1.25')
) AS GRUPO


