SELECT 
(CASE WHEN GRUPO.USUARIO_CRIACAO <> GRUPO.USUARIO_MODIFICACAO THEN (GRUPO.EMAIL_CRIACAO + '; ' + GRUPO.EMAIL_MOD) ELSE GRUPO.EMAIL_CRIACAO END) as 'EMAIL'
,* 
FROM (

SELECT 
GUSUARIO.EMAIL AS 'EMAIL_CRIACAO',
USERMOD.EMAIL AS 'EMAIL_MOD',
TMOV.RECCREATEDBY AS 'USUARIO_CRIACAO',
TMOV.RECMODIFIEDBY AS 'USUARIO_MODIFICACAO'
,TMOV.CODCOLIGADA
,TMOV.CODFILIAL
,TMOV.NUMEROMOV
,TMOV.IDMOV
,TMOTIVOCONCLPED.MOTIVO
,TMOTIVOCONCLPED.NSEQUENCIAL

FROM TMOV					(NOLOCK)
LEFT JOIN TMOVRELAC			(NOLOCK) ON TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO
LEFT JOIN TMOV AS TMOV2		(NOLOCK) ON TMOV2.IDMOV = TMOVRELAC.IDMOVORIGEM AND TMOV2.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM
LEFT JOIN GUSUARIO			(NOLOCK) ON GUSUARIO.CODUSUARIO = TMOV.RECCREATEDBY
LEFT JOIN GUSUARIO USERMOD (NOLOCK) ON USERMOD.CODUSUARIO = TMOV.RECMODIFIEDBY
LEFT JOIN TITMMOV			(NOLOCK) ON TMOV.IDMOV = TITMMOV.IDMOV AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA 
LEFT JOIN TMOTIVOCONCLPED	(NOLOCK) ON TMOTIVOCONCLPED.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOTIVOCONCLPED.IDMOV = TMOV.IDMOV AND TITMMOV.NSEQITMMOV = TMOTIVOCONCLPED.NSEQUENCIAL


WHERE TMOV.IDMOV = 5918
AND TMOV.CODCOLIGADA = :CODCOLIGADA
AND TMOV.CODTMV IN ('1.1.18','1.1.20')
--AND DATEDIFF(SECOND,TMOTIVOCONCLPED.RECCREATEDON,GETDATE()) <= 5
) AS GRUPO

