SELECT 1 AS VALIDA FROM TMOV (NOLOCK) WHERE IDMOV IN 
					(SELECT IDMOV_ORIGEM FROM TMOV 
					INNER JOIN TMOVCOMPL (NOLOCK) ON TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA  
					WHERE TMOV.CODTMV = '3.1.28' AND TMOV.CODCOLIGADA =1)--:CODCOLIGADA) 

AND TMOV.CODCOLIGADA =1--:CODCOLIGADA
AND TMOV.IDMOV =2156182--:IDMOV





SELECT tmov.* FROM TMOV 
					INNER JOIN TMOVCOMPL (NOLOCK) ON TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA  
					WHERE TMOV.CODTMV = '3.1.28' AND TMOV.CODCOLIGADA =1 and TMOVCOMPL.IDMOV_ORIGEM = 2156182




					select * from ttmv where codtmv = '3.1.28'