/*DECLARE @DATA_APROV_CONTROLE_INI AS DATE = '20230101',
		@DATA_APROV_CONTROLE_FIN AS DATE = '20250105';
		@EMPREENDIMENTO AS VARCHAR = '122',
		@GRUPO_ITEM AS VARCHAR = '66';*/

SELECT 

CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_ENGENHARIA)) AS CRIACAO_ULTIMA_APROV_ENG,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA)) AS CRIACAO_PRIMEIRA_APROV_ENG,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_CADASTRO)) AS CRIACAO_PRIMEIRO_CADASTRO,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.PRIMEIRA_DATA_CADASTRO),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA)) AS CADASTRO_PRIMEIRA_APROV_ENG,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA),CONVERT (DATE,GRUPO.PRIMEIRA_DATA_DESAPROVACAO)) AS PRIMEIRA_APROV_ENG_PRIMEIRA_DESAPROV,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_ENGENHARIA),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_CONTROLE)) AS ULTIMA_APROV_ENG_ULTIMA_APROV_CONTROLE,
CORPORE_RESIDENCIAL.DBO.DIAS_UTEIS(CONVERT (DATE,GRUPO.DATA_CRIACAO),CONVERT (DATE,GRUPO.ULTIMA_DATA_APRV_CONTROLE)) AS CRIACAO_ULTIMA_APROV_CONTROLE,

/* ALTERAÇÃO REALIZADA POR GABRIEL HIAGO DIA 21/09. SOLCITADO POR WSLEY NUNES E CAMILA PIRES. */
(SELECT TOP 1 DAT_APROVACAO_QUALIDADE FROM QUALIDADE.FICHA_VERIFICACAO 
INNER JOIN QUALIDADE.FICHA_VERIFICACAO_REVISAO ON QUALIDADE.FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO = QUALIDADE.FICHA_VERIFICACAO.ID_FICHA_VERIFICACAO
INNER JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO ON QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO = QUALIDADE.FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO AND FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO
INNER JOIN QUALIDADE.FICHA_PREENCHIDA ON QUALIDADE.FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = [QUALIDADE].[FICHA_VERIFICACAO_EMPREENDIMENTO].ID_FICHA_VERIFICACAO_EMPREENDIMENTO 
WHERE  QUALIDADE.FICHA_VERIFICACAO .APROVADO_QUALIDADE <> 0 AND FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO) AS DATA_APROV_QUALIDADE,

(SELECT MIN (FICHA_PREENCHIDA.DAT_INICIO_SERVICO) FROM QUALIDADE.FICHA_PREENCHIDA (NOLOCK)
INNER JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)

WHERE	FICHA_PREENCHIDA.ID_OBRA IN (SELECT ID_OBRA FROM OBRA WHERE OBRA.ID_EMPREENDIMENTO = GRUPO.ID_EMPREENDIMENTO)
AND		FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO) AS DATA_INICIO_SERVICO,

(SELECT TOP 1 SUBSTRING(ASPNET_USERS.USERNAME,9,100) FROM QUALIDADE.FICHA_PREENCHIDA (NOLOCK)
INNER JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO (NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
INNER JOIN ASPNET_USERS (NOLOCK) ON (ASPNET_USERS.USERID = FICHA_PREENCHIDA.USERID)
WHERE	FICHA_PREENCHIDA.ID_OBRA IN (SELECT ID_OBRA FROM OBRA WHERE OBRA.ID_EMPREENDIMENTO = GRUPO.ID_EMPREENDIMENTO)
AND		FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = GRUPO.ID_ITEM_EMPREENDIMENTO ORDER BY FICHA_PREENCHIDA.DAT_INICIO_SERVICO) AS USUARIO_VERIFICADOR,
GRUPO.ID_EMPREENDIMENTO,
GRUPO.NOM_EMPREENDIMENTO,
GRUPO.ID_GRUPO_ITEM,
GRUPO.NOM_GRUPO_ITEM,
GRUPO.CODIGO,
GRUPO.NOM_ITEM,
GRUPO.SIGLA,
GRUPO.ID_ITEM_EMPREENDIMENTO,
GRUPO.PRECO_UNITARIO,
GRUPO.PRECO_ORCADO,
GRUPO.QUANTIDADE_MAX,
GRUPO.PRECO_TOTAL_REAL,
GRUPO.PRECO_TOTAL_ORCADO,
GRUPO.USUARIO_CRIACAO,
GRUPO.DATA_CRIACAO,
GRUPO.ULTIMO_USUARIO_CADASTRO,
GRUPO.ULTIMA_DATA_CADASTRO,
GRUPO.PRIMEIRO_USUARIO_CADASTRO,
GRUPO.PRIMEIRA_DATA_CADASTRO,
GRUPO.ULTIMO_USUARIO_APR_ENGENHARIA,
GRUPO.ULTIMA_DATA_APRV_ENGENHARIA,
GRUPO.PRIMEIRO_USUARIO_APR_ENGENHARIA,
GRUPO.PRIMEIRA_DATA_APRV_ENGENHARIA,
GRUPO.ULTIMO_USUARIO_APR_CONTROLE,
GRUPO.ULTIMA_DATA_APRV_CONTROLE,
GRUPO.ULTIMO_HISTORICO_APRV_CONTROLE,
GRUPO.ULTIMO_USUARIO_DESAPROVAÇAO,
GRUPO.ULTIMA_DATA_DESAPROVACAO,
GRUPO.PRIMEIRO_USUARIO_DESAPROVAÇAO,
GRUPO.PRIMEIRA_DATA_DESAPROVACAO,
GRUPO.ULTIMO_HISTORICO_DESAPROVACAO,
GRUPO.REVISAO,
GRUPO.PRECO_ANTERIOR,
GRUPO.ACRESCIMO_PREÇO,
ISNULL(GRUPO.QTD_MEDIDA,0) AS 'QTD_MEDIDA',
ISNULL((GRUPO.PRECO_UNITARIO * GRUPO.QTD_MEDIDA),0) AS TOTAL_MEDIDO

FROM 

(SELECT 

EMPREENDIMENTO.ID_EMPREENDIMENTO,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.CODIGO,
ITEM_EMPREENDIMENTO.NOM_ITEM,
GRUPO_ITEM.ID_GRUPO_ITEM,
GRUPO_ITEM.NOM_GRUPO_ITEM,
UNIDADE_MEDIDA.SIGLA,
ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.PRECO_UNITARIO,
ITEM_EMPREENDIMENTO.PRECO_ORCADO,
SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS QUANTIDADE_MAX, /*QUANTIDADE SOMADA */
ITEM_EMPREENDIMENTO.PRECO_UNITARIO * SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS PRECO_TOTAL_REAL,
ITEM_EMPREENDIMENTO.PRECO_ORCADO * SUM (ITEM_EMPREENDIMENTO_OBRA.QUANTIDADE_MAX) AS PRECO_TOTAL_ORCADO,
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ASPNET_USERS (NOLOCK) WHERE USERID = USERID_CRIACAO) AS USUARIO_CRIACAO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 1 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS DATA_CRIACAO,


/* CADASTRO */

(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_CADASTRO,
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_CADASTRO,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_CADASTRO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 2 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_CADASTRO,




/* ENGENHARIA */
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_APR_ENGENHARIA,
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_APRV_ENGENHARIA,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) 
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_APR_ENGENHARIA,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 3 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_APRV_ENGENHARIA,

/*CONTROLE*/
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO  (NOLOCK)
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_APR_CONTROLE,

(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_APRV_CONTROLE,

(SELECT TOP 1 OBSERVACOES FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO AND DAT_HISTORICO = 
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) ) AS ULTIMO_HISTORICO_APRV_CONTROLE,

/*DESAPROVAÇÃO*/
(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK)  
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MAX(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS ULTIMO_USUARIO_DESAPROVAÇAO,

(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS ULTIMA_DATA_DESAPROVACAO,


(SELECT SUBSTRING (ASPNET_USERS.USERNAME,9,100) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK)  
INNER JOIN ASPNET_USERS(NOLOCK) ON (ITEM_EMPREENDIMENTO_HISTORICO.USERID = ASPNET_USERS.USERID) WHERE ID_ITEM_EMPREENDIMENTO_HISTORICO = (SELECT MIN(ITEM_EMPREENDIMENTO_HISTORICO.ID_ITEM_EMPREENDIMENTO_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)) AS PRIMEIRO_USUARIO_DESAPROVAÇAO,
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS PRIMEIRA_DATA_DESAPROVACAO,

(SELECT TOP 1 OBSERVACOES FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO AND DAT_HISTORICO = 
(SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 6 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) ) AS ULTIMO_HISTORICO_DESAPROVACAO,
ITEM_EMPREENDIMENTO.REVISAO,
LAG(ITEM_EMPREENDIMENTO.PRECO_UNITARIO) OVER (PARTITION BY ITEM_EMPREENDIMENTO.CODIGO ORDER BY ITEM_EMPREENDIMENTO.REVISAO) AS PRECO_ANTERIOR,
    ITEM_EMPREENDIMENTO.PRECO_UNITARIO - ISNULL(LAG(ITEM_EMPREENDIMENTO.PRECO_UNITARIO) OVER (PARTITION BY ITEM_EMPREENDIMENTO.CODIGO ORDER BY ITEM_EMPREENDIMENTO.REVISAO), 0) AS 'ACRESCIMO_PREÇO',

(SELECT SUM(QTD_MEDIDA) AS SOMA_QTD
 FROM MEDICAO_ITEM_EMPREENDIMENTO
 WHERE ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = MEDICAO_ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) AS 'QTD_MEDIDA'



FROM ITEM_EMPREENDIMENTO (NOLOCK)

INNER JOIN	EMPREENDIMENTO				(NOLOCK) ON (EMPREENDIMENTO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO)
LEFT JOIN ITEM_EMPREENDIMENTO_OBRA		(NOLOCK) ON (ITEM_EMPREENDIMENTO_OBRA.ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)
LEFT JOIN	OBRA						(NOLOCK) ON (OBRA.ID_OBRA = ITEM_EMPREENDIMENTO_OBRA.ID_OBRA)
INNER JOIN  GRUPO_ITEM					(NOLOCK) ON (GRUPO_ITEM.ID_GRUPO_ITEM = ITEM_EMPREENDIMENTO.ID_GRUPO_ITEM)
INNER JOIN  UNIDADE_MEDIDA				(NOLOCK) ON (UNIDADE_MEDIDA.ID_UNIDADE_MEDIDA = ITEM_EMPREENDIMENTO.ID_UNIDADE_MEDIDA)

WHERE (SELECT MAX (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO (NOLOCK) WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO) BETWEEN @DATA_APROV_CONTROLE_INI AND @DATA_APROV_CONTROLE_FIN


GROUP BY 

EMPREENDIMENTO.ID_EMPREENDIMENTO,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.CODIGO,
ITEM_EMPREENDIMENTO.NOM_ITEM,
GRUPO_ITEM.ID_GRUPO_ITEM,
GRUPO_ITEM.NOM_GRUPO_ITEM,
UNIDADE_MEDIDA.SIGLA,
ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO,
ITEM_EMPREENDIMENTO.PRECO_UNITARIO,
ITEM_EMPREENDIMENTO.PRECO_ORCADO,
ITEM_EMPREENDIMENTO.USERID_CRIACAO,
ITEM_EMPREENDIMENTO.REVISAO,
ITEM_EMPREENDIMENTO.PRECO_UNITARIO

) AS GRUPO

WHERE		GRUPO.ID_EMPREENDIMENTO IN (@EMPREENDIMENTO)
AND		GRUPO.ID_GRUPO_ITEM IN (@GRUPO_ITEM)
AND  GRUPO.CODIGO = '45.0089'
ORDER BY GRUPO.ULTIMA_DATA_APRV_CONTROLE

