SELECT 
ob.RM_NOME,
AE.ID_AVALIACAO,
EMP.NOM_EMPREITEIRO,
((CASE 
	WHEN AEQS.TIPO = 1 THEN 'P'
	WHEN AEQS.TIPO = 2 THEN 'Q' 
	WHEN AEQS.TIPO = 3 THEN 'C' END) +	'/'	+ CONT.COD_CONTRATO) AS 'CONTRATO',
AE.DATA_PREENCHIMENTO,
DBO.TRAZ_USERNAME(AE.USUARIO_PREENCHIMENTO) AS 'USUARIO AVALIAÇÃO',
AEQS.NOME AS 'QUESTIONARIO',
(CASE 
	WHEN AEQS.TIPO = 1 THEN 'PERIODICO'
	WHEN AEQS.TIPO = 2 THEN 'QUITAÇÃO' 
	WHEN AEQS.TIPO = 3 THEN 'CRIAÇÃO' END) AS 'TIPO',
(CASE 
	WHEN AE.STATUS = 1 THEN 'PENDENTE'
	WHEN AE.STATUS = 2 THEN 'CADASTRADO'
	WHEN AE.STATUS = 3 THEN 'APROVADO'
	WHEN AE.STATUS = 4 THEN 'REJEITADO'
	WHEN AE.STATUS = 5 THEN 'CANCELADO' END) AS 'STATUS',
	AEQ.ID_QUESTAO,
	AEQ.TEXTO_PERGUNTA,
	(CASE WHEN AER.VALOR_RESPOSTA_TEXTO IS NOT NULL AND AER.VALOR_RESPOSTA IS NOT NULL THEN (CONVERT(VARCHAR(MAX),AER.VALOR_RESPOSTA) + ' - ' + CONVERT(VARCHAR(MAX),AER.VALOR_RESPOSTA_TEXTO))
		  WHEN AER.VALOR_RESPOSTA_TEXTO IS NULL THEN (CONVERT(VARCHAR(MAX),AER.VALOR_RESPOSTA))
		  WHEN AER.VALOR_RESPOSTA IS NULL THEN CONVERT(VARCHAR(MAX),AER.VALOR_RESPOSTA_TEXTO) END) AS 'RESPOSTA'


FROM [questionario].[AVALIACOES_EMPREITEIROS]						AS AE
INNER JOIN EMPREITEIRO												AS EMP							(NOLOCK) ON EMP.ID_EMPREITEIRO = AE.ID_EMPREITEIRO
INNER JOIN OBRA														AS OB							(NOLOCK) ON OB.ID_OBRA = AE.ID_OBRA
INNER JOIN CONTRATO													AS CONT							(NOLOCK) ON CONT.ID_CONTRATO = AE.ID_CONTRATO
INNER JOIN [questionario].[AVALIACAO_EMPREITEIROS_QUESTIONARIOS]	AS AEQS							(NOLOCK) ON AEQS.ID_QUESTIONARIO = AE.ID_QUESTIONARIO
INNER JOIN [questionario].[AVALIACAO_EMPREITEIROS_QUESTOES]			AS AEQ							(NOLOCK) ON AEQS.ID_QUESTIONARIO = AEQ.ID_QUESTIONARIO 
INNER JOIN [questionario].[AVALIACAO_EMPREITEIROS_OPCOES]			AS AEQO							(NOLOCK) ON AEQO.ID_QUESTAO = AEQ.ID_QUESTAO
INNER JOIN [questionario].[AVALIACAO_EMPREITEIRO_RESPOSTA]			AS AER							(NOLOCK) ON AER.ID_AVALIACAO = AE.ID_AVALIACAO AND AER.ID_QUESTIONARIO = AE.ID_QUESTIONARIO AND AER.ID_QUESTAO = AEQ.ID_QUESTAO



WHERE AE.ID_OBRA IN (@OBRA)


GROUP BY 
AE.ID_AVALIACAO,
EMP.NOM_EMPREITEIRO,
AEQS.TIPO,
CONT.COD_CONTRATO,
AEQS.NOME,
AE.DATA_PREENCHIMENTO,
AE.USUARIO_PREENCHIMENTO,
AE.STATUS,
AEQ.ID_QUESTAO,
AEQ.TEXTO_PERGUNTA,
AER.VALOR_RESPOSTA,
AER.VALOR_RESPOSTA_TEXTO