
select 
CODIGO,
NOM_ITEM, 
[dbo].[ITEM_EMPREENDIMENTO].ID_OBJETO_CONTRATO, 
* 
from [dbo].[CONTRATO_ITEM_EMPREENDIMENTO]
JOIN [dbo].[CONTRATO]				(NOLOCK) ON [dbo].[CONTRATO].ID_CONTRATO = [dbo].[CONTRATO_ITEM_EMPREENDIMENTO].ID_CONTRATO
JOIN [dbo].[ITEM_EMPREENDIMENTO]	(NOLOCK) ON [dbo].[ITEM_EMPREENDIMENTO].ID_ITEM_EMPREENDIMENTO = [dbo].[CONTRATO_ITEM_EMPREENDIMENTO].ID_ITEM_EMPREENDIMENTO


WHERE ID_OBRA = 208 AND ID_EMPREITEIRO = 3038 

SELECT * FROM [qualidade].[FICHA_VERIFICACAO_REVISAO]
SELECT * FROM [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO]

SELECT * FROM EMPREENDIMENTO WHERE NOM_EMPREENDIMENTO LIKE '%ARBO%'

select NOM_FICHA_VERIFICACAO, COD_FICHA_VERIFICACAO, * 
from [qualidade].[FICHA_VERIFICACAO]
JOIN [qualidade].[FICHA_VERIFICACAO_REVISAO] ON [qualidade].[FICHA_VERIFICACAO_REVISAO].ID_FICHA_VERIFICACAO = [qualidade].[FICHA_VERIFICACAO].ID_FICHA_VERIFICACAO
JOIN [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO] ON [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO].ID_FICHA_VERIFICACAO_REVISAO = [qualidade].[FICHA_VERIFICACAO_REVISAO].ID_FICHA_VERIFICACAO_REVISAO
WHERE 
 ID_EMPREENDIMENTO = 152
AND ID_ITEM_EMPREENDIMENTO IN (46115
,46116
,60847
,60849
,60847
,60849)
--ID_OBRA = 208 AND ID_EMPREITEIRO = 3038 

/*
60849

60847
*/