SELECT 
obra.RM_NOME
ID_MEDICAO, 
COD_MEDICAO, 
EMPREITEIRO.NOM_EMPREITEIRO, 
CONVERT(VARCHAR,MEDICAO.DAT_CRIACAO,103) AS 'DATA_CRIACAO', 
[dbo].[TRAZ_USERNAME](MEDICAO.UserId_CRIACAO) AS 'USUARIO_CRIAÇÃO',
CONVERT(VARCHAR,MEDICAO.DAT_CADASTRO,103) AS 'DATA_CADASTRO',
[dbo].[TRAZ_USERNAME](MEDICAO.UserId_CADASTRO) AS 'USUARIO_CRIAÇÃO',
CONVERT(VARCHAR,DAT_INICIO,103) AS 'DATA INICIO',
CONVERT(VARCHAR,DAT_FIM,103) AS 'DATA FIM',
CONVERT(VARCHAR,DAT_VENCIMENTO,103) AS 'DATA VENCIMENTO',
ETAPA.NOM_ETAPA AS 'ETAPA',
MEDICAO.VLR_TOTAL AS 'VALOR TOTAL',
VLR_LIQUIDO AS 'VALOR LIQUIDO',
(CASE WHEN MEDICAO.EXCLUIDO = 1 THEN 'SIM' ELSE 'NAO' END) AS 'EXCLUIDO'

FROM MEDICAO 
INNER JOIN OBRA ON OBRA.ID_OBRA = MEDICAO.ID_OBRA
INNER JOIN CONTRATO ON CONTRATO.ID_CONTRATO = MEDICAO.ID_CONTRATO
INNER JOIN EMPREITEIRO ON EMPREITEIRO.ID_EMPREITEIRO = CONTRATO.ID_EMPREITEIRO
INNER JOIN ETAPA ON MEDICAO.ID_ETAPA = ETAPA.ID_ETAPA

WHERE
--ID_OBRA = 199

--AND
VLR_LIQUIDO < 0
--AND  ID_MEDICAO = 93507
AND MEDICAO.EXCLUIDO = 0

ORDER BY MEDICAO.DAT_CRIACAO DESC

SELECT * 
FROM MEDICAO

/*
SELECT * 
FROM OBRA 
WHERE RM_NOME LIKE '%MARES%'
*/