DECLARE @OBRA AS INT = 201,
		@FDV AS INT = 5314,
		@DATA_INI AS DATE = '20200101',
		@DATA_FINAL AS DATE = '20250603';
		
SELECT 
	(
		CASE 
			WHEN G.SIGLA_EMP = 'EXCECAO' THEN 'EXCECAO'
			WHEN G.EXCECAO_PREENCHIDA <> 'NAO' THEN 'EXCECAO CADASTRADA'
			/* NÃO CONFORME */ 
			WHEN G.TOTAL_METODO > G.FICHAS_PREENCHIDAS AND G.STATUS_FICHA = 'NÃO CONFORME' THEN ('EM ANDAMENTO' + ' - ' + 'NÃO CONFORME' + ' - ' + G.SIGLA_EMP)
			WHEN G.STATUS_FICHA = 'NÃO CONFORME' THEN ('NÃO CONFORME' + ' - ' + G.SIGLA_EMP)

			/* CONFORME REINSPEÇÃO */ 
			WHEN G.TOTAL_METODO > G.FICHAS_PREENCHIDAS AND G.STATUS_FICHA = 'CONFORME APÓS REINSPEÇÃO' THEN 'EM ANDAMENTO' + ' - ' + 'CONFORME APÓS REINSPEÇÃO' + ' - ' + G.SIGLA_EMP
			WHEN G.STATUS_FICHA = 'CONFORME APÓS REINSPEÇÃO' THEN 'CONFORME APÓS REINSPEÇÃO'

			/* NÃO SE APLICA */
			WHEN G.STATUS_FICHA = 'NÃO SE APLICA' THEN 'NÃO SE APLICA'

			/* CONFORME */
			WHEN G.TOTAL_METODO > G.FICHAS_PREENCHIDAS AND G.STATUS_FICHA = 'CONFORME'  THEN  ('EM ANDAMENTO' + ' - ' + 'CONFORME' + ' - ' + G.SIGLA_EMP)
			WHEN G.STATUS_FICHA = 'CONFORME' AND G.FLG_LIBERADA = 1 THEN  ('LIBERADA' + ' - ' + G.SIGLA_EMP)

			ELSE 'FICHA NÃO PREENCHIDA'
			end) 'CASE TEST',
	G.ID_FICHA_VERIFICACAO_REVISAO,
G.TOTAL_METODO,
G.FICHAS_PREENCHIDAS,
G.STATUS_VERIFICACAO,
G.NOM_LOCAL_BLOCO,
G.ID_LOCAL_BLOCO,
G.NOME_OBRA,
G.ANDAR,
G.NOM_LOCAL_APARTAMENTO,
G.CONT_AP,
G.ID_LOCAL_APARTAMENTO,
G.FLG_BLOQUEIA_PAGAMENTO,
G.FLG_LIBERADA,
G.sigla1,
G.SIGLA_EMP,
G.ETAPA,
G.EXCECAO_PREENCHIDA

FROM(

SELECT 
(CASE 
	WHEN PREENCHIMENTO.STATUS_VERIFICACAO = 3 THEN 'NÃO CONFORME'
	WHEN PREENCHIMENTO.STATUS_VERIFICACAO = 2 THEN 'CONFORME APÓS REINSPEÇÃO'
	WHEN PREENCHIMENTO.STATUS_VERIFICACAO = 1 THEN 'NÃO SE APLICA'
	ELSE 'CONFORME'
	END) AS 'STATUS_FICHA',
PREENCHIMENTO.ID_FICHA_VERIFICACAO_REVISAO,
PREENCHIMENTO.TOTAL_METODO,
PREENCHIMENTO.FICHAS_PREENCHIDAS,
PREENCHIMENTO.STATUS_VERIFICACAO,
PREENCHIMENTO.FLG_LIBERADA,
LOCAL_BLOCO.NOM_LOCAL_BLOCO,
LOCAL_BLOCO.ID_LOCAL_BLOCO,
OBRA.RM_NOME AS NOME_OBRA,
CAST(QUALIDADE.LOCAL_PAVIMENTO.NUMERO AS INT) AS 'ANDAR',
LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
CAST(RIGHT(QUALIDADE.LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,2) AS INT) AS 'CONT_AP',
LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
PREENCHIMENTO.FLG_BLOQUEIA_PAGAMENTO,
PREENCHIMENTO.SIGLA_EMP as sigla1,
ISNULL (PREENCHIMENTO.SIGLA_EMP,
								(SELECT 
									'EXCECAO'
									FROM QUALIDADE.LOCAL_APARTAMENTO_EXCECAO (NOLOCK)
									WHERE	QUALIDADE.LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO = LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO
									AND		QUALIDADE.LOCAL_APARTAMENTO_EXCECAO.ID_FICHA_VERIFICACAO = @FDV)
								) AS SIGLA_EMP,


(SELECT 
MAX (MEDICAO.ID_ETAPA) AS ETAPA_MEDICAO

FROM QUALIDADE.FICHA_PREENCHIDA (NOLOCK)
LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_REVISAO			(NOLOCK) ON (FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO)
LEFT JOIN QUALIDADE.MEDICAO_FICHA_PREENCHIDA			(NOLOCK) ON (MEDICAO_FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)
LEFT JOIN MEDICAO_ITEM_EMPREENDIMENTO					(NOLOCK) ON (MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO_ITEM_EMPREENDIMENTO = MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN MEDICAO										(NOLOCK) ON (MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO)

WHERE	FICHA_PREENCHIDA.FLG_LIBERADA = 1
AND		FICHA_PREENCHIDA.ID_LOCAL_APARTAMENTO = LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO
AND		FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO = @FDV
AND		MEDICAO.EXCLUIDO = 0
/*CONDICAO COLOCADA A PEDIDO DO CADU PARA NÃO TRAZER MEDIÇÕES NEGATIVAS */
GROUP BY MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA
HAVING 	SUM (MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA) > 0) AS ETAPA,

ISNULL(PREENCHIMENTO.EXCECAO_PREENCHIDA,'NAO') AS EXCECAO_PREENCHIDA

FROM QUALIDADE.LOCAL_BLOCO (NOLOCK)

LEFT JOIN [QUALIDADE].[LOCAL_CONDOMINIO] AS CONDOMINIO  (NOLOCK) ON (CONDOMINIO.ID_LOCAL_CONDOMINIO = QUALIDADE.LOCAL_BLOCO.ID_LOCAL_CONDOMINIO)
LEFT JOIN OBRA											(NOLOCK) ON (OBRA.ID_OBRA = LOCAL_BLOCO.ID_OBRA)
LEFT JOIN QUALIDADE.LOCAL_PAVIMENTO						(NOLOCK) ON (LOCAL_PAVIMENTO.ID_LOCAL_BLOCO = LOCAL_BLOCO.ID_LOCAL_BLOCO)
LEFT JOIN QUALIDADE.LOCAL_APARTAMENTO					(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_PAVIMENTO = LOCAL_PAVIMENTO.ID_LOCAL_PAVIMENTO)
LEFT JOIN (
			SELECT 
				(SELECT 
					COUNT(FVM1.ORDEM) AS 'CONTAGEM DE METODOS'
					FROM QUALIDADE.FICHA_PREENCHIDA FP1							(NOLOCK)
					LEFT JOIN QUALIDADE.FICHA_PREENCHIDA_DETALHE FPD1			(NOLOCK) ON (FP1.ID_FICHA_PREENCHIDA = FPD1.ID_FICHA_PREENCHIDA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_RESPOSTA FVR1			(NOLOCK) ON (FVR1.ID_FICHA_VERIFICACAO_RESPOSTA = FPD1.ID_FICHA_VERIFICACAO_RESPOSTA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_METODO FVM1			(NOLOCK) ON (FVM1.ID_FICHA_VERIFICACAO_METODO = FPD1.ID_FICHA_VERIFICACAO_METODO)
					WHERE 	FP1.ID_FICHA_PREENCHIDA = FP.ID_FICHA_PREENCHIDA
					) AS 'TOTAL_METODO',
				(SELECT 
					COUNT(FVR2.ID_FICHA_VERIFICACAO_RESPOSTA) AS 'CONTAGEM DE METODOS2'
					FROM QUALIDADE.FICHA_PREENCHIDA FP2							(NOLOCK)
					LEFT JOIN QUALIDADE.FICHA_PREENCHIDA_DETALHE FPD2			(NOLOCK) ON (FP2.ID_FICHA_PREENCHIDA = FPD2.ID_FICHA_PREENCHIDA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_RESPOSTA FVR2			(NOLOCK) ON (FVR2.ID_FICHA_VERIFICACAO_RESPOSTA = FPD2.ID_FICHA_VERIFICACAO_RESPOSTA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_METODO FVM2			(NOLOCK) ON (FVM2.ID_FICHA_VERIFICACAO_METODO = FPD2.ID_FICHA_VERIFICACAO_METODO)
					WHERE 	FP2.ID_FICHA_PREENCHIDA = FP.ID_FICHA_PREENCHIDA
					) AS 'FICHAS_PREENCHIDAS',
				FVRV.ID_FICHA_VERIFICACAO_REVISAO,
				LOCAL_BLOCO.NOM_LOCAL_BLOCO,
				LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
				LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,

				/*CASE 
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1  -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2  -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3  -- NÃO SE APLICA
							ELSE 999
						END
					) = 1 THEN 'NÃO CONFORME'
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1 -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2 -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3 -- NÃO SE APLICA
							ELSE 999
						END
					) = 2 THEN 'CONFORME APÓS REINSPEÇÃO'
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1 -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2 -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3 -- NÃO SE APLICA
							ELSE 999
						END
					) = 3 THEN 'NÃO SE APLICA'
					ELSE 'CONFORME'
				END AS STATUS_VERIFICACAO,*/
					(SELECT 
					TOP 1 (CASE 
						WHEN FVR3.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 3 -- NÃO CONFORME
						WHEN FVR3.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2 -- CONFORME APÓS REINSPEÇÃO
						WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 1  -- NÃO SE APLICA
						ELSE 0
						END) 
					FROM QUALIDADE.FICHA_PREENCHIDA FP3							(NOLOCK)
					LEFT JOIN QUALIDADE.FICHA_PREENCHIDA_DETALHE FPD3			(NOLOCK) ON (FP3.ID_FICHA_PREENCHIDA = FPD3.ID_FICHA_PREENCHIDA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_RESPOSTA FVR3			(NOLOCK) ON (FVR3.ID_FICHA_VERIFICACAO_RESPOSTA = FPD3.ID_FICHA_VERIFICACAO_RESPOSTA)
					LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_METODO FVM3			(NOLOCK) ON (FVM3.ID_FICHA_VERIFICACAO_METODO = FPD3.ID_FICHA_VERIFICACAO_METODO)
					WHERE 	FP3.ID_FICHA_PREENCHIDA = FP.ID_FICHA_PREENCHIDA
					ORDER BY 1 DESC)
					AS 'STATUS_VERIFICACAO',
							(CASE 
							 
							 WHEN FP.ID_LOCAL_APARTAMENTO IN (
																				SELECT 
																				LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO
																				FROM QUALIDADE.LOCAL_APARTAMENTO_EXCECAO	(NOLOCK)

																				WHERE	LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO = FP.ID_LOCAL_APARTAMENTO
																				AND		LOCAL_APARTAMENTO_EXCECAO.ID_FICHA_VERIFICACAO = fv.ID_FICHA_VERIFICACAO
																			)

							  THEN 'SIM' ELSE 'NAO' END

						) AS EXCECAO_PREENCHIDA,
						ISNULL (EMPREITEIRO.SIGLA_EMPREITEIRO, LEFT (EMPREITEIRO.NOM_EMPREITEIRO,5))AS SIGLA_EMP,
						FLG_BLOQUEIA_PAGAMENTO,
						FLG_LIBERADA

						FROM QUALIDADE.FICHA_PREENCHIDA FP							(NOLOCK)
						LEFT JOIN QUALIDADE.FICHA_PREENCHIDA_DETALHE FPD			(NOLOCK) ON (FP.ID_FICHA_PREENCHIDA = FPD.ID_FICHA_PREENCHIDA)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_RESPOSTA FVR			(NOLOCK) ON (FVR.ID_FICHA_VERIFICACAO_RESPOSTA = FPD.ID_FICHA_VERIFICACAO_RESPOSTA)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_METODO FVM			(NOLOCK) ON (FVM.ID_FICHA_VERIFICACAO_METODO = FPD.ID_FICHA_VERIFICACAO_METODO)
						LEFT JOIN QUALIDADE.METODO M								(NOLOCK) ON (FVM.ID_METODO = M.ID_METODO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO FVE	(NOLOCK) ON (FVE.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FP.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_REVISAO FVRV			(NOLOCK) ON (FVRV.ID_FICHA_VERIFICACAO_REVISAO = FVE.ID_FICHA_VERIFICACAO_REVISAO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO FV					(NOLOCK) ON (FV.ID_FICHA_VERIFICACAO = FVRV.ID_FICHA_VERIFICACAO)
						LEFT JOIN OBRA O											(NOLOCK) ON (O.ID_OBRA = FP.ID_OBRA)
						LEFT JOIN QUALIDADE.LOCAL_BLOCO LOCAL_BLOCO					(NOLOCK) ON (LOCAL_BLOCO.ID_LOCAL_BLOCO = FP.ID_LOCAL_BLOCO)
						LEFT JOIN QUALIDADE.LOCAL_APARTAMENTO LOCAL_APARTAMENTO		(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO = FP.ID_LOCAL_APARTAMENTO)
						LEFT JOIN EMPREITEIRO										(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = FP.ID_EMPREITEIRO)
						
						WHERE 
							FVRV.ID_FICHA_VERIFICACAO = @FDV
							--FP.ID_FICHA_PREENCHIDA = @FDV
							AND	FP.ID_OBRA = @OBRA
							AND	FP.DAT_PREENCHIMENTO BETWEEN @DATA_INI AND @DATA_FINAL
						
						GROUP BY 
							LOCAL_BLOCO.NOM_LOCAL_BLOCO,
							FPD.ID_FICHA_VERIFICACAO_METODO,
							FVRV.ID_FICHA_VERIFICACAO_REVISAO,
							LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
							LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
							FP.ID_LOCAL_APARTAMENTO,
							FV.ID_FICHA_VERIFICACAO,
							EMPREITEIRO.NOM_EMPREITEIRO,
							EMPREITEIRO.SIGLA_EMPREITEIRO,
							FP.FLG_BLOQUEIA_PAGAMENTO,
							FP.FLG_LIBERADA,
							FP.ID_FICHA_PREENCHIDA,
							FVR.ID_FICHA_VERIFICACAO_RESPOSTA

			) AS PREENCHIMENTO ON (PREENCHIMENTO.ID_LOCAL_APARTAMENTO = QUALIDADE.LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO)

WHERE	LOCAL_BLOCO.ID_OBRA = @OBRA
--AND LOCAL_BLOCO.ID_LOCAL_BLOCO = @BLOCO
--AND CONDOMINIO.ID_LOCAL_CONDOMINIO = @CONDOMINIO

) AS G

GROUP BY 
G.ID_FICHA_VERIFICACAO_REVISAO,
G.TOTAL_METODO,
G.FICHAS_PREENCHIDAS,
G.STATUS_FICHA,
G.STATUS_VERIFICACAO,
G.NOM_LOCAL_BLOCO,
G.ID_LOCAL_BLOCO,
G.NOME_OBRA,
G.ANDAR,
G.NOM_LOCAL_APARTAMENTO,
G.CONT_AP,
G.ID_LOCAL_APARTAMENTO,
G.FLG_BLOQUEIA_PAGAMENTO,
G.FLG_LIBERADA,
G.sigla1,
G.SIGLA_EMP,
G.ETAPA,
G.EXCECAO_PREENCHIDA

ORDER BY 
G.ANDAR,
G.CONT_AP
