USE DBCONTROLEMP
SELECT DISTINCT 
OBRA.RM_NOME,
NOM_EMPREITEIRO,
CONCAT([qualidade].[FICHA_VERIFICACAO].COD_FICHA_VERIFICACAO, ' - ', [qualidade].[FICHA_VERIFICACAO].NOM_FICHA_VERIFICACAO) AS FDV,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
CONTRATO.ID_CONTRATO,
COD_CONTRATO,
CONCAT ([qualidade].[FICHA_PREENCHIDA_DETALHE].ID_FICHA_VERIFICACAO_RESPOSTA, ' - ' , [FICHA_VERIFICACAO_RESPOSTA].NOM_FICHA_VERIFICACAO_RESPOSTA) AS REPOSTA_FICHA,
(CASE 	WHEN FICHA_PREENCHIDA_DETALHE.FLG_ACEITO = 1 THEN 'SIM' ELSE 'NÃO' END) AS FICHA_ACEITA,
[qualidade].[LOCAL_PAVIMENTO].NUMERO,
[qualidade].[LOCAL_APARTAMENTO].NOM_LOCAL_APARTAMENTO


FROM EMPREENDIMENTO

JOIN OBRA																									ON EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO AND EMPREENDIMENTO.RM_CODCOLIGADA = OBRA.RM_CODCOLIGADA
JOIN [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO]				ON [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO].ID_EMPREENDIMENTO = EMPREENDIMENTO.ID_EMPREENDIMENTO
JOIN [qualidade].[FICHA_VERIFICACAO_REVISAO]								ON [qualidade].[FICHA_VERIFICACAO_REVISAO].ID_FICHA_VERIFICACAO_REVISAO = [FICHA_VERIFICACAO_EMPREENDIMENTO].ID_FICHA_VERIFICACAO_REVISAO
JOIN [qualidade].[FICHA_VERIFICACAO]												ON [qualidade].[FICHA_VERIFICACAO].ID_FICHA_VERIFICACAO = [qualidade].[FICHA_VERIFICACAO_REVISAO].ID_FICHA_VERIFICACAO
JOIN CONTRATO																						ON CONTRATO.ID_OBRA = OBRA.ID_OBRA
JOIN EMPREITEIRO																						ON EMPREITEIRO.ID_EMPREITEIRO = CONTRATO.ID_EMPREITEIRO
JOIN [qualidade].[FICHA_PREENCHIDA]													ON [qualidade].[FICHA_PREENCHIDA].ID_EMPREITEIRO = EMPREITEIRO.ID_EMPREITEIRO and [qualidade].[FICHA_PREENCHIDA].ID_FICHA_VERIFICACAO_EMPREENDIMENTO = [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO].ID_FICHA_VERIFICACAO_EMPREENDIMENTO
JOIN [dbo].[MEDICAO]																				ON [dbo].[MEDICAO].ID_CONTRATO = CONTRATO.ID_CONTRATO AND [dbo].[MEDICAO].ID_OBRA = OBRA.ID_OBRA
JOIN [qualidade].[FICHA_PREENCHIDA_DETALHE]								ON [qualidade].[FICHA_PREENCHIDA_DETALHE].ID_FICHA_PREENCHIDA = [qualidade].[FICHA_PREENCHIDA].ID_FICHA_PREENCHIDA
JOIN [qualidade].[FICHA_VERIFICACAO_RESPOSTA]                           ON [qualidade].[FICHA_VERIFICACAO_RESPOSTA].ID_FICHA_VERIFICACAO_RESPOSTA = [qualidade].[FICHA_PREENCHIDA_DETALHE].ID_FICHA_VERIFICACAO_RESPOSTA
--JOIN [qualidade].[FICHA_VERIFICACAO_ITEM_PADRAO]					ON [qualidade].[FICHA_VERIFICACAO_ITEM_PADRAO].ID_FICHA_VERIFICACAO = [qualidade].[FICHA_VERIFICACAO].ID_FICHA_VERIFICACAO
--JOIN [dbo].[ITEM]																					ON [dbo].[ITEM].ID_ITEM = [FICHA_VERIFICACAO_ITEM_PADRAO].ID_ITEM
JOIN [qualidade].[LOCAL_PAVIMENTO]													ON ([qualidade].[LOCAL_PAVIMENTO].ID_LOCAL_BLOCO = [qualidade].[FICHA_PREENCHIDA].ID_LOCAL_BLOCO)
JOIN [qualidade].[LOCAL_APARTAMENTO]											ON [qualidade].[LOCAL_APARTAMENTO].ID_LOCAL_APARTAMENTO = [qualidade].[FICHA_PREENCHIDA].ID_LOCAL_APARTAMENTO



WHERE EMPREENDIMENTO.ID_EMPREENDIMENTO = 105 
AND EMPREITEIRO.ID_EMPREITEIRO = 4063 
AND OBRA.ID_OBRA = 153 
AND [dbo].[MEDICAO].ID_CONTRATO = 52615
AND [qualidade].[FICHA_VERIFICACAO].COD_FICHA_VERIFICACAO = '17.75'
AND [qualidade].[LOCAL_PAVIMENTO].NUMERO = 16 -- 16, 21
--AND[qualidade].[LOCAL_APARTAMENTO].NOM_LOCAL_APARTAMENTO = 2102 --  2102, 1608

--AND [qualidade].[FICHA_PREENCHIDA_DETALHE].ID_FICHA_VERIFICACAO_RESPOSTA <> 2



