USE DBCONTROLEMP
SELECT 
ID_EMPREITEIRO,
NOM_EMPREITEIRO AS Nome_do_empreiteiro,
NOM_FANTASIA AS Nome_Fantasia,
RM_CNPJ AS CNPJ,
RM_NOME_ESTADO AS ESTADO,
CONTRATO.ID_CONTRATO,
CONTRATO.COD_CONTRATO,
CONTRATO.DAT_INICIO_CONTRATO,
CONTRATO.DAT_FIM_CONTRATO,
CONTRATO.VLR_TOTAL,
ETAPA.NOM_ETAPA,
ETAPA.ACAO
FROM EMPREITEIRO

JOIN CONTRATO ON CONTRATO.ID_EMPREITEIRO = EMPREITEIRO.ID_EMPREITEIRO
JOIN ETAPA ON ETAPA.ID_ETAPA = CONTRATO.ID_ETAPA

WHERE
--ID_EMPREITEIRO = 'XXXXXXXXX'
--NOM_EMPREITEIRO LIKE ''