--SELECT * FROM [qualidade].[FICHA_PREENCHIDA] WHERE ID_EMPREITEIRO = 3038 AND ID_OBRA = 208-- AND ID_CONTRATO = 40169

--SELECT * FROM [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO] 
--SELECT * FROM [qualidade].[FICHA_VERIFICACAO]
--SELECT * FROM [qualidade].[FICHA_VERIFICACAO_REVISAO]

--SELECT * FROM [dbo].[CONTRATO] WHERE ID_EMPREITEIRO = 4063 AND ID_OBRA = 153  AND ID_CONTRATO = 52615

--SELECT * FROM [dbo].[OBJETO_CONTRATO] WHERE ID_OBJETO_CONTRATO = 15 
--SELECT * FROM [qualidade].[FICHA_PREENCHIDA]
--SELECT * FROM [qualidade].[FICHA_VERIFICACAO] 
--SELECT * FROM [dbo].[MEDICAO] WHERE ID_CONTRATO = 40169
SELECT * FROM [qualidade].[FICHA_VERIFICACAO_METODO]
SELECT * FROM [qualidade].[FICHA_VERIFICACAO_RESPOSTA]

SELECT * FROM EMPREITEIRO WHERE NOM_EMPREITEIRO LIKE '%VN_PINTURA%' --and ID_EMPREITEIRO = 4063

SELECT * FROM EMPREENDIMENTO WHERE NOM_EMPREENDIMENTO LIKE '%BUTA%' AND ID_EMPREENDIMENTO = 105

SELECT * FROM OBRA WHERE ID_EMPREENDIMENTO = 105 AND ID_OBRA = 153

SELECT * 

FROM MEDICAO 

JOIN CONTRATO ON MEDICAO.ID_CONTRATO = CONTRATO.ID_CONTRATO 
JOIN OBRA ON OBRA.ID_OBRA = MEDICAO.ID_OBRA 
JOIN EMPREENDIMENTO ON EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO


WHERE  CONTRATO.ID_CONTRATO = 52615



select * from [qualidade].[FICHA_PREENCHIDA]
SELECT * FROM [qualidade].[FICHA_PREENCHIDA_DETALHE]
SELECT * FROM [qualidade].[FICHA_PREENCHIDA_DETALHE_HISTORICO]
SELECT * FROM  [qualidade].[FICHA_PREENCHIDA_HISTORICO]
select * from [qualidade].[FICHA_VERIFICACAO_EMPREENDIMENTO]
select * from [qualidade].[FICHA_VERIFICACAO_RESPOSTA]
select * from [qualidade].[FICHA_VERIFICACAO]
SELECT * FROM [qualidade].[FICHA_VERIFICACAO_METODO]
select * from [qualidade].[FICHA_VERIFICACAO_ITEM_PADRAO]
SELECT * FROM [dbo].[ITEM]
select * from [qualidade].[FICHA_SITUACAO]

select * from[qualidade].[FICHA_VERIFICACAO_REVISAO]

SELECT * FROM OBRA WHERE RM_NOME LIKE '%ARBOR%'