SELECT 
QUALIDADE.FICHA_PREENCHIDA .ID_FICHA_PREENCHIDA,
QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_EMPREENDIMENTO,
QUALIDADE.FICHA_PREENCHIDA .ID_EMPREITEIRO,
QUALIDADE.FICHA_PREENCHIDA .ID_OBRA,
QUALIDADE.FICHA_PREENCHIDA .ID_FICHA_VERIFICACAO_EMPREENDIMENTO, 
QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO,
QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_EMPREENDIMENTO,
qualidade.FICHA_VERIFICACAO.COD_FICHA_VERIFICACAO,
qualidade.FICHA_VERIFICACAO.NOM_FICHA_VERIFICACAO,
qualidade.FICHA_VERIFICACAO.APROVADO_QUALIDADE,
qualidade.FICHA_VERIFICACAO_REVISAO.REVISAO

FROM QUALIDADE.FICHA_PREENCHIDA 

JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO ON QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = QUALIDADE.FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO 
JOIN qualidade.FICHA_VERIFICACAO_REVISAO ON qualidade.FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO
JOIN qualidade.FICHA_VERIFICACAO ON qualidade.FICHA_VERIFICACAO.ID_FICHA_VERIFICACAO = qualidade.FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO

WHERE qualidade.FICHA_VERIFICACAO_EMPREENDIMENTO.ID_EMPREENDIMENTO = 94 AND qualidade.FICHA_VERIFICACAO.COD_FICHA_VERIFICACAO = '11.201.5' AND QUALIDADE.FICHA_PREENCHIDA.ID_EMPREITEIRO = 3218 AND USERID_REVISAO = '37E59AD9-351C-4320-A162-B0EAC6B71C84'


--SELECT * FROM QUALIDADE.FICHA_PREENCHIDA 
--SELECT * FROM QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO
--SELECT * FROM EMPREENDIMENTO WHERE NOM_EMPREENDIMENTO LIKE '%JUNDIA%' AND ID_EMPRRENDIMENTO = 94
--SELECT * FROM[qualidade].[FICHA_VERIFICACAO]
--SELECT * FROM [qualidade].[FICHA_VERIFICACAO_REVISAO]

--SELECT * FROM EMPREITEIRO WHERE NOM_EMPREITEIRO LIKE '%DEBORA%' ID EMPREITEIRO = 3218

--SELECT * FROM [dbo].[aspnet_Users] WHERE UserName LIKE '%Jose.Rocha%'