  WITH USUARIO AS 
	(
	SELECT 
	PPESSOA.CODUSUARIO
	FROM CORPORE_RESIDENCIAL..PFUNC AS PFUNC (NOLOCK)
	INNER JOIN CORPORE_RESIDENCIAL..PPESSOA (NOLOCK) AS PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO
	WHERE PFUNC.CODSITUACAO <> 'D')  
  
  SELECT  
  OBRA.RM_CODCOLIGADA													AS COLIGADA_NO_RM, 
  OBRA.RM_CODCCUSTO														AS 'CENTRO DE CUSTO',
  OBRA.RM_NOME															AS OBRA, 
 PERFIL_USUARIO_OBRA.UserId,
  REPLACE(ASPNET_USERS.USERNAME, 'EMCCAMP\', '')						AS USUARIO,  
  STRING_AGG(PERFIL.NOM_PERFIL, ', ')									AS PERFIL_DO_CONTROLEMP
  

  
  FROM PERFIL_USUARIO_OBRA (NOLOCK)
  
  INNER JOIN OBRA						(NOLOCK)	ON OBRA.ID_OBRA = PERFIL_USUARIO_OBRA.ID_OBRA AND OBRA.RM_NOME NOT LIKE '%DESATIVADO%'
  INNER JOIN EMPREENDIMENTO				(NOLOCK)	ON EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO AND EMPREENDIMENTO.FLG_ATIVO = 1
  INNER JOIN ASPNET_USERS				(NOLOCK)	ON ASPNET_USERS.USERID = PERFIL_USUARIO_OBRA.USERID
  INNER JOIN PERFIL						(NOLOCK)	ON PERFIL.ID_PERFIL = PERFIL_USUARIO_OBRA.ID_PERFIL
  INNER JOIN USUARIO								ON USUARIO.CODUSUARIO = REPLACE(ASPNET_USERS.USERNAME, 'EMCCAMP\', '')

  WHERE REPLACE(ASPNET_USERS.USERNAME, 'EMCCAMP\', '')	= 'MATHEUS.FRANCA'

  GROUP BY 
  OBRA.RM_NOME,
  ASPNET_USERS.USERNAME,
  OBRA.RM_CODCCUSTO,
  OBRA.RM_CODCOLIGADA,PERFIL_USUARIO_OBRA.UserId


  SELECT * 
  FROM PERFIL

  SELECT * 
  FROM PERFIL_USUARIO_OBRA



