SELECT
DO.RM_CODCOLIGADA,
DO.RM_CODFILIAL,
DEMP.NOM_EMPREENDIMENTO,
ID_FICHA_PREENCHIDA AS LOCAL, 
DE.NOM_EMPREITEIRO,
DAT_PREENCHIMENTO, 
qfp.ID_FICHA_PREENCHIDA,
(CASE WHEN FLG_LIBERADA = 1 THEN 'SIM' ELSE 'NÃO' END) AS FICHA_LIBERADA
FROM qualidade.FICHA_PREENCHIDA AS QFP (NOLOCK)
JOIN dbo.EMPREITEIRO AS DE		(NOLOCK) ON DE.ID_EMPREITEIRO = QFP.ID_EMPREITEIRO
JOIN dbo.FUNCIONARIO AS DF		(NOLOCK) ON DF.ID_FUNCIONARIO = QFP.ID_FUNCIONARIO
JOIN dbo.OBRA AS DO				(NOLOCK) ON DO.ID_OBRA = QFP.ID_OBRA
JOIN dbo.EMPREENDIMENTO AS DEMP (NOLOCK) ON DEMP.ID_EMPREENDIMENTO = DO.ID_EMPREENDIMENTO
WHERE 
QFP.ID_FICHA_PREENCHIDA = 1590112

select FICHA_VERIFICACAO.COD_FICHA_VERIFICACAO, FICHA_PREENCHIDA.FLG_ATIVO,
FICHA_PREENCHIDA.* 
FROM DBCONTROLEMP.QUALIDADE.FICHA_PREENCHIDA AS FICHA_PREENCHIDA
LEFT JOIN DBCONTROLEMP.QUALIDADE.FICHA_PREENCHIDA_DETALHE AS FICHA_DETALHE								(NOLOCK) ON (FICHA_DETALHE.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)

LEFT JOIN DBCONTROLEMP.QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO AS FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.QUALIDADE.FICHA_VERIFICACAO_REVISAO AS FICHA_VERIFICACAO_REVISAO					(NOLOCK) ON (FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO)
LEFT JOIN DBCONTROLEMP.QUALIDADE.PERIODICIDADE AS PERIODICIDADE											(NOLOCK) ON (PERIODICIDADE.ID_PERIODICIDADE = FICHA_VERIFICACAO_REVISAO.ID_PERIODICIDADE)
LEFT JOIN DBCONTROLEMP.QUALIDADE.FICHA_VERIFICACAO AS FICHA_VERIFICACAO									(NOLOCK) ON (FICHA_VERIFICACAO.ID_FICHA_VERIFICACAO = FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO)
where FICHA_PREENCHIDA.ID_EMPREITEIRO = 4523



--select * from [dbo].[CONTRATO_ITEM_EMPREENDIMENTO]

