SELECT
DO.RM_CODCOLIGADA,
DO.RM_CODFILIAL,
DEMP.NOM_EMPREENDIMENTO,
ID_FICHA_PREENCHIDA AS LOCAL, 
DE.NOM_EMPREITEIRO,
DAT_PREENCHIMENTO, 
qfp.ID_FICHA_PREENCHIDA,
(CASE WHEN FLG_LIBERADA = 1 THEN 'SIM' ELSE 'NÃO' END) AS FICHA_LIBERADA
FROM qualidade.FICHA_PREENCHIDA AS QFP (NOLOCK)
JOIN dbo.EMPREITEIRO AS DE		(NOLOCK) ON DE.ID_EMPREITEIRO = QFP.ID_EMPREITEIRO
JOIN dbo.FUNCIONARIO AS DF		(NOLOCK) ON DF.ID_FUNCIONARIO = QFP.ID_FUNCIONARIO
JOIN dbo.OBRA AS DO				(NOLOCK) ON DO.ID_OBRA = QFP.ID_OBRA
JOIN dbo.EMPREENDIMENTO AS DEMP (NOLOCK) ON DEMP.ID_EMPREENDIMENTO = DO.ID_EMPREENDIMENTO
WHERE 
DE.NOM_EMPREITEIRO LIKE '%lmd%'


select * from [qualidade].[FICHA_PREENCHIDA] where ID_FICHA_PREENCHIDA = 753711
select 
* 
from [qualidade].[FICHA_PREENCHIDA_DETALHE] 
join [qualidade].[FICHA_VERIFICACAO_METODO] on [qualidade].[FICHA_VERIFICACAO_METODO].ID_FICHA_VERIFICACAO_METODO = [qualidade].[FICHA_PREENCHIDA_DETALHE].ID_FICHA_VERIFICACAO_METODO
where ID_FICHA_PREENCHIDA = 753711


select * from [dbo].[CONTRATO_ITEM_EMPREENDIMENTO]

