SELECT 
MED.ID_MEDICAO,
med.COD_MEDICAO, 
med.ID_CONTRATO,
CONTRATO.COD_CONTRATO,
EMPREITEIRO.NOM_EMPREITEIRO,
MED.DAT_CRIACAO,
DBO.TRAZ_USERNAME(MED.UserId_CRIACAO),
MED.DAT_CADASTRO,
dbo.TRAZ_USERNAME(med.UserId_CADASTRO),
med.DAT_INICIO,
med.DAT_FIM,
med.DAT_VENCIMENTO,
ETAPA.NOM_ETAPA,
MED.VLR_TOTAL,
MED.VLR_LIQUIDO,
CASE WHEN MED.EXCLUIDO = 1 THEN 'SIM' ELSE 'NAO' END AS EXCLUIDO,
MED.MOTIVO,
ITEM_EMP.CODIGO,
ITEM_EMP.NOM_ITEM,
ITEM_EMP.REVISAO,
ITEM_EMP.PRECO_UNITARIO,
ITEM_EMP.PRECO_ORCADO,
MED_ITEM_EMP.QTD_MEDIDA,
MED_ITEM_EMP.VLR_MEDIDO,
CLASSE.NOM_CLASSE,
CLASSE_OBRA.RM_CODTAREFA

FROM MEDICAO AS MED (NOLOCK) 

INNER JOIN [dbo].[MEDICAO_ITEM_EMPREENDIMENTO]	AS MED_ITEM_EMP		(NOLOCK) ON MED_ITEM_EMP.ID_MEDICAO = MED.ID_MEDICAO
INNER JOIN [DBO].[CONTRATO]						AS CONTRATO			(NOLOCK) ON CONTRATO.ID_CONTRATO = MED.ID_CONTRATO
INNER JOIN [DBO].[EMPREITEIRO]					AS EMPREITEIRO		(NOLOCK) ON EMPREITEIRO.ID_EMPREITEIRO = CONTRATO.ID_EMPREITEIRO
INNER JOIN [dbo].[OBRA]							AS OBRA				(NOLOCK) ON OBRA.ID_OBRA = MED.ID_OBRA
INNER JOIN [DBO].[EMPREENDIMENTO]				AS EMPRE			(NOLOCK) ON EMPRE.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO
INNER JOIN [dbo].[ITEM_EMPREENDIMENTO]			AS ITEM_EMP			(NOLOCK) ON ITEM_EMP.ID_EMPREENDIMENTO = EMPRE.ID_EMPREENDIMENTO AND ITEM_EMP.ID_ITEM_EMPREENDIMENTO = MED_ITEM_EMP.ID_ITEM_EMPREENDIMENTO
INNER JOIN [DBO].[ETAPA]						AS ETAPA			(NOLOCK) ON MED.ID_ETAPA = ETAPA.ID_ETAPA
INNER JOIN [DBO].[CLASSE]						AS CLASSE			(NOLOCK) ON CLASSE.ID_CLASSE = MED_ITEM_EMP.ID_CLASSE
INNER JOIN [DBO].[CLASSE_OBRA]					AS CLASSE_OBRA		(NOLOCK) ON CLASSE.ID_CLASSE = CLASSE_OBRA.ID_CLASSE AND CLASSE_OBRA.ID_OBRA = OBRA.ID_OBRA

WHERE MED.ID_MEDICAO = 95024
AND OBRA.ID_OBRA = 154
