/*VERIFICAR SE EXISTE FICHA LIBERADA E NÃO MEDIDA*/

/*Verificar se tem medição, se flg_liberada = 1 e se id_etapa = 4 */
SELECT
MEDICAO.ID_MEDICAO
,DBO.TRAZ_COD_FDV(FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA) AS FICHA_VERIFICAO
,FLG_LIBERADA
,MEDICAO_ITEM_EMPREENDIMENTO.QTD_MEDIDA
,MEDICAO.ID_MEDICAO
,MEDICAO.EXCLUIDO
,MEDICAO.ID_ETAPA
,MEDICAO.ID_OBRA
,OBRA.RM_NOME
,EMPREITEIRO.NOM_EMPREITEIRO
,CONTRATO.ID_CONTRATO
--,* 
FROM qualidade.FICHA_PREENCHIDA (NOLOCK)
LEFT JOIN qualidade.MEDICAO_FICHA_PREENCHIDA	(NOLOCK) ON (MEDICAO_FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)
LEFT JOIN MEDICAO_ITEM_EMPREENDIMENTO			(NOLOCK) ON (MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO_ITEM_EMPREENDIMENTO = MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN MEDICAO								(NOLOCK) ON (MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO)
LEFT JOIN OBRA									(NOLOCK) ON (FICHA_PREENCHIDA.ID_OBRA = OBRA.ID_OBRA)
LEFT JOIN EMPREITEIRO							(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = FICHA_PREENCHIDA.ID_EMPREITEIRO)
LEFT JOIN CONTRATO								(NOLOCK) ON (CONTRATO.ID_EMPREITEIRO = EMPREITEIRO.ID_EMPREITEIRO AND CONTRATO.ID_OBRA = OBRA.ID_OBRA)
LEFT JOIN ETAPA									(NOLOCK) ON (ETAPA.ID_ETAPA = MEDICAO.ID_ETAPA)


WHERE EMPREITEIRO.NOM_EMPREITEIRO  like '%moura%moria%'
AND FICHA_PREENCHIDA.ID_OBRA in (select ID_OBRA from OBRA where RM_NOME like '%cit%penha%')
AND (MEDICAO.EXCLUIDO = 0 or  MEDICAO.EXCLUIDO is null)
--and MEDICAO.ID_ETAPA is null 
AND FLG_LIBERADA = '0'
ORDER BY 1


/*VERUFICAR A ETAPA DA MEDIÇÃO, se id_etapa = 4*/
--SELECT ID_ETAPA,* FROM MEDICAO WHERE ID_MEDICAO IN (50439
--,49779
--,51122
--,51959
--,53972
--,55226
--,55813
--,56527
--,57315
--,58198
--,59097)

--SELECT * FROM ETAPA

