SELECT 
CONTRATO.ID_CONTRATO, 
CONTRATO.COD_CONTRATO,
[dbo].[OBJETO_CONTRATO].NOM_OBJETO_CONTRATO,
OBRA.RM_NOME,
empreendimento.NOM_EMPREENDIMENTO,
EMPREITEIRO.NOM_EMPREITEIRO,
CONTRATO.VLR_TOTAL,
CONTRATO.VLR_RETENCAO_CONTRATUAL,
--CONTRATO.ID_CONDICAO_PAGAMENTO,
[dbo].[TRAZ_USERNAME](CONTRATO.UserId_CRIACAO) AS 'USUARIO_CRIAÇÃO',
CONTRATO.DAT_CRIACAO,
ETAPA.NOM_ETAPA

FROM CONTRATO
INNER JOIN OBJETO_CONTRATO			ON OBJETO_CONTRATO.ID_OBJETO_CONTRATO = CONTRATO.ID_OBJETO_CONTRATO
INNER JOIN OBRA						ON CONTRATO.ID_OBRA = OBRA.ID_OBRA
INNER JOIN EMPREENDIMENTO			ON EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO
INNER JOIN EMPREITEIRO				ON CONTRATO.ID_EMPREITEIRO = EMPREITEIRO.ID_EMPREITEIRO
INNER JOIN ETAPA					ON ETAPA.ID_ETAPA = CONTRATO.ID_ETAPA

WHERE VLR_RETENCAO_CONTRATUAL = 0
and CONTRATO.ID_OBJETO_CONTRATO = 7
AND CONTRATO.DAT_CRIACAO > '20240101'

ORDER BY  CONTRATO.DAT_CRIACAO DESC


--select * 
--from [dbo].[OBJETO_CONTRATO]