DECLARE @ID_OBRA AS INT = 230; /* ID DA OBRA A SER DELETADA */ 

 /* VERIFICAR TABELAS COM VINCULO */
SELECT * 
FROM OBRA 
WHERE ID_OBRA = @ID_OBRA 

SELECT * 
FROM LOG_ALTERACAO_CCUSTO_OBRA 
WHERE ID_OBRA = @ID_OBRA

SELECT * 
FROM [DBO].[PERFIL_USUARIO_OBRA]
WHERE ID_OBRA = @ID_OBRA

SELECT *
FROM [DBO].[CLASSE_OBRA]
WHERE ID_OBRA = @ID_OBRA

/* UPDATE PRA DESVINCULAR DE OBRA PRINCIPAL */

UPDATE [DBCONTROLEMP].[DBO].OBRA
SET [FLG_OBRA_BASE] = 0
WHERE ID_OBRA = @ID_OBRA;

/*DELETE DAS PRINCIPAIS TABELAS VINCULADAS */

BEGIN TRAN
DELETE FROM [DBO].[PERFIL_USUARIO_OBRA]
WHERE ID_OBRA = @ID_OBRA;

BEGIN TRAN
DELETE FROM LOG_ALTERACAO_CCUSTO_OBRA 
WHERE ID_OBRA = @ID_OBRA

BEGIN TRAN
DELETE FROM [DBO].[CLASSE_OBRA]
WHERE ID_OBRA = @ID_OBRA

--COMMIT
--COMMIT
--COMMIT


/* TABELAS QUE PODEM ESTAR VINCULADAS EM 30/04/2025 */

/*
[dbo].[CONTRATO]
[dbo].[FGTS]
[qualidade].[FICHA_PREENCHIDA]
[qualidade].[FICHA_VERIFICACAO_RESERVA_HISTORICO]
[qualidade].[FICHA_VERIFICACAO_RESERVA]
[dbo].[ITEM_EMPREENDIMENTO_OBRA]
[qualidade].[LOCAL_BLOCO]
[qualidade].[LOCAL_CONDOMINIO]
[dbo].[LOG_ALTERACAO_CCUSTO_OBRA]
[qualidade].[LOG_EXCLUSAO_FICHA_PREENCHIDA]
[RMO].[MATERIAIS_A_DESCONTAR]
[dbo].[MEDICAO]
[dbo].[OBRA_EMPREITEIRO_TAREFA]
[dbo].[PERFIL_USUARIO_OBRA]
[dbo].[PRODUCAO_OBRA_ITEM_EMPREENDIMENTO]
[RMO].[REQUISICAO]
[RMO].[USUARIO_GRUPO_MATERIAIS]
[RMO].[USUARIO_KIT]
[RMO].[USUARIO_KIT_HISTORICO]
[RMO].[KIT_OBRA]
[fgts].[CHECKLISTS]
[questionario].[AVALIACOES_EMPREITEIROS]
[dbo].[SOLICITACAO_QUANTIDADE_ITEM_EMPREENDIMENTO]
[servicos].[AGENDAMENTOS]
[servicos].[FRETES]
[dbo].[ADIANTAMENTOS]

*/
