BEGIN TRAN
INSERT INTO PERFIL_USUARIO_OBRA (
    ID_OBRA,
    UserId,
    ID_PERFIL,
    LOGIN_RM_ENGENHEIRO
)
SELECT 
    o.ID_OBRA,
    '499AF34D-99E3-4044-B2C5-6B69FE4B114D' AS UserId,
    p.ID_PERFIL,
    CASE 
        WHEN p.ID_PERFIL = 3 THEN 'MATHEUS.FRANCA'
        ELSE NULL
    END AS LOGIN_RM_ENGENHEIRO
FROM OBRA o
INNER JOIN EMPREENDIMENTO e ON e.ID_EMPREENDIMENTO = o.ID_EMPREENDIMENTO
CROSS JOIN (
    SELECT 3 AS ID_PERFIL
    UNION ALL
    SELECT 6
    UNION ALL
    SELECT 7
    UNION ALL
    SELECT 8
) p
WHERE e.FLG_ATIVO = 1
AND NOT EXISTS (
    SELECT 1
    FROM PERFIL_USUARIO_OBRA pu
    WHERE pu.ID_OBRA = o.ID_OBRA
      AND pu.UserId = '499AF34D-99E3-4044-B2C5-6B69FE4B114D'
      AND pu.ID_PERFIL = p.ID_PERFIL
);
--rollback
--commit

--SELECT * 
--FROM PERFIL_USUARIO_OBRA
--WHERE USERID = '499AF34D-99E3-4044-B2C5-6B69FE4B114D'
--ORDER BY 1