SELECT 
OBRA.ID_OBRA, 
OBRA.RM_NOME 
FROM OBRA 
WHERE ID_OBRA IN (SELECT DISTINCT ID_OBRA FROM QUALIDADE.FICHA_PREENCHIDA) AND ID_OBRA IN (
	SELECT ID_OBRA FROM PERFIL_USUARIO_OBRA
	INNER JOIN ASPNET_USERS (NOLOCK) ON (ASPNET_USERS.USERID = PERFIL_USUARIO_OBRA.USERID)
	WHERE 
	ASPNET_USERS.USERNAME = @USUARIO_LOGADO 
	AND ID_PERFIL IN (10,13,4))
	ORDER BY OBRA.RM_NOME