  /* COLIGADA 1 */ 
  
  SELECT 
        TMOV.CODCOLIGADA,
		TMOV.CODFILIAL,
        TMOV.IDMOV,
		(CASE WHEN TMOVRELAC.IDMOVORIGEM IS NOT NULL THEN 'SIM' ELSE 'NAO' END) AS 'RECEBIDO?',
		ISNULL(TMOVRELAC.IDMOVORIGEM,0) AS 'ID_MOV_RECEBIO',
		ISNULL(TMOV2.CODTMV,'NÃO RECEBIDO') AS 'CODIGO DO MOVIMENTO RECEBIDO',
		TMOV.CODTMV,
        TITMMOVCOMPL.ID_REQUISICAO_RMO,
		REC_MAT.ID_REQUISICAO_MATERIAL,
		TITMMOV.IDPRD,
		TPRD.NOMEFANTASIA,
		CONVERT(DECIMAL(10,2),TITMMOV.QUANTIDADE) AS 'QUANTIDADE INTEGRADA',
		CONVERT(DECIMAL(10,2),REC_MAT.QUANTIDADE_ENTREGUE) AS 'QUANTIDADE PEDIDA'


    FROM TMOV (NOLOCK) 
    INNER JOIN TITMMOV			(NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV 
    INNER JOIN TITMMOVCOMPL		(NOLOCK) ON TITMMOV.CODCOLIGADA = TITMMOVCOMPL.CODCOLIGADA AND TITMMOV.IDMOV = TITMMOVCOMPL.IDMOV AND TITMMOV.NSEQITMMOV = TITMMOVCOMPL.NSEQITMMOV
	LEFT JOIN TMOVRELAC			(NOLOCK) ON TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO
	LEFT JOIN TMOV AS TMOV2	(NOLOCK) ON TMOV2.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM AND TMOV2.IDMOV = TMOVRELAC.IDMOVORIGEM
	INNER JOIN TPRD				(NOLOCK) ON TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TPRD.IDPRD = TITMMOV.IDPRD
	INNER JOIN DBCONTROLEMP.RMO.REQUISICAO_MATERIAL REC_MAT (NOLOCK) ON  REC_MAT.RM_CODCOLIGADA = TITMMOV.CODCOLIGADA AND  REC_MAT.RM_CODFILIAL = TITMMOV.CODFILIAL AND REC_MAT.RM_IDMOV = TITMMOV.IDMOV AND REC_MAT.RM_IDPRD = TITMMOV.IDPRD AND REC_MAT.QUANTIDADE_SOLICITADA = TITMMOV.QUANTIDADE
	
	where TMOV.IDMOV IN (24223, 25195, 25750)
	AND TMOV.CODCOLIGADA = 59

	GROUP BY 
	    TMOV.CODCOLIGADA,
		TMOV.CODFILIAL,
        TMOV.IDMOV,
		TMOVRELAC.IDMOVORIGEM,
		TMOV.CODTMV,
        TITMMOVCOMPL.ID_REQUISICAO_RMO,
		REC_MAT.ID_REQUISICAO_MATERIAL,
		TITMMOV.IDPRD,
		TPRD.NOMEFANTASIA,
		TITMMOV.QUANTIDADE,
		REC_MAT.QUANTIDADE_ENTREGUE,
		TMOV2.CODTMV


		HAVING TITMMOV.QUANTIDADE <> REC_MAT.QUANTIDADE_ENTREGUE

