/*DECLARE @OBRA AS INT = 212,
		@FDV AS INT = 13757,
		@DATA_INI AS DATE = '20200101',
		@DATA_FINAL AS DATE = '20250603';
		*/
SELECT 
	(
		CASE 
			WHEN G.SIGLA_EMP = 'EXCECAO' THEN 'EXCECAO'
			WHEN G.EXCECAO_PREENCHIDA <> 'NAO' THEN 'EXCECAO CADASTRADA'
			WHEN G.STATUS_VERIFICACAO = 'NÃO CONFORME' THEN ('NÃO CONFORME' + ' - ' + G.SIGLA_EMP)
			WHEN G.STATUS_VERIFICACAO = 'CONFORME APÓS REINSPEÇÃO' THEN ('CONFORME APÓS REINSPEÇÃO' + ' - ' + G.SIGLA_EMP)
			WHEN G.STATUS_VERIFICACAO = 'NÃO SE APLICA' THEN 'NÃO SE APLICA'
			WHEN G.STATUS_VERIFICACAO = 'CONFORME' THEN  ('CONFORME' + ' - ' + G.SIGLA_EMP)
			ELSE 'FICHA NÃO PREENCHIDA'
			end) 'CASE TEST',
	*

FROM(

SELECT 
PREENCHIMENTO.STATUS_VERIFICACAO,
LOCAL_BLOCO.NOM_LOCAL_BLOCO,
LOCAL_BLOCO.ID_LOCAL_BLOCO,
OBRA.RM_NOME AS NOME_OBRA,
CAST(QUALIDADE.LOCAL_PAVIMENTO.NUMERO AS INT) AS 'ANDAR',
LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
CAST(RIGHT(QUALIDADE.LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,2) AS INT) AS 'CONT_AP',
LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
PREENCHIMENTO.FLG_BLOQUEIA_PAGAMENTO,
PREENCHIMENTO.FLG_LIBERADA,
PREENCHIMENTO.ID_FICHA_VERIFICACAO_RESPOSTA,
PREENCHIMENTO.SIGLA_EMP as sigla1,
ISNULL (PREENCHIMENTO.SIGLA_EMP,
								(SELECT 
									'EXCECAO'
									FROM QUALIDADE.LOCAL_APARTAMENTO_EXCECAO (NOLOCK)
									WHERE	QUALIDADE.LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO = LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO
									AND		QUALIDADE.LOCAL_APARTAMENTO_EXCECAO.ID_FICHA_VERIFICACAO = @FDV)
								) AS SIGLA_EMP,


(SELECT 
MAX (MEDICAO.ID_ETAPA) AS ETAPA_MEDICAO
FROM QUALIDADE.FICHA_PREENCHIDA (NOLOCK)
LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_REVISAO			(NOLOCK) ON (FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO)
LEFT JOIN QUALIDADE.MEDICAO_FICHA_PREENCHIDA			(NOLOCK) ON (MEDICAO_FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)
LEFT JOIN MEDICAO_ITEM_EMPREENDIMENTO					(NOLOCK) ON (MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO_ITEM_EMPREENDIMENTO = MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN MEDICAO										(NOLOCK) ON (MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO)

WHERE	FICHA_PREENCHIDA.FLG_LIBERADA = 1
AND		FICHA_PREENCHIDA.ID_LOCAL_APARTAMENTO = LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO
AND		FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO = @FDV
AND		MEDICAO.EXCLUIDO = 0
/*CONDICAO COLOCADA A PEDIDO DO CADU PARA NÃO TRAZER MEDIÇÕES NEGATIVAS */
GROUP BY MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA
HAVING 	SUM (MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA) > 0) AS ETAPA,

ISNULL(PREENCHIMENTO.EXCECAO_PREENCHIDA,'NAO') AS EXCECAO_PREENCHIDA

FROM QUALIDADE.LOCAL_BLOCO (NOLOCK)

LEFT JOIN [QUALIDADE].[LOCAL_CONDOMINIO] AS CONDOMINIO  (NOLOCK) ON (CONDOMINIO.ID_LOCAL_CONDOMINIO = QUALIDADE.LOCAL_BLOCO.ID_LOCAL_CONDOMINIO)
LEFT JOIN OBRA											(NOLOCK) ON (OBRA.ID_OBRA = LOCAL_BLOCO.ID_OBRA)
LEFT JOIN QUALIDADE.LOCAL_PAVIMENTO						(NOLOCK) ON (LOCAL_PAVIMENTO.ID_LOCAL_BLOCO = LOCAL_BLOCO.ID_LOCAL_BLOCO)
LEFT JOIN QUALIDADE.LOCAL_APARTAMENTO					(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_PAVIMENTO = LOCAL_PAVIMENTO.ID_LOCAL_PAVIMENTO)
LEFT JOIN (	
			SELECT 
				FVR.ID_FICHA_VERIFICACAO_RESPOSTA,
				LOCAL_BLOCO.NOM_LOCAL_BLOCO,
				LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
				LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
				CASE 
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1  -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2  -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3  -- NÃO SE APLICA
							ELSE 999
						END
					) = 1 THEN 'NÃO CONFORME'
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1 -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2 -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3 -- NÃO SE APLICA
							ELSE 999
						END
					) = 2 THEN 'CONFORME APÓS REINSPEÇÃO'
					WHEN MIN(
						CASE 
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 3 THEN 1 -- NÃO CONFORME
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 5 THEN 2 -- CONFORME APÓS REINSPEÇÃO
							WHEN FVR.ID_FICHA_VERIFICACAO_RESPOSTA = 4 THEN 3 -- NÃO SE APLICA
							ELSE 999
						END
					) = 3 THEN 'NÃO SE APLICA'
					ELSE 'CONFORME'
				END AS STATUS_VERIFICACAO,
							(CASE 
							 
							 WHEN FP.ID_LOCAL_APARTAMENTO IN (
																				SELECT 
																				LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO
																				FROM QUALIDADE.LOCAL_APARTAMENTO_EXCECAO	(NOLOCK)

																				WHERE	LOCAL_APARTAMENTO_EXCECAO.ID_LOCA_APARTAMENTO = FP.ID_LOCAL_APARTAMENTO
																				AND		LOCAL_APARTAMENTO_EXCECAO.ID_FICHA_VERIFICACAO = fv.ID_FICHA_VERIFICACAO
																			)

							  THEN 'SIM' ELSE 'NAO' END

						) AS EXCECAO_PREENCHIDA,
						ISNULL (EMPREITEIRO.SIGLA_EMPREITEIRO, LEFT (EMPREITEIRO.NOM_EMPREITEIRO,5))AS SIGLA_EMP,
						FLG_BLOQUEIA_PAGAMENTO,
						FLG_LIBERADA

						FROM QUALIDADE.FICHA_PREENCHIDA FP							(NOLOCK)
						LEFT JOIN QUALIDADE.FICHA_PREENCHIDA_DETALHE FPD			(NOLOCK) ON (FP.ID_FICHA_PREENCHIDA = FPD.ID_FICHA_PREENCHIDA)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_RESPOSTA FVR			(NOLOCK) ON (FVR.ID_FICHA_VERIFICACAO_RESPOSTA = FPD.ID_FICHA_VERIFICACAO_RESPOSTA)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_METODO FVM			(NOLOCK) ON (FVM.ID_FICHA_VERIFICACAO_METODO = FPD.ID_FICHA_VERIFICACAO_METODO)
						LEFT JOIN QUALIDADE.METODO M								(NOLOCK) ON (FVM.ID_METODO = M.ID_METODO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_EMPREENDIMENTO FVE	(NOLOCK) ON (FVE.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FP.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO_REVISAO FVRV			(NOLOCK) ON (FVRV.ID_FICHA_VERIFICACAO_REVISAO = FVE.ID_FICHA_VERIFICACAO_REVISAO)
						LEFT JOIN QUALIDADE.FICHA_VERIFICACAO FV					(NOLOCK) ON (FV.ID_FICHA_VERIFICACAO = FVRV.ID_FICHA_VERIFICACAO)
						LEFT JOIN OBRA O											(NOLOCK) ON (O.ID_OBRA = FP.ID_OBRA)
						LEFT JOIN QUALIDADE.LOCAL_BLOCO LOCAL_BLOCO					(NOLOCK) ON (LOCAL_BLOCO.ID_LOCAL_BLOCO = FP.ID_LOCAL_BLOCO)
						LEFT JOIN QUALIDADE.LOCAL_APARTAMENTO LOCAL_APARTAMENTO		(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO = FP.ID_LOCAL_APARTAMENTO)
						LEFT JOIN EMPREITEIRO										(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = FP.ID_EMPREITEIRO)
						
						WHERE 
							FVRV.ID_FICHA_VERIFICACAO = @FDV
							AND		FP.ID_OBRA = @OBRA
							AND		FP.DAT_PREENCHIMENTO BETWEEN @DATA_INI AND @DATA_FINAL
						
						GROUP BY 
							FVR.ID_FICHA_VERIFICACAO_RESPOSTA,
							LOCAL_BLOCO.NOM_LOCAL_BLOCO,
							LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO,
							LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
							FP.ID_LOCAL_APARTAMENTO,
							FV.ID_FICHA_VERIFICACAO,
							EMPREITEIRO.NOM_EMPREITEIRO,
							EMPREITEIRO.SIGLA_EMPREITEIRO,
							FP.FLG_BLOQUEIA_PAGAMENTO,
							FP.FLG_LIBERADA

			) AS PREENCHIMENTO ON (PREENCHIMENTO.ID_LOCAL_APARTAMENTO = QUALIDADE.LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO)

WHERE	LOCAL_BLOCO.ID_OBRA = @OBRA
AND LOCAL_BLOCO.ID_LOCAL_BLOCO = @BLOCO
AND CONDOMINIO.ID_LOCAL_CONDOMINIO = @CONDOMINIO
) AS G


ORDER BY 
G.NOM_LOCAL_APARTAMENTO,
CAST(G.ANDAR AS INT),
CAST(G.CONT_AP AS INT)
