--COMMIT
--ROLLBACK
BEGIN TRAN ;

WITH MOVIMENTO AS (
	SELECT 
		TMOV.CODCOLIGADA,
		TMOV.IDMOV,
		TITMMOVCOMPL.ID_REQUISICAO_RMO,
		TITMMOV.IDPRJ,
		TITMMOV.IDTRF,
		TMOV.RECCREATEDON
	FROM CORPORE_RESIDENCIAL..TMOV					AS TMOV					(NOLOCK)
	INNER JOIN CORPORE_RESIDENCIAL..TITMMOV			AS TITMMOV				(NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
	INNER JOIN CORPORE_RESIDENCIAL..TITMMOVCOMPL	AS TITMMOVCOMPL			(NOLOCK) ON TITMMOVCOMPL.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TITMMOVCOMPL.IDMOV = TITMMOV.IDMOV
),
DADOS_CORRECAO AS (
	SELECT  
		TITMMOV.CODCOLIGADA,
		TITMMOV.IDMOV,
		TITMMOV.IDPRD,
		TITMMOV.NSEQITMMOV,
		REC_MAT.RM_IDTRF
	FROM [RMO].[REQUISICAO]							AS REC		(NOLOCK)
	INNER JOIN [RMO].[REQUISICAO_MATERIAL]			AS REC_MAT	(NOLOCK) ON REC_MAT.ID_REQUISICAO = REC.ID_REQUISICAO
	INNER JOIN MOVIMENTO												 ON REC_MAT.RM_IDMOV = MOVIMENTO.IDMOV AND REC_MAT.RM_CODCOLIGADA = MOVIMENTO.CODCOLIGADA AND MOVIMENTO.ID_REQUISICAO_RMO = REC_MAT.ID_REQUISICAO
	INNER JOIN CORPORE_RESIDENCIAL..TITMMOV	AS TITMMOV			(NOLOCK) ON TITMMOV.CODCOLIGADA = REC_MAT.RM_CODCOLIGADA AND TITMMOV.IDMOV = REC_MAT.RM_IDMOV AND TITMMOV.IDPRJ = REC_MAT.RM_IDPRJ AND TITMMOV.IDPRD = REC_MAT.RM_IDPRD
	WHERE 
		MOVIMENTO.IDTRF <> REC_MAT.RM_IDTRF
		AND MOVIMENTO.RECCREATEDON > '2025-05-01 00:30:00.000'
)

UPDATE TITMMOV
SET IDTRF = DADOS_CORRECAO.RM_IDTRF
FROM CORPORE_RESIDENCIAL..TITMMOV AS TITMMOV
INNER JOIN DADOS_CORRECAO ON TITMMOV.CODCOLIGADA = DADOS_CORRECAO.CODCOLIGADA AND TITMMOV.IDMOV = DADOS_CORRECAO.IDMOV AND TITMMOV.IDPRD = DADOS_CORRECAO.IDPRD AND TITMMOV.NSEQITMMOV = DADOS_CORRECAO.NSEQITMMOV;
