WITH TAREFA AS (
		SELECT 
		CODCOLIGADA, 
		IDPRJ, 
		IDTRF, 
		CODTRF
		FROM CORPORE_RESIDENCIAL..MTRF (NOLOCK)),
		MOVIMENTO AS (
		SELECT 
		TMOV.CODCOLIGADA,
		TMOV.IDMOV,
		TMOVCOMPL.ID_REQUISICAO_RMO,
		TITMMOV.IDPRJ,
		TITMMOV.IDTRF
		FROM CORPORE_RESIDENCIAL..TMOV				AS TMOV			(NOLOCK)
		INNER JOIN CORPORE_RESIDENCIAL..TMOVCOMPL	AS TMOVCOMPL	(NOLOCK) ON TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA AND TMOV.IDMOV = TMOVCOMPL.IDMOV
		INNER JOIN CORPORE_RESIDENCIAL..TITMMOV		AS TITMMOV		(NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV)


SELECT  REC.ID_REQUISICAO, REC_MAT.RM_IDPRJ, REC.* 
FROM [RMO].[REQUISICAO] AS REC
INNER JOIN [RMO].[REQUISICAO_MATERIAL] AS REC_MAT ON REC_MAT.ID_REQUISICAO = REC.ID_REQUISICAO
INNER JOIN [dbo].[CLASSE_OBRA] AS CLASSE ON CLASSE.ID_CLASSE = REC_MAT.ID_CLASSE AND REC.ID_OBRA = CLASSE.ID_OBRA
INNER JOIN 

/*WHERE REC.ID_OBRA = 201
AND REC.ID_REQUISICAO = 873980*/


