SELECT 

EMPREITEIRO.ID_EMPREITEIRO,
EMPREENDIMENTO.NOM_EMPREENDIMENTO,
OBRA.RM_NOME,
FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA,
ficha_verificacao.ID_FICHA_VERIFICACAO,
FICHA_VERIFICACAO.COD_FICHA_VERIFICACAO + ' - ' + FICHA_VERIFICACAO.NOM_FICHA_VERIFICACAO AS FDV,
PERIODICIDADE.NOM_PERIODICIDADE,
INSTRUCAO_SERVICO.COD_INSTRUCAO_SERVICO + ' - ' + INSTRUCAO_SERVICO.NOM_INSTRUCAO_SERVICO AS IDS,
CONVERT (VARCHAR,GRUPO_ITEM.ID_GRUPO_ITEM) + ' - ' + GRUPO_ITEM.NOM_GRUPO_ITEM AS GRUPO_ITEM,
LOCAL_BLOCO.ID_LOCAL_BLOCO,
LOCAL_BLOCO.NOM_LOCAL_BLOCO,
LOCAL_PAVIMENTO.NUMERO AS PVTO, 
LOCAL_APARTAMENTO.NOM_LOCAL_APARTAMENTO,
LOCAL_ESCADA.NUMERO AS ESCADA,
LOCAL_HALL.NUMERO AS HALL,
FICHA_PREENCHIDA.NOM_LOCAL,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_PREENCHIMENTO,103) AS DAT_PREENCHIMENTO,
FICHA_PREENCHIDA.DAT_PREENCHIMENTO AS HORA,
SUBSTRING (aspnet_Users.UserName,9,100) AS UserName,(CASE	WHEN MEDICAO.ID_MEDICAO IS NOT NULL AND MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA < 0 THEN 'NÃO'
		WHEN FICHA_PREENCHIDA.FLG_LIBERADA = 1 THEN 'SIM'
		ELSE 'NÃO'
END) AS LIBERADA,
EMPREITEIRO.NOM_EMPREITEIRO,
FUNCIONARIO.NOM_FUNCIONARIO,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_INICIO_SERVICO,103) AS DAT_INICIO_SERVICO,
CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_FIM_SERVICO,103) AS DAT_FIM_SERVICO,
DATEDIFF(DAY,DAT_FIM_SERVICO,FICHA_PREENCHIDA.DAT_LIBERACAO)  AS DESEMPENHO_POR_USUARIO,

CONVERT (VARCHAR,FICHA_PREENCHIDA.DAT_LIBERACAO,103) AS DAT_LIBERACAO,

(SELECT  MAX (FPDH.DAT_HISTORICO)
FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA) AS DATA_ULTIMO_METODO,


MEDICAO.COD_MEDICAO AS MEDICAO,
ETAPA.NOM_ETAPA AS ETAPA,
MEDICAO.EXCLUIDO,

CONVERT (VARCHAR,MEDICAO.DAT_CRIACAO,103) AS DAT_CRIACAO,
CONVERT (VARCHAR,MEDICAO.DAT_VENCIMENTO,103) AS DAT_VENCIMENTO,

(SELECT TOP 1 CONVERT (VARCHAR,DATA_EXPORTACAO,103) FROM NOTA_FISCAL WHERE NOTA_FISCAL.FLAG_CANCELADO = 0 AND NOTA_FISCAL.ID_MEDICAO = MEDICAO.ID_MEDICAO) AS DATA_ENVIO_RM,

CONVERT (VARCHAR,(SELECT MAX (DAT_HISTORICO) FROM MEDICAO_HISTORICO WHERE MEDICAO.ID_MEDICAO = MEDICAO_HISTORICO.ID_MEDICAO AND MEDICAO_HISTORICO.ID_ETAPA = 3),103) AS DATA_APRV_ENGE,



MEDICAO_FICHA_PREENCHIDA.QTD_MEDIDA,

ITEM_EMPREENDIMENTO.CODIGO + ' - ' + ITEM_EMPREENDIMENTO.NOM_ITEM AS ITEM_EMPREENDIMENTO,
CONTRATO.COD_CONTRATO,

OBJETO_CONTRATO_ITEM.ID_OBJETO_CONTRATO,
OBJETO_CONTRATO_ITEM.NOM_OBJETO_CONTRATO,

/* RETIRADO DEVIDO A LENTIDAO 
(SELECT MIN (DAT_HISTORICO) FROM ITEM_EMPREENDIMENTO_HISTORICO WHERE ID_ETAPA = 4 AND ID_ITEM_EMPREENDIMENTO IN (
SELECT ITM_INTERNO.ID_ITEM_EMPREENDIMENTO FROM ITEM_EMPREENDIMENTO AS ITM_INTERNO WHERE ITM_INTERNO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO AND ITM_INTERNO.CODIGO = ITEM_EMPREENDIMENTO.CODIGO)) AS APROVACAO_ITEM_CONTROLE,

*/

(SELECT MAX (IE.PRECO_UNITARIO) * FICHA_VERIFICACAO_EMPREENDIMENTO.QUANTIDADE_MEDICAO

FROM QUALIDADE.MEDICAO_FICHA_PREENCHIDA AS MFP_INTERNO
LEFT JOIN MEDICAO_ITEM_EMPREENDIMENTO AS MIE	(NOLOCK) ON (MIE.ID_MEDICAO_ITEM_EMPREENDIMENTO = MFP_INTERNO.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN MEDICAO AS M								(NOLOCK) ON (M.ID_MEDICAO = MIE.ID_MEDICAO)
LEFT JOIN ITEM_EMPREENDIMENTO AS IE				(NOLOCK) ON (IE.ID_ITEM_EMPREENDIMENTO = MIE.ID_ITEM_EMPREENDIMENTO)
WHERE	MFP_INTERNO.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA
AND		M.EXCLUIDO = 0
) AS PRECO_ITEN_MEDICAO,

/* TRAZ O USUARIO QUE PREENCHEU O PRIMEIRO METODO DA FICHA ATRAVÉS DA FUNÇÃO ABAIXO, PASSANDO O MENOR ID DE HISTÓRICO, 
FOI FEITO DESTA FORMA POIS TRAZENDO DIRETAMENTE NO RELATORIO ESTAVA MUITO LENTO */

dbo.USUARIO_ABERTURA_FICHA_PREENCHIDA((SELECT MIN (FPDH.ID_FICHA_PREENCHIDA_DETALHE_HISTORICO) 
FROM qualidade.FICHA_PREENCHIDA_DETALHE_HISTORICO AS FPDH
INNER JOIN qualidade.FICHA_PREENCHIDA_DETALHE AS FPD		(NOLOCK) ON (FPD.ID_FICHA_PREENCHIDA_DETALHE = FPDH.ID_FICHA_PREENCHIDA_DETALHE)
WHERE	FPD.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA)) AS USUARIO_PRIMEIRO_PREENCHIMENTO,

/* TRAZ O PRECO UNITARIO DA ULTIMA REVISAO DO ITEM */
(SELECT TOP 1 ITEM_ULTIMA_REVISAO.PRECO_UNITARIO FROM ITEM_EMPREENDIMENTO AS ITEM_ULTIMA_REVISAO  WHERE ITEM_ULTIMA_REVISAO.CODIGO = ITEM_EMPREENDIMENTO.CODIGO AND ITEM_ULTIMA_REVISAO.ID_EMPREENDIMENTO = ITEM_EMPREENDIMENTO.ID_EMPREENDIMENTO ORDER BY ITEM_ULTIMA_REVISAO.ID_ITEM_EMPREENDIMENTO DESC) AS PRC_ULTIMA_REVISAO




FROM DBCONTROLEMP.qualidade.FICHA_PREENCHIDA AS FICHA_PREENCHIDA

LEFT JOIN DBCONTROLEMP.DBO.OBRA AS OBRA																	(NOLOCK) ON (OBRA.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA)
LEFT JOIN DBCONTROLEMP.DBO.EMPREENDIMENTO AS EMPREENDIMENTO												(NOLOCK) ON (EMPREENDIMENTO.ID_EMPREENDIMENTO = OBRA.ID_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_BLOCO AS LOCAL_BLOCO												(NOLOCK) ON (LOCAL_BLOCO.ID_LOCAL_BLOCO = FICHA_PREENCHIDA.ID_LOCAL_BLOCO and LOCAL_BLOCO.ID_OBRA = FICHA_PREENCHIDA.ID_OBRA)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_PAVIMENTO AS LOCAL_PAVIMENTO 									(NOLOCK) ON (LOCAL_PAVIMENTO.ID_LOCAL_PAVIMENTO = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO and LOCAL_PAVIMENTO.ID_LOCAL_BLOCO  = FICHA_PREENCHIDA.ID_LOCAL_BLOCO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_APARTAMENTO AS LOCAL_APARTAMENTO									(NOLOCK) ON (LOCAL_APARTAMENTO.ID_LOCAL_APARTAMENTO = FICHA_PREENCHIDA.ID_LOCAL_APARTAMENTO and LOCAL_APARTAMENTO.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_ESCADA AS LOCAL_ESCADA											(NOLOCK) ON (LOCAL_ESCADA.ID_LOCAL_ESCADA = FICHA_PREENCHIDA.ID_LOCAL_ESCADA and LOCAL_ESCADA.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.LOCAL_HALL	AS LOCAL_HALL												(NOLOCK) ON (LOCAL_HALL.ID_LOCAL_HALL = FICHA_PREENCHIDA.ID_LOCAL_HALL and LOCAL_HALL.ID_LOCAL_PAVIMENTO  = FICHA_PREENCHIDA.ID_LOCAL_PAVIMENTO)
LEFT JOIN DBCONTROLEMP.DBO.aspnet_Users	AS aspnet_Users													(NOLOCK) ON (aspnet_Users.UserId = FICHA_PREENCHIDA.UserId)
LEFT JOIN DBCONTROLEMP.DBO.EMPREITEIRO AS EMPREITEIRO													(NOLOCK) ON (EMPREITEIRO.ID_EMPREITEIRO = FICHA_PREENCHIDA.ID_EMPREITEIRO) 
LEFT JOIN DBCONTROLEMP.DBO.FUNCIONARIO AS FUNCIONARIO													(NOLOCK) ON (FUNCIONARIO.ID_FUNCIONARIO = FICHA_PREENCHIDA.ID_FUNCIONARIO)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO_EMPREENDIMENTO AS FICHA_VERIFICACAO_EMPREENDIMENTO	(NOLOCK) ON (FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_EMPREENDIMENTO = FICHA_PREENCHIDA.ID_FICHA_VERIFICACAO_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO_REVISAO AS FICHA_VERIFICACAO_REVISAO					(NOLOCK) ON (FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO_REVISAO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_FICHA_VERIFICACAO_REVISAO)
LEFT JOIN DBCONTROLEMP.qualidade.PERIODICIDADE AS PERIODICIDADE											(NOLOCK) ON (PERIODICIDADE.ID_PERIODICIDADE = FICHA_VERIFICACAO_REVISAO.ID_PERIODICIDADE)
LEFT JOIN DBCONTROLEMP.qualidade.FICHA_VERIFICACAO AS FICHA_VERIFICACAO									(NOLOCK) ON (FICHA_VERIFICACAO.ID_FICHA_VERIFICACAO = FICHA_VERIFICACAO_REVISAO.ID_FICHA_VERIFICACAO)
LEFT JOIN DBCONTROLEMP.qualidade.INSTRUCAO_SERVICO AS INSTRUCAO_SERVICO									(NOLOCK) ON (FICHA_VERIFICACAO.ID_INSTRUCAO_SERVICO = INSTRUCAO_SERVICO.ID_INSTRUCAO_SERVICO)
LEFT JOIN DBCONTROLEMP.dbo.ITEM_EMPREENDIMENTO AS ITEM_EMPREENDIMENTO									(NOLOCK) ON (ITEM_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO = FICHA_VERIFICACAO_EMPREENDIMENTO.ID_ITEM_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.dbo.OBJETO_CONTRATO AS OBJETO_CONTRATO_ITEM										(NOLOCK) ON (OBJETO_CONTRATO_ITEM.ID_OBJETO_CONTRATO = ITEM_EMPREENDIMENTO.ID_OBJETO_CONTRATO)
LEFT JOIN DBCONTROLEMP.dbo.GRUPO_ITEM AS GRUPO_ITEM														(NOLOCK) ON (ITEM_EMPREENDIMENTO.ID_GRUPO_ITEM = GRUPO_ITEM.ID_GRUPO_ITEM)
LEFT JOIN DBCONTROLEMP.qualidade.MEDICAO_FICHA_PREENCHIDA as MEDICAO_FICHA_PREENCHIDA					(NOLOCK) ON (MEDICAO_FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA = FICHA_PREENCHIDA.ID_FICHA_PREENCHIDA AND MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_FICHA_PREENCHIDA NOT IN (
																																																																			SELECT MFP.ID_MEDICAO_FICHA_PREENCHIDA FROM qualidade.MEDICAO_FICHA_PREENCHIDA AS MFP
																																																																			INNER JOIN MEDICAO_ITEM_EMPREENDIMENTO AS MIE				(NOLOCK) ON (MIE.ID_MEDICAO_ITEM_EMPREENDIMENTO = MFP.ID_MEDICAO_ITEM_EMPREENDIMENTO)
																																																																			INNER JOIN MEDICAO AS M															(NOLOCK) ON (M.ID_MEDICAO = MIE.ID_MEDICAO)
																																																																			WHERE	M.EXCLUIDO = 1
																																																																		  )) /*ELIMINA MEDICAOES EXCLUIDAS */
LEFT JOIN DBCONTROLEMP.dbo.MEDICAO_ITEM_EMPREENDIMENTO AS MEDICAO_ITEM_EMPREENDIMENTO					(NOLOCK) ON (MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO_ITEM_EMPREENDIMENTO = MEDICAO_FICHA_PREENCHIDA.ID_MEDICAO_ITEM_EMPREENDIMENTO)
LEFT JOIN DBCONTROLEMP.dbo.MEDICAO AS MEDICAO															(NOLOCK) ON (MEDICAO.ID_MEDICAO = MEDICAO_ITEM_EMPREENDIMENTO.ID_MEDICAO AND MEDICAO.EXCLUIDO <> 1)
LEFT JOIN DBCONTROLEMP.dbo.CONTRATO AS CONTRATO															(NOLOCK) ON (CONTRATO.ID_CONTRATO = MEDICAO.ID_CONTRATO AND CONTRATO.ID_OBRA = MEDICAO.ID_OBRA)
LEFT JOIN DBCONTROLEMP.dbo.ETAPA AS ETAPA																(NOLOCK) ON (ETAPA.ID_ETAPA = MEDICAO.ID_ETAPA)		
	



where	OBRA.ID_OBRA = 154
AND		FICHA_PREENCHIDA.ID_EMPREITEIRO = 4296
AND		NOM_LOCAL_APARTAMENTO LIKE '%1808%'


