/*COPIAR CAMPO COMPLEMENTAR ENTRE COLIGADAS */

--SELECT * FROM GDEFCOMPL WHERE  APLICACAO = 'T' AND  NOMECOLUNA like '%curva%c%'

--BEGIN TRAN 
--DELETE FROM GDEFCOMPL WHERE  APLICACAO = 'T' AND  NOMECOLUNA like '%URGENCIA' AND CODCOLIGADA <> 51

/* COPIA CAMPO DESTINO */ 

DECLARE @CODCOLIGADA_ORIGEM INT; 
DECLARE @NOMECOLUNA VARCHAR (50);
DECLARE @APLICACAO VARCHAR(2); 
DECLARE @TABDADOS VARCHAR (50);
DECLARE @I INT;

SET @CODCOLIGADA_ORIGEM  = 1;
SET @NOMECOLUNA = 'DESTINO';
SET @TABDADOS = 'TMOVCOMPL'
SET @APLICACAO  = 'T';
SET @I  = 1


BEGIN TRAN
--ROLLBACK
--COMMIT

WHILE @I < (SELECT COUNT(*)FROM GCOLIGADA)
BEGIN
  
 
  IF(SELECT COUNT(*) FROM GDEFCOMPL WHERE CODCOLIGADA = @I AND NOMECOLUNA =@NOMECOLUNA AND APLICACAO =@APLICACAO) = 0 AND (SELECT COUNT(*) FROM GCOLIGADA WHERE CODCOLIGADA = @I) = 1
   BEGIN
     INSERT INTO GDEFCOMPL ([CODCOLIGADA],[APLICACAO],[TABDADOS],[NOMECOLUNA],[DESCRICAO],[CODTABDINAM],[CODFORMULA],[VALORDEFAULT],[CODCOLTABDINAM],[APLICTABDINAM],[ORDEM],
                            [QUEBRALINHA],[PESQTABDINAMPORCOD],[CODCOLFORMULA],[CODAPLICFORMULA],[TIPOTEXTO],[RECCREATEDBY],[RECCREATEDON],[RECMODIFIEDBY],[RECMODIFIEDON],[FORMATO],[MASCARA])
 
        SELECT @I,[APLICACAO],[TABDADOS],[NOMECOLUNA],[DESCRICAO],[CODTABDINAM],[CODFORMULA],[VALORDEFAULT],[CODCOLTABDINAM],[APLICTABDINAM],[ORDEM],
               [QUEBRALINHA],[PESQTABDINAMPORCOD],[CODCOLFORMULA],[CODAPLICFORMULA],[TIPOTEXTO],[RECCREATEDBY],[RECCREATEDON],[RECMODIFIEDBY],[RECMODIFIEDON],[FORMATO],[MASCARA] 
                FROM GDEFCOMPL (NOLOCK)
                  WHERE CODCOLIGADA = @CODCOLIGADA_ORIGEM 
				  AND NOMECOLUNA = @NOMECOLUNA 
				  AND APLICACAO = @APLICACAO
				  AND NOMECOLUNA NOT IN (SELECT DESTINO.NOMECOLUNA 
													FROM GDEFCOMPL AS DESTINO (NOLOCK) 
													WHERE DESTINO.CODCOLIGADA = @I
														AND DESTINO.APLICACAO = @APLICACAO 
														)
 
      END         
	 SET @I += 1;  
END	



/* 
DESTINO 
DATAVIAGEM
DATARETORNO 
*/

