--CONSULTA - SALDO
Declare @DATA_INI_D date = '20240501'
declare @DATA_FIM_D	date = '20240507'
declare @CONTA_CAIXA varchar(15) = '11006-0'
declare @COLIGADA int = 44


DECLARE @SALDO RMDVALOR4
DECLARE @CODCOLIGADA INT, @CONT INT, @IDXCX INT
DECLARE @SALDO_ANTERIOR RMDVALOR4, @VALOR RMDVALOR4
DECLARE @CLASS_FINANC NVARCHAR(50)

DECLARE @TABELA TABLE (
    CODCOLIGADA INT, 
    IDXCX INT, 
    VALOR RMDVALOR4, 
    SALDO RMDVALOR4, 
    SALDO_ANTERIOR RMDVALOR4,
    CLASS_FINANC NVARCHAR(50)
)

DECLARE CURSOR01 CURSOR FOR 
SELECT 
    FXCX.CODCOLIGADA,
    ROW_NUMBER() OVER (ORDER BY FXCX.DATACOMPENSACAO, FXCX.IDXCX) AS CONT,
    FXCX.IDXCX,
    ISNULL((
        SELECT SUM(F.VALOR) 
        FROM FXCX F (NOLOCK)
        WHERE 
            F.CODCOLIGADA = @COLIGADA
            AND F.DATACOMPENSACAO < @DATA_INI_D
            AND F.CODCXA = @CONTA_CAIXA
    ), '0') AS SALDO_ANTERIOR_RM,
    FXCX.VALOR AS VALOR,
    FXCX.CODTB2FLX AS CLASS_FINANC
FROM FXCX (NOLOCK)
WHERE
    FXCX.CODCOLIGADA = @COLIGADA
    AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
    AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
    AND FXCX.CODCXA = @CONTA_CAIXA
ORDER BY
    FXCX.DATACOMPENSACAO,
    FXCX.IDXCX

OPEN CURSOR01
FETCH NEXT FROM CURSOR01 INTO 
    @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC

WHILE @@FETCH_STATUS = 0 
BEGIN 
    IF (@CONT = 1)
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO_ANTERIOR + @VALOR, @SALDO_ANTERIOR, @CLASS_FINANC)
        SET @SALDO = @SALDO_ANTERIOR + @VALOR
    END
    ELSE
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO + @VALOR, @SALDO, @CLASS_FINANC)
        SET @SALDO = @SALDO + @VALOR
    END

    FETCH NEXT FROM CURSOR01 INTO 
        @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC
END 

CLOSE CURSOR01
DEALLOCATE CURSOR01

SELECT 
( CASE 
	WHEN G.VALOR1 > 0 THEN (G.VALOR1 + G.VALOR_INTEGRACAO)
	ELSE G.VALOR_INTEGRACAO
	END) AS 'VALOR_INT_2',
	(CASE WHEN G.VALOR1 IS NULL THEN G.VALOR_CONTA ELSE G.VALOR1 END) AS 'VALOR',
	(CASE WHEN G.HISTORICO1 IS NULL THEN G.CONTA_HIST ELSE G.HISTORICO1 END) AS 'HISTORICO',
	(CASE WHEN G.VALOR1 < 0 THEN (G.VALOR_BAIXADO1 * (-1)) ELSE VALOR_BAIXADO1 END) AS 'VALOR_BAIXADO',
	G.IDXCX,
    G.CLASS_FINANC,
    G.CLASSI_FINANC2,
    G.NOM_CLASSI,
    G.DATA,
    G.NUMERODOCUMENTO,
    G.CONTA_HIST,
    G.VALOR_CONTA,
    G.VALOR1,
    G.SALDO,
    G.SALDO_ANTERIOR,
    G.CODCOLIGADA,
    G.IDLAN,
    G.DATA_CONTABILIZA플O,
    G.NOME_CENTRO_DE_CUSTO,
    G.NOME_FANTASIA,
    G.HISTORICO1,
    G.VALOR_BAIXADO1,
    G.DATA_DA_BAIXA,
    G.CODTB2FLX,
    G.DESCRICAO_ITEM,
    G.VALOR_LIQUIDO_RATEADO,
    G.VALOR_LIQUIDO_RATEADO2,
    G.DATABAIXA,
    G.USUARIOCRIACAO,
    G.DATACRIACAO,
    G.NUNDOC,
    G.CENTRO_DE_CUSTO_DO_RATEIO,
    G.CENTRO_DE_CUSTO,
    G.VALOR_INTEGRACAO

FROM(
SELECT 
/* INICO CONCILIA플O */ 
A.IDXCX,
A.CLASS_FINANC,
/*FXCX.DATA,*/
FXCX.CODTB2FLX AS 'CLASSI_FINANC2',
FTB2.DESCRICAO AS 'NOM_CLASSI',
FXCX.DATACOMPENSACAO AS 'DATA',
FXCX.NUMERODOCUMENTO,
FXCX.HISTORICO AS 'CONTA_HIST',
CONVERT(MONEY,FXCX.VALOR) AS 'VALOR_CONTA',
CONVERT(MONEY,A.VALOR) AS 'VALOR1',
A.SALDO,
A.SALDO_ANTERIOR,
A.CODCOLIGADA,
/* FIM CONCILIA플O */

/* INICIO 009.002 */ 
FLAN.IDLAN,
FLANBAIXA.DATACONTABILIZBX AS 'DATA_CONTABILIZA플O',
GCCUSTO.NOME AS 'NOME_CENTRO_DE_CUSTO', 
FCFO.NOME AS 'NOME_FANTASIA', 
FLAN.HISTORICO AS 'HISTORICO1',
FLANBAIXARATCCU.VALOR AS 'VALOR_BAIXADO1', 
FLAN.DATABAIXA AS 'DATA_DA_BAIXA',
FLAN.CODTB2FLX, 
FTB5.DESCRICAO AS 'DESCRICAO_ITEM',
/* FIM 009.002 */ 

/* INICIO 009.051 */ 
CAST(
    ROUND(
        (
            FLAN.VALORORIGINAL - 
            (
                FLAN.VALORDESCONTO +
                FLAN.VALORADIANTAMENTO +
                FLAN.VALORDEVOLUCAO +
                FLAN.VALOROP1 +
                FLAN.VALOROP2 +
                FLAN.VALOROP3 +
                FLAN.VALOROP5 +
                FLAN.VALORINSS +
                FLAN.VALORIRRF +
                FLAN.VALORSESTSENAT +
                (SELECT ISNULL(SUM(FTRBLAN.VALOR), 0) FROM FTRBLAN (NOLOCK) WHERE FTRBLAN.IDLAN = FLAN.IDLAN AND FTRBLAN.CODCOLIGADA = FLAN.CODCOLIGADA)
            ) +
            FLAN.VALOROP4 +
            FLAN.VALORJUROS +
            FLAN.VALORMULTA
        ) * ISNULL(FLANRATCCU.PERCENTUAL, 100) / 100, 
        2
    ) 
AS money) AS 'VALOR_LIQUIDO_RATEADO',


dbo.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA, FLAN.IDLAN, GCCUSTO.CODCCUSTO) AS 'VALOR_LIQUIDO_RATEADO2',
FLAN.DATABAIXA,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
FLAN.NUMERODOCUMENTO as 'NUNDOC',
DBO.REMOVE_QUEBRA_LINHA(FLAN.HISTORICO) AS 'FLAN_HISTORICO',

/* FIM 009.051 */

/* ADI합ES SOLICITADAS */ 
FLANRATCCU.CODCCUSTO AS 'CENTRO_DE_CUSTO_DO_RATEIO',
GCCUSTO.CODCCUSTO AS 'CENTRO_DE_CUSTO',
ISNULL((SELECT SUM(FLANINTEGRACAO.VALOR)
			FROM FLANINTEGRACAO
			WHERE (FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN)),0) AS 'VALOR_INTEGRACAO'


FROM @TABELA AS A
LEFT JOIN FXCX				(NOLOCK) ON (FXCX.IDXCX = A.IDXCX AND FXCX.CODCOLIGADA = A.CODCOLIGADA)
LEFT JOIN FTB2				(NOLOCK) ON (FXCX.CODCOLIGADA=FTB2.CODCOLIGADA AND FXCX.CODTB2FLX=FTB2.CODTB2FLX)
/* VINCULADAS A FLAN */
LEFT JOIN FLANBAIXA			(NOLOCK) ON (A.CODCOLIGADA = FLANBAIXA.CODCOLXCX AND A.IDXCX = FLANBAIXA.IDXCX)
LEFT JOIN FLANBAIXARATCCU	(NOLOCK) ON (FLANBAIXA.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA AND FLANBAIXA.IDLAN = FLANBAIXARATCCU.IDLAN AND FLANBAIXA.IDBAIXA = FLANBAIXARATCCU.IDBAIXA)
LEFT JOIN FLAN				(NOLOCK) ON (FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN)
LEFT JOIN FLANRATCCU		(NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN)
LEFT JOIN FCFO				(NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN FCFODEF			(NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB5				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN FTB2 AS FTB2_DEF	(NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)

LEFT JOIN TMOV				(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN GCCUSTO			(NOLOCK) ON (GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO AND GCCUSTO.CODCOLIGADA = FLAN.CODCOLIGADA)


WHERE
FXCX.CODCOLIGADA = @COLIGADA
AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
AND FXCX.CODCXA = @CONTA_CAIXA

) AS G

ORDER BY
G.DATA_CONTABILIZA플O
