SELECT
	GRUPO.CODCOLIGADA,
	GRUPO.CODCONTA AS COD_CONTA,
	GRUPO.DESCRICAO AS DESCRICAO,
	(VALORCSALDOEXERCICIO ) + ( ( SALDOANTDEB ) - ( SALDOANTCRED ) ) AS 'Anterior',
	MOVDEB AS 'Débito', 
	MOVCRED AS 'Crédito', 
	(MOVDEB-MOVCRED) AS 'Movimento',
	( VALORCSALDOEXERCICIO ) + ( ( SALDOANTDEB ) - ( SALDOANTCRED ) ) + ( ( MOVDEB ) - ( MOVCRED ) ) AS 'Saldo Atual'

FROM

(

		SELECT 
			CONTA_COLIGADA.CODCOLIGADA,
			CONTA_COLIGADA.CODCONTA,
			CONTA_COLIGADA.DESCRICAO,
			(SELECT ISNULL (Sum (VALOR), 0) VALORCSALDOEXERCICIO
			FROM   CSALDOEXERCICIO (NOLOCK)
			WHERE  IDEXERCICIO = (SELECT Max(IDEXERCICIO)
								  FROM   CSALDOEXERCICIO (NOLOCK) MAXIMO5
								  WHERE  CSALDOEXERCICIO.CODCOLIGADA = CONTA_COLIGADA.CODCOLIGADA
								  )
               AND CODCONTA = CONTA_COLIGADA.CODCONTA
			   AND CODCOLIGADA = CONTA_COLIGADA.CODCOLIGADA) VALORCSALDOEXERCICIO,

       (SELECT ISNULL (Sum (VALOR), 0) AS SALDOANTDEB
        FROM   CPARTIDA (NOLOCK)
        WHERE  DATA < @DATA_INICIAL_PERIODO
               AND  DEBITO = CONTA_COLIGADA.CODCONTA 
               AND CPARTIDA.CODCOLDEBITO = CONTA_COLIGADA.CODCOLIGADA
               AND CODCOLIGADA  = CONTA_COLIGADA.CODCOLIGADA
               AND CODLOTE = 0) SALDOANTDEB,

       (SELECT ISNULL (Sum (VALOR), 0) AS SALDOANTCRED
        FROM   CPARTIDA (NOLOCK)
        WHERE  DATA < @DATA_INICIAL_PERIODO
               AND  CREDITO = CONTA_COLIGADA.CODCONTA 
               AND CPARTIDA.CODCOLIGADA = CONTA_COLIGADA.CODCOLIGADA
               AND CODLOTE = 0) SALDOANTCRED,

       (SELECT ISNULL (Sum (VALOR), 0) AS MOVDEB
        FROM   CPARTIDA (NOLOCK)
        WHERE  DATA >= @DATA_INICIAL_PERIODO
               AND DATA <= @DATA_FINAL_PERIODO
               AND  DEBITO = CONTA_COLIGADA.CODCONTA 
               AND CPARTIDA.CODCOLIGADA = CONTA_COLIGADA.CODCOLIGADA
               AND CODLOTE = 0) MOVDEB,

       (SELECT ISNULL (Sum (VALOR), 0) AS MOVCRED
        FROM   CPARTIDA (NOLOCK)
        WHERE  DATA >= @DATA_INICIAL_PERIODO
               AND DATA <= @DATA_FINAL_PERIODO
               AND CODLOTE = 0
               AND  CREDITO = CONTA_COLIGADA.CODCONTA 
               AND CPARTIDA.CODCOLIGADA = CONTA_COLIGADA.CODCOLIGADA
			   ) MOVCRED

	FROM CCONTA AS CONTA_COLIGADA (NOLOCK)
	WHERE (CODCONTA LIKE + '%' + (@CODCONTA) + '%' OR CODCONTA IN (@CODCONTA))
	AND CODCOLIGADA IN (@CODCOLIGADA)
	AND CONTA_COLIGADA.ANALITICA = 1

	
) AS GRUPO

/*WHERE ((VALORCSALDOEXERCICIO ) + ( ( SALDOANTDEB ) - ( SALDOANTCRED ) ) <> 0
	OR MOVDEB <> 0
	OR MOVCRED <> 0
	OR  (MOVCRED-MOVDEB) <> 0
	OR ( VALORCSALDOEXERCICIO ) + ( ( SALDOANTDEB ) - ( SALDOANTCRED ) ) + ( ( MOVDEB ) - ( MOVCRED ) ) <> 0)*/

GROUP BY
	GRUPO.CODCOLIGADA,
	GRUPO.CODCONTA,
	GRUPO.VALORCSALDOEXERCICIO,
	GRUPO.SALDOANTDEB,
	GRUPO.SALDOANTCRED,
	GRUPO.MOVDEB, 
	GRUPO.MOVCRED,
	GRUPO.DESCRICAO

ORDER BY GRUPO.CODCONTA