--CONSULTA - SALDO
/*declare @DATA_INI_D date = '20240301'
declare @DATA_FIM_D	date = '20240315'
declare @CONTA_CAIXA varchar(15) = '473-1'
declare @COLIGADA int = 1
*/

DECLARE @SALDO RMDVALOR4
DECLARE @CODCOLIGADA INT, @CONT INT, @IDXCX INT
DECLARE @SALDO_ANTERIOR RMDVALOR4, @VALOR RMDVALOR4
DECLARE @CLASS_FINANC NVARCHAR(50)

DECLARE @TABELA TABLE (
    CODCOLIGADA INT, 
    IDXCX INT, 
    VALOR RMDVALOR4, 
    SALDO RMDVALOR4, 
    SALDO_ANTERIOR RMDVALOR4,
    CLASS_FINANC NVARCHAR(50)
)

DECLARE CURSOR01 CURSOR FOR 
SELECT 
    FXCX.CODCOLIGADA,
    ROW_NUMBER() OVER (ORDER BY FXCX.DATACOMPENSACAO, FXCX.IDXCX) AS CONT,
    FXCX.IDXCX,
    ISNULL((
        SELECT SUM(F.VALOR) 
        FROM FXCX F (NOLOCK)
        WHERE 
            F.CODCOLIGADA = @COLIGADA
            AND F.DATACOMPENSACAO < @DATA_INI_D
            AND F.CODCXA = @CONTA_CAIXA
    ), '0') AS SALDO_ANTERIOR_RM,
    FXCX.VALOR AS VALOR,
    FXCX.CODTB2FLX AS CLASS_FINANC
FROM FXCX (NOLOCK)
WHERE
    FXCX.CODCOLIGADA = @COLIGADA
    AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
    AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
    AND FXCX.CODCXA = @CONTA_CAIXA
ORDER BY
    FXCX.DATACOMPENSACAO,
    FXCX.IDXCX

OPEN CURSOR01
FETCH NEXT FROM CURSOR01 INTO 
    @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC

WHILE @@FETCH_STATUS = 0 
BEGIN 
    IF (@CONT = 1)
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO_ANTERIOR + @VALOR, @SALDO_ANTERIOR, @CLASS_FINANC)
        SET @SALDO = @SALDO_ANTERIOR + @VALOR
    END
    ELSE
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO + @VALOR, @SALDO, @CLASS_FINANC)
        SET @SALDO = @SALDO + @VALOR
    END

    FETCH NEXT FROM CURSOR01 INTO 
        @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC
END 

CLOSE CURSOR01
DEALLOCATE CURSOR01

SELECT 
( CASE 
	WHEN A.VALOR > 0 THEN (A.VALOR + A.VALOR_INTEGRACAO)
	ELSE A.VALOR_INTEGRACAO
	END) AS 'VALOR_INT_2'
	,* 
FROM(
SELECT 
/* INICO CONCILIA플O */ 
A.IDXCX,
A.CLASS_FINANC,
/*FXCX.DATA,*/
FXCX.DATACOMPENSACAO AS 'DATA',
FXCX.NUMERODOCUMENTO,
'' AS 'NOMINAL',
CONVERT(MONEY,A.VALOR) AS 'VALOR',
A.SALDO,
A.SALDO_ANTERIOR,
A.CODCOLIGADA,
/* FIM CONCILIA플O */

/* INICIO 009.002 */ 
FLAN.IDLAN,
FLANBAIXA.DATACONTABILIZBX AS 'DATA CONTABILIZA플O',
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO', 
FCFO.NOME AS 'NOME FANTASIA', 
FLAN.HISTORICO,
FLANBAIXA.VALORBAIXA AS 'VALOR BAIXADO', 
FLAN.DATABAIXA AS 'DATA DA BAIXA',
FLAN.CODTB2FLX, 
FTB5.DESCRICAO AS 'DESCRICAO ITEM',
/* FIM 009.002 */ 

/* INICIO 009.051 */ 
CAST(
    ROUND(
        (
            FLAN.VALORORIGINAL - 
            (
                FLAN.VALORDESCONTO +
                FLAN.VALORADIANTAMENTO +
                FLAN.VALORDEVOLUCAO +
                FLAN.VALOROP1 +
                FLAN.VALOROP2 +
                FLAN.VALOROP3 +
                FLAN.VALOROP5 +
                FLAN.VALORINSS +
                FLAN.VALORIRRF +
                FLAN.VALORSESTSENAT +
                (SELECT ISNULL(SUM(FTRBLAN.VALOR), 0) FROM FTRBLAN (NOLOCK) WHERE FTRBLAN.IDLAN = FLAN.IDLAN AND FTRBLAN.CODCOLIGADA = FLAN.CODCOLIGADA)
            ) +
            FLAN.VALOROP4 +
            FLAN.VALORJUROS +
            FLAN.VALORMULTA
        ) * ISNULL(FLANRATCCU.PERCENTUAL, 100) / 100, 
        2
    ) 
AS money) AS 'VALOR_LIQUIDO_RATEADO',


dbo.VALOR_LIQUIDO_FLUXUS(FLAN.CODCOLIGADA, FLAN.IDLAN, GCCUSTO.CODCCUSTO) AS 'VALOR_LIQUIDO_RATEADO2',
FLAN.DATABAIXA,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
FLAN.NUMERODOCUMENTO as 'NUNDOC',
DBO.REMOVE_QUEBRA_LINHA(FLAN.HISTORICO) AS 'FLAN_HISTORICO',

/* FIM 009.051 */

/* ADI합ES SOLICITADAS */ 
FLANRATCCU.CODCCUSTO AS 'CENTRO DE CUSTO DO RATEIO',
GCCUSTO.CODCCUSTO AS 'CENTRO DE CUSTO',
ISNULL((SELECT SUM(FLANINTEGRACAO.VALOR)
			FROM FLANINTEGRACAO
			WHERE (FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN)),0) AS 'VALOR_INTEGRACAO'


FROM @TABELA AS A
INNER JOIN FXCX				(NOLOCK) ON (FXCX.IDXCX = A.IDXCX AND FXCX.CODCOLIGADA = A.CODCOLIGADA)
/* VINCULADAS A FLAN */
LEFT JOIN FLANBAIXA			(NOLOCK) ON (A.CODCOLIGADA = FLANBAIXA.CODCOLXCX AND A.IDXCX = FLANBAIXA.IDXCX)
LEFT JOIN FLAN				(NOLOCK) ON (FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN)
LEFT JOIN FLANRATCCU		(NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN)
LEFT JOIN FCFO				(NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN FCFODEF			(NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB5				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN FTB2 AS FTB2_DEF	(NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)
LEFT JOIN FTB2				(NOLOCK) ON (FLAN.CODCOLIGADA=FTB2.CODCOLIGADA AND FLAN.CODTB2FLX=FTB2.CODTB2FLX)
LEFT JOIN TMOV				(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN GCCUSTO			(NOLOCK) ON (GCCUSTO.CODCCUSTO = FLAN.CODCCUSTO AND GCCUSTO.CODCOLIGADA = FLAN.CODCOLIGADA)

/* CAMPOS DE INTEGRA플O */
--LEFT JOIN FLANINTEGRACAO	(NOLOCK) ON (FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN)
/*LEFT JOIN FLANINTEGRACAODEF	(NOLOCK) ON (FLANINTEGRACAO.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA AND FLANINTEGRACAO.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO)*/

WHERE
FXCX.CODCOLIGADA = @COLIGADA
AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
AND FXCX.CODCXA = @CONTA_CAIXA


/*
ORDER BY
FXCX.DATACOMPENSACAO,FXCX.IDXCX*/) AS A

ORDER BY
A.[DATA CONTABILIZA플O]