--CONSULTA - SALDO
/*Declare @DATA_INI_D date = '20240401'
declare @DATA_FIM_D	date = '20240430'
declare @CONTA_CAIXA varchar(15) = '11006-0'
declare @COLIGADA int = 44
*/ 

DECLARE @SALDO RMDVALOR4
DECLARE @CODCOLIGADA INT, @CONT INT, @IDXCX INT
DECLARE @SALDO_ANTERIOR RMDVALOR4, @VALOR RMDVALOR4
DECLARE @CLASS_FINANC NVARCHAR(50)

DECLARE @TABELA TABLE (
    CODCOLIGADA INT, 
    IDXCX INT, 
    VALOR RMDVALOR4, 
    SALDO RMDVALOR4, 
    SALDO_ANTERIOR RMDVALOR4,
    CLASS_FINANC NVARCHAR(50)
)

DECLARE CURSOR01 CURSOR FOR 
SELECT 
    FXCX.CODCOLIGADA,
    ROW_NUMBER() OVER (ORDER BY FXCX.DATACOMPENSACAO, FXCX.IDXCX) AS CONT,
    FXCX.IDXCX,
    ISNULL((
        SELECT SUM(F.VALOR) 
        FROM FXCX F (NOLOCK)
        WHERE 
            F.CODCOLIGADA = @COLIGADA
            AND F.DATACOMPENSACAO < @DATA_INI_D
            AND F.CODCXA = @CONTA_CAIXA
    ), '0') AS SALDO_ANTERIOR_RM,
    FXCX.VALOR AS VALOR,
    FXCX.CODTB2FLX AS CLASS_FINANC
FROM FXCX (NOLOCK)
WHERE
    FXCX.CODCOLIGADA = @COLIGADA
    AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
    AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
    AND FXCX.CODCXA = @CONTA_CAIXA
ORDER BY
    FXCX.DATACOMPENSACAO,
    FXCX.IDXCX

OPEN CURSOR01
FETCH NEXT FROM CURSOR01 INTO 
    @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC

WHILE @@FETCH_STATUS = 0 
BEGIN 
    IF (@CONT = 1)
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO_ANTERIOR + @VALOR, @SALDO_ANTERIOR, @CLASS_FINANC)
        SET @SALDO = @SALDO_ANTERIOR + @VALOR
    END
    ELSE
    BEGIN
        INSERT INTO @TABELA 
        VALUES(@CODCOLIGADA, @IDXCX, @VALOR, @SALDO + @VALOR, @SALDO, @CLASS_FINANC)
        SET @SALDO = @SALDO + @VALOR
    END

    FETCH NEXT FROM CURSOR01 INTO 
        @CODCOLIGADA, @CONT, @IDXCX, @SALDO_ANTERIOR, @VALOR, @CLASS_FINANC
END 

CLOSE CURSOR01
DEALLOCATE CURSOR01

SELECT 
( CASE 
	WHEN G.VALOR1 > 0 THEN (G.VALOR1 + G.VALOR_INTEGRACAO)
	ELSE G.VALOR_INTEGRACAO
	END) AS 'VALOR_INT_2',
	(CASE WHEN G.VALOR1 IS NULL THEN G.VALOR_CONTA ELSE G.VALOR1 END) AS 'VALOR',
	(CASE WHEN G.HISTORICO1 IS NULL THEN G.CONTA_HIST ELSE G.HISTORICO1 END) AS 'HISTORICO',
	(CASE 
		WHEN G.VALOR_BAIXADO1 IS NULL THEN G.VALOR1
		WHEN G.VALOR1 < 0 THEN (G.VALOR_BAIXADO1 * (-1))
		ELSE VALOR_BAIXADO1 END) AS 'VALOR_BAIXADO',
	G.IDXCX,
    (CASE WHEN G.CLASS_FINANC IS NULL THEN G.CLASSI_FINANC2 ELSE G.CLASS_FINANC END) AS 'CLASS_FINANC',
    G.CLASSI_FINANC2,
	G.COD_CONTA,
    G.NOM_CLASSI,
    G.DATA,
    (CASE WHEN G.NUMERODOCUMENTO IS NULL THEN G.CONT_NUMDOC ELSE G.NUMERODOCUMENTO END) AS 'NUMERODOCUMENTO',
    G.CONTA_HIST,
    G.VALOR_CONTA,
    G.VALOR1,
    G.SALDO,
    G.SALDO_ANTERIOR,
    G.CODCOLIGADA,
    G.IDLAN,
    G.DATA_CONTABILIZA플O,
    G.NOME_FANTASIA,
    G.HISTORICO1,
    G.VALOR_BAIXADO1,
    (CASE WHEN G.DATA_DA_BAIXA IS NULL THEN G.CONT_DATA ELSE G.DATA_DA_BAIXA END) AS 'DATA_DA_BAIXA',
    G.CODTB2FLX,
    G.DESCRICAO_ITEM,
    G.DATABAIXA,
    G.USUARIOCRIACAO,
    G.DATACRIACAO,
    G.NUNDOC,
    G.IDTRF,
	(CASE WHEN G.CENTRO_DE_CUSTO_DO_RATEIO IS NULL THEN G.CENTRO_DE_CUSTO ELSE G.CENTRO_DE_CUSTO_DO_RATEIO END) AS 'CASE_CODCCUSTO',
	(CASE WHEN G.CDC_R_NOME IS NULL THEN G.CDC_N_NOME ELSE G.CDC_R_NOME END) AS 'NOME_CDC',
	G.CONT_CODCUSTO,
    G.VALOR_INTEGRACAO,
	G.ORIGEM_USUARIOCRIACAO AS 'USU_CRIACAO',
	G.ORIGEM_DATACRIACAO AS 'DT_CRIACAO',
	G.ORIGEM_USUARIOAPROVACAO AS 'USU_APROV',
	G.ORIGEM_USUARIOAPROVACAO AS 'DT_APROV'
	
FROM(
SELECT 
/* INICO CONCILIA플O */ 
A.IDXCX,
A.CLASS_FINANC,
/*FXCX.DATA,*/
FXCX.CODTB2FLX AS 'CLASSI_FINANC2',
FXCX.CODCXA AS 'COD_CONTA',
FTB2.DESCRICAO AS 'NOM_CLASSI',
FXCX.DATACOMPENSACAO AS 'DATA',
FXCX.NUMERODOCUMENTO,
FXCX.HISTORICO AS 'CONTA_HIST',
FXCX.NUMERODOCUMENTO AS 'CONT_NUMDOC',
FXCX.CODCCUSTO AS 'CONT_CODCUSTO',
FXCX.DATA AS 'CONT_DATA',
CONVERT(MONEY,FXCX.VALOR) AS 'VALOR_CONTA',
CONVERT(MONEY,A.VALOR) AS 'VALOR1',
A.SALDO,
A.SALDO_ANTERIOR,
A.CODCOLIGADA,
/* FIM CONCILIA플O */

/* INICIO 009.002 */ 
FLAN.IDLAN,
FLANBAIXA.DATACONTABILIZBX AS 'DATA_CONTABILIZA플O',
GCCUSTO.NOME AS 'NOME_CENTRO_DE_CUSTO', 
FCFO.NOME AS 'NOME_FANTASIA', 
FLAN.HISTORICO AS 'HISTORICO1',
FLANBAIXARATCCU.VALOR AS 'VALOR_BAIXADO1', 
FLAN.DATABAIXA AS 'DATA_DA_BAIXA',
FLAN.CODTB2FLX, 
FTB5.DESCRICAO AS 'DESCRICAO_ITEM',
/* FIM 009.002 */ 

/* INICIO 009.051 */ 
FLAN.DATABAIXA,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
FLAN.NUMERODOCUMENTO as 'NUNDOC',
DBO.REMOVE_QUEBRA_LINHA(FLAN.HISTORICO) AS 'FLAN_HISTORICO',
ISNULL((SELECT MAX (ORIGEM.USUARIOCRIACAO) FROM TMOVRELAC (NOLOCK)
		LEFT JOIN	TMOV ORIGEM			(NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
		WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA), FLAN.USUARIOCRIACAO) AS 'ORIGEM_USUARIOCRIACAO',
ISNULL((SELECT MAX (ORIGEM.DATACRIACAO) FROM TMOVRELAC (NOLOCK)
		LEFT JOIN	TMOV ORIGEM			(NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
		WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA),FLAN.DATACRIACAO) AS 'ORIGEM_DATACRIACAO',
(SELECT MAX (TMOVAPROVA.CODUSUARIO) FROM TMOVRELAC (NOLOCK)
		LEFT JOIN		TMOV ORIGEM			(NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
		LEFT JOIN		TMOVAPROVA			(NOLOCK) ON (TMOVAPROVA.IDMOV = ORIGEM.IDMOV AND TMOVAPROVA.CODCOLIGADA = ORIGEM.CODCOLIGADA  AND TMOVAPROVA.TIPOAPROVACAO = 1)
		WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA) AS 'ORIGEM_USUARIOAPROVACAO',
(SELECT MAX (TMOVAPROVA.DATAAPROVACAO) FROM TMOVRELAC (NOLOCK)
		LEFT JOIN		TMOV ORIGEM			(NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
		LEFT JOIN		TMOVAPROVA			(NOLOCK) ON (TMOVAPROVA.IDMOV = ORIGEM.IDMOV AND TMOVAPROVA.CODCOLIGADA = ORIGEM.CODCOLIGADA  AND TMOVAPROVA.TIPOAPROVACAO = 1)
		WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA) AS 'ORIGEM_DATAAPROVACAO',

/* FIM 009.051 */

/* ADI합ES SOLICITADAS */ 
FLANBAIXARATCCU.CODCCUSTO AS 'CENTRO_DE_CUSTO_DO_RATEIO',
GCCUSTO.CODCCUSTO AS 'CENTRO_DE_CUSTO',
ISNULL((SELECT SUM(FLANINTEGRACAO.VALOR)
			FROM FLANINTEGRACAO
			WHERE (FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN)),0) AS 'VALOR_INTEGRACAO',
			FLANBAIXARATCCU.IDTRF,
			GCCUSTO.NOME AS 'CDC_N_NOME',
			CUSTRAT.NOME AS 'CDC_R_NOME'

FROM @TABELA AS A
LEFT JOIN FXCX				(NOLOCK) ON (FXCX.IDXCX = A.IDXCX AND FXCX.CODCOLIGADA = A.CODCOLIGADA)
LEFT JOIN FTB2				(NOLOCK) ON (FXCX.CODCOLIGADA=FTB2.CODCOLIGADA AND FXCX.CODTB2FLX=FTB2.CODTB2FLX)
/* VINCULADAS A FLAN */
LEFT JOIN FLANBAIXA				(NOLOCK) ON (A.CODCOLIGADA = FLANBAIXA.CODCOLXCX AND A.IDXCX = FLANBAIXA.IDXCX)
LEFT JOIN FLANBAIXARATCCU		(NOLOCK) ON (FLANBAIXA.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA AND FLANBAIXA.IDLAN = FLANBAIXARATCCU.IDLAN AND FLANBAIXA.IDBAIXA = FLANBAIXARATCCU.IDBAIXA)
LEFT JOIN FLAN					(NOLOCK) ON (FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN)
LEFT JOIN FLANRATCCU			(NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN)
LEFT JOIN FCFO					(NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN FCFODEF				(NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB5					(NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN FTB2 AS FTB2_DEF		(NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)
LEFT JOIN TMOV					(NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN GCCUSTO				(NOLOCK) ON (FXCX.CODCCUSTO = GCCUSTO.CODCCUSTO AND FXCX.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN GCCUSTO AS CUSTRAT	(NOLOCK) ON (CUSTRAT.CODCCUSTO = FLANBAIXARATCCU.CODCCUSTO AND CUSTRAT.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA)

WHERE
FXCX.CODCOLIGADA = @COLIGADA
AND FXCX.DATACOMPENSACAO >= @DATA_INI_D
AND FXCX.DATACOMPENSACAO <= @DATA_FIM_D
AND FXCX.CODCXA = @CONTA_CAIXA



) AS G

GROUP BY 
G.VALOR1,
G.VALOR_INTEGRACAO,
G.VALOR_CONTA,
G.HISTORICO1,
G.COD_CONTA,
G.CONTA_HIST,
G.VALOR_BAIXADO1,
	G.CENTRO_DE_CUSTO_DO_RATEIO,
	G.IDXCX,
    G.CLASS_FINANC,
    G.CLASSI_FINANC2,
    G.NOM_CLASSI,
    G.DATA,
    G.NUMERODOCUMENTO,
    G.CONTA_HIST,
    G.VALOR_CONTA,
    G.VALOR1,
    G.SALDO,
    G.SALDO_ANTERIOR,
    G.CODCOLIGADA,
    G.IDLAN,
    G.DATA_CONTABILIZA플O,
    G.NOME_CENTRO_DE_CUSTO,
    G.NOME_FANTASIA,
    G.HISTORICO1,
    G.VALOR_BAIXADO1,
    G.DATA_DA_BAIXA,
    G.CODTB2FLX,
    G.DESCRICAO_ITEM,
    G.DATABAIXA,
    G.USUARIOCRIACAO,
    G.DATACRIACAO,
	G.CONT_CODCUSTO,
	G.CONT_DATA,
	G.CONT_NUMDOC,
    G.NUNDOC,
    G.IDTRF,
    G.CENTRO_DE_CUSTO,
    G.VALOR_INTEGRACAO,
	G.CDC_N_NOME,
	G.CDC_R_NOME,
	G.ORIGEM_USUARIOCRIACAO,
	G.ORIGEM_DATACRIACAO,
	G.ORIGEM_USUARIOAPROVACAO,
	G.ORIGEM_USUARIOAPROVACAO



ORDER BY
G.DATA
