SELECT VR_TOT_VENDA, NOME,  XVENDA.CODCOLIGADA, * 
FROM XVENDA
JOIN XEMPREENDIMENTO ON XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR
WHERE XVENDA.CODCOLIGADA = 29
ORDER BY XVENDA.VR_TOT_VENDA DESC

