SELECT 
TMOV.CODCOLIGADA AS COLIGADA, 
TMOV.CODFILIAL AS COD_FILIAL,
GFILIAL.NOMEFANTASIA AS NOME_FILIAL,

 

 

 

(CASE
      WHEN TMOV_ODC.STATUS = 'C' THEN 'CANCELADO'    
      WHEN ITEM_ODC.QUANTIDADEARECEBER > 0 AND TMOV_ODC.DATAENTREGA > GETDATE() THEN 'PROGRAMADO'
      WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 'RECEBIDO'
      WHEN ITEM_ODC.QUANTIDADEARECEBER < ITEM_ODC.QUANTIDADETOTAL THEN 'PARCIALMENTE RECEBIDO'
      WHEN ITEM_ODC.QUANTIDADEARECEBER = ITEM_ODC.QUANTIDADETOTAL THEN 'PENDENTE'
END) AS STATUS_NOVO,

(CASE WHEN ITEM_ODC.QUANTIDADEARECEBER = 0 THEN 0 ELSE TMOV_ODC.VALORLIQUIDO END)  AS 'VALOR_DOCUMENTO',
GFILIAL.ESTADO,
ISNULL(
        TMOV.CODCCUSTO,
                        (
                            SELECT TOP 1
                            TITMMOVRATCCU.CODCCUSTO 
                            FROM TITMMOVRATCCU 
                            WHERE    TITMMOVRATCCU.IDMOV = TMOV.IDMOV
                            AND        TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV
                            AND        TITMMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA
                        )
) AS COD_CENTRO_CUSTO,

 

 

 

ISNULL(
        GCCUSTO.NOME,
                        (
                            SELECT TOP 1
                            GCCUSTO.NOME 
                            FROM TITMMOVRATCCU 
                            LEFT JOIN GCCUSTO (NOLOCK) ON (GCCUSTO.CODCCUSTO = TITMMOVRATCCU.CODCCUSTO AND GCCUSTO.CODCOLIGADA = TITMMOVRATCCU.CODCOLIGADA)
                            WHERE    TITMMOVRATCCU.IDMOV = TMOV.IDMOV
                            AND        TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV
                            AND        TITMMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA
                        )
) AS NOME_OBRA,

 

 

 

DBO.DIAS_UTEIS(TMOV_ODC.DATACRIACAO, APROVA_ODC.DATAAPROVACAO) AS 'TEMPO APROVACAO ODC',

 

 

 

TMOV.IDMOV AS IDENTIFICADOR,
TMOV.NUMEROMOV AS NUMERO_MOV_SC,
CONVERT(VARCHAR,TMOV.DATAEMISSAO,103) AS DATA_EMISSAO_SC,
CONVERT(VARCHAR,TITMMOV.DATAENTREGA,103) AS 'ENTREGA_SC',
CONVERT(VARCHAR,DBO.TRAZ_DATAAPROVACAO(TMOV.CODCOLIGADA,TMOV.IDMOV),103) AS DATA_APROVACAO_SC,
/*CONVERT(VARChAR,TMOVAPROVA.DATAAPROVACAO,103) AS DATA_APROVACAO_SC,*/
TMOV.CODTMV AS COD_MOVIMENTO_SC,
TPRODUTO.CODIGOPRD AS COD_PRODUTO_SC,
TPRODUTO.DESCRICAO AS DESC_PRODUTO_SC,
TITMMOV.QUANTIDADETOTAL AS QUANT_PRODUTO_SC,
TCCOTACAO.CODCOTACAO,
CONVERT(VARCHAR, TCCOTACAO.DATCOTACAO, 103) AS DATCOTACAO,
TVEN.NOME,
dbo.DIAS_UTEIS( DBO.TRAZ_DATAAPROVACAO(TMOV.CODCOLIGADA,TMOV.IDMOV),(CASE WHEN TMOV_ODC.DATAEMISSAO IS NULL THEN GETDATE() ELSE TMOV_ODC.DATAEMISSAO END )) AS 'TEMPO CRIAÇÃO DA ODC',
DBO.TRAZ_STATUS(TMOV.STATUS) AS STATUS_SC,
CONVERT(VARCHAR,TMOV_ODC.DATACRIACAO,103) AS DATA_CRIACAO_ODC,
TMOV_ODC.NUMEROMOV AS NUMERO_MOV_ODC,
TMOV_ODC.CODFILIAL AS FILIAL_ODC,
TMOV_ODC.IDMOV AS IDENTIFICADOR_ODC,
TMOV_ODC.CODTMV AS COD_MOVIMENTO_ODC,
ITEM_ODC.QUANTIDADETOTAL as    QUANTIDADE_ODC,
ITEM_ODC.VALORBRUTOITEMORIG,
ITEM_ODC.PRECOUNITARIO,
CONVERT(VARCHAR,APROVA_ODC.DATAAPROVACAO,103) AS DATA_APROVACAO,
dbo.traz_status_cotacao(tccotacao.STSCOTACAO) as 'STATUS_COTACAO',
FCFO.NOME AS FORNECEDOR,
TITMMOV.CODUND,
(CASE TMOV_ODC.STSEMAIL WHEN 1 THEN 'SIM' /*WHEN 2 THEN 'NÃO'*/ ELSE ' ' END)AS 'ODC ENVIADA',
CONVERT(VARCHAR,TMOV_ODC.DATAENTREGA,103)  'DATA_ENTREGA',
CONVERT(VARCHAR,ITEM_ODC.DATAENTREGA,103)  'DATA_ENTREGA_ITEM',

 

 

 

TCPG.NOME AS 'FORMA DE PGTO',
dbo.DIAS_UTEIS( DBO.TRAZ_DATAAPROVACAO(TMOV.CODCOLIGADA,TMOV.IDMOV),(CASE WHEN TMOV_ODC.DATAEMISSAO IS NULL THEN GETDATE() ELSE TMOV_ODC.DATAEMISSAO END )) AS TEMPO,
TMOVCOMPL.URGENCIA,
TMOV.VALOROUTROS,
(CASE WHEN TCCOTACAOITMMOV.TIPOMOVCOMPRAS = 1 THEN 'Ativo'
      WHEN TCCOTACAOITMMOV.TIPOMOVCOMPRAS = 2 THEN 'Ordem de compra gerada'
      WHEN TCCOTACAOITMMOV.TIPOMOVCOMPRAS = 3 THEN 'Concluído'
      WHEN TCCOTACAOITMMOV.TIPOMOVCOMPRAS = -1 THEN 'Excluído'
      WHEN TCCOTACAOITMMOV.TIPOMOVCOMPRAS = 4 THEN 'Estornado'
	  ELSE 'Em branco' END)
AS SITUACAO_DO_ITEM,

 

 

GCONSIST.DESCRICAO AS JUSTIFICATIVA_URGENCIA

 

 

FROM TMOV 
/*LEFT JOIN  TMOVAPROVA            (NOLOCK) ON (TMOVAPROVA.IDMOV = TMOV.IDMOV AND TMOVAPROVA.CODCOLIGADA = TMOV.CODCOLIGADA and tipoaprovacao = '1')*/
LEFT JOIN  TITMMOV                (NOLOCK) ON (TITMMOV.IDMOV = TMOV.IDMOV AND TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN  TCCOTACAOITMMOV      (NOLOCK) ON (TCCOTACAOITMMOV.IDMOV = TITMMOV.IDMOV AND TCCOTACAOITMMOV.NSEQITMMOV = TITMMOV.NSEQITMMOV AND TCCOTACAOITMMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT JOIN  TCCOTACAO            (NOLOCK) ON (TCCOTACAO.CODCOTACAO = TCCOTACAOITMMOV.CODCOTACAO AND TCCOTACAOITMMOV.CODCOLIGADA = TCCOTACAO.CODCOLIGADA)
LEFT JOIN  TVEN                    (NOLOCK) ON (TVEN.CODVEN = TCCOTACAO.CODCOMPRADOR AND TVEN.CODCOLIGADA = TCCOTACAO.CODCOLIGADA)
INNER JOIN TPRODUTO             (NOLOCK) ON (TPRODUTO.IDPRD = TITMMOV.IDPRD )
LEFT JOIN  GCCUSTO                (NOLOCK) ON (GCCUSTO.CODCCUSTO = TMOV.CODCCUSTO AND GCCUSTO.CODCOLIGADA = TMOV.CODCOLIGADA)
INNER JOIN GFILIAL                (NOLOCK) ON (GFILIAL.CODFILIAL = TMOV.CODFILIAL AND GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN TMOVCOMPL                (NOLOCK) ON (TMOVCOMPL.IDMOV = TMOV.IDMOV AND TMOVCOMPL.CODCOLIGADA = TMOV.CODCOLIGADA)
LEFT JOIN GCONSIST				(NOLOCK) ON TMOVCOMPL.JUSTIFICATIVA = GCONSIST.CODINTERNO AND GCONSIST.APLICACAO = 'T' AND GCONSIST.CODTABELA = 'JUSTIFICAT'

 

 

 

/*TRAZ DADOS DA ODC*/
LEFT JOIN TITMMOVRELAC                (NOLOCK) ON (TITMMOV.IDMOV = TITMMOVRELAC.IDMOVORIGEM AND TITMMOV.CODCOLIGADA = TITMMOVRELAC.CODCOLORIGEM AND TITMMOVRELAC.NSEQITMMOVORIGEM = TITMMOV.NSEQITMMOV) 
LEFT JOIN TITMMOV AS ITEM_ODC        (NOLOCK) ON (ITEM_ODC.IDMOV = TITMMOVRELAC.IDMOVDESTINO AND ITEM_ODC.CODCOLIGADA = TITMMOVRELAC.CODCOLDESTINO AND ITEM_ODC.NSEQITMMOV = TITMMOVRELAC.NSEQITMMOVDESTINO ) 
LEFT JOIN TMOV AS TMOV_ODC            (NOLOCK) ON (TMOV_ODC.IDMOV = ITEM_ODC.IDMOV AND TMOV_ODC.CODCOLIGADA = ITEM_ODC.CODCOLIGADA)
LEFT JOIN FCFO                        (NOLOCK) ON (FCFO.CODCFO = TMOV_ODC.CODCFO AND TMOV_ODC.CODCOLCFO = FCFO.CODCOLIGADA)
LEFT JOIN TCPG                        (NOLOCK) ON (TCPG.CODCOLIGADA = TMOV_ODC.CODCOLIGADA AND TCPG.CODCPG = TMOV_ODC.CODCPG)
LEFT JOIN GCCUSTO as CUSTO            (NOLOCK) ON (CUSTO.CODCCUSTO = TMOV_ODC.CODCCUSTO AND CUSTO.CODCOLIGADA = TMOV_ODC.CODCOLIGADA)
LEFT JOIN TPRODUTO AS PRODUTO_ODC    (NOLOCK) ON (PRODUTO_ODC.IDPRD = ITEM_ODC.IDPRD )
LEFT JOIN  TMOVAPROVA AS APROVA_ODC    (NOLOCK) ON (APROVA_ODC.IDMOV = TMOV_ODC.IDMOV AND APROVA_ODC.CODCOLIGADA = TMOV_ODC.CODCOLIGADA and APROVA_ODC.tipoaprovacao = '1')

 

 

 

WHERE        TMOV.CODTMV IN ('1.1.18','1.1.20','1.1.25','1.1.34')
AND        TMOV.STATUS <> 'C'
AND TMOV.DATAEMISSAO >= DATEADD(MONTH, -12,GETDATE())
/*AND        TCCOTACAOITMMOV.TIPOMOVCOMPRAS  NOT IN (-1,4)*/
/*AND TMOV.DATAEMISSAO BETWEEN @DAT_INI AND @DAT_FIM
AND TMOV.CODCOLIGADA IN (@COLIGADA)*/
AND TCCOTACAO.CODCOTACAO = '2023.000110'
AND TCCOTACAO.CODCOLIGADA = 19
AND TITMMOV.QUANTIDADETOTAL > 0
--AND TVEN.NOME LIKE '%EDVAR%'


GROUP BY
TMOV_ODC.STSEMAIL,
TCCOTACAO.DATCOTACAO,
TITMMOV.CODUND,
FCFO.NOME,
GFILIAL.ESTADO,
TITMMOV.NSEQITMMOV,
TCCOTACAO.STSCOTACAO,
TMOV.STSEMAIL,
TCCOTACAO.CODCOTACAO,
CUSTO.NOME,
APROVA_ODC.DATAAPROVACAO,
TVEN.NOME,
TMOV.CODCOLIGADA ,
TMOV.CODFILIAL,
GFILIAL.NOMEFANTASIA,
TMOV.CODCCUSTO,
GCCUSTO.NOME,
TMOV.IDMOV ,
TMOV.NUMEROMOV,
TMOV.CODTMV ,
TPRODUTO.CODIGOPRD ,
TPRODUTO.DESCRICAO ,
TITMMOV.QUANTIDADETOTAL,
TMOV.DATAEMISSAO,
/*TMOVAPROVA.DATAAPROVACAO,*/
TMOV_ODC.DATACRIACAO ,
TMOV_ODC.NUMEROMOV ,
TMOV_ODC.IDMOV,
TMOV_ODC.CODTMV ,
TMOV.STATUS,
TMOV_ODC.STATUS,
TMOV_ODC.DATAEMISSAO,
ITEM_ODC.DATAENTREGA,
TMOV_ODC.CODTMV,
ITEM_ODC.QUANTIDADEARECEBER,
ITEM_ODC.VALORBRUTOITEMORIG,
ITEM_ODC.PRECOUNITARIO,
TMOV.DATAENTREGA,
TMOV_ODC.DATAENTREGA,
TCPG.NOME,
TMOVCOMPL.URGENCIA,
TMOV.VALOROUTROS,
TMOV_ODC.VALORLIQUIDO,
TCCOTACAOITMMOV.TIPOMOVCOMPRAS,
TITMMOV.DATAENTREGA,
TMOV_ODC.CODFILIAL,
TMOV_ODC.DATAENTREGA,
ITEM_ODC.QUANTIDADETOTAL,
TMOV_ODC.RECMODIFIEDON,
TMOVCOMPL.JUSTIFICATIVA,
GCONSIST.DESCRICAO

 
ORDER BY
TMOV.CODCOLIGADA,
TMOV.CODFILIAL,
TMOV.DATAEMISSAO


SELECT * FROM TCCOTACAOITMMOV WHERE CODCOTACAO = '2023.000110' AND CODCOLIGADA = 19