select PFUNC.CODCOLIGADA,
GCOLIGADA.NOMEFANTASIA,
pfunc.CHAPA, 
PFUNC.NOME AS NOME_FUNCIONARIO, 
PFUNCAO.NOME AS NOME_CARGO,
pfunc.codsituacao AS 'SITUAÇÃO',
PFUNC.SALARIO,
PFPERFF.NROPERIODO AS PERIODO,
PFPERFF.ANOCOMP AS ANO_COMP,
PFPERFF.MESCOMP AS MES_COMP,
PFFINANC.CODEVENTO,
PFFINANC.REF AS REFERENCIA,
PFFINANC.HORA,
PEVENTO.DESCRICAO AS EVENTO,
PFFINANC.VALOR 

FROM PFUNC (NOLOCK)
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
LEFT JOIN PFPERFF					(NOLOCK)			ON			(PFPERFF.CHAPA = PFUNC.CHAPA AND PFPERFF.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN PFFINANC					(NOLOCK)			ON			(PFFINANC.CHAPA = PFUNC.CHAPA AND PFFINANC.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN PEVENTO					(NOLOCK)			ON			(PEVENTO.CODIGO = PFFINANC.CODEVENTO AND PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA)
LEFT JOIN GCOLIGADA					(NOLOCK)			ON			(PFUNC.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)

WHERE PFUNC.CODCOLIGADA IN (:P_COLIGADA)
AND PSECAO.CODIGO BETWEEN :P_SECAO_INI AND :P_SECAO_FIM
AND PFPERFF.ANOCOMP IN (:P_ANO)
AND PFPERFF.MESCOMP IN (:P_MES)
AND PEVENTO.CODIGO IN (:P_EVENTO)