SELECT 
PFUNC.CHAPA,
PFUNC.NOME AS NOME_FUNC,
PFUNC.CODSECAO,
PSECAO.DESCRICAO AS NOME_SECAO,
PFUNCAO.NOME AS CARGO,
PPESSOA.DTNASCIMENTO,
PPESSOA.CPF AS CPF,
PPESSOA.CARTEIRATRAB AS CART_TRAB,
PPESSOA.SERIECARTTRAB AS SERIE_CART,
PFUNC.PISPARAFGTS AS PIS,
PFUNC.DATADEMISSAO AS DATA_DEMI,
PFUNC.DTULTIMOMOVIM AS DT_ULTIMO_MOV,
PFUNC.CODAGENCIAPAGTO AS AGENCIA,
PFUNC.CONTAPAGAMENTO AS CONTA,
PFUNC.DATAADMISSAO,
GCOLIGADA.NOMEFANTASIA AS NOME_COLI,
GCOLIGADA.RUA,
GCOLIGADA.CIDADE,
GCOLIGADA.CGC,
PFUNC.SALARIO AS SALARIO

FROM PFUNC (NOLOCK)
LEFT JOIN PFHSTPROV (NOLOCK) ON (PFUNC.CODCOLIGADA = PFHSTPROV.CODCOLIGADA AND PFHSTPROV.CHAPA = PFUNC.CHAPA)
LEFT JOIN PFUNCAO   (NOLOCK) ON (PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO)
LEFT JOIN PSECAO	(NOLOCK) ON (PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA AND PSECAO.CODIGO = PFUNC.CODSECAO)
LEFT JOIN PPESSOA	(NOLOCK) ON (PFUNC.CODPESSOA = PPESSOA.CODIGO)
LEFT JOIN GCOLIGADA (NOLOCK) ON (GCOLIGADA.CODCOLIGADA = PFUNC.CODCOLIGADA)



WHERE  PFUNC.CHAPA = '00024817'
AND PFUNC.CODCOLIGADA = 1
AND PFUNC.CODSITUACAO <> 'D'
AND PFHSTPROV.MES = 11
AND PFHSTPROV.ANO = 2023

/*
WHERE PFUNC.CHAPA = '00021985'
AND PFUNC.CODCOLIGADA = 1
AND PFUNC.CODSITUACAO <> 'D'
AND PFHSTPROV.MES = 11
AND PFHSTPROV.ANO = 2023
AND PFUNC.CODTIPO  <> :CODTIPO*/




GROUP BY 
PFUNC.CHAPA,
PFUNC.NOME,
PFUNC.SALARIO,
PFUNC.SALARIO,
PSECAO.DESCRICAO,
PFUNC.CODSECAO,
GCOLIGADA.NOMEFANTASIA,
GCOLIGADA.RUA,
GCOLIGADA.CIDADE,
GCOLIGADA.CGC,
PFUNC.CODCOLIGADA,
PFUNC.DATAADMISSAO,
PFUNCAO.NOME,
PPESSOA.CARTEIRATRAB ,
PPESSOA.SERIECARTTRAB ,
PFUNC.PISPARAFGTS ,
PFUNC.DATADEMISSAO ,
PFUNC.DTULTIMOMOVIM ,
PFUNC.CODAGENCIAPAGTO ,
PFUNC.CONTAPAGAMENTO,
PPESSOA.CPF,
PPESSOA.DTNASCIMENTO

