DECLARE  @DATA_INI_CRIACAO_MOV AS DATE,
				  @DATA_FIM_CRIACAO_MOV AS DATE;
--				  @CODCCUSTO AS VARCHAR;


SET @DATA_INI_CRIACAO_MOV = '20230101'
SET @DATA_FIM_CRIACAO_MOV = '20231121'
--SET @CODCCUSTO = '1.2006'


SELECT

TMOVORCAMENTO.CODCOLIGADA,
GCOLIGADA.NOMEFANTASIA AS 'NOME COLIGADA',
GFILIAL.CODFILIAL,
GFILIAL.NOMEFANTASIA AS 'NOME FILIAL',
TMOVORCAMENTO.USUARIOCRIACAO 'ULTIMA EDIÇÃO DO MOVIMENTO',
--'CRIAÇÃO'
(ISNULL(MOV_ODC.USUARIOCRIACAO,(ISNULL(MOV_ORIGEM_CONT.USUARIOCRIACAO,TMOV.USUARIOCRIACAO)))) AS 'USUÁRIO CRIAÇÃO DO MOVIMENTO',

CONVERT(VARCHAR,DBO.DTORCAMENTO(TMOV.IDMOV,TMOVORCAMENTO.CODCOLIGADA,TORCAMENTO.CODCCUSTO),103) AS 'DATA AFETA ORÇAMENTO',

TPERIODOORCAMENTO.DESCRICAO AS 'DESCRIÇÃO ORÇAMENTO',
CONVERT (VARCHAR(2),MONTH(TITMPERIODOORCAMENTO.DATAINICIO)) + ' / ' + CONVERT(VARCHAR(4),YEAR(TITMPERIODOORCAMENTO.DATAINICIO)) AS 'PERIODO ORÇAMENTO',
TORCAMENTO.CODCCUSTO AS 'CENTRO DE CUSTO',
GCCUSTO.NOME AS 'NOME CENTRO DE CUSTO',

(ISNULL(TMV_ODC.CODTMV,(ISNULL(TMV_ORIGEM_CONT.CODTMV,TTMV.CODTMV)))) AS CODIGO_MOVIMENTO,

UPPER((ISNULL(TMV_ODC.NOME,(ISNULL(TMV_ORIGEM_CONT.NOME,TTMV.NOME))))) AS 'NOME DO MOVIMENTO',
(ISNULL(MOV_ODC.IDMOV,(ISNULL(MOV_ORIGEM_CONT.IDMOV,TMOV.IDMOV)))) AS 'ID DO MOVIMENTO',

TMOV.CODCFO AS 'CODIGO FORNECEDOR',
FCFO.NOMEFANTASIA AS 'NOME FORNECEDOR',

(CASE WHEN TMOV.CODTMV = '1.2.21' THEN TMOV.DATAEMISSAO
ELSE
(ISNULL(MOV_ODC.DATACRIACAO,(ISNULL(MOV_ORIGEM_CONT.DATACRIACAO,TMOV.DATACRIACAO)))) END) AS DATACRIACAO,

(ISNULL(MOV_ODC.DATAEMISSAO,(ISNULL(MOV_ORIGEM_CONT.DATAEMISSAO,TMOV.DATAEMISSAO)))) AS 'DATA EMISSÃO',
TMOV.DATACRIACAO AS DATA_PROCESSAMENTO,

TTBORCAMENTO.CODTBORCAMENTO AS 'COD NATUREZA ORÇAMENTO',
TTBORCAMENTO.DESCRICAO AS 'NATUREZA ORÇAMENTO',
CAST(TMOVORCAMENTO.VALOROPCIONAL1 AS MONEY) AS 'VALOR COMPROMETIDO',
CAST(TMOVORCAMENTO.VALOROPCIONAL2 AS MONEY) AS 'VALOR EMPENHADO',
CAST(TMOVORCAMENTO.VALORREAL AS MONEY) AS 'VALOR REALIZADO'

FROM TMOVORCAMENTO (NOLOCK)

LEFT JOIN TORCAMENTO (NOLOCK) ON (TMOVORCAMENTO.IDPERIODO = TORCAMENTO.IDPERIODO AND TMOVORCAMENTO.IDORCAMENTO = TORCAMENTO.IDORCAMENTO AND TMOVORCAMENTO.CODCOLIGADA = TORCAMENTO.CODCOLIGADA)
LEFT JOIN GCOLIGADA (NOLOCK) ON (GCOLIGADA.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN TMOV (NOLOCK) ON (TMOVORCAMENTO.IDMOV = TMOV.IDMOV AND TMOV.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN GFILIAL (NOLOCK) ON (GFILIAL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA AND TMOV.CODFILIAL = GFILIAL.CODFILIAL)
LEFT JOIN TPERIODOORCAMENTO (NOLOCK) ON (TPERIODOORCAMENTO.IDPERIODO = TMOVORCAMENTO.IDPERIODO AND TPERIODOORCAMENTO.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA)
LEFT JOIN TITMPERIODOORCAMENTO (NOLOCK) ON (TMOVORCAMENTO.CODCOLIGADA = TITMPERIODOORCAMENTO.CODCOLIGADA AND TMOVORCAMENTO.IDPERIODO = TITMPERIODOORCAMENTO.IDPERIODO AND TITMPERIODOORCAMENTO.IDITMPERIODO = TMOVORCAMENTO.IDITMPERIODO)
LEFT JOIN TTBORCAMENTO (NOLOCK) ON (TORCAMENTO.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO AND TORCAMENTO.CODCOLTBORCAMENTO = TTBORCAMENTO.CODCOLIGADA)
LEFT JOIN GCCUSTO (NOLOCK) ON (TORCAMENTO.CODCCUSTO = GCCUSTO.CODCCUSTO AND TORCAMENTO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN TTMV (NOLOCK) ON (TMOV.CODTMV = TTMV.CODTMV AND TMOV.CODCOLIGADA = TTMV.CODCOLIGADA)
LEFT JOIN TITMTMV (NOLOCK) ON (TITMTMV.CODCOLIGADA = TTMV.CODCOLIGADA AND TITMTMV.CODTMV = TTMV.CODTMV)
LEFT JOIN FCFO (NOLOCK) ON (FCFO.CODCFO = TMOV.CODCFO AND FCFO.CODCOLIGADA = TMOV.CODCOLCFO)

-- Movimento anterior a TMOV
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOV.IDMOV = TMOVRELAC.IDMOVDESTINO AND TMOV.CODCOLIGADA = TMOVRELAC.CODCOLDESTINO)
LEFT JOIN TMOV MOV_ORIGEM_CONT (NOLOCK) ON (MOV_ORIGEM_CONT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOV_ORIGEM_CONT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM AND MOV_ORIGEM_CONT.CODTMV NOT IN ('1.1.34','1.1.20','1.1.18','1.1.21','1.1.51','1.2.29','1.2.30'))
LEFT JOIN TITMTMV TITM_ORIGEM_CONT (NOLOCK) ON (TITM_ORIGEM_CONT.CODTMV = MOV_ORIGEM_CONT.CODTMV AND TITM_ORIGEM_CONT.CODCOLIGADA = MOV_ORIGEM_CONT.CODCOLIGADA AND TITM_ORIGEM_CONT.HABILITAORCAMENTO = 1)
LEFT JOIN TTMV TMV_ORIGEM_CONT (NOLOCK) ON (TMV_ORIGEM_CONT.CODTMV = TITM_ORIGEM_CONT.CODTMV AND TMV_ORIGEM_CONT.CODCOLIGADA = TITM_ORIGEM_CONT.CODCOLIGADA)

-- Ordem de compra gerada no 1.1.35
LEFT JOIN TMOVRELAC ODC (NOLOCK) ON (MOV_ORIGEM_CONT.IDMOV = ODC.IDMOVDESTINO AND MOV_ORIGEM_CONT.CODCOLIGADA = ODC.CODCOLDESTINO)
LEFT JOIN TMOV MOV_ODC (NOLOCK) ON (ODC.IDMOVORIGEM = MOV_ODC.IDMOV AND ODC.CODCOLORIGEM = MOV_ODC.CODCOLIGADA AND MOV_ODC.CODTMV = '1.1.35')
LEFT JOIN TTMV TMV_ODC (NOLOCK) ON (TMV_ODC.CODTMV = MOV_ODC.CODTMV AND TMV_ODC.CODCOLIGADA = MOV_ODC.CODCOLIGADA)

WHERE

TMOV.STATUS <> 'C'
--AND TORCAMENTO.CODCCUSTO = @CODCCUSTO
AND (CASE WHEN TMOV.CODTMV = '1.2.21' THEN TMOV.DATAEMISSAO
ELSE
(ISNULL(MOV_ODC.DATACRIACAO,(ISNULL(MOV_ORIGEM_CONT.DATACRIACAO,TMOV.DATACRIACAO)))) END)
 BETWEEN @DATA_INI_CRIACAO_MOV AND @DATA_FIM_CRIACAO_MOV
 

GROUP BY 
 TMOVORCAMENTO.CODCOLIGADA
,GCOLIGADA.NOMEFANTASIA
,GFILIAL.CODFILIAL
,GFILIAL.NOMEFANTASIA
,TMOVORCAMENTO.USUARIOCRIACAO
,MOV_ODC.USUARIOCRIACAO
,MOV_ORIGEM_CONT.USUARIOCRIACAO
,TMOV.USUARIOCRIACAO
,TMOV.DATAEXTRA2
,TPERIODOORCAMENTO.DESCRICAO
,TITMPERIODOORCAMENTO.DATAINICIO,TITMPERIODOORCAMENTO.DATAINICIO
,TORCAMENTO.CODCCUSTO
,GCCUSTO.NOME 
,TMV_ODC.CODTMV
,TMV_ORIGEM_CONT.CODTMV
,TTMV.CODTMV
,TMV_ODC.NOME
,TMV_ORIGEM_CONT.NOME
,TTMV.NOME
,MOV_ODC.IDMOV
,MOV_ORIGEM_CONT.IDMOV
,TMOV.IDMOV
,TMOV.CODCFO
,FCFO.NOMEFANTASIA
,TMOV.CODTMV
,TMOV.DATAEMISSAO
,TMOV.DATACRIACAO
,MOV_ODC.DATACRIACAO
,MOV_ORIGEM_CONT.DATACRIACAO
,MOV_ODC.DATAEMISSAO
,MOV_ORIGEM_CONT.DATAEMISSAO
,TMOV.DATAEMISSAo
,TTBORCAMENTO.CODTBORCAMENTO
,TTBORCAMENTO.DESCRICAO
,TMOVORCAMENTO.VALOROPCIONAL1
,TMOVORCAMENTO.VALOROPCIONAL2
,TMOVORCAMENTO.VALORREAL