DECLARE @CODCOLIGADA AS INT = 10,
		@DATA_INI AS DATE = '20231001',
		@DATA_FIM AS DATE = '20240111',
		@COBRANCA AS VARCHAR = 'C1123';


SELECT 
FLAN.CODCOLIGADA,
GFILIAL.NOMEFANTASIA AS NOME_FILIAL,
XEMPREENDIMENTO.NOME AS NOME_EMPREENDIMENTO, 
FLAN.IDLAN AS IDLAN,
FCFO.CGCCFO AS CNPJCPF,
GFILIAL.CGC AS CNPJ_EMPREENDIMENTO,
FCFO.NOMEFANTASIA AS NOME_CLIENTE,
XTIPOPARCELA.DSC_TIPO_PARC AS TIPO_PARCELA,
FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy') AS DATA_VENCIMENTO,
FORMAT(FLAN.DATABAIXA, 'dd/MM/yyyy') AS DATA_BAIXA,
CONVERT(DECIMAL(10,2), FLAN.VALORORIGINAL) AS VALOR_ORIGINAL,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORJUROS) AS VALORJUROS,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORMULTA) AS VALORMULTA,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORDESCONTO) AS VALORDESCONTO, 
CONVERT (DECIMAL(10,2), FLANBAIXA.HONORARIOS) AS HONORARIOS,
CONVERT (DECIMAL(10,2), FLANBAIXA.VALORBAIXA)AS VALOR_BAIXADO,
CONVERT(DECIMAL(10,2), (FLAN.VALORORIGINAL)
			+ FLANBAIXA.HONORARIOS 
			+ FLANBAIXA.VALORJUROS 
			+ FLANBAIXA.VALORMULTA 
			- FLANBAIXA.VALORDESCONTO 
			+ (SELECT ISNULL(SUM(FLANINTEGRACAO.VALOR),0) AS VALOR
				FROM FLAN AS FLAN2(NOLOCK)
				JOIN FLANINTEGRACAO		(NOLOCK) ON (FLAN2.IDLAN = FLANINTEGRACAO.IDLAN AND FLAN2.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA)
				JOIN FLANINTEGRACAODEF	(NOLOCK) ON (FLANINTEGRACAO.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND FLANINTEGRACAO.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
				WHERE FLAN2.IDLAN = FLAN.IDLAN
				AND FLAN2.CODCOLIGADA = FLAN.CODCOLIGADA
				AND FLANINTEGRACAODEF.DESCRICAO IN('CM ANTES ENTREGA', 'CM APOS ENTREGA', 'Taxa Juros Antes Entrega', 'Taxa Juros Apos Entrega-106', 'Taxa Juros Apos Entrega','ADIANTAMENTO REGISTRO','DESCONTO'))
		)AS VALOR_SOMADO,
CONVERT(VARCHAR(MAX),FLANCOMPL.COBRANCA) AS COBRANCA
 
FROM FLAN (NOLOCK)
 			LEFT JOIN FLANCOMPL					(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA )
			LEFT JOIN GFILIAL					(NOLOCK) ON (FLAN.CODCOLIGADA = GFILIAL.CODCOLIGADA AND FLAN.CODFILIAL = GFILIAL.CODFILIAL)
		    LEFT JOIN XVENDAPARCELA				(NOLOCK) ON (XVENDAPARCELA.IDLAN = FLAN.IDLAN AND XVENDAPARCELA.CODCOLLAN = FLAN.CODCOLIGADA)
			LEFT JOIN XTIPOPARCELA				(NOLOCK) ON (XTIPOPARCELA.COD_TIPO_PARC = XVENDAPARCELA.CODTIPOPARC)
			LEFT JOIN XVENDA					(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA)
			LEFT JOIN XEMPREENDIMENTO			(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR)				
--			LEFT JOIN GFILIAL					(NOLOCK) ON (XEMPREENDIMENTO.CODFILIAL = GFILIAL.CODFILIAL AND XEMPREENDIMENTO.CODCOLIGADA = GFILIAL.CODCOLIGADA)
			LEFT JOIN FCFO						(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO AND FLAN.CODCOLCFO = FCFO.CODCOLIGADA)
			LEFT JOIN ( SELECT 
							FLANBAIXA.IDLAN,
							FLANBAIXA.CODCOLIGADA,
							ISNULL(SUM(CONVERT (DECIMAL(10,2), FLANBAIXA.VALORJUROS)),0) AS VALORJUROS,
							ISNULL(SUM(CONVERT (DECIMAL(10,2), FLANBAIXA.VALORMULTA)),0) AS VALORMULTA,
							ISNULL(SUM(CONVERT (DECIMAL(10,2), FLANBAIXA.VALORDESCONTO)),0) AS VALORDESCONTO, 
							ISNULL(SUM(CONVERT (DECIMAL(10,2), FLANBAIXA.VALOROP8)),0) AS HONORARIOS,
							ISNULL(SUM(CONVERT(DECIMAL(10,2), (FLANBAIXA.VALORORIGINAL))),0) AS VALORORIGINAL,
							ISNULL(SUM(CONVERT (DECIMAL(10,2), FLANBAIXA.VALORBAIXA)),0) AS VALORBAIXA
							FROM FLANBAIXA (NOLOCK)
							  WHERE FLANBAIXA.STATUS = 0					
							
							GROUP BY FLANBAIXA.IDLAN,
										FLANBAIXA.CODCOLIGADA
						) AS FLANBAIXA ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)

WHERE FLAN.CODCOLIGADA IN (@CODCOLIGADA) 
AND FLAN.DATABAIXA BETWEEN @DATA_INI  AND @DATA_FIM
AND CONVERT(VARCHAR(MAX),FLANCOMPL.COBRANCA) IN (@COBRANCA)
--AND FLANINTEGRACAODEF.DESCRICAO NOT IN ('CM APOS ENTREGA', 'CM ANTES ENTREGA', 'TAXA JUROS APOS ENTREGA', 'Taxa Juros Apos Entrega-106', 'Taxa Juros Antes Entrega')
--AND FLAN.IDLAN = @IDLAN