SELECT DISTINCT 
--PFPERFF.DESCRICAO,
PFPERFF.NROPERIODO,
PFFINANC.CODEVENTO,
PEVENTO.PROVDESCBASE,
PFFINANC.REF,
PEVENTO.DESCRICAO,
(CASE WHEN PROVDESCBASE = 'P' THEN PFFINANC.VALOR ELSE 0 END) AS PROVENTOS,
(CASE WHEN PROVDESCBASE = 'D' THEN PFFINANC.VALOR ELSE 0 END) AS DESCONTOS,
PFFINANC.DTPAGTO

/*PFFINANC.VALOR
*/

FROM PFFINANC
LEFT JOIN PFPERFF  (NOLOCK) ON (PFFINANC.CODCOLIGADA = PFPERFF.CODCOLIGADA AND PFFINANC.CHAPA = PFPERFF.CHAPA AND PFPERFF.NROPERIODO = PFFINANC.NROPERIODO)
LEFT JOIN PEVENTO	(NOLOCK) ON (PEVENTO.CODCOLIGADA = PFFINANC.CODCOLIGADA AND PEVENTO.CODIGO = PFFINANC.CODEVENTO)
/*
WHERE
PFFINANC.CHAPA = '00024817'
AND PFFINANC.CODCOLIGADA = 1
AND PFFINANC.ANOCOMP = 2023
AND PFFINANC.MESCOMP = 11
AND PFPERFF.DESCRICAO IS NOT NULL
AND PROVDESCBASE IN ('P', 'D')
AND PEVENTO.CODIGO NOT IN ('0032', '0172', '0174', '0654', '0655', '0682', '0688', '0722')
*/
WHERE
PFFINANC.CHAPA =:CHAPA
AND PFFINANC.CODCOLIGADA = :$CODCOLIGADA
AND PFFINANC.MESCOMP = :MES
AND PFFINANC.ANOCOMP =:ANO
AND PEVENTO.CODIGO NOT IN ('0032', '0172', '0174', '0654', '0655', '0682', '0688', '0722')
AND PFPERFF.DESCRICAO IS NOT NULL
AND PROVDESCBASE IN ('P', 'D')

ORDER BY 1, 3
