/* RELATÓRIO CRIADO PARA ATENDER O CHAMADO 0123-001051 ONDE É NECESSÁRIO QUE O RELATÓRIO GERE DE ACORDO COM O PLANO(PALAVRA CHAVE DO EVENTO) */

SELECT 

PSECAO.CODIGO + ' - ' + PSECAO.DESCRICAO AS QUEBRA$,
PFUNC.CHAPA,
PFUNC.NOME,
SUM (PFHSTASSMED.VALOR) AS VALOR_HISTORICO,

(SELECT SUM (PFFINANC.VALOR)
FROM PFFINANC 
LEFT JOIN	PEVENTO AS EVENTO_PFFINANC		(NOLOCK) ON (EVENTO_PFFINANC.CODIGO = PFFINANC.CODEVENTO AND EVENTO_PFFINANC.CODCOLIGADA = PFFINANC.CODCOLIGADA)

WHERE PFFINANC.CHAPA = PFUNC.CHAPA 
AND PFFINANC.CODCOLIGADA = PFUNC.CODCOLIGADA 
AND PFFINANC.ANOCOMP = PFHSTASSMED.ANOCOMP
AND PFFINANC.CODEVENTO IN ('0014','0114','0706','0707','0708','0709','0714','0404','0668','0666','0667','0710','0711','0712','0713')
/* AND PFFINANC.CODEVENTO IN ('0014','0114','0404','0582','0246','0215','0666','0667','0668','0706','0707','0708','0709','0714') */
AND EVENTO_PFFINANC.DESCRICAO LIKE '%'+ :DESCRICAO_PLANO + '%') 
-
ISNULL((SELECT SUM (PFFINANC.VALOR)
FROM PFFINANC 
WHERE PFFINANC.CHAPA = PFUNC.CHAPA 
AND PFFINANC.CODCOLIGADA = PFUNC.CODCOLIGADA 
AND PFFINANC.ANOCOMP = PFHSTASSMED.ANOCOMP
/* Evento 0409 - = Reembolso assistencia medica */
AND PFFINANC.CODEVENTO ='0409'),0)  AS VALOR_FOLHA





FROM PFUNC 
LEFT JOIN	PFHSTASSMED (NOLOCK) ON (PFHSTASSMED.CHAPA = PFUNC.CHAPA AND PFHSTASSMED.CODCOLIGADA = PFUNC.CODCOLIGADA)
INNER JOIN  PSECAO		(NOLOCK) ON (PSECAO.CODIGO = PFUNC.CODSECAO AND PSECAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
LEFT JOIN	PEVENTO		(NOLOCK) ON (PEVENTO.CODIGO = PFHSTASSMED.CODEVENTO AND PEVENTO.CODCOLIGADA = PFHSTASSMED.CODCOLIGADA)

WHERE	PFHSTASSMED.ANOCOMP = :ANO
AND		PFUNC.CODSECAO BETWEEN :SECAO_INI AND :SECAO_FIN
AND 	PFUNC.CODCOLIGADA = :$CODCOLIGADA 
AND		(PFUNC.DATADEMISSAO IS NULL OR (PFUNC.TIPODEMISSAO <> '5'))
AND PEVENTO.DESCRICAO LIKE '%'+ :DESCRICAO_PLANO + '%'





GROUP BY
PSECAO.CODIGO,
PSECAO.DESCRICAO,
PFUNC.CODCOLIGADA,
PFUNC.CHAPA,
PFUNC.NOME,
PFHSTASSMED.ANOCOMP

ORDER BY QUEBRA$, PFUNC.NOME