SELECT  
    Subquery.CODCOLIGADA,
	Subquery.NOME_COLIGADA,
	Subquery.CGC AS CNPJ_EMPREENDIMENTO,
	Subquery.NOME_FILIAL,
    Subquery.NOME_CLIENTE,
    Subquery.CNPJCPF AS 'CNPJ/CPF CLIENTE',
    Subquery.IDLAN,
	Subquery.TIPO_PARCELA,
    Subquery.DATA_VENCIMENTO,
    Subquery.DATA_BAIXA,
	Subquery.VALORORIGINAL,
    Subquery.VALORJUROS,
    Subquery.VALORMULTA,
    Subquery.VALORDESCONTO,
    Subquery.HONORARIOS,
    Subquery.VALOR_BAIXADO,
    Subquery.COBRANCA
FROM (
				SELECT DISTINCT
					GCOLIGADA.CODCOLIGADA,
					(SELECT TOP 1 CGC FROM GFILIAL (NOLOCK) WHERE GFILIAL.CODFILIAL = FLAN.CODFILIAL) AS CGC,
					(SELECT TOP 1 NOME FROM GFILIAL (NOLOCK) WHERE GFILIAL.CODFILIAL = FLAN.CODFILIAL) AS NOME_FILIAL,
					FLANBAIXA.IDBAIXA AS IDLAN,
					FCFO.CGCCFO AS CNPJCPF,
					(
						SELECT TOP 1 FILI1.CGC 
						FROM GFILIAL AS FILI1(NOLOCK)
						WHERE FILI1.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND FILI1.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA
						ORDER BY FILI1.CGC DESC
					) AS CNPJ_EMPREENDIMENTO,
					GCOLIGADA.NOME AS NOME_COLIGADA,
					FCFO.NOMEFANTASIA AS NOME_CLIENTE,
						   FLANINTEGRACAODEF.DESCRICAO AS TIPO_PARCELA,
						(
							SELECT TOP 1 FORMAT(FLAN1.DATAVENCIMENTO, 'dd/MM/yyyy')
							FROM FLAN AS FLAN1(NOLOCK)
							WHERE FLAN1.IDLAN = FLAN.IDLAN AND FLAN1.CODCOLIGADA = FLAN.CODCOLIGADA
						)AS DATA_VENCIMENTO,
						(
							SELECT TOP 1 FORMAT(BAIXA.DATABAIXA, 'dd/MM/yyyy')
							FROM FLANBAIXA AS BAIXA (NOLOCK)
							WHERE BAIXA.IDBAIXA = FLANBAIXA.IDBAIXA AND BAIXA.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
						)AS DATA_BAIXA,
					(
							SELECT TOP 1 SUM(CONVERT (DECIMAL(10,2), FLAN2.VALORORIGINAL) + CONVERT (DECIMAL(10,2), FLANINTEGRACAO.VALOR)) AS SOMA
							FROM FLANBAIXA AS FLAN2(NOLOCK)
							JOIN FLANINTEGRACAO		(NOLOCK) ON (FLAN2.IDLAN = FLANINTEGRACAO.IDLAN AND FLAN2.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA)
							JOIN FLANINTEGRACAODEF (NOLOCK) ON (FLANINTEGRACAO.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND FLANINTEGRACAO.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
							WHERE FLAN2.IDLAN = FLAN.IDLAN
							AND FLAN2.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
							AND FLANINTEGRACAODEF.DESCRICAO IN('CM ANTES ENTREGA', 'CM APOS ENTREGA','Adiantamento Escritura/ITBI', 'SINAL', 'Taxa Juros Antes Entrega', 'Taxa Juros Apos Entrega-106', 'Juros de Mutuarios', 'Taxa Juros Apos Entrega')
							) AS VALORORIGINAL,
								(
								 SELECT TOP 1 SUM(CONVERT(DECIMAL(10,2), FB1.VALORJUROS)) AS SOMA_JUROS
								 FROM FLANBAIXA AS FB1
								 WHERE FB1.IDLAN = FLAN.IDLAN
								 AND FB1.CODCOLIGADA = FLAN.CODCOLIGADA) AS VALORJUROS,
					/*CONVERT (DECIMAL(10,2), FLANBAIXA.VALORJUROS) AS VALORJUROS,*/
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORMULTA) AS VALORMULTA,
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALORDESCONTO) AS VALORDESCONTO, 
					CONVERT (DECIMAL(10,2), FLANBAIXA.VALOROP8) AS HONORARIOS,
					(SELECT TOP 1 SUM(CONVERT (DECIMAL(10,2), TOTAL_PARCIAL.VALORBAIXA)) FROM FLANBAIXA AS TOTAL_PARCIAL WHERE TOTAL_PARCIAL.IDLAN = FLANBAIXA.IDLAN AND FLANBAIXA.CODCOLIGADA = TOTAL_PARCIAL.CODCOLIGADA )AS VALOR_BAIXADO,
					CONVERT(VARCHAR,FLANCOMPL.COBRANCA) AS COBRANCA

			 FROM FLAN (NOLOCK)

			LEFT JOIN GCOLIGADA									(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FCFO											(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO)
			LEFT JOIN FLANBAIXA									(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FLANINTEGRACAO						(NOLOCK) ON (FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FLANINTEGRACAODEF					(NOLOCK) ON (FLANINTEGRACAO.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND FLANINTEGRACAO.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
			LEFT JOIN FLANCOMPL									(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA )
			LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
			LEFT JOIN XVENDA										(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
			LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
			
			WHERE GCOLIGADA.CODCOLIGADA IN (@CODCOLIGADA) AND 
			FLANBAIXA.DATABAIXA BETWEEN @DATA_INI  AND @DATA_FIM
			AND CONVERT(VARCHAR,FLANCOMPL.COBRANCA) IN (@COBRANCA)
			AND FLANINTEGRACAODEF.DESCRICAO NOT IN ('CM APOS ENTREGA', 'CM ANTES ENTREGA', 'TAXA JUROS APOS ENTREGA', 'Taxa Juros Apos Entrega-106', 'Taxa Juros Antes Entrega')
			/*AND FLAN.IDLAN = '49296'*/


) AS Subquery

GROUP BY 
    Subquery.CODCOLIGADA
	,Subquery.NOME_COLIGADA
	,Subquery.CGC
	,Subquery.NOME_FILIAL
	,Subquery.NOME_CLIENTE
	,Subquery.CNPJCPF
    ,Subquery.IDLAN
	,Subquery.TIPO_PARCELA
    ,Subquery.DATA_VENCIMENTO
	,Subquery.DATA_BAIXA,
	Subquery.VALORORIGINAL,
    Subquery.VALORJUROS,
    Subquery.VALORMULTA,
    Subquery.VALORDESCONTO,
    Subquery.HONORARIOS,
    Subquery.VALOR_BAIXADO,
    Subquery.COBRANCA

--ORDER BY Subquery.NOME_CLIENTE DESC
