SELECT * 
FROM 
(
SELECT
FLAN.IDLAN,
FLANRATCCU.CODCCUSTO,
GCCUSTO.NOME 'NOME_CDC',
 
/*INICIO VALOR LIQUIDO*/
CAST(
(FLAN.VALORORIGINAL -(
FLAN.VALORDESCONTO +
FLAN.VALORADIANTAMENTO +
FLAN.VALORDEVOLUCAO +
FLAN.VALOROP1 +
FLAN.VALOROP2 +
FLAN.VALOROP3 +
FLAN.VALOROP5 +
FLAN.VALORINSS +
FLAN.VALORIRRF +
FLAN.VALORSESTSENAT+
DBO.VALOR_IMPOSTOS_FLUXUS(FLAN.CODCOLIGADA, FLAN.IDLAN)
)+
FLAN.VALOROP4 +
FLAN.VALORJUROS +
FLAN.VALORMULTA)* ISNULL(FLANRATCCU.PERCENTUAL,100)/100 AS MONEY) AS 'VALOR_LIQUIDO',
/*FIM VALOR LIQUIDO*/
 
FLAN.CODTB2FLX  'CLASSI',
FTB2.DESCRICAO AS DESC_CLASS_FIN,
FLAN.DATABAIXA,
FCFO.CODCFO,
FCFO.NOME,
FCFO.NOMEFANTASIA,
FCFO.CGCCFO,
 
 
 
/* FOI UTILIZADO SUB SELECT PARA EVITAR DUPLICIDADE DE INFORMAÇÕES DEVIDO A AGRUPAMENTO DE LANÇAMENTOS DE ORIGEM */
 
 
 
ISNULL((SELECT MAX (ORIGEM.IDMOV) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA),'') AS ORIGEM_IDMOV,
 
 
 
ISNULL((SELECT MAX (ORIGEM.USUARIOCRIACAO) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA), FLAN.USUARIOCRIACAO) AS ORIGEM_USUARIOCRIACAO,
 
 
 
ISNULL((SELECT MAX (ORIGEM.DATACRIACAO) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA),FLAN.DATACRIACAO) AS ORIGEM_DATACRIACAO,
 
 
 
(SELECT MAX (TMOVAPROVA.CODUSUARIO) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
LEFT JOIN TMOVAPROVA (NOLOCK) ON (TMOVAPROVA.IDMOV = ORIGEM.IDMOV AND TMOVAPROVA.CODCOLIGADA = ORIGEM.CODCOLIGADA AND TMOVAPROVA.TIPOAPROVACAO = 1)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA) AS ORIGEM_USUARIOAPROVACAO,
 
 
 
(SELECT MAX (TMOVAPROVA.DATAAPROVACAO) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
LEFT JOIN TMOVAPROVA (NOLOCK) ON (TMOVAPROVA.IDMOV = ORIGEM.IDMOV AND TMOVAPROVA.CODCOLIGADA = ORIGEM.CODCOLIGADA AND TMOVAPROVA.TIPOAPROVACAO = 1)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA) AS ORIGEM_DATAAPROVACAO,
 
 
 
ISNULL((SELECT MAX (ORIGEM.CODTMV) FROM TMOVRELAC
LEFT JOIN TMOV ORIGEM (NOLOCK) ON (ORIGEM.IDMOV = TMOVRELAC.IDMOVORIGEM AND ORIGEM.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA),'') AS ORIGEM_CODTMV,
 
 
 
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
FLAN.NUMERODOCUMENTO,
CASE WHEN (SELECT COUNT (IDLAN) FROM FLANRATCCU WHERE CODCOLIGADA = FLAN.CODCOLIGADA AND IDLAN=FLAN.IDLAN) > 1 THEN 'RATEIO' ELSE ' ' END AS RATEIO,
 
 
 
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLANRATCCU.HISTORICO),char(13) + char(10),' '),';',' ') AS FLANRATCCU_HISTORICO,
REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLAN.HISTORICO),char(13) + char(10),' '),';',' ') AS FLAN_HISTORICO,
 
 
 
FLAN.IDMOV,
FTB2_DEF.CODTB2FLX,
FTB2_DEF.DESCRICAO,
FLAN.DATAEMISSAO,
(FLAN.VALORORIGINAL * FLANRATCCU.PERCENTUAL / 100) AS VALOR_ORIGINAL,
FCFOCOMPL.QUALIFICACAO_CLIFOR

/* ITENS DO MOVIMENTO INICIO */
/*TITMMOV.NSEQITMMOV AS 'SEQUENCIAL',
TITMMOVRATCCU.CODCCUSTO AS 'CDC_ITEM',
TPRD.CODIGOPRD AS 'PRODUTO', 
TPRD.DESCRICAO AS 'DESC_PRODUTO',
TITMMOV.QUANTIDADE,

TITMMOVRATCCU.VALOR,
TITMMOV.VALORBRUTOITEM*/
/* ITENS DO MOVIMENTO FINAL */ 
 
 
FROM FLAN (NOLOCK)
LEFT JOIN FTB5    (NOLOCK) ON (FLAN.CODCOLIGADA=FTB5.CODCOLIGADA AND FLAN.CODTB5FLX=FTB5.CODTB5FLX)
LEFT JOIN FCFO    (NOLOCK) ON (FLAN.CODCOLCFO=FCFO.CODCOLIGADA AND FLAN.CODCFO=FCFO.CODCFO)
LEFT JOIN FCFOCOMPL   (NOLOCK) ON (FLAN.CODCOLCFO = FCFOCOMPL.CODCOLIGADA AND FLAN.CODCFO = FCFOCOMPL.CODCFO)
LEFT JOIN FCFODEF   (NOLOCK) ON (FCFODEF.CODCFO = FCFO.CODCFO AND FCFODEF.CODCOLCFO = FCFO.CODCOLIGADA AND FCFODEF.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FTB2 AS FTB2_DEF  (NOLOCK) ON (FCFODEF.CODCOLIGADA=FTB2_DEF.CODCOLIGADA AND FCFODEF.CODTB2FLX=FTB2_DEF.CODTB2FLX)
LEFT JOIN FTB2    (NOLOCK) ON (FLAN.CODCOLIGADA=FTB2.CODCOLIGADA AND FLAN.CODTB2FLX=FTB2.CODTB2FLX)
LEFT JOIN FLANRATCCU  (NOLOCK) ON (FLAN.CODCOLIGADA = FLANRATCCU.CODCOLIGADA AND FLAN.IDLAN = FLANRATCCU.IDLAN/* AND FLAN.CODCCUSTO = FLANRATCCU.CODCCUSTO*/)
LEFT JOIN GCCUSTO   (NOLOCK) ON (GCCUSTO.CODCCUSTO = FLANRATCCU.CODCCUSTO AND GCCUSTO.CODCOLIGADA = FLANRATCCU.CODCOLIGADA)
LEFT JOIN TMOV    (NOLOCK) ON (TMOV.IDMOV = FLAN.IDMOV AND TMOV.CODCOLIGADA = FLAN.CODCOLIGADA)

/* ITENS DO MOVIMENTO INICIO */
/*LEFT JOIN TITMMOV   (NOLOCK) ON (TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV)
LEFT JOIN TITMMOVRATCCU  (NOLOCK) ON (TITMMOVRATCCU.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TITMMOVRATCCU.IDMOV = TITMMOV.IDMOV AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV)
INNER JOIN TPRD    (NOLOCK) ON (TITMMOV.CODCOLIGADA = TPRD.CODCOLIGADA AND TITMMOV.IDPRD = TPRD.IDPRD)*/
/* ITENS DO MOVIMENTO FINAL*/ 
 
 
WHERE
FLAN.CODCOLIGADA=1
AND FLAN.PAGREC = 2
/*AND FLANRATCCU.CODCCUSTO BETWEEN '3.0052' AND '3.0052'*/
--AND GCCUSTO.CODCCUSTO IN ('1.1003.01', '1.1003.02', '1.1003.03')
/*OR TITMMOVRATCCU.CODCCUSTO IN ('1.1003.01', '1.1003.02', '1.1003.03')*/
AND FLAN.CODTDO <> '0025'
AND FLAN.NFOUDUP <> 1
AND CAST(FLAN.DATABAIXA AS DATE) >= '20170101'
AND FLAN.CODCXA <> '1'
/*AND FLAN.IDLAN IN (4344784)
*/

 ) AS GRUPO


 ORDER BY GRUPO.CODTB2FLX,
 GRUPO.NOME
 

 