DECLARE @EMPREENDIMENTO INT, @NUMVENDA INT, @CODCOLIGADA INT, @DATA_BASE_D AS DATETIME, @MULTA AS DECIMAL(10,5), @MORA AS DECIMAL(10,10)

SET @DATA_BASE_D = GETDATE()
SET @MULTA='0.02'
SET @MORA='0.033333333'

SET @NUMVENDA = ISNULL((	
					SELECT MAX(X.NUM_VENDA) FROM XVENDA AS X (NOLOCK) 
					LEFT JOIN FCFO AS F (NOLOCK)   ON (F.CODCOLIGADA=X.CODCOLCFO AND F.CODCFO=X.CODCFO)
					WHERE F.NOME LIKE '%' + @NOME_CPF  + '%'  OR dbo.TRAZ_NUMEROS(F.CGCCFO) = @NOME_CPF
					AND X.COD_SIT_VENDA NOT IN (10,60,61,62)
				),0)

SET @EMPREENDIMENTO = ISNULL((SELECT XVENDA.COD_PESS_EMPR FROM XVENDA WHERE XVENDA.NUM_VENDA = @NUMVENDA),0)

SET @CODCOLIGADA = ISNULL((SELECT XVENDA.CODCOLIGADA FROM XVENDA WHERE XVENDA.NUM_VENDA = @NUMVENDA),0)

SELECT 

SGI.CODCOLIGADA,
GCOLIGADA.NOME AS NOME_COLIGADA				 
,SGI.EMP
,XEMPREENDIMENTO.NOME AS NOME_EMPRE
,SGI.NUM_VENDA
,XVENDA.DAT_VENDA
,SGI.QUADRA AS UND
,SGI.LOTE
,SGI.TIPO_PAG
,SGI.NUMERO
,SGI.CLIENTE
,SGI.VENCIMENTO
,SGI.DATADORECEBIMENTO
,SGI.VALORRECEBIDO AS VALOR
,SGI.IDLAN


FROM DBO.REL_SGI_RECEBIDAS (@CODCOLIGADA, @NUMVENDA, @EMPREENDIMENTO,'%%','19900101',GETDATE()) AS SGI
INNER JOIN XVENDA			(NOLOCK) ON (XVENDA.CODCOLIGADA=SGI.CODCOLIGADA AND XVENDA.NUM_VENDA=SGI.NUM_VENDA AND XVENDA.COD_PESS_EMPR=SGI.EMP)
INNER JOIN XEMPREENDIMENTO	(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = SGI.EMP)
INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
INNER JOIN XMODALIDADEVENDA (NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
INNER JOIN XSITUACAOVENDA   (NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)

WHERE SGI.VALORHIST IS NOT NULL
AND SGI.VALORRECEBIDO > 0
AND SGI.COD_TIPO_PARC NOT IN(90)


UNION ALL


SELECT     
		GCOLIGADA.CODCOLIGADA,
		GCOLIGADA.NOME,

     'EMPREENDIMENTO'= XEMPREENDIMENTO.COD_PESS_EMPR
     ,'NOME_EMPREENDIMENTO' = XEMPREENDIMENTO.NOME 
	  ,XVENDA.NUM_VENDA
,XVENDA.DAT_VENDA
     ,'BL/QD'=XITEMVENDA.NUM_UNID 
     ,'APTO/LOTE'=XITEMVENDA.NUM_SUB_UNID 
     ,'TIPO_PAGTO'=XTIPOPARCELA.DSC_TIPO_PARC
     ,'PARCELA'=XVENDAPARCELA.NUMPARC
     ,'CLIENTE'=UPPER (FCFO.NOME) 
     ,'VENCIMENTO'= FLAN.DATAVENCIMENTO
	 ,NULL AS PAGAMENTO

     

			
	,VALOR_CORRIGIDO=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) + FLAN.VALORJUROS
	+(dbo.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))
	+(dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) 
	-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
	INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
	WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
	-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO 
	INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
	WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (select IDCAMPO from dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
	-VALORDESCONTO
	,FLAN.IDLAN
     

FROM			    XVENDA (NOLOCK)
					LEFT JOIN  XVENDAPARCELA (NOLOCK)  ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
					LEFT JOIN XEMPREENDIMENTO (NOLOCK)   ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
					LEFT JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
					LEFT JOIN FCFO (NOLOCK)   ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
					LEFT JOIN XITEMVENDA (NOLOCK)   ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
					LEFT JOIN XTIPOPARCELA (NOLOCK)   ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
					LEFT JOIN FLAN (NOLOCK)   ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
					LEFT JOIN FTB2 (NOLOCK) on (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
					LEFT JOIN XMODALIDADEVENDA (NOLOCK)   ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)


WHERE				FLAN.STATUSLAN IN (0,4)
					--AND FCFO.NOME LIKE '%' + 'Adelia Vieira Santos' + '%' 
					AND XVENDA.NUM_VENDA IN (@NUMVENDA)
					AND XVENDAPARCELA.CODTIPOPARC NOT IN(90)

ORDER BY VENCIMENTO