
DECLARE @CONT INT = 0
	DECLARE @TAMANHO INT = (SELECT COUNT (*) FROM XEMPREENDIMENTO (NOLOCK) WHERE COD_PESS_EMPR IN (@EMPREENDIMENTO))
	DECLARE @RESULTADO VARCHAR(MAX) =''

	WHILE @CONT < @TAMANHO
		BEGIN
			SET @RESULTADO = @RESULTADO + (
											SELECT CONVERT (VARCHAR(10),COD_PESS_EMPR) FROM 
												(
													SELECT 
													ROW_NUMBER() OVER (ORDER BY XEMPREENDIMENTO.COD_PESS_EMPR) AS ORDEM,
													COD_PESS_EMPR
													FROM XEMPREENDIMENTO (NOLOCK) 
													WHERE COD_PESS_EMPR IN (@EMPREENDIMENTO)
	
												) AS GRUPO
												WHERE GRUPO.ORDEM = @CONT + 1
										) + ';'


			SET @CONT = @CONT + 1
		END

SELECT 

				(SELECT TOP 1  XREGRACOMPONENTEVENDA.CODCONTRATOCEF 
							 FROM XREGRACOMPONENTEVENDA  (NOLOCK) 
							 WHERE COD_COMPN IN (20,500)
							 AND XREGRACOMPONENTEVENDA.CODCONTRATOCEF IS NOT NULL
							 AND XREGRACOMPONENTEVENDA.NUM_VENDA = SGI.NUM_VENDA 
							 AND XREGRACOMPONENTEVENDA.CODCOLIGADA = SGI.CODCOLIGADA
							 ) AS 'CONTRATOCEF',
				GCOLIGADA.CODCOLIGADA
				,GCOLIGADA.NOMEFANTASIA
				,XEMPREENDIMENTO.NOME
				,SGI.EMP
				,CONVERT (VARCHAR (20),SGI.QUADRA) AS UND
				,CONVERT (VARCHAR (20),SGI.LOTE) AS LOTE
				,SGI.TIPO_PAG
				,SGI.NUMERO
				,SGI.CLIENTE
				,CONVERT (VARCHAR, SGI.EMISSAO,103) AS EMISSAO
				,CONVERT (VARCHAR, SGI.VENCIMENTO,103) AS VENCIMENTO
				,CAST (SGI.VALORHIST AS MONEY) AS VALOR_HIST
				,CONVERT (VARCHAR, SGI.DATADORECEBIMENTO,103) AS DATADORECEBIMENTO
				,SGI.SITUACAO
				,SGI.IDLAN
				,SGI.NUM_VENDA
				,SGI.DAT_VENDA
				,SGI.DSC_MOD_VENDA AS MODALIDADE
				,SGI.CORRECAO
				,SGI.JUROS
				,SGI.VALORHIST AS TOTAL
				,SGI.DESCONTO
				,SGI.MULTA
				,SGI.MORA				
				,SGI.VALORRECEBIDO AS VALOR_CORRIGIDO
                                                                ,' ' AS DATACONTABIL

FROM DBO.REL_SGI_RECEBIDAS_VARIOS_EMP  (@RESULTADO ,'19000101','30000101') AS SGI
INNER JOIN XEMPREENDIMENTO	(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = SGI.EMP)
INNER JOIN GCOLIGADA		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
WHERE SGI.VALORHIST IS NOT NULL
AND SGI.VALORRECEBIDO > 0

UNION ALL
SELECT	 
					 (SELECT TOP 1  XREGRACOMPONENTEVENDA.CODCONTRATOCEF 
							 FROM XREGRACOMPONENTEVENDA  (NOLOCK) 
							 WHERE COD_COMPN IN (20,500)
							 AND XREGRACOMPONENTEVENDA.CODCONTRATOCEF IS NOT NULL
							 AND XREGRACOMPONENTEVENDA.NUM_VENDA = XVENDA.NUM_VENDA 
							 AND XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDA.CODCOLIGADA
							 ) AS 'CONTRATOCEF',
					 GCOLIGADA.CODCOLIGADA,
					 GCOLIGADA.NOMEFANTASIA,
					 XEMPREENDIMENTO.NOME,
					XEMPREENDIMENTO.COD_PESS_EMPR AS 'EMPREENDIMENTO'
					,CONVERT (VARCHAR (20),XITEMVENDA.NUM_UNID) AS UND
					,CONVERT (VARCHAR (20),XITEMVENDA.NUM_SUB_UNID) AS LOTE
					,XTIPOPARCELA.DSC_TIPO_PARC
					,'PARCELA'=XVENDAPARCELA.NUMPARC
					,'CLIENTE'=DBO.INITCAP(FCFO.NOME) 
					,CONVERT(VARCHAR,FLAN.DATAEMISSAO,103) AS EMISSAO
					,CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103) AS VENCIMENTO	 				
					,CAST ((CASE WHEN FLAN.STATUSLAN = 4 THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLLAN) ELSE FLAN.VALORORIGINAL END)  +
					DBO.RETORA_VALORES_CEF( XVENDAPARCELA.CODCOLLAN,XVENDAPARCELA.IDLAN) - 
					DBO.RETORA_VALORES_BAIXADOS_CEF( XVENDAPARCELA.CODCOLLAN,XVENDAPARCELA.IDLAN) AS MONEY) AS VALOR
					,NULL AS DATA_RECEBIMENTO
					,FLAN.STATUSLAN
					,XVENDAPARCELA.IDLAN 
					,XVENDA.NUM_VENDA
					,XVENDA.DAT_VENDA  AS DAT_VENDA
					,XMODALIDADEVENDA.DSC_MOD_VENDA AS MODALIDADE

					 ,'CORREÇÃO'= ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
					-
					/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)

					,'JUROS'= ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) 
					-
					/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)										 

					,TOTAL=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
					 +ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
					-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
					-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)

					,FLAN.VALORDESCONTO AS 'DESCONTO'

					,(DBO.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, GETDATE())) AS 'MULTA'
					,(DBO.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, GETDATE())) AS 'MORA'

					,VALOR_CORRIGIDO=(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)
			+ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			+ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO  (NOLOCK)  WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) + FLAN.VALORJUROS
			+(DBO.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, GETDATE()))
			+(DBO.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, GETDATE())) 
			-/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			-/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO  (NOLOCK) 
			INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
			WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			-FLAN.VALORDESCONTO

                                                                                /*TRAZER A ULTIMA DATA DA CONTABILIZAÇÃO DA BAIXA*/
                                                                              ,(SELECT TOP 1 FORMAT(DATACONTABILIZBX,'DD/MM/YYYY') FROM FLANBAIXA  (NOLOCK)  WHERE FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA ORDER BY DATACONTABILIZBX DESC) AS DATACONTABIL

					/* CORRECAO COLIGADA 10 (6 , 13)
	    CORRECAO COLIGADA 11 (4 , 11) */
   	
					
	/* JUROS COLIGADA 10 (5 , 14) 
	   JUROS COLIGADA 11 (*/

FROM  XVENDA  (NOLOCK) 
          INNER JOIN  XVENDAPARCELA                     (NOLOCK) ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
		  INNER JOIN XEMPREENDIMENTO               (NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
		  INNER JOIN GCOLIGADA								(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
		  INNER JOIN FCFO											(NOLOCK) ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
		  INNER JOIN XITEMVENDA								(NOLOCK) ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
		  INNER JOIN XTIPOPARCELA							(NOLOCK) ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
		  INNER JOIN FLAN                                           (NOLOCK) ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
		  INNER JOIN FTB2                                           (NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
		  INNER JOIN XMODALIDADEVENDA            (NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
		  INNER JOIN XVENDACOMPL							(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDACOMPL.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDACOMPL.NUMVENDA)				
					

WHERE		XVENDA.COD_SIT_VENDA NOT IN (60,61,62)
					AND XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
					AND FLAN.STATUSLAN IN (0,4)
					AND XVENDAPARCELA.CODTIPOPARC NOT IN (23,43,38,36,41,42,44,4,45,48,98,101)