
SELECT 

(isnull(PFUNC.NOME,FCFO.NOMEFANTASIA)) AS NOMEFANTASIA,
FLAN.DATAEMISSAO,
FLAN.CODCCUSTO as CODCUSTO$ ,
FLAN.CODCXA,
FLAN.VALORORIGINAL,
FLAN.NUMERODOCUMENTO,
FLAN.DATAVENCIMENTO,
FLAN.HISTORICO,
FLAN.CODTDO,
FTB2.DESCRICAO,
FLAN.USUARIOCRIACAO,
flan.idlan,
gccusto.nome,
FLAN.CODFILIAL,
FLAN.CODCOLIGADA ,
flan.codtb2flx

FROM
FLAN				(NOLOCK)
LEFT JOIN FCFO		(NOLOCK) ON FLAN.CODCOLCFO = FCFO.CODCOLIGADA AND FLAN.CODCFO = FCFO.CODCFO
LEFT JOIN GCCUSTO	(NOLOCK) ON FLAN.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND FLAN.CODCCUSTO = GCCUSTO.CODCCUSTO
LEFT JOIN FTB2		(NOLOCK) ON FTB2.CODCOLIGADA = FLAN.CODCOLIGADA AND FLAN.CODTB2FLX  = FTB2.CODTB2FLX
LEFT JOIN PFUNC		(NOLOCK) ON (FLAN.CHAPA = PFUNC.CHAPA AND FLAN.CODCOLIGADA = PFUNC.CODCOLIGADA)
WHERE
--FLAN.CODCOLIGADA =:$CODCOLIGADA AND 
FLAN.DATAVENCIMENTO >= '20240101'/*:DATA_VENCIMENTO_INICIAL_D*/
AND FLAN.DATAVENCIMENTO <= '20240405'/*:DATA_VENCIMENTO_FINAL_D*/
AND FLAN.CODTDO IN('042','043')
AND FLAN.PAGREC = 2
AND FLAN.CODTB2FLX in ('005','170','01.011','02.118')
AND FLAN.STATUSLAN <> 2
order by CODCUSTO$, FLAN.DATAEMISSAO