USE CORPORE_RESIDENCIAL

DECLARE @CODCOLIGADA		INT;
DECLARE @CLIENTE						VARCHAR(255);
DECLARE @DATA_INI						NVARCHAR(10);
DECLARE @DATA_FIM					NVARCHAR(10);

SET @CODCOLIGADA = 33
SET @CLIENTE = '427.399.258-24'
SET @DATA_INI	= '20230101'
SET @DATA_FIM	= '20231231'

SELECT 

GCOLIGADA.CODCOLIGADA AS COD_COLIGADA,
GFILIAL.CGC AS CNPJ_EMPREENDIMENTO,
GCOLIGADA.NOME AS NOME_COLIGADA,
FCFO.NOMEFANTASIA AS NOME_CLIENTE,
FCFO.CGCCFO AS 'CNPJ/CPF',
(	
	SELECT TOP 1 UPPER(FLANINTEGRACAODEF.DESCRICAO)
	FROM FLANINTEGRACAO AS INTEGRA
	LEFT JOIN FLANINTEGRACAODEF					(NOLOCK) ON (INTEGRA.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND INTEGRA.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
	WHERE FLAN.IDLAN = INTEGRA.IDLAN
	AND FLAN.CODCOLIGADA = INTEGRA.CODCOLIGADA
	ORDER BY INTEGRA.VALOR DESC
) 
AS 'TIPO DE PARCELA',

FLAN.IDLAN,
(
	SELECT DISTINCT FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy')
	FROM FLAN
	WHERE FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
)AS DATA_VENCIMENTO,
(
	SELECT DISTINCT FORMAT(FLAN.DATABAIXA, 'dd/MM/yyyy')
	FROM FLAN
	WHERE FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
)AS DATA_BAIXA,
--FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy') AS DATA_VENCIMENTO,
--FORMAT(FLANBAIXA.DATABAIXA, 'dd/MM/yyyy')AS DATA_BAIXA,
CONVERT (DECIMAL(10,2), FLAN.VALORORIGINAL) AS  VALORORIGINAL,
CONVERT (DECIMAL(10,2), FLAN.VALORJUROS) AS VALORJUROS,
CONVERT (DECIMAL(10,2), FLAN.VALORDESCONTO) AS VALORDESCONTO, 
CONVERT (DECIMAL(10,2), FLAN.VALORBAIXADO)AS 'VALORBAIXADO/FINAL',
CONVERT (DECIMAL(10,2), FLANBAIXA.VALOROP8) AS HONORARIOS,
CONVERT(VARCHAR,FLANCOMPL.COBRANCA) AS COBRANCA
--CONCAT(XCOMPONENTE.COD_COMPN ,+' - ', + XCOMPONENTE.DSC_COMPN) AS CODCOMPN

FROM FLAN (NOLOCK)

LEFT JOIN GCOLIGADA									(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANBAIXA									(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANINTEGRACAO						(NOLOCK) ON (FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANCOMPL									(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA )
LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
LEFT JOIN GFILIAL											(NOLOCK) ON (GFILIAL.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND GFILIAL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
LEFT JOIN XVENDA											(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
LEFT JOIN FCFO												(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO)
LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
--INNER JOIN XCOMPONENTE						(NOLOCK) ON (XCOMPONENTE.COD_TIPO_COMPN = XVENDAPARCELA.COD_TIPO_COMPN)

WHERE GCOLIGADA.CODCOLIGADA =  @CODCOLIGADA
AND FCFO.CGCCFO = @CLIENTE
AND FLANBAIXA.DATABAIXA BETWEEN @DATA_INI AND @DATA_FIM
AND FLANCOMPL.COBRANCA IS NOT NULL

GROUP BY GCOLIGADA.CODCOLIGADA, 
GCOLIGADA.NOME,
GFILIAL.CGC,
FLANBAIXA.IDLAN,
FLAN.DATAVENCIMENTO,
FLANBAIXA.DATABAIXA,
FCFO.NOMEFANTASIA,
FCFO.CGCCFO,
--XCOMPONENTE.DSC_COMPN,
FLAN.IDLAN,
FLAN.CODCOLIGADA,
FLANBAIXA.IDLAN,
FLAN.VALORORIGINAL,
FLAN.VALORBAIXADO,
FLAN.VALORJUROS,
FLAN.VALORDESCONTO, 
FLANBAIXA.VALOROP8,
CONVERT(VARCHAR,FLANCOMPL.COBRANCA)

