
SELECT DISTINCT
FLAN.CODCOLIGADA AS COD_COLIGADA,
--GCOLIGADA.NOME,
(SELECT TOP 1 CGC FROM GFILIAL WHERE GFILIAL.CODFILIAL = FLAN.CODFILIAL) AS CGC,
(SELECT TOP 1 NOME FROM GFILIAL WHERE GFILIAL.CODFILIAL = FLAN.CODFILIAL) AS NOME_FILIAL,
--/*GFILIAL.CGC AS CNPJ_EMPREENDIMENTO,*/
--GCOLIGADA.NOME AS NOME_COLIGADA,
FCFO.NOMEFANTASIA AS NOME_CLIENTE,
FCFO.CGCCFO AS 'CNPJ/CPF',
(	
	SELECT TOP 1 UPPER(FLANINTEGRACAODEF.DESCRICAO)
	FROM FLANINTEGRACAO AS INTEGRA
	LEFT JOIN FLANINTEGRACAODEF					(NOLOCK) ON (INTEGRA.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND INTEGRA.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
	WHERE FLAN.IDLAN = INTEGRA.IDLAN
	AND FLAN.CODCOLIGADA = INTEGRA.CODCOLIGADA
--	AND FLANINTEGRACAODEF.DESCRICAO IN('Adiant.Escritura/ITBI-P.CHAVES', 
--	'Adiantamento Escritura/ITBI', 'ADIANTAMENTO REGISTRO', 'Anual', 'Anual Parcelada', 'Bimestral', 'C.CREDITO- ADIANT ESCRIT/ITBI', 'CM ADIANTAMENTO ESCRITURA/ITBI','CM Antes Aditivo', 
--	'CM Antes Entrega', 'CM Apos Entrega', 'CM EMOLUMENTOS', 'Complemento de Ato', 'Correção e Juros S/Financ.', 'EMOLUMENTOS - IPCA E JUROS', 'Emolumentos Cartorários', 'Entrada', 
--	'Financiamento', 'Financiamento Fixo', 'Financiamento SFH', 'IPTU', 'ITBI/REGISTRO', 'ITBI/REGISTRO PARCELADO', 'Juros Antes Aditivo', 'Juros Atraso', 'Juros Contratuais M.Indexado', 
--	'Juros de Acordo M.Indexado', 'Juros de Mora', 'Juros de Mutuários', 'Juros e Multa Contratual', 'Juros Remuneratórios', 'LAUDÊMIO', 'Mensal','Mensal 2','Mensal 3','Mensal 4','MENSAL FIXO',
--	'Multa Atraso','Multa Atraso de Mora','Multa e Juros de Mora','Parcela Chaves','Parcela Condominio','Parcela de Acordo','Parcela Fixa','Parcela Intermediária','Parcela Única','Pentamensal',
--	'Quadrimestral','Quitação','Recursos proprios','Reneg. Parc. Anual Cobranca','Reparcelamento IPTU','Residuo','Resíduo CM','Semestral','Semestral 2','Sinal','Taxa de Notificação','Taxa de Transferencia',
--	'Taxa IPTU','Taxa Juros Antes Entrega','Taxa Juros Apos Entrega','TAXAS E CUSTAS JUDICIAIS','Trimestral','TRIMESTRAL 2','TRIMESTRAL 3','Tx. Agua/Esgoto/Luz/Telefone')
--	ORDER BY INTEGRA.VALOR DESC
) AS 'TIPO DE PARCELA',

FLAN.IDLAN,
--(
--	SELECT DISTINCT FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy')
--	FROM FLAN
--	WHERE FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
--	GROUP BY FLAN.IDLAN,
--	FLAN.DATAVENCIMENTO
--)AS DATA_VENCIMENTO,
--(
--	SELECT DISTINCT FORMAT(FLAN.DATABAIXA, 'dd/MM/yyyy')
--	FROM FLAN
--	WHERE FLAN.IDLAN = FLANBAIXA.IDLAN AND FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
--	GROUP BY FLAN.IDLAN,
--	FLAN.DATABAIXA
--)AS DATA_BAIXA,
FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy') AS DATA_VENCIMENTO,
FORMAT(FLANBAIXA.DATABAIXA, 'dd/MM/yyyy')AS DATA_BAIXA,
CONVERT (DECIMAL(10,2), FLAN.VALORORIGINAL) AS  VALORORIGINAL,
CONVERT (DECIMAL(10,2), FLAN.VALORJUROS) AS VALORJUROS,
CONVERT (DECIMAL(10,2), FLAN.VALORMULTA) AS VALORMULTA,
CONVERT (DECIMAL(10,2), FLAN.VALORDESCONTO) AS VALORDESCONTO, 
CONVERT (DECIMAL(10,2), FLAN.VALOROP8) AS HONORARIOS,
CONVERT (DECIMAL(10,2), FLAN.VALORBAIXADO)AS VALOR_SOMADO,
CONVERT(VARCHAR,FLANCOMPL.COBRANCA) AS COBRANCA
--CONCAT(XCOMPONENTE.COD_COMPN ,+' - ', + XCOMPONENTE.DSC_COMPN) AS CODCOMPN

FROM FLAN (NOLOCK)
LEFT JOIN GCOLIGADA							(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FCFO								(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO)
LEFT JOIN FLANBAIXA							(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANINTEGRACAO						(NOLOCK) ON (FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA)
LEFT JOIN FLANCOMPL							(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = FLAN.CODCOLIGADA )
LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
LEFT JOIN XVENDA								(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
------INNER JOIN XCOMPONENTE						(NOLOCK) ON (XCOMPONENTE.COD_TIPO_COMPN = XVENDAPARCELA.COD_TIPO_COMPN)

WHERE FLAN.CODCOLIGADA IN (1)
--AND FLAN.DATABAIXA BETWEEN '20230101' AND '20231025'
--AND CONVERT(VARCHAR,FLANCOMPL.COBRANCA) IN ('c0923')
AND FCFO.NOME = 'ADRIANA DE SOUZA PINTO CUNHA'

--GROUP BY 
--FLAN.IDLAN,
--FLAN.CODFILIAL,
--GCOLIGADA.NOME,
--FLAN.DATAVENCIMENTO,
----FLANBAIXA.DATABAIXA,
--FCFO.NOMEFANTASIA,
--FCFO.CGCCFO,
--GCOLIGADA.CODCOLIGADA, 
----XCOMPONENTE.DSC_COMPN,
--FLAN.IDLAN,
--FLAN.CODCOLIGADA,
----FLANBAIXA.IDLAN,
--FLAN.VALORORIGINAL,
--FLAN.VALORBAIXADO,
--FLAN.VALORJUROS,
--FLAN.VALORMULTA,
--FLAN.VALORDESCONTO, 
--FLAN.VALOROP8,
----GFILIAL.NOME,
----XEMPREENDIMENTO.CODFILIAL,
----XEMPREENDIMENTO.CODCOLIGADA,
----CONVERT(VARCHAR,FLANCOMPL.COBRANCA)
--FCFO.NOME




--ORDER BY 5,8

