SELECT 
    Subquery.COD_COLIGADA AS CODCOLIGADA,
    Subquery.CNPJ_EMPREENDIMENTO,
    Subquery.NOME_COLIGADA,
    Subquery.NOME_CLIENTE,
    Subquery.CNPJCPF AS 'CNPJ/CPF CLIENTE',
    Subquery.TIPOPARCELA,
    Subquery.IDLAN,
    Subquery.DATA_VENCIMENTO,
    Subquery.DATA_BAIXA,
    Subquery.VALORORIGINAL,
    Subquery.VALORJUROS,
    Subquery.VALORMULTA,
    Subquery.VALORDESCONTO,
    Subquery.HONORARIOS,
    Subquery.VALOR_BAIXADO,
    Subquery.COBRANCA
FROM (
				SELECT
					GCOLIGADA.CODCOLIGADA AS COD_COLIGADA,
					FLAN.IDLAN,
					FCFO.CGCCFO AS CNPJCPF,
					(
						SELECT TOP 1 FILI1.CGC 
						FROM GFILIAL AS FILI1
						WHERE FILI1.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND FILI1.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA
						ORDER BY FILI1.CGC DESC
					) AS CNPJ_EMPREENDIMENTO,
					GCOLIGADA.NOME AS NOME_COLIGADA,
					FCFO.NOMEFANTASIA AS NOME_CLIENTE,
						   (	
							SELECT TOP 1 UPPER(FLANINTEGRACAODEF.DESCRICAO)
							FROM FLANINTEGRACAO AS INTEGRA
							LEFT JOIN FLANINTEGRACAODEF					(NOLOCK) ON (INTEGRA.IDCAMPO = FLANINTEGRACAODEF.IDCAMPO AND INTEGRA.CODCOLIGADA = FLANINTEGRACAODEF.CODCOLIGADA)
							WHERE FLAN.IDLAN = INTEGRA.IDLAN
							AND FLAN.CODCOLIGADA = INTEGRA.CODCOLIGADA
							AND FLANINTEGRACAODEF.DESCRICAO IN('Adiant.Escritura/ITBI-P.CHAVES', 
							'Adiantamento Escritura/ITBI', 'ADIANTAMENTO REGISTRO', 'Anual', 'Anual Parcelada', 'Bimestral', 'C.CREDITO- ADIANT ESCRIT/ITBI', 'CM ADIANTAMENTO ESCRITURA/ITBI','CM Antes Aditivo', 
							'CM Antes Entrega', 'CM Apos Entrega', 'CM EMOLUMENTOS', 'Complemento de Ato', 'Correção e Juros S/Financ.', 'EMOLUMENTOS - IPCA E JUROS', 'Emolumentos Cartorários', 'Entrada', 
							'Financiamento', 'Financiamento Fixo', 'Financiamento SFH', 'IPTU', 'ITBI/REGISTRO', 'ITBI/REGISTRO PARCELADO', 'Juros Antes Aditivo', 'Juros Atraso', 'Juros Contratuais M.Indexado', 
							'Juros de Acordo M.Indexado', 'Juros de Mora', 'Juros de Mutuários', 'Juros e Multa Contratual', 'Juros Remuneratórios', 'LAUDÊMIO', 'Mensal','Mensal 2','Mensal 3','Mensal 4','MENSAL FIXO',
							'Multa Atraso','Multa Atraso de Mora','Multa e Juros de Mora','Parcela Chaves','Parcela Condominio','Parcela de Acordo','Parcela Fixa','Parcela Intermediária','Parcela Única','Pentamensal',
							'Quadrimestral','Quitação','Recursos proprios','Reneg. Parc. Anual Cobranca','Reparcelamento IPTU','Residuo','Resíduo CM','Semestral','Semestral 2','Sinal','Taxa de Notificação','Taxa de Transferencia',
							'Taxa IPTU','Taxa Juros Antes Entrega','Taxa Juros Apos Entrega','TAXAS E CUSTAS JUDICIAIS','Trimestral','TRIMESTRAL 2','TRIMESTRAL 3','Tx. Agua/Esgoto/Luz/Telefone')
							ORDER BY INTEGRA.VALOR DESC
						)AS TIPOPARCELA,
						(
							SELECT DISTINCT FORMAT(FLAN.DATAVENCIMENTO, 'dd/MM/yyyy')
							FROM FLAN AS FLAN1
							WHERE FLAN1.IDLAN = FLANBAIXA.IDLAN AND FLAN1.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
						)AS DATA_VENCIMENTO,
						(
							SELECT DISTINCT FORMAT(FLAN.DATABAIXA, 'dd/MM/yyyy')
							FROM FLAN AS FLAN2
							WHERE FLAN2.IDLAN = FLANBAIXA.IDLAN AND FLAN2.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
						)AS DATA_BAIXA,
					CONVERT (DECIMAL(10,2), FLAN.VALORORIGINAL) AS VALORORIGINAL,
					CONVERT (DECIMAL(10,2), FLAN.VALORJUROS) AS VALORJUROS,
					CONVERT (DECIMAL(10,2), FLAN.VALORMULTA) AS VALORMULTA,
					CONVERT (DECIMAL(10,2), FLAN.VALORDESCONTO) AS VALORDESCONTO, 
					CONVERT (DECIMAL(10,2), FLAN.VALOROP8) AS HONORARIOS,
					CONVERT (DECIMAL(10,2), FLAN.VALORBAIXADO) AS VALOR_BAIXADO,
					CONVERT(VARCHAR,FLANCOMPL.COBRANCA) AS COBRANCA

			 FROM FLAN (NOLOCK)

			LEFT JOIN GCOLIGADA									(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FLANBAIXA									(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FLANINTEGRACAO						(NOLOCK) ON (FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA)
			LEFT JOIN FLANCOMPL									(NOLOCK) ON (FLANCOMPL.IDLAN = FLAN.IDLAN AND FLANCOMPL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA )
			LEFT JOIN XEMPREENDIMENTO						(NOLOCK) ON (XEMPREENDIMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
			LEFT JOIN GFILIAL											(NOLOCK) ON (GFILIAL.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND GFILIAL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
			LEFT JOIN XVENDA											(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
			LEFT JOIN FCFO												(NOLOCK) ON (FLAN.CODCFO = FCFO.CODCFO)
			LEFT JOIN XVENDAPARCELA							(NOLOCK) ON (XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
			

			WHERE GCOLIGADA.CODCOLIGADA IN (1)
			AND FLANBAIXA.DATABAIXA BETWEEN '20230101' AND '20231025'
			AND CONVERT(VARCHAR,FLANCOMPL.COBRANCA) IN ('c0923')

) AS Subquery

GROUP BY  Subquery.COD_COLIGADA,
    Subquery.CNPJ_EMPREENDIMENTO,
    Subquery.NOME_COLIGADA,
    Subquery.NOME_CLIENTE,
    Subquery.CNPJCPF,
    Subquery.TIPOPARCELA,
    Subquery.IDLAN,
    Subquery.DATA_VENCIMENTO,
    Subquery.DATA_BAIXA,
    Subquery.VALORORIGINAL,
    Subquery.VALORJUROS,
    Subquery.VALORMULTA,
    Subquery.VALORDESCONTO,
    Subquery.HONORARIOS,
    Subquery.VALOR_BAIXADO,
    Subquery.COBRANCA

ORDER BY Subquery.NOME_CLIENTE DESC,
    Subquery.COD_COLIGADA,
    Subquery.CNPJ_EMPREENDIMENTO,
    Subquery.NOME_COLIGADA,
    Subquery.CNPJCPF,
    Subquery.TIPOPARCELA,
    Subquery.IDLAN,
    Subquery.DATA_VENCIMENTO,
    Subquery.DATA_BAIXA,
    Subquery.VALORORIGINAL,
    Subquery.VALORJUROS,
    Subquery.VALORMULTA,
    Subquery.VALORDESCONTO,
    Subquery.HONORARIOS,
    Subquery.VALOR_BAIXADO,
    Subquery.COBRANCA;