SELECT 
nome,reccreatedby,reccreatedon,* 
FROM FCFOHISTORICO (nolock) 

WHERE  
codcfo IN ('F53137') 
ORDER BY idhistorico


SELECT * FROM FCFO WHERE codcfo IN ('F53137')

/*UPDATE PARA TROCAR DADOS DO CLI/FOR ALTERADOs PELA INTEGRAÇÃO*/

BEGIN TRAN
UPDATE FCFO
SET 
FCFO.NOME						= FCFOHISTORICO.NOME
,FCFO.NOMEFANTASIA				= FCFOHISTORICO.NOMEFANTASIA
,FCFO.CGCCFO					= FCFOHISTORICO.CGCCFO
,FCFO.INSCRMUNICIPAL			= FCFOHISTORICO.INSCRMUNICIPAL
,FCFO.INSCRESTADUAL				= FCFOHISTORICO.INSCRESTADUAL
,FCFO.NUMDEPENDENTES			= FCFOHISTORICO.NUMDEPENDENTES
,FCFO.VROUTRASDEDUCOESIRRF		= FCFOHISTORICO.VROUTRASDEDUCOESIRRF
,FCFO.RUA						= FCFOHISTORICO.RUA
,FCFO.NUMERO					= FCFOHISTORICO.NUMERO
,FCFO.COMPLEMENTO				= FCFOHISTORICO.COMPLEMENTO
,FCFO.CEP						= FCFOHISTORICO.CEP
,FCFO.BAIRRO					= FCFOHISTORICO.BAIRRO
,FCFO.CIDADE					= FCFOHISTORICO.CIDADE
,FCFO.CODETD					= FCFOHISTORICO.CODETD
,FCFO.PAIS						= FCFOHISTORICO.PAIS
,FCFO.TELEFONE					= FCFOHISTORICO.TELEFONE
,FCFO.FAX						= FCFOHISTORICO.FAX
,FCFO.EMAIL						= FCFOHISTORICO.EMAIL
,FCFO.CONTATO					= FCFOHISTORICO.CONTATO
,FCFO.CODMUNICIPIO				= FCFOHISTORICO.CODMUNICIPIO
,FCFO.PESSOAFISOUJUR			= FCFOHISTORICO.PESSOAFISOUJUR
,FCFO.TIPORUA					= FCFOHISTORICO.TIPORUA
,FCFO.TIPOBAIRRO				= FCFOHISTORICO.TIPOBAIRRO
,FCFO.IDPAIS					= FCFOHISTORICO.IDPAIS
,FCFO.RECCREATEDBY				= FCFOHISTORICO.RECCREATEDBY
,FCFO.RECCREATEDON				= FCFOHISTORICO.RECCREATEDON
,FCFO.RECMODIFIEDBY				= FCFOHISTORICO.RECMODIFIEDBY
,FCFO.RECMODIFIEDON				= FCFOHISTORICO.RECMODIFIEDON
,FCFO.USARCUMULATRETENCAOPAGAR	= FCFOHISTORICO.USARCUMULATRETENCAOPAGAR

FROM FCFO (NOLOCK) 
INNER JOIN FCFOHISTORICO (NOLOCK) ON (FCFOHISTORICO.CODCOLIGADA = FCFO.CODCOLIGADA AND FCFOHISTORICO.CODCFO = FCFO.CODCFO)

WHERE  
FCFOHISTORICO.CODCFO IN ('F53137') 
AND IDHISTORICO = 5960155 /*PEGAR ULTIMO ID QUE DESEJA USAR PARA FAZER UPDATE*/


--COMMIT
--ROLLBACK





