DECLARE @ANO INT = YEAR(@DATA_REFERENCIA)


SELECT 
(CASE WHEN MONTH(MESES.DATA) = 1 THEN 'JANEIRO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 2 THEN 'FEVEREIRO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 3 THEN 'MARCO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 4 THEN 'ABRIL / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 5 THEN 'MAIO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 6 THEN 'JUNHO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 7 THEN 'JULHO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 8 THEN 'AGOSTO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 9 THEN 'SETEMBO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 10 THEN 'OUTUBRO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 WHEN MONTH(MESES.DATA) = 11 THEN 'NOVEMBRO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))
		 ELSE 'DEZEMBRO / ' + CONVERT(VARCHAR(4),YEAR(MESES.DATA))END
) AS 'MES',

ISNULL((SELECT 
SUM(CONTAS.CREDITO) - SUM(CONTAS.DEBITO) 'TOTAL RECEITA'
FROM
(	
	SELECT VALOR AS DEBITO, 0 AS CREDITO
	FROM CPARTIDA
	WHERE 
	DEBITO  LIKE '3.1.01.02%'
	/*DEBITO  IN ('3.1.01.02.000001','3.1.01.02.000009','3.1.01.02.000010','3.1.01.02.000013')*/
	AND	MONTH(DATA) = MONTH(MESES.DATA) AND YEAR(DATA) = YEAR(MESES.DATA)
	AND CPARTIDA.CODHISTP <> @CODIGO
	AND CODLOTE = 0
	AND CPARTIDA.CODCOLIGADA = @CODCOLIGADA
	AND CPARTIDA.CODCCUSTO IN (@CENTRO_DE_CUSTO)
	UNION ALL

	SELECT 0 AS DEBITO, VALOR AS CREDITO
	FROM CPARTIDA
	WHERE 
	CREDITO LIKE '3.1.01.02%'
	/*CREDITO IN ('3.1.01.02.000001','3.1.01.02.000009','3.1.01.02.000010','3.1.01.02.000013')*/
	AND	MONTH(DATA) = MONTH(MESES.DATA) AND YEAR(DATA) = YEAR(MESES.DATA)
	AND CPARTIDA.CODHISTP <> @CODIGO
	AND CODLOTE = 0
	AND CPARTIDA.CODCOLIGADA = @CODCOLIGADA
	AND CPARTIDA.CODCCUSTO IN (@CENTRO_DE_CUSTO)

	) AS CONTAS
),0) AS RECEITA_TOTAL 


FROM 

(
			SELECT * FROM  DBO.TRAZ_INTERVALO_DATAS (@DATA_REFERENCIA)
) AS MESES