
SELECT XEMPREENDIMENTO.CODCOLIGADA, XEMPREENDIMENTO.NOME,  FCFO.NOME , FCFO.CODCFO
FROM FCFO
JOIN XVENDA				ON XVENDA.CODCFO = FCFO.CODCFO
JOIN XEMPREENDIMENTO	ON XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR
WHERE FCFO.NOME LIKE '%DOMITILLA%'

/*SELECT * 
FROM XVENDA 
WHERE CODCFO = 'C50133'

SELECT * 
FROM XEMPREENDIMENTO
WHERE COD_PESS_EMPR = '2026'*/