/*************** CONSULTA ALTERADA, ADICIONADO CORREÇÃO CM E ALTERADO VALOR LIQUIDO************************/
/*CAPYS.0002.02 - TODAS AS PARCELAS DO CLIENTE*/
DECLARE @DATA_BASE_D AS DATE, 
@MULTA AS DECIMAL(10,5), 
@MORA AS DECIMAL(10,10),
@ID_VENDA AS INT;

SET @DATA_BASE_D = GETDATE()
SET @ID_VENDA = 10856


/*SET @DATA_BASE_D = GETDATE()*/
SET @MULTA='0.02'
SET @MORA='0.033333333'


SELECT  
0 AS 'ID_CASO_COBRANCA_FATO_PARCELAS_A_RECEBER',
CONCAT(XVENDA.CODCOLIGADA,'-',XVENDA.COD_PESS_EMPR,'-',XVENDA.NUM_VENDA,'-',XVENDAPARCELA.IDLAN,'-',XVENDAPARCELA.CODTIPOPARC,'-',XVENDAPARCELA.CODTIPOPARC) AS 'ID_CHAVE_ERP',
XVENDA.CODCOLIGADA AS 'ID_EMPRESA',
XVENDA.COD_PESS_EMPR AS 'ID_OBRA',
XVENDA.NUM_VENDA AS 'ID_VENDA',
XVENDAPARCELA.IDLAN AS 'ID_PARCELA',
XVENDAPARCELA.CODTIPOPARC AS 'ID_TIPO_PARCELA',
DBO.INITCAP(XTIPOPARCELA.DSC_TIPO_PARC) AS 'DS_TIPO_PARCELA',
XVENDAPARCELA.CODTIPOPARC AS 'ID_PARCELA_GERAL',
XVENDAPARCELA.NUMPARC AS 'NUMERO_PARCELA',
FLAN.VALORORIGINAL AS 'VL_ORIGINAL', /*PRINCIPAL (EXTRATO)*/
(CASE WHEN FLAN.STATUSLAN IN (1,4) THEN FLAN.DATABAIXA ELSE NULL END) AS 'DATA_PAGAMENTO',

/*NOVOS CAMPOS ADICIONADOS NO EXTRATO*/
VLR.CORRECAO_TOTAL	AS 'CORRECAO_TOTAL_EXT',
VLR.JUROS_TOTAL		AS 'JUROS_TOTAL_EXT',
VLR.MULTA_TOTAL		AS 'MULTA_TOTAL_EXT',
VLR.MORA_TOTAL		AS 'MORA_TOTAL_EXT',
(VLR.DESCONTO_ADITIVO_TOTAL + VLR.DESCONTO_TOTAL) AS 'DESCONTO_TOTAL_EXT',
VLR.VALOR_TOTAL		AS 'VALOR_TOTAL_EXT',
/**/


( CASE
	WHEN FLAN.STATUSLAN = 1 
		THEN 0
		ELSE (
				VLR.SALDO  /*VALOR_LIQUIDO*/
				+
				VLR.MORA /*JUROS_FORMULA*/
				+
				VLR.MULTA  /*MULTA_FORMULA*/
				-
				VLR.DESCONTO_TOTAL + VLR.DESCONTO_BAIXADO  /*DESCONTO_LIQUIDO*/
				+
				(VLR.CORRECAO_TOTAL - VLR.CORRECAO_BAIXADO) /*CORRECAO_INTEGRAÇÃO*/
				+
				(VLR.JUROS_TOTAL - VLR.JUROS_BAIXADO) /*JUROS2_INTEGRAÇÃO*/
				+
				(VLR.DESCONTO_ADITIVO_TOTAL - VLR.DESCONTO_ADITIVO_BAIXADO)  /*DESCONTO_INTEGRAÇÃO_ADITIVO*/
				+
				(VLR.HONORARIO_TOTAL - VLR.HONORARIO_BAIXADO) /*HONORARIO*/

			)
END) AS 'VL_SALDO_DEVEDOR_EXT', /*SALDO_DEVEDOR NÃO TEM NO EXTRATO*/

( 			
		VLR.SALDO  /*VALOR_LIQUIDO*/
		+
		VLR.MORA /*JUROS_FORMULA*/
		+
		VLR.MULTA  /*MULTA_FORMULA*/
		-
		VLR.DESCONTO_TOTAL  /*DESCONTO_LIQUIDO*/
		+
		VLR.CORRECAO_TOTAL /*CORRECAO_INTEGRAÇÃO*/
		+
		VLR.JUROS_TOTAL /*JUROS2_INTEGRAÇÃO*/
		+
		VLR.DESCONTO_ADITIVO_TOTAL /*DESCONTO_INTEGRAÇÃO_ADITIVO*/
		+
		VLR.HONORARIO_TOTAL /*HONORARIO*/

) AS 'VL_PARCELA_LIQUIDO', /*VALOR REAJUSTADO (EXTRATO)*/

FLAN.VALORBAIXADO AS 'VL_PAGO', /*VALOR PAGO (EXTRATO)*/

/* O DESCONTO ESTÁ SENDO ENVIADO SEPARADAMENTE A PEDIDO DO MAURO DA CAPYS */
FLAN.VALORDESCONTO AS VL_DESCONTO_BOLETO, /*DESCONTO DO BOLETO NÃO TEM NO EXTRATO*/

/* O HONORARIO ESTÁ SENDO ENVIADO SEPARADAMENTE A PEDIDO DO MAURO DA CAPYS */
FLAN.VALOROP8 AS 'VL_HONORARIO', /*HONORARIO DO BOLETO NÃO TEM NO EXTRATO*/
FLAN.VALOROP8 - (SELECT SUM (FLANBAIXA.VALOROP8) FROM FLANBAIXA (NOLOCK) WHERE FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.STATUS <> 1) AS 'VL_HONORARIO_A_RECEBER',
(SELECT SUM (FLANBAIXA.VALOROP8) FROM FLANBAIXA (NOLOCK) WHERE FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.STATUS <> 1) AS 'VL_HONORARIO_RECEBIDO',
			
			
(CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END) AS 'VL_PARCELA_PRINCIPAL',

/*ALTERADO OS CAMPOS PARA ENVIAR APENAS 2 CASAS DECIMAIS, ARREDONDANDO O VALOR*/
ROUND(dbo.MULTA_PARCELAS_SGI(FLAN.CODCOLIGADA, FLAN.IDLAN, @DATA_BASE_D), 2) AS 'VL_MULTA_ATRASO', /*MULTA (EXTRATO)*/

ROUND(dbo.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D),2) as 'VL_JUROS_ATRASO', /*MORA (EXTRATO)*/

/* ALTERADO A CORREÇÃO PARA ENVIAR A CORREÇÃO DE CM */
/*0 AS VL_CORRECAO_ATRASO,*/

ROUND((CASE WHEN FLAN.STATUSLAN = 1 THEN VLR.CORRECAO_BAIXADO ELSE VLR.CORRECAO_TOTAL - VLR.CORRECAO_BAIXADO END),2) AS 'VL_CORRECAO_ATRASO', /*CORREÇÃO (EXTRATO)*/
		
ROUND((CASE WHEN FLAN.STATUSLAN = 1 THEN VLR.JUROS_BAIXADO ELSE VLR.JUROS_TOTAL - VLR.JUROS_BAIXADO END),2) AS 'VL_JUROS_ATRASO', /*JUROS (EXTRATO)*/
	 

ISNULL(FLAN.VALORADIANTAMENTO,0) + ISNULL((SELECT SUM (FLANBAIXA.VALORBAIXA) FROM FLANBAIXA (NOLOCK) 
																				WHERE FLANBAIXA.IDLAN = FLAN.IDLAN 
																					AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA 
																					AND FLANBAIXA.STATUS <> 1),0) AS 'VL_TOTAL_RECEBIDO',	

DATEDIFF (DAY,FLAN.DATAVENCIMENTO,GETDATE()) AS 'NR_AGING_PARCELA',
DATEDIFF (DAY,FLAN.DATAVENCIMENTO,GETDATE()) AS 'NR_AGING_PARCELA_PRORROGACAO',
DBO.PRIMEIRODIA(GETDATE()) AS 'DT_MES_REFERENCIA',
FLAN.DATAVENCIMENTO AS 'DT_VENCIMENTO',
FLAN.DATAVENCIMENTO AS 'DT_PRORROGACAO',
0 'DS_INDICE_REAJUSTE',
0 'NR_JUROS_PARCELA',
GETDATE() 'DT_ATUALIZACAO',
(CASE 
		WHEN FLAN.STATUSLAN = 1 THEN 'PAGO'
		WHEN FLAN.STATUSLAN = 0 THEN 'EM ABERTO'
		WHEN FLAN.STATUSLAN = 4 THEN 'PARCIALMENTE PAGO'
		ELSE DBO.TRAZ_STATUSLAN(FLAN.STATUSLAN) 
END) AS 'STATUS_PARCELA',

CONVERT(VARCHAR(100),UPPER(FCFO.NOMEFANTASIA)) 'DS_NOME',				/* NOME DO CLIENTE*/
CONVERT(VARCHAR(18),FCFO.CGCCFO) 'NR_CPF',								/* CPF DO CLIENTE*/
CONVERT(VARCHAR(50),FCFO.BAIRRO) 'DS_BAIRRO',							/* BAIRRO DO CLIENTE*/
CONVERT(VARCHAR(100),FCFO.RUA) 'DS_LOGRADOURO',							/* RUA DO CLIENTE*/
CONVERT(VARCHAR(20),FCFO.RUA) 'NR_ENDERECO',							/* NUMERO DO CLIENTE*/
CONVERT(VARCHAR(50),FCFO.COMPLEMENTO) 'DS_COMPLEMENTO_ENDERECO',		/* COMPLEMENTO DO CLIENTE*/
CONVERT(VARCHAR(20),FCFO.CEP) 'NR_CEP',	
FBOLETO.IPTE AS 'DS_LINHA_DIGITAVEL',
FBOLETO.CODIGOBARRA,
FBOLETO.VENCIMENTO AS 'VENCIMENTO_BOLETO',
FBOLETO.VALOR AS 'VALOR_BOLETO',

UPPER ((SELECT TOP 1 GFILIAL.NOMEFANTASIA FROM GFILIAL (NOLOCK) WHERE GFILIAL.CGC = FCONVENIO.CGCCEDENTE) + ' - ' + FCONVENIO.CGCCEDENTE) AS 'BOLETO_NOME_CEDENTE',
LEFT (CONVERT(VARCHAR,FCONVENIO.CODCEDENTE),4) + '/' + RIGHT (CONVERT(VARCHAR,FCONVENIO.CODCEDENTE),6) + '-'+ RIGHT (CONVERT(VARCHAR,FCONVENIO.DIGCEDENTE),1) AS 'BOLETO_AGENCIA_CEDENTE',
LEFT (CONVERT(VARCHAR,FBOLETO.NOSSONUMERO),2) + '/' + SUBSTRING(CONVERT(VARCHAR,FBOLETO.NOSSONUMERO),3,15) + '-'+ RIGHT (CONVERT(VARCHAR,FBOLETO.NOSSONUMERO),1) AS 'BOLETO_NOSSONUMERO',
'104' as 'BOLETO_BANCO',
'MULTA DE R$: ' + CONVERT (VARCHAR,CAST (FBOLETO.VALOR * '0.02' AS DECIMAL (10,2))) + ' APÓS: ' + CONVERT (VARCHAR,FBOLETO.VENCIMENTO,103) AS 'BOLETO_TEXTO_1',
'JUROS DE R$: ' + CONVERT (VARCHAR,CAST (FBOLETO.VALOR * '0.0003' AS DECIMAL (10,2))) + ' AO DIA' AS 'BOLETO_TEXTO_2',
'APÓS DIA ' + CONVERT (VARCHAR,DATEPART (DAY, FBOLETO.VENCIMENTO)) + ' COBRAR JUROS E MULTA' AS 'BOLETO_TEXTO_3',

'' AS 'BOLETO_TEXTO_4',
/*UPPER(DBO.TRAZ_PARCELAS_BOLETO(FBOLETO.CODCOLIGADA,FBOLETO.IDBOLETO)) AS BOLETO_TEXTO_4,*/

FLAN.NUMERODOCUMENTO AS 'BOLETO_NUMERODOCUMENTO',
'DM' AS 'BOLETO_ESPECIE',
'RG' AS 'BOLETO_CARTEIRA',
'N' AS  'BOLETO_ACEITE',
'R$' AS 'BOLETO_MOEDA',

FINTEGRACAOCARTAO.QRCODEPIX AS 'PIX_COPIA_COLA',
FINTEGRACAOCARTAO.QRCODEIMGPIX AS 'QRCODE_PIX',

(CASE FBOLETO.CNABSTATUS 
	WHEN 0 THEN 'Não Remetido' 
	WHEN 1 THEN 'Remetido' 
	WHEN 2 THEN 'Registrado' 
	WHEN 3 THEN 'Recusado' 
	WHEN 4 THEN 'Baixado' 
	WHEN 5 THEN 'Registrado Online' 
	WHEN 6 THEN 'Cancelado'
	WHEN 7 THEN 'Pendente Remessa'
	ELSE 'Não Gerado'
END) AS 'STATUS_BOLETO',

ISNULL(FBOLETO.CNABSTATUS,8) AS 'COD_STATUS_BOLETO'

/*INSERIDO CAMPOS A PEDIDO DO OZIEL - CHAMADO 0624-000097 - CESSÃO DA CARTEIRA PARA O INTER*/
,GCONSIST.DESCRICAO AS 'BANCOCEDIDO'
,CONVERT(DATE,XVENDACOMPL.DATACESSAO,103) AS 'DATA_CESSAO'

FROM XVENDA (NOLOCK)
		LEFT JOIN XVENDAPARCELA			(NOLOCK) ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
		LEFT JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
		LEFT JOIN GCOLIGADA				(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
		LEFT JOIN FCFO					(NOLOCK) ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
		LEFT JOIN XITEMVENDA			(NOLOCK) ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
		LEFT JOIN XTIPOPARCELA			(NOLOCK) ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
		LEFT JOIN FLAN					(NOLOCK) ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
		LEFT JOIN FTB2					(NOLOCK) ON (FTB2.CODTB2FLX = FLAN.CODTB2FLX AND FTB2.CODCOLIGADA = FLAN.CODCOLIGADA)
		LEFT JOIN XMODALIDADEVENDA		(NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
		LEFT JOIN FBOLETO				(NOLOCK) ON (FBOLETO.IDBOLETO = FLAN.IDBOLETO AND FBOLETO.CODCOLIGADA = FLAN.CODCOLIGADA AND FBOLETO.CNABSTATUS IN (0,1,2,5))
		LEFT JOIN FINTEGRACAOCARTAO     (NOLOCK) ON (FBOLETO.IDBOLETO = FINTEGRACAOCARTAO.IDBOLETO AND FBOLETO.CODCOLIGADA = FINTEGRACAOCARTAO.CODCOLIGADA AND FINTEGRACAOCARTAO.IDSTATUS = 1)
		LEFT JOIN FCONVENIO				(NOLOCK) ON (FCONVENIO.IDCONVENIO = FBOLETO.IDCONVENIO AND FCONVENIO.CODCOLIGADA = FBOLETO.CODCOLIGADA)
		LEFT JOIN DBO.VALORES_CALCULADOS_A_RECEBER_FLUXUS_POR_VENDA(@ID_VENDA,@DATA_BASE_D) AS VLR ON (VLR.IDLAN = FLAN.IDLAN AND VLR.CODCOLIGADA = FLAN.CODCOLIGADA)

/*INSERIDO CAMPOS A PEDIDO DO OZIEL - CHAMADO 0624-000097 - CESSÃO DA CARTEIRA PARA O INTER*/
		LEFT JOIN XVENDACOMPL			(NOLOCK) ON (XVENDACOMPL.CODCOLIGADA = XVENDA.CODCOLIGADA AND XVENDACOMPL.NUMVENDA = XVENDA.NUM_VENDA)
		LEFT JOIN GCONSIST				(NOLOCK) ON (GCONSIST.APLICACAO = 'X' AND GCONSIST.CODTABELA = '001' AND GCONSIST.CODCLIENTE = XVENDACOMPL.BANCOCEDIDO)

WHERE	
		FLAN.STATUSLAN NOT IN (2)
		AND FLAN.BAIXAPENDENTE = 0
		AND XVENDA.COD_SIT_VENDA NOT IN (10,60,61,62)
		/*TRAZER TODAS PARCELAS DO CLIENTE
		AND FLAN.DATAVENCIMENTO BETWEEN GETDATE() AND DATEADD(DAY, 30, GETDATE()) */
		
		/*AND XVENDAPARCELA.CODTIPOPARC NOT IN (60)*/
		
	/*BLOQUEIO DAS PARCELAS VENCIDAS APÓS DATA DA CESSAO - CHAMADO 0624-000097 - CESSÃO DA CARTEIRA PARA O INTER*/
		AND ( FLAN.DATAVENCIMENTO <= XVENDACOMPL.DATACESSAO OR XVENDACOMPL.DATACESSAO is null )
		
		AND XVENDA.NUM_VENDA =@ID_VENDA

		/*and flan.idlan in (14760)--,21339)*/

ORDER BY FCFO.NOME, FLAN.DATAVENCIMENTO    