
/* MIRO */ 


DECLARE @DATA_BASE_D AS DATETIME, @MULTA AS DECIMAL(10,5), @MORA AS DECIMAL(10,10)

SET @DATA_BASE_D = GETDATE()
SET @MULTA='0.02'
SET @MORA='0.033333333'

SELECT  

	 'CODCOLIGADA' = GCOLIGADA.CODCOLIGADA /*ADICIONADO A PEDIDO DA ANDREIA SILVA - CHAMADO 0323-000094*/
	 ,'NOME_COLIGADA' = GCOLIGADA.NOME
	 ,'CLIENTE'=DBO.INITCAP(FCFO.NOME)
	 ,'CPF' = FCFO.CGCCFO 
	 ,'COMPRADOR2' = 	 
	 (
		SELECT RESULT.NOMEFANTASIA FROM
			(
				SELECT FCFO.NOMEFANTASIA,
				ROW_NUMBER() OVER (ORDER BY XCOMPRADOR.NUM_VENDA)
				AS CONT
				FROM XCOMPRADOR (NOLOCK)
				INNER JOIN FCFO (NOLOCK) ON FCFO.CODCFO = XCOMPRADOR.CODCFO
				AND FCFO.CODCOLIGADA = XCOMPRADOR.CODCOLCFO
				WHERE XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA
				AND XCOMPRADOR.PRINCIPAL = 0
			) AS RESULT
			WHERE RESULT.CONT = 1
		) 

	 ,'CPF_COMPRADOR2' = 
	  (
		SELECT RESULT.CGCCFO FROM
			(
				SELECT FCFO.CGCCFO,
				ROW_NUMBER() OVER (ORDER BY XCOMPRADOR.NUM_VENDA)
				AS CONT
				FROM XCOMPRADOR (NOLOCK)
				INNER JOIN FCFO (NOLOCK) ON FCFO.CODCFO = XCOMPRADOR.CODCFO
				AND FCFO.CODCOLIGADA = XCOMPRADOR.CODCOLCFO
				WHERE XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA
				AND XCOMPRADOR.PRINCIPAL = 0
			) AS RESULT
			WHERE RESULT.CONT = 1
		)
	
	 ,XVENDA.NUM_VENDA
	 ,'COD_EMPREENDIMENTO' = XVENDA.COD_PESS_EMPR
     ,'NOME_EMPREENDIMENTO' = XEMPREENDIMENTO.NOME 
     ,'CNPJ_EMPREENDIMENTO' = XEMPREENDIMENTO.CNPJ
	 ,'BL/QD'=XITEMVENDA.NUM_UNID 
     ,'APTO/LOTE'=XITEMVENDA.NUM_SUB_UNID 
	 ,'UF' = XEMPREENDIMENTO.UF
     ,'TIPO_PAGTO'=XTIPOPARCELA.DSC_TIPO_PARC
     ,'PARCELA'=XVENDAPARCELA.NUMPARC
     ,'VENCIMENTO'=CONVERT(VARCHAR,FLAN.DATAVENCIMENTO,103)
	 ,'VALOR_ORIGINAL' = CAST((CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END) AS MONEY)
		
   ,'CORREÇÃO'= CAST(ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO (NOLOCK) WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
					-
					/* CORRECAO BAIXADA PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)AS MONEY)
	
	,'JUROS'= CAST(ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO (NOLOCK) WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)  
					-
					/* JUROS BAIXADO PARCIALMENTE */ ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK) 
					INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
					WHERE FLANBAIXA.STATUS <> 1 AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)  AS MONEY)
	
	,'DESCONTO'=CAST(VALORDESCONTO AS MONEY) 
					
	/*INCLUIDO O DESCONTO GERADO VIA ADITIVO*/
	,'DESCONTO_PARCELA' = CAST(ISNULL((SELECT VALOR FROM FLANINTEGRACAO (NOLOCK) 
													WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
															AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
															AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS MONEY)
			
	,'MULTA' = CAST((DBO.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))  AS MONEY)
	,'MORA' = CAST((DBO.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) AS MONEY)
	
	/*ALTERADO CONSULTA PARA BUSCAR VALOR LIQUIDO NA FUNÇÃO*/	
	,'VALOR_ATUALIZADO'	= CAST(dbo.VALOR_LIQUIDO_PARCELAS_SGI(FLAN.CODCOLIGADA, FLAN.IDLAN, @DATA_BASE_D) AS MONEY)
	/*,'VALOR_ATUALIZADO'= CAST((CASE WHEN FLAN.STATUSLAN IN (4) THEN  DBO.SAL_REMANECENTE(XVENDAPARCELA.IDLAN, XVENDAPARCELA.CODCOLIGADA) ELSE FLAN.VALORORIGINAL END)  
			+ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
			+ISNULL((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) 
			+FLAN.VALORJUROS
			+(DBO.MULTA_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D))
			+(DBO.JUROS_PARCELAS_SGI (FLAN.CODCOLIGADA,FLAN.IDLAN, @DATA_BASE_D)) 
			+FLAN.VALOROP8 HONORÁRIO
			 CORRECAO BAIXADA PARCIALMENTE 
			ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK)
									INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
										WHERE FLANBAIXA.STATUS <> 1 
											AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN 
											AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA 
											AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0)
			 JUROS BAIXADO PARCIALMENTE  
			ISNULL((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK)
									INNER JOIN FLANBAIXA (NOLOCK) ON (FLANBAIXA.IDBAIXA = FLANBAIXAINTEGRACAO.IDBAIXA AND FLANBAIXA.IDLAN = FLANBAIXAINTEGRACAO.IDLAN AND FLANBAIXA.CODCOLIGADA = FLANBAIXAINTEGRACAO.CODCOLIGADA)
										WHERE FLANBAIXA.STATUS <> 1 
											AND FLANBAIXAINTEGRACAO.IDLAN = FLAN.IDLAN 
											AND FLANBAIXAINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA 
											AND FLANBAIXAINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)
			-VALORDESCONTO 
			DESCONTO DA PARCELA VIA ADITIVO 
			ISNULL((SELECT VALOR FROM FLANINTEGRACAO (NOLOCK) 
									WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA
											AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN
											AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))),0) AS MONEY)*/
	
	,XSITUACAOVENDA.DSC_SIT_VENDA
	/*ENDEREÇO CONCATENADO RETIRADO DEVIDO AO CHAMADO 1024-001010*/
	/*,'ENDEREÇO' = FCFO.RUA + ', Nº: ' + FCFO.NUMERO + ', BAIRRO: '+ FCFO.BAIRRO + ', CIDADE: ' +GMUNICIPIO.NOMEMUNICIPIO + ', UF: ' + FCFO.CODETD*/

	,FCFO.RUA AS 'RUA'
	,FCFO.NUMERO AS 'NUMERO'
	,FCFO.COMPLEMENTO AS 'COMPLEMENTO'
	,FCFO.CEP AS 'CEP'
	,FCFO.BAIRRO AS 'BAIRRO'
	,GMUNICIPIO.NOMEMUNICIPIO AS 'CIDADE'
	,FCFO.CODETD AS 'UF'

	,'TELEFONE' = ISNULL(FCFO.TELEFONE,FCFO.TELEX)
	,FCFO.EMAIL
	/*ADICIONADO VIA CHAMADO 1123-000069*/
	,FLAN.IDLAN AS 'REF_LANÇAMENTO',


	(
			SELECT RESULT.NOM_PESS FROM
			(
				SELECT XPESSOA.NOM_PESS,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOA ON XPESSOA.COD_PESS = XVENDAFIADOR.CODFIADOR
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 1
		) AS FIADOR_1,
				(
			SELECT RESULT.NOM_PESS FROM
			(
				SELECT XPESSOA.NOM_PESS,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOA ON XPESSOA.COD_PESS = XVENDAFIADOR.CODFIADOR
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 2
		) AS FIADOR_2,
				(
			SELECT RESULT.NOM_PESS FROM
			(
				SELECT XPESSOA.NOM_PESS,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOA ON XPESSOA.COD_PESS = XVENDAFIADOR.CODFIADOR
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 3
		) AS FIADOR_3,

		(
			SELECT RESULT.ENDEREÇO FROM
			(
				SELECT CONCAT(XPESSOAENDERECO.DSC_END,' / ',XPESSOAENDERECO.DSC_NUM,' / ',XPESSOAENDERECO.DSC_COMPL,' / ',XPESSOAENDERECO.NOM_BAIR,' / ',XPESSOAENDERECO.NOM_CID,' / ',XPESSOAENDERECO.SIG_UF,' / ',XPESSOAENDERECO.NUM_CEP,' / ',XPESSOAENDERECO.NUM_CEL,' / ',XPESSOAENDERECO.NUM_TEL) AS ENDEREÇO,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOAENDERECO ON XVENDAFIADOR.CODFIADOR = XPESSOAENDERECO.COD_PESS
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 1
		) AS ENDERECO_FIADOR_1,
				(
			SELECT RESULT.ENDEREÇO FROM
			(
				SELECT CONCAT(XPESSOAENDERECO.DSC_END,' / ',XPESSOAENDERECO.DSC_NUM,' / ',XPESSOAENDERECO.DSC_COMPL,' / ',XPESSOAENDERECO.NOM_BAIR,' / ',XPESSOAENDERECO.NOM_CID,' / ',XPESSOAENDERECO.SIG_UF,' / ',XPESSOAENDERECO.NUM_CEP,' / ',XPESSOAENDERECO.NUM_CEL,' / ',XPESSOAENDERECO.NUM_TEL) AS ENDEREÇO,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOAENDERECO ON XVENDAFIADOR.CODFIADOR = XPESSOAENDERECO.COD_PESS
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 2
		) AS ENDERECO_FIADOR_2,
				(
			SELECT RESULT.ENDEREÇO FROM
			(
				SELECT CONCAT(XPESSOAENDERECO.DSC_END,' / ',XPESSOAENDERECO.DSC_NUM,' / ',XPESSOAENDERECO.DSC_COMPL,' / ',XPESSOAENDERECO.NOM_BAIR,' / ',XPESSOAENDERECO.NOM_CID,' / ',XPESSOAENDERECO.SIG_UF,' / ',XPESSOAENDERECO.NUM_CEP,' / ',XPESSOAENDERECO.NUM_CEL,' / ',XPESSOAENDERECO.NUM_TEL) AS ENDEREÇO,
				ROW_NUMBER() OVER (ORDER BY XVENDAFIADOR.NUMVENDA)
				AS CONT
				FROM XVENDAFIADOR (NOLOCK)
				INNER JOIN XPESSOAENDERECO ON XVENDAFIADOR.CODFIADOR = XPESSOAENDERECO.COD_PESS
				WHERE XVENDAFIADOR.NUMVENDA = XVENDA.NUM_VENDA
			) AS RESULT
			WHERE RESULT.CONT = 3
		) AS ENDERECO_FIADOR_3
				




FROM	XVENDA (NOLOCK)
			LEFT JOIN XVENDAPARCELA			(NOLOCK) ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
			LEFT JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR=XVENDA.COD_PESS_EMPR)
			LEFT JOIN FCFO					(NOLOCK) ON (FCFO.CODCOLIGADA=XVENDA.CODCOLCFO AND FCFO.CODCFO=XVENDA.CODCFO)
			LEFT JOIN XTIPOPARCELA			(NOLOCK) ON (XVENDAPARCELA.CODTIPOPARC=XTIPOPARCELA.COD_TIPO_PARC)
			LEFT JOIN FLAN					(NOLOCK) ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
			LEFT JOIN XMODALIDADEVENDA		(NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
			LEFT JOIN XSITUACAOVENDA		(NOLOCK) ON (XVENDA.COD_SIT_VENDA = XSITUACAOVENDA.COD_SIT_VENDA)
			LEFT JOIN XITEMVENDA			(NOLOCK) ON (XITEMVENDA.NUM_VENDA=XVENDA.NUM_VENDA)
			LEFT JOIN GMUNICIPIO			(NOLOCK) ON (FCFO.CODMUNICIPIO = GMUNICIPIO.CODMUNICIPIO AND FCFO.CODETD = GMUNICIPIO.CODETDMUNICIPIO)
			LEFT JOIN GCOLIGADA				(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XVENDA.CODCOLIGADA)
			LEFT JOIN XEMPREENDIMENTOCOMPL	(NOLOCK) ON (XEMPREENDIMENTOCOMPL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA AND XEMPREENDIMENTOCOMPL.CODPESSEMPR = XEMPREENDIMENTO.COD_PESS_EMPR) 
			LEFT JOIN XVENDACOMPL			(NOLOCK) ON (XVENDA.NUM_VENDA = XVENDACOMPL.NUMVENDA AND XVENDACOMPL.CODCOLIGADA = XVENDA.CODCOLIGADA )

WHERE				
			XTIPOPARCELA.COD_TIPO_PARC NOT IN (26,101,106,13,60,90,554,110,95,153)
			AND XVENDA.COD_SIT_VENDA NOT IN (60,61,62,10)
			AND FLAN.STATUSLAN IN (0,4)
			AND DBO.QTD_PARCELA_MAIOR_180_DIAS(XVENDA.NUM_VENDA,XVENDA.CODCOLIGADA) > 0 /*FUNÇÃO PEGA PARCFELAS MAIOR QUE 5 DIAS*/
			AND FLAN.BAIXAPENDENTE = 0
			AND XVENDACOMPL.BANCOCEDIDO IS NULL
			/*INCLUIDO A PEDIDO DA COBRANÇA 0524-000671*/

			AND (XVENDACOMPL.DISTRIBUICAOJUDICIAL = '4' OR (XVENDACOMPL.DISTRIBUICAOJUDICIAL IS NULL AND XEMPREENDIMENTOCOMPL.INTEGRACAOAPI IN ('1','5'))) /* CONDIÇÃO PARA TRAZER APENAS A MIRO - CHAMADO 0425-000881 */
			
			/* REMOVIDO NO DIA 25/04 CONFORME SOLICITAÇÃO DA JENNIFFER LOUISE - CHAMADO 0425-000881
			(
					XVENDACOMPL.JUSTICA IN ('1','3') AND XVENDACOMPL.DISTRIBUICAOJUDICIAL IN ('4')
					OR 
					XVENDACOMPL.JUSTICA NOT IN ('1') AND XEMPREENDIMENTOCOMPL.INTEGRACAOAPI IN ('1','5')
					OR
					XVENDACOMPL.JUSTICA IS NULL AND XEMPREENDIMENTOCOMPL.INTEGRACAOAPI IN ('1','5')
	
			)*/
														/*CONTROLE DE INTEGRAÇÃO DO EMPREENDIMENTO*/
															/*
															1 - AMBOS
															2 - GRUPO BARCELOS
															3 - CANDIOTTO VALLE ADVOGADOS
															4 - NÃO INTEGRAR EMPREENDIMENTO
															5 - MIRO
															*/

					AND FLAN.DATAVENCIMENTO BETWEEN :DATA_VENCIMENTO_INICIAL AND :DATA_VENCIMENTO_FINAL
			
					
					/*
					 LINHA COMENTADA DE ACORDO COM CHAMADO 1022-000664 VERIFCADO POR MARCELO E MARCOS   
					
					AND XVENDA.COD_PESS_EMPR NOT IN ('17564','17552','17550','17634','17551','17549','17642','17643','17644','17560','17616','17633','17645','17637','17639')
					
					*/
			

     
ORDER BY FCFO.NOME    




