DECLARE 
		@CODCOLIGADA INT = (37),
		@DATA_IN DATE = '20230101',
		@DATA_FIN DATE = '20240823',
		@EMPREENDIMENTO VARCHAR(40) = '17671',
		@INDICE DECIMAL(15, 4),
	    @DATA_VENC DATE = GETDATE();
		

/* TAB 1 */		
WITH DATAEFETIVA
     AS ((SELECT DISTINCT 
		CASE
			WHEN VENDADIRETA.DATAEMISSAO IS NOT NULL												THEN VENDADIRETA.DATAEMISSAO
            WHEN VENDADIRETA.DATAEMISSAO IS NULL AND VENDA.DAT_VENDA > XUNCOMPL.DTPRIMEIRADEMANDA	THEN VENDA.DAT_VENDA
            WHEN VENDADIRETA.DATAEMISSAO IS NULL AND VENDA.DAT_VENDA <= XUNCOMPL.DTPRIMEIRADEMANDA	THEN XUNCOMPL.DTPRIMEIRADEMANDA
            ELSE VENDA.DAT_VENDA 
         END DATA,
         VENDA.CODCOLIGADA,
         VENDA.NUM_VENDA

         FROM XVENDA				VENDA (NOLOCK)
         LEFT JOIN XVENDACOMPL		COMPL (NOLOCK)									ON VENDA.CODCOLIGADA = COMPL.CODCOLIGADA			AND VENDA.NUM_VENDA = COMPL.NUMVENDA
         LEFT JOIN GCOTACAO			GC (NOLOCK)										ON SIMBOLO = 'INCC'
         INNER JOIN XITEMVENDA		XITEM (NOLOCK)									ON VENDA.NUM_VENDA = XITEM.NUM_VENDA
         INNER JOIN XUNIDADE		XUN (NOLOCK)									ON XITEM.COD_PESS_EMPR = XUN.COD_PESS_EMPR			AND XITEM.NUM_UNID = XUN.NUM_UNID
         LEFT JOIN XUNIDADECOMPL	XUNCOMPL (NOLOCK)								ON XUN.COD_PESS_EMPR = XUNCOMPL.COD_PESS_EMPR		AND XUN.NUM_UNID = XUNCOMPL.NUM_UNID
         LEFT JOIN XSITUACAOVENDA	XSITUACAO (NOLOCK)								ON VENDA.COD_SIT_VENDA = XSITUACAO.COD_SIT_VENDA	AND Upper(XSITUACAO.DSC_SIT_VENDA) NOT LIKE 'DISTRATADA'
         OUTER APPLY	
				(SELECT Max(XREGRAADIT.DATA_EMISSAO) AS DATAEMISSAO		
                 FROM   XADIT									(NOLOCK)
                 INNER JOIN XADITRENEGOCIACAO					(NOLOCK)ON XADIT.CODCOLIGADA = XADITRENEGOCIACAO.CODCOLIGADA					AND XADIT.NUMVENDA = XADITRENEGOCIACAO.NUMVENDA						AND XADIT.NUMADIT = XADITRENEGOCIACAO.NUMADIT
                 INNER JOIN XADITRENEGOCIACAOPARC				(NOLOCK)ON XADITRENEGOCIACAO.CODCOLIGADA = XADITRENEGOCIACAOPARC.CODCOLIGADA	AND XADITRENEGOCIACAO.NUMVENDA = XADITRENEGOCIACAOPARC.NUMVENDA		AND XADITRENEGOCIACAO.NUMADIT = XADITRENEGOCIACAOPARC.NUMADIT
                 INNER JOIN XREGRACOMPONENTEVENDA XREGRAADIT	(NOLOCK)ON XADITRENEGOCIACAOPARC.CODCOLIGADA = XREGRAADIT.CODCOLIGADA			AND XADITRENEGOCIACAOPARC.NUMVENDA = XREGRAADIT.NUM_VENDA			AND XADITRENEGOCIACAOPARC.NUMADIT = XREGRAADIT.COD_GRUPO_REF
                 INNER JOIN XCOMPONENTE XCOMPO					(NOLOCK)ON XREGRAADIT.COD_COMPN = XCOMPO.COD_COMPN								AND XCOMPO.DSC_COMPN LIKE '%Financiamento%'
                 INNER JOIN XTIPOPARCELA XTIPOPARC				(NOLOCK)ON XCOMPO.COD_TIPO_PARC = XTIPOPARC.COD_TIPO_PARC						AND XTIPOPARC.DSC_TIPO_PARC LIKE '%Financiamento%'
                 INNER JOIN XPARCELACOMPONENTE XPARCCOMP		(NOLOCK)ON XREGRAADIT.CODCOLIGADA = XPARCCOMP.CODCOLIGADA						AND XREGRAADIT.NUM_VENDA = XPARCCOMP.NUM_VENDA						AND XREGRAADIT.COD_GRUPO = XPARCCOMP.COD_GRUPO					AND XTIPOPARC.COD_TIPO_PARC = XPARCCOMP.COD_TIPO_PARC		AND XCOMPO.COD_COMPN = XPARCCOMP.COD_COMPN
                 LEFT JOIN FLAN FL								(NOLOCK)ON XPARCCOMP.CODCOLLAN = FL.CODCOLIGADA									AND XPARCCOMP.IDLAN = FL.IDLAN										AND FL.STATUSLAN <> 2
                 INNER JOIN XVENDA X							(NOLOCK)ON XADIT.NUMVENDA = X.NUM_VENDA
                 INNER JOIN XMODALIDADEVENDA XMOD				(NOLOCK)ON X.COD_MOD_VENDA = XMOD.COD_MOD_VENDA									AND ( XMOD.DSC_MOD_VENDA = 'PLANO DE VENDA DIRETA' OR XMOD.DSC_MOD_VENDA LIKE '%Venda Direta%' )
                 WHERE  XADIT.NUMVENDA = VENDA.NUM_VENDA
                 AND XADIT.DSCADIT NOT LIKE '%INCC%')VENDADIRETA)),

/* TAB 2 */			 
DEFASAGEM
     AS (SELECT 
				CASE
					WHEN DATAASSCEF <= '2024/03/22' AND EOMONTH(Max(DATA)) >= DATAASSCEF THEN 0
					WHEN DATAASSCEF <= '2024/03/22' AND Month(Max(DATA)) = Month(Dateadd(MM, -1, DATAASSCEF)) AND Year(Max(DATA)) = Year(Dateadd(MM, -1, DATAASSCEF)) THEN 1
                ELSE 2
                END DEFASAGEM,
                XVENDACOMPL.NUMVENDA,
                XVENDACOMPL.CODCOLIGADA

				FROM   XVENDACOMPL		(NOLOCK)
                LEFT JOIN GCOTACAO		(NOLOCK) ON SIMBOLO = 'INCC'

				WHERE  CODCOLIGADA IN (@CODCOLIGADA)
				GROUP  BY 
				NUMVENDA,
                DATAASSCEF,
                CODCOLIGADA), 
				
/* TAB 3 */				
BAIXA
     AS (SELECT Sum (ISNULL(XPARCELACOMPONENTE.VR_BAIXA, 0)) VALOR,
                XVENDA.CODCOLIGADA,
                XVENDA.NUM_VENDA
				FROM   XVENDA						(NOLOCK)
                INNER JOIN XREGRACOMPONENTEVENDA	(NOLOCK)ON XVENDA.CODCOLIGADA = XREGRACOMPONENTEVENDA.CODCOLIGADA AND XVENDA.NUM_VENDA = XREGRACOMPONENTEVENDA.NUM_VENDA
                INNER JOIN XPARCELACOMPONENTE		(NOLOCK)ON XREGRACOMPONENTEVENDA.CODCOLIGADA = XPARCELACOMPONENTE.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA = XPARCELACOMPONENTE.NUM_VENDA AND XREGRACOMPONENTEVENDA.COD_GRUPO = XPARCELACOMPONENTE.COD_GRUPO AND XREGRACOMPONENTEVENDA.COD_COMPN = XPARCELACOMPONENTE.COD_COMPN
                CROSS APPLY 
							(SELECT XREGRACOMP.COD_GRUPO
                             FROM   XREGRACOMPONENTEVENDA XREGRACOMP	(NOLOCK)
                             INNER JOIN XCOMPONENTE XCOMP				(NOLOCK)ON XREGRACOMP.COD_COMPN = XCOMP.COD_COMPN AND XCOMP.DSC_COMPN LIKE 'Financiamento%' AND XCOMP.DSC_COMPN NOT LIKE '%INCC%'
                             WHERE  XREGRACOMP.CODCOLIGADA = XVENDA.CODCOLIGADA
                             AND XREGRACOMP.NUM_VENDA = XVENDA.NUM_VENDA
                             AND XREGRACOMP.COD_GRUPO = XPARCELACOMPONENTE.COD_GRUPO) GRUPOIN
                CROSS APPLY 
							(SELECT Max(XREGRACOMP.COD_GRUPO) COD_GRUPO
                             FROM   XREGRACOMPONENTEVENDA XREGRACOMP	(NOLOCK)
                             INNER JOIN XCOMPONENTE XCOMP				(NOLOCK)ON XREGRACOMP.COD_COMPN = XCOMP.COD_COMPN AND XCOMP.DSC_COMPN LIKE 'Financiamento%' AND XCOMP.DSC_COMPN NOT LIKE '%INCC%'
                             WHERE  XREGRACOMP.CODCOLIGADA = XVENDA.CODCOLIGADA
                             AND XREGRACOMP.NUM_VENDA = XVENDA.NUM_VENDA) GRUPONOT
							 WHERE  XVENDA.CODCOLIGADA IN (@CODCOLIGADA)
							 AND GRUPOIN.COD_GRUPO <> GRUPONOT.COD_GRUPO
							 AND XPARCELACOMPONENTE.VR_BAIXA > 0
							 GROUP  BY XVENDA.CODCOLIGADA,
							 XVENDA.NUM_VENDA)

/*
SELECT * 
FROM BAIXA
*/

SELECT
XVENDA.CODCOLIGADA
,XVENDA.NUM_VENDA
,XVENDA.DAT_VENDA
,XVENDA.DATAASSINATURA
,XVENDACOMPL.DATAASSCEF
,XVENDA.COD_PESS_EMPR
,XVENDA.COD_MOD_VENDA
,XVENDA.DATAENTREGACHAVE
,XVENDA.VALOR_VENDA
,XEMPREENDIMENTO.NOME 
,FCFO.NOMEFANTASIA AS CLIENTE
,XMODALIDADEVENDA.DSC_MOD_VENDA 
,XSITUACAOVENDA.DSC_SIT_VENDA,

(CASE WHEN (
		SELECT TOP 1
		ISNULL((SELECT SUM (CONVERT(DECIMAL(10,4),VALOR))
		FROM FLANINTEGRACAO (NOLOCK) 
		INNER JOIN XVENDAPARCELA AS XVENDAPARCELA1	(NOLOCK) ON (XVENDAPARCELA1.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA1.CODCOLLAN = XVENDA.CODCOLIGADA AND XVENDAPARCELA1.CODGRUPO IN (3,4,8, 10))
		INNER JOIN FLAN								(NOLOCK) ON (FLAN.IDLAN = FLANINTEGRACAO.IDLAN AND FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.STATUSLAN IN (1, 4))
		WHERE FLANINTEGRACAO.IDLAN = XVENDAPARCELA1.IDLAN 
		AND FLANINTEGRACAO.CODCOLIGADA = XVENDAPARCELA1.CODCOLLAN
		/*AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(XVENDAPARCELA1.CODCOLLAN,'FIN_CEF'))*/
		),0)) = 0.0000
		THEN 
		(Sum(XREGRACOMPONENTEVENDA.VR_PARTE_COMPN)
		   + ISNULL(Max(BAIXA.VALOR), 0))
		ELSE 
		(
		SELECT TOP 1
		ISNULL((SELECT SUM (CONVERT(DECIMAL(10,4),VALOR))
		FROM FLANINTEGRACAO (NOLOCK) 
		INNER JOIN XVENDAPARCELA AS XVENDAPARCELA1	(NOLOCK) ON (XVENDAPARCELA1.NUMVENDA = XVENDA.NUM_VENDA AND XVENDAPARCELA1.CODCOLLAN = XVENDA.CODCOLIGADA AND XVENDAPARCELA1.CODGRUPO IN (3,4,8, 10))
		INNER JOIN FLAN								(NOLOCK) ON (FLAN.IDLAN = FLANINTEGRACAO.IDLAN AND FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.STATUSLAN IN (1, 4))
		WHERE FLANINTEGRACAO.IDLAN = XVENDAPARCELA1.IDLAN 
		AND FLANINTEGRACAO.CODCOLIGADA = XVENDAPARCELA1.CODCOLLAN
		/*AND FLANINTEGRACAO.IDCAMPO IN (SELECT IDCAMPO FROM DBO.RETORNA_IDCAMPO_JUROS(XVENDAPARCELA1.CODCOLLAN,'FIN_CEF'))*/
		),0)) END) AS 'FIN_CEF_TOTAL'

, Sum(XREGRACOMPONENTEVENDA.VR_PARTE_COMPN) + ISNULL(Max(BAIXA.VALOR), 0) AS 'VALOR_FINANCIADO'

/* DESMEMBRANDO O VALOR ACUMULADO */

/*PRIMEIRO CASE */

(SELECT GC.DATA,
	
(CASE
                           WHEN GC.DATA < Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN 0
                           WHEN ( LAG(GC.FATOR, 2, 0) OVER (ORDER BY Year(GC.DATA)) ) = 0 THEN 0
                      ELSE ( Round(( GC.FATOR / ( LAG(GC.FATOR, 1, 0)OVER (ORDER BY Year(GC.DATA)) ) ), 4) * 100 ) - 100
                      END ) / Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME))) * (CASE
                                                                                                 WHEN Month(DATAEFETIVA.DATA) = Month(COMPL.DATAASSCEF) AND Year(DATAEFETIVA.DATA) = Year(COMPL.DATAASSCEF) AND GC.DATA = Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF)
                                                                                                 WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Month(GC.DATA) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Year(GC.DATA) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(COMPL.DATAASSCEF) + ( Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF) ) - ( Datediff (DAY, Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA), Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) )
                                                                                                 WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Month(Dateadd(MONTH, 0, GC.DATA)) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Year(Dateadd(MONTH, 0, GC.DATA)) AND Dateadd(MONTH, 0, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) < Dateadd(MONTH, 0, Dateadd(DD, -( Day(COMPL.DATAASSCEF) - 1 ), COMPL.DATAASSCEF)) THEN Datediff (DAY, DATAEFETIVA.DATA, EOMONTH(Cast(DATAEFETIVA.DATA AS DATETIME)))
                                                                                                 WHEN GC.DATA BETWEEN Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) )) AND Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME)))
                                                                                             ELSE 0
                                                                                             END) AS ACUMULADO
        FROM   XVENDA VENDA (NOLOCK)
        LEFT JOIN XVENDACOMPL COMPL			(NOLOCK)ON VENDA.CODCOLIGADA = COMPL.CODCOLIGADA		AND VENDA.NUM_VENDA = COMPL.NUMVENDA 
        LEFT JOIN GCOTACAO GC				(NOLOCK)ON SIMBOLO = 'INCC'
        INNER JOIN XITEMVENDA XITEM			(NOLOCK)ON VENDA.NUM_VENDA = XITEM.NUM_VENDA
        INNER JOIN XUNIDADE XUN				(NOLOCK)ON XITEM.COD_PESS_EMPR = XUN.COD_PESS_EMPR		AND XITEM.NUM_UNID = XUN.NUM_UNID
        LEFT JOIN XUNIDADECOMPL XUNCOMPL	(NOLOCK)ON XUN.COD_PESS_EMPR = XUNCOMPL.COD_PESS_EMPR	AND XUN.NUM_UNID = XUNCOMPL.NUM_UNID
        WHERE  VENDA.CODCOLIGADA = XVENDA.CODCOLIGADA
        AND VENDA.NUM_VENDA = XVENDA.NUM_VENDA
        AND CONVERT(DATE, GC.DATA) BETWEEN CONVERT(DATE, Dateadd(MONTH, -4, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) ))) AND CONVERT(DATE, COMPL.DATAASSCEF))

,(SELECT Sum(ACUMULADO.ACUMULADO)
        FROM (SELECT (CASE
                           WHEN GC.DATA < Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN 0
                           WHEN ( LAG(GC.FATOR, 2, 0) OVER (ORDER BY Year(GC.DATA)) ) = 0 THEN 0
                      ELSE ( Round(( GC.FATOR / ( LAG(GC.FATOR, 1, 0)OVER (ORDER BY Year(GC.DATA)) ) ), 4) * 100 ) - 100
                      END ) / Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME))) * (CASE
                                                                                                 WHEN Month(DATAEFETIVA.DATA) = Month(COMPL.DATAASSCEF) AND Year(DATAEFETIVA.DATA) = Year(COMPL.DATAASSCEF) AND GC.DATA = Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF)
                                                                                                 WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Month(GC.DATA) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Year(GC.DATA) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(COMPL.DATAASSCEF) + ( Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF) ) - ( Datediff (DAY, Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA), Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) )
                                                                                                 WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Month(Dateadd(MONTH, 0, GC.DATA)) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Year(Dateadd(MONTH, 0, GC.DATA)) AND Dateadd(MONTH, 0, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) < Dateadd(MONTH, 0, Dateadd(DD, -( Day(COMPL.DATAASSCEF) - 1 ), COMPL.DATAASSCEF)) THEN Datediff (DAY, DATAEFETIVA.DATA, EOMONTH(Cast(DATAEFETIVA.DATA AS DATETIME)))
                                                                                                 WHEN GC.DATA BETWEEN Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) )) AND Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME)))
                                                                                             ELSE 0
                                                                                             END) AS ACUMULADO
        FROM   XVENDA VENDA (NOLOCK)
        LEFT JOIN XVENDACOMPL COMPL			(NOLOCK)ON VENDA.CODCOLIGADA = COMPL.CODCOLIGADA		AND VENDA.NUM_VENDA = COMPL.NUMVENDA 
        LEFT JOIN GCOTACAO GC				(NOLOCK)ON SIMBOLO = 'INCC'
        INNER JOIN XITEMVENDA XITEM			(NOLOCK)ON VENDA.NUM_VENDA = XITEM.NUM_VENDA
        INNER JOIN XUNIDADE XUN				(NOLOCK)ON XITEM.COD_PESS_EMPR = XUN.COD_PESS_EMPR		AND XITEM.NUM_UNID = XUN.NUM_UNID
        LEFT JOIN XUNIDADECOMPL XUNCOMPL	(NOLOCK)ON XUN.COD_PESS_EMPR = XUNCOMPL.COD_PESS_EMPR	AND XUN.NUM_UNID = XUNCOMPL.NUM_UNID
        WHERE  VENDA.CODCOLIGADA = XVENDA.CODCOLIGADA
        AND VENDA.NUM_VENDA = XVENDA.NUM_VENDA
        AND CONVERT(DATE, GC.DATA) BETWEEN CONVERT(DATE, Dateadd(MONTH, -4, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) ))) AND CONVERT(DATE, COMPL.DATAASSCEF)) AS ACUMULADO) AS INDICE,
		CASE
			WHEN XADIT.NUMVENDA IS NULL THEN ( ( Sum(XREGRACOMPONENTEVENDA.VR_PARTE_COMPN) + ISNULL(Max(BAIXA.VALOR), 0) ) * (	SELECT Sum(ACUMULADO.ACUMULADO) / 100
																																FROM   (SELECT ( ( CASE
																																WHEN GC.DATA < Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN 0
            WHEN ( LAG(GC.FATOR, 2, 0) OVER (ORDER BY Year(GC.DATA)) ) = 0 THEN 0
            ELSE ( ( GC.FATOR / ( LAG(GC.FATOR, 1, 0)OVER (ORDER BY Year(GC.DATA)) ) ) * 100 ) - 100 END ) / Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME))) ) * CASE
																																												WHEN Month(DATAEFETIVA.DATA) = Month(COMPL.DATAASSCEF) AND Year(DATAEFETIVA.DATA) = Year(COMPL.DATAASSCEF) AND GC.DATA = Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) THEN Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF)
																																												WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Month(GC.DATA) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) = Year(GC.DATA) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(COMPL.DATAASSCEF) + ( Datediff (DAY, DATAEFETIVA.DATA, COMPL.DATAASSCEF) ) - ( Datediff (DAY, Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA), Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF)) )
																																												WHEN Month(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Month(Dateadd(MONTH, 0, GC.DATA)) AND Year(Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, DATAEFETIVA.DATA)) = Year(Dateadd(MONTH, 0, GC.DATA)) AND Dateadd(MONTH, 0, Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA)) < Dateadd(MONTH, 0, Dateadd(DD, -( Day(COMPL.DATAASSCEF) - 1 ), COMPL.DATAASSCEF)) THEN Datediff (DAY, DATAEFETIVA.DATA, EOMONTH(Cast(DATAEFETIVA.DATA AS DATETIME)))
																																												WHEN GC.DATA BETWEEN Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) )) AND Dateadd(MONTH, -DEFASAGEM.DEFASAGEM, COMPL.DATAASSCEF) AND Month(DATAEFETIVA.DATA) <> Month(COMPL.DATAASSCEF) THEN Day(EOMONTH(Cast(Dateadd(MONTH, -0, GC.DATA) AS DATETIME)))
                                                                                                                                                                             ELSE 0
                                                                                                                                                                             END AS ACUMULADO
																																											 FROM   XVENDA VENDA (NOLOCK)
																																											 LEFT JOIN XVENDACOMPL COMPL (NOLOCK)ON VENDA.CODCOLIGADA = COMPL.CODCOLIGADA AND VENDA.NUM_VENDA = COMPL.NUMVENDA
																																											 LEFT JOIN GCOTACAO GC (NOLOCK)ON SIMBOLO = 'INCC'
																																											 INNER JOIN XITEMVENDA XITEM (NOLOCK)ON VENDA.NUM_VENDA = XITEM.NUM_VENDA
																																											 INNER JOIN XUNIDADE XUN (NOLOCK)ON XITEM.COD_PESS_EMPR = XUN.COD_PESS_EMPR AND XITEM.NUM_UNID = XUN.NUM_UNID
																																											 LEFT JOIN XUNIDADECOMPL XUNCOMPL (NOLOCK)ON XUN.COD_PESS_EMPR = XUNCOMPL.COD_PESS_EMPR AND XUN.NUM_UNID = XUNCOMPL.NUM_UNID
																																											 WHERE  VENDA.CODCOLIGADA = XVENDA.CODCOLIGADA
																																											 AND VENDA.NUM_VENDA = XVENDA.NUM_VENDA
																																											 AND CONVERT(DATE, GC.DATA)BETWEEN CONVERT(DATE, Dateadd(MONTH, -4, ( Dateadd(DD, -( Day(DATAEFETIVA.DATA) - 1 ), DATAEFETIVA.DATA) ))) AND CONVERT(DATE, COMPL.DATAASSCEF)) AS ACUMULADO) )
         ELSE 0
       END  AS VALOR_COBRADO
        ,XUNIDADECOMPL.DTPRIMEIRADEMANDA
	    ,XREGRA.VR_PARTE_COMPN AS VALOR_TOTAL_ADIT_INCC
		,XREGRA.QTD_PARC AS QTD_PARC_ADIT_INCC
		,XREGRA.VRUNTPARCELA AS VALOR_UNIT_ADIT_INCC
		,XREGRA.DAT_INI_CALC AS DATA_VENCIMENTO_INCC
		,CASE 
				WHEN XADIT.CODSITADIT = 1 THEN 'EM PREPARAÇÃO'
				WHEN XADIT.CODSITADIT = 2 THEN 'EFETIVADO'
				WHEN XADIT.CODSITADIT = 3 THEN 'CANCELADO'
		 ELSE ' ' 
		 END AS SITUACAO_ADITIVO
		 ,CASE 
				WHEN CONVERT(VARCHAR(20), XADIT.NUMADIT) IS NULL AND FORMAT(XUNIDADECOMPL.DTPRIMEIRADEMANDA,'yyyy-MM-dd') = FORMAT(XVENDACOMPL.DATAASSCEF,'yyyy-MM-dd') THEN 'DATA DA ASS CAIXA IGUAL DATA DA PRIMEIRA DEMANDA'
				WHEN CONVERT(VARCHAR(20), XADIT.NUMADIT) IS NULL AND FORMAT(XVENDACOMPL.DATAASSCEF,'yyyy-MM-dd') IS NULL THEN 'NÃO ASSINOU CONTRATO CEF'
				WHEN CONVERT(VARCHAR(20), XADIT.NUMADIT) IS NULL AND FORMAT(XVENDACOMPL.DATAASSCEF,'yyyy-MM-dd') IS NOT NULL THEN 'PENDENTE CONFECCÇÃO'
		 ELSE 'ADITIVO CONFECCIONADO'
		 END AS NUM_ADITIVO
		 ,XREGRA.RECCREATEDBY AS USUARIO_CRIACAO_INCC
		 ,(	SELECT  TOP 1 FLAN.DATAVENCIMENTO
			FROM XVENDAPARCELA XVENDA_PARC (NOLOCK)
			LEFT JOIN FLAN					(NOLOCK) ON FLAN.CODCOLIGADA = XVENDA_PARC.CODCOLIGADA AND FLAN.IDLAN = XVENDA_PARC.IDLAN
			INNER JOIN XCOMPONENTE			(NOLOCK) ON XCOMPONENTE.COD_TIPO_PARC = XVENDA_PARC.CODTIPOPARC
			WHERE XCOMPONENTE.COD_COMPN NOT IN (105,107,110,111,4,11,106,554,3,108,500,515,530,553,91,5,6,7,8,10,12,14,18,20,21,93,99,47,37,57,58,63,88)
			AND XVENDA_PARC.NUMVENDA = XVENDA.NUM_VENDA
			AND ( (DAY(@DATA_VENC) > 15 AND DATEPART(YEAR, FLAN.DATAVENCIMENTO) = DATEPART(YEAR, DATEADD(MONTH, 2, GETDATE())) AND DATEPART(MONTH, FLAN.DATAVENCIMENTO) = DATEPART(MONTH, DATEADD(MONTH, 2, GETDATE()))
) OR (DAY(@DATA_VENC) <= 15 AND DATEPART(YEAR, FLAN.DATAVENCIMENTO) = DATEPART(YEAR, DATEADD(MONTH, 1, @DATA_VENC)) AND DATEPART(MONTH, FLAN.DATAVENCIMENTO) = DATEPART(MONTH, DATEADD(MONTH, 1, @DATA_VENC))))
	ORDER BY FLAN.DATAVENCIMENTO )AS PROX_VENC

		 ,(	SELECT COUNT(DISTINCT DATEPART(YEAR, LAN.DATAVENCIMENTO) * 100 + DATEPART(MONTH, LAN.DATAVENCIMENTO)) 
			FROM XVENDAPARCELA (NOLOCK)
			INNER JOIN FLAN LAN				(NOLOCK) ON LAN.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND LAN.IDLAN = XVENDAPARCELA.IDLAN
			INNER JOIN XCOMPONENTE			(NOLOCK) ON XCOMPONENTE.COD_TIPO_PARC = XVENDAPARCELA.CODTIPOPARC
			WHERE XVENDAPARCELA.NUMVENDA = XVENDA.NUM_VENDA
			AND XCOMPONENTE.COD_COMPN NOT IN (105,107,110,111,4,11,106,554,3,108,500,515,530,553,91,5,6,7,8,10,12,14,18,20,21,93,99,47,37,57,58,63,88)
			AND LAN.STATUSLAN IN (0,4)
			AND LAN.DATAVENCIMENTO >= (	SELECT  TOP 1 FLAN.DATAVENCIMENTO
										FROM XVENDAPARCELA XVENDA_PARC (NOLOCK)
										LEFT JOIN FLAN					(NOLOCK) ON FLAN.CODCOLIGADA = XVENDA_PARC.CODCOLIGADA AND FLAN.IDLAN = XVENDA_PARC.IDLAN
										INNER JOIN XCOMPONENTE			(NOLOCK) ON XCOMPONENTE.COD_TIPO_PARC = XVENDA_PARC.CODTIPOPARC
										WHERE XCOMPONENTE.COD_COMPN NOT IN (105,107,110,111,4,11,106,554,3,108,500,515,530,553,91,5,6,7,8,10,12,14,18,20,21,93,99,47,37,57,58,63,88)
										AND XVENDA_PARC.NUMVENDA = XVENDA.NUM_VENDA
										AND ((DAY(@DATA_VENC) > 15 AND DATEPART(YEAR, FLAN.DATAVENCIMENTO) = DATEPART(YEAR, DATEADD(MONTH, 2, GETDATE())) AND DATEPART(MONTH, FLAN.DATAVENCIMENTO) = DATEPART(MONTH, DATEADD(MONTH, 2, GETDATE()))
) OR (DAY(@DATA_VENC) <= 15 AND DATEPART(YEAR, FLAN.DATAVENCIMENTO) = DATEPART(YEAR, DATEADD(MONTH, 1, @DATA_VENC)) AND DATEPART(MONTH, FLAN.DATAVENCIMENTO) = DATEPART(MONTH, DATEADD(MONTH, 1, @DATA_VENC)))))) AS QTS_PARCELAS
		  
FROM XVENDA (NOLOCK)
INNER JOIN XMODALIDADEVENDA		(NOLOCK) ON XVENDA.COD_MOD_VENDA = XMODALIDADEVENDA.COD_MOD_VENDA
INNER JOIN XCOMPRADOR			(NOLOCK) ON XVENDA.CODCOLIGADA = XCOMPRADOR.CODCOLIGADA AND XVENDA.NUM_VENDA = XCOMPRADOR.NUM_VENDA AND XCOMPRADOR.PRINCIPAL = 1
INNER JOIN FCFO					(NOLOCK) ON XCOMPRADOR.CODCOLCFO = FCFO.CODCOLIGADA AND XCOMPRADOR.CODCFO = FCFO.CODCFO
INNER JOIN XEMPREENDIMENTO		(NOLOCK) ON XVENDA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA AND XVENDA.COD_PESS_EMPR = XEMPREENDIMENTO.COD_PESS_EMPR
INNER JOIN XSITUACAOVENDA		(NOLOCK) ON XVENDA.COD_SIT_VENDA = XSITUACAOVENDA.COD_SIT_VENDA
LEFT JOIN XREGRACOMPONENTEVENDA (NOLOCK) ON XVENDA.CODCOLIGADA = XREGRACOMPONENTEVENDA.CODCOLIGADA AND XVENDA.NUM_VENDA = XREGRACOMPONENTEVENDA.NUM_VENDA AND XREGRACOMPONENTEVENDA.COD_GRUPO = ISNULL((SELECT Max(XREGRACOMP.COD_GRUPO)
																																																		FROM   XREGRACOMPONENTEVENDA XREGRACOMP (NOLOCK)
																																																		INNER JOIN XCOMPONENTE XCOMP (NOLOCK)ON XREGRACOMP.COD_COMPN = XCOMP.COD_COMPN AND XCOMP.DSC_COMPN LIKE 'Financiamento%' AND XCOMP.DSC_COMPN NOT LIKE '%INCC%'
																																																		WHERE  XREGRACOMP.CODCOLIGADA = XVENDA.CODCOLIGADA
																																																		AND XREGRACOMP.NUM_VENDA = XVENDA.NUM_VENDA), 0)
LEFT JOIN XVENDACOMPL	(NOLOCK) ON XVENDA.CODCOLIGADA = XVENDACOMPL.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDACOMPL.NUMVENDA
LEFT JOIN GCOTACAO		(NOLOCK) ON GCOTACAO.SIMBOLO = 'INCC' AND Month(DATA) = Month(Dateadd(MONTH, -1, XVENDACOMPL.DATAASSCEF)) AND Year(DATA) = Year(Dateadd(MONTH, -1, XVENDACOMPL.DATAASSCEF))
INNER JOIN XITEMVENDA	(NOLOCK) ON XVENDA.NUM_VENDA = XITEMVENDA.NUM_VENDA
INNER JOIN XUNIDADE		(NOLOCK) ON XITEMVENDA.COD_PESS_EMPR = XUNIDADE.COD_PESS_EMPR AND XITEMVENDA.NUM_UNID = XUNIDADE.NUM_UNID
LEFT JOIN XUNIDADECOMPL (NOLOCK) ON XUNIDADE.COD_PESS_EMPR = XUNIDADECOMPL.COD_PESS_EMPR AND XUNIDADE.NUM_UNID = XUNIDADECOMPL.NUM_UNID
LEFT JOIN DATAEFETIVA			 ON XVENDA.CODCOLIGADA = DATAEFETIVA.CODCOLIGADA AND XVENDA.NUM_VENDA = DATAEFETIVA.NUM_VENDA
LEFT JOIN DEFASAGEM				 ON XVENDA.NUM_VENDA = DEFASAGEM.NUMVENDA AND XVENDA.CODCOLIGADA = DEFASAGEM.CODCOLIGADA
LEFT JOIN BAIXA					 ON XVENDA.CODCOLIGADA = BAIXA.CODCOLIGADA AND XVENDA.NUM_VENDA = BAIXA.NUM_VENDA
LEFT JOIN XADIT			(NOLOCK) ON XADIT.NUMVENDA = XVENDA.NUM_VENDA AND XADIT.CODCOLIGADA = XVENDA.CODCOLIGADA AND XADIT.DSCADIT LIKE '%INCC%'
LEFT JOIN XREGRACOMPONENTEVENDA XREGRA (NOLOCK) ON XVENDA.CODCOLIGADA = XREGRA.CODCOLIGADA AND XVENDA.NUM_VENDA = XREGRA.NUM_VENDA AND XREGRA.COD_COMPN = 93

WHERE  XMODALIDADEVENDA.DSC_MOD_VENDA <> 'Financiamento Proprio'
       AND CONVERT(VARCHAR, XVENDA.CODCOLIGADA) IN (@CODCOLIGADA)
       AND XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
	   AND XVENDA.DAT_VENDA BETWEEN @DATA_IN AND @DATA_FIN
	   AND XVENDA.COD_SIT_VENDA NOT IN (61)
	    
GROUP  BY XVENDA.CODCOLIGADA,
          XVENDA.NUM_VENDA,
          XADIT.NUMVENDA,
          XVENDA.DAT_VENDA,
          XVENDACOMPL.DATAASSCEF,
          XEMPREENDIMENTO.COD_PESS_EMPR,
          XEMPREENDIMENTO.NOME,
          FCFO.NOMEFANTASIA,
          GCOTACAO.FATOR,
          XMODALIDADEVENDA.DSC_MOD_VENDA,
		  XVENDA.DATAASSINATURA,
		  XVENDA.COD_PESS_EMPR,
		  XVENDA.COD_MOD_VENDA,
		  XVENDA.DATAENTREGACHAVE,
          XVENDA.VALOR_VENDA,
          XSITUACAOVENDA.DSC_SIT_VENDA,
          XUNIDADECOMPL.DTPRIMEIRADEMANDA,
          DATAEFETIVA.DATA,
          DEFASAGEM.DEFASAGEM

		  ,XREGRA.VR_PARTE_COMPN
		  ,XREGRA.QTD_PARC
		  ,XREGRA.VRUNTPARCELA
		  ,XREGRA.DAT_INI_CALC
		  ,XADIT.CODSITADIT	
		  ,XADIT.NUMADIT 
		  ,XREGRA.RECCREATEDBY


ORDER  BY XVENDA.CODCOLIGADA,
          XEMPREENDIMENTO.COD_PESS_EMPR,
          FCFO.NOMEFANTASIA
		  

		  