DECLARE @CODCOLIGADA AS NVARCHAR(MAX) = '1',
 @EMPREENDIMENTO AS NVARCHAR(MAX) = '17633',
 @CLIENTE AS VARCHAR(MAX) = 'KELI FREITAS FAUSTINO',
 @DATA_BAIXA_INI as date = '20000101',
 @DATA_BAIXA_FIN as date = '20260101',
 @DATA_VENCIMENTO_INI as date = '20000101',
 @DATA_VENCIMENTO_FIN as date = '20260101',
 @TIPO_PARC NVARCHAR(MAX) = '29,15,63,98,58,81,101,150,1,50,93,153,110,10,61,90,4,96,36,62,554,5,22,202,16,2,17,60,154,40,91,57',
 @XML_COLIGADA AS XML,
 @XML_EMPREENDIMENTO AS XML,
 @XML_TIPO_PARC AS XML;

/*Transforma a string em um XML*/

SET @XML_TIPO_PARC = CAST(('<A>' + REPLACE(@TIPO_PARC, ',', '</A><A>') + '</A>') AS XML)
SET @XML_COLIGADA = CAST(('<A>' + REPLACE(@CODCOLIGADA, ',', '</A><A>') + '</A>') AS XML)
SET @XML_EMPREENDIMENTO = CAST(('<A>' + REPLACE(@EMPREENDIMENTO, ',', '</A><A>') + '</A>') AS XML)


SELECT	 XVENDA.COD_PESS_EMPR
									,XITEMVENDA.NUM_UNID
									,XITEMVENDA.NUM_SUB_UNID 
									,XTIPOPARCELA.DSC_TIPO_PARC
									,XVENDAPARCELA.NUMPARC
									,FCFO.NOMEFANTASIA
									,FLAN.DATAVENCIMENTO
									,FLAN.DATAEMISSAO
									

										
									,(CASE WHEN FLAN.PAGREC = 2 THEN 
																	(FLAN.VALORADIANTAMENTO + FLANBAIXA.VALORBAIXA 
																	- isnull((SELECT SUM (VALOR) FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) 
																	- isnull((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
																	- isnull(FLANBAIXA.VALORMULTA,0) 
																	- isnull(FLANBAIXA.VALORJUROS,0) 
																	+ isnull(FLANBAIXA.VALORDESCONTO,0) )
																* -1 
																ELSE 
																	FLAN.VALORADIANTAMENTO + FLANBAIXA.VALORBAIXA 
																	- isnull((SELECT SUM (VALOR) FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0) 
																	- isnull((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) 
																	- isnull(FLANBAIXA.VALORMULTA,0) 
																	- isnull(FLANBAIXA.VALORJUROS,0) 
																	- isnull(FLANBAIXA.VALOROP8,0) 
																	+ isnull(FLANBAIXA.VALORDESCONTO,0)
																END)
									AS VALOR_HIST
																		
									/* VALOR HISTORICO ANTIGO MODIFICADO A PEDIDO DE JANILSON ,CASE WHEN XPARCELAPAGAMENTO.COD_TIPO_PARC=26 AND FLAN.STATUSLAN=1 THEN FLANBAIXA.VALORBAIXA ELSE ((case when flan.valorbaixado = 0 and flan.valoradiantamento>0 then flan.valoradiantamento else flan.valorbaixado end) -isnull((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (11,5)),0) - isnull((SELECT SUM (VALOR)FROM FLANINTEGRACAO WHERE IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (12,4)),0) - isnull(FLAN.VALORMULTA,0) - isnull(FLAN.VALORJUROS,0) + isnull(FLAN.VALORDESCONTO,0)) END */
									,isnull((SELECT SUM (VALOR) FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'CM'))),0) AS CORRECAO
									,isnull((SELECT SUM (VALOR)FROM FLANBAIXAINTEGRACAO (NOLOCK)  WHERE  IDBAIXA = FLANBAIXA.IDBAIXA AND IDLAN = FLAN.IDLAN AND CODCOLIGADA = FLAN.CODCOLIGADA AND IDCAMPO IN (SELECT IDCAMPO FROM dbo.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'JUROS'))),0)  AS JUROS
									,isnull(FLANBAIXA.VALORMULTA,0) AS VALORMULTA
									,isnull(FLANBAIXA.VALORJUROS,0) AS VALORJUROS
									,isnull(FLANBAIXA.VALORDESCONTO,0) AS VALORDESCONTO
									,isnull(FLANBAIXA.VALOROP8,0) AS VALOROP8
									,FLAN.VALORADIANTAMENTO+FLANBAIXA.VALORBAIXA
									,FLANBAIXA.DATABAIXA
									/*,XPARCELAPAGAMENTO.DAT_LIQ_PARC */
									,FLAN.STATUSLAN
									,XVENDAPARCELA.IDLAN
									,FLAN.DATAVENCIMENTO
									,XVENDA.CODCXA
									,XVENDA.NUM_VENDA
									,XVENDA.CODCOLIGADA
									,XVENDA.DAT_VENDA
									,XMODALIDADEVENDA.DSC_MOD_VENDA
									,FLANBAIXA.DATACONTABILIZBX
									
							FROM XVENDAPARCELA				(NOLOCK)
								JOIN XVENDA					(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND  XVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA)
								JOIN XITEMVENDA				(NOLOCK) ON (XVENDA.NUM_VENDA = XITEMVENDA.NUM_VENDA AND XVENDA.COD_PESS_EMPR = XITEMVENDA.COD_PESS_EMPR)
								JOIN FCFO					(NOLOCK) ON (XVENDA.CODCFO = FCFO.CODCFO AND XVENDA.CODCOLCFO = FCFO.CODCOLIGADA)
								JOIN XTIPOPARCELA			(NOLOCK) ON (XTIPOPARCELA.COD_TIPO_PARC = XVENDAPARCELA.CODTIPOPARC)
								JOIN FLAN					(NOLOCK) ON (FLAN.CODCOLIGADA=XVENDAPARCELA.CODCOLLAN AND FLAN.IDLAN=XVENDAPARCELA.IDLAN)
								LEFT JOIN FLANBAIXA			(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.STATUS <> 1)
								LEFT JOIN XMODALIDADEVENDA	(NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)		
WHERE XVENDA.COD_SIT_VENDA NOT IN (10,60,61,62)

 AND XVENDA.CODCOLIGADA IN (
  SELECT N.value('.', 'INT')
  FROM @XML_COLIGADA.nodes('/A') AS T(N)
 )

 AND XVENDA.COD_PESS_EMPR IN (
  SELECT N.value('.', 'NVARCHAR(MAX)')
  FROM @XML_EMPREENDIMENTO.nodes('/A') AS T(N)
 )

 AND FCFO.NOMEFANTASIA LIKE  @CLIENTE
 AND FLANBAIXA.DATABAIXA BETWEEN @DATA_BAIXA_INI AND @DATA_BAIXA_FIN
 AND FLAN.DATAVENCIMENTO BETWEEN @DATA_VENCIMENTO_INI AND @DATA_VENCIMENTO_FIN


 AND XTIPOPARCELA.COD_TIPO_PARC IN (
  SELECT N.value('.', 'NVARCHAR(MAX)') 
  FROM @XML_TIPO_PARC.nodes('/A') AS T(N)
 )