	DECLARE @CONT_EMP INT = 0
	DECLARE @TAMANHO_EMP INT = (SELECT COUNT (*) FROM XEMPREENDIMENTO (NOLOCK) WHERE COD_PESS_EMPR IN (@EMPREENDIMENTO))
	DECLARE @RESULTADO_EMP VARCHAR(MAX) =''
	DECLARE @CONT_PARC INT = 0
	DECLARE @TAMANHO_PARC INT = (SELECT COUNT (*) FROM XTIPOPARCELA (NOLOCK) WHERE XTIPOPARCELA.COD_TIPO_PARC IN (@TIPO_PARC))
	DECLARE @RESULTADO_PARC VARCHAR(MAX) =''
	--17634
	WHILE @CONT_EMP < @TAMANHO_EMP
		BEGIN
			SET @RESULTADO_EMP = @RESULTADO_EMP + (
											SELECT CONVERT (VARCHAR(10),COD_PESS_EMPR) FROM 
												(
													SELECT 
													ROW_NUMBER() OVER (ORDER BY XEMPREENDIMENTO.COD_PESS_EMPR) AS ORDEM,
													COD_PESS_EMPR
													FROM XEMPREENDIMENTO (NOLOCK) 
													WHERE COD_PESS_EMPR IN (@EMPREENDIMENTO)
	
												) AS GRUPO
												WHERE GRUPO.ORDEM = @CONT_EMP + 1
										) + ';'


			SET @CONT_EMP = @CONT_EMP + 1
		END

	WHILE @CONT_PARC < @TAMANHO_PARC
		BEGIN
			SET @RESULTADO_PARC = @RESULTADO_PARC + (
											SELECT CONVERT (VARCHAR(10),COD_TIPO_PARC) FROM 
												(
													SELECT 
													ROW_NUMBER() OVER (ORDER BY XTIPOPARCELA.COD_TIPO_PARC) AS ORDEM,
													XTIPOPARCELA.COD_TIPO_PARC
													FROM XTIPOPARCELA (NOLOCK) 
													WHERE XTIPOPARCELA.COD_TIPO_PARC IN (@TIPO_PARC)
	
												) AS GRUPO
												WHERE GRUPO.ORDEM = @CONT_PARC + 1
										) + ';'


			SET @CONT_PARC = @CONT_PARC + 1
		END

SELECT 
GFILIAL.CGC AS CNPJ_EMPREENDIMENTO
,GCOLIGADA.NOME AS NOME_COLIGADA				 
,FORMAT (XVENDA.DAT_VENDA, 'dd/MM/yyyy') AS DATA_VENDA
				,SGI.EMP
				,FCFO.CGCCFO
				,CONVERT (VARCHAR,XEMPREENDIMENTO.COD_PESS_EMPR) + ' - ' + XEMPREENDIMENTO.NOME AS NOME_EMPRE
				,SGI.QUADRA AS UND
				,SGI.LOTE
				,SGI.TIPO_PAG
				,SGI.NUMERO
				,SGI.CLIENTE
				,SGI.VENCIMENTO
				,(CASE WHEN SGI.TIPO_PAG = '101' THEN 'CHAVES' ELSE CONVERT(VARCHAR,SGI.VENCIMENTO,103) END) AS VENCIMENTO_NOVO
				,SGI.VALORHIST
				,SGI.CORRECAO
				,SGI.JUROS
				,SGI.MULTA
				,SGI.MORA
				,SGI.DESCONTO
				,SGI.VALOROP8
				,SGI.VALORRECEBIDO
				,SGI.DATADORECEBIMENTO
				,SGI.SITUACAO
				,SGI.IDLAN
				,SGI.DATAORIG
				,SGI.CODCXA
				,SGI.NUM_VENDA
				,XSITUACAOVENDA.DSC_SIT_VENDA
				,FORMAT (SGI.DAT_VENDA, 'dd/MM/yyyy') AS DAT_VENDA
				,SGI.CODCOLIGADA 
				,XMODALIDADEVENDA.DSC_MOD_VENDA
				,CONVERT(VARCHAR, XMODALIDADEVENDA.COD_MOD_VENDA) + ' - ' +XMODALIDADEVENDA.DSC_MOD_VENDA AS MODALIDADE_VENDA
,FTB2.CODTB2FLX + ' - ' + FTB2.DESCRICAO AS CLASS_FIN								,XVENDA.NUM_CONT
				,FLAN.VALOROP8 AS HONORARIO
				/* Alteração realizada por Gabriel Hiago em 15/12, solicitado por Andreia.Silva no chamado #1223-000042*/
				,(CASE WHEN XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = 1 THEN 'AMBOS'
					   WHEN XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = 2 THEN 'Barcelos'
					   WHEN XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = 3 THEN 'Cadiotto Valle Advogados'
					   WHEN XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = 4 THEN 'Não integra empreendimento'
					   WHEN XEMPREENDIMENTOCOMPL.INTEGRACAOAPI = 5 THEN 'MIRO'
					   ELSE 'NENHUM' END) AS ESCRITORIO,
					   /*campos chamado Julio L. incluido por Yan chamado 0224-000177  */

				FLAN.CODCCUSTO,
				FLAN.CODCXA AS 'CONTA_CAIXA',
				FLANBAIXA.DATACONTABILIZBX AS 'DATA_CONT_BX',
				FLANBAIXA.DATABAIXA AS 'DATA_BAIXA',
				FLANBAIXA.RECMODIFIEDON AS 'DATA_CRIACAO_BX', 
                FLAN.RECMODIFIEDBY AS 'USUARIO_ALTERA',
                FLANBAIXA.RECCREATEDBY AS 'USUÁRIO_BAIXA'



FROM DBO.REL_SGI_RECEBIDAS_VARIOS_EMP_IMOB (@RESULTADO_EMP, @RESULTADO_PARC ,@NOME_CLIENTE,@DATA_PAGAMENTO_INI,@DATA_PAGAMENTO_FIN,@DATA_VENCIMENTO_INI,@DATA_VENCIMENTO_FIN) AS SGI
INNER JOIN XVENDA				(NOLOCK) ON (XVENDA.CODCOLIGADA=SGI.CODCOLIGADA AND XVENDA.NUM_VENDA=SGI.NUM_VENDA AND XVENDA.COD_PESS_EMPR=SGI.EMP)
INNER JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = SGI.EMP)
INNER JOIN GCOLIGADA			(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
INNER JOIN XMODALIDADEVENDA		(NOLOCK) ON (XMODALIDADEVENDA.COD_MOD_VENDA=XVENDA.COD_MOD_VENDA)
INNER JOIN XSITUACAOVENDA		(NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
INNER JOIN FCFO					(NOLOCK) ON (XVENDA.CODCFO = FCFO.CODCFO AND XVENDA.CODCOLCFO = FCFO.CODCOLIGADA)
LEFT JOIN GFILIAL				(NOLOCK) ON (GFILIAL.CODFILIAL = XEMPREENDIMENTO.CODFILIAL AND GFILIAL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA)
LEFT JOIN FLAN					(NOLOCK) ON (FLAN.IDLAN = SGI.IDLAN AND FLAN.CODCOLIGADA = SGI.CODCOLIGADA)
LEFT JOIN FTB2					(NOLOCK) ON (FLAN.CODTB2FLX = FTB2.CODTB2FLX AND FLAN.CODCOLIGADA = FTB2.CODCOLIGADA)
/* Alteração realizada por Gabriel Hiago em 15/12, solicitado por Andreia.Silva no chamado #1223-000042*/
INNER JOIN XEMPREENDIMENTOCOMPL (NOLOCK) ON (XEMPREENDIMENTOCOMPL.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA AND XEMPREENDIMENTOCOMPL.CODPESSEMPR = XEMPREENDIMENTO.COD_PESS_EMPR)

/* ALTERAÇÃO CHAMADO JULIO L. YAN/ chamado 0224-000177  */
INNER JOIN FLANBAIXA			(NOLOCK) ON (FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.RECCREATEDON = (SELECT MAX(RECCREATEDON) 
																																								FROM FLANBAIXA (NOLOCK)
																																								WHERE FLANBAIXA.IDLAN = SGI.IDLAN 
																																								AND FLANBAIXA.CODCOLIGADA = SGI.CODCOLIGADA))



WHERE SGI.VALORHIST IS NOT NULL
AND SGI.VALORRECEBIDO > 0
/* Alteração realizada por Gabriel Hiago em 15/12, solicitado por Andreia.Silva no chamado #1223-000042*/
AND XEMPREENDIMENTOCOMPL.INTEGRACAOAPI IN (@ESCRITORIO)

ORDER BY  CLIENTE