
--select * 
--from XEMPREENDIMENTO
--where codcoligada = 26
/*
DECLARE @SITUACAO_VENDA INT = 40,
		@EMPREENDIMENTO INT = 17662,
		@COLIGADA INT = 26,
		@DATA_VENDA_INI DATE = '20220101',
		@DATA_VENDA_FIN DATE = '20250101';*/

WITH LANCAMENTOS AS 
(
SELECT 
COUNT(FLAN.IDLAN) AS 'QUANTIDADE_DE_PARCELAS',
FLAN.CODCFO,
SUM(FLANINTEGRACAO.VALOR) AS 'VALOR',
(CASE 
	WHEN FLAN.STATUSLAN = 0 THEN 'Em Aberto'
	WHEN FLAN.STATUSLAN = 1 THEN 'Baixado'
	WHEN FLAN.STATUSLAN = 2 THEN 'Cancelado'
	WHEN FLAN.STATUSLAN = 3 THEN 'Baixado por Acordo'
	WHEN FLAN.STATUSLAN = 4 THEN 'Baixado parcialmente'
	WHEN FLAN.STATUSLAN = 5 THEN 'Borderô'
	END) AS 'STATUS'

FROM FLAN (NOLOCK)
INNER JOIN FLANINTEGRACAO		(NOLOCK) ON FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN
INNER JOIN FLANINTEGRACAODEF	(NOLOCK) ON FLANINTEGRACAODEF.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLANINTEGRACAODEF.IDCAMPO = FLANINTEGRACAO.IDCAMPO
WHERE FLANINTEGRACAODEF.IDCAMPO = 2
GROUP BY FLAN.STATUSLAN,
FLAN.CODCFO
)



SELECT 
XVENDA.NUM_VENDA,
XEMPREENDIMENTO.UF AS ESTADO_EMP,
XEMPREENDIMENTO.NOME,
XITEMVENDA.NUM_UNID AS 'BLOCO',
RIGHT(XITEMVENDA.NUM_SUB_UNID,3) AS 'UNIDADE',
(XITEMVENDA.NUM_UNID + ' - ' + RIGHT(XITEMVENDA.NUM_SUB_UNID,3)) 'BLOCO + UNIDADE',
FCFO.NOME AS 'COMPRADOR 1',
FCFO.CGCCFO,
		(SELECT TOP 1 FCFO.NOME  FROM XCOMPRADOR  (NOLOCK) AS COMPRADOR2
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS NOME_SEGUNDO_COMPRADOR,

		(SELECT TOP 1 FCFO.CGCCFO  FROM XCOMPRADOR (NOLOCK) AS COMPRADOR2 
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS CPF_SEGUNDO_COMPRADOR,
		XVENDA.DAT_VENDA,
		(
		SELECT TOP 1
COUNT(FLAN.IDLAN) AS 'QUANTIDADE_DE_PARCELAS'/*,
(CASE 
	WHEN FLAN.STATUSLAN = 0 THEN 'Em Aberto'
	WHEN FLAN.STATUSLAN = 1 THEN 'Baixado'
	WHEN FLAN.STATUSLAN = 2 THEN 'Cancelado'
	WHEN FLAN.STATUSLAN = 3 THEN 'Baixado por Acordo'
	WHEN FLAN.STATUSLAN = 4 THEN 'Baixado parcialmente'
	WHEN FLAN.STATUSLAN = 5 THEN 'Borderô'
	END) AS 'STATUS'*/
FROM FLAN AS FL1 (NOLOCK)
INNER JOIN FLANINTEGRACAO (NOLOCK) ON FL1.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FL1.IDLAN = FLANINTEGRACAO.IDLAN
INNER JOIN FLANINTEGRACAODEF (NOLOCK) ON FLANINTEGRACAODEF.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLANINTEGRACAODEF.IDCAMPO = FLANINTEGRACAO.IDCAMPO
WHERE FL1.CODCFO = FLAN.CODCFO
AND FLANINTEGRACAODEF.IDCAMPO = 2
		)AS 'QTD_PARC_Escritura_ITBI2',
		(SELECT TOP 1 
			SUM(XREGRACOMPONENTEVENDA.QTD_PARC)		
			FROM XREGRACOMPONENTEVENDA (NOLOCK)			
			INNER JOIN XCOMPONENTE (NOLOCK) ON (XCOMPONENTE.COD_COMPN = XREGRACOMPONENTEVENDA.COD_COMPN)
			WHERE XREGRACOMPONENTEVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XREGRACOMPONENTEVENDA.NUM_VENDA =XVENDAPARCELA.NUMVENDA AND XCOMPONENTE.COD_COMPN = 99
		) AS 'QTD_PARC_Escritura_ITBI',
	  LANCAMENTOS.QUANTIDADE_DE_PARCELAS AS 'QTD_PARC_Escritura_ITBI_PENDENTES2',

D.DESCONTO,
(   SELECT TOP 1 R1.VR_PARTE_COMPN
    FROM XREGRACOMPONENTEVENDA R1 (NOLOCK)
    INNER JOIN XCOMPONENTE C1 (NOLOCK) ON C1.COD_COMPN = R1.COD_COMPN
    WHERE R1.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND R1.NUM_VENDA = XVENDAPARCELA.NUMVENDA AND C1.COD_COMPN = 99
    ORDER BY R1.NUM_VENDA DESC 
) - D.DESCONTO AS 'VALOR CONTRATUAL ACORDADO',

LANCAMENTOS.VALOR as 'VALOR CONTRATUAL PENDENTE'



FROM XVENDA (NOLOCK) 
		LEFT JOIN XVENDAPARCELA			(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA)
		LEFT JOIN FLAN					(NOLOCK) ON (FLAN.IDLAN = XVENDAPARCELA.IDLAN AND FLAN.CODCOLIGADA = XVENDAPARCELA.CODCOLLAN)
		LEFT JOIN XITEMVENDA			(NOLOCK) ON (XITEMVENDA.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR  AND XITEMVENDA.NUM_VENDA = XVENDA.NUM_VENDA)													
		LEFT JOIN GCOLIGADA				(NOLOCK) ON (XVENDA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)                                                                              /*CORRECAO ADICIONADA EM VIRTUDE DO CHAMADO Nº 0525-000171 (COMPRADORES DUPLICADOS), ADICIONADA CLAUSULA PARA TRAZER APENAS OS QUE NÃO TEM DATA DE SAIDA DO PLANO DE FINANCIAMENTO */
		LEFT JOIN XCOMPRADOR			(NOLOCK) ON (XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA AND XVENDA.CODCOLIGADA = XCOMPRADOR.CODCOLIGADA AND XCOMPRADOR.PRINCIPAL = '1' AND XCOMPRADOR.DATASAIDAPLANO IS NULL)
		LEFT JOIN FCFO					(NOLOCK) ON (XCOMPRADOR.CODCFO = FCFO.CODCFO AND XCOMPRADOR.CODCOLCFO = FCFO.CODCOLIGADA)
		LEFT JOIN XSITUACAOVENDA		(NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
		LEFT JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR AND XVENDA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA) 
		INNER JOIN LANCAMENTOS					 ON (LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'Em Aberto')
		CROSS APPLY (SELECT CAST(ISNULL(SUM(VALOR), 0) AS decimal(18,2)) AS DESCONTO
					 FROM FLANINTEGRACAO (NOLOCK)
					 WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.IDCAMPO IN (
					       SELECT IDCAMPO 
					       FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))
					 ) AS D


WHERE	
XVENDA.COD_SIT_VENDA IN (@SITUACAO_VENDA)
AND		XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
AND		(
			(XVENDA.DAT_VENDA >= @DATA_VENDA_INI AND XVENDA.DAT_VENDA < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 0 ELSE 1 END) )
			OR 
			(ISNULL(XVENDA.DAT_CANCELA,XVENDA.DAT_VENDA) >= @DATA_VENDA_INI AND ISNULL(XVENDA.DAT_CANCELA,XVENDA.DAT_VENDA) < DATEADD(DAY,1,@DATA_VENDA_FIN) AND 1 = (CASE WHEN XVENDA.COD_SIT_VENDA IN (60,61,62) THEN 1 ELSE 0 END) ) /* ISNULL FEITO POR MARCELO DEVIDO A VENDAS CANCELADAS (STATUS 60) SEM DATA DE CANCELAMENTO EXEMPLO 51114 */
		)
AND	XVENDA.CODCOLIGADA IN (@COLIGADA)
--and XVENDA.NUM_VENDA = 32805

GROUP BY 
FLAN.CODCFO,
XEMPREENDIMENTO.UF,
XEMPREENDIMENTO.NOME,
FCFO.NOME,
FCFO.CGCCFO,
XVENDA.NUM_VENDA,
XVENDA.CODCOLIGADA,
XVENDA.DAT_VENDA,
XVENDAPARCELA.CODCOLIGADA,
XVENDAPARCELA.NUMVENDA,
/*FLAN.CODCOLIGADA,
FLAN.IDLAN,*/
XITEMVENDA.NUM_UNID,
XITEMVENDA.NUM_SUB_UNID,
D.DESCONTO,
LANCAMENTOS.QUANTIDADE_DE_PARCELAS,
LANCAMENTOS.VALOR


/*
SELECT 
COUNT(FLAN.IDLAN) AS 'QUANTIDADE_DE_PARCELAS',
(CASE 
	WHEN FLAN.STATUSLAN = 0 THEN 'Em Aberto'
	WHEN FLAN.STATUSLAN = 1 THEN 'Baixado'
	WHEN FLAN.STATUSLAN = 2 THEN 'Cancelado'
	WHEN FLAN.STATUSLAN = 3 THEN 'Baixado por Acordo'
	WHEN FLAN.STATUSLAN = 4 THEN 'Baixado parcialmente'
	WHEN FLAN.STATUSLAN = 5 THEN 'Borderô'
	END) AS 'STATUS'

FROM FLAN (NOLOCK)
INNER JOIN FLANINTEGRACAO (NOLOCK) ON FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN
INNER JOIN FLANINTEGRACAODEF (NOLOCK) ON FLANINTEGRACAODEF.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLANINTEGRACAODEF.IDCAMPO = FLANINTEGRACAO.IDCAMPO
WHERE CODCFO = 'F40877'
AND FLANINTEGRACAODEF.IDCAMPO = 2
GROUP BY FLAN.STATUSLAN

select * 
from flanintegracao 
where IDLAN = 150466

select * 
from glinksrel 
where CHILDTABLE = 'flanintegracao'

select * 
from FLANINTEGRACAODEF

SELECT * FROM XCOMPRADOR 
WHERE NUM_VENDA = 32805



SELECT NOME,* 
FROM FCFO
WHERE CODCFO IN ('F40877', 'F40878')*/

