/*
DECLARE @SITUACAO_VENDA INT = 40,
		@EMPREENDIMENTO INT = 17662,
		@CODCOLIGADA INT = 22,
		@DATA_VENDA_INI DATE = '20220101',
		@DATA_VENDA_FIN DATE = '20250101';*/

WITH LANCAMENTOS AS 
(
SELECT 
SUM(G.QUANTIDADE_DE_PARCELAS) AS 'QTD_PARCELAS',
SUM(G.VALOR) AS 'VALOR',
G.CODCFO,
/*G.IDCAMPO,*/
G.STATUS
FROM (

SELECT 
COUNT(FLAN.IDLAN) AS 'QUANTIDADE_DE_PARCELAS',
FLAN.CODCFO,
SUM(FLANINTEGRACAO.VALOR) AS 'VALOR',
FLANINTEGRACAODEF.IDCAMPO,

(CASE 
	WHEN FLAN.STATUSLAN = 0 AND FLAN.DATAVENCIMENTO < CONVERT(DATE,GETDATE()) THEN 'VENCIDA'
	WHEN FLAN.STATUSLAN = 0 THEN 'EM ABERTO'
	WHEN FLAN.STATUSLAN = 1 THEN 'BAIXADO'
	WHEN FLAN.STATUSLAN = 2 THEN 'CANCELADO'
	WHEN FLAN.STATUSLAN = 3 THEN 'BAIXADO POR ACORDO'
	WHEN FLAN.STATUSLAN = 4 THEN 'BAIXADO PARCIALMENTE'
	WHEN FLAN.STATUSLAN = 5 THEN 'BORDERÔ'
	END) AS 'STATUS'

FROM FLAN (NOLOCK)
INNER JOIN FLANINTEGRACAO			(NOLOCK) ON FLAN.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLAN.IDLAN = FLANINTEGRACAO.IDLAN
INNER JOIN FLANINTEGRACAODEF		(NOLOCK) ON FLANINTEGRACAODEF.CODCOLIGADA = FLANINTEGRACAO.CODCOLIGADA AND FLANINTEGRACAODEF.IDCAMPO = FLANINTEGRACAO.IDCAMPO
WHERE FLANINTEGRACAODEF.IDCAMPO IN (2, 119, 53)
/*AND FLAN.CODCFO = 'F45026'*/
GROUP BY FLAN.STATUSLAN,
FLAN.CODCFO,
FLANINTEGRACAODEF.IDCAMPO,
FLAN.DATAVENCIMENTO) AS G

WHERE G.STATUS <> 'CANCELADO'

GROUP BY 
G.CODCFO,
/*G.IDCAMPO,*/
G.STATUS

)



SELECT 
XVENDA.NUM_VENDA,
XEMPREENDIMENTO.UF AS ESTADO_EMP,
XEMPREENDIMENTO.NOME,
XITEMVENDA.NUM_UNID AS 'BLOCO',
RIGHT(XITEMVENDA.NUM_SUB_UNID,3) AS 'UNIDADE',
(XITEMVENDA.NUM_UNID + ' - ' + RIGHT(XITEMVENDA.NUM_SUB_UNID,3)) 'BLOCO + UNIDADE',
FCFO.NOME AS 'COMPRADOR 1',
FCFO.CGCCFO,
		(SELECT TOP 1 FCFO.NOME  FROM XCOMPRADOR  (NOLOCK) AS COMPRADOR2
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS NOME_SEGUNDO_COMPRADOR,

		(SELECT TOP 1 FCFO.CGCCFO  FROM XCOMPRADOR (NOLOCK) AS COMPRADOR2 
		INNER JOIN FCFO (NOLOCK) ON COMPRADOR2.CODCFO = FCFO.CODCFO AND COMPRADOR2.CODCOLCFO = FCFO.CODCOLIGADA
		WHERE COMPRADOR2.PRINCIPAL = 0
		AND COMPRADOR2.NUM_VENDA = XVENDA.NUM_VENDA
		AND COMPRADOR2.CODCOLIGADA = XVENDA.CODCOLIGADA
		AND COMPRADOR2.DATASAIDAPLANO IS NULL
 
		) AS CPF_SEGUNDO_COMPRADOR,
		XVENDA.DAT_VENDA,
		(SELECT TOP 1 SUM(LANCAMENTOS.QTD_PARCELAS)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO)AS 'QTD_PARC_ITBI',
	    (SELECT TOP 1 SUM(LANCAMENTOS.VALOR)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO)AS 'TOTAL_PARC_ITBI',
		(SELECT TOP 1 R1.VR_PARTE_COMPN
		FROM XREGRACOMPONENTEVENDA R1 (NOLOCK)
		INNER JOIN XCOMPONENTE C1 (NOLOCK) ON C1.COD_COMPN = R1.COD_COMPN
		WHERE R1.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND R1.NUM_VENDA = XVENDAPARCELA.NUMVENDA AND C1.COD_COMPN = 99
		ORDER BY R1.NUM_VENDA DESC 
		)- D.DESCONTO AS 'VALOR CONTRATUAL ACORDADO',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.QTD_PARCELAS)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'BAIXADO'),0)AS 'QTD_PARC_ITBI_PG',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.VALOR)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'BAIXADO'),0)AS 'TOTAL_PARC_ITBI_PG',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.QTD_PARCELAS)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'VENCIDA'),0)AS 'QTD_PARC_ITBI_VENC',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.VALOR)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'VENCIDA'),0)AS 'TOTAL_PARC_ITBI_VENC',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.QTD_PARCELAS)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'EM ABERTO'),0)AS 'QTD_PARC_ITBI_A_VENCER',
		ISNULL((SELECT TOP 1 SUM(LANCAMENTOS.VALOR)
		FROM LANCAMENTOS
		WHERE LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS = 'EM ABERTO'),0)AS 'TOTAL_PARC_ITBI_A_VENCER'





FROM XVENDA (NOLOCK) 
		LEFT JOIN XVENDAPARCELA			(NOLOCK) ON (XVENDA.CODCOLIGADA = XVENDAPARCELA.CODCOLIGADA AND XVENDA.NUM_VENDA = XVENDAPARCELA.NUMVENDA)
		LEFT JOIN FLAN					(NOLOCK) ON (FLAN.IDLAN = XVENDAPARCELA.IDLAN AND FLAN.CODCOLIGADA = XVENDAPARCELA.CODCOLLAN)
		LEFT JOIN XITEMVENDA			(NOLOCK) ON (XITEMVENDA.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR  AND XITEMVENDA.NUM_VENDA = XVENDA.NUM_VENDA)													
		LEFT JOIN GCOLIGADA				(NOLOCK) ON (XVENDA.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)                                                                              /*CORRECAO ADICIONADA EM VIRTUDE DO CHAMADO Nº 0525-000171 (COMPRADORES DUPLICADOS), ADICIONADA CLAUSULA PARA TRAZER APENAS OS QUE NÃO TEM DATA DE SAIDA DO PLANO DE FINANCIAMENTO */
		LEFT JOIN XCOMPRADOR			(NOLOCK) ON (XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA AND XVENDA.CODCOLIGADA = XCOMPRADOR.CODCOLIGADA AND XCOMPRADOR.PRINCIPAL = '1' AND XCOMPRADOR.DATASAIDAPLANO IS NULL)
		LEFT JOIN FCFO					(NOLOCK) ON (XCOMPRADOR.CODCFO = FCFO.CODCFO AND XCOMPRADOR.CODCOLCFO = FCFO.CODCOLIGADA)
		LEFT JOIN XSITUACAOVENDA		(NOLOCK) ON (XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA)
		LEFT JOIN XEMPREENDIMENTO		(NOLOCK) ON (XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR AND XVENDA.CODCOLIGADA = XEMPREENDIMENTO.CODCOLIGADA) 
		--LEFT JOIN LANCAMENTOS					 ON (LANCAMENTOS.CODCFO = FLAN.CODCFO AND LANCAMENTOS.STATUS <> 'Cancelado')
		CROSS APPLY (SELECT CAST(ISNULL(SUM(VALOR), 0) AS decimal(18,2)) AS DESCONTO
					 FROM FLANINTEGRACAO (NOLOCK)
					 WHERE FLANINTEGRACAO.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANINTEGRACAO.IDLAN = FLAN.IDLAN AND FLANINTEGRACAO.IDCAMPO IN (
					       SELECT IDCAMPO 
					       FROM CORPORE_RESIDENCIAL.DBO.RETORNA_IDCAMPO_JUROS(FLAN.CODCOLIGADA,'DESCONTO'))
					 ) AS D


WHERE	
XVENDA.COD_SIT_VENDA IN (@SITUACAO_VENDA)
AND		XVENDA.COD_PESS_EMPR IN (@EMPREENDIMENTO)
AND	XVENDA.CODCOLIGADA IN (@CODCOLIGADA)
/*and XVENDA.NUM_VENDA = 36010*/

GROUP BY 
FLAN.CODCFO,
XEMPREENDIMENTO.UF,
XEMPREENDIMENTO.NOME,
FCFO.NOME,
FCFO.CGCCFO,
XVENDA.NUM_VENDA,
XVENDA.CODCOLIGADA,
XVENDA.DAT_VENDA,
XVENDAPARCELA.CODCOLIGADA,
XVENDAPARCELA.NUMVENDA,
/*FLAN.CODCOLIGADA,
FLAN.IDLAN,*/
XITEMVENDA.NUM_UNID,
XITEMVENDA.NUM_SUB_UNID,
D.DESCONTO


ORDER BY 3,4,5