DECLARE @ID_VENDA AS INT = 10856;

SELECT CONVERT(MONEY,SUM(VLR.VALOR_TOTAL)) as 'VALOR TOTAL'

FROM XVENDA (NOLOCK)
LEFT JOIN XVENDAPARCELA			(NOLOCK) ON (XVENDAPARCELA.NUMVENDA=XVENDA.NUM_VENDA)
LEFT JOIN FLAN					(NOLOCK) ON (XVENDAPARCELA.CODCOLLAN=FLAN.CODCOLIGADA AND XVENDAPARCELA.IDLAN=FLAN.IDLAN)
LEFT JOIN DBO.VALORES_CALCULADOS_A_RECEBER_FLUXUS_POR_VENDA(@ID_VENDA,GETDATE()) AS VLR ON (VLR.IDLAN = FLAN.IDLAN AND VLR.CODCOLIGADA = FLAN.CODCOLIGADA)


WHERE XVENDA.NUM_VENDA = @ID_VENDA
AND XVENDA.CODCOLIGADA = 1
