SELECT [ID_LOG]
      ,[NOME_USUARIO]
      ,[MAQUINA],
	[DATA]
      ,[STATUS]
      ,[REGRA_VIGENTE]
      ,[TEMPO_LOGADO]/60 As HORAS_LOGADO
      ,[TEMPO_ATIVO]/60  As HORAS_TEMPO_ATIVO  

  FROM [KICKER_2].[dbo].[LOG]

  WHERE
  NOME_USUARIO = @USUARIO 
  AND DATA BETWEEN @DATA_INI 
  AND @DATA_FIM
  AND 
  (DATA IN 
	  (SELECT MAX(DATA) 
	  FROM [KICKER_2].[dbo].[LOG] 
	  WHERE 
	  NOME_USUARIO = @USUARIO
	  AND DATA 
	  BETWEEN @DATA_INI  
	  AND @DATA_FIM
	  GROUP BY DAY(DATA),MONTH(DATA),YEAR(DATA))
 OR DATA IN 
	  (SELECT MIN(DATA) 
	  FROM [KICKER_2].[dbo].[LOG] 
	  WHERE 
	  NOME_USUARIO = @USUARIO 
	  AND DATA 
	  BETWEEN @DATA_INI  
	  AND @DATA_FIM 
	  GROUP BY DAY(DATA),MONTH(DATA),YEAR(DATA)))
 
  ORDER BY DATA desc