SELECT GRUPO.*
/*,										
	  APROVADORES.*	*/							
FROM (													
		SELECT             
                   
        --GCOLIGADA.NOMEFANTASIA,            
        GUSUARIO.CODUSUARIO,            
        ISNULL(POR_NOME.NOME,GUSUARIO.NOME) AS NOME,            
        POR_NOME.FUNCAO,            
        POR_NOME.DESCRICAO AS SECAO,
		GCOLIGADA.CODCOLIGADA, 
		GUSRPERFIL.CODPERFIL,            
        ISNULL(ZMDCENTRODECUSTO.CODCCUSTO,'TODOS') AS CODCCUSTO,            
        ISNULL(GCCUSTO.NOME,'TODOS') AS NOME_CCUSTO            

        from GUSRPERFIL					(NOLOCK)            
        INNER JOIN GUSUARIO      		(NOLOCK) ON (GUSUARIO.CODUSUARIO = GUSRPERFIL.CODUSUARIO)      
        INNER JOIN GCOLIGADA    		(NOLOCK) ON (GCOLIGADA.CODCOLIGADA = GUSRPERFIL.CODCOLIGADA)        
        --LEFT JOIN ZMDCENTRODECUSTO  	(NOLOCK) ON (ZMDCENTRODECUSTO.COLIGADA = GUSRPERFIL.CODCOLIGADA AND ZMDCENTRODECUSTO.CODUSUARIO = GUSRPERFIL.CODUSUARIO)          
        LEFT JOIN          (
                        SELECT GCCUSTO.CODCOLIGADA, GCCUSTO.CODCCUSTO, GUSRPERFIL.CODUSUARIO  
                        FROM GUSRPERFIL			(NOLOCK)
                        INNER JOIN GCCUSTO		(NOLOCK) ON (GCCUSTO.CODCOLIGADA = REPLACE(substring(CODPERFIL, 1, 2), '_', '') AND GCCUSTO.CODCCUSTO = SUBSTRING(CODPERFIL,CHARINDEX('_',CODPERFIL) + 1,IIF((CHARINDEX('_',CODPERFIL,4) -1) - CHARINDEX('_',CODPERFIL) < 0 , LEN(CODPERFIL),(CHARINDEX('_',CODPERFIL,4) -1) - CHARINDEX('_',CODPERFIL))))
                        WHERE GUSRPERFIL.CODSISTEMA = 'T'
                        AND left(codperfil,1) IN ('1','2','3','4','5','6','7','8','9')
                      ) AS ZMDCENTRODECUSTO ON (ZMDCENTRODECUSTO.CODCOLIGADA = GUSRPERFIL.CODCOLIGADA AND ZMDCENTRODECUSTO.CODUSUARIO = GUSRPERFIL.CODUSUARIO)          

        LEFT JOIN GCCUSTO      					(NOLOCK) ON (ZMDCENTRODECUSTO.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND ZMDCENTRODECUSTO.CODCCUSTO = GCCUSTO.CODCCUSTO)      

        left JOIN (            
                  SELECT PFUNC.CODCOLIGADA, PFUNC.CODSITUACAO,PFUNCAO.NOME AS FUNCAO,PPESSOA.EMAIL, PFUNC.NOME,PPESSOA.CODUSUARIO,PFUNC.DATADEMISSAO,PSECAO.CODIGO,PSECAO.DESCRICAO FROM PPESSOA (NOLOCK)  
                  INNER JOIN PFUNC  			(NOLOCK) ON (PFUNC.CODPESSOA = PPESSOA.CODIGO)
                  INNER JOIN PFUNCAO  			(NOLOCK) ON (PFUNCAO.CODIGO = PFUNC.CODFUNCAO AND PFUNCAO.CODCOLIGADA = PFUNC.CODCOLIGADA)
                  INNER JOIN PSECAO  			(NOLOCK) ON (PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
                  WHERE PFUNC.CODSITUACAO <> 'D'  
              ) AS POR_NOME ON (POR_NOME.NOME = GUSUARIO.NOME  OR POR_NOME.EMAIL = GUSUARIO.EMAIL OR POR_NOME.CODUSUARIO = GUSUARIO.CODUSUARIO)    
										
				WHERE GUSRPERFIL.CODSISTEMA = 'T'						
				AND GUSUARIO.STATUS = 1		
				--AND GCOLIGADA.CODCOLIGADA IN (18, 30)
				--AND GUSUARIO.CODUSUARIO = 'lilian.roman'
				AND GUSRPERFIL.CODPERFIL IN ('GERAL.COMPRAS01', 'ESTOQUE.CENTRAL', 'GERAL.PLANEJ', 'GESTAO.ORCAMENT', 'GERAL.COMPRAS', 'GERAL.CONTROL', 'GERAL.CONTABIL', 'GERAL.ORÇAMENTO', 'APROV.AST.MG')		
				AND (						
						SELECT COUNT(*) 				
						FROM TUSRTMV			(NOLOCK) 				
						WHERE TUSRTMV.CODTMV IN 
							(SELECT TMOV.CODTMV 
							FROM TMOV			(NOLOCK) 
							WHERE TMOV.DATAEMISSAO >= '20230101' GROUP BY TMOV.CODTMV) 				
						AND TUSRTMV.INCLUIR = 1				
						AND TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO				
						AND TUSRTMV.CODCOLIGADA = GUSRPERFIL.CODCOLIGADA				
					) > 0					
										
				GROUP BY 						
				GCOLIGADA.CODCOLIGADA,						
				GUSUARIO.NOME,
				GUSRPERFIL.CODPERFIL,						
				GCOLIGADA.NOMEFANTASIA,						
				GUSUARIO.CODUSUARIO,						
				POR_NOME.NOME,						
				POR_NOME.FUNCAO,						
				POR_NOME.DESCRICAO,						
				ZMDCENTRODECUSTO.CODCCUSTO,						
				GCCUSTO.NOME						
		) AS GRUPO								
										
		LEFT JOIN  dbo.TRAZ_APROVADORES() AS APROVADORES ON (APROVADORES.CODUSUARIO = GRUPO.CODUSUARIO AND APROVADORES.CODCOLIGADA = GRUPO.CODCOLIGADA)								
										
ORDER BY GRUPO.CODUSUARIO, GRUPO.CODCOLIGADA		

/*
MINHA CHAPA: 00024817
*/
