
/* PROCURAR O PERFIL */

SELECT *
FROM PERFIL
--WHERE ID_PERFIL = 4
1	Usuário Visualizador
3	Engenheiro
4	Controle
5	Secretaria
6	Cadastro Item
7	Cadastro Contrato
8	Cadastro Medição
9	Administrador
10	Qualidade
11	Contabilidade
12	Cadastro FGTS
13	Cadastro Requisição
14	Apr/Rej.Questionário
15	Controle Fichas
16	Cadastro Requis. ADM
17	Qualidade Aprovador

/* PROCURAR ID DO USUÁRIO */ 

SELECT *
FROM PERFIL_USUARIO_OBRA
WHERE UserId = (SELECT UserId 
					FROM ASPNET_USERS
					WHERE
					UserName LIKE 'emccamp\andrey.melo')



/* INSERIR PERFIL EM TODAS OBRAS */ 

DECLARE @USUARIO VARCHAR(20) = 'emccamp\sara.soares'
DECLARE @ID_PERFIL INT		 = 13
--SELECT * FROM PERFIL_USUARIO_OBRA WHERE ID_PERFIL = @ID_PERFIL AND USERID = (SELECT UserId FROM ASPNET_USERS WHERE UserName LIKE @USUARIO)


BEGIN TRAN
INSERT INTO PERFIL_USUARIO_OBRA (ID_OBRA,UserId,ID_PERFIL)  /*TABELA DOS PERFIS EM TODAS AS OBRAS */
 
SELECT ID_OBRA, (SELECT UserId FROM ASPNET_USERS WHERE UserName IN('emccamp\ANA.GOMES','emccamp\arthur.bicalho', 'emccamp\BRUNA.TOREZANI', 'emccamp\CAMILA.PIRES', 'emccamp\EMILLY.EDUARDO', 'emccamp\FERNANDA.CANUTO', 'emccamp\FLAVIA.GIBRAM', 'emccamp\JOAO.CAMARGO', 'emccamp\LUCAS.PAULA', 'emccamp\THAISA.JESUS', 'emccamp\THIAGO.MAGALHAES', 'emccamp\VITORIA.COTA', 'emccamp\WESLEY.LUZ')), @ID_PERFIL FROM OBRA   /* INSERIR USUÁRIO E O ID DO PERFIL */ 
WHERE ID_OBRA 
	 IN 
		(SELECT PERFIL_USUARIO_OBRA.ID_OBRA 
			FROM PERFIL_USUARIO_OBRA 
			WHERE PERFIL_USUARIO_OBRA.USERID = (SELECT UserId FROM ASPNET_USERS WHERE UserName IN('emccamp\ANA.GOMES','emccamp\arthur.bicalho', 'emccamp\BRUNA.TOREZANI', 'emccamp\CAMILA.PIRES', 'emccamp\EMILLY.EDUARDO', 'emccamp\FERNANDA.CANUTO', 'emccamp\FLAVIA.GIBRAM', 'emccamp\JOAO.CAMARGO', 'emccamp\LUCAS.PAULA', 'emccamp\THAISA.JESUS', 'emccamp\THIAGO.MAGALHAES', 'emccamp\VITORIA.COTA', 'emccamp\WESLEY.LUZ')) --AND PERFIL_USUARIO_OBRA.ID_PERFIL = 6)  
			
    AND ID_OBRA NOT IN (SELECT ID_OBRA FROM PERFIL_USUARIO_OBRA WHERE ID_PERFIL = @ID_PERFIL AND USERID = (SELECT UserId FROM ASPNET_USERS WHERE UserName LIKE @USUARIO))
 


 --COMMIT
--ROLLBACK


/* DELETAR TODOS PERFIS */
BEGIN TRAN
DELETE FROM PERFIL_USUARIO_OBRA 
WHERE PERFIL_USUARIO_OBRA.USERID = (SELECT UserId FROM ASPNET_USERS WHERE UserName LIKE 'emccamp\andrey.melo') AND ID_OBRA = '120' and ID_PERFIL = 6

--COMMIT
--ROLLBACK


