/*

--Saldos e custos em andamento
SELECT  
GJOBX.CODCOLIGADA,
GJOBX.NOME,
GJOBXEXECUCAO.* 
FROM GJOBXEXECUCAO 
INNER JOIN GJOBX (NOLOCK) on (GJOBX.IDJOB = GJOBXEXECUCAO.IDJOB)
WHERE 
GJOBXEXECUCAO.IDJOB in (select idjob from gjobx where nome like '%saldos%' and codusuario = 'job') 
AND PERCPROGRESSO < 100
and GJOBXEXECUCAO.status <> 7
AND DATAINIEXEC >= '20230807'
ORDER BY 
GJOBX.CODCOLIGADA

*/

/* 

-- Saldos e custos
SELECT
CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
IDJOB,
PROCESSO,
NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
WHERE nome like '%saldos%custos%' 
AND codcoligada IS NOT NULL
order by 1,3

*/

/*

-- Tabela pra erro de saldos e custos
select DATAFECHAMENTOESTOQUE,* from tpar

*/

/*

--Importação de arquivos
SELECT  
CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
IDJOB,
PROCESSO,
NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,
MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
where nome like '%Importação de Arquivos%' 
AND codcoligada IS NOT NULL
order by 1,3 DESC

*/

/*
-- Consulta Status (Erro se não tiver atualização) 
SELECT 
CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
IDJOB,
PROCESSO,
NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,
MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
WHERE nome like '%Serviço%Consulta%XML%' 
AND codcoligada IS NOT NULL
order by 1,3

*/

/*

--Integração SOC RM
SELECT 
CONSULTA_JOB.CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
CONSULTA_JOB.IDJOB,
PROCESSO,
CONSULTA_JOB.NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,
MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
LEFT JOIN GJOBX ON GJOBX.IDJOB = CONSULTA_JOB.IDJOB
WHERE gjobx.classeprocesso = 'GlbWorkflowExecProc' 
AND CONSULTA_JOB.idjob = 3445624 
order by 1,3

*/

/*
--Correções do controlEMP
SELECT 
CONSULTA_JOB.CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
CONSULTA_JOB.IDJOB,
PROCESSO,
CONSULTA_JOB.NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
LEFT JOIN GJOBX ON GJOBX.IDJOB = CONSULTA_JOB.IDJOB
WHERE gjobx.idjob = 3455272 OR gjobx.idjob = 3624208
order by 1,3

*/

/*

--Envio de e-mails ControlEMP
SELECT 
CONSULTA_JOB.CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
CONSULTA_JOB.IDJOB,
PROCESSO,
CONSULTA_JOB.NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,
MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
LEFT JOIN GJOBX ON GJOBX.IDJOB = CONSULTA_JOB.IDJOB
WHERE gjobx.idjob = 3005449 OR gjobx.idjob = 3435794 OR gjobx.idjob = 3439618
order by 1,3

*/

/*

--Atualiza transações PIX
SELECT  
CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
IDJOB,
PROCESSO,
NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
WHERE nome like '%ajust%transa%' 
AND codcoligada IS NOT NULL
ORDER BY 1,3

*/

/*

--Conciliação PIX
SELECT  
CODCOLIGADA,
STATUS,
DATA_FINAL_EXEC,
DATAPROGRAMADA,
STSJOB,
IDJOB,
PROCESSO,
NOME,
DATAFECHAMENTOESTOQUE,
LIMNEGSALDO2,
MENSAGEMSTATUS
FROM [dbo].[CONSULTA_JOB]()
where nome like 'Importação do Arquivo de Conciliação' 
AND [CONSULTA_JOB].codcoligada IS NOT NULL
order by 1,3

*/

