
SELECT 

PFUNC.CODCOLIGADA,
PFUNC.NOME											AS 'USUARIO_NOME',
--PFUNC.CODSITUACAO									AS 'SITUAÇÃO',
--TUSRTMV.CODUSUARIO									AS 'USUARIO', 
--PFUNCAO.NOME										AS 'FUNCAO',
--PSECAO.DESCRICAO									AS 'SEÇÃO',
--GCCUSTO.NOME										AS 'DEPARTAMENTO/LOCAL DE ACESSO',
GUSRPERFIL.CODSISTEMA								AS 'SISTEMA',
GUSRPERFIL.CODPERFIL								AS 'PERFIL'
--GUSRPERFIL.CODCOLIGADA								AS 'COLIGADA'
--TUSRTMV.CODTMV

FROM GUSRPERFIL						(NOLOCK)
LEFT JOIN TUSRTMV					(NOLOCK)			ON			(TUSRTMV.CODUSUARIO = GUSRPERFIL.CODUSUARIO AND GUSRPERFIL.CODCOLIGADA = TUSRTMV.CODCOLIGADA)
LEFT JOIN GUSUARIO					(NOLOCK)			ON			(GUSRPERFIL.CODUSUARIO= GUSUARIO.CODUSUARIO)
LEFT JOIN PFUNC						(NOLOCK)			ON			(PFUNC.NOME = GUSUARIO.NOME) 
LEFT JOIN PFUNCAO					(NOLOCK)			ON			(PFUNC.CODFUNCAO = PFUNCAO.CODIGO AND PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
LEFT JOIN PSECAO					(NOLOCK)			ON			(PFUNC.CODSECAO = PSECAO.CODIGO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA)
LEFT JOIN GCCUSTO				    (NOLOCK)			ON			(PSECAO.NROCENCUSTOCONT = GCCUSTO.CODCCUSTO AND PSECAO.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
LEFT JOIN GSISTEMA					(NOLOCK)			ON			(GSISTEMA.CODSISTEMA = GUSRPERFIL.CODSISTEMA)

WHERE GUSUARIO.NOME LIKE 'Graciane%Oliveira' 
AND GUSRPERFIL.CODSISTEMA = 'p'
AND PFUNC.CODSITUACAO <>  'D'
--AND GUSRPERFIL.CODPERFIL = 'portal_func'
--AND TUSRTMV.CODTMV = '1.1.80'
--AND PFUNC.CODSECAO NOT IN ('01.500.20', '01.500.11', '01.500.74')
--AND TUSRTMV.CODCOLIGADA = '10'
--and GUSUARIO.NOME LIKE '%celma%almeida%'    
--AND PFUNCAO.NOME LIKE '%seguranca%'
--AND TUSRTMV.CODUSUARIO '%ALINE%'   
--AND GCCUSTO.NOME LIKE '%OSASCO%'


GROUP BY 
PFUNC.CODCOLIGADA,
PFUNC.NOME											,
--PFUNC.CODSITUACAO									,
--TUSRTMV.CODUSUARIO								, 
--PFUNCAO.NOME										,
--PSECAO.DESCRICAO									,
--GCCUSTO.NOME										,
GUSRPERFIL.CODSISTEMA								,
GUSRPERFIL.CODPERFIL								
--GUSRPERFIL.CODCOLIGADA							
--TUSRTMV.CODTMV

ORDER BY 2 ASC


select SALARIO,* from pfunc 
WHERE NOME LIKE '%HIAGO%FERREIRA%'
AND CODSITUACAO = 'A'


