/*DECLARE @COLIGADA AS VARCHAR = 1,
		@SECAO_SETOR AS VARCHAR = '01.500.03',
		@MES_INICIAL AS VARCHAR = 'JANEIRO',
		@MES_FINAL AS VARCHAR = 'JUNHO',
		@ANO AS VARCHAR = 2024
		
*/


SELECT
Grupo.SETOR,
GRUPO.APROVADO_POR AS 'APROVADO POR',
GRUPO.DATA_INICIO,
GRUPO.MES_INICIAL,
Grupo.DATA_FIM,
GRUPO.ANO,
GRUPO.MES_FINAL,
SUM(GRUPO.HORAS_EXTRAS_PERIODO) AS 'TOTAL DE HORAS EXTRAS',
GRUPO.TIPO
FROM
		(SELECT
		PSECAO.CODIGO + ' - ' + PSECAO.DESCRICAO AS SETOR,
		USUARIO_APROVADOR.NOME AS APROVADO_POR,
		DATEDIFF (DAY,	ACESSO_ALTERNATIVO.DATA_INICIO, ACESSO_ALTERNATIVO.DATA_FIM) + 1 AS DIAS_ACESSO_ALTERNATIVO,
		ACESSO_ALTERNATIVO.DATA_INICIO AS DATA_INICIO,
			(CASE MONTH(ACESSO_ALTERNATIVO.DATA_INICIO)
				WHEN 1  THEN 'Janeiro'
				WHEN 2  THEN 'Fevereiro'
				WHEN 3  THEN 'Março'
				WHEN 4  THEN 'Abril'
				WHEN 5  THEN 'Maio'
				WHEN 6  THEN 'Junho'
				WHEN 7  THEN 'Julho'
				WHEN 8  THEN 'Agosto'
				WHEN 9  THEN 'Setembro'
				WHEN 10 THEN 'Outubro'
				WHEN 11 THEN 'Novembro'
				WHEN 12 THEN 'Dezembro'
			END) AS MES_INICIAL,
		 (CASE MONTH(ACESSO_ALTERNATIVO.DATA_FIM)
				WHEN 1  THEN 'Janeiro'
				WHEN 2  THEN 'Fevereiro'
				WHEN 3  THEN 'Março'
				WHEN 4  THEN 'Abril'
				WHEN 5  THEN 'Maio'
				WHEN 6  THEN 'Junho'
				WHEN 7  THEN 'Julho'
				WHEN 8  THEN 'Agosto'
				WHEN 9  THEN 'Setembro'
				WHEN 10 THEN 'Outubro'
				WHEN 11 THEN 'Novembro'
				WHEN 12 THEN 'Dezembro'
			END) AS MES_FINAL,
			YEAR(ACESSO_ALTERNATIVO.DATA_INICIO) AS ANO,
		ACESSO_ALTERNATIVO.DATA_FIM AS DATA_FIM,
		SUM(DBO.CALCULA_HORAS_EXTRAS_DIA(ACESSO_ALTERNATIVO.DATA_INICIO,
										(CASE WHEN ACESSO_ALTERNATIVO.DATA_FIM >= GETDATE() THEN GETDATE() ELSE ACESSO_ALTERNATIVO.DATA_FIM END),
										ACESSO_ALTERNATIVO_PARA_USUARIO.ID_USUARIO, 
										ACESSO_ALTERNATIVO_PARA_USUARIO.ID_ACESSO_ALTERNATIVO)
		) AS HORAS_EXTRAS_PERIODO,
		(CASE WHEN ACESSO_ALTERNATIVO.HORAS_EXTRA = 1 THEN 'HORA EXTRA' ELSE 'COMPENSAÇÃO DE HORAS' END) AS TIPO

		FROM ACESSO_ALTERNATIVO_PARA_USUARIO (NOLOCK)
 
		LEFT JOIN ACESSO_ALTERNATIVO					(NOLOCK) ON (ACESSO_ALTERNATIVO.ID_ACESSO_ALTERNATIVO = ACESSO_ALTERNATIVO_PARA_USUARIO.ID_ACESSO_ALTERNATIVO)
		LEFT JOIN USUARIO								(NOLOCK) ON (USUARIO.ID_USUARIO = ACESSO_ALTERNATIVO_PARA_USUARIO.ID_USUARIO)
		LEFT JOIN USUARIO_APROVADOR						(NOLOCK) ON (USUARIO_APROVADOR.ID_USUARIO_APROVADOR = ACESSO_ALTERNATIVO.USUARIO_APROVADOR)
		LEFT JOIN CORPORE_RESIDENCIAL..PFUNC AS PFUNC	(NOLOCK) ON (PFUNC.CHAPA = USUARIO.CHAPA COLLATE SQL_Latin1_General_CP1_CI_AI AND PFUNC.CODCOLIGADA = USUARIO.CODCOLIGADA) 
		LEFT JOIN CORPORE_RESIDENCIAL..PSECAO AS PSECAO	(NOLOCK) ON (PSECAO.CODIGO = PFUNC.CODSECAO AND PFUNC.CODCOLIGADA = PSECAO.CODCOLIGADA) 
												
		/* /* FILTROS USADOS NO TESTE */
		WHERE	ACESSO_ALTERNATIVO.DATA_INICIO > = '20240501' AND ACESSO_ALTERNATIVO.DATA_INICIO <= '20240614'
		AND		ACESSO_ALTERNATIVO.APROVADO = 1
		AND		PSECAO.CODCOLIGADA IN (1)
		--AND		PSECAO.CODIGOPAI IN (@SECAO_PAI)
		AND		PSECAO.CODIGO IN ('01.500.03')
		--AND		USUARIO.AD_NOME LIKE @USUARIO
		AND		USUARIO.ID_REGRA_ACESSO <> 2
		*/

		WHERE	
		ACESSO_ALTERNATIVO.DATA_INICIO > = @DATA_INICIAL AND ACESSO_ALTERNATIVO.DATA_INICIO <= @DATA_FINAL 
		AND ACESSO_ALTERNATIVO.APROVADO = 1
		AND		PSECAO.CODCOLIGADA IN (@COLIGADA)
		AND		PSECAO.CODIGOPAI IN (@SECAO_PAI)
		AND		PSECAO.CODIGO IN (@SECAO_SETOR)
		AND		USUARIO.ID_REGRA_ACESSO <> 2

		GROUP BY
		PSECAO.CODIGO,
		PSECAO.DESCRICAO,
		ACESSO_ALTERNATIVO.DATA_INICIO, 
		ACESSO_ALTERNATIVO.DATA_FIM,
		USUARIO_APROVADOR.NOME,
		ACESSO_ALTERNATIVO.HORAS_EXTRA) as GRUPO

GROUP BY 
Grupo.SETOR,
GRUPO.DATA_INICIO,
GRUPO.MES_INICIAL,
Grupo.DATA_FIM,
GRUPO.MES_FINAL,
GRUPO.TIPO,
GRUPO.ANO,
Grupo.APROVADO_POR

ORDER BY 3,5 DESC
