SELECT 
XVENDA.CODCOLIGADA,
FCFO.CGCCFO,
FCFO.NOME,
(CONVERT(VARCHAR(10),XVENDA.COD_SIT_VENDA) + ' - ' + CONVERT(VARCHAR(100),XSITUACAOVENDA.DSC_SIT_VENDA)) AS 'SATUS',
XVENDA.NUM_CONT, 
XVENDA.NUM_VENDA,
XVENDA.RECCREATEDON AS 'DT_INICIAL',
XVENDA.RECMODIFIEDON AS 'DT_FINAL',
XVENDA.DATAASSINATURA,
'INTEGRADO' AS 'STATUSINTEGRACAOVENDA',
XVENDA.COD_MOD_VENDA,
(CONVERT(VARCHAR(10),XVENDA.COD_MOD_VENDA) + ' - ' + CONVERT(VARCHAR(100),XMODALIDADEVENDA.DSC_MOD_VENDA)) AS 'MODALIDADE',
XVENDA.VALOR_VENDA,
XVENDA.COD_PESS_EMPR,
(CASE 
	WHEN XVENDA.COD_PESS_EMPR = 17569 THEN 'a0PU400000PsN6iMAF' 
	WHEN XVENDA.COD_PESS_EMPR = 17576 THEN 'a0PU400000PsN6kMAF'
	WHEN XVENDA.COD_PESS_EMPR = 17569 THEN 'a0PU400000PsN6iMAF'
	ELSE IdEmpSalesForce END) AS 'IdSalesEmp2',
Venda_Teste.MIGRAR AS 'MIGRAR?',
XITEMVENDA.NUM_UNID AS 'BLOCO',
Venda_Teste2.BlocoQuadra_c AS 'BLOCO_SALES',
CONVERT(VARCHAR(10),XITEMVENDA.NUM_SUB_UNID) AS  'APTO',
Venda_Teste2.ID AS 'UND_SALES',
XVENDA.RECCREATEDBY AS 'USUARIO_DE_CRIACAO',
Venda_Teste.D4 AS 'D4'

FROM XVENDA (NOLOCK)
INNER JOIN XCOMPRADOR		(NOLOCK) ON XCOMPRADOR.NUM_VENDA = XVENDA.NUM_VENDA
INNER JOIN FCFO				(NOLOCK) ON XCOMPRADOR.CODCFO = FCFO.CODCFO
INNER JOIN XSITUACAOVENDA	(NOLOCK) ON XSITUACAOVENDA.COD_SIT_VENDA = XVENDA.COD_SIT_VENDA
INNER JOIN XMODALIDADEVENDA	(NOLOCK) ON XMODALIDADEVENDA.COD_MOD_VENDA = XVENDA.COD_MOD_VENDA
INNER JOIN XEMPREENDIMENTO	(NOLOCK) ON XEMPREENDIMENTO.COD_PESS_EMPR = XVENDA.COD_PESS_EMPR
INNER JOIN XITEMVENDA		(NOLOCK) ON XITEMVENDA.NUM_VENDA = XVENDA.NUM_VENDA
INNER JOIN Venda_Teste		(NOLOCK) ON Venda_Teste.CGCCFO = FCFO.CGCCFO AND Venda_Teste.NUM_VENDA = XVENDA.NUM_VENDA
INNER JOIN Venda_Teste2		(NOLOCK) ON Venda_Teste2.Empreendimento_r_CodigoDoEmpreendimento_c = XVENDA.COD_PESS_EMPR 
									 AND RIGHT(Venda_Teste2.BlocoQuadra_r_Name, 2) = XITEMVENDA.NUM_UNID 
									 AND Venda_Teste2.AptoLoteCasa_c = XITEMVENDA.NUM_SUB_UNID

WHERE XVENDA.CODCOLIGADA = 1

/*
SELECT RIGHT(Venda_Teste2.BlocoQuadra_r_Name, 2)  
FROM Venda_Teste2


SELECT * 
FROM Venda_Teste
*/

/*
SELECT * 
FROM GLINKSREL
WHERE MASTERTABLE = 'XVENDA'*/

/*
select NUMEROEND,* 
from XEMPREENDIMENTO 
WHERE NOME LIKE '%VISTA%'*/