
BEGIN TRAN ;
WITH AND_REAL AS 
(
SELECT 
XSUBUNIDADE.COD_PESS_EMPR,
XSUBUNIDADE.NUM_UNID,
XSUBUNIDADE.NUM_SUB_UNID,
NUMANDAR, 
XSUBUNIDADECOMPL.ANDAR
FROM XSUBUNIDADE				(NOLOCK)
LEFT JOIN XSUBUNIDADECOMPL		(NOLOCK) ON (XSUBUNIDADE.COD_PESS_EMPR = XSUBUNIDADECOMPL.COD_PESS_EMPR AND XSUBUNIDADE.NUM_UNID = XSUBUNIDADECOMPL.NUM_UNID AND XSUBUNIDADE.NUM_SUB_UNID = XSUBUNIDADECOMPL.NUM_SUB_UNID)
)
--ROLLBACK
--COMMIT

UPDATE XSUBUNIDADECOMPL
SET ANDAR = (AND_REAL.NUMANDAR - 1)
FROM XSUBUNIDADECOMPL AS X1
INNER JOIN AND_REAL ON (AND_REAL.COD_PESS_EMPR = X1.COD_PESS_EMPR AND AND_REAL.NUM_UNID = X1.NUM_UNID AND AND_REAL.NUM_SUB_UNID = X1.NUM_SUB_UNID)




