

DECLARE @MES_APROV AS VARCHAR(10) = 'OUT',
		@COLIGADA AS INT = 51,
		@CCUSTO_INI AS VARCHAR(10) = '3.0001.05',
		@DATAINI_D AS DATE = '20241115',
		@DATAFIM_D AS DATE = '20241201';



SELECT 
(SELECT CONVERT(VARCHAR,GCCUSTO.CODCCUSTO)+' - '+ NOME FROM GCCUSTO (NOLOCK) WHERE GCCUSTO.CODCCUSTO = T.CODCCUSTO AND GCCUSTO.CODCOLIGADA = T.CODCOLIGADA) AS CENTRO_CUSTO_NOME,
(SELECT CONVERT(VARCHAR,PRJ.CODPRJ)+' - '+ CONVERT(VARCHAR,PRJ.DESCRICAO) AS NOME_PROJETO  FROM MPRJ AS PRJ WHERE PRJ.IDPRJ = T.IDPRJ AND  PRJ.CODCOLIGADA = T.CODCOLIGADA) AS NOME_PROJETO,
T.DESCRICAO,
(SELECT TOP 1 COLIGA.NOMEFANTASIA FROM GCCUSTO (NOLOCK) AS CUSTO, GCOLIGADA AS COLIGA WHERE  CUSTO.CODCOLIGADA = T.CODCOLIGADA AND CUSTO.CODCCUSTO = T.CODCCUSTO AND T.CODCOLIGADA = COLIGA.CODCOLIGADA) AS COLIGADA,
DBO.ULTIMODIAMES(GETDATE())AS QUEBRA$,
CODCQ,
/*DATEPART(MONTH,DATAAPROVACAO) AS MES_APROV,*/
--@MES_APROV AS MES_APROV,
(CASE WHEN DATEPART(YEAR,DBO.TRAZ_DATAAPROVACAO (CODCOLIGADA,IDMOV)) IS NOT NULL THEN 'RDO' ELSE '' END) AS ANO_APROV,
CODCCUSTO,
CLASSE,
(CASE CLASSE  
		WHEN 'MT' THEN 'MATERIAL' 
		WHEN 'EQ' THEN 'EQUIPAMENTO' 
		WHEN 'ST' THEN 'SERVIÇOS DE TERCEIROS'
		WHEN 'CI' THEN 'CUSTO INDIRETO OBRA'
		WHEN 'CIC' THEN 'CUSTO INDIRETO COMERCIAL'
	ELSE''
END) AS DESC_CLASSE,

SUB_CLASSE,
DESC_SUB_CLASSE,
DESC_GRUPO,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,
SUM(VALOR) AS VALOR,
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
/*USUARIO_APROVACAO,
DATAAPROVACAO,*/
DBO.APROVADOR_MOVIMENTO(CODCOLIGADA,IDMOV) AS USUARIO_APROVACAO,
DBO.TRAZ_DATAAPROVACAO (CODCOLIGADA,IDMOV)AS DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO
,T.CODCOLIGADA
,ISNULL(CODTMV_ORIGEM,'N/A') AS CODTMV_ORIGEM

FROM (
		SELECT CODCQ, TMOV.IDMOV, MTRF.CODCOLIGADA,MPRJ.DESCRICAO,TMOV.IDPRJ,
		
		(CASE WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN TMOVRATCCU.CODCCUSTO ELSE TMOV.CODCCUSTO END) AS CODCCUSTO,
		
		MTRF.CODTRF,
		ISNULL (MTRF.NOME,MTRF.DESCRICAO) AS DESCTRF,
		MTRFPAI.CODTRF AS CODTRF_PAI,
		ISNULL (MTRFPAI.NOME,MTRFPAI.DESCRICAO) AS DESCTRFPAI,
		(SELECT NOMEFANTASIA FROM TPRD (NOLOCK) WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =TMOV.CODCOLIGADA) AS DESC_GRUPO,
		ISNULL(FCFO.NOMEFANTASIA,'') AS NOME_FORNECEDOR,
		TMOV.NUMEROMOV,
		CONVERT(VARCHAR,DATEADD(D,(SELECT TOP 1 PRAZO1 FROM TCPG (NOLOCK) WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND CODCPG = TMOV.CODCPG),TMOV.DATAEMISSAO),103) AS DATAPG,
		
		PRODUTO.NOMEFANTASIA AS NOME_PRODUTO,

CASE WHEN 

		(SELECT COUNT (*)FROM TMOV CONTA (NOLOCK)
		LEFT JOIN TITMMOV CONTAITEM ON CONTA.CODCOLIGADA = CONTAITEM.CODCOLIGADA AND CONTA.IDMOV = CONTAITEM.IDMOV
		 WHERE TMOV.IDMOV = CONTA.IDMOV AND TMOV.CODCOLIGADA = CONTA.CODCOLIGADA )>1
		 
		THEN
		
		/* PREÇO MÉDIO DO ITEM FOI MULTIPLICADO PELO RATEIO (CASO TENHA RATEIO) PARA TRAZER O VALOR CORRETO BY MARCELO WAGNER 04-12-2018 */
		
			CASE WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN
		
							((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
							(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV (NOLOCK) WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
							CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
							ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
							)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 
		
								*
		
							((CASE WHEN TMOVRATCCU.VALOR = '0' OR TMOVRATCCU.VALOR IS NULL THEN TMOVRATCCULOGFAT.VALOR ELSE TMOVRATCCU.VALOR END)  * 100 / (TMOV.VALORLIQUIDOORIG)/100)
		
			ELSE
		
			
							((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
							(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV (NOLOCK) WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
							CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
							ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
							)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 
			END
		
			/* FIM DA ALTERACAO */
		WHEN 
		
		(SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1
		
		THEN 
		
		(CASE WHEN TMOVRATCCU.VALOR = '0' OR TMOVRATCCU.VALOR IS NULL THEN TMOVRATCCULOGFAT.VALOR ELSE TMOVRATCCU.VALOR END)
		
		ELSE
		
		TMOV.VALORLIQUIDOORIG

END
AS VALOR,

CONVERT(VARCHAR, TMOV.DATACRIACAO,103) AS CRIACAO,

(SELECT NOMEFANTASIA FROM TPRD (NOLOCK)WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =1)AS PRODUTO,
ISNULL(LEFT((SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA),4),'') AS SUB_CLASSE,

ISNULL((SELECT DESCRICAO FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA),'') AS DESC_SUB_CLASSE,


case 
	when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
		and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
		and codcoligada = TMOV.CODCOLIGADA) in	('AC','ALT','AUD','C','CO','CP','DBC','EPI','FX','HB','MA','MMI','MOI','MOL',
												'MOS','PJ','RP','S','TO','TR','TX','USI','V')
		
		then 'CI'  when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
		and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
		and codcoligada = TMOV.CODCOLIGADA) in('APE','CG','CMD','ITB','MKT - CP','MKT - CP','MKT - PROD','MKT - PROM','PBL','PBO','SV','VD')
		
		then 'CIC' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' 
					and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
					and codcoligada = TMOV.CODCOLIGADA) IN( 'T','FER','AL-EQ')
		then 'EQ' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) and codcoligada = TMOV.CODCOLIGADA) = 'AND'
		then 'MT' else
		
		case when (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' and CODCLIENTE = dbo.pegapaifase1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) and codcoligada = TMOV.CODCOLIGADA) IN('CT','AL-ST')
		then 'ST' else
		case when left(produto.CODIGOPRD,1) = 'D' then 'CI' else
			case when left(produto.CODIGOPRD,1) = 'M' then 'MT' else
			case when left(produto.CODIGOPRD,1) = 'S' then 'ST' else
			case when left(produto.CODIGOPRD,1) = 'E' then 'EQ' else
			case when left(produto.CODIGOPRD,1) = 'T' then 'MT' else
			case when left(produto.CODIGOPRD,1) = 'A' then 'ST'
			end
		end
			END
			end
			end
			end
		end
		END
		END
END AS CLASSE,

TMOV.CODTMV,
DBO.TRAZ_STATUS(TMOV.STATUS) AS STATUS,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
/*TMOVAPROVA.CODUSUARIO AS USUARIO_APROVACAO,
TMOVAPROVA.DATAAPROVACAO,*/
TMOV.DATAEMISSAO,

(SELECT TOP 1 FLAN.IDLAN FROM FLAN (NOLOCK)
	LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
	WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
	AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
	AND		FLAN.CODTB2FLX NOT IN ('129','02.023')
) AS REFERENCIA_PGTO,

(SELECT TOP 1 REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLAN.HISTORICO),CHAR(13) + CHAR(10),' '),';',' ') FROM FLAN (NOLOCK)
	LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
	WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
	AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
	AND		FLAN.CODTB2FLX NOT IN ('129','02.023')
) AS HISTORICO_PGTO,

(SELECT TOP 1 MOVT.CODTMV
	FROM TMOVRELAC (NOLOCK)
	INNER JOIN TMOV AS MOVT (NOLOCK) ON (MOVT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOVT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
	WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV  AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA
) AS CODTMV_ORIGEM 

FROM TMOV (NOLOCK)
INNER JOIN TITMMOV 		(NOLOCK) on (TMOV.IDMOV = TITMMOV.IDMOV and TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT  JOIN TMOVRATCCU		(NOLOCK) ON (TMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCU.IDMOV = TMOV.IDMOV)
LEFT JOIN TMOVRATCCULOGFAT		(NOLOCK) ON (TMOVRATCCULOGFAT.IDMOVRATCCU = TMOVRATCCU.IDMOVRATCCU AND TMOVRATCCULOGFAT.IDMOV = TMOV.IDMOV AND TMOVRATCCULOGFAT.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TMOVRATCCULOGFAT FAT WHERE TMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TMOVRATCCULOGFAT.IDMOVRATCCU))
left JOIN MPRJ 			(NOLOCK) ON (ISNULL(TMOVRATCCU.CODCOLIGADA,TITMMOV.CODCOLIGADA) = MPRJ.CODCOLIGADA AND ISNULL(TMOVRATCCU.IDPRJ,TITMMOV.IDPRJ) = MPRJ.IDPRJ )
LEFT JOIN MPRJCOMPL 		(NOLOCK) on (MPRJ.CODCOLIGADA = MPRJCOMPL.CODCOLIGADA and MPRJ.IDPRJ = MPRJCOMPL.IDPRJ)
LEFT JOIN MTRF 			(NOLOCK) on (MPRJ.CODCOLIGADA = MTRF.CODCOLIGADA and MPRJ.IDPRJ = MTRF.IDPRJ  AND TITMMOV.IDTRF = MTRF.IDTRF)
LEFT JOIN MTRF AS MTRFPAI 	(NOLOCK) ON (MTRFPAI.IDTRF = MTRF.IDPAI AND MTRFPAI.IDPRJ = MTRF.IDPRJ AND MTRFPAI.CODCOLIGADA = MTRF.CODCOLIGADA)
										
INNER JOIN TPRD  as produto              (NOLOCK) on (produto.CODCOLIGADA = TITMMOV.CODCOLIGADA and produto.IDPRD = TITMMOV.IDPRD)
LEFT JOIN FCFO 			(NOLOCK) on (TMOV.CODCOLCFO = FCFO.CODCOLIGADA and TMOV.CODCFO = FCFO.CODCFO)
/*LEFT JOIN TMOVAPROVA 		(NOLOCK) ON (TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)*/


WHERE 
TMOV.CODCOLIGADA IN (@COLIGADA)
/*AND MPRJ.CODPRJ IN (@CODPRJ)*/
AND (MPRJ.CODPRJ LIKE '__.____.___' OR MPRJ.CODPRJ LIKE 'VIAB.__.____.___')

AND (

		/*CASE WHEN CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.64','1.1.15') 
				and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) > 0
			THEN (SELECT count(*) FROM TMOVAPROVA (NOLOCK) WHERE 
									TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and
									TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1) 
		
			WHEN CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  
				AND (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) = 0 
				OR CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15')  
				AND (SELECT QUANTIDADERATEADAS FROM TCTRCMOV (NOLOCK) WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA) is null
			
			THEN (SELECT count(*) FROM TMOVAPROVA (NOLOCK) WHERE 
					TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA and
					TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)
		
		END > 0*/

		case when CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.64','1.1.15','1.1.40', '1.1.41') and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) > 0
then (SELECT COUNT (DBO.TRAZ_DATAAPROVACAO (MOV.CODCOLIGADA,MOV.IDMOV)) FROM TMOV AS MOV WHERE TMOV.IDMOV = MOV.IDMOV AND TMOV.CODCOLIGADA = MOV.CODCOLIGADA)

when CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15','1.1.40', '1.1.41')  and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) = 0 or CODTMV IN ('1.1.43','1.1.19','1.1.42','1.1.60','1.1.61','1.1.24','1.1.49','1.1.66','1.1.64','1.1.15','1.1.40', '1.1.41')  and (SELECT QUANTIDADERATEADAS FROM TCTRCMOV WHERE TCTRCMOV.IDMOV = TMOV.IDMOV  AND TCTRCMOV.CODCOLIGADA = TMOV.CODCOLIGADA
) is null
then (SELECT COUNT (DBO.TRAZ_DATAAPROVACAO (MOV.CODCOLIGADA,MOV.IDMOV)) FROM TMOV AS MOV WHERE TMOV.IDMOV = MOV.IDMOV AND TMOV.CODCOLIGADA = MOV.CODCOLIGADA)

END > 0
 
	)

AND (CASE 
		WHEN (SELECT COUNT (*) FROM TMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 
		THEN TMOVRATCCU.CODCCUSTO 
		ELSE TMOV.CODCCUSTO 
	END) IN (@CCUSTO_INI)


AND DBO.TRAZ_DATAAPROVACAO (TMOV.CODCOLIGADA,TMOV.IDMOV) BETWEEN @DATAINI_D AND dateadd(day,1,@DATAFIM_D)
and tmov.STATUS <> 'C'
AND (TITMMOV.QUANTIDADE > 0 OR TITMMOV.QUANTIDADETOTAL > 0)
) as t
GROUP BY 
CODCCUSTO,
CODCQ,
CLASSE,
SUB_CLASSE,
DESC_SUB_CLASSE,
DESC_GRUPO,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
/*USUARIO_APROVACAO,
DATAAPROVACAO,*/
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO
,CODTMV_ORIGEM
,T.CODCOLIGADA
,T.DESCRICAO
,T.IDPRJ
,DBO.APROVADOR_MOVIMENTO(CODCOLIGADA,IDMOV)
,DBO.TRAZ_DATAAPROVACAO(CODCOLIGADA,IDMOV)

ORDER BY DATAPG