SELECT

FLAN.CODCFO,
FCFO.CODCOLIGADA,
FCFO.NOMEFANTASIA AS FORNECEDOR,
FLAN.CODCCUSTO,
ISNULL(FLAN.VALORBAIXADO,0) AS ADIANTAMENTO_CX4

FROM FLAN 

/*LEFT JOIN FRELLAN					(NOLOCK) ON (FLAN.IDLAN = FRELLAN.IDLANREL AND FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA)*/
LEFT JOIN FTB4						(NOLOCK) ON (FLAN.CODTB4FLX = FTB4.CODTB4FLX AND FLAN.CODCOLIGADA = FTB4.CODCOLIGADA)
LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
/*LEFT JOIN FLAN DESCONTO (NOLOCK) ON (DESCONTO.IDLAN = FRELLAN.IDLAN AND DESCONTO.CODCOLIGADA = FRELLAN.CODCOLIGADA)
LEFT JOIN FTB2						(NOLOCK) ON (FTB2.CODTB2FLX = DESCONTO.CODTB2FLX AND FTB2.CODCOLIGADA = DESCONTO.CODCOLIGADA)*/

WHERE
 FLAN.CODTDO IN ('0044')
AND FLAN.PAGREC = 1
AND FLAN.CODCOLIGADA = @COD_COLIGADA
AND  (SELECT TOP 1 FLANBAIXA.CODCXA FROM FLANBAIXA WHERE FLANBAIXA.IDLAN = FLAN.IDLAN AND FLANBAIXA.CODCOLIGADA = FLAN.CODCOLIGADA AND FLANBAIXA.CODCXA = '8' ) IN ('8')
AND FLAN.CODTB2FLX IN ('02.009','02.125')
) AS GRUPO2

GROUP BY

GRUPO2.CODCFO,
GRUPO2.FORNECEDOR,
GRUPO2.CODCOLIGADA,
GRUPO2.CODCCUSTO

) AS ADIANTAMENTO_CX4 ON (ADIANTAMENTO_CX4.CODCFO = EMPREITEIROS.CODCFO AND ADIANTAMENTO_CX4.CODCCUSTO = EMPREITEIROS.CODCCUSTO AND ADIANTAMENTO_CX4.CODCOLIGADA = EMPREITEIROS.CODCOLIGADA)