/*DECLARE @MES_APROV AS VARCHAR(10) = 'OUT',
		@COLIGADA AS INT = 1,
		--@CCUSTO_INI as varchar(10) = '5.0095',
		@DATAINI_D AS DATE = '20241001',
		@DATAFIM_D AS DATE = '20241201';*/
		
SELECT (CASE GRUPO.CLASSE 
		WHEN 'MT' THEN 'MATERIAL' 
		WHEN 'EQ' THEN 'EQUIPAMENTO' 
		WHEN 'ST' THEN 'SERVIÇOS DE TERCEIROS'
		WHEN 'CI' THEN 'CUSTO INDIRETO'
		WHEN 'CIC' THEN 'CUSTO INDIRETO COMERCIAL'
	ELSE''
END) AS DESC_CLASSE,
GRUPO.CENTRO_CUSTO_NOME,
GRUPO.QUEBRA$,
GRUPO.CODCQ,
GRUPO.MES_APROV,
GRUPO.ANO_APROV,
GRUPO.CODCCUSTO,
GRUPO.CODIGOPRD,
GRUPO.FASE,
GRUPO.CLASSE,
GRUPO.SUB_CLASSE,
GRUPO.DESC_SUB_CLASSE,
GRUPO.DESC_GRUPO,
GRUPO.DESC_INS,
GRUPO.CODGRUPO,
GRUPO.DESCRICAO_GRUPO,
GRUPO.NOME_FORNECEDOR,
GRUPO.NUMEROMOV,
GRUPO.DATAEMISSAO,
GRUPO.VALOR,
GRUPO.CODTMV,
GRUPO.STATUS,
GRUPO.USUARIOCRIACAO,
GRUPO.DATACRIACAO,
GRUPO.USUARIO_APROVACAO,
GRUPO.DATAAPROVACAO,
GRUPO.DATAPG,
GRUPO.IDMOV,
GRUPO.REFERENCIA_PGTO,
GRUPO.HISTORICO_PGTO,
GRUPO.CODTRF,
GRUPO.CODTRF_PAI,
GRUPO.DESCTRFPAI,
GRUPO.NOME_PRODUTO,
GRUPO.UND_PROD,
GRUPO.QTD,
GRUPO.PRECO_UNIT,
GRUPO.CODTMV_ORIGEM,
GRUPO.DESCTRF,
grupo.cod_cc
FROM(

SELECT
T.CODCCUSTO AS 'CENTRO_CUSTO_NOME',
t.cod_cc,
(SELECT CONVERT(VARCHAR, CODCOLIGADA) + ' - ' + NOMEFANTASIA FROM GCOLIGADA (NOLOCK) WHERE T.CODCOLIGADA = GCOLIGADA.CODCOLIGADA) AS NOME_COLIGADA,
DBO.ULTIMODIAMES(GETDATE())AS QUEBRA$,
CODCQ,
/*DATEPART(MONTH,DATAAPROVACAO) AS MES_APROV,*/
@MES_APROV AS MES_APROV,
/*DATEPART(YEAR,DATAAPROVACAO) AS ANO_APROV,*/
(CASE WHEN DATAAPROVACAO IS NOT NULL 
		THEN 'RDA'
	  ELSE ''
END) AS ANO_APROV,
CODCCUSTO,
CODIGOPRD,
FASE,
(CASE 
	WHEN CODCLASSIFICA IN (10, 4, 6) THEN 'CIC'
	WHEN CODCLASSIFICA = 3 THEN 'CI' 
	WHEN CODTMV IN ('1.1.06', '1.1.40', '1.1.41', '1.1.42', '1.1.43') AND CODTMV_ORIGEM = '1.1.06' THEN 'ST'
	/*WHEN CODTMV = '1.1.27' AND ID_REQUISICAO_RMO IS NULL THEN 'MT'*/
	 WHEN SUB_CLASSE IN ('AC','ADM','AL','ALM','ALT','ATAE','ATE','ATEC','ATEL','ATH','ATIN','ATPO','AT-PO','ATRC','ATT','AUAX','AUD','C','CA','CO','CP','DBC','DF','DI','DRE','DVR','EPC',
                         'EX','EXT','EXTEL','FX','HB','I TX','LC','LD','MA','MAP','MC','ME','MMI','MOI','MOL','MOS','MTO','OTR','PJ','RP','S','SO','TFSLQA','TI','TO','TR','TX','V','VT') THEN 'CI'
	WHEN SUB_CLASSE IN  ('IPDV','MKTC','MKTIN','MKTM','MKTOUT','MKTPD','MKTPM','MKTPP','MKTPPI','MKTRE','MKTRV','MKTSI','MPDV','PBL','PBO','SMAQ','SV','SVC','SVF','SVM','SVP','SVS','VD') THEN 'CIC'
	WHEN LEFT(CODIGOPRD,3) = '001' THEN 'MT'
	WHEN LEFT(CODIGOPRD,3) = '002' THEN 'ST'
	WHEN LEFT(CODIGOPRD,3) = '003' THEN 'EQ'
	WHEN LEFT(CODIGOPRD,3) = '999' THEN [dbo].[CLASSEPORFASE](SUB_CLASSE)
	ELSE 'SEM CLASSE' END) AS 'CLASSE',

SUB_CLASSE,
DESC_SUB_CLASSE,
DESC_GRUPO,
DESC_INS,
CODGRUPO,
DESCRICAO_GRUPO,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,


CASE WHEN SUM(VALOR) = '0' THEN  ISNULL((SELECT SUM(TMOVRATCCULOGFAT.VALOR) 
											FROM TMOVRATCCULOGFAT (NOLOCK)
											WHERE IDMOV = T.IDMOV 
											AND TMOVRATCCULOGFAT.CODCOLIGADA IN (@COLIGADA )
											AND TMOVRATCCULOGFAT.CODCCUSTO IN (@CCUSTO_INI)),0) ELSE SUM (VALOR) END as 'VALOR',
CODTMV,
STATUS,
USUARIOCRIACAO,
DATACRIACAO,
USUARIO_APROVACAO,
DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO,
UND_PROD,
QTD,
PRECO_UNIT,
ISNULL(CODTMV_ORIGEM,'N/A') AS CODTMV_ORIGEM,
T.NUMEROSEQUENCIAL

FROM (
SELECT CODCQ, 
TMOV.IDMOV, 
TMOV.CODCOLIGADA,

(CASE WHEN (SELECT COUNT (*) FROM TITMMOVRATCCU (NOLOCK) WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN (CONVERT(VARCHAR(10),TITMMOVRATCCU.CODCCUSTO) + ' - ' + GCCUSTO.NOME) ELSE (CONVERT(VARCHAR(10),TMOV.CODCCUSTO) + ' - ' + GCCUSTO.NOME) END) AS CODCCUSTO,
TITMMOVRATCCU.CODCCUSTO as 'cod_cc',

MTRF.CODTRF,
ISNULL (MTRF.NOME,MTRF.DESCRICAO) AS DESCTRF,
MTRFPAI.CODTRF AS CODTRF_PAI,
ISNULL (MTRFPAI.NOME,MTRFPAI.DESCRICAO) AS DESCTRFPAI,
(SELECT NOMEFANTASIA FROM TPRD (NOLOCK) WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) AND CODCOLIGADA =TMOV.CODCOLIGADA) AS DESC_GRUPO,
(SELECT TTB22.DESCRICAO 
FROM TTB2 AS TTB22
WHERE TTB22.CODCOLIGADA = PRODUTO_DEF.CODCOLIGADA AND TTB22.CODTB2FAT = PRODUTO_DEF.CODTB2FAT) AS 'DESC_INS',
TITMMOV.CODUND AS 'UND_PROD',
(CASE WHEN (SELECT COUNT (*) FROM TITMMOVRATCCU WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV ) > 1 
	  THEN

	  		(CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)
						*
			((CASE WHEN TITMMOVRATCCU.VALOR = '0' OR TITMMOVRATCCU.VALOR IS NULL THEN TITMMOVRATCCULOGFAT.VALOR ELSE TITMMOVRATCCU.VALOR END)  * 100 / (TITMMOV.PRECOUNITARIO * (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END))/100)
			

	ELSE
			(CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END)
END) AS QTD,


TITMMOV.PRECOUNITARIO AS 'PRECO_UNIT',

ISNULL(FCFO.NOMEFANTASIA,'') AS NOME_FORNECEDOR,
TMOV.NUMEROMOV,
CONVERT(VARCHAR,DATEADD(D,(SELECT TOP 1 PRAZO1 FROM TCPG (NOLOCK) WHERE CODCOLIGADA = TMOV.CODCOLIGADA AND CODCPG = TMOV.CODCPG),TMOV.DATAEMISSAO),103) DATAPG,

PRODUTO.NOMEFANTASIA AS NOME_PRODUTO,
( CASE WHEN 

(select COUNT (*)from TMOV CONTA 
LEFT JOIN TITMMOV CONTAITEM ON CONTA.CODCOLIGADA = CONTAITEM.CODCOLIGADA AND CONTA.IDMOV = CONTAITEM.IDMOV
 WHERE TMOV.IDMOV = CONTA.IDMOV AND TMOV.CODCOLIGADA = CONTA.CODCOLIGADA )>1
 
THEN

/* PREÇO MÉDIO DO ITEM FOI MULTIPLICADO PELO RATEIO (CASO TENHA RATEIO) PARA TRAZER O VALOR CORRETO BY MARCELO WAGNER 04-12-2018 */

	CASE WHEN (SELECT COUNT (*) FROM TITMMOVRATCCU WHERE IDMOV = TITMMOV.IDMOV AND CODCOLIGADA = TITMMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV) >=  1 THEN

					((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
					(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
					CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
					ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
					)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 

						*

					((CASE WHEN TITMMOVRATCCU.VALOR = '0' OR TITMMOVRATCCU.VALOR IS NULL THEN TITMMOVRATCCULOGFAT.VALOR ELSE TITMMOVRATCCU.VALOR END)  * 100 / (TITMMOV.PRECOUNITARIO * (CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END))/100) 

	ELSE

	
					((((TITMMOV.PRECOUNITARIO + (ISNULL(TITMMOV.VALORFRETECTRC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) - (ISNULL(TITMMOV.VALORDESC,0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ) + 
					(ISNULL((SELECT SUM(VALOR) FROM TTRBMOV WHERE CODCOLIGADA = TITMMOV.CODCOLIGADA AND IDMOV = TITMMOV.IDMOV AND NSEQITMMOV = TITMMOV.NSEQITMMOV AND CODTRB = 'IPI'),0)/ CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) +  
					CASE WHEN ISNULL( CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END ,0) < 1 THEN ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  )) 
					ELSE ((ISNULL(TMOV.VALORFRETE,0)-ISNULL(TMOV.VALORDESC,0)+ISNULL(TMOV.VALOREXTRA1,0)) * ((TITMMOV.PRECOUNITARIO *  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  ) /  CASE WHEN TMOV.VALORBRUTO = '0' THEN TMOV.VALORBRUTOORIG ELSE TMOV.VALORBRUTO END  ))/  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END  END 
					)*  CASE WHEN TITMMOV.QUANTIDADE = '0' THEN TITMMOV.QUANTIDADETOTAL ELSE TITMMOV.QUANTIDADE END )) 
	END

	/* FIM DA ALTERACAO */
WHEN 

(SELECT COUNT (*) FROM TITMMOVRATCCU WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV) > = 1

THEN 

TITMMOV.PRECOUNITARIO/*(CASE WHEN TITMMOVRATCCU.VALOR = '0' OR TITMMOVRATCCU.VALOR IS NULL THEN TITMMOVRATCCULOGFAT.VALOR ELSE TITMMOVRATCCU.VALOR END)*/

ELSE

TMOV.VALORLIQUIDOORIG

END

)

 AS VALOR,

CONVERT(VARCHAR, TMOV.DATACRIACAO,103) AS CRIACAO,
(SELECT NOMEFANTASIA 
	FROM TPRD (NOLOCK) 
	WHERE CODIGOPRD = LEFT(PRODUTO.CODIGOPRD,4) 
		AND CODCOLIGADA =1)AS PRODUTO,

ISNULL(LEFT((SELECT CODCLIENTE 
				FROM GCONSIST (NOLOCK) 
				WHERE CODTABELA = 'FASE' 
					AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
					AND CODCOLIGADA = TMOV.CODCOLIGADA),4),'') AS SUB_CLASSE,

ISNULL((SELECT DESCRICAO 
			FROM GCONSIST (NOLOCK)  
			WHERE CODTABELA = 'FASE' 
				AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
				AND CODCOLIGADA = TMOV.CODCOLIGADA),'') AS DESC_SUB_CLASSE,

CASE WHEN (SELECT CODCLIENTE 
			FROM GCONSIST (NOLOCK) 
			WHERE CODTABELA = 'FASE' 
				AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
				AND CODCOLIGADA = TMOV.CODCOLIGADA) IN ('AC','ALT','AUD','C','CO','CP','DBC','EPI','FX','HB','MA','MMI','MOI','MOL',
														'MOS','PJ','RP','S','TO','TR','TX','USI','V')
THEN 'CIO'  WHEN (SELECT CODCLIENTE 
					FROM GCONSIST (NOLOCK) 
					WHERE CODTABELA = 'FASE' 
						AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) 
						AND CODCOLIGADA = TMOV.CODCOLIGADA) IN('APE','CG','CMD','ITB','MKT - CP','MKT - CP','MKT - PROD','MKT - PROM','PBL','PBO','SV','VD')

THEN 'CIC' ELSE

CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA) IN( 'T','FER','AL-EQ')
THEN 'EQ' ELSE

CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA) = 'AND'
THEN 'MT' ELSE

CASE WHEN (SELECT CODCLIENTE FROM GCONSIST (NOLOCK) WHERE CODTABELA = 'FASE' AND CODCLIENTE = DBO.PEGAPAIFASE1(TMOV.CODCOLIGADA,TMOV.IDPRJ,TITMMOV.IDTRF,MTRF.IDPAI) AND CODCOLIGADA = TMOV.CODCOLIGADA) IN('CT','AL-ST')
THEN 'ST' ELSE
CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'D' THEN 'CI' ELSE
	CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'M' THEN 'MT' ELSE
	CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'S' THEN 'ST' ELSE
	CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'E' THEN 'EQ' ELSE
	CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'T' THEN 'MT' ELSE
	CASE WHEN LEFT(PRODUTO.CODIGOPRD,1) = 'A' THEN 'ST'
	END
END
	END
	END
	END
	END
END
END
END
END AS FASE,
TPRDGRUPOPRODUTO.CODGRUPO,
(TGRUPOPRODUTO.CODGRUPO + ' - ' + TGRUPOPRODUTO.DESCRICAO) AS 'DESCRICAO_GRUPO',
TMOV.CODTMV,
DBO.TRAZ_STATUS(TMOV.STATUS) AS STATUS,
TMOV.USUARIOCRIACAO,
TMOV.DATACRIACAO,
TMOVAPROVA.CODUSUARIO AS USUARIO_APROVACAO,
TMOVAPROVA.DATAAPROVACAO,
TMOV.DATAEMISSAO,

(SELECT TOP 1 FLAN.IDLAN FROM FLAN (NOLOCK)
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
AND		FLAN.CODTB2FLX <> '129') AS REFERENCIA_PGTO,

(SELECT TOP 1 REPLACE (REPLACE (CONVERT (VARCHAR(MAX) ,FLAN.HISTORICO),CHAR(13) + CHAR(10),' '),';',' ') 
FROM FLAN (NOLOCK)
LEFT JOIN TMOVRELAC (NOLOCK) ON (TMOVRELAC.IDMOVDESTINO = FLAN.IDMOV AND TMOVRELAC.CODCOLDESTINO = FLAN.CODCOLIGADA)
WHERE	TMOVRELAC.IDMOVORIGEM = TMOV.IDMOV
AND		TMOVRELAC.CODCOLORIGEM = TMOV.CODCOLIGADA
AND		FLAN.CODTB2FLX <> '129') AS HISTORICO_PGTO,

(SELECT TOP 1 MOVT.CODTMV
FROM TMOVRELAC (NOLOCK)
INNER JOIN TMOV AS MOVT (NOLOCK) ON (MOVT.IDMOV = TMOVRELAC.IDMOVORIGEM AND MOVT.CODCOLIGADA = TMOVRELAC.CODCOLORIGEM)
WHERE TMOVRELAC.IDMOVDESTINO = TMOV.IDMOV  AND TMOVRELAC.CODCOLDESTINO = TMOV.CODCOLIGADA
) AS CODTMV_ORIGEM,
GCCUSTO.CODCLASSIFICA,
TMOVCOMPL.ID_REQUISICAO_RMO,
PRODUTO.CODIGOPRD, 
TITMMOV.NUMEROSEQUENCIAL

FROM TMOV (NOLOCK)
INNER JOIN TITMMOV								(NOLOCK) ON (TMOV.IDMOV = TITMMOV.IDMOV AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
LEFT JOIN TMOVRATCCU							(NOLOCK) ON (TMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCU.IDMOV = TMOV.IDMOV)
LEFT JOIN MPRJ 									(NOLOCK) ON (ISNULL(TMOVRATCCU.CODCOLIGADA,TITMMOV.CODCOLIGADA) = MPRJ.CODCOLIGADA AND ISNULL(TMOVRATCCU.IDPRJ,TITMMOV.IDPRJ) = MPRJ.IDPRJ )
LEFT JOIN MPRJCOMPL 							(NOLOCK) ON (MPRJ.CODCOLIGADA = MPRJCOMPL.CODCOLIGADA AND MPRJ.IDPRJ = MPRJCOMPL.IDPRJ)
LEFT JOIN MTRF 									(NOLOCK) ON (MTRF.CODCOLIGADA = TITMMOV.CODCOLIGADA AND MTRF.IDPRJ = TITMMOV.IDPRJ  AND TITMMOV.IDTRF = MTRF.IDTRF)
LEFT JOIN MTRF AS MTRFPAI 						(NOLOCK) ON (MTRFPAI.IDTRF = MTRF.IDPAI AND MTRFPAI.IDPRJ = MTRF.IDPRJ AND MTRFPAI.CODCOLIGADA = MTRF.CODCOLIGADA)
INNER JOIN TPRD AS PRODUTO 						(NOLOCK) ON (PRODUTO.CODCOLIGADA = TITMMOV.CODCOLIGADA AND PRODUTO.IDPRD = TITMMOV.IDPRD)
INNER JOIN TPRODUTODEF as PRODUTO_DEF			(NOLOCK) ON (PRODUTO_DEF.IDPRD = PRODUTO.IDPRD AND PRODUTO_DEF.CODCOLIGADA = PRODUTO.CODCOLIGADA) 
LEFT JOIN TPRDGRUPOPRODUTO						(NOLOCK) ON (TPRDGRUPOPRODUTO.IDPRD = PRODUTO.IDPRD AND TPRDGRUPOPRODUTO.CODCOLPRD = PRODUTO.CODCOLIGADA)
LEFT JOIN TGRUPOPRODUTO							(NOLOCK) ON (TGRUPOPRODUTO.CODCOLIGADA = TPRDGRUPOPRODUTO.CODCOLPRD AND TGRUPOPRODUTO.CODGRUPO = TPRDGRUPOPRODUTO.CODGRUPO)
LEFT  JOIN FCFO 								(NOLOCK) ON (TMOV.CODCOLCFO = FCFO.CODCOLIGADA AND TMOV.CODCFO = FCFO.CODCFO)
LEFT JOIN TMOVAPROVA 							(NOLOCK) ON (TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA AND TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)
LEFT JOIN TITMMOVRATCCU							(NOLOCK) ON (TITMMOVRATCCU.IDMOV = TMOV.IDMOV AND TITMMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOVRATCCU.NSEQITMMOV = TITMMOV.NSEQITMMOV)
LEFT JOIN TMOVRATCCULOGFAT						(NOLOCK) ON (TMOVRATCCULOGFAT.IDMOVRATCCU = TMOVRATCCU.IDMOVRATCCU AND TMOVRATCCULOGFAT.IDMOV = TMOV.IDMOV AND TMOVRATCCULOGFAT.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TMOVRATCCULOGFAT FAT WHERE TMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TMOVRATCCULOGFAT.IDMOVRATCCU))
LEFT JOIN TITMMOVRATCCULOGFAT					(NOLOCK) ON (TITMMOVRATCCULOGFAT.NSEQITMMOV= TITMMOVRATCCU.NSEQITMMOV AND TITMMOVRATCCULOGFAT.IDMOVRATCCU = TITMMOVRATCCU.IDMOVRATCCU AND TITMMOVRATCCULOGFAT.IDMOV = TITMMOVRATCCU.IDMOV AND TITMMOVRATCCULOGFAT.CODCOLIGADA = TITMMOVRATCCU.CODCOLIGADA AND TITMMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TITMMOVRATCCULOGFAT FAT WHERE TITMMOVRATCCULOGFAT.NSEQITMMOV = FAT.NSEQITMMOV AND TITMMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TITMMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TITMMOVRATCCULOGFAT.IDMOVRATCCU))
INNER JOIN GCCUSTO								(NOLOCK) ON (TITMMOVRATCCU.CODCCUSTO = GCCUSTO.CODCCUSTO AND TITMMOVRATCCU.CODCOLIGADA = GCCUSTO.CODCOLIGADA)
INNER JOIN TMOVCOMPL							(NOLOCK) ON (TMOV.IDMOV = TMOVCOMPL.IDMOV AND TMOV.CODCOLIGADA = TMOVCOMPL.CODCOLIGADA)

/*
INNER JOIN TITMMOV 		(NOLOCK) ON (TMOV.IDMOV = TITMMOV.IDMOV AND TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA)
INNER JOIN MPRJ 			(NOLOCK) ON (TMOV.CODCOLIGADA = MPRJ.CODCOLIGADA AND TMOV.IDPRJ = MPRJ.IDPRJ )
INNER JOIN MPRJCOMPL 		(NOLOCK) ON (MPRJ.CODCOLIGADA = MPRJCOMPL.CODCOLIGADA AND MPRJ.IDPRJ = MPRJCOMPL.IDPRJ)
LEFT JOIN MTRF 			(NOLOCK) ON (MPRJ.CODCOLIGADA = MTRF.CODCOLIGADA AND MPRJ.IDPRJ = MTRF.IDPRJ  AND TITMMOV.IDTRF = MTRF.IDTRF)
LEFT JOIN MTRF AS MTRFPAI 	(NOLOCK) ON (MTRFPAI.IDTRF = MTRF.IDPAI AND MTRFPAI.IDPRJ = MTRF.IDPRJ AND MTRFPAI.CODCOLIGADA = MTRF.CODCOLIGADA)
INNER JOIN TPRD AS PRODUTO 	(NOLOCK) ON (PRODUTO.CODCOLIGADA = TITMMOV.CODCOLIGADA AND PRODUTO.IDPRD = TITMMOV.IDPRD)
LEFT OUTER JOIN FCFO 		(NOLOCK) ON (TMOV.CODCOLCFO = FCFO.CODCOLIGADA AND TMOV.CODCFO = FCFO.CODCFO)
LEFT JOIN TMOVAPROVA 		(NOLOCK) ON (TMOV.CODCOLIGADA = TMOVAPROVA.CODCOLIGADA AND TMOV.IDMOV = TMOVAPROVA.IDMOV AND TMOVAPROVA.TIPOAPROVACAO = 1)
LEFT JOIN TMOVRATCCU          (NOLOCK) ON (TMOVRATCCU.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCU.IDMOV = TMOV.IDMOV)
LEFT JOIN TMOVRATCCULOGFAT		(NOLOCK) ON (TMOVRATCCULOGFAT.IDMOVRATCCU = TMOVRATCCU.IDMOVRATCCU AND TMOVRATCCULOGFAT.IDMOV = TMOV.IDMOV AND TMOVRATCCULOGFAT.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVRATCCULOGFAT.IDPROCESSOFAT = (SELECT MIN(IDPROCESSOFAT) FROM TMOVRATCCULOGFAT FAT WHERE TMOVRATCCULOGFAT.IDMOV = FAT.IDMOV AND FAT.CODCOLIGADA = TMOVRATCCULOGFAT.CODCOLIGADA AND FAT.IDMOVRATCCU = TMOVRATCCULOGFAT.IDMOVRATCCU))
*/

WHERE 
TMOV.CODCOLIGADA IN (@COLIGADA)
/*AND MPRJ.CODPRJ IN (@CODPRJ)*/
AND CASE WHEN 
                (SELECT COUNT (*) FROM TITMMOVRATCCU (NOLOCK) 
	      WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN TITMMOVRATCCU.CODCCUSTO 
          ELSE TMOV.CODCCUSTO END IN (@CCUSTO_INI)

AND CAST(TMOVAPROVA.DATAAPROVACAO AS DATE)  >= @DATAINI_D 
AND CAST(TMOVAPROVA.DATAAPROVACAO AS DATE)  <= @DATAFIM_D 
AND TMOV.STATUS <> 'C'
/*AND TMOV.IDMOV = '2215622'*/
AND (TITMMOV.QUANTIDADE > 0 OR TITMMOV.QUANTIDADETOTAL > 0)
AND CODTMV IN ('1.1.62','1.1.63')
AND CASE WHEN TMOV.CODTMV = '1.1.66'  THEN (SELECT COUNT(C.IDMOVCTRC) 
						FROM TMOV M (NOLOCK), FCFO F (NOLOCK), TCTRCENTRADA C (NOLOCK) 
						WHERE M.CODCOLCFO = F.CODCOLIGADA AND M.CODCFO = F.CODCFO AND M.CODCOLIGADA = C.CODCOLIGADA 
						AND M.IDMOV = C.IDMOVNF AND C.CODCOLIGADA = TMOV.CODCOLIGADA AND C.IDMOVCTRC = TMOV.IDMOV)
	ELSE 0 END
	 = 0
/*
	 WHERE 
TMOV.CODCOLIGADA IN (1)
/*AND MPRJ.CODPRJ IN (@CODPRJ)*/
AND CASE WHEN 
                (SELECT COUNT (*) FROM TITMMOVRATCCU (NOLOCK) 
	      WHERE IDMOV = TMOV.IDMOV AND CODCOLIGADA = TMOV.CODCOLIGADA) > = 1 THEN TITMMOVRATCCU.CODCCUSTO 
          ELSE TMOV.CODCCUSTO END IN ('5.0095')

AND CAST(TMOVAPROVA.DATAAPROVACAO AS DATE)  >= '20241101' 
AND CAST(TMOVAPROVA.DATAAPROVACAO AS DATE)  <= '20241201' 
AND TMOV.STATUS <> 'C'
AND (TITMMOV.QUANTIDADE > 0 OR TITMMOV.QUANTIDADETOTAL > 0)
AND CODTMV IN ('1.1.62','1.1.63')
AND CASE WHEN TMOV.CODTMV = '1.1.66'  THEN (SELECT COUNT(C.IDMOVCTRC) 
						FROM TMOV M (NOLOCK), FCFO F (NOLOCK), TCTRCENTRADA C (NOLOCK) 
						WHERE M.CODCOLCFO = F.CODCOLIGADA AND M.CODCFO = F.CODCFO AND M.CODCOLIGADA = C.CODCOLIGADA 
						AND M.IDMOV = C.IDMOVNF AND C.CODCOLIGADA = TMOV.CODCOLIGADA AND C.IDMOVCTRC = TMOV.IDMOV)
	ELSE 0 END
	 = 0
	 */

) AS T

GROUP BY 
CODCQ,
CODCCUSTO,
FASE,
SUB_CLASSE,
DESC_SUB_CLASSE,
CODGRUPO,
DESC_GRUPO,
DESC_INS,
NOME_FORNECEDOR,
NUMEROMOV,
DATAEMISSAO,
CODTMV,
STATUS,
USUARIOCRIACAO,
CODGRUPO,
DESCRICAO_GRUPO,
DATACRIACAO,
USUARIO_APROVACAO,
DATAAPROVACAO,
DATAPG,
IDMOV,
REFERENCIA_PGTO,
HISTORICO_PGTO,
CODTRF,
DESCTRF,
CODTRF_PAI,
DESCTRFPAI,
T.NOME_PRODUTO,
CODTMV_ORIGEM,
UND_PROD,
QTD,
PRECO_UNIT,
T.CODCOLIGADA,
T.CODCLASSIFICA,
T.ID_REQUISICAO_RMO,
T.CODIGOPRD,
T.NUMEROSEQUENCIAL,
t.cod_cc
) AS GRUPO

ORDER BY DATAPG