/*DECLARE @MES_CONTROLE AS VARCHAR(10) = 'JUN',
		@CODCOLIGADA AS INT = 51,
		@EMPREITEIRO AS VARCHAR(15) = 'F62102';
		*/
			SELECT 
			GRUPO2.IDLAN,
			GRUPO2.ID_LAN_VINC,
			GRUPO2.NUMERODOCUMENTO AS 'NUMERO_NOTA',
			@MES_CONTROLE AS 'MES_CONTROLE',
			'02.125' AS 'LANC_VINC_ORIG',
			'CONTROLE' AS TIPO,
			GRUPO2.CODCCUSTO AS 'CENTRO_DE-CUSTO',
			'ST' AS CLASSE,
			'SERVIÇOS DE TERCEIROS' AS 'DESC_DE_CLASSE',
			'AD' AS 'SUBCLASSE_ORIGINAL',
			'AD' AS 'SUBCLASSE',
			'' AS 'DESCRICAO_SUBCLASSE',		/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			'' AS 'DESCRICAO_GRUPO',			/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			(CASE 
				WHEN GRUPO2.LANC_CLASS_FINANC IN ('02.124', '02.076')  THEN 'MEDIÇÃO'
				WHEN GRUPO2.LANC_CLASS_FINANC = '02.023' THEN 'RETENÇÃO'
				ELSE GRUPO2.LANC_CLASS_FINANC 
				END) AS 'DESCRICAO_INSUMO_ORIGINAL',
			'' AS 'DESCRICAO_INSUMO',			/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			'' AS 'CODIGOPRD',					/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			GRUPO2.LANC_NUM_NOTA AS 'NOTA LANC POSTERIOR',				/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			GRUPO2.CODCFO AS 'OBSERVACAO',
			GRUPO2.FORNECEDOR AS 'NOME_FORNECEDOR',
			GRUPO2.DATABAIXA AS 'DATA_BAIXA',
			'' AS 'UND_PROD',					/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			'' AS 'QTD',						/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			'' AS 'PRECO_UNIT',					/* EM BRANCO POR SOLICITAÇÃO DA ANNA CLARA */
			(GRUPO2.LANC_VALOR_VINC * (-1)) AS 'VALOR_VINCULADO',			/* VIR DO LANÇAMENTO POSTERIOR */
			GRUPO2.LANC_CLASS_FINANC AS 'TIPO_MOV',					/* VIR DO LANÇAMENTO POSTERIOR */
			GRUPO2.LANC_CLASS_FINANC AS 'TIPO_MOV_ORIGEM',					/* VIR DO LANÇAMENTO POSTERIOR */
			GRUPO2.CODCOLIGADA AS 'COLIGADA',
			GRUPO2.MES_ANO_BAIXA AS 'MES_ANO_BAIXA',	
			CONVERT(MONEY,SUM (GRUPO2.ADIANTAMENTO_CX4)) AS 'VLR_ADIANTAMENTO_CX4',
			(SUM (GRUPO2.LANC_VALOR_VINC)* (-1)) AS 'VALOR_VINCULADO_LANC_ORIG'
			FROM (
					SELECT
					FLAN.IDLAN,
					VINC_LAN.IDLAN AS 'ID_LAN_VINC',
                    FORMAT(FLAN.DATABAIXA, 'MMMM/YYYY', 'PT-BR') AS MES_ANO_BAIXA,
					FLANBAIXA.DATABAIXA,
					FLAN.RECCREATEDON,
					FLAN.CODCFO,
					FLAN.CODCOLIGADA,
					FCFO.NOMEFANTASIA AS FORNECEDOR,
					FLAN.CODCCUSTO,
					ISNULL(FLAN.VALORBAIXADO,0) AS ADIANTAMENTO_CX4,
					FLAN.VALORORIGINALBX,
					FLAN.IDMOV,
					FLAN.CODTB2FLX,
					FLAN.NUMERODOCUMENTO,
					/*FLAN.CODTB2FLX AS 'LANC_CLASS_FINANC',*/
					VINC_LAN.NUMERODOCUMENTO AS 'LANC_NUM_NOTA',
					FLANBAIXA.VALORORIGINAL AS 'LANC_VALOR_VINC',
					(SELECT CODTB2FLX
					FROM FLAN AS FLAN1
					WHERE FRELLAN.CODCOLIGADA = FLAN1.CODCOLIGADA AND FRELLAN.IDLAN = FLAN1.IDLAN AND FLAN1.CODTB2FLX IN ('02.124', '02.076','02.023')) AS 'LANC_CLASS_FINANC'

	
					FROM FLAN (NOLOCK)
					LEFT JOIN FTB4						(NOLOCK) ON (FLAN.CODTB4FLX = FTB4.CODTB4FLX AND FLAN.CODCOLIGADA = FTB4.CODCOLIGADA)
					LEFT JOIN FCFO						(NOLOCK) ON (FCFO.CODCOLIGADA = FLAN.CODCOLCFO AND FCFO.CODCFO = FLAN.CODCFO)
					INNER JOIN FLANBAIXA				(NOLOCK) ON (FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA AND FLAN.IDLAN = FLANBAIXA.IDLAN)
					INNER JOIN FRELLAN					(NOLOCK) ON (FLAN.CODCOLIGADA = FRELLAN.CODCOLIGADA AND FLAN.IDLAN = FRELLAN.IDLANREL AND FRELLAN.TIPOREL = 28)
					INNER JOIN FLAN AS VINC_LAN			(NOLOCK) ON	(FRELLAN.CODCOLIGADA = VINC_LAN.CODCOLIGADA AND FRELLAN.IDLAN = VINC_LAN.IDLAN 
																	AND FRELLAN.VALORVINCULO = FLANBAIXA.VALORORIGINAL  /* FEITO PARA IMPEDIR DUPLICIDADE E TRAZER SÓ OS VALORES SELECIONADOS */
																	AND VINC_LAN.CODTB2FLX IN ('02.124', '02.076','02.023'))/* PARA TRAZER OS VALORES DAS NOTAS E CLASSIFICAÇÃO CORRETA DOS LANÇAMENTOS POSTERIORES */

					WHERE
					FLAN.CODTDO IN ('0044')
					AND FLAN.CODCOLIGADA IN (@CODCOLIGADA)
					/*AND FLAN.CODCOLIGADA IN (51)*/
					AND FLAN.CODTB2FLX IN ('02.125')
					AND (FCFO.CODCFO LIKE '%' + @EMPREITEIRO + '%')
					AND FLANBAIXA.DATABAIXA BETWEEN @DATAINI AND @DATAFIM
			) AS GRUPO2
			
			GROUP BY
			GRUPO2.CODCFO,
			GRUPO2.FORNECEDOR,
			GRUPO2.CODCOLIGADA,
			GRUPO2.CODCCUSTO,
			GRUPO2.MES_ANO_BAIXA,
			GRUPO2.CODTB2FLX,
			GRUPO2.LANC_CLASS_FINANC,
			GRUPO2.NUMERODOCUMENTO,
			GRUPO2.DATABAIXA,
			GRUPO2.IDLAN,
			GRUPO2.ID_LAN_VINC,
			GRUPO2.LANC_NUM_NOTA,
			GRUPO2.LANC_VALOR_VINC
	
	ORDER BY 1